### ISSUE TITLE
NTR - retropharyngeal space, parapharyngeal space and peripharyngeal space

### ISSUE THREAD

**Issue by cindyJax** [obophenotype/uberon#1131]
1) 
LABEL: peripharyngeal space 
DEF: the space filled with loose areolar tissue surrounding the pharynx; it is divided into two major divisions, the parapharyngeal space and the retropharyngeal space  (ISBN:0683400088) 
DBX_REF: FMA:84964
SUBCLASS OF: anatomical space UBERON:0000464

Subclasses of above term:
2) 
LABEL: parapharyngeal space
DEF:  The portion of the peripharyngeal space limited by the lateral wall of the pharynx, the cervical vertebrae and medial pterygoid muscle.
SYN: pharyngomaxillary space (ISBN:0683400088); lateral pharyngeal space (FMA:55081)
DBX_REF: FMA:55081

3) 
LABEL: retropharyngeal space
DEF:  The portion of the peripharyngeal space that is located posterior to the pharynx. (ISBN:0683400088)
SYN: Henke's space (ISBN:0683400088) , postpharyngeal space (ISBN:0683400088) 
DBX_REF: FMA:84965

**Comment by cmungall** [comment]
FMA has both space and compartment terms

Do you definitely want space and not compartment? What qualities will be 
attached? Spaces can't have mass, genes expressed in them… but shape 
and size are perfectly fine

spaces are also better defined w.r.t. compartment. The space ends in the 
wall. The boundaries of the compartment may not be clear, but for uberon 
we could define as being the entire wall plus the space.

**Comment by cindyJax** [comment]
I have some edema terms that need the corresponding anatomy- retropharyngeal edema for example.  The space is filled with an excess of watery or serous fluid.  So 'space' appears to be the right anatomy term in these instances.

________________________________
