### ISSUE TITLE
NTR: paraumbilical vein

### ISSUE THREAD

**Issue by cindyJax** [obophenotype/uberon#1134]
The paraumbilical veins are a set of small veins, so the term label may need to be 'set of paraumbilical veins' ?

Label: paraumbilical vein
Def: The small superficial veins that arise from the cutaneous veins, and run from the umbilicus along the round ligament of the liver; these terminate as accessory portal veins in the liver. [ ISBN:0683400088 and PMID:7400038 ]
Subclass of: vein [UBERON:0001638]

**Comment by cmungall** [comment]
I prefer singular as the primary label, but we have the FMA set nomenclature in there as a syn
