### ISSUE TITLE
term requests - craniofacial

### ISSUE THREAD

**Issue by markengelstad** [obophenotype/uberon#1140]
new term requests: structures or classes needed for logical definitions of new HPO classes

tensor veli palatini muscle
musculature of soft palate
Stylopharyngeus muscle(part of musculature of pharynx)
Salpingopharyngeus muscle (part of musculature of pharynx)
Superior constrictor muscle (part of musculature of pharynx)
middle constrictor muscle (part of musculature of pharynx)
inferior constrictor muscle (part of musculature of pharynx)
platsyma muscle is also a subclass of deep cervical fascia of neck
muscle of facial expression
levator labii superioris alaeque nasi

**Comment by RDruzinsky** [comment]
Chris, most of these are in the MFMO. I can add the middle and inferior
constrictors. I will think about the muscles of facial expression and
fascia.
Best,
Robert

**Comment by cmungall** [comment]
All of these are in uberon, see 
http://monarchinitiative.org/annotate/text/?q=tensor+veli+palatini+muscle%0D%0Amusculature+of+soft+palate%0D%0AStylopharyngeus+muscle%28part+of+musculature+of+pharynx%29%0D%0ASalpingopharyngeus+muscle+%28part+of+musculature+of+pharynx%29%0D%0ASuperior+constrictor+muscle+%28part+of+musculature+of+pharynx%29%0D%0Amiddle+constrictor+muscle+%28part+of+musculature+of+pharynx%29%0D%0Ainferior+constrictor+muscle+%28part+of+musculature+of+pharynx%29%0D%0Aplatsyma+muscle+is+also+a+subclass+of+deep+cervical+fascia+of+neck%0D%0Amuscle+of+facial+expression%0D%0Alevator+labii+superioris+alaeque+nasi&longestOnly=true


I think Mark is having issues with import modules in HPO
