### ISSUE TITLE
term request: common carotid artery

### ISSUE THREAD

**Issue by markengelstad** [obophenotype/uberon#1141]
the root of the carotid arterial system 
no discrete class for 'common carotid artery' alone exist in uberon.

carotid artery plus branches was deprecated (and different than common carotid artery)

https://en.wikipedia.org/wiki/Common_carotid_artery

**Comment by cmungall** [comment]
Not deprecated in uberon:

[UBERON:0001530](http://purl.obolibrary.org/obo/UBERON_0001530) ! common carotid artery plus branches

**Comment by cmungall** [comment]
Is this what you need?

[UBERON:0005396](http://purl.obolibrary.org/obo/UBERON_0005396) ! carotid artery segment

Apologies for the over-zealous formality in the names. New suggestions welcome

**Comment by markengelstad** [comment]
that's close -- 
in ontobee, i can see this class, which is best (UBERON_0010197) Trunk of Common Carotid Artery

But that class doesn't show up in the hp-edit.owl (github) version of UBERON

What does that mean?

**Comment by cmungall** [comment]
@nicolevasilevsky can you help Mark with the module generation in HP?

**Comment by nicolevasilevsky** [comment]
Sebastian showed me how to change my catalog file so it imported all of Uberon, @markengelstad can you ask him how to do it? Or I can help you MIREOT the term after I'm back from vacation.

**Comment by cmungall** [comment]
I think @drseb may be unavailable for a few weeks...

We really need to make a youtube video showing how this is done! I was just showing @pbuttigieg how to do this for ENVO. But every ontology is a little different.

**Comment by drseb** [comment]
@cmungall I will start working tomorrow again, but not with full force. 

@cmungall @markengelstad @nicolevasilevsky 
I hope I can join the call on thursday. Let's discuss it then. It is not as easy with the github structure as it was with googlecode structure. (We do not have a catalog-xml per default)

**Comment by RDruzinsky** [comment]
Care must be taken when defining the carotid arterial system in Uberon, to
avoid being anthropocentric. Although humans and many other mammals have
paired common carotids, the left and right common carotids arise from
different arteries. In some mammals, there is an unpaired "common" common
carotid that arises from the aorta that branches into symmetrical left and
right common carotids, but this is just one of the many patterns seen in
mammals. To me, what is very interesting is that many of the variations
seen in humans are the same patterns seen in the other mammalian clades.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by uberon** [comment]
Yes, I think this area needs some work. The current representation is 
based on Kardong. However, any mistakes are probably mine, and the 
overview in Kardong may miss out key variations.

What I would like to do is to assemble the correct branching graph for a 
number of key species and to obtain the correct uberon generalization 
from these
