### ISSUE TITLE
Advice to compute taxon constraints for taxa with lots of unsatisfiable classes

### ISSUE THREAD

**Issue by fbastian** [obophenotype/uberon#1144]
I try to compute taxon constraints using the SpeciesSubsetterUtil of owltools, it works well, but for some taxa, it fails because of OutOfMemoryErrors, e.g., for Porifera or Tunicata, even with 400 Gb of memory used.

I know this is a known issue of Elk when there are lots of unsatisfiable classes, but maybe you would have some advices to reduce the memory consumption? 
For instance, would that help to remove more relations, and which ones? Or to remove immediately some classes (e.g., species-specific ontology terms of unrelated species)? To reduce/increase number of Elk workers?

Any advice to be able to compute these taxon constraints on a 500Gb-server would be appreciated :p

**Comment by cmungall** [comment]
No magic solutions.

You could try doing this iteratively: make a non-human subset, then non-mammalian, then non-vertebrate - by now you have a much smaller (and I would expect less "relation-dense" set)

But if you're going to start encoding the logic procedurally then we may as well go back to the graph-traversal approach, sorry - it seems the idea of subsetting by unsatisfiability is elegant but not scalable. Before giving up we could try approaching the Elk developers as they may find this an interesting problem.

**Comment by balhoff** [comment]
Does this involve lots of queries with anonymous expressions? I have experienced problems with memory explosion on datasets that Elk can classify with no problem. It is related to deletion of temporary inferences after the query. See https://code.google.com/p/elk-reasoner/issues/detail?id=28

I don't know if it applies in this case but the problem can be worked around by adding the query expression with generated IRIs, and then querying using the IRIs only.

**Comment by cmungall** [comment]
@hdietze has noted a similar problem in the past (cc @dosumis who was skeptical this was an issue).

In this case the issue is caused by our strategy of rendering entire taxa membership unsatsfiable and then removing all unsatisfiable classes. A sort of brutal logic-based form of extinction. Time to rethink.

**Comment by fbastian** [comment]
I like the idea of doing this iteratively. But actually, the SpeciesSubsetterUtil can be used to make a human subset, or a vertebrate subset, but not a non-human or a non-vertebrate subset, etc. The Porifera/Tunicata classes would go away.

Am I missing anything, or should I implement this myself?

**Comment by cmungall** [comment]
@fbastian you're right it's not so simple. 

I'm desperate to refactor some of this myself but am unlikely to for the next few weeks so have at it, do you want to post your plan here first?

**Comment by fbastian** [comment]
@balhoff did you get a chance to test the version of elk provided in the last message of the issue you linked to? This is indeed very similar to what I see (JVM stuck in garbage collection). 

Also, could you have a look at `owltools.mooncat.SpeciesSubsetterUtil#removeOtherSpecies()` and see if your strategy could be applied? Should we make `OWLSubClassOfAxiom qax` a named class, or something like that? Or am I completely missing the point? :p

@cmungall, don't you think it could be a related problem?

**Comment by balhoff** [comment]
@fbastian no, at the time I was too busy and I had already put in place a system for inserting named classes for my queries. So I have never gotten around to testing it again.

**Comment by fbastian** [comment]
So, to generate a non-xxx subset, I was thinking of an easy to implement (but slow to compute) solution: for instance, to generate a non-craniata subset, the principle would be to generate a subset for craniata, and a subset for each of its siblings (i.e., Cephalochordata and Tunicata); The terms that are uniquely present in the craniata subset, but not in any of the sibling subsets, would be craniata specific; removing them will lead to have a non-craniata subset.

Would that be correct? Would you have a better idea?

**Comment by fbastian** [comment]
Another try, reasoner-based approach, example for a non-human subset: 
* add axiom `(in taxon some NCBITaxon:9606 "human") DisjointWith (in taxon some NCBITaxon:1 "root")`
* add axiom `OWL:Thing SubClassOf (in taxon some NCBITaxon:1 "root")`

=> unsatisfiable classes are human specific. 

@cmungall, what do you think?

Also, maybe the computation would be easier for the reasoner if we used a new class rather than NCBITaxon:1? i.e.: 
* add a new class `FakeClass`
* add axiom `(in taxon some NCBITaxon:9606 "human") DisjointWith (in taxon some FakeClass)`
* add axiom `OWL:Thing SubClassOf (in taxon some FakeClass)`
* remove `FakeClass`

**Comment by cmungall** [comment]
I think this would work

The concern is that you are embedding a lot of logic into procedural code. The intent of the OWL reasoning based method was to have things entirely driven by ontology axioms and reasoning. If we are going to do procedural code, the original graph-based method is more appealing

**Comment by cmungall** [comment]
To make a non-human subset you could just do `(in taxon some Homo sapiens) SubClassOf Nothing` and remove unsats.

I think this may what you're getting at with the second method.

**Comment by fbastian** [comment]
Oh yes, thanks. This was so easy :p

**Comment by fbastian** [comment]
It works like a charm! I tried with 50Gb of memory. Mostly, it is removing the vertebrate-specific structures that is problematic, so it is really needed to first filter structures specific to sub-taxa before removing the vertebrate-specific. 

For instance, to generate constraints for Tunicata, I first filtered out, in order: mammals, amniota, tetrapoda, sarcopterygii, gnathostomata, vertebrata.

**Comment by fbastian** [comment]
Leaving an additional piece of information: Teleostomi really seems to be the pivot, as soon as a taxon is not a descendant nor an ancestor of Teleostomi, the reasoner fails (e.g., it also fails for Chondrichthyes).
