### ISSUE TITLE
NCIt cross reference

### ISSUE THREAD

**Issue by CatherineLeroy** [obophenotype/uberon#1149]
Hello, 

As a programmer at the EBI in the SPOT team I am working on updating our cross references to other ontologies. 
Of course we import lots of anatomy term from UBERON which have cross references themselves. 
I have noticed that in the database_cross_reference section of UBERON terms, you have those type of cross references : 
 http://ncicb.nci.nih.gov/xml/owl/EVS/Accumbens_Nucleus
When I click those, I get a 404: Page Not Found exception.
Exemple there : http://www.ontobee.org/browser/rdf.php?o=UBERON&iri=http://purl.obolibrary.org/obo/UBERON_0001882

Are those the NCIt cross references? 

If they are why do you choose to use the label rather then the IRI (http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C52733) or term id as you seem to do for other cross references?

Thank you very much in advance for your time! :-)
Catherine Leroy
cleroy@ebi.ac.uk

**Comment by cmungall** [comment]
Thanks Catherine

I confirmed with the NCIT developers that the latter form is the correct one (they used to make the URIs include the labels, but this stopped about 5 years ago, and we have been tracking it since)

The xrefs will be switched to the correct URIs in the nexr release

**Comment by CatherineLeroy** [comment]
On 21 Sep 2015, at 18:38, Chris Mungall <notifications@github.com> wrote:

> Thanks Catherine
> 
> I confirmed with the NCIT developers that the latter form is the correct one (they used to make the URIs include the labels, but this stopped about 5 years ago, and we have been tracking it since)
> 
> The xrefs will be switched to the correct URIs in the nexr release
> 
> 
Then we won’t have to change them on our side. 
Great! 
Thanks,
Catherine
