### ISSUE TITLE
a few xrefs that might need updating

### ISSUE THREAD

**Issue by CatherineLeroy** [obophenotype/uberon#1150]
Hello, 
Me again. 
Still working on updating the cross reference in EFO ontology, I had a look through a tiny part of you terms (285). 
I have put a list of changes I would suggest below. However, I might not have them all right. Let me know if you agree on some of them. 

http://purl.obolibrary.org/obo/UBERON_0001772   corneal epithelium  SNOMEDCT:15775008(Structure of corneal epithelium) to be replaced by SNOMEDCT:368825001(All corneal epithelium)

http://purl.obolibrary.org/obo/UBERON_0001621   uterine cervix  SNOMEDCT:245494008(Entire cervical canal)  to be replaced by  SNOMEDCT:181453009 (Entire cervix uteri)

http://purl.obolibrary.org/obo/UBERON_0001691   external ear   SNOMEDCT:181176000(COULD NOT FIND IT IN BIOPORTAL) to be replaced by    SNOMEDCT:420893000(Entire external ear)

http://purl.obolibrary.org/obo/UBERON_0001870   frontal cortex  SNOMEDCT:180920004(Entire frontal lobe) to be replaced by   SNOMEDCT:314140006(Region of frontal cortex)

http://purl.obolibrary.org/obo/UBERON_0003894   liver primordium    NCI_Thesaurus:Hepatic_Cord,NCI_Thesaurus:Primordium_of_the_Liver    to be replaced by   NCIt:C34277(Primordium of the Liver)
http://purl.obolibrary.org/obo/UBERON_0002028   hindbrain  could  add : SNOMEDCT/303456008 (Hindbrain structure)

http://purl.obolibrary.org/obo/UBERON_0000079   male reproductive system    NCI_Thesaurus:Male_Genitalia,NCI_Thesaurus:Male_Reproductive_System to be replaced by   NCIt:C12722(Male Reproductive System)

http://purl.obolibrary.org/obo/UBERON_0002374   metacarpal bone SNOMEDCT:425761003(Entire metacarpal of finger) to be replaced by  SNOMEDCT:181977005(Entire metacarpal)

http://purl.obolibrary.org/obo/UBERON_0001211 Peyer's patch NCI_Thesaurus:Mouse_Peyer_s_Patches,NCI_Thesaurus:Peyer_s_Patch  to be replaced by  NCIt:C12771(Peyer Patch)
http://purl.obolibrary.org/obo/UBERON_0000004   remove EFO:0000828 which is now obsolete

http://purl.obolibrary.org/obo/UBERON_0001890   forebrain   NCI_Thesaurus:Prosencephalon,NCI_Thesaurus:Fore-Brain to be replaced by   NCIt:C40185(Forebrain)

http://purl.obolibrary.org/obo/UBERON_0002372   tonsil        NCI_Thesaurus:Tonsilar_Tissue,NCI_Thesaurus:Tonsillar_Lymphoid_Tissue,NCI_Thesaurus:Tonsil  to be replaced by  NCIt:C12802(tonsil)

http://purl.obolibrary.org/obo/UBERON_0006860   swim bladder    SNOMEDCT:64748009(not found in bioportal), so I would just drop this xref.

Thanks in advance for your time!
Catherine Leroy
cleroy@ebi.ac.uk

**Comment by cmungall** [comment]
> http://purl.obolibrary.org/obo/UBERON_0001772 corneal epithelium SNOMEDCT:15775008 ! Structure of corneal epithelium to be replaced by SNOMEDCT:368825001 ! All corneal epithelium

Done, thanks!

> http://purl.obolibrary.org/obo/UBERON_0001621 uterine cervix SNOMEDCT:245494008 ! Entire cervical canal to be replaced by SNOMEDCT:181453009  ! Entire cervix uteri

Done!

> http://purl.obolibrary.org/obo/UBERON_0001691 external ear SNOMEDCT:181176000 ! COULD NOT FIND IT IN BIOPORTAL to be replaced by SNOMEDCT:420893000 ! Entire external ear

Ah yes, I see, marked as deprecated here:
http://www.snomedbrowser.com/Codes/Details/181176000 DEPRECATED

With the replacement you suggest

> http://purl.obolibrary.org/obo/UBERON_0001870 frontal cortex SNOMEDCT:180920004 ! Entire frontal lobe to be replaced by SNOMEDCT:314140006 ! Region of frontal cortex

Hmm, a valid concept here:

http://www.snomedbrowser.com/Codes/Details/180920004

I really have no idea how term versioning works with SNOMED, and which version is where

It would be great to see a decent SNOMED browser in the new OLS but that may prove difficult with their annoying licensing

> http://purl.obolibrary.org/obo/UBERON_0003894 liver primordium NCI_Thesaurus:Hepatic_Cord,NCI_Thesaurus:Primordium_of_the_Liver to be replaced by NCIt:C34277 ! Primordium of the Liver

Done!

> http://purl.obolibrary.org/obo/UBERON_0002028 hindbrain could add : SNOMEDCT/303456008  ! Hindbrain structure

Done!

Odd that SNOMED doesn't have an `E` for this. Ah, gotta love the SEP pattern

> http://purl.obolibrary.org/obo/UBERON_0000079 male reproductive system NCI_Thesaurus:Male_Genitalia,NCI_Thesaurus:Male_Reproductive_System to be replaced by NCIt:C12722 ! Male Reproductive System

Done!

> http://purl.obolibrary.org/obo/UBERON_0002374 metacarpal bone SNOMEDCT:425761003 ! Entire metacarpal of finger to be replaced by SNOMEDCT:181977005 ! Entire metacarpal

I prefer to keep both and implicitly merge the concepts. 

i.e. keep
```
xref: SCTID:181977005 ! Entire metacarpal
xref: SCTID:425761003 ! Entire metacarpal of finger
```

This must be a mistake in SCTID:
http://www.snomedbrowser.com/Codes/Details/181977005

all metacarpals are finger-associated. Maybe the more general one is intendend to be metapodium?

> http://purl.obolibrary.org/obo/UBERON_0001211 Peyer's patch NCI_Thesaurus:Mouse_Peyer_s_Patches,NCI_Thesaurus:Peyer_s_Patch to be replaced by NCIt:C12771 ! Peyer Patch

Done!

> http://purl.obolibrary.org/obo/UBERON_0000004 remove EFO:0000828 which is now obsolete

Done!

What, EFO has no nose? How does it smell?

> http://purl.obolibrary.org/obo/UBERON_0001890 forebrain NCI_Thesaurus:Prosencephalon,NCI_Thesaurus:Fore-Brain to be replaced by NCIt:C40185 ! Forebrain

Done!

> http://purl.obolibrary.org/obo/UBERON_0002372 tonsil NCI_Thesaurus:Tonsilar_Tissue,NCI_Thesaurus:Tonsillar_Lymphoid_Tissue,NCI_Thesaurus:Tonsil to be replaced by NCIt:C12802 ! tonsil

Done!

**Comment by CatherineLeroy** [comment]
> I really have no idea how term versioning works with SNOMED, and which version is where
> 
> 
> It would be great to see a decent SNOMED browser in the new OLS but that may prove difficult with their annoying licensing
> 
> 
Might be difficult!
> 
> http://purl.obolibrary.org/obo/UBERON_0002374 metacarpal bone SNOMEDCT:425761003 ! Entire metacarpal of finger to be replaced by SNOMEDCT:181977005 ! Entire metacarpal
> 
> I prefer to keep both and implicitly merge the concepts.
> 
> i.e. keep
> 
> xref: SCTID:181977005 ! Entire metacarpal
> xref: SCTID:425761003 ! Entire metacarpal of finger
> This must be a mistake in SCTID:
> http://www.snomedbrowser.com/Codes/Details/181977005
> 
> all metacarpals are finger-associated. Maybe the more general one is intendend to be metapodium?
> 
> 
Metacarpe is used in mammals (porc, horses) too and those don’t have ‘fingers’. Maybe finger metacarpe is more specific to humans?
> http://purl.obolibrary.org/obo/UBERON_0001211 Peyer's patch NCI_Thesaurus:Mouse_Peyer_s_Patches,NCI_Thesaurus:Peyer_s_Patch to be replaced by NCIt:C12771 ! Peyer Patch
> 
> Done!
> 
> http://purl.obolibrary.org/obo/UBERON_0000004 remove EFO:0000828 which is now obsolete
> 
> Done!
> 
> What, EFO has no nose? How does it smell?
> 
> 
;-) We smell thanks to Uberon. (we import your term)

Thanks for the update!
Cheers,
Catherine
