### ISSUE TITLE
Stroma of mammary gland

### ISSUE THREAD

**Issue by nursatranscriptomine** [obophenotype/uberon#1151]
Looking for an Uberon identifier for stroma of the mammary gland - I see stroma listed for many other organs but not that one....thanks

**Comment by cmungall** [comment]
we have this:

 [UBERON:0003584](http://purl.obolibrary.org/obo/UBERON_0003584) ! mammary gland connective tissue

"The fibrous supportive tissue of the mammary gland."

should we add a synonym? Or can we distinguish the concepts (as in FMA?)

**Comment by nursatranscriptomine** [comment]
I think there's an argument for discriminating between the concepts - connective tissue implies a more passive role in mammary gland biology than the stroma actually has - there's a fair amount of evidence documenting stromal-epithelial interactions, for example,  http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2941044/

**Comment by cmungall** [comment]
Do we need to discriminate between the concepts at the level of the mammary gland? It sounds like we should stick with the existing ID, possibly relabel it, and make it clear in the definition that it is non-passive?

As far as discriminating the generic stroma class from connective tissue - interesting that you indicate stroma indicates a more active role. Our current def: *"Connective, non-functional supportive framework of a biological cell, tissue, or organ. Contrast with parenchyma."*

**Comment by nursatranscriptomine** [comment]
Thanks.

My comments were intended to apply to the mammary stroma only, I am less familiar with the literature relating to other organs.

**Comment by cmungall** [comment]
so are you ok with rolling mammary stroma and mammary connective tissue into one?

**Comment by nursatranscriptomine** [comment]
Yes that makes sense

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Sep 23, 2015 at 2:26 PM -0700, "Chris Mungall" <notifications@github.com<mailto:notifications@github.com>> wrote:


so are you ok with rolling mammary stroma and mammary connective tissue into one?

-
