### ISSUE TITLE
Suggestion: Stellate cells as a subclass of pancreas

### ISSUE THREAD

**Issue by nursatranscriptomine** [obophenotype/uberon#1153]
Stellate cells are a cell type in the pancreas.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC524499/

**Comment by cmungall** [comment]
This is more an issue for the cell ontology tracker here: https://github.com/obophenotype/cell-ontology/issues

we have

 * [CL:0000117](http://purl.obolibrary.org/obo/CL_0000117) ! CNS neuron (sensu Vertebrata)
    * [CL:0000122](http://purl.obolibrary.org/obo/CL_0000122) ! stellate cell  
         *  [CL:0010010](http://purl.obolibrary.org/obo/CL_0010010) ! cerebellar stellate cell
         * [CL:2000090](http://purl.obolibrary.org/obo/CL_2000090) ! dentate gyrus of hippocampal formation stellate cell [DEF: "Any stellate cell that is part of a dentate gyrus of hippocampal form

I think CL_0000122 should be relabeled 'neural stellate cell' or similar. We can then add a distinct pancreatic stellate cell

we *could* have a grouping for both based on morphology. Is there a deeper connection? The paper indicates that there may be a connection in lineage but I haven't read it

**Comment by cmungall** [comment]
I just realized we have: [CL:0002410](http://purl.obolibrary.org/obo/CL_0002410) ! pancreatic stellate cell

So I think the action is to relabel  CL:0000122

**Comment by nursatranscriptomine** [comment]
Ah – I was looking under pancreas rather than pancreatic….

**Comment by cmungall** [comment]
What browser do you use?

**Comment by nursatranscriptomine** [comment]
Chrome

**Comment by cmungall** [comment]
Ah yes - but do you use an ontology browser like ontobee, bioportal, ols...? or look at the ontology in protege?

**Comment by nursatranscriptomine** [comment]
I see – yes, Ontobee

**Comment by cmungall** [comment]
OK, thanks. Some browsers don't handle synonym search well but in this case, the right synonym was missing from CL (I added it). 

In the next CL release CL:0000122 will be called 'stellate neuron'

**Comment by nursatranscriptomine** [comment]
Thanks!
