### ISSUE TITLE
Definition typo parietal-supraoccipital

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1155]
change "endodermal" to "endochondral" in definition:

Term IRI: http://purl.obolibrary.org/obo/UBERON_2001997
definition: Compound dermal and endochondral bone that results from the fusion of the paired dermal parietal bones and the median endodermal supraoccipital. Forms the dorso-posterior element of the dermatocranium.

**Comment by cmungall** [comment]
Fixed in r4190
