### ISSUE TITLE
muscle of facial expression

### ISSUE THREAD

**Issue by markengelstad** [obophenotype/uberon#1156]
I'm requesting uberon class 'muscle of facial expression'.
A useful concept in the HPO 'abnormality of muscle of facial expression'.
These muscles include http://www.getbodysmart.com/ap/muscularsystem/expression/menu/menu.html

many other hpo classes exist that refer to muscles and facial expression, and none of them are logically modeled.  i'm assuming the lack of logical modeling is, in part, due to a lack of 'musc of facial expression' class.  

or perhaps there's a way to logically model HP:0005346 [abnormal facial expression]

**Comment by mellybelly** [comment]
organismal level process/function.... GO? @RDruzinsky ?

**Comment by markengelstad** [comment]
for uberon, is 'muscle of facial expression' (defined as a muscle innervated by the cranial nerve (facial nerve) that alters the facial expression)  too 'human centric'?

**Comment by cewall** [comment]
No. They are also muscles of facial expression in mammals.

Chris Wall

**Comment by cmungall** [comment]
I think we're good on the uberon side?
