### ISSUE TITLE
adding reflexivity to part_of causes unsatisfiable classes

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#1159]
The *part_of* property used in Uberon is not marked as reflexive, nor is it in the current RO. However my recollection is that it used to be considered reflexive by RO, and I have been relying on that behavior in queries for a long time. When *part_of* is marked reflexive in http://purl.obolibrary.org/obo/uberon/releases/2015-09-27/ext.owl, it results in 17 unsatisfiable classes. Is *part_of* intentionally non-reflexive?

**Comment by cmungall** [comment]
Intentionally non-gloabally-reflexive:
https://github.com/oborel/obo-relations/wiki/ROGuideDraft#local-reflexivity

We can add local reflexivity… but that would help you neither with 
your queries nor with replicating your error, assuming Elk.

Any suggestions? Local axioms for phenoscape? part-of is the one OP it 
is probably safe to do global reflexivity on, as it applies to pretty 
much any upper category in my view (BFO may be undercommitted here, need 
to check)

**Comment by balhoff** [comment]
Thanks, I missed that. Yes, I should have said the results were with Elk. I currently have a file used in the Phenoscape KB that makes sure the object properties have expected characteristics, but I should take out reflexive part_of if there are going to be Uberon axioms that conflict with that. I think mostly it's just a matter of making sure I have "A or part_of some A" everywhere I am currently just using "part_of some A".

**Comment by uberon** [comment]
I'd still like to investigate… if the logical incoherencies are 
biological ones we can at least retain this as a test

**Comment by cmungall** [comment]
Unsats:

![screen shot 2015-10-09 at 1 06 09 pm](https://cloud.githubusercontent.com/assets/50745/10404299/8b4b61b4-6e86-11e5-84cf-ee5a4c265c89.png)

Feather issue:

![screen shot 2015-10-09 at 1 07 17 pm](https://cloud.githubusercontent.com/assets/50745/10404326/b37cbc78-6e86-11e5-9fef-699d419ace93.png)

VT nucleus:

![screen shot 2015-10-09 at 1 08 10 pm](https://cloud.githubusercontent.com/assets/50745/10404342/d3ac7f10-6e86-11e5-8bd8-7175c95e8144.png)

Thymoid:

![screen shot 2015-10-09 at 1 08 54 pm](https://cloud.githubusercontent.com/assets/50745/10404354/ec31e8b8-6e86-11e5-9ad5-5e285cbe9be0.png)

Another nucleus:

![screen shot 2015-10-09 at 1 09 32 pm](https://cloud.githubusercontent.com/assets/50745/10404370/0628910e-6e87-11e5-9406-a5f98b76d1f1.png)

These are bona-fide ontology issues, looks like some axioms are too strong. Thanks!

**Comment by cmungall** [comment]
See also #1305
