### ISSUE TITLE
pericardium layers logic issue

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1166]
I think we should offer a prize to anyone who can figure this one out:

<img width="1234" alt="screen shot 2015-10-27 at 11 40 23 pm" src="https://cloud.githubusercontent.com/assets/50745/10781533/31a7dfba-7d05-11e5-827d-95f6dd1afb87.png">

**Comment by dosumis** [comment]
At a guess, there's an inference somewhere that

'pariteal serous percardium' SubClassOf 'visceral serous paricardium' or
vice versa.  Combine with with the reflexive part_of relation and the
disjointness axiom and you an inconsistency.  In the absence of
instantiated inference, it should be possible to find an explanation on an
inference of this (or some intermediate class).  Would probably need to
temporarily remove an axiom to get something consistent to reason with to
test.

**Comment by cmungall** [comment]
You're quite right. 

In fact, none of the SubClassOfs in the above are instantiated-inferreds. However, the assertion of superclass to a grouping like 'cavity lining' is the kind of thing that *should* be inferred. In fact, cavity lining is a dubious kind of grouping (what is the lining? Is it just the epithelium? connective tissue too?)

Investigating this lead to a number of longstanding fixes in serous membranes and cavities (see #86). This included obsoleting 'cavity lining' and using in its place better defined concepts like serous sacs and membranes.

**Comment by cmungall** [comment]
Fixed with latest commits on #86
