### ISSUE TITLE
ribs and postcranial skeletal system

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1167]
Please add a part_of relationship between the rib terms and the postcranial axial skeletal system (see def below)

The post-cranial subdivision of skeleton structural components forming the long axis of the vertebrate body; in Danio, consisting of the notochord, vertebrae, ribs, supraneurals, intermuscular bones, and unpaired median fins; in human consists of the bones of the vertebral column, the thoracic cage and the pelvis[ZFA+FMA].

**Comment by uberon** [comment]
Related Q: FMA says ribs are long bones, but this contradicts the VSAO 
supplied def of long bone. I'll take VSAO def as primary here but more 
context would be beneficial.

def: "Long bone is a limb bone that is subcylindrical and has a shaft 
with periosteum separating the ends of the bones. Long bones are present 
only in the limbs[VSAO:wd]." [VSAO:wd, Wikipedia:Long_bone, 
https://github.com/obophenotype/uberon/issues/32]
