### ISSUE TITLE
new term request: apex of left ventricle

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1169]
Hi Chris,

for GTEx annotation, 

'apex of left ventricle'

would be useful

http://www.vhlab.umn.edu/atlas/left-ventricle/apex/

Tentative definition:

The apex of the cardiac left ventricle located at the bottom of the left ventricle inferior to both the mitral and aortic valve.

(and same for 'apex of right ventricle' BTW ?)

Mouse ontology has a general term:
[Term]
id: MA:0003017
name: apex of heart ventricle (Mus)
synonym: "apex of cardiac ventricle" RELATED []
relationship: part_of UBERON:0002082 ! cardiac ventricle

Many thanks.
Cheers,

Anne

**Comment by cmungall** [comment]
We currently model apexes of the heart as points. This is not so useful for gene expression. I assume that what you need is more along the lines of an apical zone, centered around the apex, extending some undefined distance?

**Comment by ANiknejad** [comment]
Hi Chris,
I just wanted to report as much precise as possible the information available from GTEx, but maybe yes, here I was too much enthousiastic, Thank you for your patience.
Anne

**Comment by cmungall** [comment]
No worries. Should we create a class for apical region?

**Comment by ANiknejad** [comment]
yes, please, it would be fine for GTEx annotation, many thanks
