### ISSUE TITLE
songbird Area X 

### ISSUE THREAD

**Issue by michaelerice** [obophenotype/uberon#1171]
Request for basal ganglion(UBERON:0002420) to include Area X as child term. 
definition: Area X is a basal ganglia nucleus of songbirds

only_in Passeriformes Taxon ID 9126

PMID: 18398825
PMID: 15116398

GOC:mr

**Comment by cmungall** [comment]
Done! See linked commit message above.

**Comment by michaelerice** [comment]
?much obliged


________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Sciences
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________
