### ISSUE TITLE
Death as a process boudary

### ISSUE THREAD

**Issue by aellenhicks** [obophenotype/uberon#1172]
We made the following request on OGMS, and they suggested we post it here. 
"We propose the following definition of 'death' - A process boundary that occupies the latest instant occupied by a life course."

We are looking for something that is modelled as a process boundary to distinguish it from processes that have more than one instant. Unfortunately, 'death stage' seems to be too broad since it does not specify that it is a boundary.

Is it possible to have a subclass of 'death' that specifies that it is a process boundary?

More information about the history of this request can be found here:
https://github.com/OGMS/ogms/issues/95#issuecomment-155462219

**Comment by cmungall** [comment]
You can't see the equivalence axiom in OntoBee but it's defined as simultaneous with [GO:0016265](http://purl.obolibrary.org/obo/GO_0016265) ! death, which is a process (file a ticket on the GO tracker for objections)

I'm open to adding life-death boundary and adding a synonym for OGMS of 'death'. This would be a process boundary.

**Comment by mellybelly** [comment]
agree, death is both a process and a stage boundary, maybe the stage can be called “time of death” CSI style


On Nov 10, 2015, at 7:03 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:


You can't see the equivalence axiom in OntoBee but it's defined as simultaneous with GO:0016265<http://purl.obolibrary.org/obo/GO_0016265> ! death, which is a process (file a ticket on the GO tracker for objections)

I'm open to adding life-death boundary and adding a synonym for OGMS of 'death'. This would be a process boundary.

—
Reply to this email directly or view it on GitHub<https://github.com/obophenotype/uberon/issues/1172#issuecomment-155607944>.

Dr. Melissa Haendel

Associate Professor
Ontology Development Group, OHSU Library
www.ohsu.edu/library/ontology<http://www.ohsu.edu/library/ontology>
Department of Medical Informatics and Clinical Epidemiology
Oregon Health & Science University
haendel@ohsu.edu<mailto:haendel@ohsu.edu>
skype: melissa.haendel
503-407-5970

**Comment by aellenhicks** [comment]
I'm always up for CSI-inspired labels! But I think in this case time (as a measurement or index) is different from a moment which, in turn, is different from a boundary of a process. The process boundary isn't just a point in time; it is also a part of the process that begins/ends and so depends on the process in a way that times and moments do not.


Amanda Hicks, PhD
Assistant Professor, Health Outcomes & Policy
College of Medicine
University of Florida
CTRB 3226
PO Box 100219
2004 Mowry Road
Gainesville, FL  32610
p: (352) 294-5932<tel:%28352%29%20294-4197>
f: (352) 273-8703<tel:%28352%29%20273-8703>
aehicks@ufl.edu<mailto:hoganwr@ufl.edu>
________________________________

**Comment by cmungall** [comment]
How soon is this needed? I'd like to have boundaries integrated into the RO temporal interval calculus before adding process boundaries

**Comment by aellenhicks** [comment]
We can wait for death.  Thanks, Chris.

**Comment by aellenhicks** [comment]
We were hoping we could wait for death, but it turns out death can't wait
for us. :) Do you think we could this issue resolved shortly?

Thanks, Amanda

On Thu, Nov 19, 2015 at 11:34 PM, Chris Mungall <notifications@github.com>
wrote:

> How soon is this needed? I'd like to have boundaries integrated into the
> RO temporal interval calculus before adding process boundaries
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/obophenotype/uberon/issues/1172#issuecomment-158276898>
> .
>



-- 
Amanda Hicks, PhD
Assistant Professor, Health Outcomes & Policy
College of Medicine
University of Florida
CTRB 3226
PO Box 100219
2004 Mowry Road
Gainesville, FL  32610
p: (352) 294-5932 <%28352%29%20294-4197>
f: (352) 273-8703
aehicks@ufl.edu <hoganwr@ufl.edu>

**Comment by aellenhicks** [comment]
Just following up. If we could have something in the next two weeks, it would help our projects. Thanks!
