### ISSUE TITLE
new term request: lower esophagus muscularis layer

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1176]
Hi Chris,

To define the muscle layer of the lower part of the esophagus
(GTEx talks about 'Esophagus -muscularis	Squamous region above GE junction')

it would be useful to have

'lower esophagus muscularis layer'

with definition like that:
def: "A muscle layer that is part of the lower one third of the esophagus wall

see
UBERON:0011878 muscle layer of esophagus
and
UBERON:0013473 lower esophagus

many thanks

**Comment by ANiknejad** [comment]
see #1177 too, please

**Comment by cmungall** [comment]
FMA subdivides into abdominal/thoracic/cervical, but I don't think this corresponds to lower/middle/upper?

**Comment by ANiknejad** [comment]
Hi Chris,
Wondering if you could create for 'lower esophagus' all the layers you created for the esophagogastric junction' #1182 ?

lower esophagus mucosa
lower esophagus muscularis mucosa
lower esophagus submucosa
lower esophagus muscularis mucosa
lower esophagus muscularis propria (=UBERON:0035833 lower esophagus muscularis layer)

This link could be interesting too
http://training.seer.cancer.gov/ugi/anatomy/esophagus.html

Many thanks in advance
Cheers,
Anne
