### ISSUE TITLE
dorsal fin equ class

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1183]
'dorsal fin' has an equivalent class axiom that I think should be removed. (fin and (has_skeleton some dorsal fin skeleton)). It results in 'dorsal fin' having two parents in Ontobee.

**Comment by cmungall** [comment]
Not sure I understand the objection.

The equivalence pattern is a generic one applied to all skeletal appendages.

Two two named superclasses in ontobee are correct (although 'structure with contribution from NC' is an arguably dispensible grouping, happy to discuss getting rid of this but that would be a separate ticket)
