### ISSUE TITLE
spiracle - sensu arthropoda

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#1186]
Spiracle in Uberon refers to the vertebrate structure: "A small hole behind each eye that opens to the mouth in some fish."
In arthropods, a spiracle is an opening of the tracheal system.

Both definitions are here: https://en.wikipedia.org/wiki/Spiracle

This is causing problems for GO consistency:

![image](https://cloud.githubusercontent.com/assets/112839/11936890/baa365e0-a808-11e5-8207-081f4c7965aa.png)

**Comment by cmungall** [comment]
@wdahdul how should we approach this?

Note we also have:

[UBERON:4100115](http://purl.obolibrary.org/obo/UBERON_4100115) ! spiracular notch [DEF: "Soft tissue notch/opening lying on a spiracle.[PHENOSCAPE:NI]"]

This is the term of more interest to systematists as it's the bone structure. Note the two classes are not currently connected.

We need to improve on this however:

```
is_a: UBERON:0000061  ! anatomical structure
relationship: part_of UBERON:0004704 ! bone fossa
```

@dosumis the GO axiom should be removed of course. I am probably responsible, even though I explicitly noted in the metadata for the uberon class:

```
property_value: external_ontology_notes "GO term spiracle morphogenesis, open tracheal system - does not refer to this structure" xsd:string {isAbout="GO:0035277"}
```

I find the GO terminology a bit weird here, the ", open tracheal system" is obviously intended to disambiguate, but lexically it qualifies the process noun-phrase. "open tracheal system spiracle morphogenesis" is better but I feel we need a shorter name, even "tracheal spiracle" is IMHO better and non-ambiguous.

As to the actual arthropod structure, we can place in Uberon or PAAO/Arthro. The latter will require some modification of the GO import chain.

**Comment by dosumis** [comment]
I think 'tracheal spiracle' would be OK (although, IIRC, the spiracle is, at least in part, a modification of the integument rather than a part of the tracheal system.)
