### ISSUE TITLE
Manually classify ocular adnexa

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1189]
We currently have axioms of the form:

    (part_of some 'orbital region') DisjointUnion (part_of some 'ocular adnexa'), (part_of some 'eyeball')

See: https://github.com/obophenotype/uberon/wiki/Part-disjointness-Design-Pattern

ie the orbital region consists solely of parts of the ocular adnexa and parts of the eyeball, and these do not comingle

We can write this in a more compact (non-official) syntax like: `orbital_region = ocular_adnexa + eyeball`

Unfortunately Elk is not complete w.r.t these axioms, so we should manually classify, e.g. based on prolog reasoning

**Comment by cmungall** [comment]
We expect to end up with:

 * conjunctiva
 * extraocular muscles
 * nasolacrimal system

**Comment by cmungall** [comment]
Currently conjunctiva is not classifying as adnexa as it's asserted part-of the eyeball

MA has 'conjunctiva part_of anterior segment of eye'

It looks like we interpreted that as being part-of the anterior segment of the eyeBALL, and followed MA's lead. MA is technically correct that the conjunctiva is in the anterior segment of the EYE (ie eyeball plus directly associated apparatus), but AFAICT the 'anterior segment' qualifier is typically applied just to the globe and not the associated apparatus. @tfhayamizu 

We will change uberon so conjunctiva is no longer eyeball, which will yield the correct classification

**Comment by mellybelly** [comment]
agree that conjunctiva is not part of the anterior segment (of the eyeball)

also agree that anterior segment is only the globe, w parts such as ciliary body, cornea, pupil, lens, iris, and aqueous humor

**Comment by cmungall** [comment]
the ciliary ganglia are not in @pnrobinson's list nor are they listed as adnexa in HPO. However, according to my rules they are classified as such (they are in the orbital region). Discuss

**Comment by cmungall** [comment]
will include the extraocular muscles. Also include the common tendinous ring (currently classified as in the ocular region)

**Comment by mellybelly** [comment]
RE ciliary ganglia, innervating the ciliary body and in close proximity, I'd probably want to see them included in adnexia, especially if you were going to include the rectus muscles.

**Comment by cmungall** [comment]
Accessory CG too?

**Comment by RDruzinsky** [comment]
Harderian apparatus UBERON_0015153 should be included in the adnexa, too. Right?

**Comment by mellybelly** [comment]
RE Accessory CG - yes include. lovely paper here: https://journals.viamedica.pl/folia_morphologica/article/viewFile/16223/12861
see figure 6 for Accessory CG. Lots of diversity in CGs !!

**Comment by cmungall** [comment]
@RDruzinsky https://github.com/obophenotype/uberon/commit/c2a8e5cd9662ad0dc4adf2a88769ca45c9b0072f#diff-c138f865f3844d4ca864af8f4e32dae7R117678 includes all ocular glands into the adnexa, including the harderian

**Comment by cmungall** [comment]
what about

 [UBERON:0013398](http://purl.obolibrary.org/obo/UBERON_0013398) ! choroidal gland

I think this should be adnexal, but currently part-of the eyeball

**Comment by RDruzinsky** [comment]
I believe that the choroidal gland is not really a gland. Rather, it is a
network of vessels associated with the optic nerve. I think that it should
remain a part_of the eye, rather than an adnexal part_of the orbit.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by uberon** [comment]
On Wed, Dec 23, 2015 at 5:55 PM, Robert Druzinsky <notifications@github.com>
wrote:

> I believe that the choroidal gland is not really a gland. Rather, it is a
> network of vessels associated with the optic nerve. I think that it should
> remain a part_of the eye, rather than an adnexal part_of the orbit.
>

Fixed in next release, thanks!
