### ISSUE TITLE
typo in definition: UBERON_0011933

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/uberon#1191]
Def is:
A pilosebaceuous init that contains a strand of virbissa hair (a specialized tactile hair) with the follicle incorporating a blood sinus, heavily innervated by sensory nerves.

Should it be "unit" instead of "init"?

**Comment by cmungall** [comment]
Yep. Will fix next week unless you want to do a PR on uberon_edit.obo

**Comment by RDruzinsky** [comment]
Agreed!

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by nicolevasilevsky** [comment]
@cmungall please fix, I don't know what a PR on uberon_edit.obo is :)
