### ISSUE TITLE
basioccipital bone relationship to occipital bone

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1196]
Please remove the part_of relation between basioccipital bone UBERON:0001692 and occipital bone Uberon:0001676. In protege it appears to come from this general class axiom:
'basioccipital bone' and ('part of' some Mammalia) SubClassOf 'part of' some 'occipital bone'

**Comment by cmungall** [comment]
The axiom is annotated with ISBN10:0073040584 (Kardong, which I don't have handy right now)

Is this wrong? Do you have an example where the mammalian basioccipital is not part of the occipital?

Skull needs a lot of work

**Comment by balhoff** [comment]
I found the problem in the Phenoscape KB that led to this issue. Basioccipital bone phenotypes were being provided by the KB as justification for inference of presence of occipital bone in some taxa. It is not a result of that class axiom for mammalian basioccipital. It is a result of bad interaction of the MP hierarchy and the Uberon hierarchy in the EQ mappings. In MP, [abnormal basioccipital bone morphology](http://purl.obolibrary.org/obo/MP_0000079) is a subclass of [abnormal occipital bone morphology](http://purl.obolibrary.org/obo/MP_0005269). The EQ semantics of these map to Uberon anatomy terms, but I guess MP is not automatically classified.

I wonder if we should strip the class hierarchy from model organism phenotype ontologies before bringing them into the KB.

**Comment by balhoff** [comment]
Or possibly all the anatomy terms referenced in MP need to be scoped to the right taxon so that fish phenotypes cannot be classified under MP terms.

**Comment by balhoff** [comment]
I think we can close this issue unless @wdahdul thinks this is actually incorrect for mammals. The issues in Phenoscape are more related to proper scoping of entities referenced in MP when used in a broader taxonomic context.

**Comment by wdahdul** [comment]
Yes, I agree with closing this item.  Wasila
