### ISSUE TITLE
right and left kidney interstitium term placement reversed

### ISSUE THREAD

**Issue by jrsjrs** [obophenotype/uberon#1207]
In the OBO version of UBERON, looking at the children of "left kidney" and "right kidney", I found that right kidney interstitium (UBERON:0018114) is a child of left kidney (UBERON:0004538) and has children left renal cortex interstitium (UBERON:0018117) and left renal medulla interstitium (UBERON:0018119), whereas left kidney interstitium (UBERON:0018113) is a child of right kidney (UBERON:0004539) and has children right renal cortex interstitium (UBERON:0018118) and right renal medulla interstitium (UBERON:0018120).

In the version on BioPortal, the information for right kidney interstitium (for example) is:

Preferred Name               right kidney interstitium
Definitions                  A kidney interstitium that is part of a left kidney.
ID                           http://purl.obolibrary.org/obo/UBERON_0018114
database_cross_reference     FMA:74271
definition                   A kidney interstitium that is part of a left kidney.
has_exact_synonym            left renal stroma
                             stroma of left kidney
has_obo_namespace            uberon
id                           UBERON:0018114
label                        right kidney interstitium

**Comment by cmungall** [comment]
Thanks! Fix will be visible in next release
