### ISSUE TITLE
Cerebrum as synonym to Telencephalon

### ISSUE THREAD

**Issue by elviram** [obophenotype/uberon#1208]
Hello,
looking at anatomy terms regarding annotation of diseases, I couldn't find that cerebrum is a synonym of telencephalon. Looking at Dorland's Illustrated Medical Anatomy (and other sources, e.g. MP) it is stated that the cerebrum derives from the telencephalon.
Any clarification on that?

Thank you!

**Comment by RDruzinsky** [comment]
The cerebrum is not an exact synonym of the telencephalon. Only the dorsal
telencephalon or pallium develops into the cerebrum.

see  http://purl.obolibrary.org/obo/UBERON_0000203

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by elviram** [comment]
I agree. My question was, and maybe I didn't make it clear, why the cerebrum is stated as a synonym to telencephalos, see http://www.ebi.ac.uk/ols/beta/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001893

**Comment by RDruzinsky** [comment]
In that case, I don't know. It is not correct.


Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by cmungall** [comment]
I don't think there is a correct or not correct here. The term "cerebrum" is ambiguous, historically being used for different structures.

We take neuronames as an authoriative source, which notes the ambiguity of the term Cerebrum, and provides as first definition "In the classical segmentation of the CNS on the basis of topology and internal structure, the cerebrum is equivalent to the endbrain component of the forebrain. "

http://braininfo.rprc.washington.edu/Source.aspx?ID=118&questID=2068

In uberon, we call endbrain "telencephalon" (despite some connotations the latter is a developmental classification only), and as these are equivalent according to neuronames, we make an exact syn. We can weaken the syn scope if the other definitions are widespread. Or we can even add a new class if there is a separate defined division

Also some discussion here:
https://en.wikipedia.org/wiki/Talk:Cerebrum/Archive_1

**Comment by cmungall** [comment]
Not sure if anyone has access to https://www.crcpress.com/Neuroanatomy-and-the-Neurologic-Exam-A-Thesaurus-of-Synonyms-Similar-Sounding/Anthoney/9780849386312

But I believe this may have been incorporated into neuronames already

**Comment by RDruzinsky** [comment]
Unfortunately, the Anthoney text is not available to me via my library.
However, it does seem that the text in Neuronames follows Anthoney.

From the definition on Neuronames one could also say that forebrain,
prosencephalon, and cerebrum are synonymous. Clinicians and undergraduate
biology students may use the terms in that way, but I would argue that this
is imprecise and just wrong. Neuronames also cites Swanson (2004), but my
guess is that almost no neuroanatomy texts would make those terms
synonymous. Just browsing books in my office:
Standring, et al., Gray's Anatomy 39th ed., 2005
Butler and Hodos, Comparative Vertebrate Neuroanatomy, 1st ed., 1996
Nolte, The Human Brain, 5th ed., 2002 In the glossary, Cerebral Hemisphere
is defined as "The telencephalic derivatives on each side of the CNS,
together with a few nontelencephalic but adjoining structures. Includes the
cerebral cortex, striatum, globus pallidus, hippocampus, amygdala, and the
white matter pathways interconnecting them."

I see your point but I am not comfortable.



Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by cmungall** [comment]
We have a separate class for [UBERON:0001869](http://purl.obolibrary.org/obo/UBERON_0001869) ! cerebral hemisphere

this has "cerebrum" as a related synonym.

Would you be more comfortable if we weakened the scope of the cerebrum synonym for telencephalon to related?

**Comment by RDruzinsky** [comment]
Yes. I would be much happier with related.

This terminology is very confused, especially when it is used in an
imprecise manner.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky
