### ISSUE TITLE
refactor teeth

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1210]
Split from https://github.com/BgeeDB/anatomical-similarity-annotations/issues/18

Currently we have:
- [UBERON:0004765](http://purl.obolibrary.org/obo/UBERON_0004765) ! skeletal element
  - [UBERON:0003913](http://purl.obolibrary.org/obo/UBERON_0003913) ! tooth-like structure
    - [UBERON:0001091](http://purl.obolibrary.org/obo/UBERON_0001091) ! calcareous tooth   [develops_from: "tooth placode"] [developmental_contribution_from "neural crest"]

"tooth-like structure" is not a very satisfactory grouping, we should rethink whether some pan-metazoan "tooth" structure is required (e.g. grouping radulae, vertebrate teeth, echinoderm "teeth") and how it should be defined.

One possibility is:
- **label**: 'digestive tract skeletal element'
- **def**: 'any skeletal element that protrudes from the soft tissue of the digestive tract'

**Comment by cmungall** [comment]
@megbalk is this something you have opinions on? I don't love the grouping class but I suggest we just leave as is and close for now

**Comment by RDruzinsky** [comment]
I am not sure that there is anything better than "tooth-like structure." We
group all of these things together   (e.g. grouping radulae, vertebrate
teeth, echinoderm "teeth")  for that very reason - they are, functionally,
"tooth-like structures." There is no other reason they are grouped
together. I don't really have a problem with it.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by cmungall** [comment]
Thanks! Let's close this for now then
