### ISSUE TITLE
new term: optic foramen

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1213]
Please add optic foramen.
Note this is a TAO term but it was merged in uberon with 'optic canal' (UBERON_0005745). Optic foramen is the preferred usage in teleosts (it doesn't appear as a canal). Need to remove the TAO xref from UBERON_0005745.

Optic foramen
has_exact_synonym: optic nerve foramen
xref: TAO:0002025
Definition: Foramen in the orbital region of the neurocranium for the passage of the optic nerve (cranial nerve II). [database_cross_reference: TAO:wd]
is_a formen
part_of some orbital region

**Comment by wdahdul** [comment]
Chris, I assigned to you because I can't edit the xref in core uberon. Thanks!

**Comment by cmungall** [comment]
It seems the easiest thing to do here is relabel the existing class. It's logical definition even uses foramen.

In what circumstances do we want distinct foramina vs canals in the ontology?

Note the FMA has classes for both foramen and canal, but the distinction between these is not clear (both are classified under 'anatomical conduit')

what would you say the difference between a foramen and a canal is? Relative width/depth?

Let's focus on the definitions first

is this material or a space? Is it defined by the bone it passes through, or by the vessels passing through it?

**Comment by wdahdul** [comment]
In teleosts it’s more like an opening, not like a canal which is a deeper/longer, so the term used is "optic foramen”. I’m not sure of the condition outside of teleosts.

It’s defined as the foramen through which the optic nerve (cranial nerve II) passes. Not defined by the bone that houses it.

**Comment by cmungall** [comment]
OK, I think the uberon class should be define generically: any opening in the skull through which CNII passes. The label would use foramen

We can then add taxon notes and taxon-specific morphologies (e.g. canal-shaped) and taxon syns (e.g. canal)

**Comment by RDruzinsky** [comment]
Sounds good to me.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by wdahdul** [comment]
Yes, sounds good. Thanks
