### ISSUE TITLE
UBERON:0000010 pulling in bad synonyms from NeuroNames:247 (UBERON:0002888)

### ISSUE THREAD

**Issue by tgbugs** [obophenotype/uberon#1214]
peripheral nervous system seems to have some bad RELATED synonyms
```
synonym: "lateral part of the basal amygdalar nucleus" RELATED [NeuroNames:247]
synonym: "lateral part of the basolateral nucleus" RELATED [NeuroNames:247]
synonym: "nucleus amygdalae basalis, pars lateralis" RELATED LATIN [NeuroNames:247]
synonym: "nucleus amygdaloideus basalis, pars lateralis magnocellularis" RELATED LATIN [NeuroNames:247]
synonym: "nucleus basalis lateralis amygdalae" RELATED LATIN [NeuroNames:247]
```
These appear (correctly) under UBERON:0002888 (lateral part of basal amygdaloid nucleus). Not sure how they are getting pulled in, but they probably shouldn't be there.

**Comment by cmungall** [comment]
Good catch. The root of the issue is here http://neurolex.org/wiki/Birnlex_1111#tab=Factbox (follow the neuronames link) - we took the NIFGA to NN xrefs as a trusted source, should be verified.

**Comment by tgbugs** [comment]
Looks like that was just a plain error, the ID should be to [3232](http://braininfo.rprc.washington.edu/centraldirectory.aspx?type=h&ID=3232).

Can't claim credit for this one since, Doug Bowden is the one who caught it.

**Comment by cmungall** [comment]
Say hi to Doug from me. I'm still interested in the OWLization of 
neuronames and doing a deeper integration with uberon than we have now.
