### ISSUE TITLE
Intergluteal cleft vs sulcus confusion?

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1216]
http://purl.obolibrary.org/obo/UBERON_0016411 'intergluteal cleft'

Text definition is between buttock and leg. The OWL definition is between two buttocks (i.e. butt crack)

**Comment by RDruzinsky** [comment]
Intergluteal cleft or fold is between the buttocks. Fold between the
buttock and thigh is the gluteal fold.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by uberon** [comment]
Thanks! I think we have it right now. Original term was obsoleted as it 
was horribly confused.
