### ISSUE TITLE
2 new term requests for specific endocardial cushion regions

### ISSUE THREAD

**Issue by RLovering** [obophenotype/uberon#1226]
Hi

please could you generate these 2 new terms:
Inferior endocardial cushion
Definition: The endocardial cushions on the ventral surface of the AV canal, derived from the margin of the atrioventricular groove [database_cross_reference: https://embryology.med.unsw.edu.au/embryology/index.php/Intermediate_-_Atrial_Ventricular_Septation].  During embryonic development the dorsal and ventral endocardial cushions fuse and remodel to eventually form the valves and septa of the mature adult heart.[database_cross_reference: http://en.wikipedia.org/wiki/Atrioventricular_cushions]
synonym: ventral endocardial cushion

Superior endocardial cushion 
Definition: The endocardial cushions on the ventral surface of the AV canal, derived from the margin of the atrioventricular groove [database_cross_reference: https://embryology.med.unsw.edu.au/embryology/index.php/Intermediate_-_Atrial_Ventricular_Septation].  During embryonic development the dorsal and ventral endocardial cushions fuse and remodel to eventually form the valves and septa of the mature adult heart.[database_cross_reference: http://en.wikipedia.org/wiki/Atrioventricular_cushions]
synonym: ventral endocardial cushion

Both terms should be child terms of UBERON_0002062 endocardial cushion

These terms will enable me provide more descriptive GO annotations for Tgfbr2 based on PMID: 17050629.  I will either request more specific GO terms as is_a child terms to GO:0003203 
endocardial cushion morphogenesis (e.g. inferior endocardial cushion morphogenesis), or use the annotation extension field to specify this location when creating an annotation with GO:0003203 endocardial cushion morphogenesis.

Thanks

Ruth

**Comment by cmungall** [comment]
I think you mean dorsal for the superior. See the commit above for the def I went with, reopen if you want this changes.

Note SNOMED has anterior and posterior ECs
