### ISSUE TITLE
UBERON:0005876 "undifferentiated genital tubercle", taxon constraint to remove?

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1230]
Hi Chris,

UBERON:0000989 "penis" develops_from UBERON:0005876 "undifferentiated genital tubercle" only_in_taxon NCBITaxon:40674 "Mammalia"

I guess, this relation should be discarded:

'All amniotes studied to date initiate external genital development with the formation of paired genital swellings. In mammals, archosaurs, and turtles, these swellings merge to form a single genital tubercle, the precursor of the penis and clitoris'

http://www.ncbi.nlm.nih.gov/pubmed/24960313

Please see
https://github.com/BgeeDB/anatomical-similarity-annotations/issues/12

**Comment by cmungall** [comment]
The df relations in general could do with improving here. E.g. we're missing a link between penis and the undifferentiated tubercle
