### ISSUE TITLE
Uberon claims incorrectly that MESH:A14.254.646 and FMA:56665 are the same

### ISSUE THREAD

**Issue by ChristianKleineidam** [obophenotype/uberon#1233]
FMA:56665 is defined as "Skeletal ligament that connects a tooth to maxilla or mandibular". 

On the other hand MESH:A14.254.646 is defined as "The structures surrounding and supporting the tooth. Periodontium includes the gum ( GINGIVA), the alveolar bone ( ALVEOLAR PROCESS), the DENTAL CEMENTUM, and the PERIODONTAL LIGAMENT"

The gingiva (FMA:59762) is not part of the skeletal ligament. This issue is confusing because the word  `Periodontium` get's both used as synnonym for `Peridontal ligament` (FMA lists it as synnonym) and as synnonym for the old `Tooth Supporting Structures`.

**Comment by cmungall** [comment]
Yes, I'm not sure FMA is terminologically correct here. We have an editor note

```
id: UBERON:0001758
name: periodontium
property_value: external_ontology_notes "FMA treats periodontium and periodontal ligament as the same" xsd:string {external_ontology="FMA"}
```

And also:

```
id: UBERON:0008266
name: periodontal ligament
property_value: external_ontology_notes "FMA treats periodontium and periodontal ligament as the same; it has a separate class desmodentium, which we place here even though it is classified as fetal in FMA" xsd:string {external_ontology="FMA"}
```

We should go for logical consistency here rather than terminological. I will make the changes

**Comment by cmungall** [comment]
For some history, see #21

**Comment by ChristianKleineidam** [comment]
I don't think FMA is wrong. It's just using a term that has polysemy different then MeSH does.
The German Wikipedia happens to list periodontium as a synnonym for periodontal ligament as early as 2005 (https://de.wikipedia.org/w/index.php?title=Wurzelhaut&oldid=11148364). Other websites like http://www.zahn-lexikon.com/index.php/w/50-faqs/497-wurzelhaut also suggest that periodontium is a synnonym in some contexts.

It's like FMA usage of words like `arm` for (upper arm) or `leg` (for lower leg) whether other people mean something more general with the words doesn't seem to bother FMA.

**Comment by cmungall** [comment]
On 7 Jul 2016, at 9:25, Christian Kleineidam wrote:

> It's like FMA usage of words like `arm` for (upper arm) 
> or `leg` (for lower leg) whether other people mean something more 
> general with the words doesn't seem to bother FMA.

But it bothers a lot of users. I know some anatomists who have been 
dumbfounded by the FMA's usage of 'arm' and 'leg'. Also many users don't 
read definitions, so it's important to have 'idiot-proof' primary 
labels.
