### ISSUE TITLE
incoherency caused by spatial disjointness axiom between PNS and CNS

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1236]
From @dosumis 

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/50745/16715406/c2b47466-46ac-11e6-94ea-941e05d6ac33.png)

I believe this comes from mixing the latest uberon nervous-system-subset plus the latest CL. It's probably that CL is bringing in part of an older subset of uberon causing the conflict

**Comment by cmungall** [comment]
wtf is that determined-by... obviously at the root of this

**Comment by dosumis** [comment]
Can't see any reason it should be in the mereotopological relationship hierarchy.  Oddly - the relationship to has_part doesn't seem to be in the latest RO.   Looks like this is making a cycle => inconsistency even in ontologies that don't use determined_by but have (some?) combinations of part of and has part.

**Comment by cmungall** [comment]
determined by is fine http://purl.obolibrary.org/obo/RO_0002507

It seems somewhere (not in RO) we have an axiom that has-developmental-contribution-from http://purl.obolibrary.org/obo/RO_0002254 is being asserted as a subproperty of determined-by.

This is invalid, and furthermore there is no reason at all for these to be connected. It seems like this is leaking in from somwhere else. Can you tell where this subPropertyOf is coming from (I don't have the source module here)

**Comment by cmungall** [comment]
OK, I have tracked it down. Ugly: #1237

**Comment by dosumis** [comment]
Suspected it might be an ID clash.

**Comment by cmungall** [comment]
closing, it will be fixed in next release
