### ISSUE TITLE
composite-metazoan missing FBdv

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1239]
cc @fbastian

**Comment by dosumis** [comment]
Thought this was fixed

cc @mmc46  (just in case this is of interest).

**Comment by uberon** [comment]
Don't worry, this is a pipeline issue on the uberon side.

Specifically, we switched from having a lot of configuration (lists of 
ontologies plus bridging files) directly encoded in the Makefile to 
putting this into an OWL importer ontology; fbdv was omitted 
accidentally in this transition.
