### ISSUE TITLE
paired fin term relationships

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1241]
@cmungall  I added 'larval pelvic fin' UBERON_4300159 and 'larval pectoral fin' UBERON_4300160 to uberon-ext, but the necessary relationships in core uberon need to be updated:

Remove 
'pelvic fin’ develops_from ‘pelvic appendage bud'
'pectoral fin’ develops_from ‘pectoral appendage bud'

Add
'pelvic fin’ develops_from ‘larval pelvic fin'
'pectoral fin’ develops_from ‘larval pectoral fin'

Thanks!
Wasila and @laurajackson

**Comment by cmungall** [comment]
Hmm, this is a bit tricky.

In general, I would rather we adhere to well-documented design patterns for making stage-specific classes. Unfortunately this area needs a bit of work. In some cases we are consistently temporal splitters (e.g endochondral elements, for which we have a well defined pattern). In other cases, the patterns are not well documented, but are reasonably consistent: for example, distinguishing the bud from the fully formed structure, sometimes preceded by a field. But we don't include extract appendage classes for, say, the paddle stage of a limb. And we don't really have any design patterns for when to temporally lump/split with metamorphic transformations . It may be instructive to look at FBbt here, which is definitely a splitter - but this may be more appropriate to insects than vertebrates.

In this particular case, we have a few other issues

First, we want to be consistent with ZFA's modeling. When we make bridge axioms, we say 'ZFA:pectoral fin' EquivalentTo 'UBERON:pectoral fin' and part-of some Danio-rerio

In ZFA the pectoral fin temporally extends prior to the larval stage:

```
[Term]
id: ZFA:0001161
name: pectoral fin
namespace: zebrafish_anatomy
def: "Paired fin that is located in the thoracic region of the body." [TAO:curator]
synonym: "forefin" EXACT []
synonym: "pectoral fins" EXACT PLURAL []
xref: TAO:0001161
is_a: ZFA:0005596  ! paired fin
relationship: develops_from ZFA:0000141 ! pectoral fin bud
relationship: end ZFS:0000044 ! Adult
*****relationship: start ZFS:0000030 ! Pharyngula:Prim-15
```

Your requested change effectively changes the existing definition of pectoral fin to be post-larval pectoral fin (admittedly we need to be very clear about starts and ends in the ontology, which we have not been here).

Also, are we sure all fish fins go through a metamorphic transition? See

Flegler-Balon, Christine. "Direct and indirect development in fishes—examples of alternative life-history styles." Alternative life-history styles of animals. Springer Netherlands, 1989. 71-100.

Copp, Gordon H., and Vladimír Kovác. "When do fish with indirect development become juveniles?." Canadian Journal of Fisheries and Aquatic Sciences 53.4 (1996): 746-752.

Balon, Eugene K. "Alternative ways to become a juvenile or a definitive phenotype (and on some persisting linguistic offenses)." When do fishes become juveniles?. Springer Netherlands, 1998. 17-38.

This starts getting very complicated if we want to do this right. Splits are infectious. If we temporally split pectoral fin in this way, we are forced to split pectoral fin skeleton and musculature into larval and post-larval subclasses.  

My advice is to keep things simple and lump, not split. Make appendages liberal w.r.t to their start stage. This does not prohibit making stage-specific subclasses e.g. larval. So you could keep your newly added classes in ext, but change the axioms to follow the pattern:

 * larval X = X and part-of some larva

With no change of X in core

**Comment by fbastian** [comment]
Also, 'X transformation_of larval X' would be more appropriate than 'develops_from' I believe? (important distinction for some of our tools)

**Comment by cmungall** [comment]
Yes, immediate_transformation_of

**Comment by wdahdul** [comment]
Yes, I agree with your points below, Chris, and thanks for having a close look at this. I’ll modify the larval terms in ext to follow the pattern:
> 
> larval X = X and part-of some larva
- Wasila
