### ISSUE TITLE
bad synonym `Brodmann.10` on  UBERON:0013541

### ISSUE THREAD

**Issue by tgbugs** [obophenotype/uberon#1245]
This is an issue that propagated from nifstd/neurolex. Currently `Brodmann.10` is listed as an exact synonym, but other Brodmann areas do not have that synonym listed at any level. This was mentioned in https://support.crbs.ucsd.edu/browse/NIF-9272 as well.

**Comment by cmungall** [comment]
These were present in the original NIFSTD from 2007, in the synonym field.

Actually there are 3 culprits with exactly the same issue. Will fix:

 * UBERON:0006102 ! Brodmann (1909) area 35
 * UBERON:0006104 ! Brodmann (1909) area 36
 * UBERON:0013541 ! Brodmann (1909) area 10
