### ISSUE TITLE
UBERON bridge to BFO 2.0 'life cycle temporal boundary'

### ISSUE THREAD

**Issue by aellenhicks** [obophenotype/uberon#1258]
'life cycle temporal boundary' is a decendent class of BFO 'process'. In BFO 2.0 'process' is defined as 'An occurrent that has temporal proper parts and for some time t, p s-depends_on some material entity at t.' However, since life cycle temporal boundaries are instantaneous they (presumably) do not have proper temporal parts, so there is a semantic mismatch here.

In our project, we have MIREOTed 'start of neonate stage' in an ontology that also imports IAO. IAO has made processes and process boundaries disjoint (presumably to support the BFO 2.0 definitions). As long as we only MIREOT classes from UBERON, we do not anticipate formal inconsistencies in our current project, but down the road this could cause data integration problems if we want to use more of UBERON and import it directly. 

I have posted an issue on IAO also addressing this issue here: https://github.com/information-artifact-ontology/IAO/issues/189

**Comment by dosumis** [comment]
Agree. For ease of modelling, I think It makes sense for these to be instants - no temporal extent.  This is implicit in the relations algebra we've (partially) implemented.  While there could be some argument about whether stages are processes, process-boundary is a better fit and so should be used by Uberon in preference to process.
