### ISSUE TITLE
new term request: Cardiopharyngeal field

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1263]
http://www.nature.com/nature/journal/v520/n7548/full/nature14435.html#bx1

"Cardiopharyngeal field. Includes anterior lateral mesoderm of the first heart field plus contiguous pharyngeal mesoderm that gives rise to second-heart-field-derived regions of the heart and branchiomeric muscles."

relations should be:

is_a: UBERON:0004120 ! mesoderm-derived structure
is_a: UBERON:0005291 ! embryonic tissue
is_a: UBERON:0007688 ! anlage

**Comment by cmungall** [comment]
How about this? I think we need to make UBERON:0004140 part of thus? I 
think heart anlage in uberon need some work...

```
[Term]
id: UBERON:0036146
name: cardiopharyngeal field
def: "An region of the mesoderm that includes anterior lateral mesoderm 
of the first heart field plus contiguous pharyngeal mesoderm that gives 
rise to second-heart-field-derived regions of the heart and 
branchiomeric muscles." 
[http://www.nature.com/nature/journal/v520/n7548/full/nature14435.html#bx1, 
BGEE:ann]
is_a: UBERON:0007688 ! anlage
relationship: part_of UBERON:0000922 ! embryo
relationship: develops_from UBERON:0000926 ! mesoderm
```

**Comment by uberon** [comment]
ok - we have dual partonomy now, PHF part of LPM and cardiopharyngeal field

maybe this is fine... or is the CPF part of the LPM too?
