### ISSUE TITLE
new term request: orovelar muscle

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1264]
http://www.nature.com/nature/journal/v520/n7548/full/nature14435.html

This evolutionary scenario implies that the amphioxus orovelar muscles and urochordate oral siphon muscles may be homologous to the cyclostome orovelar muscles and gnathostome mandibular muscles, which could potentially explain why these muscles are derived from the CPF only in vertebrates.

**Comment by cmungall** [comment]
can we flesh this out, so to speak?

```
[Term]
id: UBERON:0036148
name: orovelar muscle
def: "." [https://github.com/obophenotype/uberon/issues/1264]
is_a: UBERON:0001630 ! muscle organ
relationship: attaches_to UBERON:0013653 {comment="to be checked"} ! velar skeleton
relationship: never_in_taxon NCBITaxon:7776 ! Gnathostomata <vertebrate>
relationship: only_in_taxon NCBITaxon:89593 ! Craniata
```
