### ISSUE TITLE
new term request:  skin (or cutaneous) appendage placode

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1266]
http://www.ncbi.nlm.nih.gov/pubmed/25963196

Nuclear β-catenin localization supports homology of feathers, avian scutate scales, and alligator scales in early development.

"given that the earliest stage of β-catenin localization in feathers and archosaur scales is also found in placodes of several mammalian skin appendages, including hair and mammary glands, we hypothesize that a common skin appendage placode originated in the common ancestor of all amniotes. We suggest a skin placode should **not be defined by anatomical features**, but as a local, organized molecular signaling center from which an epidermal appendage develops."

Shall we create anyway a class?

http://www.unige.ch/sciences/Actualites/2016/News-240616-1_en.html

skin (or cutaneous) appendage placode

is_a: UBERON:0011814 {source="NCBIBook:NBK53175"} ! non-neurogenic ectodermal placode

**Comment by cmungall** [comment]
we have [UBERON:0011817](http://purl.obolibrary.org/obo/UBERON_0011817) ! follicle placode  

but it's undefined!

looking at its structure

![plac](https://cloud.githubusercontent.com/assets/50745/18936347/773d3846-859b-11e6-8345-354aaa8e04d0.png)

it was intended as a not-necessarily homologous grouping of hair and feather placodes, so would fit this request well. If you agree I will update name/def

**Comment by cmungall** [comment]
looks like we need a generic cutaneous follicle

**Comment by ANiknejad** [comment]
ok, yes, thank you Chris, for updating the name/def!
