### ISSUE TITLE
CL:0011001 part of UBERON:0002240

### ISSUE THREAD

**Issue by mbernste** [obophenotype/uberon#1269]
Should CL:0011001 (spinal cord motor neuron) include a "part_of" edge to UBERON:0002240 (spinal cord)? Thanks!

**Comment by uberon** [comment]
On 24 Sep 2016, at 20:01, Matthew Bernstein wrote:

> Should CL:0011001 (spinal cord motor neuron) include a "part_of" edge 
> to UBERON:0002240 (spinal cord)? Thanks!

It already does - which edition of the CL are you using?

**Comment by mbernste** [comment]
My apologies, I was using an incorrect version of the CL. Thanks for pointing that out
