### ISSUE TITLE
new term request - suprapubic skin

### ISSUE THREAD

**Issue by jahilton** [obophenotype/uberon#1272]
The ENCODE DCC is requesting NTR for 'suprapubic skin' for GTEx samples
I believe these had been annotated as 'skin of abdomen', but a 'suprapubic skin' term would be more accurate to distinguish the non-sun exposed area

is_a: 'zone of skin' [UBERON_0000014]

section 4.3.6.7 here...
https://biospecimens.cancer.gov/resources/sops/docs/GTEx_SOPs/BBRB-PR-0004-W1%20GTEx%20Tissue%20Harvesting%20Work%20Instruction.pdf

**Comment by cmungall** [comment]
Added:

```
[Term]
id: UBERON:0036149
name: suprapubic skin
def: "Area of skin in the hypoastric region of the abdomen." [https://github.com/obophenotype/uberon/issues/1272]
synonym: "hypogastric skin" RELATED []
intersection_of: UBERON:0000014 ! zone of skin
intersection_of: part_of UBERON:0013203 ! hypogastrium
```

this is defined formally in terms of the hypogastrium, which may be a broader than what you need. @ANiknejad can advise

**Comment by fbastian** [comment]
@ANiknejad: do we need to update our GTEx annotations following the creation of this term?

**Comment by uberon** [comment]
In some ways it seems like false specificity? Is the region distinct at the
cellular level? Or is it just a proxy for non sun exposed? (Which should be
captured as an extra qualifier)

**Comment by fbastian** [comment]
Yep, my question exactly.

**Comment by ANiknejad** [comment]
Actually there are some interesting human skin transcriptomics studies

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4305515/

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4882522/

http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0163054

Main factors sound to be ageing and UV for skin transcriptomics variability, so I guess, there is no reason to specify the localization of the zone of skin, but reasons to qualify the sun exposition status.
pH and microbiota may anyway vary depending of the zone of skin and sex of the individual, while such parameters should not influence human RNA-seq analysis in fine:

https://www.ncbi.nlm.nih.gov/pubmed/11393210

https://www.ncbi.nlm.nih.gov/pubmed/18489300

**Comment by ANiknejad** [comment]
>this is defined formally in terms of the hypogastrium, which may be a broader than what you need. @ANiknejad can advise

so far as available in the literature it is OK to have hypogastrium synonym of suprapubic
