### ISSUE TITLE
plectral apparatus def and synonyms

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1274]
Updates to the existing term plectral apparatus UBERON_3000443:

exact synonym: plectrum
related synonyms: stapes, columella, columella auris (citation: http://www.nature.com/articles/srep34130)

Def: Combined element that is the ossified footplate and ossified stylus that are, together, called the columella or stapes, as well as the distal cartilaginous parts bound to the tympanic ring. [PHENOSCAPE:DB]

Notes: Most authors would refer to this as the columella or stapes, but the plectrum also consists of a third component (distal parts), thus correspondence of frog columella and mammalian stapes is not certain.

**Comment by cmungall** [comment]
This issue was moved to obophenotype/uberon-phenoscape-ext#4
