### ISSUE TITLE
UBERON:0002685 anteroventral nucleus of thalamus and UBERON:0002637 ventral anterior nucleus of thalamus

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1286]
A bit tricky to understand the difference...

Both are 

is_a: UBERON:0015233 ! nucleus of dorsal thalamus

while it sounds like only 'antero(ventral?)' is from the dorsal part ?

https://en.wikipedia.org/wiki/List_of_thalamic_nuclei#/media/File:Thalmus.png

the 'ventral nuclear group' (UBERON:0002776) does not contain dorsal thalamus nucleus but is'...involved in modulating activity of dorsal thalamic nuclei."

UBERON:0002685
name: anteroventral nucleus of thalamus
is_a: UBERON:0015233 ! nucleus of dorsal thalamus
relationship: part_of UBERON:0002788 {source="NIFSTD"} ! anterior nuclear group

UBERON:0002637
name: ventral anterior nucleus of thalamus
is_a: UBERON:0015233 ! nucleus of dorsal thalamus
relationship: part_of UBERON:0002776 {source="BTO", source="FMA", source="NIF"} ! ventral nuclear group

Thoughts?

**Comment by RDruzinsky** [comment]
This: the 'ventral nuclear group' (UBERON:0002776) does not contain dorsal thalamus nucleus but is'...involved in modulating activity of dorsal thalamic nuclei" seems to be the problem.

UBERON:0002637 and UBERON:0002685 are correct, I believe. However, since the ventral nuclear group is_a nucleus of the dorsal thalamus then the statement above seems to make no sense.

**Comment by cmungall** [comment]
From Butler and Hodos:

https://books.google.com/books?id=6kGARvykJKMC&pg=PA66&dq=%22involved+in+modulating+the+activity+of+dorsal+thalamic+nuclei%22&hl=en&sa=X&ved=0ahUKEwjds4bxuYXQAhXqh1QKHcezBsgQ6AEIHDAA#v=onepage&q=%22involved%20in%20modulating%20the%20activity%20of%20dorsal%20thalamic%20nuclei%22&f=false

this may be the issue:

```
[Term]
id: UBERON:0002776
name: ventral nuclear group
def: "Nuclei in the ventral part of the thalamus, involved in modulating activity of dorsal thalamic nuclei." [ISBN10:0471888893]
is_a: UBERON:0002308 ! nucleus of brain
***relationship: part_of UBERON:0004703 {source="FMA"} ! dorsal thalamus
```

the part-of comes from:

```
[Term]
id: FMA:62022
name: ventral nuclear group of thalamus
synonym: "noyaux ventraux du thalamus@fr" EXACT []
synonym: "nuclei ventrales thalami" EXACT LATIN [FMA:TA]
synonym: "ventral nuclear group" EXACT []
synonym: "ventral nuclear mass" EXACT []
synonym: "ventral nuclei of thalamus" EXACT []
synonym: "ventral tier thalamic nuclei" EXACT []
is_a: FMA:256693  ! nucleus of thalamus
relationship: part_of FMA:62007 ! thalamus
relationship: regional_part_of FMA:62007 ! thalamus

[Term]
id: FMA:62007
name: thalamus
synonym: "dorsal thalamus" EXACT []
synonym: "dorsal thalamus (Anthoney)" EXACT []
xref: NIFSTD:birnlex_954
xref: RadLex:RID6578
is_a: FMA:83153  ! organ component of neuraxis
...
```

**Comment by ANiknejad** [comment]
ok so now I understand that 'thalamus' and 'dorsal thalamus' are actually identical structure, and any 'thalamus' related anatomical structure could be part_of UBERON:0004703 {source="FMA"} ! dorsal thalamus

**Comment by cmungall** [comment]
more or less. Uberon doesn't have any class with a primary label "thalamus", but it is a broad syn of "dorsal plus ventral thalamus"
