### ISSUE TITLE
BFO_0000063 is declared as both an AP and an OP

### ISSUE THREAD

**Issue by mcourtot** [obophenotype/uberon#1296]
In http://purl.obolibrary.org/obo/uberon/ro_import.owl:

```
<!-- http://purl.obolibrary.org/obo/BFO_0000063 -->
<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/BFO_0000063"/>
```

whereas `http://purl.obolibrary.org/obo/BFO_0000063` is an OP.

Causes an error in GO release:
`ERROR (OWLOntologyManagerImpl:1138) Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/BFO_0000063 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000063>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000063>))]`

**Comment by balhoff** [comment]
The root cause was fixed here: https://github.com/oborel/obo-relations/issues/130

**Comment by cmungall** [comment]
Fixed propagated to uberon release
