### ISSUE TITLE
Remove property chain: (located_in o in taxon) subPropertyOf in taxon

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#1297]
There are rather a lot of property chains on ['in taxon' (RO_0002162) in Uberon](http://www.ontobee.org/ontology/UBERON?iri=http://purl.obolibrary.org/obo/RO_0002162) that are not present on [this relation in RO](http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002162).  (see end of ticket for complete lists).

One of these is problematic:

(located_in o in taxon) subPropertyOf in taxon

There is a long-term plan to use located_in for non-cannonical parts (see GO symbiont/virus paper) both in GO extensions and in the GO itself. e.g. the relationship between a provirus and the host genome into which it is inserted.   This property chain prevents any use of located_in for this purpose if there are taxon restrictions on the classes related in this way that mark them as viral only, e.g.

![image](https://cloud.githubusercontent.com/assets/112839/20649158/3e477148-b4b0-11e6-9af3-d95bbbed4b90.png)

Please could this chain be deleted?

If not, please could you explain the use-case?

----------------

Side note: Shouldn't these be consolidated into RO.  I took some time to track down this property chain, as it was showing up in the GO TermGenie Build but not in the regular GO build.

Uberon has:

(has potential to develop into o in taxon) subPropertyOf in taxon
(existence starts during o in taxon) subPropertyOf in taxon
(developmentally_induced_by o in taxon) subPropertyOf in taxon
(attaches_to o in taxon) subPropertyOf in taxon
(develops_from o in taxon) subPropertyOf in taxon
(has developmental contribution from o in taxon) subPropertyOf in taxon
(connects o in taxon) subPropertyOf in taxon
(supplies o in taxon) subPropertyOf in taxon
(continuous_with o in taxon) subPropertyOf in taxon
(connected to o in taxon) subPropertyOf in taxon
(innervated_by o in taxon) subPropertyOf in taxon
(overlaps o in taxon) subPropertyOf in taxon
(part of o in taxon) subPropertyOf in taxon
(located_in o in taxon) subPropertyOf in taxon
(produced_by o in taxon) subPropertyOf in taxon
(extends_fibers_into o in taxon) subPropertyOf in taxon
(produces o in taxon) subPropertyOf in taxon
(existence ends during o in taxon) subPropertyOf in taxon

RO has: 

(has prototype o in taxon) subPropertyOf in taxon
(capable of o in taxon) subPropertyOf in taxon
(develops from o in taxon) subPropertyOf in taxon
(expressed in o in taxon) subPropertyOf in taxon
(part of o in taxon) subPropertyOf in taxon
(has part o in taxon) subPropertyOf in taxon
(has developmental contribution from o in taxon) subPropertyOf in taxon
(results in developmental progression of o in taxon) subPropertyOf in taxon
(actively participates in o in taxon) subPropertyOf in taxon
(develops from part of o in taxon) subPropertyOf in taxon

**Comment by cmungall** [comment]
Agreed, it's irresponsible injecting these. This should be fixed.

Use case: for internal coherency checking within uberon we can overconstrain, especially as we don't have inter-species located-ins within the ontology.
