### ISSUE TITLE
New version of uberon causes unsatsfiable classes for reproductive structures in GO

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1306]
![image](https://cloud.githubusercontent.com/assets/50745/22843697/8b7babe0-ef8f-11e6-97c5-a651860dc389.png)

Not clear if this is entirely in Uberon or some mixture of Uberon + GO

**Comment by mcourtot** [comment]
It looks like there are differences between the uberon module imported by GO and the one imported by TG, or some sort of asynchrony? https://github.com/geneontology/go-ontology/issues/13011

**Comment by cmungall** [comment]
Sorry I didn't realize you'd filed the ticket on GO.

Yes, you're quite right, for ~ 24hrs after an uberon release, TG is using new-Uberon plus a stale module of Uberon (go/imports/uberon_imports)

Let's take this back to your ticket on the go tracker

**Comment by uberon** [comment]
I manually pushed the rebuild of uberon_imports so we didn't have to 
wait til the automated build tonight. TG back up
