### ISSUE TITLE
sigmoid colon & transverse colon part_of large intestine

### ISSUE THREAD

**Issue by jahilton** [obophenotype/uberon#1315]
I believe these connections were present before the most recent release, but seems they no longer...

sigmoid colon (UBERON:0001159) part_of large intestine (UBERON:0000059)
transverse colon (UBERON:0001157) part_of large intestine (UBERON:0000059)

**Comment by cmungall** [comment]
It does actually connect, but it's indirect via a *subdivision of* relation, which is a subproperty of part-of

http://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000168

This is not ideal. It shouldn't be necessary for people using uberon to have to deal with traversing subPropertyOf hierarchies. The next Uberon release will have a plain part-of link materialized for convenience.

It may still be indirect:

SC is_a 'proximal-distal subdivision of colon' part-of some colon part-of some LI
