### ISSUE TITLE
NTR: rectosigmoid junction

### ISSUE THREAD

**Issue by cstoeckert** [obophenotype/uberon#1319]
The rectosigmoid junction is needed for the Ontology for Biobanking for colon pathology.
Parent: anatomical junction
Logical definition: anatomical junction and (connects some rectum) and (connects some sigmoid colon)
definition: An anatomical junction that is between the sigmoid colon and rectum. 
definition source: https://www.cdc.gov/cancer/npcr/pdf/abstracting/colon.pdf

**Comment by cmungall** [comment]
Apologies - it appears in the next release, which is typically within a few weeks. We should make the github process less confusing, I filed this: #1321
