### ISSUE TITLE
secondary prosencephalon, to create an UBERON class?

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1322]
Hi Chris,

https://www.ncbi.nlm.nih.gov/pubmed/28470718

"In the current model, the most anterior part of the forebrain (secondary prosencephalon) is subdivided into the telencephalon dorsally and the hypothalamus ventrally. Our recent study identified a new morphogenetic unit named the optic recess region (ORR) between the telencephalon and the hypothalamus.  ...figure 2....
Our comparative analyses suggest that the presence of the three regions (telencephalon, ORR, hypothalamus) in the secondary prosencephalon is conserved in vertebrates. "

[Term]
id: DMBA:15567
name: secondary prosencephalon (mouse)
alt_id: DMBA:SP
synonym: "SP" RELATED ABBREVIATION []
is_a: UBERON:0002616 ! regional part of brain
relationship: part_of UBERON:0001890 ! forebrain
property_value: identifier "15567" xsd:int

Tentative definition:

def: "The most anterior region of the forebrain including both the telencephalon and the hypothalamus in the prosomeric model" [doi:10.1111/dgd.12348]
comment:  may contain the optic recess region (ORR) in the new model proposed by Yamamoto et al. 2017 (see https://www.ncbi.nlm.nih.gov/pubmed/28470718)

Cheers,

Anne

**Comment by cmungall** [comment]
This would presumably also entail rewiring part-ofs. This might upset people who expect a clean classical subdivision of the forebrain?
