### ISSUE TITLE
NTR: central right lobe of liver

### ISSUE THREAD

**Issue by jahilton** [obophenotype/uberon#1328]
As part of a GTEx subproject within the ENCODE project, liver samples were taken in the middle of the right lobe to minimize inclusion of peripheral tissue. We'd like a UBERON term for this section of the lobe...

Name: central right lobe of liver
Definition: The middle of the right lobe of the liver that is at least 1 cm below the capsule.
part_of: right lobe of liver ['UBERON:0001114']
Ref: https://www.encodeproject.org/documents/3cede565-25cc-4d1a-86fd-3cb2bc10fca1/@@download/attachment/GTEx%20Tissue%20Harvesting%20Work%20Instruction.pdf

**Comment by cmungall** [comment]
@ANiknejad what do you do in situations like this? So far we haven't added subdivisions of the right lobe.

We would expect gene expression to be the same throughout. The fact that the sample is taken from a place that minimizes peripheral tissue seems like it belongs as metadata about the sample?

**Comment by RDruzinsky** [comment]
I agree that the description of the location should be in the metadata. One
could make arbitrary divisions of any structure.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by jahilton** [comment]
This is not an unexpected response, but we just wanted to confirm how it would be treated from your point-of-view.
Thanks so much!
