### ISSUE TITLE
Should Pyramidal tract be it's own class?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/uberon#1334]
Pyramidal tract is a broad synonym for UBERON_0002707 corticospinal tract

See related HP ticket: https://github.com/obophenotype/upheno/issues/174

Could we have a new class for Pyramidal tract?

Source: https://en.wikipedia.org/wiki/Pyramidal_tracts

**Comment by cmungall** [comment]
Dupe #553
