### ISSUE TITLE
UBERON:0002533 post-anal tail bud AND mouse stages

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1337]
Hi Chris,

UBERON:0002533
name: post-anal tail bud
relationship: existence_ends_during_or_before MmusDv:0000021 {gci_relation="part_of", gci_filler="NCBITaxon:10090"} ! Theiler stage 14 (mouse)
relationship: existence_starts_during_or_after MmusDv:0000021 {gci_relation="part_of", gci_filler="NCBITaxon:10090"} ! Theiler stage 14 (mouse)

while there are expression data on stage E9.5 (= TS15)
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1477374

Maybe just to correct 

relationship: existence_ends_during_or_before MmusDv:0000021 {gci_relation="part_of", gci_filler="NCBITaxon:10090"} ! Theiler stage 14 (mouse)

because sounds like 'tail bud' is still present at TS16 ?
'Theiler Stage 16 - Closure of posterior neuropore; hind limb bud and tail bud'

https://www.emouseatlas.org/emap/ema/theiler_stages/StageDefinition/ts16definition.html

Thank you

**Comment by cmungall** [comment]
```
[Term]
id: EMAPA:16580
name: tail bud
namespace: anatomical_structure
relationship: ends_at TS14 ! TS14
relationship: part_of EMAPA:16039 ! embryo
relationship: starts_at TS14 ! TS14
```

can you file a ticket here: https://github.com/obophenotype/mouse-anatomy-ontology

**Comment by cmungall** [comment]
https://github.com/obophenotype/mouse-anatomy-ontology/issues/112
