### ISSUE TITLE
new term request: coronary band

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1339]
Expression data from bovine coronary band

https://www.ncbi.nlm.nih.gov/pubmed/20961407

"area above the hoof where hair growth ends"
relationship: part_of UBERON:0008963 ! hoof

synonym: "corium coronae" EXACT [SNMI:T-01722]

http://bioportal.bioontology.org/ontologies/SNMI?p=classes&conceptid=T-01722

**Comment by cmungall** [comment]
Also present in horses: http://horsesidevetguide.com/drv/Observation/104/wound-to-coronary-band-hairline-of-hoof/

I'll assume we want this generalized for all ungulates
