### ISSUE TITLE
NT: parenchyma of mammary gland

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1349]
see
https://github.com/obophenotype/uberon/issues/1151
Stroma of mammary gland

> cmungall commented on 23 Sep 2015 
Do we need to discriminate between the concepts at the  level of the mammary gland? It sounds like we should stick with the  existing ID, possibly relabel it, and make it clear in the definition  that it is non-passive? As far as discriminating the generic stroma class from connective  tissue - interesting that you indicate stroma indicates a more active  role. Our current def: "Connective, non-functional supportive framework of a biological cell, tissue, or organ. Contrast with parenchyma."

Actually there are expression data on mammary gland parenchyma (Atlas of Bovine Gene Expression) that may be of interest:
https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?study=SRP002394

So it would be useful to have 

'parenchyma of mammary gland'

draft definition:
'parenchymal tissue that consists of the alveoli, grape-like clusters where milk is stored, and branching ducts, which are tubular canals carrying gladular secretions.'

from 
http://www.newworldencyclopedia.org/entry/Mammary_gland

**Comment by cmungall** [comment]
I wonder if we should not reconsider adding stroma too?
