### ISSUE TITLE
Review cranial placodes

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#135]
Some points to consider:
- check scheme for accommodating different usages of the term (generic placode, cranial placode, neurogenic placode)
- See vagal placodes #133
- Check develops_from to placodes.
- Should placodes be split into epithelial and mesenchymal parts? See EHDAA2
- Check develops_from leading from placodes to ganglia and nerves - document mixed contribution from neural crest
- Check cl
- Check we have everything in http://www.ncbi.nlm.nih.gov/books/NBK53175
- Check taxon constraints, particularly: are there invertebrate placodes in the sense defined here: https://github.com/geneontology/go-ontology/issues/12223#issuecomment-215692347
## HIERARCHY
- [UBERON:0005085](http://purl.obolibrary.org/obo/UBERON_0005085) ! ectodermal placode   [only_in_taxon: "Chordata"]
  - [UBERON:0002546](http://purl.obolibrary.org/obo/UBERON_0002546) ! cranial placode [only_in_taxon: "Chordata"]
    - [UBERON:0003073](http://purl.obolibrary.org/obo/UBERON_0003073) ! lens placode
    - [UBERON:0009122](http://purl.obolibrary.org/obo/UBERON_0009122) ! adenohypophyseal placode
    - [UBERON:0009955](http://purl.obolibrary.org/obo/UBERON_0009955) ! neurogenic placode
      - [UBERON:0003050](http://purl.obolibrary.org/obo/UBERON_0003050) ! olfactory placode
      - [UBERON:0003067](http://purl.obolibrary.org/obo/UBERON_0003067) ! dorsolateral placode
        - [UBERON:0003069](http://purl.obolibrary.org/obo/UBERON_0003069) ! otic placode
        - [UBERON:0003070](http://purl.obolibrary.org/obo/UBERON_0003070) ! trigeminal placode complex
        - [UBERON:0009128](http://purl.obolibrary.org/obo/UBERON_0009128) ! lateral line placode [only_in_taxon: "Vertebrata <Metazoa>"]
        - [UBERON:2001156](http://purl.obolibrary.org/obo/UBERON_2001156) ! posterior lateral line placode
        - [UBERON:2001316](http://purl.obolibrary.org/obo/UBERON_2001316) ! anterior lateral line placode
        - [UBERON:2005121](http://purl.obolibrary.org/obo/UBERON_2005121) ! middle lateral line placode
      - [UBERON:0003078](http://purl.obolibrary.org/obo/UBERON_0003078) ! epibranchial placode
        - [UBERON:0009124](http://purl.obolibrary.org/obo/UBERON_0009124) ! geniculate placode
        - [UBERON:0009125](http://purl.obolibrary.org/obo/UBERON_0009125) ! petrosal placode
        - [UBERON:0009126](http://purl.obolibrary.org/obo/UBERON_0009126) ! nodosal placode
        - [UBERON:2001297](http://purl.obolibrary.org/obo/UBERON_2001297) ! vagal placode 1
        - [UBERON:2001298](http://purl.obolibrary.org/obo/UBERON_2001298) ! vagal placode 2
        - [UBERON:2001299](http://purl.obolibrary.org/obo/UBERON_2001299) ! vagal placode 3
        - [UBERON:2001300](http://purl.obolibrary.org/obo/UBERON_2001300) ! vagal placode 4
      - [UBERON:0035597](http://purl.obolibrary.org/obo/UBERON_0035597) ! profundal placode
      - [UBERON:0035598](http://purl.obolibrary.org/obo/UBERON_0035598) ! maxillomandibular placode
  - [UBERON:0011814](http://purl.obolibrary.org/obo/UBERON_0011814) ! non-neurogenic ectodermal placode
    - [UBERON:0003073](http://purl.obolibrary.org/obo/UBERON_0003073) ! lens placode
    - [UBERON:0005087](http://purl.obolibrary.org/obo/UBERON_0005087) ! tooth placode
      - [UBERON:0008969](http://purl.obolibrary.org/obo/UBERON_0008969) ! dental follicle
    - [UBERON:0005088](http://purl.obolibrary.org/obo/UBERON_0005088) ! sebaceous gland placode
    - [UBERON:0005089](http://purl.obolibrary.org/obo/UBERON_0005089) ! sweat gland placode
    - [UBERON:0005311](http://purl.obolibrary.org/obo/UBERON_0005311) ! mammary placode
    - [UBERON:0009122](http://purl.obolibrary.org/obo/UBERON_0009122) ! adenohypophyseal placode
    - [UBERON:0011817](http://purl.obolibrary.org/obo/UBERON_0011817) ! follicle placode
      - [UBERON:0005086](http://purl.obolibrary.org/obo/UBERON_0005086) ! hair follicle placode
      - [UBERON:0011783](http://purl.obolibrary.org/obo/UBERON_0011783) ! feather follicle placode

**Comment by ANiknejad** [comment]
https://github.com/obophenotype/uberon/issues/693

**Comment by cmungall** [comment]
## CHORDATE SPECIFICITY ##

```
id: UBERON:0005085
name: ectodermal placode
def: "An ectodermal placode is a thickening of the ectoderm that is the primordium of many structures derived from the ectoderm[GO]" [GO:0060788]
property_value: editor_note "consder adding placodal ectoderm as a distinct class? Also place placodal ectoderm as develops_from ectoderm; need to check taxon-appropriateness" xsd:string
property_value: taxon_notes "With the exception of the adenohypophysis, homologues of the nonneurogenic placodes (e.g. placodes giving rise to the teeth, hair follicles and lens), appear to be lacking in invertebrate chordates." xsd:string
is_a: UBERON:0001048 ! primordium
relationship: part_of UBERON:0000924 ! ectoderm
relationship: only_in_taxon NCBITaxon:7711 {source="PMID:22512454"} ! Chordata
```

http://www.ncbi.nlm.nih.gov/pubmed/22512454
The origin and evolution of the ectodermal placodes.

_Many of the features that distinguish the vertebrates from other chordates are found in the head. Prominent amongst these differences are the paired sense organs and associated cranial ganglia. Significantly, these structures are derived developmentally from the ectodermal placodes. It has therefore been proposed that the emergence of the ectodermal placodes was concomitant with and central to the evolution of the vertebrates. More recent studies, however, indicate forerunners of the ectodermal placodes can be readily identified outside the vertebrates, particularly in urochordates. Thus the evolutionary history of the ectodermal placodes is deeper and more complex than was previously appreciated with the full repertoire of vertebrate ectodermal placodes, and their derivatives, being assembled over a protracted period rather than arising collectively with the vertebrates_

Of course, this paper may be claiming the label for something more specific than simply a lump of ectodermal tissue with developmental potential --- need to tease this out

**Comment by dosumis** [comment]
>  I believe this paper is talking about what we would call the UBERON:0002546 ! cranial placode

I agree.  Cranial keeps the term specific to vertebrates.  

Outside of this context, developmental biologists just understand an ectodermal placode as a thickening of the ecotdermal epithelium - see tracheal placode in Drosophila.  Please move the taxon restriction to cranial placode.

**Comment by mellybelly** [comment]
You may wish to consider expanding taxon constraints for cranial placodes to chordates and not verts, or having some other homologous structure:

http://www.ncbi.nlm.nih.gov/pubmed/17959164
http://www.ncbi.nlm.nih.gov/pubmed/26258298
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1594956/\
http://www.ncbi.nlm.nih.gov/pubmed/24491817

http://www.ncbi.nlm.nih.gov/pubmed/18536035
(should model some of the development here too)

I think the naming of some of the placodes came from work I did long ago in ZFA, they are actually fairly diverse in their coalescence/naming across species, we should revisit that. 

Also, the lateral line placodes should be limited to species with lateral lines :-)

**Comment by cmungall** [comment]
chordate TC on the generic 'ectodermal placode' was removed already: https://github.com/obophenotype/uberon/commit/8cbed78c2c669e26051512d1c72da993443d34ef

And the reference for this was pushed down to the cranial placode class (now supported by two references)

**Comment by cmungall** [comment]
I think placodes are in good shape
