### ISSUE TITLE
issue with modelling of UBERON:0001877 medial septal nucleus

### ISSUE THREAD

**Issue by tgbugs** [obophenotype/uberon#1356]
The definition of `UBERON:0001877` leads to incorrect classification of `UBERON:0001879` (nucleus of diagonal band) as a subClassOf `UBERON:0001877`. This error was encountered while trying to resolve conflicts between modelling of NIFGA and Uberon, where we have a disjointness axiom between the two. A brief review of the Allen atlases [shows](http://atlas.brain-map.org/atlas?atlas=1#atlas=1&plate=100960336&structure=904&x=6096.952427455358&y=4152.952357700893&zoom=-3&resolution=11.97&z=5) that 'nucleus of diagonal band' is not a sub class of 'medial septal nucleus' despite being part of the medial septal complex. There are a number of changes required to correct the issue: 1) removal of `UBERON:0001879 rdfs:subClassOf UBERON:0001877` 2) removal of
``` 
UBERON:0001877 owl:equivalentClass [ a owl:Class ;
                                     owl:intersectionOf (
                                       UBERON:0002308
                                       [ a owl:Restriction ;
                                         owl:onProperty BFO:0000050 ;
                                         owl:someValuesFrom UBERON:0007629 ] ) ]
```
so that when we add 3) `UBERON:0001879 rdfs:subClassOf UBERON:0002308` the misclassification does not happen again (the part of restriction is already present).

Including @memartone for reference.

**Comment by cmungall** [comment]
Agreed. The equivalence axiom will be relaxed to a subclass (i.e. 2+3). This will automatically remove 1, since 1 is inferred.

**Comment by cmungall** [comment]
While we're here, any proposed definition for MSC? BrainInfo has a rat-centric def: http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=1958

**Comment by tgbugs** [comment]
It does not seem that the terminology of 'medial septal complex' is used in humans.

[Andy 68](https://www.ncbi.nlm.nih.gov/pubmed/5710964/) seems to be the only reference to a human NDB and the definitive work on what we might call the MSC. Plate 4 on page 401 (aka 19) figures 22, and 23 seem to indicate that NDB (BD in the plate) and MSN (MA, MP in the plate) are directly adjacent to each other (at least at some point) similar to how they are in the rat. Given all this I think it is probably ok to use to definition provided in the rat, with an addition, maybe: `def: "A septal nuclear complex that consists of the nucleus of the diagonal bands and the septal medial nuclei. This term is mainly used in the rat. While this term is not used in the human, the spatial relationship between its components in the human suggests that the term also applies."`

Here are annotations from the most recent works I can found that were trying to reconcile MRI studies with histology https://hyp.is/jXZG-JXPEeetgPOvfI0SDw/www.ncbi.nlm.nih.gov/pmc/articles/PMC4180657/ https://hyp.is/rXX3CpXPEee0EQ8-M_UddQ/www.ncbi.nlm.nih.gov/pmc/articles/PMC2577158/.

There is some overlapping nomenclature for the MSN here https://hyp.is/ow2JopXREeeYiAsiGxVYDA/www.ncbi.nlm.nih.gov/pmc/articles/PMC4175400/ with MSN -> Ch1 but nothing going to NDB directly, only the limbs of the diagonal bands.
