### ISSUE TITLE
Odd structure due to handling of obsolete terms in is_a relationships

### ISSUE THREAD

**Issue by lfearnley** [obophenotype/uberon#1360]
Just flagging what might be unintentional behaviours that I've picked up on while building a tree from UBERON's OBO file. If I'm understanding the ontology right, I should expect to see two root nodes (UBERON:0000000, processural entity, and UBERON:0001062, anatomical entity). 

Instead I get five-seven, with either three obsolete terms (UBERON:0000470, UBERON:0008277 and UBERON:0002946) or the non-obsolete children of these terms (UBERON:2002106, UBERON:0008278, UBERON:0008279, UBERON:2002050 and UBERON:3010306) depending on how I build the tree.

I'm not sure whether or not a term being marked obsolete should result in that obsolete status propagating to the children of that term, or what that means for the ontology's structure - could someone please clarify?

Details follow: 

UBERON:2002106 has an is_a relationship with UBERON:0002946, which is an obsolete term that has been replaced by UBERON:0002037

UBERON:0008278 and UBERON:0008279 have an is_a relationship with UBERON:0008277, which is obsolete and hasn't been updated with a replacement - it was moved to GO per documents; there's no 'replaced by' tag in UBERON:0008277.

UBERON:2002050 and UBERON:3010306 have an is_a relationship with UBERON:0000470, which is obsolete and hasn't been replaced.

**Comment by cmungall** [comment]
Thanks for these, you're right these should not have escaped. Some of these were accidents on my part, I forgot we were managing the source for the 2x and 3x terms in a separate file, the nematocyst one was just an accident.

> UBERON:2002106 has an is_a relationship with UBERON:0002946, which is an obsolete term that has been replaced by UBERON:0002037

Thanks. Fixed

> UBERON:0008278 and UBERON:0008279 have an is_a relationship with UBERON:0008277, which is obsolete and hasn't been updated with a replacement - it was moved to GO per documents; there's no 'replaced by' tag in UBERON:0008277.

Fixed

> UBERON:2002050 and UBERON:3010306 have an is_a relationship with UBERON:0000470, which is obsolete and hasn't been replaced.

Schreckstoff again, following up here:

https://github.com/obophenotype/uberon/issues/87

The other one is being moved to GO

**Comment by cmungall** [comment]
OK, all resolved. Will be fixed in next release

**Comment by lfearnley** [comment]
Thanks all!
