### ISSUE TITLE
potential modelling issues from NIFGA

### ISSUE THREAD

**Issue by tgbugs** [obophenotype/uberon#1362]
There are a couple of modelling issues that I have found in Uberon as I have been working through the old NIFGA doing a final deprecation. See https://github.com/SciCrunch/NIF-Ontology/commit/e866a4dc306ec30af2398125f37fef3e52e02db8 for context. For cases of missing part_of axioms I will be porting those missing restrictions to their equivalent uberon identifiers and can provide the uberon equivalents if needs be. Uberon has classes that should not be `subClassOf` their current parent, but should instead be `part_of` a given class and in some cases there should then be an `owl:disjointUnionOf` axiom on those subclasses (I don't know know if obo supports disjoint unions, but switching from subClassOf -> part_of is the main point). The issues are outlined below. Thoughts?

ccing @memartone

1. UBERON:0003002 ! medial lemniscus
    subClassOf issues leading to missing part_of axioms.
2. UBERON:0003045 ! dorsal longitudinal fasciculus
    subClassOf issues leading to missing part_of axioms.
3. UBERON:0004171 ! trigeminothalamic tract
    subClassOf issues leading to missing part_of axioms.

4. UBERON:0024151 ! tegmentum
    Missing part_of axioms.

5. Hippocampus layers. Everything seems to be in order here, only missing the disjointUnions where that is relevant.
    UBERON:0005371 ! stratum oriens
    UBERON:0005372 ! stratum radiatum
    UBERON:0007640 ! stratum lacunosum moleculare
    UBERON:0002313 ! stratum pyramidale hippocampi
6. All the rest are ok but could have disjointUnionOf axioms added.
    UBERON:0007641 ! trigeminal nuclear complex
    UBERON:0002474 ! cerebellar penducular complex
    UBERON:0002150 ! superior cerebellar peduncle

**Comment by cmungall** [comment]
Working on it.

One Q is generic classes like 'tract'. Does this denote a complete tract or a segment of a tract? in FMA, Dorsal trigeminal tract is_a tract of brain, suggesting the latter.

**Comment by cmungall** [comment]
disjointUnions - assume you require partonomic DUs? https://github.com/obophenotype/uberon/wiki/Part-disjointness-Design-Pattern

**Comment by tgbugs** [comment]
I think that for tract it can denote both, depending on how the particular tract was originally named. In the case of the Dorsal trigeminal tract I'm fairly certain that the 'dorsal' is used to distinguish the _entire_ tract, from another, presumably more ventral tract, because that tract runs along the rostral-caudal axis of the spine and dorsal/ventral is orthogonal, so it can't be segmented.

I think the distinction is ultimately based on whether a single individual axon can be found in two different 'tracts'. So for UBERON:0004171 ! trigeminothalamic tract we actually have both cases and so I need to do one more fix (I think). Basically the medulla/pons portions both themselves would have a dorsal and a ventral tract and thus would not be spatially disjoint from either the dorsal or the ventral tract (even though all 4 are still disjoint in the class sense).
```
                            medulla     pons
caudal  dorsal tract    --------------===========
caudal ventral tract    --------------===========
```

RE DUs: Yes. I had a feeling that simply making the classes disjoint did not produce the more stringent spatial results that they 'seem' to imply to an anatomist, so doing the partonomic in addition would be great.
