### ISSUE TITLE
reasoning issues when importing uberon and doid

### ISSUE THREAD

**Issue by tgbugs** [obophenotype/uberon#1370]
I am cross referencing this issue with the doid issue tracker.

Importing uberon and doid into a single ontology and running elk results in a large number of reasoning errors. At first I though the primary cause was that we have an additional axiom in NIFSTD `DOID:4 rdfs:subClassOf BFO:0000016 .` but further investigation suggests that there are some fundamental conflicts in modelling. Most of these issues arise in uberon_imports.owl from doid.

The doid-uberon conflicts mostly seem to revolve around conflicts between multicellular and acellular structure caused by the following triple `'acellular anatomical structure' owl:disjointWith 'multicellular anatomical structure'`. See for example 'amnion'.

Another issues is with disjointness between anatomical space and anatomical line (e.g. 'gingival groove').

There is another issue that appears when ro.owl is also imported and the DOID:4 triple show above is included, which is that 'located in' (RO:0001025) is used to relate various system diseases with their respective systems which are then 'part of' (BFO:0000050) some entity, triggering ro's sub property chain on 'contained in' (RO:0001018) which causes reasoning errors due to the disjointness between 'material entity' and 'independent continuant'. I don' think that this is an uberon issue, since 'immune system' being 'part of' some 'organism' is more than reasonable, while the choice to use 'located in' to associate diseases with their system seems less reasonable. Am I incorrect to think that 'disposition' is a reasonable subClassOf for 'disease' (a quick look at the literature suggests disposition is the preferred positioning for diseases under BFO)? I think that there are a number of more appropriate existing object properties (e.g. 'disposition of') that could be used that are closer to the 'manifests in' (or similar) relationship doid needs here.

```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/uberon_doid_ro_error.ttl> a owl:Ontology ;
    owl:imports <http://purl.obolibrary.org/obo/uberon/releases/2017-09-09/uberon.owl>,
        <http://purl.obolibrary.org/obo/doid/releases/2017-07-14/doid.owl>,
        <http://purl.obolibrary.org/obo/doid/imports/uberon_import.owl>,
        <http://purl.obolibrary.org/obo/ro/releases/2017-09-22/ro.owl> .
```

**Comment by cmungall** [comment]
I don't think there is an uberon action item here.

Note that the merged disease ontology http://obofoundry.org/ontology/mondo.html has axioms that are consistent with RO and other ontologies
