### ISSUE TITLE
UBERON:0002107 Liver infered as owl:Nothing for Platypus (9258)

### ISSUE THREAD

**Issue by jwollbrett** [obophenotype/uberon#1377]
related to : #1309
We used the SpeciesSubsetterUtil class from owltools-0.3.0 in order to create species specific ontologies.
In the Platypus ontology the liver is missing.

We followed the same strategy than the one used in the SpeciesSubsetterUtil
but directly in protégé i.e We manually added owl:Thing SubclassOf ('in taxon' some 'Ornithorhynchus') then we run the ELK 0.4.3 reasoner.

The owl:Nothing inference is explained by :
![screen shot 2017-10-10 at 11 58 03](https://user-images.githubusercontent.com/5854506/31380702-57f39abc-adb2-11e7-9a86-81314c5db946.png)

By removing _owlNothing EquivalentTo 'stomach' and ('in taxon' some Ornithoryncus)_, the reasoner did not anymore infer that Liver corresponds to owl:Nothing for Rattus.

**Comment by cmungall** [comment]
OK, looks like potentially two things going on here:

 - the inferred existential dependency between liver and stomach is surely too strong, as some species have the former without the latter? Consider making some of the continuous/connected relationships species dependent
 - the stomach taxon constraint excluding platypus is dubious. We normally track provenance at the axiom level but here we just have a class-level comment referencing wikipedia.

**Comment by cmungall** [comment]
UPDATE: actually, the first issue was already addressed in #1250, when we weakened depedency of pancreatic duct from duodenum to intestine, so I assume you are using a version of the ontology that is >1 year old?

**Comment by jwollbrett** [comment]
My bad. I used the ext.owl version of uberon from 2016-07-14 to explain inference in Protégé.
It's the version we used in the last version of Bgee.

With the last version of the ext.owl ontology I obtained these explanations :
![screen shot 2017-10-19 at 10 20 44](https://user-images.githubusercontent.com/5854506/31761391-edd71a0c-b4b7-11e7-893d-b139f8e972b5.png)

**Comment by cmungall** [comment]
Thanks!

The developmental relationship (from EHDAA2) was dubious, removed with https://github.com/obophenotype/uberon/commit/87951e572dd6de28473a6d7b25f13432abcc7ccb which I think fixes this
