### ISSUE TITLE
UBERON:0002728 entorhinal cortex and UBERON:0010415 barrel cortex infered as owl:Nothing for Mus musculus (10090)

### ISSUE THREAD

**Issue by jwollbrett** [obophenotype/uberon#1378]
related to : https://github.com/obophenotype/uberon/issues/1309
We used the SpeciesSubsetterUtil class from owltools-0.3.0 in order to create species specific ontologies.
In the species specific Mus musculus the entorhinal cortex is missing.

The owl:Nothing inference is explained by :
![screen shot 2017-10-10 at 12 30 33](https://user-images.githubusercontent.com/5854506/31383996-6dc6c746-adbd-11e7-9917-933a8dcf27ce.png)

the barrel cortex is also missing
The owl:Nothing inference is explained by :
![screen shot 2017-10-10 at 13 28 37](https://user-images.githubusercontent.com/5854506/31384372-03eb2c2a-adbf-11e7-8b70-99617c1d006b.png)

There are other missing anatomical entities in the Mus musculus ontology.
All of them are explained by :

* _owlNothing EquivalentTo 'gyrus' and ('in taxon' some 'Mus <Mouse, genus>')_

**Comment by cmungall** [comment]
The simplest thing here is to allow gyrii in mice. At some point we need to go back  and look at brain parthood relationships which are somewhat averaged across species at the moment and make more granular species-specific calls.
