### ISSUE TITLE
UBERON:0004813 seminiferous tubule epithelium and UBERON:0001343 seminiferous tubule of testis infered as owl:Nothing for Xenopus

### ISSUE THREAD

**Issue by jwollbrett** [obophenotype/uberon#1381]
related to : #1309
We used the SpeciesSubsetterUtil class from owltools-0.3.0 in order to create species specific ontologies.
In the species specific Xenopus tropicalis ontology the seminiferous tubule epithelium is missing.

We followed the same strategy than the one used in the SpeciesSubsetterUtil
but directly in protégé i.e We manually added owl:Thing SubclassOf ('in taxon' some 'Xenopus <subgenus>') then we run the ELK 0.4.3 reasoner.

The owl:Nothing inference is explained by :
![screen shot 2017-10-10 at 15 40 38](https://user-images.githubusercontent.com/5854506/31389563-aa7dd4fe-add1-11e7-9bc5-a0bbf7351d38.png)

the seminiferous tubule of testis is also missing.

**Comment by cmungall** [comment]
Bookmarked: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5049625/

For now I will simply qualify the channeling relationship to be mammal specific
