### ISSUE TITLE
material parts of immaterial entities

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#1382]
Load ext into Protege, import full RO, these are unsatisfiable:

- [x] blastocoel roof
- [x] cartilago lateralis of aryngo-tracheal chamber
- [x] foramen acusticum anterius
- [x] foramen acusticum maius
- [x] foramen acusticum minus
- [x] foramen acusticum posterius
- [x] foramen perilymphaticum accessorium
- [x] foramen perilymphaticus inferius
- [x] lateral appendix
- [x] lower oral valve
- [x] spiracular notch
- [x] upper oral valve

**Comment by cmungall** [comment]
Ah, looks like we remove the tbox when we make ro_import - to avoid the dreaded ontology self-autophagy. Will look into the pipeline issue - maybe @wdahdul could look at fixing the classes?
