### ISSUE TITLE
duplicate synonym for deltopectoral crest

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1390]
'deltoid crest' is included as related and exact synonyms

**Comment by wdahdul** [comment]
Also, the term 'bone element' has the same name as synonym (see exact synonym 'bone element')

**Comment by cmungall** [comment]
On 1 Dec 2017, at 12:55, Wasila Dahdul wrote:

> Also, the term 'bone element' has the same name as synonym (see exact 
> synonym 'bone element')

we're a bit inconsistent on this. Sometimes it's useful to record where 
it has been used elsewhere and we don't have a way of annotating the 
rdfs:label field (this causes issues for obo users)

Removing for now, can add en-massed with a special tag later.
