### ISSUE TITLE
dentition is_a skeleton?

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#1391]
![image](https://user-images.githubusercontent.com/112839/33488414-69a1a230-d6a8-11e7-81b3-1d3b31cac86c.png)

Presumably inferred from equivalent class axiom on skeleton: 

![image](https://user-images.githubusercontent.com/112839/33488466-95d235b8-d6a8-11e7-954b-98835ca02a87.png)

Suggest relaxing this axiom to subClassOf.

**Comment by cmungall** [comment]
ouch that's bad ok will fix
