### ISSUE TITLE
Mapping with ICD-O-3 topology

### ISSUE THREAD

**Issue by allisonheath** [obophenotype/uberon#1398]
Was wondering if there was a way to get from uberon terms to ICD-O-3 topology: http://codes.iarc.fr/topography? Perhaps via NCIt/UMLS somehow? Is this of interest / has anyone done this?

**Comment by cmungall** [comment]
@balhoff @nicolevasilevsky do we have a start on this or shall I generate?

**Comment by balhoff** [comment]
I think this is the most relevant document: https://docs.google.com/spreadsheets/d/1jQZZNeGDgUYV7bTksqqwTtuq3yI2xJPjMV27xvvK4NI/edit?usp=sharing

The mapping there is to NCIt, and then we can use the xrefs in NCIt to Uberon.

**Comment by balhoff** [comment]
Actually it's not xrefs, but equiv mappings here: http://purl.obolibrary.org/obo/ncit/ncit-bridge-to-uberon.owl

**Comment by wdduncan** [comment]
Thanks for putting this together!
