### ISSUE TITLE
NTR: bilaminar omphalopleure AND trilaminar omphalopleure

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1426]
Hi Chris,

https://www.ncbi.nlm.nih.gov/pubmed/28895534

"Molecular conservation of marsupial and eutherian placentation and lactation."

this recent paper reports expression data for both 'bilaminar omphalopleure' and 'trilaminar omphalopleure' in tammar wallaby (Notamacropus eugenii, taxonID 9315). This is a non-invasive placentation organism, please see also
https://www.ncbi.nlm.nih.gov/pubmed/29243855.
As far as I understand, both structures are related to 'bounding_layer_of UBERON:0001040 ! yolk sac' but anyway none of them are currently a class in UBERON. Maybe to create these new classes?
Thank you in advance for your help.
Cheers,

Anne

**Comment by cmungall** [comment]
Thanks! I think some of the early-stage embryonic structures may need a bit of a review, especially with a view to correctness across species.

I think for now, the quickest way to implement this is a new term __ omphalopleure__, part-of YM, and then subclasses based on lamina cardinality. Can you help with definitions?

It seems the same string is used at least for non-mammals (e.g. https://www.ncbi.nlm.nih.gov/pubmed/10761048), I have not had time to determine true applicability across species

**Comment by ANiknejad** [comment]
"In marsupials, gestation is supported by a yolk sac placenta. There is evidence for a division of function between distinct areas of the yolk sac. The non-vascular part (bilaminar omphalopleure) is responsible for the uptake and metabolism of nutrients, and the vascular part (trilaminar omphalopleure) is important for respiration."

https://www.ncbi.nlm.nih.gov/pubmed/29416852

_"Recent advances in understanding evolution of the placenta: insights from transcriptomics." 2018_

Sounds like using omphalopleure only for squamate is a older concept (1993)

https://onlinelibrary.wiley.com/doi/abs/10.1002/jez.1402660509

"Yolk sac placentation has been described in all major taxa of viviparous amniotes. The yolk sac of viviparous reptiles contributes to three categories of placentation, the choriovitelline placenta, which also occurs in marsupial and eutherian mammals, and the omphaloplacenta and omphalallantoic placenta, which occur only among squamate reptiles (lizards and snakes)...Epithelial cells of the bilaminar omphalopleure of the omphaloplacenta and omphalallantoic placenta are hypertrophied. "

>It seems the same string is used at least for non-mammals (e.g. https://www.ncbi.nlm.nih.gov/pubmed/10761048), I have not had time to determine true applicability across species

From this reference (200):

"with few exceptions the eggs of squamates share distinctive characteristics that are unique among amniotes; typically, eggs are oviposited  at  the  embryonic  limb  bud  stage  (Shine, 1983),  the  eggs  of  most  species  are  surrounded  by pliable eggshells that exchange water, oxygen, and carbon dioxide with the environment during development  (Packard  and  Packard,  1988),  and  the  ontogeny  of  the omphalopleure  is  unlike  any  other amniote  (Stewart,  1997). "
