### ISSUE TITLE
new term: precaudal vertebra

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1432]
New term request for 'precaudal vertebra'. This term was in TAO (http://purl.obolibrary.org/obo/TAO_0000263) but merged into 'trunk vertebra' in Uberon. It's distinct from trunk vertebra, however (see def below). 

I'll add the new term to ext. @cmungall in core, can you remove references to precaudal vertebra from uberon term: 'trunk vertebra'?

precaudal vertebra
def:  vertebrae lacking hemal spines (Weitzman, 1962), refers generally to the anterior vertebral region bounding the abdominal cavity. Alternate but not quite synonymous terms are abdominal or trunk vertebrae, which bear parapophyses and ribs. In many actinopterygians dorsal to the posterior abdominal cavity there are transitional vertebrae lacking ribs but also without hemal spines or sometimes even enclosed hemal arches. The primary definition would identify these vertebrae as precaudal. Bird and Mabee, 2003.

**Comment by wdahdul** [comment]
https://github.com/obophenotype/uberon-phenoscape-ext/commit/3a96860dc453c814e8537db9dde245455fccafc6

**Comment by cmungall** [comment]
@cerivs @ybradford you may also want to sync your def, from ZFA:

```
def: "Post-cranial vertebrae lacking hemal spines (Weitzman, 1962), refers generally to the anterior vertebral region bounding the abdominal cavity. Alternate but not quite synonymous terms are abdominal or trunk vertebrae, which bear parapophyses and ribs. In many actinopterygians dorsal to the posterior abdominal cavity there are transitional vertebrae lacking ribs but also without hemal spines or sometimes even enclosed hemal arches. The primary definition would identify these vertebrae as precaudal." [ZFA:0000263, ZFIN:ZDB-PUB-031103-13]
synonym: "abdominal vertebra" RELATED  [ZFA:0000263]
synonym: "precaudal vertebrae" EXACT PLURAL  [ZFA:0000263]
synonym: "trunk vertebra" RELATED  [ZFA:0000263]
```

**Comment by cmungall** [comment]
@wdahdul done - can you add the ZFA ID onto the new term, then close this, thx!

**Comment by wdahdul** [comment]
added the zfa and tao xrefs to the new term
