### ISSUE TITLE
Modify reticular lamina of epithelium

### ISSUE THREAD

**Issue by ukemi** [obophenotype/uberon#1436]
GO has recently obsoleted the term 'lamina reticularis' and the term is used in a the logical definition of UBERON:0001967.  The original ticket for the obsoletion is here:

https://github.com/geneontology/go-ontology/issues/15652

@rachhuntley

**Comment by cmungall** [comment]
@tfhayamizu 

will you obsolete this based on the GO team's investigations?

```
[Term]
id: MA:0001194
name: reticular lamina
namespace: adult_mouse_anatomy.gxd
synonym: "reticular membrane" RELATED []
relationship: BFO:0000050 MA:0001193 ! spiral organ
```

(also seems like the name should have been "reticular lamina of spiral organ")

also:

 *  MA:0001817 ! respiratory system reticular lamina
 *  MA:0001856 ! trachea reticular lamina
 * MA:0001834 ! bronchus reticular lamina

**Comment by tfhayamizu** [comment]
MA:0001194  and EMAPA:35735 - formerly named "reticular lamina"
Changing names to "reticular membrane" (retaining as synonym: "reticular lamina")
https://en.wikipedia.org/wiki/Reticular_membrane
in concordance with:id: 
id: UBERON:0007825
name: reticular membrane of spiral organ
def: "A reticular lamina of epithelium that is part of a spiral organ of cochlea." [OBOL:automatic]

No relationships to MA:0001817 or EMAPA:37572 "respiratory system reticular lamina"
Neither mouse anatomy ontologies currently have terms for the class "reticular lamina"

Wondering what this term represents:
id: UBERON:0013763
name: sensory epithelium of spiral organ
def: "A reticular lamina of epithelium that is part of a sensory epithelium." [OBOL:automatic]

**Comment by tfhayamizu** [comment]
For now, the mouse anatomy ontologies will be retaining the respiratory system basement membrane terms as substructures.

**Comment by cmungall** [comment]
UBERON:0013763 appears to be a mistake, will obsolete, thanks!
