### ISSUE TITLE
New release to include Phenoscape ext edits

### ISSUE THREAD

**Issue by laurajackson** [obophenotype/uberon#1444]
Is it possible to get a new Uberon release to include edits made in the Phenoscape ext version?

**Comment by cmungall** [comment]
just trying to track down this unsatisfiable class:

![image](https://user-images.githubusercontent.com/50745/43216647-6033cf7e-8ff4-11e8-8837-7b44ca7abf3f.png)

**Comment by cmungall** [comment]
This illustrates the issue:

![image](https://user-images.githubusercontent.com/50745/43216853-e213c5b2-8ff4-11e8-9403-691cedcd1468.png)

**Comment by wdahdul** [comment]
agree with you Chris, need to remove part_of lower jaw region. I checked the authors description ( this was needed for a curation experiment), and the term was loosely defined, so can't provide more detail other than needing to remove that relationship.

**Comment by RDruzinsky** [comment]
Agreed, Wasila. Only part of "jaws" in a very loose sense.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky
