### ISSUE TITLE
labels matching exact syns

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1446]
* same_label_as   UBERON:4000173 ! pelvic fin lepidotrichium      UBERON:4300117 ! pelvic fin ray pelvic fin ray  exact   label   2       9
 * same_label_as   UBERON:4000175 ! pectoral fin lepidotrichium    UBERON:4500007 ! pectoral fin ray       pectoral fin ray        exact   label   2       10
 * same_label_as   UBERON:4000176 ! anal fin lepidotrichium        UBERON:4500006 ! anal fin ray   anal fin ray    exact   label   3       9
 * same_label_as   UBERON:4000177 ! dorsal fin lepidotrichium      UBERON:4300116 ! dorsal fin ray dorsal fin ray  exact   label   2       9

**Comment by cmungall** [comment]
demoting to related synonyms or anything except EXACT would also be fine

**Comment by wdahdul** [comment]
Yes, I agree. @laurajackson you can change them to 'narrow' in this case.

**Comment by laurajackson** [comment]
Changed exact synonym to narrow synonym.
