### ISSUE TITLE
-base artifact missing

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#1448]
After the new release I expected to see `http://purl.obolibrary.org/obo/uberon/uberon-base.owl`. Do we need to do something else to make this get released?

**Comment by cmungall** [comment]
Release process is a bit contorted, I'll make a release today which will 
propagate tomorrow

**Comment by balhoff** [comment]
Looks good. There is a lot of RO content in there though, I guess as an artifact of OBO format.

**Comment by cmungall** [comment]
Yeh I think ultimately we will need some kind of robot command for cleaning up
