### ISSUE TITLE
Alliance expression ribbon needs new term for "excretory system"

### ISSUE THREAD

**Issue by doughowe** [obophenotype/uberon#1450]
<img width="349" alt="screen shot 2018-08-07 at 9 44 51 am" src="https://user-images.githubusercontent.com/7142077/43790127-8def3066-9a26-11e8-932b-4fd956eeb9de.png">

Currently, uberon has the term 'renal system' (UBERON:0001008) as a child of "anatomical structure" (UBERON:0000467).  That term is defined "The renal system in an anatomical system that maintains fluid balance and contributes to electrolyte balance, acid/base balance, and disposal of nitrogenous waste products." (NOTE: there is an extra period at the end of the definition).

Can this term be renamed to "excretory system"?  "renal system" is already a synonym even thought the term itself is "renal system".

If the term is renamed, the definition changes to:
The excretory system in an anatomical system that maintains fluid balance and contributes to electrolyte balance, acid/base balance, and disposal of nitrogenous waste products.

If a "renal system" term is desired, then a new term "excretory system" would be placed between "anatomical system" and "renal system"

**Comment by cmungall** [comment]
Uberon attempts to follow the GO classification that came out of the kidney working group, but it seems to have been vertebrate + arthropod centric, see my comments here:

Linked GO ticket: https://github.com/geneontology/go-ontology/issues/16143

**Comment by sbello** [comment]
The VTO called this urinary system  http://purl.obolibrary.org/obo/VT_1000777 Would this work? Do C. elegans produce urine? Cloaca (i.e. http://purl.obolibrary.org/obo/VT_0015055) lives under the surface structure branch and not under urinary or digestive system branches.

**Comment by cerivs** [comment]
Another possible term name is biofiltration system.
