### ISSUE TITLE
stomatogastric nervous system taxon constraint too strict

### ISSUE THREAD

**Issue by doughowe** [obophenotype/uberon#1462]
I happened upon this one randomly....The stomatogastric nervous system term has a taxon constraint limiting it to insecta.  I believe the stomatogastric nervous system is also present in various crabs.  Not sure what changes may be needed to rectify.

 Here is the current term from OBO.

[Term]
id: UBERON:6005096
name: stomatogastric nervous system
def: "A group of small, interconnected ganglia situated posterior to and between the two brain hemispheres and associated with the pharynx, esophagus and aorta." [FlyBase:FBrf0089570, PMID:12966498]
synonym: "stomodaeal nervous system" RELATED [FlyBase:FBrf0111704]
synonym: "stomodeal nervous system" RELATED [FlyBase:FBrf0111704]
xref: FBbt:00005096
is_a: UBERON:0004121 ! ectoderm-derived structure
is_a: UBERON:0011216 ! organ system subdivision
relationship: only_in_taxon NCBITaxon:50557 ! Insecta
relationship: part_of UBERON:0001017 ! central nervous system

Maybe the taxon constraint needs to be lifted to the pancrustacea level to encompass crabs and insects.
Taxonomy ID: 197562

**Comment by cmungall** [comment]
generalizing this to arthropod for now
