### ISSUE TITLE
Release docs

### ISSUE THREAD

**Issue by jahilton** [obophenotype/uberon#1463]
It seems like http://uberon.github.io/ is no longer updated with each release.
Is there a better place to get the Release notifications & notes?

**Comment by paola-scibite** [comment]
Hi again, 
See also https://github.com/obophenotype/uberon/issues/1598.
Thank you.

**Comment by jahilton** [comment]
In case others have the same issue & come across this ticket, it looks like releases are now being tracked here https://github.com/obophenotype/uberon/releases/

**Comment by paolaroncaglia** [comment]
Hi @jahilton ,

As you might have seen, there's a plan now to migrate contents from https://uberon.github.io/, and then obsolete that repository (#2045 ). So I'll close this ticket. Thanks,

Paola

**Comment by matentzn** [comment]
Let me keep this open, just so I remember to let everyone know. I will close it end of next week. Thank you @paolaroncaglia for pointing me to it

**Comment by matentzn** [comment]
The new Uberon documentation is now available here:
http://obophenotype.github.io/uberon/team/

Expect some changes, but it will be kept up to date.
