### ISSUE TITLE
NTR: peritrophic membrane

### ISSUE THREAD

**Issue by pgaudet** [obophenotype/uberon#1465]
to add a logical definition to  GO:0016490 structural constituent of peritrophic membrane
See https://github.com/geneontology/go-ontology/issues/16448

**Comment by cmungall** [comment]
Not sure if it's worth generalizing this Dmel term esp as no annotations:
http://amigo.geneontology.org/amigo/term/GO:0016490

**Comment by pgaudet** [comment]
OK
