### ISSUE TITLE
Broken Links on UBERON Page

### ISSUE THREAD

**Issue by smithGit** [obophenotype/uberon#1472]
I am using Ontobee occasionally, and I noticed that the link below is broken; it appears that all/most links on the page result in 404 error.  Could someone look into this?  Thanks and Happy New Year, Sam Smith – Michigan (retired volunteer with Dr. Oliver He’s lab at U of M)
 
http://uberon.github.io/browse/ontobee.html

**Comment by matentzn** [comment]
Thank you! The new Uberon page now simply redirects to ontobee:

http://obophenotype.github.io/uberon

![image](https://user-images.githubusercontent.com/7070631/135610191-7eb8eb8f-7404-45f3-b23a-433de5bee0c2.png)

**Comment by smithGit** [comment]
Thank you!
