### ISSUE TITLE
Mesocolon

### ISSUE THREAD

**Issue by ChristianKleineidam** [obophenotype/uberon#1473]
Currently, Uberon doesn't find anything when one searches for _mesocolon_. Should it be a synonym for _mesentery of colon_? Or should a new item be created?

**Comment by RDruzinsky** [comment]
Yes, it is a synonym. In humans the term is used to identify the mesentary
of a particular region of the colon, for example the transverse mesocolon
is the mesentary of the transverse colon, etc.


Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by cmungall** [comment]
OK, we'll add as a synonym for this class and for some of the subclasses
too, thanks
