### ISSUE TITLE
NTR: 'forelimb autopod'

### ISSUE THREAD

**Issue by jahilton** [obophenotype/uberon#1475]
upper limb segment [UBERON:0008785] has child terms 'forelimb stylopod' and 'forelimb zeugopod' but I am wondering if there should be an additional 'forelimb autopod' term
This would mirror the breakdown of the more generic limb segment [UBERON:0002529] and tis child terms 'stylopod', 'zeugopod', and 'autopod region'

If it is agreed that this should be a term, I can collect definition, synonyms, references...

**Comment by cmungall** [comment]
This is called manus or hand in uberon:

https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002398

We should add a synonym "forelimb autopod" though

**Comment by jahilton** [comment]
Ah, it's actually there as a synonym. Apologies.
Thanks!
