### ISSUE TITLE
Obsolete term in hierarchy (pterygoideus)

### ISSUE THREAD

**Issue by S2Ola** [obophenotype/uberon#1486]
During arecent import of UBERON into EFO I noticed that pterygoideus is OWL:deprecated but still in the hierarchy. 
You can see this in OLS ; https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_3010730

This is causing problem with our EFO build. 

Thanks.

**Comment by cmungall** [comment]
@wdahdul we merged into  UBERON:0006720 ! pterygoid muscle  but looks like the shadow remains in the ext file - do you want me to take this one?

**Comment by wdahdul** [comment]
Yes, please go ahead with obsoleting the one in ext. Thanks

**Comment by S2Ola** [comment]
@cmungall @wdahdul Is there any update on this ticket? We have found similar issues, which I've outlined in a new ticket here: link

**Comment by wdahdul** [comment]
Just saw this - I'll take care of it today

**Comment by wdahdul** [comment]
It shouldn't appear in the hierarchy now.
