### ISSUE TITLE
Relating tooth rows to member tooth type 

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1494]
The terms for rows of teeth on different bones aren’t currently related to the tooth types comprising the row.  Is there a recommendation (e.g., premaxillary tooth row composed_primarily_of premaxillary tooth)? It looks like ‘has member’ and ‘composed primarily of’ are used for similar sets of structures.

**Comment by cmungall** [comment]
Good question.

 * If "dentition" denotes a set of teeth AND all members are of type X, then we should use has_member X
 * If "dentition" includes other structures (e.g. region of jaw skeleton, gum, cementum or attaching structures OR there can be a mixture then the looser composed-primarily-of should be used.

But overall we want to keep this simple and well documented. It may be better to just to use composition relations throughout.

**Comment by wdahdul** [comment]
Thanks, I agree about using composed of for these. 
Updated the terms in ext.
