### ISSUE TITLE
Obsolete terms in hierarchy

### ISSUE THREAD

**Issue by S2Ola** [obophenotype/uberon#1498]
During arecent import of UBERON into EFO I noticed that pterygoideus is OWL:deprecated but still in the hierarchy.

Also linked to a ticket from March: [https://github.com/obophenotype/uberon/issues/1486]

1. http://purl.obolibrary.org/obo/UBERON_4200085
2. http://purl.obolibrary.org/obo/UBERON_4200024
3. http://purl.obolibrary.org/obo/UBERON_0005284
4. http://purl.obolibrary.org/obo/UBERON_0001124
5. http://purl.obolibrary.org/obo/UBERON_3010730
6. http://purl.obolibrary.org/obo/UBERON_6007435
7. http://purl.obolibrary.org/obo/UBERON_3010730

The following terms remain in the hierarchy after being obsoleted. 

Thank you

**Comment by wdahdul** [comment]
@cmungall I took care of 'obsolete suprascapular fossa' and 'obsolete glenoid head of scapula' in phenoscape-ext, but couldn’t find the other terms (which don't seem to have labels).

**Comment by matentzn** [comment]
All of these are fixed.
