### ISSUE TITLE
epiphysis

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1499]
Is epiphysis (e.g., distal epiphysis of femur) considered an adult trait or a juvenile trait?
In terms of development, juveniles have an epiphyseal plate that is unfused until maturation. To refer to an epiphysis is to refer to a juvenile bone. 
At maturation, the epiphysEs fuse to to the diaphysis, and then is refered to as the ephipysEs of a bone for adults. 
Some clarification on life stage this term is referring to would be helpful.

**Comment by cmungall** [comment]
Thanks for your question! It is considered applicable regardless of adult vs juvenile status

I think the def should be clarified

_The head of a long bone that articulates with a neighboring skeletal element and is separated from the shaft by the epiphyseal plate until bone growth stops. At that time, the plate disappears and the head and shaft are united[MESH,modified]_

Perhaps to

_The head of a long bone that articulates with a neighboring skeletal element. During development the epiphysis is separated from the shaft by the epiphyseal plate. After development the epiphysis and the shaft are united_

I wasn't aware that the i/e marked a distinction in stage - have you come across this @wdahdul ?

**Comment by megbalk** [comment]
It seems the epiphysis definition then comes from more of a developmental term. Thank you for the clarification!
For the change of the definition, I'd replace "head" with "end" as head can have a specific meaning for long bones.
