### ISSUE TITLE
Explore entry for Bgee Anatomical homology

### ISSUE THREAD

**Issue by marcrr** [obophenotype/uberon#1501]
Hi,

I suggest adding our new "Anatomical homology" page to the "Explore" menu on http://uberon.github.io/:

https://bgee.org/?page=anat_similarities

Marc

**Comment by mellybelly** [comment]
+1

**Comment by matentzn** [comment]
@marcrr we are getting to this now.

As we are in the process of streamlining quite a lot in Uberon, can you tell us which exact files in uberon BGEE is depending on? For all your use cases? uberon.owl? homology.owl? composite-metazoan.owl?

**Comment by fbastian** [comment]
@matentzn we rely on composite-metazoan.owl to retrieve the full ontology, and ext.owl to compute the taxon constraints.

**Comment by fbastian** [comment]
We update Uberon only for major releases of Bgee, which we just did, so I won't know for a while!

**Comment by matentzn** [comment]
cc @cmungall related to #2032
