### ISSUE TITLE
Help needed: Interpret justification for 'anterior limiting lamina of cornea'

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1504]
I have a problem in cell with up to date imports (or at least up-to-date afaikt), and I get that 'anterior limiting lamina of cornea' is unsatisfiable, basically because it is asserted to be a 'basement membrane of epithelium' (acellular anatomical structure) and inferred to be a 'connected anatomical structure' through some a variety of paths, the easiest of which is (just from current Uberon release):

![image](https://user-images.githubusercontent.com/7070631/61367082-d7212800-a882-11e9-8e72-5067aa40144f.png)

Now as you can see here, connected anatomical structures is through a fairly complex path inferred to be 'multicellular anatomical structure', which is disjoint with 'acellular structure'. 

![image](https://user-images.githubusercontent.com/7070631/61366861-4e09f100-a882-11e9-890e-883bfc1298f4.png)

Its a bit hard for me to figure out where the offending axiom comes from, but if you can easily see it of have an idea which direction to look, would appreciate it. This bug currently prevents CL to be build without hacking (current hack: lose the 'anterior limiting lamina of cornea' subclass of  basement membrane of epithelium' axiom which I am sure you dont like).

@dosumis @cmungall @balhoff

**Comment by balhoff** [comment]
`'material anatomical entity' SubClassOf drains some 'connected anatomical structure'` is very suspicious to me. It seems like some mistaken find and replace.

**Comment by matentzn** [comment]
It is in RO.. But fixing this wont fix the issue. We still have the inference path I mentioned above through the attached to relation.

Should I make an RO issue for your suspicion? 

The problem however still remains.. Any other idea what might have gone wrong here?

**Comment by balhoff** [comment]
[Here you can see](http://www.ontobee.org/ontology/RO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0000006) that the axiom should be `'material anatomical entity' SubClassOf drains ONLY 'connected anatomical structure'`. I expect somewhere in the import chain is an OBO file, and you are hitting this issue: https://github.com/owlcs/owlapi/issues/808

**Comment by matentzn** [comment]
OH MY GOD! I didnt notice, sorry! Such issues existed? WOW. Hopefully future ROBOT releases will not have this anymore? 

In any case; even in the absence of this axiom won't change the fact that  `anterior limiting lamina of cornea` is a connected anatomical structure. :/ Thanks Jim for helping out here!

**Comment by matentzn** [comment]
Let me check again. I think i can see what happened. Will comment later!

**Comment by matentzn** [comment]
Thanks @balhoff you rock. That was it! Not fixed yet but you identified it correctly. Merci :)
