### ISSUE TITLE
Q: Which is the class to use for whole organism (multi+single cell)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1507]
We urgently need this for our pattern efforts! Thanks.

**Comment by nicolevasilevsky** [comment]
there is UBERON_0000468 multicellular organism but I don't know if there is a term that includes both unicellular and multicellular organisms.

**Comment by matentzn** [comment]
Yeah our single cell organism are itchy because our patterns are restricted currently to multi-cellular organisms.. :P

**Comment by uberon** [comment]
See discussion on core tracker

use NCBITaxon:1 or caro

**Comment by matentzn** [comment]
Please point me to "core tracker".

Importantly, I need that UBERON:multicellular organism is a subclass. Is this the case for NCBITAXON:1? 

Caro I guess you are talking about ['organism or virus or viroid'](https://www.ebi.ac.uk/ols/ontologies/caro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0001010). Is UBERON:multicellular organism a sub? 

Thanks for the info, and we can close this.

**Comment by cmungall** [comment]
You're better to use caro as the bridge axioms exist. core =
experimental-obo-core

**Comment by matentzn** [comment]
Thank you
