### ISSUE TITLE
revise the definition of malar bone

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/uberon#1511]
Per https://github.com/obophenotype/human-phenotype-ontology/issues/4908, we should consider revising the def of malar bone to include zygomatic bone.

**Comment by RDruzinsky** [comment]
Zygomatic arch is not an exact synonym for the malaria or automatic bone
because the arch includes parts of the maxilla and the temporal bones.

**Comment by RDruzinsky** [comment]
It is a synonym for zygomatic bone.

**Comment by cewall** [comment]
I agree.  Malar and zygomatic (auto-correct woes Robert).


Christine E. Wall
Research Professor Emerita, Department of Evolutionary Anthropology
Senior Research Scientist & Director of Biomechanics, Duke Lemur Center
Duke University
Durham, NC  27708
mobile:  919-612-1306
http://walllab.evolutionaryanthropology.duke.edu/
FEED Archive Zenodo DOI:  10.5281/zenodo.1229320

________________________________

**Comment by uberon** [comment]
Thanks all!

It wouldn't hurt to add more provenance to the synonym assignments in
uberon (currently FMA is out only source for that synonym). We could
include this ticket URL, or ORCIDs of our helpful authorities!

>

**Comment by nicolevasilevsky** [comment]
I am reopening this ticket - I will try to do a PR to add a link to this ticket as a source (I've never done a PR in Uberon before!) :)

@RDruzinsky and @cewall, do you have ORCIDs? If yes, can you paste them in the comments and I'll add them to the term. If you don't have one, you can sign up at [orcid.org](https://orcid.org/)

**Comment by RDruzinsky** [comment]
Thanks, Chris Wall

**Comment by nicolevasilevsky** [comment]
I think I am confused again actually - @RDruzinsky and @cewall are you saying malar bone is an exact synonym of UBERON_0002500 zygomatic arch?

Thanks for clarifying!

**Comment by nicolevasilevsky** [comment]
Malar bone is currently a synonym on UBERON_0001683 jugal bone and the dbxef is FMA:52747

**Comment by nicolevasilevsky** [comment]
I just deleted some comments, FYI, I was mixed up but figured out the answers to my questions :)

**Comment by RDruzinsky** [comment]
No, malar bone is a synonym of zygomatic bone. Zygomatic arch includes the
zygomatic bone as well as parts of the maxilla and the temporal bones.
Zygomatic arch and zygomatic bone are not synonymous.

**Comment by nicolevasilevsky** [comment]
Thanks @RDruzinsky, I was thinking z. arch and z. bone were synonymous, but now I understand :)

**Comment by nicolevasilevsky** [comment]
I think this can be closed
