### ISSUE TITLE
Please revise some children of UBERON:0000020 sense organ 

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1517]
Hi,
This request stems from some issues in placement of disease ontology terms that are due to anatomical axioms. More details here (including links to other tickets in EFO and Mondo): https://github.com/monarch-initiative/mondo/issues/823 
At a first inspection, the underlying problematic assumptions in Uberon seem to be:

1) nose Subclass of olfactory organ
The nose as a whole is not only an olfactory organ. Would you consider replacing with olfactory organ has_part nose?

2) ear Subclass of sense organ
3) eye Subclass of sense organ
4) tongue Subclass of sense organ

The ear, eye and tongue as a whole are not just sense organs. The issue is the same as above except for the absence of intermediate terms (at least at a very quick glance). Would you consider replacing axioms 2, 3 and 4 with e.g. hearing/auditory sense organ has_part ear, etc?

There may be more, similar issues under 'sense organ', but I've only looked at anatomy terms that are causing issues in EFO (and Mondo). 

Many thanks,

Paola (Experimental Factor Ontology, EFO)
cc FYI @zoependlington, @nicolevasilevsky , @cmungall

**Comment by cmungall** [comment]
See also #536

**Comment by nicolevasilevsky** [comment]
I realized I am not sure what to do here, I have never actually edited Uberon before, and I am not sure how to address this ticket.

@paolaroncaglia for item 1, is the action item to:
- remove olfactory bulb as a superclass for nose
- add the superclass axiom 'has_part' some nose to 'olfactory bulb' 

This doesn't seem right, when I did this, I got incorrect inferences.

Thanks for your help!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Thanks for following up.
Looking back at my suggestion "Would you consider replacing with olfactory organ has_part nose?", I see that that would be incorrect (nose is for vertebrates, and olfactory organ covers non-vertebrates too). And 'nose' in Uberon is not only a subclass of olfactory organ, so that covers its other "aspects". Similarly, the way 'sense organ' is defined in Uberon, its subclasses make sense from a vertebrate perspective (it's not the entire ear that transduces sound stumuli, but the issue would persist anyway). 
Sorry. We may want to go back and try and fix this in Mondo, possibly as per @cmungall 's comment here https://github.com/monarch-initiative/mondo/issues/823#issuecomment-537327306 "Note we already excluded the is-a from SSD to nervous system disease for same underlying reasons. What's the use case for sensory system disease? Maybe the intent is nervous system part of sensory system disease?". Not sure what the best strategy is, though.
Thanks!

**Comment by cmungall** [comment]
Uberon uses 'sense organ' and 'sensory system' (http://purl.obolibrary.org/obo/UBERON_0001032) in quite a broad way consistent with other ontologies

http://purl.obolibrary.org/obo/BTO_0000202
http://purl.obolibrary.org/obo/FMA_78499
http://purl.obolibrary.org/obo/MA_0000017
http://purl.obolibrary.org/obo/EMAPA_35955

The intent is that it is (1) an organ (2) one of the evolved functions of the organ is to support some kind of detection of stimulus

many parts of the organ may not have anything to do with the function. They may be support such as skeleton or just there as part of the organ like skin. The function may also require structures outside the organ (at least nerves conducting to the CNS).

Given this broadness it may make sense (ho ho) to use a different strategy for the mondo definitions. I will respond on that ticket

**Comment by nicolevasilevsky** [comment]
I don't think there are any actions needed in Uberon. Closing this. Please reopen if necessary.
