### ISSUE TITLE
uberon-bridge-to-fbbt.owl is broken

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#1518]
https://github.com/obophenotype/uberon/blob/master/bridge/uberon-bridge-to-fbbt.owl

=> org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=7:column=17] Expecting rdf:RDF element.

obo version is fine though. 

Perhaps sufficient to just re-run the build?

**Comment by matentzn** [comment]
Accidental use of wrong purl seems to have been the cause. Reopen if necessary.
