### ISSUE TITLE
Make human subset part of the release

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1522]
@dosumis can you remind me the process HCA uses? Do you use owltools and the TCs to make a subset?

**Comment by cmungall** [comment]
OK, it seems we have two ways of making the taxon subsets in the Makefile

 - human-view.owl
 - uberon-taxmod-9606.owl

Both produce different results...

**Comment by balhoff** [comment]
The reasoner approach is satisfying. Can we make a push on `never_in_taxon`/`only_in_taxon` annotations as needed? I don't have an idea of how big of a job that would be.

**Comment by balhoff** [comment]
https://github.com/obophenotype/uberon-phenoscape-ext/pull/14 :-)

**Comment by cmungall** [comment]
Thanks, merged thagomizer TC! But I still think there is something not right with how I implemented the reasoner approach, it should have been excluded from the human subset based on being part of a tail

**Comment by cmungall** [comment]
oh I think I see what is wrong.. Makefile issue, looks like ext-taxon-axioms isn't being rebuilt...

**Comment by cmungall** [comment]
Another decision point:

Currently human-view is built from a *composite* ontology meaning it will have Allen HBA, EHDAA2, and FMA classes as leaves. Do we want this? I think this is a useful artefact, but I think the most useful one is a subset of Uberon itself. cc @mellybelly @dosumis

**Comment by dosumis** [comment]
Sorry for being slow on this one.

HCA build is here:  https://github.com/HumanCellAtlas/ontology
It's pretty scrappy and could definitely benefit from an Uberon Human build.

CC @zoependlington

**Comment by mellybelly** [comment]
I think for usability and maintenance it would be preferable to have the classes all in Uberon namespace (and CL). Also, we are going to need clinical preferred labels I expect.

**Comment by wdduncan** [comment]
If the  HBA, EHDAA2, and FMA classes are leaves we pull them out. Are the class IDs also stored as xrefs?

**Comment by cmungall** [comment]
Here's where we are:

trying to figure out the discrepancy between the two methods (see above). @balhoff suggests using the more principled reasoner approach (X-view.owl), I agree.

Here is the step:

https://github.com/obophenotype/uberon/blob/9b74bc88b8fef5b30e41c9990b0536703fc6a5d2/Makefile#L387-L390

This combines a [context](https://github.com/obophenotype/uberon/tree/9b74bc88b8fef5b30e41c9990b0536703fc6a5d2/contexts) file (e.g. "everything is part of a mouse") with a "no homology" (nh) file. The nh file has any axioms that connect to a structure in a different taxon blocked out (less relevant since we removed these), because this would existentially contaminate our solipsist everything-is-a-mouse view.

I suspect we are losing taxon axioms in nh...

**Comment by cmungall** [comment]
oh interesting

It looks like this step:

https://github.com/obophenotype/uberon/blob/9b74bc88b8fef5b30e41c9990b0536703fc6a5d2/Makefile#L129-L133

loses our never-in-taxon axioms.

E.g. unreasoned.owl has:

EquivalentClasses(owl:Nothing ObjectIntersectionOf(ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0005348) ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0005349)))

But this is not in materialized.owl...

**Comment by cmungall** [comment]
## SOLVED

ok, the issue is that we build x-view from composite-x. When we build composite-x we **deliberately** remove all constraining axioms. This is because we know we get incoherencies when we mix strict constraints in uberon with ssAOs.

I think it's in fact better to make the human view from ext (uberon+cl+go) rather than the somewhat weird composite files, which have unexpected stuff due to mixing ontologies. I will do...

**Comment by cmungall** [comment]
Available to download from:

http://uberon.github.io/downloads.html#subsets
