### ISSUE TITLE
NTR: subclasses for left arm bone, right arm bone, left leg bone, right leg bone 

### ISSUE THREAD

**Issue by bonitalam** [obophenotype/uberon#1523]
The ENCODE DCC would like to add subclasses for left arm bone, right arm bone, left leg bone, and right leg bone. We need more specific terms for arm bone [UBERON:0003460] and leg bone [UBERON:0005893], so that a lab’s samples can be more accurately described and annotated. These subclasses could follow the modeling paired structures design pattern (https://github.com/obophenotype/uberon/wiki/Modeling-paired-structures-Design-Pattern) and the subclasses currently found on UBERON for the left clavicle [UBERON:0008256] and the right clavicle [UBERON:0008255]. 

We suggest: 

Left arm bone:
- Equivalent to arm bone and _in_left_side_of_ some appendicular skeleton
- Subclass of arm bone, _in_left_side_of_ some appendicular skeleton

Right arm bone:
- Equivalent to arm bone and _in_right_side_of_ some appendicular skeleton
- Subclass of arm bone, _in_right_side_of_ some appendicular skeleton

Left leg bone:
- Equivalent to leg bone and _in_left_side_of_ some appendicular skeleton
- Subclass of leg bone, _in_left_side_of_ some appendicular skeleton

Right leg bone
- Equivalent to leg bone and _in_right_side_of_ some appendicular skeleton
- Subclass of leg bone, _in_right_side_of_ some appendicular skeleton

Thank you!

**Comment by cmungall** [comment]
Thank you for your request and taking time to read the documentation.

Before we add these, can we check that post-composition definitely does not work for ENCODE (e.g. where you would include a laterality qualifier in the database annotation fields?)

If ENCODE really needs these we will add them.

Can I also check that what you really require by arm and leg bone. In uberon this is stylopod + zeugopod but excluding autopod. IMO biologically this is an odd grouping. We can add, but just checking.

Also note that arm/leg can be ambiguous. Some people use as synonym for the whole limb (including autopod). FMA uses arm for the forelimb stylopod and leg for the hindlimb zeugopod which seems kind of odd to me, but apparently this usage is common in some formal US anatomical contexts.

**Comment by bonitalam** [comment]
Apologies for taking so long to reply, I was waiting for the lab that produced the biosamples to get back to me about how they defined arm and leg bone.  

Post-composition with a laterality qualifier is not preferred for these biosamples and the accessions produced by ENCODE. The lab defined their arm and leg bones as the stylopod, zeugopod, and autopod. In this case, can we use left and right forelimb [UBERON:0002102] and left and right hindlimb [UBERON:0002103] instead? I noticed that are terms for forelimb bone [UBERON:0008962] and hindlimb bone [UBERON:0003464], but I don't believe they describe the entirety of the bones comprising the forelimb and hindlimb and are meant to describe a singular bone. Please let us know if these terms sounds appropriate. Thank you!

**Comment by cmungall** [comment]
Ignoring laterality for the moment:

if the lab are specific about the precise segment (stylo/zeugo/auto-pod) then we should not lose that specificity by rolling up to to the broader "arm" or "limb".

In fact these terms you want in uberon are:

 - manus bone (aka hand bone, i.e. forelimb autopod bone)
 - pes bone (aka foot bone, i.e. hindlimb autopod bone)
 - humerus (aka forelimb stylopod bone)
 - femur (aka hindlimb stylopod bone)

for the zeugopod there are two bones - can you check with your lab to see if they know which one it is (e.g. radius v ulna, tibia vs fibula). And also check if it is only the long bones I mentioned, or if sometimes it can be other bones in this region (e.g. sesamoid bone in a muscle - unlikely).

Sorry to have you go back, but precision is really good here, and it sounds like they will know precisely which bone it is they samples. Once we establish this we'll make L+R versions.

**Comment by bonitalam** [comment]
After discussion with the lab and with other people with the ENCODE consortium, we have decided to go back to the original request of left arm bone, right arm bone, left leg bone, and left arm bone. We understand that Uberon defines this as only stylopod and zeugopod. The person who processed these samples is no longer with the lab, so the response we got earlier was just a best guess of what the samples were comprised of. However, we feel as though left/right arm/leg bone will best describe the samples as is. In the future, we may need to also request right and left manus and pes bone. Thank you for all your help again.

**Comment by bonitalam** [comment]
Hello, apologies. I would like to follow-up on this issue/request. After communication with the lab again, they have clarified they have used the whole limb or arm (bone and tissue) to be a part of their samples. I believe the correct route is to make new terms for left and right forelimb [UBERON:0002102] and left and right hindlimb [UBERON:0002103]. Here is their response below:

> These were received from UW's BDRL as intact limbs including all bones, tissue etc.  They were processed whole, so stylopod + zeugopod + autopod would be most accurate.  Apologies that I did not pick up on bones versus bones + tissue.   

Thank you again for your help!

**Comment by bonitalam** [comment]
This was taken care of in https://github.com/obophenotype/uberon/pull/1604
