### ISSUE TITLE
uberon-ext untracked file 

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1527]
In uberon-ext, there a file is appearing that won't allow me to pull from the repo. I don't think it needs to be in git. Can you make it ignored?

```
$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 4 and 3 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.DS_Store

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by balhoff** [comment]
Generally you can ignore "untracked files" warnings. But anyway I added a gitignore and removed that file. Can you see if this works? Otherwise you may need to first run:

`git checkout -- .DS_Store`

**Comment by wdahdul** [comment]
Thanks Jim, that worked for me.
