### ISSUE TITLE
Uberon website issues

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#1531]
Hi,

some issues currently (not only directly related to the website):
- links to subsets mouse.obo and mouse.owl are not working (would be good to have more subsets for download)
- the site under Adopters looks a bit broken. 
- naming of artefacts should have a leading "uberon_"... i.e. it should be uberon_basic.obo and not basic.obo or ext.owl should be uberon_ext.owl

**Comment by cmungall** [comment]
Subsets link now fixed: http://uberon.github.io/downloads.html#subsets

**Comment by drseb** [comment]
will close as at least the subsets files are linked now
