### ISSUE TITLE
How to edit UBERON

### ISSUE THREAD

**Issue by ramonawalls** [obophenotype/uberon#1534]
I need to request 8 or 9 new terms, plus more down the road. I would like to do this using a pull request, as I hope that is easier for you all.

I have looked over a lot of the documentation both in the code and in the wiki sections, but I am still not sure how I should got about creating new terms and editing existing terms. The documented workflows seem a bit out of date. I'm happy to contribute to the documentation as part of my pull requests, but I need to make sure I am consistent with your SOPs.

**Comment by nicolevasilevsky** [comment]
I am curious too. I don't see an ID ranges file in this repo.

**Comment by matentzn** [comment]
The structure is a bit different. While I am not sure how it is done, @nicolevasilevsky I think this is what you looking for: https://github.com/obophenotype/uberon/blob/master/uberon-idranges.owl

@ramonawalls @nicolevasilevsky Please wait a moment until 
https://github.com/obophenotype/uberon/pull/1535

Is merged, then you can edit. Maybe register id ranges first (@nicolevasilevsky, can you maybe make ranges for @ramonawalls me and you?)

All edits now happen on uberon_edit.obo in the top level of the repository.

**Comment by nicolevasilevsky** [comment]
Yes, that is what I was looking for Nico, thanks!

I can set up ID ranges for the three of us, once you are done with your edits.

**Comment by matentzn** [comment]
You can do it now or whenever.. wont interfere. As long as you dont edit `uberon_edit.obo`, it does not matter!

**Comment by nicolevasilevsky** [comment]
ok, done! #1536

**Comment by matentzn** [comment]
Ok @ramonawalls @nicolevasilevsky you are good to go.

1. Check out repo
2. Create branch
3. Edit uberon_edit.obo in Protege 5.5 (please 55, not 53, or 52), or with text editor (if you know what you are doing)
4. Save
5. Commit change to branch
6. Make pull request, referencing the issues this pull request is fixing
7. Wait for someone to review it and merge it in.

**Comment by nicolevasilevsky** [comment]
Thanks @matentzn!

**Comment by ramonawalls** [comment]
Thank you both! We will get to this soon. @nicolevasilevsky did you create new ID ranges for us?

**Comment by nicolevasilevsky** [comment]
Yes! Yours is:
Datatype: idrange:17
Annotations: allocatedto: "Ramona Walls",
EquivalentTo: xsd:integer[> 7500000 , <= 7999999]

**Comment by ramonawalls** [comment]
Wow, that was fast! :) Thanks!

**Comment by nicolevasilevsky** [comment]
@ramonawalls I just did a few edits in Uberon (for the first time!) I think everything is working okay, except Protege is reordering the synonyms in the file, so the diffs look a bit weird, but it is not introducing any unwanted changes.

**Comment by ramonawalls** [comment]
I am going to have @megbalk make pull requests in my ID range. I will review her requests before asking others to merge them.
