### ISSUE TITLE
New term: central retina

### ISSUE THREAD

**Issue by zoependlington** [obophenotype/uberon#1538]
**Preferred term label**
central retina

**Textual definition**
Region of retina around the fovea that extends approximately for 6 mm. Central retina is considerably thick due to increased density of photoreceptors, particularly cones and their associated bipolar and ganglion cells.
Link: https://webvision.med.utah.edu/book/part-i-foundations/simple-anatomy-of-the-retina/

**Suggested parent term**
retina - UBERON:0000966

Request from https://github.com/HumanCellAtlas/ontology/issues/52

**Comment by nicolevasilevsky** [comment]
If this is a region of the retina, I think the parent should be 'multi-tissue structure' and 'part of' some some retina.
