### ISSUE TITLE
NTRs: specific instar larva stages

### ISSUE THREAD

**Issue by zhengj2007** [obophenotype/uberon#1540]
Name | Value
-- | --
Label | first instar larva stage
Definition | The first stage of instar larva stage.
Parent | UBERON_0004730 instar larval stage

Name | Value
-- | --
Label | second instar larva stage
Definition | The second stage of instar larva stage.
Parent | UBERON_0004730 instar larval stage

Name | Value
-- | --
Label | third instar larva stage
Definition | The third stage of instar larva stage.
Parent | UBERON_0004730 instar larval stage
Alternative term | third instar larva
Definition source | IDOMAL:0000658 third instar larva

Name | Value
-- | --
Label | fourth instar larva stage
Definition | The fourth stage of instar larva stage.
Parent | UBERON_0004730 instar larval stage
Alternative term | fourth instar larva
Definition source | IDOMAL:0000659 fourth instar larva

**Comment by zhengj2007** [comment]
Thanks @nicolevasilevsky for working on these terms. Any further progress? Thanks!

**Comment by nicolevasilevsky** [comment]
Hi @zhengj2007 looks like there was a conflict, i just resolved it. Thanks for pinging me, this fell off my radar.

The pull request needs to be reviewed and hopefully it will be merged soon.

**Comment by cmungall** [comment]
How meaningful is Nth instar larval stage? Should this not be done in a sssO? cc @ANiknejad 

If we add these, do we xref FBbt even though (1) these may be neither homologous nor comparable in a meaningful way (2) FBbt models these as structures @dosumis 

See

https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00005339

Minor: I don't think it's very meaningful to use IDOMAL as a definition source here

I'm guessing what you really want is an Aedis stage ontology

**Comment by dosumis** [comment]
> On 27 Feb 2020, at 00:35, Chris Mungall <notifications@github.com> wrote:
> 
> How meaningful is Nth instar larval stage? Should this not be done in a sssO? cc @ANiknejad <https://github.com/ANiknejad>
> 
Probably not very meaningful - there’s a pretty big range of numbers of instars among insects. If you wanted to group holometabolous instars then first (after hatching) and last (before pupariation) and likely most comparable. 
> If we add these, do we xref FBbt even though (1) these may be neither homologous nor comparable in a meaningful way (2) FBbt models these as structures @dosumis <https://github.com/dosumis>
> See
> 
> https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00005339 <https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http://purl.obolibrary.org/obo/FBbt_00005339>
> 
We model them as both. Always have - but have never wired up the two.

**Comment by zhengj2007** [comment]
@nicolevasilevsky Thanks for working on the terms.

@cmungall @dosumis Thanks for the comments. I will pass the comments to VEuPathDB people who used the terms in annotation.

**Comment by SAK22** [comment]
please go ahead without the instars. Thank you!
