### ISSUE TITLE
add license to header

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1543]
http://obo-dashboard-test.ontodev.com/ - the ontology is failing the 'open' check

the release owl should contain:

```
     xmlns:terms="http://purl.org/dc/terms/"
...
        <terms:license rdf:resource="https://creativecommons.org/publicdomain/zero/1.0/"/>
```

See https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1041

**Comment by anitacaron** [comment]
Currently, uberon has included the license, and it is no longer failing the "open" check in the dashboard.

<img width="635" alt="Screenshot 2023-03-27 at 21 40 46" src="https://user-images.githubusercontent.com/2208124/228061645-ecd68eaa-4f08-4da2-8bd0-68774599785c.png">
