### ISSUE TITLE
migrate away from sourceforge svn for releases

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1551]
See general discussion here: https://github.com/INCATools/ontology-development-kit/issues/149

the dependence on sf svn is killing us...

**Comment by cmungall** [comment]
This is how it currently works:

 1. I run `make release`
 2. This runs the build pipeline and copies all release files into a locally checked out https://svn.code.sf.net/p/obo/svn/uberon/trunk/
 3. I cd to this dir and do `svn commit`
 4. I run this to copy to svn releases folder `head -1000 uberon.owl | grep versionIRI | perl -ne 'print "svn copy -m new-release https://svn.code.sf.net/p/obo/svn/uberon/trunk https://svn.code.sf.net/p/obo/svn/uberon/releases/$1\n" if /(\d\d\d\d-\d\d-\d\d)/`
 5. The OBO Central build will pick this up on its nightly run
     - see the build field https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/uberon.md
     - http://obofoundry.org/faq/what-is-the-build-field.html
 6. I massage the diff and copy to _posts here: https://github.com/uberon/uberon.github.io.git

There are various complex dependencies here. sf and svn are flaky. currently the obo central build seems to be failing on the pickup and is not propagating the latest release

**Comment by cmungall** [comment]
Have made a release going directly to S3, no SF. See Makefile for how this works. Only those with credentials can do this

have not yet made release notes

**Comment by matentzn** [comment]
Can I get credentials? There is a [breaking change](https://github.com/obophenotype/uberon/pull/1624) in the new release, and I would in any case like to know how Uberon releases are handled (maybe a topic for our next tete-a-tete).

**Comment by cmungall** [comment]
@kltm will be in touch

**Comment by anitacaron** [comment]
The current releases are executed using ODK and can be found in the GitHub Releases section.
