### ISSUE TITLE
Terms deleted from uberon-ext

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#1552]
A set of terms were unintentionally deleted from ext. It seems like there was a merge done and then terms were deleted in the next commit (but these terms seem to have already existed in ext? not sure why there was a merge).  @cmungall should I revert this commit, or does it require a more careful reintegration with the core file? 

https://github.com/obophenotype/uberon-phenoscape-ext/commit/2199080216571d1d9101467143695bcdea3d7b75 

Deleted:
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300261>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300262>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300263>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300264>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300265>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300266>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300267>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300268>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300269>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300270>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300271>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_4300272>))

**Comment by cmungall** [comment]
go ahead and revert

**Comment by balhoff** [comment]
@wdahdul @cmungall here is the revert PR: https://github.com/obophenotype/uberon-phenoscape-ext/pull/15

Please take a look at the readable diff: https://stars-app.renci.org/owldiff/diff?left=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fuberon-phenoscape-ext%2Fraw%2F3eb1bb8b56e2b56837ceb47fb6bcd579494d290b%2Fphenoscape-ext.owl&right=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fuberon-phenoscape-ext%2Fraw%2F2ee225f9dfd3ad433500397d7eec657afb9cc5a8%2Fphenoscape-ext.owl&loadimports=true

**Comment by balhoff** [comment]
Fixed by https://github.com/obophenotype/uberon-phenoscape-ext/pull/15
