### ISSUE TITLE
uberon-bridge-to-bspo.owl missing?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1554]
Only uberon-bridge-to-bspo.obo is present..

**Comment by megbalk** [comment]
That makes sense, as it looks like BSPO is imported but in the "Makefile", but none of BSPO terms come up when searching in UBERON.
I'd like to create lines across bones, and so having certain BSPO terms like "medial-lateral axis" and "medial side" would be super useful. 
Can this issue get fixed?

**Comment by ramonawalls** [comment]
It would also be super helpful to have a little more documentation on how imports are handled in uberon.

**Comment by balhoff** [comment]
@megbalk the Uberon BSPO import situation is a little unusual. I'm not sure what the original reasons were, but it looks like BSPO is downloaded and then merged into RO. Then an import module is extracted out of that RO file, but any tbox axioms are removed. So you only see BSPO relations in Uberon:

https://github.com/obophenotype/uberon/blob/d2168d95bcd5438575045ec5879634031277f4e8/Makefile#L219-L233

There are a lot of things in the Uberon makefile that could be updated to be closer to ODK style if someone can find the time. I think this is a separate issue from the bridge file that @matentzn is talking about.

**Comment by ramonawalls** [comment]
Thanks @balhoff. I will start a separate issue.

**Comment by ramonawalls** [comment]
Closing this issue in favor of the more specific question in #1608
