### ISSUE TITLE
NTR: skin of scalp 

### ISSUE THREAD

**Issue by bonitalam** [obophenotype/uberon#1556]
The ENCODE project would like to request "skin of scalp" term to be made to better annotate some biosamples. There is an existing FMA term for it, FMA:24757.

Definition: A zone of skin (UBERON:0000014) that is part of a scalp (UBERON:0000403)
Equivalent to: zone of skin and part of some scalp
Subclass of: part of some scalp

Thank you!

**Comment by matentzn** [comment]
@bonitalam If you want, I can walk you through doing your own pull requests as well. That way you dont have to wait :P up to you.

**Comment by bonitalam** [comment]
@matentzn sure, I'd be happy to learn how to do my own pull requests if you could guide me through the process. Thanks!

**Comment by matentzn** [comment]
Cool! I created you an ID range [here](https://github.com/obophenotype/uberon/blob/4112102b58b8257eadd27707330693f626d53248/uberon-idranges.owl#L99). This means that your first term will have the id UBERON:8200000, and then you count up from that, so UBERON:8200001, UBERON:8200002 etc.

The only file you should ever edit is the one called [uberon_edit.obo](https://github.com/obophenotype/uberon/blob/master/uberon_edit.obo).

Here is an example of a related term to the one you are proposing, written in OBO syntax:

```
[Term]
id: UBERON:0001084
name: skin of head
def: "A zone of skin that is part of a head [Automatically generated definition]." [OBOL:automatic]
synonym: "adult head zone of skin" EXACT [OBOL:automatic]
synonym: "head skin" EXACT []
synonym: "head zone of skin" EXACT [OBOL:automatic]
synonym: "zone of skin of adult head" EXACT [OBOL:automatic]
synonym: "zone of skin of head" EXACT [OBOL:automatic]
xref: FMA:12166
xref: FMA:24756
xref: MA:0000582
xref: NCIT:C52757
xref: SCTID:181484006
xref: UMLS:C0205029 {source="ncithesaurus:Head_Skin"}
is_a: UBERON:0000014 ! zone of skin
intersection_of: UBERON:0000014 ! zone of skin
intersection_of: part_of UBERON:0000033 ! head
```

As a first exercise, maybe try to express your NTRs (starting with this one here) in a similar fashion, and share it with me here.  

As a second step, I would try the following:

1. Make an UBERON fork for yourself
2. Insert your OBO code of the skin of scalp in the right part of the OBO file (the UBERON ids are sorted by number), so just under the `central retina` term.

```
[Term]
id: UBERON:8000004
name: central retina
....
```

3. Save the file, and and go to the uberon repo and make a pull request against your own fork. I will help you with that step by step if needed! 

Let's see how far we get. Good luck!

**Comment by bonitalam** [comment]
@matentzn Thank you for getting me started with it! Hopefully we can get through one successful PR. I have one quick question though, will my ID range interfere with Anne Thessen's? I just looked at that file you linked to and it seems like we both start at 8200000?

**Comment by matentzn** [comment]
Oops yes, hasty copy pasting :) thanks for spotting that! Check again, should be fine now.

**Comment by bonitalam** [comment]
Hi @matentzn, the range looks the same to me, maybe I am missing something? Should mine start at 8300000? 

`Datatype: idrange:19
Annotations: allocatedto: "Anne Thessen",
EquivalentTo: xsd:integer[> 8200000 , <= 8299999]

Datatype: idrange:20
Annotations: allocatedto: "Bonita Lam",
EquivalentTo: xsd:integer[> 8200000 , <= 8205000]`

I have formatted my potential NTR after the example you provided:
`[Term]
id: UBERON:8200000 or UBERON:8300000?
name: skin of scalp
def: "A zone of skin that is part of a scalp [Automatically generated definition]." [OBOL:automatic]
synonym: "adult scalp zone of skin" EXACT [OBOL:automatic]
synonym: “scalp skin" EXACT []
synonym: “scalp zone of skin" EXACT [OBOL:automatic]
synonym: "zone of skin of adult scalp” EXACT [OBOL:automatic]
synonym: "zone of skin of scalp” EXACT [OBOL:automatic]
xref: FMA:24757
created_by: https://orcid.org/0000-0001-9897-3238
is_a: UBERON:0000014 ! zone of skin
intersection_of: UBERON:0000014 ! zone of skin
intersection_of: part_of UBERON:0000403 ! scalp`

I assumed that the created_by should refer to my orcid id but please correct me if I am wrong. Thanks again for all the help!

**Comment by matentzn** [comment]
Hey @bonitalam , probably have not checked out the latest version:

https://github.com/obophenotype/uberon/blob/master/uberon-idranges.owl

Are you using a fork maybe? Else dont forget to git pull the master branch!

One thing I noted is that you use differently formatted quotation marks; like for the `scalp skin` synonym. They should all be the normal `"`. 

You also have all these `[OBOL:automatic]` comments in there; your term in not really created automatically (you can drop those annotations like in the `synonym: "scalp skin" EXACT []`. case. `[Automatically generated definition]` This seems to be redundant as well.

The rest looks good. The next step would be to paste this Term into uberon_edit.obo, open the file in protege, save it again (unless you make a minor change, you need to use `Save as` dialog). This ensures your definition is correctly formatted. Then you commit the change to your fork, and create a pull request! I think thats it. If you need a more detailed guide for anything, let me know!

**Comment by bonitalam** [comment]
Great, I see it now. Thanks @matentzn! I will make sure to check that the formatting is correct with the quotation marks and all.

**Comment by bonitalam** [comment]
Created a PR: https://github.com/obophenotype/uberon/pull/1558

**Comment by bonitalam** [comment]
Was handled in https://github.com/obophenotype/uberon/pull/1558
