### ISSUE TITLE
UBERON purl redirects to old version

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1559]
@cmungall @balhoff 

Currently the OBO purl of uberon points to[ a file on Berkley servers;](https://github.com/EBISPOT/OLS/issues/320) Is this still up to date? Because the file located there has a very old version IRI (2018), and there have been at least [two release since then](http://uberon.github.io/).

Can you check that the purl actually redirects to the latest release and share how the release is done end to end? Maybe as part of the [editors readme](https://github.com/obophenotype/uberon/blob/master/README-editors.txt)?

**Comment by balhoff** [comment]
I also see what @matentzn is describing. The berkeleybop.org files don't have the new releases. 
Another strange thing: if you look at the list of releases here: http://svn.code.sf.net/p/obo/svn/uberon/releases/

there is no entry for `2018-11-25`, which is the date returned by the files at the main PURLs currently on berkeleybop.org.

**Comment by cmungall** [comment]
Are you sure you have diagnosed this correctly? The uberon owl file on svn
is latest no? I think the bug is on obo central server side. See obo faq on
build tag

**Comment by balhoff** [comment]
@cmungall I think you are saying that the OBO PURL entry needs to point to `http://svn.code.sf.net/p/obo/svn/uberon/trunk/` rather than berkeleybop.

**Comment by matentzn** [comment]
> The uberon owl file on svn is latest no? 

There is indeed a directory on the SVN that corresponds to the latest release. Should we redirect the purl there?

> Are you sure you have diagnosed this correctly?

You say [here](https://github.com/obophenotype/uberon/issues/1551) that " currently the obo central build seems to be failing on the pickup and is not propagating the latest release". Not sure whether this relates to this here issue.

**Comment by matentzn** [comment]
Oh @balhoff just beat me :P Sorry.

**Comment by matentzn** [comment]
@balhoff that would work; However, just running a few wget on the svn - it seems considerably slower as a file system compared to the bbop ones..

**Comment by balhoff** [comment]
https://github.com/OBOFoundry/purl.obolibrary.org/pull/606

**Comment by balhoff** [comment]
If berkeleybop is supposed to be grabbing the files from there, then don't merge that PR.

**Comment by balhoff** [comment]
Okay, now I see what @cmungall means about the `build` tag. The current config has no build tag and it should.

**Comment by cmungall** [comment]
There is a build tag

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/uberon.md

```
build:
  checkout: svn --ignore-externals co http://svn.code.sf.net/p/obo/svn/uberon/trunk
  email_cc: cjmungall@lbl.gov
  system: svn
  method: vcs
  infallible: 1
```

The error is in the obo central build. There are silent errors being generated:

https://build.berkeleybop.org/job/simple-build-obo-all/lastBuild/console:

```
...
Fri Jan 31 05:08:26 PST 2020 :: ONTOLOGY: uberon
Fri Jan 31 05:08:26 PST 2020 ::   RUNNING: cd stage-svn-uberon &amp;&amp; svn --ignore-externals update
ERROR RUNNING: cd stage-svn-uberon &amp;&amp; svn --ignore-externals update [in uberon ] code: 256
```

It may be better to get rid of all dependencies on the central job, and merge Jim's PR. In the past we have balked at serving directly from svn as it was unreliable, so better to slurp into a reliable place.

But for now let me try and investigate...

**Comment by balhoff** [comment]
@cmungall thanks, I was thinking it had to be in the PURL config (I get confused about the two different config files).

**Comment by cmungall** [comment]
Looking at

https://build.berkeleybop.org/job/simple-build-obo-all/ws/stage-svn-uberon/

My guess is that for some reason svn update is failing, the files here are all old

I may try blowing away the workspace

**Comment by cmungall** [comment]
I added this to the project to change the release pipeline:

https://github.com/obophenotype/uberon/projects/3

**Comment by cmungall** [comment]
Maybe the easiest thing is if I just release the files directly to ontologies.berkeleybop s3 with a manual s3 step I will talk to @kltm

**Comment by uberon** [comment]
ok, now waiting for jenkins restart...

**Comment by cmungall** [comment]
clearing the jenkins job workspace and restarting fixed this

```
$ curl -L -s $OBO/uberon.owl | grep versionIRI
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/uberon/releases/2019-11-22/uberon.owl"/>
```
