### ISSUE TITLE
github.io pages appear somewhat broken

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1560]
Click [me](http://uberon.github.io/release/2019/11/22/release.html).

Formatting is off, and Download link is 404.

**Comment by matentzn** [comment]
@balhoff I am not sure, maybe you can help. None of the github IO pages work at all; what needs to be done to fix it? Where are the releases hosted so I can browse them all? The OBO foundry [review request](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1102) is asking for it :P

Also: https://github.com/obophenotype/uberon/issues/1531

**Comment by balhoff** [comment]
> Where are the releases hosted so I can browse them all?
http://purl.obolibrary.org/obo/uberon/releases/

**Comment by balhoff** [comment]
I don't know much about the github.io site. I agree, it is messed up (there is a Phenoscape image showing up all over the place). Hopefully @cmungall can take a look.

**Comment by anitacaron** [comment]
After moving Uberon to use ODK, the page is working https://obophenotype.github.io/uberon/
