### ISSUE TITLE
NTRs: left back and right back

### ISSUE THREAD

**Issue by zhengj2007** [obophenotype/uberon#1563]
For annotation of microbiome data (microbiomeDB.org), we need two terms, left back and right back to specify where the microorganisms were collected from.

Here are proposed labels, definitions and parents for the new terms.

Label: left back
Definition: Left part of the organism dorsal to a horizontal plane and bounded on one side by the same transverse plane.
Parent: dorsum (UBERON_0001137)

Label: right back
Definition: Right part of the organism dorsal to a horizontal plane and bounded on one side by the same transverse plane.
Parent: dorsum (UBERON_0001137)

**Comment by zhengj2007** [comment]
Hi @cmungall , could any UBERON developer help on it? Thanks!

**Comment by matentzn** [comment]
@zhengj2007 UBERON has become a mostly community curated resource, so typically everyone does their own edits where possible.. There are some amazing editors like @nicolevasilevsky who sometimes help out, but before I put her on this, can I ask: how many of these left / right terms do you expect you need? There are many anatomical entities that could be left or right, and especially regions like the back seed like they would have always left and right. Is this something we want to have in UBERON? Left / right for everything? I am not saying no (I would never) - just asking the question given the potential of almost doubling the size of uberon..

**Comment by nicolevasilevsky** [comment]
I'm happy to help, let me know!

**Comment by zhengj2007** [comment]
@matentzn Current these are only left/right terms we need for our database. We have already used UBERON 'left ear' and 'right ear'.  I have no idea what else we will need in the future. It depends on the data we will load into the database.

Thanks @nicolevasilevsky for willing help on it!

**Comment by matentzn** [comment]
Ok. For labels, shouldn't it be `left side of back` and `right side of back`?

**Comment by zhengj2007** [comment]
@matentzn sounds good to me.

**Comment by matentzn** [comment]
@nicolevasilevsky If you feel charitable, do you want to create these terms?

**Comment by nicolevasilevsky** [comment]
no problem, will do asap!
