### ISSUE TITLE
editor ID for UBERON terms

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1565]
If I edit an entity, which annotation property do I use to make a note that I've changed it?

For example, I noticed some tooth terms need assertions as the parent class is not and cannot be inferred from the definition. I'd like to add the assertion (subclass) for ease of search, but make sure that it is noted.

**Comment by ramonawalls** [comment]
@obophenotype/uberon-curators Any advise on this issue?

**Comment by cmungall** [comment]
You can put an axiom annotation on the assertion using the source property
thanks!
