### ISSUE TITLE
Typedefs and OBO declarations break downstream serialisation (again)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1569]
In uberon.obo, we have a bunch of dc typedefs, like so:

```
[Typedef]
id: dc-description
name: description
xref: http://purl.org/dc/elements/1.1/description
is_metadata_tag: true
```

This causes a problem downstream, that ontologies importing uberon.owl also import this:

```
<!-- http://purl.org/dc/elements/1.1/description -->
    <owl:AnnotationProperty rdf:about="http://purl.org/dc/elements/1.1/description">
        <oboInOwl:hasDbXref rdf:resource="http://purl.org/dc/elements/1.1/description"/>
        <oboInOwl:hasOBONamespace>uberon</oboInOwl:hasOBONamespace>
        <oboInOwl:id>dc-description</oboInOwl:id>
        <oboInOwl:is_metadata_tag rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</oboInOwl:is_metadata_tag>
        <oboInOwl:shorthand>dc-description</oboInOwl:shorthand>
        <rdfs:label>description</rdfs:label>
    </owl:AnnotationProperty>
```

This then, when converting it back into obo, leads to this:

```
[Typedef]
id: dc-description
name: description
namespace: uberon
xref: http://purl.org/dc/elements/1.1/description
is_metadata_tag: true
```

Which, unromantically leads to this:

```
LOST: property_value: http://purl.org/dc/elements/1.1/description "Ontology about C elegans phenotypes" xsd:string
GAINED: property_value: dc-description "Ontology about C elegans phenotypes" xsd:string
```

Not good. 

Possible solutions:
- @dosumis suggested to agree on a namespace for dc and dct terms, (like `dc` and `dct`). 
- We could require dc terms to be imported through some external mechanism (a separately curated DC subset fo OBO ontologies, maybe as part of IAO. 
- We could remove oio:namespace declarations from typedefs by default as part of the ODK importing mechanism.

@cmungall @balhoff

**Comment by matentzn** [comment]
@jamesoverton, would you mind to give an opinion for this? I am breaking my head over what to do here.. Thinking of doing so ROBOT remove annotations stuff by default when running extract. But there must be a better way?

**Comment by cmungall** [comment]
I don't think this is James' problem

this is just obo format hacking

**Comment by matentzn** [comment]
Oh I know! The reason I asked is because he may have dealt with this issue before and hacked it in some way I can copy..

**Comment by matentzn** [comment]
Since using base-merge (imports), this problem has never reappeared. Closing.
