### ISSUE TITLE
Henle fiber layer -new term request

### ISSUE THREAD

**Issue by iamdna** [obophenotype/uberon#1570]
Hi,
Can you please add a new term in the Eye Anatomy branch?
Term: Henle fiber Layer 
Synonym: HFL, nerve fiber layer of Henle
Definition: This layer contains bundles of unmyelinated cone and rod photoreceptor axons terminating in the pedicles and spherules that synapse in the retinal outer plexiform layer (OPL).
PMID: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3101665/

**Comment by matentzn** [comment]
@iamdna would you like to learn to make your own pull requests and add this term yourself? I could walk you through this!

**Comment by iamdna** [comment]
Hi, Unfortunately I don't have time to do this. Can you add the term please? Thanks, Rama

**Comment by nicolevasilevsky** [comment]
I can do it :)

**Comment by nicolevasilevsky** [comment]
@iamdna - is this term still needed?

**Comment by iamdna** [comment]
Yes, I need this term. Thanks!
