### ISSUE TITLE
Check OBO Dashboard results

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1576]
See http://obo-dashboard-test.ontodev.com/ro/dashboard.html

Fix all issues, OR if there are false positives, report back to ticket:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1076

**Comment by anitacaron** [comment]
All issues were fixed, and finally [dashboard](https://dashboard.obofoundry.org/dashboard/index.html) is green for Uberon 🎉

![Screenshot 2024-01-24 at 15 50 29](https://github.com/obophenotype/uberon/assets/2208124/a567c843-132a-4c6b-acd3-67f9eced3b2f)
