### ISSUE TITLE
cell part has 3 labels

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/uberon#1584]
I was trying to work on #1563 and was getting weird diffs and noticed that the term GO_0044464 cell part has three labels, including two that are obsolete cell part.

![image](https://user-images.githubusercontent.com/6722114/79822314-b6bc5780-8345-11ea-819e-f769684f881d.png)

cc @matentzn

**Comment by matentzn** [comment]
Can you create a pull request so I can see what you mean by weird diff?

**Comment by matentzn** [comment]
You can ignore the various labels now - they are coming from different imports (pato/go). This should not at all reflect in the edit file diff!

**Comment by nicolevasilevsky** [comment]
I created a PR, you can see it here:
https://github.com/obophenotype/uberon/pull/1585

Sounds like maybe this isn't an issue, I'll close this, thanks @matentzn!
