### ISSUE TITLE
dead links at http://uberon.github.io/release/2019/11/22/release.html

### ISSUE THREAD

**Issue by deustp01** [obophenotype/uberon#1598]
All the links I checked at the top of the web page get 404 - no found errors

**Comment by paola-scibite** [comment]
Hi,
Following up on @deustp01 's note above, this still seems to be broken. I was looking for release notes, not sure if they are produced for Uberon. Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Hi @deustp01 ,

There's a plan now to migrate contents from https://uberon.github.io/, and then obsolete that repository (#2045 ). So I'll close this ticket. Thanks,

Paola
