### ISSUE TITLE
NTR: ethmoidal vein

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1612]
Hi,

Would you please consider adding
UBERON:NEW ethmoidal vein

Axioms: not entirely sure as this is the first anatomy term I ever request, but I suppose at least subclass of 'head blood vessel' and 'vein'? 

"The ethmoidal veins are the venae comitantes (accompanying vein) of the ethmoidal arteries, and drain into the superior ophthalmic vein."

x-ref FMA:51770 Ethmoidal vein
x-ref https://en.wikipedia.org/wiki/Ethmoidal_veins

Ethmoidal veins are mentioned in UBERON:0011192 'superior ophtalmic vein': "... The ethmoidal veins drain into the superior ophthalmic vein. ...".

Thanks,
Paola (Roncaglia)

**Comment by paolaroncaglia** [comment]
@dosumis who's the best person for vascular terms please?

**Comment by RDruzinsky** [comment]
This is correct. In humans there are, typically,  anterior and posterior
ethmoidal arteries,  accompanied by the ethmoidal veins.

**Comment by paolaroncaglia** [comment]
@RDruzinsky 

> This is correct. In humans there are, typically, anterior and posterior ethmoidal arteries, accompanied by the ethmoidal veins.

Many thanks for your feedback, and sorry for the delay in acknowledging it. Best,
Paola

**Comment by paolaroncaglia** [comment]
Note for self: at time of editing, look into adding appropriate axioms (request review of pull request if unsure).

**Comment by paolaroncaglia** [comment]
Closing this as it's a duplicate of (part of) #2035 - ethmoidal vein is one of many FMA terms that are missing in Uberon and that relate to vasculature, see https://github.com/obophenotype/uberon/issues/2035#issuecomment-951659040.
