### ISSUE TITLE
Invalid Xrefs in human-view.obo

### ISSUE THREAD

**Issue by rpwagner** [obophenotype/uberon#1615]
While trying to [parse the human terms ontology using Pronto](https://github.com/althonos/pronto/issues/80) I hit an error with some of the Xrefs that don't match the [OBO format version 1.4 specification](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2.2.3).

```
>>> from pronto import Ontology
>>> uberon = Ontology('http://purl.obolibrary.org/obo/uberon/subsets/human-view.obo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pronto/ontology.py", line 154, in __init__
    cls(self).parse_from(_handle)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pronto/parsers/obo.py", line 38, in parse_from
    raise SyntaxError(s.args[0], location) from None
  File "http://purl.obolibrary.org/obo/uberon/subsets/human-view.obo", line 242452
    synonym: "intercalarium anterior process" EXACT [TAO:Bird and Mabee 2003]␊
                                                              ^
SyntaxError: expected QuotedString
>>> 
```

**Comment by balhoff** [comment]
@wdahdul is this a publication? Could these xrefs be replaced with a DOI?

**Comment by rpwagner** [comment]
I should mention there were several like this, with spaces in the X-ref.

**Comment by rpwagner** [comment]
Here's the list of bad references that I found. The file I was comparing against was one I was cutting synonyms out of to use, so the values in the `>` file are likely very inaccurate. I don't see a pattern to the terms with bad references, unfortunately.

[human-view.obo.bad-refs.diff.txt](https://github.com/obophenotype/uberon/files/4738565/human-view.obo.bad-refs.diff.txt)

**Comment by gouttegd** [comment]
Apparently the offending cross-references have been fixed, I can’t find any traces of them (or similarly bogus ones) now and Pronto has no troubles loading the `human-view.obo` product from the latest release.

Closing now.
