### ISSUE TITLE
Uberon release page is broken and this is reflected in BioPortal

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1617]
Hi (@cmungall ),

The links in the Uberon release page (https://uberon.github.io/) are somewhat broken. 
This issue seems to be reflected in BioPortal where the Version Numbers, Release and Download dates look unreliable: https://bioportal.bioontology.org/ontologies/UBERON
I was looking to download the CSV file from BioPortal, but I can't be sure it's the latest version. I was going to ask BioPortal, but I suspect the issue would need to be fixed at the source first. 
On the same topic, are release notes generated for Uberon please? 

In case it's useful, these issues were reported in https://github.com/obophenotype/uberon/issues/1463, https://github.com/obophenotype/uberon/issues/1560 and https://github.com/obophenotype/uberon/issues/1598.

Many thanks for looking into this!
Paola (Roncaglia)

**Comment by paolaroncaglia** [comment]
Note to self - see if this is out of date now

**Comment by paolaroncaglia** [comment]
uberon.github.io will be deprecated, and I've "pinged" the ncbo tracker re BioPortal not displaying versionIRI (see Jennifer's links above), so I'll close this.

**Comment by balhoff** [comment]
I opened a related issue: #2059.
