### ISSUE TITLE
Missing connections between types of reproductive system secretions

### ISSUE THREAD

**Issue by ashfinckh** [obophenotype/uberon#1619]
There seems to be a missed connection between the finding "female reproductive gland secretion" (UBERON:0006537) and the general finding "reproductive gland secretion" (UBERON:0022293) 

In addition to the grouping of the reproductive gland secretion findings, there is no connection between the female reproductive gland secretion finding and the finding  "vaginal fluid" (UBERON:0036243).

Thanks very much for your help.

![Screenshot 2020-06-23 at 14 22 49](https://user-images.githubusercontent.com/67323234/85407205-342d5f80-b563-11ea-9474-7bf5185500c4.png)

**Comment by cmungall** [comment]
@drseb - you are best to have Elk running all times + inferred view, you should see the inference

**Comment by drseb** [comment]
Thanks @ashfinckh . This is now working. Thanks @cmungall for approving the PR
