### ISSUE TITLE
Adding a whole bunch of species-specific terms

### ISSUE THREAD

**Issue by stevevanhooser** [obophenotype/uberon#1631]
Hi -

Some of the brain areas that I study are not represented in Uberon. These areas have particular labels in different species (ferret, squirrel, tree shrew), and some have homologies to other mammals but others do not. 

How can I add these areas to Uberon, and specify where they are in the brain (sub parts of) AND specifying their species? What about orders (some areas are part of examined mammals of the order Carnivora for example)?

Thanks
Steve

**Comment by balhoff** [comment]
Hi @stevevanhooser, @cmungall is best for info on logical design patterns for brain structures, but I can hopefully help with a couple things. If there are different labels, but the structures can fit into the same concept, we can create a single term and add multiple text labels as synonyms. If there are differences that should be distinguished by different logical axioms, we can create multiple concepts.

We have different ways of incorporating taxon information. Most commonly, this is a relation on the term such as `in_taxon some X` (e.g. X == Carnivora). This would say that every instance of the concept is found in an individual of Carnivora. This helps to identify logical inconsistencies. But if the concept is found in a taxon, but not exclusively, this kind of axiom wouldn't apply. We can add a non-logical annotation to the term such as `present_in_taxon X`.

**Comment by cmungall** [comment]
Thanks Steve

I think your analysis is spot on. Based on the information here, I would make a new PSS class, reuse V1, and make a [taxon-specific GCI](https://github.com/obophenotype/uberon/wiki/Evolutionary-variability-GCIs) linking V1 to PSS.

I find issues of homology, lumping, and splitting are hardest in the brain. You may still want to maintain some separate ferret neuroanatomy outside uberon and map to it. This allows the more precise species-specific relationships and nomenclature to be encoded in a more straightforward way, at the expense of mapping. I don't know if there are any plans to make a ferret neuroanatomy atlas as there is for other species, cc @tgbugs. If your main use case is just for a few key regions and experiments I'd say make uberon the primary representation.

We are working on tools to make more intuitive species-specific views. For example, if you encode the link between V1 and PSS as a GCI it's harder to working with directly in uberon (which of course provides safety from making incorrect inferences in other mammals), but in the ferret view it would be a straightforward edge.

**Comment by cmungall** [comment]
Hi @stevevanhooser we are currently closing all old tickets but feel free to open this if you need more help! I'm really keen to add new brain terms!
