### ISSUE TITLE
Bad URI for image depiction

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#1634]
For [pharyngeal slit](http://purl.obolibrary.org/obo/UBERON_0008815) there is a 'depicted by' value:

`280px-Gill:slits.png^^xsd:anyURI`

The text isn't a URI.

**Comment by anitacaron** [comment]
At least for this case, the URI was expanded correctly somehow, and now it even shows on the OLS.

![Image](https://github.com/obophenotype/uberon/assets/2208124/a48c63ff-fc31-4878-bc66-c0513d305e7e)
