### ISSUE TITLE
Grouping term 'metabolic zone of liver'

### ISSUE THREAD

**Issue by mkeays** [obophenotype/uberon#1639]
**Preferred term label:**
metabolic zone of liver

**Synonyms**
hepatic acinus metabolic zone

**Definition (free text, please give PubMed ID)**
Any of the three metabolic zones found in the hepatic acinus. Liver tissue is heterogenous at the level of morphometry and histochemistry. This heterogeneity is linked to the position of a cell within the functional unit of the tissue, which, in turn, is related to the blood supply: Cells located in the upstream zone differ from those in the downstream zone with respect to subcellular structures, key enzymes, translocators, and receptors and, therefore, have different metabolic capacities. This is the basis for “metabolic zonation,” a concept first proposed for carbohydrate metabolism and later expanded to include amino acid and ammonia metabolism, xenobiotic metabolism, protective metabolism, and formation of plasma proteins.

[Jungermann and Keitzmann (1996)](https://pubmed.ncbi.nlm.nih.gov/8839925/), PMID:8839925

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
[organ subunit](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000063)

**Your nano-attribution (ORCID)**
0000-0003-2034-601X

Also cc @cmungall for comment.

**Comment by dosumis** [comment]
Maybe don't limit to 3 currently defined in case more are defined in future.

**Comment by mkeays** [comment]
@dosumis OK, will change that part to: "Any of the metabolic zones found in the hepatic acinus."
