### ISSUE TITLE
revise logical definition for 'mesenchyme'

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#1641]
Currently:

`mesenchyme EquivalentTo tissue and (composed primarily of some mesenchymal stem cell)`

In https://github.com/geneontology/go-ontology/issues/19984, @dosumis suggests this is incorrect and needs to be revised.

**Comment by cmungall** [comment]
I think we first have to agree on a conceptualization of mesenchyme.

This is complicated by the different ways the term has been used; see the discussion in the Invertebrates textbook: https://archive.org/details/invertebratesnde00brus/page/n240/mode/2up (which also talks about vertebrate usage)

This also discusses different lineages. In inverts largely from ectoderm, in verts from mesoderm -- but I think this is vastly simplified. In think in non-vert chordates and even other deuterostomes it comes from mesoderm. And in verts we have classes in uberon such as portions of mesoderm from neural crest... which is ectoderm.

For now I am simplifying definition to be aggregate of mesenchymal cells (see linked ticket for discussion of MC), and making the lineage restriction a has-developmental-contribution-from with taxon-GCI to vert.

**Comment by dosumis** [comment]
I think this is a good first fix.  But we really need a whole mini project to fix mesenchyme.  Perhaps worthwhile making a project board and discussing on a call.
