### ISSUE TITLE
Periportal zone of liver lobule

### ISSUE THREAD

**Issue by rich-brennan** [obophenotype/uberon#1648]
**Preferred term label:**
Periportal Region

**Synonyms**
liver acinus zone 1

**Definition (free text, please give PubMed ID)**
The hepatocellular cords are mostly one or two layers thick and are divided into three zones: 1, 2, and 3 of the acinus, and periportal (PP), mid‐ (MZ), and centrilobular (CL) zones of the lobule. Blood flows from the portal tract (PT) to the central vein, also referred to as terminal hepatic venule (CV/THV) (PMID: 30992875)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
Liver Lobule (UBERON:0004647)

**Your nano-attribution (ORCID)**
0000-0002-0449-2730

**Comment by rich-brennan** [comment]
The differential sensitivity of cells in these zones to chemical injury means that the inclusion of the zone(s) affected is an important component of liver histopathology diagnoses. The NCIT ontology includes liver acinus zones as daughter terms of Digestive System Part (NCIT:C25763) – Liver Acinus Zone I (NCIT:C32993); Liver Acinus Zone 2 (NCIT:C32994); Liver Acinus Zone 3 (NCIT:C32995)*. Suggest adding lobule regions as daughter terms of Liver Lobule (UBERON:0004647). The preferred terminology for Toxicological Pathology would be: 
a.	“Periportal Region” (equivalent to Zone 1*)
b.	“Midzonal Region” (Zone 2)
c.	“Centrilobular Region” (Zone 3)
*Note: technically acinus zones and lobule regions are not exactly the same since acinus zones are defined by functional differences whereas periportal, centrilobular, and midzonal regions are defined anatomically, however they are practically equivalent and the Wikipedia page for liver lobules conflates them.

**Comment by mkeays** [comment]
Hi @rich-brennan , recently [hepatic acinus periportal zone](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_8400001) was added, as well as [hepatic acinus intermediary zone](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_8400003) and [hepatic acinus perivenous zone](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_8400002) -- do you feel these meet requirements? We could update the definitions/synonyms if you think that makes sense.

**Comment by rich-brennan** [comment]
Hi @mkeays 

That must have been a recent addition - my bad for not double checking before submitting the request.

Technically the liver acinus and the liver lobule are different concepts, though often conflated. Lobule refers to the hexagonal area defined by the portal triad vessels surrounding the central vein, with the subregions defined by distance from the central vein and proximity to the portal triad. Acinar zones are defined by the areas of decreasing oxygen tension radiating around the portal triad (i.e. structural vs. functional definitions). When segmenting the acinus into it’s zones, the standard terminology would be acinar zone 1, 2, & 3 (rather than periportal etc.). Using perivenous in this context is confusing, since the portal triad includes the hepatic portal vein, whereas I think you were trying to convey the central vein proximity of zone 3 with hepatic acinus perivenous zone. I would recommend changing the preferred term for acinar zones to acinar zone 1/2/3.

In toxicological pathology, the liver lobule is the most widely used concept, since it’s more readily observable and intuitive than the acinus. Toxicology terminology customarily uses periportal, midzonal, and centrilobular to approximate the distance of an observed lesion from the central vein, and captures the functional differences in oxygen tension and metabolic enzyme expression across the lobule well enough to assist mechanistic interpretation of the observation.

Ideally UBERON should capture both anatomical concepts. Is it possible to do that and to cross-reference them in a way that recognizes their overlap (e.g. that acinar zone 1 is a related but not exact synonym of periportal region)? In this case I would recommend keeping both the hepatic acinus, and liver lobule concepts and including subclasses for zonation as follows:

Hepatic acinus
-	Acinar zone 1
-	Acinar zone 2
-	Acinar zone 3

Liver lobule
-	Periportal region
-	Midzonal region
-	Centrilobular region

Definitions and synonyms will need to be carefully crafted to highlight the overlap while maintaining the conceptual differences.

**Comment by mkeays** [comment]
Adding here for info after discussion with @rich-brennan -- will update the above mentioned hepatic acinus zones to rename them and update their definitions as Richard suggests, as well as creating new terms for the liver lobule zones.

Richard explained: "the acinus could be considered a subdivision of the lobule, though an acinus technically covers two lobules since it is centered around the branches of the hepatic artery. See here for a visual https://medical-dictionary.thefreedictionary.com/liver+acinus (there’s some inconsistency in the geometry of the acinar zones as well – e.g. http://www.vivo.colostate.edu/hbooks/pathphys/digestion/liver/histo_acinus.html)" . 

The pre-existing term for [hepatic acinus](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001172) already has the following relations, which I think make sense in light of this info:
 - 'has part' some ('part of' some 'liver lobule')
 - 'part of' some 'liver parenchyma'
 - 'has part' some ('part of' some 'portal lobule')

**Comment by mkeays** [comment]
Hi @rich-brennan , I've updated the hepatic acinus zones as discussed, and added the three liver lobule regions. You can see the commit here: 199c224cdae133c3fc2c7724d10a9d1cdf7c117b -- you'll have to scroll down to the relevant sections, the green parts are additions and the red parts are deletions. Let me know what you think! Thanks, Maria.

**Comment by rich-brennan** [comment]
Thanks Maria! Looks great to me.
