### ISSUE TITLE
Midzonal region of liver lobule

### ISSUE THREAD

**Issue by rich-brennan** [obophenotype/uberon#1649]
**Preferred term label:**
Midzonal region

**Synonyms**
Liver acinus zone 2

**Definition (free text, please give PubMed ID)**
The hepatocellular cords are mostly one or two layers thick and are divided into three zones: 1, 2, and 3 of the acinus, and periportal (PP), mid‐ (MZ), and centrilobular (CL) zones of the lobule. Blood flows from the portal tract (PT) to the central vein, also referred to as terminal hepatic venule (CV/THV) (PMID: 30992875)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
Liver Lobule (UBERON:0004647)

**Your nano-attribution (ORCID)**
0000-0002-0449-2730

**Comment by rich-brennan** [comment]
The differential sensitivity of cells in these zones to chemical injury means that the inclusion of the zone(s) affected is an important component of liver histopathology diagnoses. The NCIT ontology includes liver acinus zones as daughter terms of Digestive System Part (NCIT:C25763) – Liver Acinus Zone I (NCIT:C32993); Liver Acinus Zone 2 (NCIT:C32994); Liver Acinus Zone 3 (NCIT:C32995)*. Suggest adding lobule regions as daughter terms of Liver Lobule (UBERON:0004647). The preferred terminology for Toxicological Pathology would be: 
a.	“Periportal Region” (equivalent to Zone 1*)
b.	“Midzonal Region” (Zone 2)
c.	“Centrilobular Region” (Zone 3)
*Note: technically acinus zones and lobule regions are not exactly the same since acinus zones are defined by functional differences whereas periportal, centrilobular, and midzonal regions are defined anatomically, however they are practically equivalent and the Wikipedia page for liver lobules conflates them.

**Comment by mkeays** [comment]
Added in #1648
