### ISSUE TITLE
Liver subcapsular region

### ISSUE THREAD

**Issue by rich-brennan** [obophenotype/uberon#1651]
**Preferred term label:**
Subcapsular region of liver

**Synonyms**
Liver subcapsular region

**Definition (free text, please give PubMed ID)**
Region of liver parenchyma immediately below the capsule (PMID:30992875)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
liver (UBERON:0002107)

**Your nano-attribution (ORCID)**
0000-0002-0449-2730

**Comment by rich-brennan** [comment]
UBERON lacks a specific term for the subcapsular region of the liver, which is frequently specified in pathology diagnoses. Did not find an equivalent term in any OLS ontology.

**Comment by mkeays** [comment]
Adding as child of [liver parenchyma](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001280) with `part_of` relationship to [liver](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002107), `adjacent_to` relationship to [capsule of liver](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0016479).

**Comment by mkeays** [comment]
Added UBERON:8400024.
