### ISSUE TITLE
Liver Serosa

### ISSUE THREAD

**Issue by rich-brennan** [obophenotype/uberon#1652]
**Preferred term label:**
Liver serosa

**Synonyms**
Serosa of liver (FMA:15811)
Tunica serosa hepatis

**Definition (free text, please give PubMed ID)**
Hepatic serous coat; peritoneal covering of the liver, enclosing almost all except for a triangular area on its posterior surface (the "bare area of the liver") and a smaller area where the liver and gallbladder are in direct contact. (https://medical-dictionary.thefreedictionary.com/serosa+of+liver)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
liver (UBERON:0002107)

**Your nano-attribution (ORCID)**
0000-0002-0449-2730

**Comment by rich-brennan** [comment]
FMA ontology has term Serosa of liver (FMA:15811), suggest this term is adopted as “liver serosa” to UBERON

**Comment by rich-brennan** [comment]
UBERON lacks a specific term for the subserosal region of the liver. A generic UBERON term for subserosa (UBERON:0012375) exists. FMA (Foundational Model of Anatomy Ontology) includes a term for Subserosa of liver (FMA:15812) which should be adopted for UBERON

**Comment by mkeays** [comment]
Other serosa in UBERON are children of [serous membrane](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000042) -- will use this as parent and add `part_of` relationship to [liver](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002107).

**Comment by mkeays** [comment]
Added UBERON:8400021.
