### ISSUE TITLE
Subserosa of liver

### ISSUE THREAD

**Issue by rich-brennan** [obophenotype/uberon#1653]
**Preferred term label:**
Liver subserosa

**Synonyms**
Subserous layer of liver, Subserosal tissue of liver, Tela subserosa (Hepar), Hepatic subserosa

**Definition (free text, please give PubMed ID)**
Subserosal tissue of liver (FMA:15812)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
liver (UBERON:0002107)
or liver serosa (existing UBERON NTR)
and subserosa (UBERON:0012375)

**Your nano-attribution (ORCID)**
0000-0002-0449-2730

**Comment by rich-brennan** [comment]
UBERON lacks a specific term for the subserosal region of the liver. A generic UBERON term for subserosa (UBERON:0012375) exists. FMA (Foundational Model of Anatomy Ontology) includes a term for Subserosa of liver (FMA:15812) which should be adopted for UBERON

**Comment by mkeays** [comment]
Added UBERON:8400023.
