### ISSUE TITLE
duodeno-jejunal junction

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1657]
**Preferred term label:**
duodeno-jejunal junction

**Synonyms**
duodenojejunal flexure, duodeno-jejunal flexure, duodenojejunal junction

**Definition (free text, please give PubMed ID)**
(Derived from textbook Gray's Anatomy)
The duodenojejunal (DJ) flexure or junction is the anatomical border between the duodenum and the jejunum.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
Duodenum
http://purl.obolibrary.org/obo/UBERON_0002114

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Comment by paolaroncaglia** [comment]
cc @ngeorgeebi 

The requested term 'duodeno-jejunal junction' seems in scope for Uberon to me. It is referred to in the definition of UBERON:0000642. If it’s approved, I’d add it as follows:

duodeno-jejunal junction

“The anatomical border between the duodenum and the jejunum.”

subclass of organ part
part of small intestine (not duodenum)

Taxon constraint: the taxon notes for duodenum and jejunum suggest that the new term might potentially be applicable to some higher vertebrates beyond mammals. However PMID: 29064554 “…showed the anatomical similarities and dissimilarities of the duodenojejunal flexure among the mammals”. The term is used for mouse though (PMID: 23961897). I’d welcome feedback from others please. 

Dbxrefs:
https://en.wikipedia.org/w/index.php?title=Duodenojejunal_flexure&oldid=937307798
TA98:A05.6.02.009 (is this the correct format?)
TA2:2952 (is this the correct format?)
FMA:15957
https://orcid.org/0000-0003-4183-8865

synonyms: 
duodenojejunal flexure
duodeno-jejunal flexure
duodenojejunal junction
flexura duodenojejunalis (latin term)

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
I created UBERON:8410000 duodeno-jejunal junction, it will be in the next Uberon release (there isn't a precise scheduled date yet, but I will ask at the editors' call on Monday). Thanks.
