### ISSUE TITLE
Add Meissner's plexus as synonym of submucous nerve plexus

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1658]
**Uberon term**
submucous nerve plexus (http://purl.obolibrary.org/obo/UBERON_0005304)

**Synonym to be added**
Meissner's plexus; submucosal nerve plexus

**broad/exact/narrow/related ?**
exact

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
“Meissner's plexus” is already a related synonym of ‘submucous nerve plexus’ (http://purl.obolibrary.org/obo/UBERON_0005304). Are you suggesting that we make it an exact synonym instead? The cross-referenced Wikipedia entry says “German Georg Meissner was one of the first to further research the nervous system and found Meissners' plexus.” but a citation is missing, and I’ve noticed that eponyms are sometimes hard to trace back with certainty. So I’d rather leave the scope as related as it is currently; ‘submucous nerve plexus’ is in fact retrieved if one searches HCAO with “Meissner's plexus” in OLS.
“submucosal nerve plexus” is already an exact synonym of ‘submucous nerve plexus’.
I’d close this ticket, but let me know if you have any concern.
Thanks,
Paola

**Comment by ngeorgeebi** [comment]
Hi Paola, sorry I didn't get bk to you on this sooner. If it is a related synonym and is retrieved when searching Meissner's plexus, that is good for us. Thanks!

**Comment by paolaroncaglia** [comment]
> Hi Paola, sorry I didn't get bk to you on this sooner. If it is a related synonym and is retrieved when searching Meissner's plexus, that is good for us. Thanks!

Yes, it's the top Uberon result when searching OLS. Cheers.
