### ISSUE TITLE
sigmoid junction

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1659]
**Preferred term label:**
sigmoid junction

**Synonyms**
descending sigmoid junction; sigmoid flexure; 

**Definition (free text, please give PubMed ID)**
The junction between the descending colon and the sigmoid colon

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
sigmoid colon http://purl.obolibrary.org/obo/UBERON_0001159

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Comment by ngeorgeebi** [comment]
edit: can remove sigmoid flexure as a synonym - thanks!

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
I will add as:

UBERON:NEW sigmoid junction
subclass of anatomical junction
part of proximal-distal subdivision of colon
The anatomical junction between the descending colon and the sigmoid colon.
Synonyms: descending-sigmoid junction; descending-sigmoid colon junction
https://orcid.org/0000-0003-4183-8865
PMID: 27233374

Thanks,
Paola

**Comment by ngeorgeebi** [comment]
@paolaroncaglia can we rename this to descending sigmoid junction?

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 

> can we rename this to descending sigmoid junction?

Sure, I'll modify the "summary" in my previous comment to have 'descending sigmoid junction' as primary label and 'sigmoid junction' as a synonym.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
Your request has been added as follows:

[Term]
id: UBERON:8410016
name: descending sigmoid junction
def: "The anatomical junction between the descending colon and the sigmoid colon." [https://orcid.org/0000-0003-4183-8865, PMID:27233374]
synonym: "descending-sigmoid colon junction" EXACT []
synonym: "descending-sigmoid junction" EXACT []
synonym: "sigmoid junction" BROAD []
intersection_of: UBERON:0007651 ! anatomical junction
intersection_of: connects UBERON:0001158 ! descending colon
intersection_of: connects UBERON:0001159 ! sigmoid colon
relationship: part_of UBERON:0000168 ! proximal-distal subdivision of colon
created_by: http://orcid.org/0000-0002-2825-0621

It will be in the next Uberon release, which should happen quite soon. Thanks.
