### ISSUE TITLE
Add Left colic vein as uberon term

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1660]
**Preferred term label:**
left colic vein

**Synonyms**

**Definition (free text, please give PubMed ID)**
The left colic vein drains the descending colon. It is a tributary of the inferior mesenteric vein, and follows the path of its corresponding artery, the left colic artery. (https://en.wikipedia.org/wiki/Left_colic_vein)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
inferior mesenteric vein  http://purl.obolibrary.org/obo/UBERON_0001215

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Comment by paolaroncaglia** [comment]
@ngeorgeebi
I will add this as follows, similar to the existing ‘middle colic vein’:

UBERON:NEW left colic vein
Equivalent to:
portal vein and drains some descending colon and tributary_of some inferior mesenteric vein
A portal vein that drains the descending colon. It is a tributary of the inferior mesenteric vein, and follows the path of its corresponding artery, the left colic artery.
https://en.wikipedia.org/w/index.php?title=Left_colic_vein&oldid=964575339
FMA:15394
https://orcid.org/0000-0003-4183-8865

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
Your request was added as

[Term]
id: UBERON:8410017
name: left colic vein
def: "A portal vein that drains the descending colon. It is a tributary of the inferior mesenteric vein, and follows the path of its corresponding artery, the left colic artery." [https://orcid.org/0000-0003-4183-8865, WikipediaVersioned:Left_colic_vein&oldid=964575339]
xref: FMA:15394
intersection_of: UBERON:0002017 ! portal vein
intersection_of: drains UBERON:0001158 ! descending colon
intersection_of: tributary_of UBERON:0001215 ! inferior mesenteric vein
created_by: http://orcid.org/0000-0002-2825-0621
