### ISSUE TITLE
right colic vein

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1661]
**Preferred term label:**
right colic vein

**Synonyms**

**Definition (free text, please give PubMed ID)**
The right colic vein drains the ascending colon, and is a tributary of the superior mesenteric vein. It travels with its corresponding artery, the right colic artery. (https://en.wikipedia.org/wiki/Right_colic_vein)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
superior mesenteric vein http://purl.obolibrary.org/obo/UBERON_0001138

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Comment by paolaroncaglia** [comment]
@ngeorgeebi
I will add this as follows, similar to the existing ‘middle colic vein’:

UBERON:NEW right colic vein
Equivalent to:
portal vein and drains some ascending colon and tributary_of some superior mesenteric vein
A portal vein that drains the ascending colon. It is a tributary of the superior mesenteric vein, and travels with its corresponding artery, the right colic artery.
https://en.wikipedia.org/w/index.php?title=Right_colic_vein&oldid=870898828
FMA:15407
https://orcid.org/0000-0003-4183-8865

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
Your request was added:

[Term]
id: UBERON:8410018
name: right colic vein
def: "A portal vein that drains the ascending colon. It is a tributary of the superior mesenteric vein, and travels with its corresponding artery, the right colic artery." [https://orcid.org/0000-0003-4183-8865, WikipediaVersioned:Right_colic_vein&oldid=870898828]
xref: FMA:15407
intersection_of: UBERON:0002017 ! portal vein
intersection_of: drains UBERON:0001156 ! ascending colon
intersection_of: tributary_of UBERON:0001138 ! superior mesenteric vein
created_by: http://orcid.org/0000-0002-2825-0621
