### ISSUE TITLE
Jejuno-ileal junction

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1662]
**Preferred term label:**
Jejuno-ileal junction

**Synonyms**
jejunoileal junction

**Definition (free text, please give PubMed ID)**
The area where the jejunum ends and the ileum part of the intestine begins. Although there is no clear distinct section, the ileum is narrower and has smaller villi than the jejunum 

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
Jejunum  http://purl.obolibrary.org/obo/UBERON_0002115

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
Could you please provide a reference for jejuno-ileal junction? Thanks. I'll add the term with your ORCID anyway.

Notes for self:
subclass of anatomical junction
part of small intestine
https://orcid.org/0000-0003-4183-8865

**Comment by ngeorgeebi** [comment]
Hi @paolaroncaglia sorry about the missing references. Information I used for this term can be found here: https://www.sciencedirect.com/science/article/pii/B9781437722062000683 and here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3210370/

**Comment by paolaroncaglia** [comment]
Thanks @ngeorgeebi !
Notes for self: the dbxrefs above are:
https://doi.org/10.1016/B978-1-4377-2206-2.00068-3 
PMID:21802415

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
Last one for today, will be in the next Uberon release:

[Term]
id: UBERON:8410019
name: jejuno-ileal junction
def: "The area where the jejunum ends and the ileum part of the intestine begins. Although there is no clear distinct section, the ileum is narrower and has smaller villi than the jejunum." [DOI:10.1016/B978-1-4377-2206-2.00068-3, https://orcid.org/0000-0003-4183-8865, PMID:21802415]
synonym: "jejunoileal junction" EXACT []
intersection_of: UBERON:0007651 ! anatomical junction
intersection_of: connects UBERON:0002115 ! jejunum
intersection_of: connects UBERON:0002116 ! ileum
relationship: part_of UBERON:0002108 ! small intestine
created_by: http://orcid.org/0000-0002-2825-0621
