### ISSUE TITLE
'uterine tube infundibulum' should be a child of 'fallopian tube'

### ISSUE THREAD

**Issue by mshadbolt** [obophenotype/uberon#1664]
**Uberon term**
The term uterine tube infundibulum : http://purl.obolibrary.org/obo/UBERON_0003984 does not appear as a child of fallopian tube fallopian tube : http://purl.obolibrary.org/obo/UBERON_0003889

**Suggested revision and reasons**
I believe this should be classified as a child of 'fallopian tube' along with the other parts of the fallopian tube.

tag @paolaroncaglia

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
’uterine tube infundibulum' and ’fallopian tube' are already connected in Uberon, however, not by the relationship you suggest (‘uterine tube infundibulum' part_of 'fallopian tube’), but by the following:
'fallopian tube' connects some ‘uterine tube infundibulum’
'fallopian tube' connects some ‘uterus’
I agree that 'uterine tube infundibulum' should be a part_of child of 'fallopian tube' in mammals, see https://en.wikipedia.org/wiki/Fallopian_tube#Structure (“The Fallopian tube is composed of four parts. These are, described from near the ovaries to inwards near the uterus, the infundibulum…”). However, I think that Uberon aims at being species-inclusive wherever possible, and I'm not sure if the patrimony that you suggest would be more universally acceptable.
Could someone more expert than me weigh in on this please?
Thanks,
Paola

**Comment by dosumis** [comment]
> I agree that 'uterine tube infundibulum' should be a part_of child of 'fallopian tube' in mammals

Is it even present outside of Mammals? I'd change to part_of unless there are really good examples of species we need to represent where this is not true.

**Comment by dosumis** [comment]
CC @emquardokus  - is this covered in the ASCT-b tables?

**Comment by paolaroncaglia** [comment]
Update: as agreed at the CL meeting today, unless others comment, I'll make a pull request following @dosumis ' comment, and ask @cmungall to review.

**Comment by emquardokus** [comment]
@dosumis the female reproductive organs have only just been added to HuBMAP, so we are reaching out to those groups now for completing ASCT-B tables for them.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
@dosumis 
Looking at [uterine tube infundibulum](http://purl.obolibrary.org/obo/UBERON_0003984) more carefully, it has an annotation property "present in taxon: Aves" and a general class axiom "'uterine tube infundibulum' and ('part of' some Mammalia) SubClassOf 'part of' some 'fallopian tube'". (Marion, this axiom is not visible in OLS.) This suggests that the structure does exist outside of mammals, where it's not part of fallopian tubes (which are exclusive to mammals). So we can't generalize the part of statement. We might, if desired, 
- [ ] Add a taxon note to make the general class axiom explicit and aid curators: "In mammals, the uterine tube infundibulum is part of the fallopian tube. In Aves, where there is no fallopian tube, the uterine tube infundibulum is part of the oviduct."

I'll leave this ticket open until after the holidays so you have a chance to comment. If I don't hear from anyone, I'll add the taxon note and make a pull request asking Chris to review (I'll reference this comment for convenience). Thanks.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
FYI, my suggestion in https://github.com/obophenotype/uberon/issues/1664#issuecomment-750336501 was approved and committed. It will be visible in the next Uberon release. Thanks.
