### ISSUE TITLE
NTR: zones of prostate

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1670]
Stemming from https://github.com/HumanCellAtlas/ontology/issues/65, https://github.com/HumanCellAtlas/ontology/issues/66 and https://github.com/HumanCellAtlas/ontology/issues/67

The Human Cell Atlas needs terms to represent the 3 zones of the prostate gland (peripheral, central and transition, see https://en.wikipedia.org/wiki/Prostate#Structure). This type of distinction into grouping terms is relevant for cancer research. Several part-of children of UBERON:0002367 ‘prostate gland’ already exist, but it seems to me that it’s not possible to assign them precisely to one of the 3 zones above; rather, each of the 3 zones surrounds other anatomical areas (e.g. “Central zone … surrounds the ejaculatory ducts”).
Would the creation of terms for peripheral, central and transition zone of prostate be in scope for Uberon?
In GO we allowed similar grouping terms for some ciliary parts (in that case the rationale was based, if I remember well, on microscopy or antibody observations where a finer distinction wasn’t possible).
If this is not in scope for Uberon, I’ll add to EFO.

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
cc @rachadele

**Comment by cmungall** [comment]
This is in scope

Do you have any indication as to applicability beyond human? See also #665.

**Comment by paolaroncaglia** [comment]
@cmungall 

> This is in scope

Great, thanks for your prompt feedback!

> Do you have any indication as to applicability beyond human? See also #665.

I don't have any specific indication and would need to do some in-depth reading. The Wikipedia entry reads "[The prostate gland] is found only in some mammals. It differs between species anatomically, chemically, and physiologically" so I expect your question may not be easy to respond to with precision, and it may be safer to be more conservative rather than less. Tagging @rachadele who requested the terms in case she wishes to add anything. Thanks.

**Comment by paolaroncaglia** [comment]
This might be helpful, linking here before I leave for the day:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5932577/

**Comment by rachadele** [comment]
Disclaimer: I'm not a urologist, but according to the paper @paolaroncaglia linked, it doesn't look like the murine prostate has "zones". From what i've read, prostate "zones" are specific to humans (and probably close primate relatives). I believe they're mostly relevant to urologists studying prostate enlargement/cancer. 

The data set I requested these terms for [https://doi.org/10.1016/j.celrep.2018.11.086] demonstrates that cell type clusters from scRNAseq of prostate tissue aren't specific to the zone they're sampled from. I only requested them to better represent sample collection protocols. I hope this helps!

**Comment by paolaroncaglia** [comment]
@rachadele thanks!
@cmungall shall we then add the terms in Uberon with a TC for Homo sapiens?

**Comment by paolaroncaglia** [comment]
@rachadele 
FYI, at the Uberon editors' call earlier this week it was resolved that I'll add the prostate zone terms as "found in Homo sapiens", to be on the safe side, as we don't know much about other primates. Thanks.

**Comment by paolaroncaglia** [comment]
Summing up/notes for self: I will add the 3 new terms as follows:

1) Preferred term label
transition zone of prostate

Synonyms
prostate transition zone
transition zone of human prostate

Textual definition
The region of the prostate gland anterior to the central and peripheral zones, surrounding the proximal urethra. It is the zone of the prostate gland that grows the most throughout life, and is responsible for benign prostatic hypertrophy.
PMID:29038334
PMID:30566875

Suggested parent term
http://purl.obolibrary.org/obo/UBERON_0002367
Add TC: found in Homo sapiens

Attribution
https://orcid.org/0000-0002-7431-4139

2) Preferred term label
peripheral zone of prostate

Synonyms
prostate peripheral zone
peripheral zone of human prostate

Textual definition
The region of the prostate that is located posterior to central and transition zones, surrounding the distal urethra. It is the zone of origin for the vast majority of prostatic cancers.
PMID:29038334
PMID:30566875

Suggested parent term
http://purl.obolibrary.org/obo/UBERON_0002367
Add TC: found in Homo sapiens

Attribution
https://orcid.org/0000-0002-7431-4139

3) Preferred term label
central zone of prostate

Synonyms
prostate central zone
central zone of human prostate

Textual definition
The region of the prostate gland that is located between the peripheral and transition zones, surrounding the ejaculatory ducts. It gives rise to a very small percentage of prostate cancers, often aggressive and invading the seminal vesicles.
PMID:29038334
PMID:30566875

Suggested parent term
http://purl.obolibrary.org/obo/UBERON_0002367
Add TC: found in Homo sapiens

Attribution
https://orcid.org/0000-0002-7431-4139

**Comment by paolaroncaglia** [comment]
@rachadele 
These terms have been added to Uberon and will be available in the upcoming Uberon release:
UBERON:8410025 transition zone of prostate
UBERON:8410026 peripheral zone of prostate
UBERON:8410027 central zone of prostate
They should be automatically imported in the next HCAO release (sceduled for Feb. 18th).
Thanks,
Paola
