### ISSUE TITLE
NTR: glomus coccygeum

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1674]
**glomus coccygeum**
This is referred to in the def of UBERON:0005464 median sacral artery ("The median sacral artery ... ends in the glomus coccygeum") but absent as a term of its own as far as I can see.

**Synonyms**

**Definition (free text, please give PubMed ID)**
A vestigial structure placed in front of, or immediately below, the tip of the coccyx.
https://en.wikipedia.org/w/index.php?title=Coccygeal_glomus&oldid=925043236
TA98:A12.2.12.011 (from Wikipedia; I'm not 100% sure this is the correct format)
TA2:3890 (as above)
FMA:15649

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
Subclass of UBERON:0010000 multicellular anatomical structure
(unless a better, more specific parent can be suggested)

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-2825-0621

**Comment by paolaroncaglia** [comment]
@megbalk
Could you comment, please? Thanks.

**Comment by megbalk** [comment]
@paolaroncaglia is this an appropriate equivalency:

gland and ('part of' some 'coccygeus muscle')?

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,

> is this an appropriate equivalency:
> 
> gland and ('part of' some 'coccygeus muscle')?

I'm afraid not, because that equivalence would mean that _any_ gland located in the coccygeus muscle is a glomus coccygeum. Also, I'm really unsure about defining a "vestigial structure" as a gland. 
@RDruzinsky , could we ask for your thoughts, please?
Thank you both.
Paola

**Comment by RDruzinsky** [comment]
I don't think that is either a gland or a vestigial structure. See 2017
https://doi.org/10.1002/ar.23615

Note that coccygeal body and glomus coccygeum are synonyms.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by megbalk** [comment]
@RDruzinsky @paolaroncaglia  what about:
Text definition: a glomus-like cell layer found in and around coccygeal muscles?

Equivalency: 
'part of' some coccygeal muscle

Are there any synonyms for "glomus"? I found "glomeral mesnchyme" but that seems specific to the kidney.

**Comment by RDruzinsky** [comment]
@megbalk @paolaroncaglia The article from 2017 that I referenced in my
previous email   https://doi.org/10.1002/ar.23615 suggests that the
coccygeal body or glomus coccygeum is not a true glomus, in the sense that
it consists of an a-v anastomosis. However, in most of the cases in the
study, it does seem that the glomus is derived from vascular material with
evidence of smooth muscle actin and pericytes, which line vessels.
Therefore, I don't think that 'part of' some coccygeal muscle would be
appropriate. We should call the terms coccygeal body and glomus coccygeum
synonyms and we could call it glomus-like (in the sense that a glomus is a
small, globular body), on the anterior or caudal surface of the coccyx (in
humans).



Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by megbalk** [comment]
Ok, so it sounds like we have a workable definition and synonyms, but no equivalency or subclasses yet. 
As I am unfamiliar with this structure (aside what it says in the reference provided), are there any suggestions? Perhaps 'smooth muscle tissue', or 'microcirculatory vessel', and 'coccyx'?
UBERON does not have the term "glomus cell", is this something that needs to be added?

**Comment by paolaroncaglia** [comment]
Hi @megbalk and @RDruzinsky ,

Thank you very much for your feedback on "glomus coccygeum". I'll assign the ticket to Meghan and to me, but I'll have to come back to it after the summer holidays. It's not urgent anyway.

Best,
Paola

**Comment by paolaroncaglia** [comment]
Note to self: in addition to the information provided in comments above, this review is useful and contains a full list of synonyms:
PMID:30799440
(full text [here](https://www.pathologica.it/article/view/27))

**Comment by paolaroncaglia** [comment]
UBERON:8410076 glomus coccygeum
