### ISSUE TITLE
Some definitions don't start with uppercase and don't end with a period

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1677]
I presume you're aware of this issue, but I don't know if it's ticketed. Can't say how widespread it is and/or if it occurs more often in some branches than in others, but here are a few random examples:

cervical gland
UBERON:0012247
mucus-secreting glands in the mucosa of the uterine cervix

gland
UBERON:0002530
an organ that functions as a secretory or excretory organ

liver lobule
UBERON:0004647
the polygonal structure of the liver that consists of hepatocytes radiating outward from a hepatic vein

liver perisinusoidal space
UBERON:0006729
the extravascular space in the liver between the parenchymal cells and a sinusoid that contains the blood plasma

**Comment by paolaroncaglia** [comment]
@cmungall @dosumis 
Similarly to #1678 , I'm ok with closing unless you'd want to comment.

**Comment by matentzn** [comment]
I will do this.
