### ISSUE TITLE
Missing textual definitions

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1678]
I couldn't find an existing ticket for this issue and I don't know what Uberon's policy/priority is on this. A few random examples of terms that lack a textual definition:

liver bud UBERON:0008836
liver left lateral lobe UBERON:0006727
liver left medial lobe UBERON:0006728
dorsal vessel heart UBERON:0015230
limb villosities UBERON:3010721
bone spine UBERON:0013706

**Comment by paolaroncaglia** [comment]
@cmungall @dosumis 
I'm happy to close this, but perhaps you'd like to comment first?
Thanks.

**Comment by paolaroncaglia** [comment]
I'll close this as it's a duplicate of (part of) #2053 .
