### ISSUE TITLE
NTRs: greater + lesser palatine foramen

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1686]
1)
**Preferred term label:**
greater palatine foramen

**Definition (free text, please give PubMed ID)**
A foramen of the skull found at either posterior angle of the hard palate, for the transmission of the descending palatine vessels and greater palatine nerve. 
https://en.wikipedia.org/w/index.php?title=Greater_palatine_foramen&oldid=971687677
FMA:53173

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
Subclass of UBERON:0013685 foramen of skull

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-2825-0621

2)
**Preferred term label:**
lesser palatine foramen

**Definition (free text, please give PubMed ID)**
A foramen of the skull found at either posterior angle of the hard palate behind the greater palatine foramen. One or more lesser palatine foramina perforate the pyramidal process of the palatine bone and carry the lesser palatine nerve. 
https://en.wikipedia.org/w/index.php?title=Lesser_palatine_foramina&oldid=870872639
FMA:53167

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
Subclass of UBERON:0013685 foramen of skull

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-2825-0621

Thanks.
Paola

**Comment by paolaroncaglia** [comment]
@megbalk I'll tentatively assign this ticket to you, let me know if that's an issue. Thanks.

**Comment by megbalk** [comment]
done! made pull request.

**Comment by paolaroncaglia** [comment]
> done! made pull request.

Thanks @megbalk .

**Comment by paola-scibite** [comment]
These terms have been added since, as 
UBERON:7500083 greater palatine foramen
UBERON:7500084 lesser palatine foramen
