### ISSUE TITLE
[NTR] skin of inguinal region

### ISSUE THREAD

**Issue by mshadbolt** [obophenotype/uberon#1688]
**Preferred term label:**
skin of inguinal region

**Synonyms**
skin of groin, groin skin, inguinal skin, zone of skin of inguinal region, zone of skin of groin

**Definition (free text, please give PubMed ID)**
The skin covering the inguinal region between the abdomen and the thigh on either side of the pubic bone.

https://en.wikipedia.org/wiki/Groin

PMID:468709

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
inguinal part of abdomen UBERON:0008337
http://purl.obolibrary.org/obo/UBERON_0008337

also perhaps part of skin of pelvis UBERON:0001415
http://purl.obolibrary.org/obo/UBERON_0001415

**Your nano-attribution (ORCID)**
0000-0001-7505-5418

@paolaroncaglia

**Comment by paolaroncaglia** [comment]
@mshadbolt 
Thanks for your input. A few notes:
- [ ] I'll add as subclass of 'abdominal segment skin' and part of 'inguinal part of abdomen'
- [ ] The wikipedia dbxref should be https://en.wikipedia.org/w/index.php?title=Groin&oldid=978874547 to capture the current version (the entry really is about the whole anatomical region, but it mentions the skin, so ok)
- [ ] Could you please indicate your use case for this term (even in brief)
- [ ] The term could be extended at least to primates, comments welcome, I'm just writing this down as a quick note.
Thanks,
Paola

**Comment by mshadbolt** [comment]
thanks @paolaroncaglia , I am trying to give a term while curating data from this paper: https://www.nature.com/articles/s42003-020-0922-4

The region as described in the paper:
> our scRNA-seq analysis was based on five independent whole-skin samples that were obtained specifically from the sun-protected inguinoiliac region of male donors.

**Comment by paolaroncaglia** [comment]
Thanks @mshadbolt .

**Comment by paolaroncaglia** [comment]
Note for self, Marion's paper is PMID:32327715.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
Your requested term 
UBERON:8410021 inguinal region skin
will be in the next Uberon release - coming very soon. (The next HCAO release is planned for Feb 18th, so the term should be in there too and visible in OLS ~Feb 20th.)
