### ISSUE TITLE
Automate/improve FMA imports

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1689]
Stemming from https://github.com/obophenotype/uberon/commit/a3b41da7dacd642c2d616652b8912a1175a37009#commitcomment-44664927:

[Paola]
@cmungall
Stemming from this same commit where it looks like you imported dozens of FMA terms into Uberon:
@dosumis, @zoependlington and I were working on some requests from Human Cell Atlas curators for terms that are present in FMA but not Uberon (yet). We were wondering if you already have a pipeline in place to automate FMA import into Uberon. If yes, we could make good use of it, and provide classes in Uberon-only space to our users. Thanks!

[Chris]
Let's discuss on a separate ticket. The process is only semi-automated,
terms should be checked for dupes. Ideally a lot more information and
axioms would be added than in the lift-up I just performed, though some of
this could be after the fact. Some can be automated, e.g. wikidata has a
lot ofthis. For now, do you have a way of knowing in advance what kinds of
terms you might like to add?

**Comment by paolaroncaglia** [comment]
@cmungall 

> For now, do you have a way of knowing in advance what kinds of terms you might like to add?

They would typically be subclasses of existing anatomy terms and found in human. Examples are in the recent Uberon tickets labelled "HCA" or "SCA", and they reflect current work (e.g. gut, liver...). Future requests may cover virtually any area, see the list in https://www.humancellatlas.org/areas-of-impact/. Pinging @mshadbolt and @ngeorgeebi in case they wish to add more. Thanks.

**Comment by cmungall** [comment]
Thanks! I suspect many of the requested terms will also be in wikidata so we'll implement something to bring in the union for requested terms, and add uberon DPs where appropriate.

Thanks for the link to the areas of impact. Do you have any further ideas of gaps? I would suspect things like location-specific elements of vasculature (lymph and blood)

**Comment by paolaroncaglia** [comment]
@cmungall 

> Thanks! I suspect many of the requested terms will also be in wikidata so we'll implement something to bring in the union for requested terms, and add uberon DPs where appropriate.

Sounds great, thanks. Shall we start assigning people then please, I'm assuming you, @dosumis and @matentzn ?

> Thanks for the link to the areas of impact. Do you have any further ideas of gaps? I would suspect things like location-specific elements of vasculature (lymph and blood)

Yes, I believe lymph too, but as I'm relatively new to the project, I added to the agenda for discussion at my future meeting with SCA and HCA curators, and asked them to comment here. We're meeting in a week.

**Comment by dosumis** [comment]
For HCA/SCA/HubMap use case - it's not clear we need a patternised bulk import.    We will continue to make ad hoc tickets for this on Uberon tracker and add terms manually - unless this task becomes large.

@cmungall can you provide some examples of how patternised term addition from FMA might work.

**Comment by paolaroncaglia** [comment]
@cmungall 
@dosumis 
Shall we close this?

**Comment by cmungall** [comment]
Looking at #2035, having a simple turnkey solution will be hard. Different cases will require different analyses of implicit and explicit design patterns, careful thought about long term maintenance implementations

**Comment by paolaroncaglia** [comment]
> Looking at #2035, having a simple turnkey solution will be hard. Different cases will require different analyses of implicit and explicit design patterns, careful thought about long term maintenance implementations

Thanks @cmungall . I'll close this ticket then.
