### ISSUE TITLE
Typo in def of UBERON:0011933 vibrissa unit

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1695]
**Uberon term**
UBERON:0011933 vibrissa unit

**Bug description**
"A pilosebaceuous unit that contains a strand of _virbissa_ hair..."
Please correct to "vibrissa".

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
I've found a couple of mentions of "virbissa" in lit, so I'll close.
