### ISSUE TITLE
Some "buccal" terms missing part_of parent

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1697]
All "buccal" terms should be (also) part of mouth. The following are only part of cheek:
UBERON:0012167 buccal fat pad
UBERON:0017654 buccal gland

(https://orcid.org/0000-0002-2825-0621)

**Comment by paolaroncaglia** [comment]
@megbalk , may I assign this ticket to you, please?
If not, please assign someone else as appropriate, thanks.

**Comment by megbalk** [comment]
@paolaroncaglia Currently cheek only refers to the exterior portion of the side of the face. Are these both interior (mouth) and exterior (cheek)? If so, I'll add " 'part of' some mouth", if not, which should it be (mouth or cheek)?

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,

> Currently cheek only refers to the exterior portion of the side of the face. Are these both interior (mouth) and exterior (cheek)? If so, I'll add " 'part of' some mouth", if not, which should it be (mouth or cheek)?

The issue may be a bit more complicated then. 
'buccal fat pad' is defined as "The Buccal fat pad is one of several encapsulated fat masses in the cheek. It is a deep fat pad located on either side of the face between the buccinator muscle and several more superficial muscles. It should not be confused with the malar fat pad, which is directly below the skin of the cheek. It should also not be confused with jowl fat pads. It is implicated in the formation of hollow cheeks and the nasolabial fold, but not in the formation of jowls.".
Sounds like buccal fat pads are not really "external".
'buccal gland' is defined as "Any of the small racemose mucous glands in the mucous membrane lining the cheeks" which sounds internal to me. 
Perhaps @RDruzinsky could comment please?

Thanks to both,
Paola

**Comment by RDruzinsky** [comment]
"Buccal" is a word that refers to the cheek. The buccinator muscle forms
part of the wall of the cheek, the buccal fat pad is superficial to the
buccinator muscle, etc. Buccal is also used as term of anatomical
orientation, as in the buccal surface of a tooth is the surface towards the
cheek, and the lingual surface is towards the tongue.

Buccal fat pads are only "external" in the sense that they are superficial
to the buccinator muscle and, thus, the oral cavity.

Cheek is an imprecise term that refers to the wall of the oral cavity
between the upper and lower rows of posterior teeth (often termed "cheek
teeth"). So, the skin of the region is also a part of the cheek.

"Mouth" is also a very imprecise term. It is used to refer to the entire
space, which includes the oral cavity and the vestibule, but it can also be
used to refer to the opening to the space between the lips.

So, in answer to @megbalk, cheek is a part of the exterior face and also a
part of the wall of the oral cavity.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by megbalk** [comment]
Given that cheek is both part of the exterior face and also a
part of the wall of the oral cavity, @paolaroncaglia do we need to add "part of mouth" or do we need to create a more specific parent term?

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,

> Given that cheek is both part of the exterior face and also a
> part of the wall of the oral cavity, @paolaroncaglia do we need to add "part of mouth" or do we need to create a more specific parent term?

Thanks to you and @RDruzinsky for taking care of this ticket. I added myself as an assignee - I'll look into this thread more closely at a later time, probably after the summer holidays (prioritizing more urgent tasks at the moment).
Paola

**Comment by paolaroncaglia** [comment]
Looking at this thread again, based on the comment [here](https://github.com/obophenotype/uberon/issues/1697#issuecomment-889268233), this may be a non-issue, so I'll close it.
