### ISSUE TITLE
UBERON:0018306 bulge and UBERON:0010188 protuberance

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1698]
**Uberon term**
UBERON:0018306 bulge and UBERON:0010188 protuberance

**Suggested revision and reasons**
UBERON:0018306 bulge: "expanded and swollen region of a surface that is otherwise relatively flat [ PHENOSCAPE:Nizar ]"
Subclass of 'surface structure'
Has a UBERONTEMP dbxref

UBERON:0010188 protuberance: "A roughly circular bulge in a surface."
Subclass of 'zone of organ'
Editor note: requires review

If these terms are to stay in Uberon, should 'protuberance' be a subclass of 'bulge'? Or should they be merged (I'd favour "protuberance" as more in context for anatomy) Should 'hair follicle bulge' and 'forehead protuberance' be linked to the respective broader terms? 
Some ambiguity is evident in the definition of the latter, "A bulge, knob, or swelling that protrudes from the forehead."...

https://orcid.org/0000-0002-2825-0621

**Comment by paolaroncaglia** [comment]
Volunteer needed please, not sure who the best person is. Thanks!

**Comment by wdahdul** [comment]
I can take this one. 'bulge' was added by a Phenoscape curator, and we have annotations to it, and to protuberance, in the Phenoscape KB. I agree the terms can probably be merged, but I will check against our annotations. Thanks!

**Comment by wdahdul** [comment]
I created a pull request addressing this issue, and added you as a reviewer.

**Comment by paolaroncaglia** [comment]
Hi @wdahdul ,

> I created a pull request addressing this issue, and added you as a reviewer.

Following up on this, I did review the PR and commented, see https://github.com/obophenotype/uberon/pull/2002. The PR had conflicts, and as it's been some time (and some Uberon releases since), it may be easier to re-do the edits please, but up to you. Thank you again for taking care of this ticket.

Best,
Paola
