### ISSUE TITLE
UBERON:4200179 manual claw

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1699]
**Uberon term**
UBERON:4200179 manual claw

**Suggested revision and reasons**
Currently part of some skeleton of manus, which looks incorrect. 
Should the term be merged with UBERON:0009565 nail of manual digit? 

https://orcid.org/0000-0002-2825-0621

**Comment by paolaroncaglia** [comment]
@cmungall 
This ticket is also related to digits. Thanks in advance for taking a look.

**Comment by wdahdul** [comment]
I think this term was created by a Phenoscape curator, based on the ID range assignment. We don't have existing annotations to it, but I'll try to follow up with the person who created it. Thanks.

**Comment by wdahdul** [comment]
Will assign myself to keep track of it

**Comment by wdahdul** [comment]
Also check on 'pedal claws" http://purl.obolibrary.org/obo/UBERON_4100008 created by a Phenoscape curator

**Comment by paolaroncaglia** [comment]
Thanks @wdahdul !

**Comment by wdahdul** [comment]
I created a pull request to obsolete 'manual claw' and 'pedal claws'.  These terms aren't used in Phenoscape kb annotations. ('Nail of pedal digit' terms are used annotations referring to pedal claws).

**Comment by cmungall** [comment]
OK, we can close #358 when pedal claw is obsoleted

Technically nail is conceptually overlapping with claw. See my analysis here #359. claws are both more specific (morphological form) and more general (the term claw can refer to the mereological sum of keratin and bone, I believe).

However, if phenoscape doesn't have any need of the claw concept then we can go and and obsolete (keeping claw as non-exact taxonomically scoped syn)
