### ISSUE TITLE
UBERON:7500041 tip of digit

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1701]
**Uberon term**
UBERON:7500041 tip of digit

**Suggested revision and reasons**
Digits are called digits in both hand and feet (manus and pes more broadly), so why is UBERON:7500041 'tip of digit' ("The distal-most point of a digit.") equivalent to "anatomical point and distalmost_part_of some phalanx of pes"?
"tip of digit" is also an exact synonym of UBERON:0009551 'distal segment of digit'. Perhaps UBERON:7500041 tip of digit should be obsoleted?

**Comment by paolaroncaglia** [comment]
@cmungall 
When you have a chance, could you comment on this issue please? Thanks.

**Comment by wdahdul** [comment]
Tagging @megbalk here, as her orcid ID is attached to the term. In Phenoscape, we use 'distal segment of digit' to annotate the tip or distal region of a digit (foot or hand). I agree about obsoleting 'tip of digit'.

**Comment by megbalk** [comment]
@wdahdul @cmungall this term can be obsoleted.

**Comment by paolaroncaglia** [comment]
Thanks @wdahdul and @megbalk for your feedback.
I will tentatively assign this ticket to @wdahdul and @nicolevasilevsky (if help is needed with obsoletions).

**Comment by nicolevasilevsky** [comment]
i'll obsolete this
