### ISSUE TITLE
NTR: left colic artery

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1702]
**Preferred term label:**
left colic artery

**Synonyms**

**Definition (free text, please give PubMed ID)**
The first branch of the inferior mesenteric artery is the left colic artery. The left colic artery supplies blood flow to the distal third of the transverse colon and the entirety of the descending colon. Once diverging from the IMA, the left colic artery runs anterior to the left ureter, left internal spermatic vessels (males), and psoas major before branching into its ascending and descending segments. PubMed ID: NBK482156

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
inferior mesenteric artery : UBERON:0001183

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-4183-8865

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please tag with HCA, thank you!

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
UBERON:8410022 left colic artery will be in the Uberon release - coming very soon.
