### ISSUE TITLE
NTR: right colic artery

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1703]
**Preferred term label:**
right colic artery

**Synonyms**

**Definition (free text, please give PubMed ID)**
The right colic artery may arise directly from the superior mesenteric artery (SMA) but often arises from a common trunk with the ileocolic artery or middle colic artery.  It supplies the ascending colon.  Paperback ISBN: 9780443103735

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
superior mesenteric artery: UBERON:0001182

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-4183-8865

**Comment by ngeorgeebi** [comment]
please tag with HCA, @paolaroncaglia thanks!

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
UBERON:8410023 right colic artery 
will be in the next Uberon release.
