### ISSUE TITLE
UBERON:4200132 tuber

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1704]
**Uberon term**
UBERON:4200132 tuber

**Reason for deprecation**
Label is ambiguous, there are no annotations, and it's very likely the same as the better defined UBERON:0005813 'tubercle'.

**Suggested replacement or term to consider**
UBERON:0005813 'tubercle'

**Comment by balhoff** [comment]
> there are no annotations

Which annotations are you looking at?

I think this term is used in paleontological literature, but maybe only in Latin labels. @alex-dececchi @wdahdul is there any distinction between this 'tuber' and 'tubercle'?

It's used in Phenoscape data, but we could migrate to tubercle.

**Comment by paolaroncaglia** [comment]
> > there are no annotations
> 
> Which annotations are you looking at?
> 
> I think this term is used in paleontological literature, but maybe only in Latin labels. @alex-dececchi @wdahdul is there any distinction between this 'tuber' and 'tubercle'?
> 
> It's used in Phenoscape data, but we could migrate to tubercle.

I meant no annotation properties, other than "created by: AD". Sorry if I was unclear. Also if it helps, I just looked up "tuber" in a Latin dictionary book and I confirm that "tubercle" is one of its meanings. Thanks.

**Comment by balhoff** [comment]
> I meant no annotation properties, other than "created by: AD".

Oh! Thanks, I just wanted to make sure I wasn't missing an Uberon annotation corpus. AD is @alex-dececchi but he isn't active in Uberon anymore.

**Comment by paolaroncaglia** [comment]
@wdahdul @megbalk 
Could you please comment on the suggestion to obsolete UBERON:4200132 tuber and replace it with UBERON:0005813 'tubercle'? See discussion above. Thanks.

**Comment by megbalk** [comment]
it seems tubercle (UBERON:0005813) in UBERON is specific to a growth resulting from tuberculosis. Can we rename this term to something more specific and then create a synonym for "tuber" that is "tubercle"?

**Comment by megbalk** [comment]
I clarified the definition of tubercle, made "tuber" an exact synonym, and obsoleted "tuber".

**Comment by megbalk** [comment]
done. created pull request.
