### ISSUE TITLE
UBERON module

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1710]
I’d like to build an ontology module as part of FOVT (FuTRES application ontology) for UBERON that is separate but could be imported. Is there a naming convention for the module that I should use?
For example, should the module ontology be called "UBERON-FOVT"?
And, should we use UBERON terms or our own ids that get imported if wanted?

**Comment by matentzn** [comment]
Hey @megbalk sounds great. Could you provide some details about scope (domain, number of terms) and some examples for the kind of terms? What is the reason to not directly add these terms to Uberon?

**Comment by megbalk** [comment]
FOVT will be an application ontology, pulling trait terms from OBA. We are adding many (300+) trait terms, which require hyper-specific definitions of structures (e.g., the proximal-most point of the ventral tubercle of a humerus), which likely aren't of much use to those that use UBERON regularly. These structure terms then become lines and lengths of lines in OBA.

**Comment by matentzn** [comment]
Thank you @megbalk thats very interesting - I will make sure that @dosumis looks at this ticket in early January!

**Comment by dosumis** [comment]
Hi Megan - sounds very interesting & timely.  We may need similar terms for human traits - which we've just hired someone to work on.  We should meet to look at possibilities for co-ordinating soon.

**Comment by megbalk** [comment]
sounds good! I'll send a message to coordinate!

**Comment by cmungall** [comment]
I'm worried about confusion about which term belongs where - also what is the direction of imports? modularization is hard. I am more of a lumper than others. I appreciate there may have been issues getting timely releases of uberon in the past but we are getting better!

**Comment by megbalk** [comment]
We (@ramonawalls, @matentzn, @balhoff, Istvan, and @dosumis) had a discussion back in Nov. about how to best and where to add terms. For a few reasons (need to import more from BSPO and RO; limitations in nesting for axioms) we decided it'd be best to create a module as an option for UBERON users. The terms we are creating are lines for OBA to call lengths of, so not likely something more anatomists or medical professionals would find useful.

**Comment by megbalk** [comment]
An update to this: we won't make a module but will instead make patterns in OBA and import existing FOVT terms into OBA
