### ISSUE TITLE
UBERON:0006558 lymphatic part of lymphoid system

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1720]
**Uberon term**
UBERON:0006558 lymphatic part of lymphoid system

**Synonym to be added**
The term has related synonym lymporeticular system and has relational adjective lymporeticular. At first I thought it was a typo for "lymphoreticular", but Google has examples of both spellings. However, "lymphoreticular" returns ~1k more matches than "lymporeticular", so you may wish to add 
has related synonym lymphoreticular system
and 
has relational adjective lymphoreticular.

Thanks.

Update: however, I just noticed that "lymphoreticular system" is an exact synonym of UBERON:0000363 reticuloendothelial system... which also has related synonym lymphoreticular

**Comment by paola-scibite** [comment]
Similarly, please consider adding
has relational adjective proepicardial
to UBERON:0004160 proepicardium (atm it only has "propepicardial", only 73 results in Google).

**Comment by nicolevasilevsky** [comment]
@paola-scibite would you like the related syn and relational adj added to UBERON:0006558 lymphatic part of lymphoid system?

**Comment by nicolevasilevsky** [comment]
looks like the relational adjective proepicardial has been added to UBERON:0004160 proepicardium

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,

> would you like the related syn and relational adj added to UBERON:0006558 lymphatic part of lymphoid system?

I'm not sure as those synonyms are also attached to a different term. Perhaps I'll just close. Thanks for looking into this!
