### ISSUE TITLE
UBERON:0007379 shelled egg

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1726]
**Uberon term**
UBERON:0007379 shelled egg

**Suggested revision of textual definition**
Current def: The hard-shelled reproductive body produced by a _bird_ and especially by the common domestic chicken; also: its contents used as food. [ http://en.wikipedia.org/wiki/Egg_(biology) http://purl.obolibrary.org/obo/BTO_0000369 ] 
but eggs produced by reptiles and monotremes are shelled too. See the summary in https://en.wikipedia.org/wiki/Egg. 
(The def of its child 'egg yolk' refers to birds and reptiles only - maybe that one can stay as is?)

Also, a very quick note that there may be some overlap between Uberon and GO, in that Uberon has 'egg yolk' and 'yolk' (is yolk ever not part of an egg?), and GO has 'yolk'. Thanks.

**Comment by nicolevasilevsky** [comment]
I revised the def.

I'm not sure about yolks, I don't know of them existing outside of eggs.
