### ISSUE TITLE
Duplicate 'latin' annotation properties

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#1727]
Uberon has two APs for latin synonym types.  Only one is a synonym type property.  Delete the one that is not.

See https://github.com/obophenotype/uberon/pull/1707

**Comment by dosumis** [comment]
It turns out that these are coming from CL - where they have slightly different IRIs to the Uberon ones due to a defect in the OBO2OWL conversion.   The solution is, I think, to use the Uberon IRIs in both cases - I will make a ticket to this effect for CL.

**Comment by paolaroncaglia** [comment]
@dosumis 

> It turns out that these are coming from CL - where they have slightly different IRIs to the Uberon ones due to a defect in the OBO2OWL conversion. The solution is, I think, to use the Uberon IRIs in both cases - I will make a ticket to this effect for CL.

Thanks for looking into this. I'll close this ticket then as a duplicate of https://github.com/obophenotype/cell-ontology/issues/893.
