### ISSUE TITLE
NTR: venule of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1730]
**Preferred term label:**
venule of small intestine

**Synonyms**
small intestine venule

**Definition (free text, please give PubMed ID)**
Venule located in the small intestine. One of the minute vessels that collect deoxygenated blood from the capillary plexuses returns it to the veins [ MP:0004125 MESH:A07.231.432.952 ]. Venules are the smallest division of the venous system.  They are usually mirrored with their counterpart arteriole. https://doi.org/10.1016/B978-0-12-374530-9.00022-X

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
digestive system venule (NTR?); venule: http://purl.obolibrary.org/obo/UBERON_0001979

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-4183-8865

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please tag with SCA thank you!

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
I presume that these are located more specifically in the _villi_ of small intestine? I.e. rather than in the small intestine in general.
Also please see my questions in #1729 . Thank you!

**Comment by ngeorgeebi** [comment]
Thanks @paolaroncaglia yes, you are correct this is a cross section image of a small intestinal villus with the associated vessels - lymph and blood shown.
With regards to a specific PMID - none so please just use my ORCID ID
We will be using this as part of the anatomogram to confim

Many thanks
Nancy

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] I might need to come back to this when the [villus of small/large intestine issue](https://github.com/obophenotype/uberon/issues/1733#issuecomment-773259573) is resolved.

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi ,
The new term is 
UBERON:8410001 small intestine venule.
It will be available in the next Uberon release, which I think will happen shortly, and if not, I already made a note to ask at the next Uberon/CL editors meeting (day after tomorrow).
Thanks,
Paola
