### ISSUE TITLE
NTR: lymphatic capillary of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1731]
**Preferred term label:**
lymphatic capillary of small intestine

**Synonyms**
small intestine lymphatic capillary

**Definition (free text, please give PubMed ID)**
Lymphatic capillary that is located in the small intestine. Microvessel of the lymphatic system lined with a single layer of overlapping endothelial cells. Joins to form the lymphatic vessels. [ ZFA:0005252 ]

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
digestive system lymphatic capillary (NTR?); lymphatic capillary http://purl.obolibrary.org/obo/UBERON_0006842

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
@paolaroncaglia sorry for the spam - SCA tag please :)

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
Could you please confirm if the term you need is broader than the existing one Uberon:0018410 'lacteal' "a lymphatic capillary that absorbs dietary fats in the villi of the small intestine.". 
If yes, my questions in #1729 apply. Thanks.

**Comment by ngeorgeebi** [comment]
Thanks @paolaroncaglia - apologies for not getting back to this sooner! Yes I think you're right - this term is synonymous to lacteal.
No specific PMID reference but I think if the term already exists, I don't need my ORCID ID added ;)
Yes it will be part of the anatomograms

Many thanks!
Nancy

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi ,
As agreed, I added the following exact synonyms to UBERON:0018410 'lacteal', with your ORCID as a dbxref:
"lymphatic capillary of small intestine"
"small intestine lymphatic capillary"
The synonyms will be visible at the next Uberon release.
The link to 'digestive system' is already implied via the term's axioms.
Thanks for your patience,
Paola
