### ISSUE TITLE
NTR: lymphatic vessel of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1732]
**Preferred term label:**
lymphatic vessel of small intestine

**Synonyms**
small intestine lymphatic vessel

**Definition (free text, please give PubMed ID)**
A lymphatic vessel that supplies the small intestine. A vessel that contains or conveys lymph, that originates as an interfibrillar or intercellular cleft or space in a tissue or organ, and that if small has no distinct walls or walls composed only of endothelial cells and if large resembles a vein in structure[BTO]. [ http://purl.obolibrary.org/obo/BTO_0000752 http://en.wikipedia.org/wiki/Lymphatic_vessel ] 

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
digestive system lymph vessel (NTR?); lymphatic vessel http://purl.obolibrary.org/obo/UBERON_0001473

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please tag with SCA. Can discuss with @dosumis if this is better for EFO?

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
My general questions in #1729 apply please.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
@dosumis 

> Can discuss with @dosumis if this is better for EFO?

I think we've agreed to keep anatomy terms in Uberon (similarly to cell type terms in CL) rather than EFO, as long as we tag and axiomatise appropriately to ensure that classification is maintainable. David, please shout otherwise. :-)

**Comment by ngeorgeebi** [comment]
Thanks @paolaroncaglia and again apologies for delayed reply.  Same answers to the previous
1. No specific PMID reference - this is part of the Gut Cell Atlas queries - so please just use my ORCID
2. It will be part of the Gut anatomograms in SCEA so a term is needed :)
Best
Nancy

**Comment by paolaroncaglia** [comment]
Hi again @ngeorgeebi ,
The new term is 
UBERON:8410002 small intestine lymphatic vessel
Link to digestive system already implied.
Thanks,
Paola
