### ISSUE TITLE
NTR: venule of large intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1734]
Preferred term label:
venule of large intestine

Synonyms
large intestine venule

Definition (free text, please give PubMed ID)
Venule located in the large intestine. One of the minute vessels that collect deoxygenated blood from the capillary plexuses returns it to the veins [ MP:0004125 MESH:A07.231.432.952 ]. Venules are the smallest division of the venous system. They are usually mirrored with their counterpart arteriole. https://doi.org/10.1016/B978-0-12-374530-9.00022-X

Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)
digestive system venule (NTR?); venule: http://purl.obolibrary.org/obo/UBERON_0001979

Your nano-attribution (ORCID)
https://orcid.org/0000-0003-4183-8865

**Comment by ngeorgeebi** [comment]
SCA tag needed please @paolaroncaglia

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'venule of colon' and make it a child term of colon  - UBERON:0001155 colon

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410048 venule of colon
