### ISSUE TITLE
NTR: lymphatic vessel of large intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1735]
Preferred term label:
lymphatic vessel of large intestine

Synonyms
large intestine lymphatic vessel

Definition (free text, please give PubMed ID)
A lymphatic vessel that supplies the large intestine. A vessel that contains or conveys lymph, that originates as an interfibrillar or intercellular cleft or space in a tissue or organ, and that if small has no distinct walls or walls composed only of endothelial cells and if large resembles a vein in structure[BTO]. [ http://purl.obolibrary.org/obo/BTO_0000752 http://en.wikipedia.org/wiki/Lymphatic_vessel ]

Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)
digestive system lymph vessel (NTR?); lymphatic vessel http://purl.obolibrary.org/obo/UBERON_0001473

Your nano-attribution (ORCID)
orcid.org/0000-0003-4183-8865/

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'lymphatic vessel of colon' and make it a child term of colon  - UBERON:0001155 colon

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410051 lymphatic vessel of colon
