### ISSUE TITLE
NTR: lymphatic capillary of large intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1736]
Preferred term label:
lymphatic capillary of large intestine

Synonyms
large intestine lymphatic capillary

Definition (free text, please give PubMed ID)
Lymphatic capillary that is located in the large intestine. Microvessel of the lymphatic system lined with a single layer of overlapping endothelial cells. Joins to form the lymphatic vessels. [ ZFA:0005252 ]

Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)
digestive system lymphatic capillary (NTR?); lymphatic capillary http://purl.obolibrary.org/obo/UBERON_0006842

Your nano-attribution (ORCID)
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
SCA tag please @paolaroncaglia

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'lymphatic capillary of colon' and make it a child term of colon  - UBERON:0001155 colon

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410054 lymphatic capillary of colon
