### ISSUE TITLE
NTR: afferent lymphatic vessel valve

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1740]
**Preferred term label:**
afferent lymphatic vessel valve

**Synonyms**
valve of afferent lymphatic vessel

**Definition (free text, please give PubMed ID)**
Valves are essential for the correct flow of fluid through a system. Valves in the afferent lymphatic vessel manage the flow of lymphatic fluid into the lymph node carrying immune cells. (original text)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
afferent lymphatic vessel : http://purl.obolibrary.org/obo/UBERON_0010396

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please add an SCA tag :)

**Comment by ngeorgeebi** [comment]
query whether parent term should be lymphatic valve: http://purl.obolibrary.org/obo/UBERON_0034949 instead?

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 

> query whether parent term should be lymphatic valve: http://purl.obolibrary.org/obo/UBERON_0034949 instead?

Yes indeed.
My questions in #1729 apply please.

**Comment by paolaroncaglia** [comment]
Note for self: I've started to add to an uncommitted branch "issues_1740_1741".

**Comment by ngeorgeebi** [comment]
Thanks @paolaroncaglia for looking into this and for the questions.
As with #1729 - no specific publication, so please just use my ORCID ID and yes, we would like it for SCA as it will be part of the anatomograms.

Apologies for the delayed reply

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi ,
The new term is 
UBERON:8410013 afferent lymphatic vessel valve
and will be available with the next Uberon release, scheduled to happen by June 1st at the latest.
Thanks for your patience,
Paola
