### ISSUE TITLE
NTR: efferent lymphatic vessel valve

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1741]
**Preferred term label:**
efferent lymphatic vessel valve

**Synonyms**
valve of efferent lymphatic vessel

**Definition (free text, please give PubMed ID)**
Valves are essential for the correct flow of fluid through a system. Valves in the afferent lymphatic vessel manage the flow of lymphatic fluid out of the lymph node carrying immune cells. (original text)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymphatic valve: http://purl.obolibrary.org/obo/UBERON_0034949 and(?) efferent lymphatic vessel: http://purl.obolibrary.org/obo/UBERON_0010397

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please tag with SCA

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
UBERON:8410014 efferent lymphatic vessel valve
Thanks,
Paola
