### ISSUE TITLE
NTR: trabecular sinus of lymph node

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1749]
**Preferred term label:**
trabecular sinus of lymph node

**Synonyms**
lymph node trabecular sinus

**Definition (free text, please give PubMed ID)**
The trabecular sinus is the lymph filled space inside the trabeculae between lobules of the lymph node. This is a continuation of the subcapsular sinus which receives the afferent vessels and is present beneath the capsule. This space is traversed by both reticular fibers and cells in the lymph. PUBMED ID: https://www.ncbi.nlm.nih.gov/books/NBK557717/

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
trabecula: http://purl.obolibrary.org/obo/UBERON_0000440

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please add SCA tag:
Also - need to make trabeculae of lymph node NTR?
needs to have part of: lymph node for anatomograms

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 

> Also - need to make trabeculae of lymph node NTR?

No, this already exists as UBERON:0002195 'trabecula of lymph node'. However, I could 
- [ ] add exact synonyms "trabeculae of lymph node" and "lymph node trabeculae" (with synonym type = plural)
- [ ] (less urgent) do the same for 'trabecula' and any of its children that don't have them already.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 

> **Definition (free text, please give PubMed ID)**
> The trabecular sinus is the lymph filled space inside the trabeculae between lobules of the lymph node. This is a continuation of the subcapsular sinus which receives the afferent vessels and is present beneath the capsule. This space is traversed by both reticular fibers and cells in the lymph. PUBMED ID: https://www.ncbi.nlm.nih.gov/books/NBK557717/

Based on the figures and text in https://en.wikipedia.org/wiki/Lymph_node, and consistently with the book reference above, the sinus would be the space _outside_ the trabeculae, not inside. It should be modelled similarly to UBERON:0005463 'subcapsular sinus of lymph node':

'anatomical space' and ('part of' some 'lymph node') and ('adjacent to' some 'trabecula of lymph node')

That will also address your need that the new term be part of lymph node for the anatomograms.
If you have any concern, let me know. Thanks.

**Comment by ngeorgeebi** [comment]
Thanks @paolaroncaglia apologies for the mistake. All your comments look good so i'm happy with that 👍

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
The term you requested is 
UBERON:8410032 trabecular sinus of lymph node
It'll be available with the next Uberon release (not 100% sure when that will be, but probably in a week or so).
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Note for self: leaving this ticket open as a reminder to do https://github.com/obophenotype/uberon/issues/1749#issuecomment-788116928.
