### ISSUE TITLE
NTR: medullary arteriole of lymph node

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1752]
**Preferred term label:**
 medullary arteriole of lymph node

**Synonyms**
arteriole of medulla of lymph node

**Definition (free text, please give PubMed ID)**
Arterioles that arise from the hilar artery of a lymph node and radiate centrifugally, branching in the medulla.  PUBMED ID: https://pubmed.ncbi.nlm.nih.gov/17067937/

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
medulla of lymph node http://purl.obolibrary.org/obo/UBERON_0002007

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
This will be UBERON:8410035 medullary arteriole of lymph node
in the next Uberon release. Thanks,
Paola
