### ISSUE TITLE
NTR: medullary venule of lymph node

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1753]
**Preferred term label:**
medullary venule of lymph node

**Synonyms**
venule of medulla of lymph node

**Definition (free text, please give PubMed ID)**
Medullary venules are a continuation of high endothelial venules which condense repeatedly in the interfollicular cortex and peripheral deep cortical unit and then transition to medullary venules at the corticomedullary junction. The medullary venules condense and return centripetally to the hilar vein. PUBMED ID: https://pubmed.ncbi.nlm.nih.gov/17067937/

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
medulla of lymph node http://purl.obolibrary.org/obo/UBERON_0002007

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410036 medullary venule of lymph node
