### ISSUE TITLE
NTR: high endothelial venule of lymph node

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1755]
**Preferred term label:**
high endothelial venule of lymph node

**Synonyms**

**Definition (free text, please give PubMed ID)**
High endothelial venule (a specialized blood vessel adapted for lymphocyte trafficking) that is part of a of lymph node. https://pubmed.ncbi.nlm.nih.gov/28217126/

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
high endothelial venule (new term, requested in #1754)
lymph node http://purl.obolibrary.org/obo/UBERON_0000029

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410038 high endothelial venule of lymph node
