### ISSUE TITLE
UBERON:6003007 insect adult head

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1759]
**Uberon term**
UBERON:6003007 insect adult head

**Suggested revision and reasons**
Is currently not a child of UBERON:6000004 insect head.
Also, if these FBbt terms are to stay in Uberon, please consider disambiguating the labels of the descendants of UBERON:6003007 'insect adult head' to refer to insects explicitly. E.g., UBERON:6003624 'adult brain' (xref FBbt:00003624) should be renamed 'insect adult brain' to avoid ambiguities in curation and curation tools. Thanks!

**Comment by cmungall** [comment]
here is why it doesn't classify

```
id: UBERON:6000004
name: panarthropod head
xref: FBbt:00000004
intersection_of: UBERON:0000033 ! head
intersection_of: part_of NCBITaxon:88770 ! Panarthropoda
```

this is a good example of the ragged lattice issue, and why making taxon-specific classes is a bad idea

we should have done this all differently, but given we have this legacy, some incremental steps

 - [ ] fix labels as suggested above
 - [ ] mark things in this subset that are required by GO
 - [ ] obsolete things that are poor fits for uberon. 
        * concepts unlikely to be homologous e.g. serial homologs like A8
        * compositional FB concepts, e.g. emb/larval forms
        * grouping classes
 - [ ] try and fix the ragged lattice issue as much as possible - use consistent groupings
 - [ ] work with others on better insect/arthro/panarthro strategy for AOs

cc @dosumis

**Comment by cmungall** [comment]
So it turns out we added a lot of these for use in GO axiomatization... but we never finished this

```
id: GO:0022416
name: chaeta development
namespace: biological_process
def: "The process whose specific outcome is the progression of a chaeta over time, from its formation to the mature structure. A chaeta is a sensory multicellular cuticular outgrowth of a specifically differentiated cell." [FBbt:00005177, GOC:bf, GOC:cjm, GOC:dos, GOC:isa_complete]
synonym: "bristle development" NARROW [GOC:bf, GOC:dos]
is_a: GO:0007423 ! sensory organ development
```

no logical def... cc @balhoff @ukemi

**Comment by dosumis** [comment]
CC @Clare72
