### ISSUE TITLE
NTR: lymph node germinal center mantle zone

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1762]
**Preferred term label:**
germinal center mantle zone

**Synonyms**
lymph node germinal center mantle zone; mantle zone of lymph node germinal center; mantle zone of germinal center; germinal center mantle zone

**Definition (free text, please give PubMed ID)**
After an immune response B cells multiply and differentiate into B cell blasts. This proliferation displaces the IgM and IgD positive B cells in the follicle. This displacement results in the formation of the mantle zone around the germinal center.  The mantle zone is densely populated by B cells. PMID: 25656706

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymph node germinal center : http://purl.obolibrary.org/obo/UBERON_0009039

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
@paolaroncaglia tagged and assigned you :)

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi ,
Apologies for the delay. I think that your NTR 'lymph node germinal center mantle zone' may be the same as the existing term [UBERON:0010420 'lymph node follicular corona'](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0010420) ("A part of the secondary follicle in which naive B cells reside along with some helper T cells, macrophages and follicular dendritic cells; these are displaced by the expanding germinal centre and form a 'mantle' around it"). Could you confirm, please? If so, I will 

- [ ] Add synonyms:
lymph node germinal center mantle zone [exact]
germinal center mantle zone [broad]
mantle zone of lymph node germinal center [exact]
mantle zone of germinal center [broad]
germinal center mantle zone [broad]

- [ ] Add def dbxrefs: 
PMID:25656706
http://orcid.org/0000-0003-4183-8865/

- [ ] Add missing . at end of def of UBERON:0010420

As for your suggested parent term (lymph node germinal center), please note that UBERON:0010420 'lymph node follicular corona' already has the following links:

Equivalent to: secondary follicle corona and part of some lymph node

Subclass of:
secondary follicle corona
surrounds some lymph node germinal center
part of some lymph node secondary follicle

Once this is resolved, I will address https://github.com/obophenotype/cell-ontology/issues/903.

Thanks!
Paola

**Comment by addiehl** [comment]
I agree with Paola, that 'lymph node germinal center mantle zone' is equivalent to UBERON:0010420 'lymph node follicular corona' and that her suggested synonyms should be added.
--Alex

**Comment by addiehl** [comment]
I'm wondering also if "mantle" is a more common usage than "corona" for this portion of microanatomy.

**Comment by ngeorgeebi** [comment]
I would say that mantle is probably more used

**Comment by paolaroncaglia** [comment]
I confirm that a quick look at PubMed hits shows that "mantle" is a more common usage than "corona" for this portion of microanatomy, so I will
- [ ] make lymph node germinal center mantle zone the primary label
- [ ] make lymph node follicular corona an exact synonym
- [ ] add Alex' ORCID to def dbxref

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
@addiehl 
FYI, all edits done as above, will be in the next Uberon release. Thanks.
