### ISSUE TITLE
NTR: lymph node germinal center light zone 

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1763]
**Preferred term label:**
germinal center light zone

**Synonyms**
light zone of germinal center; lymph node germinal center light zone; light zone of lymph node germinal center

**Definition (free text, please give PubMed ID)**
Lymph node germinal centers contain two microenvironments - the light zone and the dark zone. The light zone is sparsely populated with B cells and includes additional cell types such as follicular dendritic cells, lymph node tingible macrophages and T follicular helper cells. PMID: 25656706

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymph node germinal center http://purl.obolibrary.org/obo/UBERON_0009039

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
thanks @paolaroncaglia

**Comment by paolaroncaglia** [comment]
@addiehl please
(cc @ngeorgeebi and @sfexova )

Nancy requested terms for ‘lymph node germinal center light zone’ (this ticket) and ‘lymph node germinal center dark zone’ (#1764 ). She suggested the following definitions based on [PMID:25656706](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4399774/),  I’ve collated them: 
“Lymph node germinal centers contain two microenvironments - the light zone and the dark zone. The light zone is sparsely populated with B cells and includes additional cell types such as follicular dendritic cells, lymph node tingible macrophages and T follicular helper cells. The dark zone is densely populated with B cell blasts and reticular cells.”
My understanding from the article is that the 2 zones, named after their appearance at histological examination, are visible under specific circumstances, i.e. in human, following immunisation, and starting at a precise temporal stage. If this is correct, I’d like Alex’ feedback please on how to best represent the light and dark zones in Uberon. Would the following work:
is_a ‘lymphoid tissue’??
part_of ‘lymph node germinal center’
present_in_taxon: Homo sapiens
'existence starts during or after' GO:0006955 ‘immune response’? But I see that 'existence starts during or after' is used with developmental stages; not sure what object property would be appropriate. 
development_notes: [copy from article, quoting days after immunization]

Also, note that currently 
'germinal center' has the exact synonym “light zone of follicle” 
'lymph node germinal center' has the related synonym “lymph node light zone”
'secondary follicle corona' has the exact synonym “dark zone of follicle”
'lymph node follicular corona' has the exact synonym “lymph node dark zone”
For 'lymph node follicular corona’, see also the related request https://github.com/obophenotype/uberon/issues/1762

Based on the above, should the following synonyms’ scopes change to:
'germinal center' has the exact synonym “light zone of follicle” => narrow
'lymph node germinal center' has the related synonym “lymph node light zone” => narrow 
'secondary follicle corona' has the exact synonym “dark zone of follicle” => related or delete
'lymph node follicular corona' has the exact synonym “lymph node dark zone” => related or delete
?

Thanks much,
Paola

**Comment by addiehl** [comment]
Use PMID:8011279 as a reference.

I don't think we should include axioms specifying when the these zones appear; it's an unnecessary complication. What is true is that when light and dark zones are present, they are part of the lymph node germinal center.

'lymphoid tissue' seems like an appropriate parent.

I agree with the adjustment of the synonyms.
--Alex

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
I created this term as UBERON:8410052 lymph node germinal center light zone. This is a less ambiguous label than the suggested 'germinal center light zone', which I kept as a broad synonym.

@addiehl 
Thanks again for your feedback. I also changed the scopes of the other terms' synonyms as agreed.
