### ISSUE TITLE
NTR: lymph node germinal center dark zone

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1764]
**Preferred term label:**
germinal center dark zone

**Synonyms**
dark zone of germinal center; lymph node germinal center dark zone; dark zone of lymph node germinal center

**Definition (free text, please give PubMed ID)**
Lymph node germinal centers contain two microenvironments - the light zone and the dark zone. The dark zone is densely populated with B cell blasts and reticular cells.PMID: 25656706

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymph node germinal center http://purl.obolibrary.org/obo/UBERON_0009039

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
thanks @paolaroncaglia

**Comment by paolaroncaglia** [comment]
See https://github.com/obophenotype/uberon/issues/1763#issuecomment-854805286.

**Comment by addiehl** [comment]
Similar comments to #1763. 

Use PMID:8011279 as a reference (in addition to the one above).

'lymph node dark zone' part of 'lymph node germinal center'.

'lymphoid tissue' seems like an appropriate parent.
-- Alex

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
This is now added as UBERON:8410053 lymph node germinal center dark zone.
'germinal center dark zone' stays as a broad synonym.
Thanks,
Paola
