### ISSUE TITLE
NTR: high endothelial venule of Peyer's patch

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1765]
Preferred term label:
high endothelial venule of Peyer's patch

Synonyms

Definition (free text, please give PubMed ID)
High endothelial venule (a specialized blood vessel adapted for lymphocyte trafficking) that is part of a Peyer's patch in the small intestne. https://pubmed.ncbi.nlm.nih.gov/28217126/

Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)
high endothelial venule (new term, requested in #1754)
Peyer's patch http://purl.obolibrary.org/obo/UBERON_0001211

Your nano-attribution (ORCID)
0000-0003-3440-1876
orcid.org/0000-0003-4183-8865/

**Comment by ngeorgeebi** [comment]
thanks @paolaroncaglia equivalent term to high endothelial venule of lymph node @sfexova created so putting her ORCID ID in as well

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi and/or @sfexova ,
Nancy originally requested 'high endothelial venule of Peyer's patch' defining it as "High endothelial venule (a specialized blood vessel adapted for lymphocyte trafficking) that is part of a Peyer's patch in the _small_ intestine". Could you please confirm if the requested term should be linked to 'Peyer's patch' or to its child 'small intestine Peyer's patch'? If the latter, I would add exact synonyms 'high endothelial venule of small intestine Peyer's patch' and 'high endothelial venule of Peyer's patch of small intestine'. 
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Note to self:
I created 'high endothelial venule of Peyer's patch' as part of generic Peyer's patch while I wait for SCA's reply.
If they ask to make it part of small intestine Peyer's patch instead, 
- [ ] I'll need to state that in the term's label, synonym(s), textual definition, and logical definition.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi and @sfexova 
The new term is UBERON:8410040 high endothelial venule of Peyer's patch, but please see my 2 comments above.
I'll leave this ticket open until they've been addressed. Thanks.

**Comment by sfexova** [comment]
Hi @paolaroncaglia, I thought Peyer's patches are specific to small intestine (illeum) - e.g here - page 195 'PPs are specialized SLOs [secondary lymphoid organs] located in the lamina propria of the mucosa and extending into the submucosa of the ileum.':
[1-s2.0-S1877117310920085-main.pdf](https://github.com/obophenotype/uberon/files/6753621/1-s2.0-S1877117310920085-main.pdf)
I have never seen a paper with Peyer's patches from somewhere else than small intestine

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
Thanks for your feedback. 
- [ ] I'll edit UBERON:8410040 'high endothelial venule of Peyer's patch' so it is part of small intestine Peyer's patch, see https://github.com/obophenotype/uberon/issues/1765#issuecomment-853757900.
- [ ] I'll open a separate ticket to improve the Peyer's patch branch, and will link it here FYI.

Thanks.

**Comment by paolaroncaglia** [comment]
Hi again @sfexova ,
I revised the term, it is now
UBERON:8410040 high endothelial venule of small intestine Peyer's patch
def: "A high endothelial venule that is located in a Peyer's patch in the small intestine." [http://orcid.org/0000-0003-3440-1876, http://orcid.org/0000-0003-4183-8865/, PMID:20800822, PMID:28217126]
synonym: "high endothelial venule of Peyer's patch" BROAD []
synonym: "high endothelial venule of Peyer's patch of small intestine" EXACT []
intersection_of: UBERON:8410037 ! high endothelial venule
intersection_of: part_of UBERON:0003454 ! small intestine Peyer's patch
