### ISSUE TITLE
Synonym: lymph node paracortex

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1768]
**Uberon term**
lymph node T cell domain

**Synonym to be added**
lymph node paracortex

**broad/exact/narrow/related ?**
exact

**Comment by ngeorgeebi** [comment]
@paolaroncaglia sorry to be a pain. Ideally we would really like for lymph node paracortex to be the main term for this with the original existing term to be the synonym. 
We would also recommend that the definition be changed:
Potential definition:
The lymph node paracortex is the middle layer of the lymph node and is mostly populated by T cells and dendritic cells. The paracortex also contains specialised blood vessels called high endothelial venules which allow lymphocytes to enter the node.  https://www.immunology.org/public-information/bitesized-immunology/organs-and-tissues/lymph-node#:~:text=Lymph%20node%20structure&text=The%20paracortex%20also%20contains%20specialised,within%20the%20nodes%2C%20via%20conduits.

**Comment by ngeorgeebi** [comment]
feel free to also add my ORCID ID ;) orcid.org/0000-0003-4183-8865/

**Comment by paolaroncaglia** [comment]
Note to self, this should be looked at along with https://github.com/obophenotype/uberon/issues/1809.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi and @sfexova 
As per Alex Diehl's recommendation, I have created 
UBERON:8410066 lymph node paracortex.
