### ISSUE TITLE
Synonym: lymph node follicular corona

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/uberon#1769]
**Uberon term**
lymph node follicular corona http://purl.obolibrary.org/obo/UBERON_0010420

**Synonym to be added**
lymph node follicular mantle zone; lymph node follicle mantle zone

**broad/exact/narrow/related ?**
exact

**Comment by ngeorgeebi** [comment]
Dear both: this is me being pendantic - sorry! It's to fit in with the new term request for lymph node follicle mantle zone :)

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi (cc @sfexova ),

> It's to fit in with the new term request for lymph node follicle mantle zone :)

I presume you refer to lymph node germinal center mantle zone #1762 ? 
If so, please see discussion there, I think that lymph node germinal center mantle zone is in fact the same as lymph node follicular corona. If so, would you like me to add 
lymph node follicular mantle zone; lymph node follicle mantle zone
as exatc synonyms of lymph node follicular corona?

Thanks,
Paola

**Comment by addiehl** [comment]
Agree with Paola and the discussion in #1762.
-- Alex

**Comment by paolaroncaglia** [comment]
@ngeorgeebi and @sfexova 
I think this was addressed as part of #1762 , so I'll close this ticket as a duplicate, but if I have missed anything please feel free to open a new ticket or re-open this one. Thank you.
Paola
