### ISSUE TITLE
Cornea should not be part of integument

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#1779]
![image](https://user-images.githubusercontent.com/6722114/106823515-f08cef00-6635-11eb-940d-17bcb9e4402e.png)

Ticket motivated by: https://github.com/monarch-initiative/mondo/issues/542

Poss fixes:
 - Remove classification as 'surface structure' (this is a dubious term anyway)
 - 'surface structure' part_of integument -> integument is_a 'surface structure'

**Comment by nicolevasilevsky** [comment]
@dosumis this is needed for Mondo, so I went ahead and did this.
