### ISSUE TITLE
NTR: lymph node vein

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1782]
**Preferred term label:**
lymph node vein

**Synonyms**
vein of lymph node, hilar vein of lymph node

**Definition (free text, please give PubMed ID)**
Lymph node venules condense and form lymph node vein which exits at the lymph node hilum and is also called hilar vein. PMID: 17067937

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymph node http://purl.obolibrary.org/obo/UBERON_0000029

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
Notes for self:
1) No xref available in FMA, NCIT or other. But PMID provided should suffice. I'd also add
WikipediaVersioned:Lymph_node&oldid=1001655735#Structure
which includes this bit: "The hilum is an indent on the concave surface of the lymph node where lymphatic vessels leave and blood vessels enter and leave."
2) Synonyms should be entered as suggested. "hilar vein" alone may be ambiguous.

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
Your requested new term
UBERON:8410033 lymph node vein
will be in the next release of Uberon, which should happen very soon.
