### ISSUE TITLE
NTR: lymph node artery

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1783]
**Preferred term label:**
lymph node artery

**Synonyms**
artery of lymph node, hilar artery of lymph node

**Definition (free text, please give PubMed ID)**
Lymph node artery enters the lymph node at the hilum and branches into smaller arterioles. PMID: 17067937

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymph node http://purl.obolibrary.org/obo/UBERON_0000029

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
Notes for self: 
1) No xref available in FMA, NCIT or other. But PMID provided should suffice. I'd also add
WikipediaVersioned:Lymph_node&oldid=1001655735#Structure
which includes this bit: "The hilum is an indent on the concave surface of the lymph node where lymphatic vessels leave and blood vessels enter and leave."
2) Synonyms should be entered as suggested. "hilar artery" alone is ambiguous (may refer to kidney too).

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410034 lymph node artery
will be in the next Uberon release.
