### ISSUE TITLE
His-Purkinje system

### ISSUE THREAD

**Issue by RLovering** [obophenotype/uberon#1785]
**Uberon term**
UBERON:0004146 His-Purkinje system and child term revisions

**Suggested revision and reasons**
The GO ontology term GO:0086069 bundle of His cell to Purkinje myocyte communication is not accurate because the left and right bundle branches are not considered to be part of the bundle of His rather they are branches from the bundle of His. David Hill has asked me to request a revision to UBERON to reflect physiologists and anatomists views of the cardia conduction system.
Please see https://github.com/geneontology/go-ontology/issues/20731

The key problem is that there are a lot of different names for the components of the conduction system.
This article is a good representation of the many figures for this system, although wikipedia also provides this too: https://dev.biologists.org/content/143/2/197 Fig 1 (and text)

    sinoatrial node (SAN) - located in atria
    atrioventricular node (AVN) - located in atria
    atrioventricular bundle (AVB, bundle of His, His bundle) - located in ventricles
    atrioventricular junction - located in ventricles
    right bundle branch - located in ventricles
    left bundle branch - located in ventricles
    peripheral ventricular conduction system (Purkinje fibre network, Purkinje fibres) - located in ventricles
    The atrial and ventricular myocardial tissues are electrically isolated from one another by a plane of connective tissue formed by the annulus fibrosus and central fibrous body.
    ventricular conduction system (VCS) is all the conduction system located on the ventricular side of this connective tissue

The GO term GO:0086069 bundle of His cell to Purkinje myocyte communication is basically describing the communication from the top of the ventricular conduction system to the end of it.

UBERON has described this with the following:
>His-Purkinje system
>>atrioventricular bundle
>>>left branch of atrioventricular bundle
>>>right branch of atrioventricular bundle

I can't find anyone using the term: bundle of His left branch or bundle of His right branch or atrioventricular bundle left branch or atrioventricular right bundle branch. From my discussions with morphology experts at UCL these terms are not used because the bundle of His is just the section from the connective tissue to the atrioventricular junction, and then the branches are part of the ventricular conduction system but are not considered to be part of the bundle of his/atrioventricular bundle

Based on the above the UBERON ontology should really be:

 >His-Purkinje system (synonym ventricular conduction system, VCS)
>> atrioventricular bundle I think this term should change to bundle of His (synonym atrioventricular bundle, AVB, His bundle)
>> atrioventricular junction
>>  left branch of atrioventricular bundle I think this term should change to left bundle branch
>> right branch of atrioventricular bundle I think this term should change to right bundle branch
>> Purkinje fibres (synonym peripheral ventricular conduction system, Purkinje fibre network)

Hope you agree with these suggestions

Thanks

Ruth

**Comment by cmungall** [comment]
I agree with these changes

**Comment by RLovering** [comment]
great, will you be submitting these revisions as this is not something I can do

**Comment by nicolevasilevsky** [comment]
Hi @RLovering, I can work on this! :)

**Comment by nicolevasilevsky** [comment]
Revised labels:
- [ ] His-Purkinje system (add synonyms: ventricular conduction system, VCS
- [ ] atrioventricular bundle -change label to bundle of His (add synonyms: atrioventricular bundle, AVB, His bundle)
- [ ] left branch of atrioventricular bundle - change label to left bundle branch
- [ ] right branch of atrioventricular bundle - change label to right bundle branch

@RLovering, to clarify, these are new terms? Could you provide definitions and references for these? Thank you!
- [ ] atrioventricular junction
- [ ] Purkinje fibres (synonym peripheral ventricular conduction system, Purkinje fibre network)

**Comment by nicolevasilevsky** [comment]
@RLovering another question- did you also want to change some of the relationship types too? If yes, could you please outline the changes for me, I'd be happy to implement.

**Comment by RLovering** [comment]
Hi Nicole
I had misinterpreted the figure above as clearly the  atrioventricular junction is not part of the conduction system. I have asked a heart morphology expert here about the whether there is a name for the part of the bundle of his where the RBB and LBB branches initiate, from all the figures I have seen I don't think this point has a name. Unfortunately the expert hasn't got back to me so maybe we should just not worry about this for now.

All of the terms listed below should be part_of child terms of His-Purkinje system (synonym ventricular conduction system, VCS) (no additional child terms should exist for any of the terms below apart from the Purkinje fibre network), and all of the existing synonyms I think can stay with suggested additions provided below)
  
- bundle of His (synonyms: atrioventricular bundle, AVB, His bundle)
- left bundle branch (synonym: left branch of atrioventricular bundle, LBB)
- right bundle branch (synonym: right branch of atrioventricular bundle, RBB) 
- Purkinje fibre network (synonyms: peripheral ventricular conduction system, Purkinje fibres)
- - part of child UBERON_0002354 Purkinje fibre

Definition for Purkinje fibre network:
The cardiac Purkinje fiber network is a collection of Purkinje fibers that receives signals from the right and left bundle branches and innervates the ventricular cardiac muscle. The Purkinje fiber network creates synchronized contractions of the heart ventricles.

Does that seem right to you/

Best

Ruth

**Comment by nicolevasilevsky** [comment]
Done: (on PR)

- bundle of His (synonyms: atrioventricular bundle, AVB, His bundle)
- left bundle branch 
  - synonyms: left branch of atrioventricular bundle, LBB
  - part of some His-Purkinje system
- right bundle branch 
  - synonyms: right branch of atrioventricular bundle, RBB
  - part of some His-Purkinje system
- New term: Purkinje fibre network
Does this look correct @RLovering?
![image](https://user-images.githubusercontent.com/6722114/107417556-97f0a280-6aca-11eb-8c56-3294061264d2.png)

![image](https://user-images.githubusercontent.com/6722114/107417495-85766900-6aca-11eb-8357-51254a4a9df1.png)

**Comment by RLovering** [comment]
Im not very good at reading these, but the cardiac Purkinje fiber needs to be a part of child of Purkinje fiber network as the Purkinje fiber network is made up of lots of Purkinje fibers.

and yes Purkinje fiber network is a part of child to His-Purkinje system

does that make sense?

**Comment by nicolevasilevsky** [comment]
yes, makes sense! I made this change.

**Comment by dosumis** [comment]
Hi Ruth - are you happy with this now?  If so we could get it into the new release.

**Comment by RLovering** [comment]
Hi Both

I am happy with what has been set up. But I also have found one more term that is required. Andrew Cook here at UCL has requested that we add the Uberon term:
branching atrioventricular bundle
synonym: branching bundle
Definition: The part of the His-Purkinje system where the atrioventricular bundle bifurcates to the right bundle branch and the left bundle branch 

Note that this term is not really used in the literature but apparently in some diseases there is a lengthening of the distance between the AV node and the point of bifurcation and therefore provision of a term for this site would be useful.

If you feel this is not required then that is not a problem. Please do go ahead with including all the other terms in the ontology when you can

Have a good weekend

Ruth

**Comment by dosumis** [comment]
Hi all.  I've merged changes so far so this makes it into the new release. Please open a new ticket for the missing term and anything (if any) missed.
