### ISSUE TITLE
NTR: airway submucosal gland

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1786]
Stemming from https://github.com/EBISPOT/efo/issues/880: 

**Preferred term label:**
airway submucosal gland

Subclass of UBERON:0011148 submucosal gland
Part of some bronchus (as per EFO term specs)

Exact synonyms:
bronchus submucosal gland, bronchial submucosal gland

**Definition (free text, please give PubMed ID)**
A submucosal gland located in a bronchus.
@ngeorgeebi and/or @sfexova could you suggest PMIDs or other references please?

**Your nano-attribution (ORCID)**
@ngeorgeebi and/or @sfexova please provide your ORCID here please. Thanks.

**Comment by paolaroncaglia** [comment]
Note for self,
- [ ] Fix typo in label of UBERON:0008989 submocosal esophageal gland (should be submucosal).

**Comment by ngeorgeebi** [comment]
@ngeorgeebi ORCID: 0000-0003-4183-8865
@sfexova ORCID: 0000-0003-3440-1876

sorry for the delay @paolaroncaglia

**Comment by paolaroncaglia** [comment]
Note to self and FYI @ngeorgeebi and @sfexova :
As resolved in https://github.com/EBISPOT/efo/issues/880, I created the term 
UBERON:8410043 bronchus submucosal gland (synonym: "airway submucosal gland")
so that in the future it may replace EFO:0010666 'airway submucosal gland'.
However, as agreed, this replacement won't happen until plenty of advance warning is given to SCA (see https://github.com/EBISPOT/efo/issues/880#issuecomment-795737707). Thanks.

**Comment by paolaroncaglia** [comment]
Reopening to 
- [ ] create a new Uberon term for 'airway submucosal gland' as a child of 'submucosal gland' (and parent of 'bronchus submucosal gland'), as requested by @sfexova in https://github.com/EBISPOT/efo/issues/880#issuecomment-1069039904
- [ ] remove the mapping to EFO:0010666 'airway submucosal gland' from Uberon 'bronchus submucosal gland', and add it instead to Uberon 'airway submucosal gland'
- [ ] update the [correspondence table](https://docs.google.com/spreadsheets/d/1Ao9d2VR4xqQsesHDz6Dn27V4ySfGntd-tbaUVeZ-NYI/edit#gid=0)
- [ ] comment on https://github.com/EBISPOT/efo/issues/880# when done.

**Comment by sfexova** [comment]
Hi @paolaroncaglia thanks for the quick reply! yes, respiratory tract is the right parent for this, I believe

**Comment by paolaroncaglia** [comment]
@sfexova , the new term is UBERON:8410077 airway submucosal gland. 
It will be available at the next Uberon release, scheduled for tomorrow if all goes well.
