### ISSUE TITLE
Typos in def of UBERON:4200120 puboischiadic plate + do spell-checking?

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1789]
**Uberon term**
UBERON:4200120 puboischiadic plate

**Bug description**
Def contains several typos
"A broad _expnase_ of bone _incorperating_ both the pubis and the ischium. Origin site for ventral limb muscle including the _pubioishciofemoralis_ externus. Modified from Romer 1956"

I spotted this randomly while looking at the diff for the release. I recall that the discussion on implementing some form of spell-checking was revived somewhere, some time ago by @cmungall and others. Was a solution agreed on? 

Cheers,
Paola

**Comment by matentzn** [comment]
It may be best split this ticket in two (general spell checking and typo) - reviving spell checking is probably low down the list of priorities for us though.. I don't know what easy solutions there are for that..

**Comment by paolaroncaglia** [comment]
Hi @matentzn ,

> It may be best split this ticket in two (general spell checking and typo) - reviving spell checking is probably low down the list of priorities for us though.. I don't know what easy solutions there are for that..

Ok, I'll close for now. We can always come back to this. Thanks.
