### ISSUE TITLE
NTR: venule of lymph node

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1793]
**Preferred term label:**
venule of lymph node

**Synonyms**

**Definition (free text, please give PubMed ID)**
A venule (a very small vein that collects blood from capillaries) that is part of a lymph node. PMID: 17067937

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymph node http://purl.obolibrary.org/obo/UBERON_0000029
venule http://purl.obolibrary.org/obo/UBERON_0001979
**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410041 venule of lymph node
