### ISSUE TITLE
NTR: arteriole of lymph node

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1794]
**Preferred term label:**
arteriole of lymph node

**Synonyms**

**Definition (free text, please give PubMed ID)**
An arteriole (a very small artery that leads and delivers blood to capillaries) that is part of a lymph node. PMID: 17067937

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymph node http://purl.obolibrary.org/obo/UBERON_0000029
arteriole http://purl.obolibrary.org/obo/UBERON_0001980

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410042 arteriole of lymph node
