### ISSUE TITLE
How to debug unsat in composite?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1799]
```
MBASE = $(TMPDIR)/ext-weak.owl $(BRIDGEDIR)/bridges $(TMPDIR)/local-ma.owl $(TMPDIR)/local-ehdaa2.owl $(TMPDIR)/local-emapa.owl $(TMPDIR)/local-xao.owl \
	$(TMPDIR)/local-zfa.owl $(TMPDIR)/local-fbbt.owl $(TMPDIR)/local-fbdv.owl \
	$(TMPDIR)/local-wbbt.owl $(TMPDIR)/local-wbls.owl $(TMPDIR)/local-ceph.owl \
	$(TMPDIR)/local-cteno.owl $(TMPDIR)/local-poro.owl $(TMPDIR)/allen-mba.obo $(TMPDIR)/allen-pba.obo $(TMPDIR)/allen-hba.obo \
	$(TMPDIR)/allen-dmba.obo $(TMPDIR)/allen-dhba.obo \
	dependencies

# A subset of OPs will be turned into taxon GCIs
TAXON_GCI_RELS = RO:0002202 RO:0002496 RO:0002497 BFO:0000051

MERGESPECIES =\
  --merge-species-ontology -s 'mouse' -t NCBITaxon:10090 -q $(TAXON_GCI_RELS) \
  --merge-species-ontology -s 'human' -t NCBITaxon:9606 -q $(TAXON_GCI_RELS) \
  --merge-species-ontology -s 'primate' -t NCBITaxon:9443 \
  --merge-species-ontology -s 'Xenopus' -t NCBITaxon:8353 \
  --merge-species-ontology -s 'Danio' -t NCBITaxon:7954 \
  --merge-species-ontology -s 'Drosophila' -t NCBITaxon:7227 \
  --merge-species-ontology -s 'C elegans' -t NCBITaxon:6237 \

MERGE_EQSETS =  --merge-equivalence-sets -s UBERON 10 -s CL 9 -s CARO 5  -l UBERON 10 -l CL 9 -d UBERON 10 -d CL 9

MAKESPMERGE= $(UCAT)\
  --map-ontology-iri $(URIBASE)/uberon.owl $(TMPDIR)/ext-weak.owl\
  --map-ontology-iri $(URIBASE)/fma.owl $(COMPONENTSDIR)/null.owl\
  --map-ontology-iri $(URIBASE)/uberon/bridge/uberon-bridge-to-fma.owl $(COMPONENTSDIR)/null.owl\
 $(URIBASE)/uberon/$(BRIDGEDIR)/collected-$*.owl --merge-imports-closure

# bundled: collect all ontologies and do a basic (non-species) import closure merge
# primarily for testing: not released
bundled-%.owl: $(MBASE)
	OWLTOOLS_MEMORY=12G owltools $(MAKESPMERGE) --merge-import-closure -o -f ofn $@
.PRECIOUS: unreasoned-composite-%.owl

# stage1 of composite build: do a species merge, but no additional reasoning
unreasoned-composite-%.owl: $(MBASE)
	OWLTOOLS_MEMORY=12G owltools $(MAKESPMERGE) --reasoner elk $(MERGESPECIES) $(MERGE_EQSETS) -o -f ofn $@
.PRECIOUS: unreasoned-composite-%.owl
```

This whole block is very hard for me to understand - What should I do if `unreasoned-composite-%.owl` fails because of an unsatisfiable class?

For example, I get:

```
Exception in thread "main" owltools.mooncat.SpeciesMergeUtil$UnmergeableOntologyException: unsatisfiable class: <http://purl.obolibrary.org/obo/DHBA_146035008>
	at owltools.mooncat.SpeciesMergeUtil.merge(SpeciesMergeUtil.java:228)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:823)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
uberon.Makefile:999: recipe for target 'unreasoned-composite-metazoan.owl' failed
make: *** [unreasoned-composite-metazoan.owl] Error 1
```

Now because `SpeciesMergeUtil` needs the reasoner, I cant dump an intermediate ontology that I can look and debug. Whats the best way to inspect this problem?

**Comment by matentzn** [comment]
Found a way to debug:

```
xxz:
	robot merge --catalog $(CATALOG) -i tmp/ext-weak.owl -i bridge/collected-metazoan.owl -i tmp/allen-dhba.obo -o tmp/debugme.owl

xxx:
	robot explain -i tmp/debugme.owl -M unsatisfiability  --unsatisfiable random:3 --explanation tmp/debug_unsat_dhba.md -o tmp/debug_unsat.owl
```

**Comment by matentzn** [comment]
If anyone can see any obvious problems here, please let me know @cmungall @balhoff @dosumis 

## [forebrain (prosencephalon)](http://purl.obolibrary.org/obo/DHBA_10156) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [forebrain (prosencephalon)](http://purl.obolibrary.org/obo/DHBA_10156) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [brain](http://purl.obolibrary.org/obo/DHBA_10155)
    - [brain](http://purl.obolibrary.org/obo/DHBA_10155) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [neural tube](http://purl.obolibrary.org/obo/DHBA_10154)
      - [neural tube](http://purl.obolibrary.org/obo/DHBA_10154) EquivalentTo [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606))
    -  Transitive: [part of](http://purl.obolibrary.org/obo/BFO_0000050)
  - [ovary](http://purl.obolibrary.org/obo/UBERON_0000992) EquivalentTo [gonad](http://purl.obolibrary.org/obo/UBERON_0000991) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [female reproductive system](http://purl.obolibrary.org/obo/UBERON_0000474))
  - [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990))
  - [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476) DisjointWith [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000)
  - [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476) SubClassOf [connected anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)
  - [female reproductive system](http://purl.obolibrary.org/obo/UBERON_0000474) EquivalentTo [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [female organism](http://purl.obolibrary.org/obo/UBERON_0003100))
  - [neural tube](http://purl.obolibrary.org/obo/EHDAA2_0001254) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [neural fold](http://purl.obolibrary.org/obo/EHDAA2_0001249)
  - [trunk neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001251) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001248)
  - [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [connected anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990))
  - [neural tube](http://purl.obolibrary.org/obo/EHDAA2_0001254) EquivalentTo [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606))
  - [epiblast](http://purl.obolibrary.org/obo/EHDAA2_0000444) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [inner cell mass](http://purl.obolibrary.org/obo/EHDAA2_0000830)
  - [morula (2-16 cells)](http://purl.obolibrary.org/obo/EHDAA2_0000005) EquivalentTo [morula](http://purl.obolibrary.org/obo/UBERON_0000085) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606))
  - [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086) SubClassOf [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476)
  - [ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0000428) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [epiblast](http://purl.obolibrary.org/obo/EHDAA2_0000444)
  - [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992)
  - [neural fold](http://purl.obolibrary.org/obo/EHDAA2_0001249) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [trunk neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001251)
  - [morula](http://purl.obolibrary.org/obo/UBERON_0000085) SubClassOf [surrounded_by](http://purl.obolibrary.org/obo/RO_0002219) some [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086)
  - [inner cell mass](http://purl.obolibrary.org/obo/EHDAA2_0000830) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [morula (2-16 cells)](http://purl.obolibrary.org/obo/EHDAA2_0000005)
  - [neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001248) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0000428)


## [neural tube](http://purl.obolibrary.org/obo/DHBA_10154) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [neural tube](http://purl.obolibrary.org/obo/DHBA_10154) EquivalentTo [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606))
    -  Transitive: [part of](http://purl.obolibrary.org/obo/BFO_0000050)
  - [ovary](http://purl.obolibrary.org/obo/UBERON_0000992) EquivalentTo [gonad](http://purl.obolibrary.org/obo/UBERON_0000991) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [female reproductive system](http://purl.obolibrary.org/obo/UBERON_0000474))
  - [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990))
  - [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476) DisjointWith [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000)
  - [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476) SubClassOf [connected anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)
  - [female reproductive system](http://purl.obolibrary.org/obo/UBERON_0000474) EquivalentTo [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [female organism](http://purl.obolibrary.org/obo/UBERON_0003100))
  - [neural tube](http://purl.obolibrary.org/obo/EHDAA2_0001254) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [neural fold](http://purl.obolibrary.org/obo/EHDAA2_0001249)
  - [trunk neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001251) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001248)
  - [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [connected anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990))
  - [neural tube](http://purl.obolibrary.org/obo/EHDAA2_0001254) EquivalentTo [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606))
  - [epiblast](http://purl.obolibrary.org/obo/EHDAA2_0000444) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [inner cell mass](http://purl.obolibrary.org/obo/EHDAA2_0000830)
  - [morula (2-16 cells)](http://purl.obolibrary.org/obo/EHDAA2_0000005) EquivalentTo [morula](http://purl.obolibrary.org/obo/UBERON_0000085) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606))
  - [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086) SubClassOf [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476)
  - [ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0000428) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [epiblast](http://purl.obolibrary.org/obo/EHDAA2_0000444)
  - [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992)
  - [neural fold](http://purl.obolibrary.org/obo/EHDAA2_0001249) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [trunk neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001251)
  - [morula](http://purl.obolibrary.org/obo/UBERON_0000085) SubClassOf [surrounded_by](http://purl.obolibrary.org/obo/RO_0002219) some [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086)
  - [inner cell mass](http://purl.obolibrary.org/obo/EHDAA2_0000830) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [morula (2-16 cells)](http://purl.obolibrary.org/obo/EHDAA2_0000005)
  - [neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001248) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0000428)


## [brain](http://purl.obolibrary.org/obo/DHBA_10155) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [brain](http://purl.obolibrary.org/obo/DHBA_10155) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [neural tube](http://purl.obolibrary.org/obo/DHBA_10154)
    -  Transitive: [part of](http://purl.obolibrary.org/obo/BFO_0000050)
    - [neural tube](http://purl.obolibrary.org/obo/DHBA_10154) EquivalentTo [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606))
  - [ovary](http://purl.obolibrary.org/obo/UBERON_0000992) EquivalentTo [gonad](http://purl.obolibrary.org/obo/UBERON_0000991) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [female reproductive system](http://purl.obolibrary.org/obo/UBERON_0000474))
  - [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990))
  - [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476) DisjointWith [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000)
  - [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476) SubClassOf [connected anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)
  - [female reproductive system](http://purl.obolibrary.org/obo/UBERON_0000474) EquivalentTo [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [female organism](http://purl.obolibrary.org/obo/UBERON_0003100))
  - [neural tube](http://purl.obolibrary.org/obo/EHDAA2_0001254) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [neural fold](http://purl.obolibrary.org/obo/EHDAA2_0001249)
  - [trunk neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001251) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001248)
  - [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [connected anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990))
  - [neural tube](http://purl.obolibrary.org/obo/EHDAA2_0001254) EquivalentTo [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606))
  - [epiblast](http://purl.obolibrary.org/obo/EHDAA2_0000444) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [inner cell mass](http://purl.obolibrary.org/obo/EHDAA2_0000830)
  - [morula (2-16 cells)](http://purl.obolibrary.org/obo/EHDAA2_0000005) EquivalentTo [morula](http://purl.obolibrary.org/obo/UBERON_0000085) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606))
  - [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086) SubClassOf [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476)
  - [ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0000428) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [epiblast](http://purl.obolibrary.org/obo/EHDAA2_0000444)
  - [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992)
  - [neural fold](http://purl.obolibrary.org/obo/EHDAA2_0001249) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [trunk neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001251)
  - [morula](http://purl.obolibrary.org/obo/UBERON_0000085) SubClassOf [surrounded_by](http://purl.obolibrary.org/obo/RO_0002219) some [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086)
  - [inner cell mass](http://purl.obolibrary.org/obo/EHDAA2_0000830) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [morula (2-16 cells)](http://purl.obolibrary.org/obo/EHDAA2_0000005)
  - [neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001248) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0000428)

# Axiom Impact 
## Axioms used 3 times
- [neural tube](http://purl.obolibrary.org/obo/DHBA_10154) EquivalentTo [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606)) [ext.owl]
- [morula (2-16 cells)](http://purl.obolibrary.org/obo/EHDAA2_0000005) EquivalentTo [morula](http://purl.obolibrary.org/obo/UBERON_0000085) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606)) [ext.owl]
- [neural tube](http://purl.obolibrary.org/obo/EHDAA2_0001254) EquivalentTo [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606)) [ext.owl]
- [female reproductive system](http://purl.obolibrary.org/obo/UBERON_0000474) EquivalentTo [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [female organism](http://purl.obolibrary.org/obo/UBERON_0003100)) [ext.owl]
- [ovary](http://purl.obolibrary.org/obo/UBERON_0000992) EquivalentTo [gonad](http://purl.obolibrary.org/obo/UBERON_0000991) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [female reproductive system](http://purl.obolibrary.org/obo/UBERON_0000474)) [ext.owl]
- [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [connected anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990)) [ext.owl]
- [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990)) [ext.owl]
- [ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0000428) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [epiblast](http://purl.obolibrary.org/obo/EHDAA2_0000444) [ext.owl]
- [epiblast](http://purl.obolibrary.org/obo/EHDAA2_0000444) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [inner cell mass](http://purl.obolibrary.org/obo/EHDAA2_0000830) [ext.owl]
- [inner cell mass](http://purl.obolibrary.org/obo/EHDAA2_0000830) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [morula (2-16 cells)](http://purl.obolibrary.org/obo/EHDAA2_0000005) [ext.owl]
- [neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001248) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0000428) [ext.owl]
- [neural fold](http://purl.obolibrary.org/obo/EHDAA2_0001249) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [trunk neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001251) [ext.owl]
- [trunk neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001251) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [neural ectoderm](http://purl.obolibrary.org/obo/EHDAA2_0001248) [ext.owl]
- [neural tube](http://purl.obolibrary.org/obo/EHDAA2_0001254) SubClassOf [develops_from](http://purl.obolibrary.org/obo/RO_0002202) some [neural fold](http://purl.obolibrary.org/obo/EHDAA2_0001249) [ext.owl]
- [morula](http://purl.obolibrary.org/obo/UBERON_0000085) SubClassOf [surrounded_by](http://purl.obolibrary.org/obo/RO_0002219) some [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086) [ext.owl]
- [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086) SubClassOf [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476) [ext.owl]
- [zona pellucida](http://purl.obolibrary.org/obo/UBERON_0000086) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992) [ext.owl]
- [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476) SubClassOf [connected anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) [ext.owl]
- [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476) DisjointWith [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) [ext.owl]
-  Transitive: [part of](http://purl.obolibrary.org/obo/BFO_0000050) [ext.owl]

## Axioms used 2 times
- [brain](http://purl.obolibrary.org/obo/DHBA_10155) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [neural tube](http://purl.obolibrary.org/obo/DHBA_10154) [ext.owl]

## Axioms used 1 times
- [forebrain (prosencephalon)](http://purl.obolibrary.org/obo/DHBA_10156) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [brain](http://purl.obolibrary.org/obo/DHBA_10155) [ext.owl]



# Ontologies used: 
- ext.owl (http://purl.obolibrary.org/obo/uberon/ext.owl)

**Comment by matentzn** [comment]
This looks suspicious:

- [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [connected anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990)) [ext.owl]
- [reproductive structure](http://purl.obolibrary.org/obo/UBERON_0005156) EquivalentTo [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990)) [ext.owl]

**Comment by matentzn** [comment]
Ignore this ticket. Found the proble I think.

**Comment by matentzn** [comment]
Update to self: seems poro carries in disjoint axioms.

**Comment by dosumis** [comment]
This doesn't look right to me: 

brain SubClassOf part of some neural tube [ext.owl]

**Comment by matentzn** [comment]
@dosumis where did you see this? I don't see that axiom (anymore?) it was there in the first version of the ticket, but I have corrected that since.

**Comment by matentzn** [comment]
Superceded.
