### ISSUE TITLE
NTR: placental blood

### ISSUE THREAD

**Issue by johnwjudkins** [obophenotype/uberon#1801]
**Preferred term label:**
placental blood

**Definition (free text, please give PubMed ID)**
Blood located in the placenta.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
blood

**Your nano-attribution (ORCID)**
0000-0001-6595-0902

I also suggest the subclass axiom "located_in some placenta", similar to the axiom for 'umbilical cord blood'. I am developing for a project that distinguishes between placental and cord blood.

**Comment by johnwjudkins** [comment]
Following up. Any interest?

**Comment by dosumis** [comment]
Hi @johnwjudkins - apologies.  This seems to have fallen through the cracks.  Have now assigned an editor so we should be able to get this into the next release.

**Comment by bvarner-ebi** [comment]
Hi @johnwjudkins, thank you for your patience with this request.
We plan to add this new term after the in-progress Uberon release is finalised.
You can track the status on this PR: https://github.com/obophenotype/uberon/pull/2379

**Comment by bvarner-ebi** [comment]
@johnwjudkins, thank you for your contribution.

The new term UBERON:8470000 'placental blood' has been added to Uberon and should be reflected in the next release.

Please reach out if you have follow up questions or concerns.
