### ISSUE TITLE
Chris to commit

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1802]
- [ ] ABA-src.obo

**Comment by cmungall** [comment]
Wait where is this required. We renamed ABA to MBA. Anyway I can check this in later when I'm at computer but need to check with @dosumis on Allen atlas strategy

**Comment by matentzn** [comment]
This is completely excluded from the currrent build so yes, we can close it:

https://github.com/obophenotype/uberon/blob/master/src/ontology/uberon.Makefile#L1553
