### ISSUE TITLE
NTR: venule of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1811]
**Preferred term label:**
venule of appendix

**Synonyms**
vermiform appendix venule
venule of vermiform appendix

**Definition (free text, please give PubMed ID)**
Venule located in the appendix vermiformis. One of the minute vessels that collect deoxygenated blood from the capillary plexuses returns it to the veins [ MP:0004125 MESH:A07.231.432.952 ]. Venules are the smallest division of the venous system. They are usually mirrored with their counterpart arteriole. https://doi.org/10.1016/B978-0-12-374530-9.00022-X

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154
venule http://purl.obolibrary.org/obo/UBERON_0001979

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by sfexova** [comment]
other child terms of the vermiform appendix term only have 'appendix' in the term label, so changed it here to correspond

**Comment by paolaroncaglia** [comment]
@sfexova 
I added 
UBERON:8410020 venule of appendix
as requested. Will be visible in the next Uberon release (which was originally planned for around this weekend, but I suspect there may be some delay as I haven't heard from my colleagues. I'm not sure if you'd prefer me to push for a release or rather wait until next week so we can fix the issues with the large intestine-related anatomograms?).
Thanks,
Paola
