### ISSUE TITLE
NTR: arteriole of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1812]
**Preferred term label:**
arteriole of appendix

**Synonyms**
vermiform appendix arteriole
appendix vermiformis arteriole
arteriole of appendix vermiformis

**Definition (free text, please give PubMed ID)**
Arteriole of villus of appendix vermiformis. Arterioles are the smallest division of artery located between the muscular arteries and the capillaries[GO]. [ http://amigo.geneontology.org/amigo/term/GO:0014830 ]. Arterioles rapidly respond to vasoconstrictor and vasodilator stimuli. (https://doi.org/10.1016/B978-0-12-374530-9.00022-X)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154
arteriole http://purl.obolibrary.org/obo/UBERON_0001980

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by sfexova** [comment]
other child terms of the vermiform appendix term only have 'appendix' in the term label, so changed it here to correspond

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410028 arteriole of appendix
