### ISSUE TITLE
NTR: lymphatic capillary of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1814]
**Preferred term label:**
lymphatic capillary of appendix

**Synonyms**
lymphatic capillary of appendix vermiformis
lymphatic capillary of vermiform appendix

**Definition (free text, please give PubMed ID)**
Lymphatic capillary that is located in the appendix vermiformis. Microvessel of the lymphatic system lined with a single layer of overlapping endothelial cells. Joins to form the lymphatic vessels. [ ZFA:0005252 ]

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154
lymphatic capillary http://purl.obolibrary.org/obo/UBERON_0006842

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by sfexova** [comment]
other child terms of the vermiform appendix term only have 'appendix' in the term label, so changed it here to correspond

**Comment by paolaroncaglia** [comment]
@sfexova 
FYI, please note that 'lymphatic capillary of appendix' will be a child of 'lymphatic vessel of appendix'. 
I assume this won't cause issues in the anatomograms, but please shout otherwise. :-)

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410029 lymphatic capillary of appendix
