### ISSUE TITLE
NTR: lymphatic vessel of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1815]
**Preferred term label:**
lymphatic vessel of appendix

**Synonyms**
lymphatic vessel of appendix vermiformis
lymphatic vessel of vermiform appendix

**Definition (free text, please give PubMed ID)**
A lymphatic vessel that supplies the large intestine. A vessel that contains or conveys lymph, that originates as an interfibrillar or intercellular cleft or space in a tissue or organ, and that if small has no distinct walls or walls composed only of endothelial cells and if large resembles a vein in structure[BTO]. [ http://purl.obolibrary.org/obo/BTO_0000752 http://en.wikipedia.org/wiki/Lymphatic_vessel ]

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154
lymphatic vessel http://purl.obolibrary.org/obo/UBERON_0001473

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by sfexova** [comment]
other child terms of the vermiform appendix term only have 'appendix' in the term label, so changed it here to correspond

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410030 lymphatic vessel of appendix
