### ISSUE TITLE
NTR: muscularis mucosae of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1816]
**Preferred term label:**
muscularis mucosae of appendix

**Synonyms**
muscularis mucosae of appendix vermiformis
muscularis mucosae of vermiform appendix

**Definition (free text, please give PubMed ID)**
A muscularis mucosa that is part of a vermiform appendix. Muscularis mucosa is a thin layer of smooth muscle found in most parts of the gastrointestinal tract, located outside the lamina propria mucosae and separating it from the submucosa[WP]. [ http://en.wikipedia.org/wiki/Muscularis_mucosae ]

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154
muscularis mucosa http://purl.obolibrary.org/obo/UBERON_0006676

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by sfexova** [comment]
other child terms of the vermiform appendix term only have 'appendix' in the term label, so changed it here to correspond

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410031 muscularis mucosae of appendix
Have a great long weekend,
Paola
