### ISSUE TITLE
NTR: high endothelial venule of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1818]
**Preferred term label:**
high endothelial venule of appendix

**Synonyms**
high endothelial venule of vermiform appendix
high endothelial venule of appendix vermiformis

**Definition (free text, please give PubMed ID)**
High endothelial venule that is located in the vermiform appendix. High endothelial venules are specialized blood vessels adapted for lymphocyte trafficking. They form a spatially organized network, which controls both the type of lymphocyte and the site of entry into lymphoid tissues. Uniquely, high endothelial venules express vascular addressins that regulate lymphocyte entry into lymphoid organs. PMID: 28217126

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154
high endothelial venule https://github.com/obophenotype/uberon/issues/1754

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410039 high endothelial venule of appendix
