### ISSUE TITLE
Ambiguous labels

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1819]
UBERON:4200169 process 2
UBERON:4200170 process 3
UBERON:4200171  process 4
Defined respectively as:
Process on the humerus of basal tetrapods, anterior to the entepicondyle and associated with subscapularis muscle (based on Coates 1996)
Process on the humerus of basal tetrapods, anterior to the entepicondyle (see Coates 1996)
Process on the humerus of basal tetrapods, anterior to the entepicondyle (see Coates 1996)

- [x] The labels are highly ambiguous. Please consider editing to e.g. 'basal tetrapod process 2' etc. [updated below]
- [x] Defs of process 3 and 4 are identical. Pls consider disambiguating to e.g. "Third process on the humerus..." etc. [fixed by others in the meantime]
- [x] (General issue) A new ticket template for "revise label" or similar may be useful. [leave this aside for now, may fall under "revise textual definition" ticket template]

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@cmungall 
I'm happy to do quick edits for this issue, but please let me know if you or others have any comments. Thanks.

**Comment by paolaroncaglia** [comment]
Phenoscape people please :-)
Updating this ticket, as it appears that 2 of the 3 relevant terms have been edited by others in the meantime:
UBERON:4200169 process 2 ("Process on the humerus of basal tetrapods, anterior to the entepicondyle and associated with subscapularis muscle (based on Coates 1996).")
has an ambiguous label; no synonyms. It is sibling of
UBERON:4200170 'process 3 of entepicondyle' ("Process on the humerus of basal tetrapods, anterior to the entepicondyle and adjacent to process 4 of entepicondyle (see Coates 1996).")
UBERON:4200171 'process 4 of entepicondyle' ("Process on the humerus of basal tetrapods, anterior to the entepicondyle and adjacent to process 3 of entepicondyle (see Coates 1996).")
I'd like to make the label of UBERON:4200169 'process 2' less ambiguous by replacing it with 'process 2 of entepicondyle' (and keeping 'process 2' as a broad synonym). Please comment if you think this would be incorrect. Thank you.

**Comment by paolaroncaglia** [comment]
In the absence of any objection, I went ahead and renamed UBERON:4200169 'process 2' as 'process 2 of entepicondyle' so it's less ambiguous (and kept 'process 2' as a broad synonym).
