### ISSUE TITLE
Revise label of UBERON:2001275 sublingual

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1825]
UBERON:2001275 sublingual
"Endochondral bone that is the median element of the ventral hyoid arch, generally lying between the paired ventral hypohyals. [ TAO:je ]"

The label is ambiguous (think e.g. sublingual gland, sublingual administration of drugs...). Please consider revising to e.g. sublingual bone and adding taxon properties/notes. The term does have in fact a provenance note:
"This class was sourced from an external ontology (teleost_anatomy). Its definitions, naming conventions and relationships may need to be checked for compatibility with uberon"
At a first glance there are many more terms with a similar provenance note, so ideally all those classes should be revisited, but focusing on the more ambiguous labels among those would be a really useful starting point. Thanks.

**Comment by wdahdul** [comment]
Yes, I agree. I'll fix this in phenoscape-ext. Thanks!

**Comment by paola-scibite** [comment]
Thank you @wdahdul

**Comment by wdahdul** [comment]
Fixed in phenoscape-ext: https://github.com/obophenotype/uberon-phenoscape-ext/commit/8c0a28332a1b79fd15c9bde534944e9109e05028 

I'll make another ticket to address revisiting the compatibility of teleost_anatomy terms with Uberon
