### ISSUE TITLE
Uberon ext coherency

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1830]
There are currently 600+ unsats in ext.owl (in the new build pipeline). Here is one explanation, and a breakdown of the most frequent axioms across a sample of 20 different explanations:

## [compound eye photoreceptor cell](http://purl.obolibrary.org/obo/CL_2000019) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [compound eye photoreceptor cell](http://purl.obolibrary.org/obo/CL_2000019) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [compound eye](http://purl.obolibrary.org/obo/UBERON_0000018)
    - [compound eye](http://purl.obolibrary.org/obo/UBERON_0000018) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656)
      - [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656) SubClassOf [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770)
        - [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770) SubClassOf [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794)
          - [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794) SubClassOf [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317)
      - [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
    - [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [overlaps](http://purl.obolibrary.org/obo/RO_0002131)
    - [compound eye](http://purl.obolibrary.org/obo/UBERON_0000018) EquivalentTo [eye](http://purl.obolibrary.org/obo/UBERON_0000970) and ([composed primarily of](http://purl.obolibrary.org/obo/RO_0002473) some [ommatidium](http://purl.obolibrary.org/obo/UBERON_0000971))
      - [eye](http://purl.obolibrary.org/obo/UBERON_0000970) SubClassOf [sense organ](http://purl.obolibrary.org/obo/UBERON_0000020)
        - [sense organ](http://purl.obolibrary.org/obo/UBERON_0000020) EquivalentTo [organ](http://purl.obolibrary.org/obo/UBERON_0000062) and ([capable of](http://purl.obolibrary.org/obo/RO_0002215) some [detection of stimulus involved in sensory perception](http://purl.obolibrary.org/obo/GO_0050906))
          - [organ](http://purl.obolibrary.org/obo/UBERON_0000062) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [anatomical system](http://purl.obolibrary.org/obo/UBERON_0000467)
            - [anatomical system](http://purl.obolibrary.org/obo/UBERON_0000467) SubClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)
              - [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606)
                - [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606) SubClassOf [Homo](http://purl.obolibrary.org/obo/NCBITaxon_9605)
                  - [Homo](http://purl.obolibrary.org/obo/NCBITaxon_9605) SubClassOf [Homininae](http://purl.obolibrary.org/obo/NCBITaxon_207598)
                    - [Homininae](http://purl.obolibrary.org/obo/NCBITaxon_207598) SubClassOf [Hominidae](http://purl.obolibrary.org/obo/NCBITaxon_9604)
                      - [Hominidae](http://purl.obolibrary.org/obo/NCBITaxon_9604) SubClassOf [Hominoidea](http://purl.obolibrary.org/obo/NCBITaxon_314295)
                        - [Hominoidea](http://purl.obolibrary.org/obo/NCBITaxon_314295) SubClassOf [Catarrhini](http://purl.obolibrary.org/obo/NCBITaxon_9526)
                          - [Catarrhini](http://purl.obolibrary.org/obo/NCBITaxon_9526) SubClassOf [Simiiformes](http://purl.obolibrary.org/obo/NCBITaxon_314293)
                            - [Simiiformes](http://purl.obolibrary.org/obo/NCBITaxon_314293) SubClassOf [Haplorrhini](http://purl.obolibrary.org/obo/NCBITaxon_376913)
                              - [Haplorrhini](http://purl.obolibrary.org/obo/NCBITaxon_376913) SubClassOf [Primates](http://purl.obolibrary.org/obo/NCBITaxon_9443)
                                - [Primates](http://purl.obolibrary.org/obo/NCBITaxon_9443) SubClassOf [Euarchontoglires](http://purl.obolibrary.org/obo/NCBITaxon_314146)
                                  - [Euarchontoglires](http://purl.obolibrary.org/obo/NCBITaxon_314146) SubClassOf [Boreoeutheria](http://purl.obolibrary.org/obo/NCBITaxon_1437010)
                                    - [Boreoeutheria](http://purl.obolibrary.org/obo/NCBITaxon_1437010) SubClassOf [Eutheria](http://purl.obolibrary.org/obo/NCBITaxon_9347)
                                      - [Eutheria](http://purl.obolibrary.org/obo/NCBITaxon_9347) SubClassOf [Theria <Mammalia>](http://purl.obolibrary.org/obo/NCBITaxon_32525)
                                        - [Theria <Mammalia>](http://purl.obolibrary.org/obo/NCBITaxon_32525) SubClassOf [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674)
                                          - [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674) SubClassOf [Amniota](http://purl.obolibrary.org/obo/NCBITaxon_32524)
                                            - [Amniota](http://purl.obolibrary.org/obo/NCBITaxon_32524) SubClassOf [Tetrapoda](http://purl.obolibrary.org/obo/NCBITaxon_32523)
                                              - [Tetrapoda](http://purl.obolibrary.org/obo/NCBITaxon_32523) SubClassOf [Dipnotetrapodomorpha](http://purl.obolibrary.org/obo/NCBITaxon_1338369)
                                                - [Dipnotetrapodomorpha](http://purl.obolibrary.org/obo/NCBITaxon_1338369) SubClassOf [Sarcopterygii](http://purl.obolibrary.org/obo/NCBITaxon_8287)
                                                  - [Sarcopterygii](http://purl.obolibrary.org/obo/NCBITaxon_8287) SubClassOf [Euteleostomi](http://purl.obolibrary.org/obo/NCBITaxon_117571)
                                                    - [Euteleostomi](http://purl.obolibrary.org/obo/NCBITaxon_117571) SubClassOf [Teleostomi](http://purl.obolibrary.org/obo/NCBITaxon_117570)
                                                      - [Teleostomi](http://purl.obolibrary.org/obo/NCBITaxon_117570) SubClassOf [Gnathostomata <vertebrate>](http://purl.obolibrary.org/obo/NCBITaxon_7776)
                                                        - [Gnathostomata <vertebrate>](http://purl.obolibrary.org/obo/NCBITaxon_7776) SubClassOf [Vertebrata <Metazoa>](http://purl.obolibrary.org/obo/NCBITaxon_7742)
                                                          - [Vertebrata <Metazoa>](http://purl.obolibrary.org/obo/NCBITaxon_7742) SubClassOf [Craniata <chordata>](http://purl.obolibrary.org/obo/NCBITaxon_89593)
                                                            - [Craniata <chordata>](http://purl.obolibrary.org/obo/NCBITaxon_89593) SubClassOf [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711)
                                                              - [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711) SubClassOf [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511)
                                        - [Theria <Mammalia>](http://purl.obolibrary.org/obo/NCBITaxon_32525) SubClassOf [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Theria <Mammalia>](http://purl.obolibrary.org/obo/NCBITaxon_32525)
  - [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511)
  - [overlaps](http://purl.obolibrary.org/obo/RO_0002131) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

# Axiom Impact 
## Axioms used 20 times
- [Boreoeutheria](http://purl.obolibrary.org/obo/NCBITaxon_1437010) SubClassOf [Eutheria](http://purl.obolibrary.org/obo/NCBITaxon_9347) [ext.owl]
- [Homininae](http://purl.obolibrary.org/obo/NCBITaxon_207598) SubClassOf [Hominidae](http://purl.obolibrary.org/obo/NCBITaxon_9604) [ext.owl]
- [Euarchontoglires](http://purl.obolibrary.org/obo/NCBITaxon_314146) SubClassOf [Boreoeutheria](http://purl.obolibrary.org/obo/NCBITaxon_1437010) [ext.owl]
- [Simiiformes](http://purl.obolibrary.org/obo/NCBITaxon_314293) SubClassOf [Haplorrhini](http://purl.obolibrary.org/obo/NCBITaxon_376913) [ext.owl]
- [Hominoidea](http://purl.obolibrary.org/obo/NCBITaxon_314295) SubClassOf [Catarrhini](http://purl.obolibrary.org/obo/NCBITaxon_9526) [ext.owl]
- [Theria <Mammalia>](http://purl.obolibrary.org/obo/NCBITaxon_32525) SubClassOf [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674) [ext.owl]
- [Haplorrhini](http://purl.obolibrary.org/obo/NCBITaxon_376913) SubClassOf [Primates](http://purl.obolibrary.org/obo/NCBITaxon_9443) [ext.owl]
- [Eutheria](http://purl.obolibrary.org/obo/NCBITaxon_9347) SubClassOf [Theria <Mammalia>](http://purl.obolibrary.org/obo/NCBITaxon_32525) [ext.owl]
- [Primates](http://purl.obolibrary.org/obo/NCBITaxon_9443) SubClassOf [Euarchontoglires](http://purl.obolibrary.org/obo/NCBITaxon_314146) [ext.owl]
- [Catarrhini](http://purl.obolibrary.org/obo/NCBITaxon_9526) SubClassOf [Simiiformes](http://purl.obolibrary.org/obo/NCBITaxon_314293) [ext.owl]
- [Hominidae](http://purl.obolibrary.org/obo/NCBITaxon_9604) SubClassOf [Hominoidea](http://purl.obolibrary.org/obo/NCBITaxon_314295) [ext.owl]
- [Homo](http://purl.obolibrary.org/obo/NCBITaxon_9605) SubClassOf [Homininae](http://purl.obolibrary.org/obo/NCBITaxon_207598) [ext.owl]
- [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606) SubClassOf [Homo](http://purl.obolibrary.org/obo/NCBITaxon_9605) [ext.owl]
- [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ext.owl]

## Axioms used 19 times
- [Euteleostomi](http://purl.obolibrary.org/obo/NCBITaxon_117571) SubClassOf [Teleostomi](http://purl.obolibrary.org/obo/NCBITaxon_117570) [ext.owl]
- [Dipnotetrapodomorpha](http://purl.obolibrary.org/obo/NCBITaxon_1338369) SubClassOf [Sarcopterygii](http://purl.obolibrary.org/obo/NCBITaxon_8287) [ext.owl]
- [Tetrapoda](http://purl.obolibrary.org/obo/NCBITaxon_32523) SubClassOf [Dipnotetrapodomorpha](http://purl.obolibrary.org/obo/NCBITaxon_1338369) [ext.owl]
- [Amniota](http://purl.obolibrary.org/obo/NCBITaxon_32524) SubClassOf [Tetrapoda](http://purl.obolibrary.org/obo/NCBITaxon_32523) [ext.owl]
- [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674) SubClassOf [Amniota](http://purl.obolibrary.org/obo/NCBITaxon_32524) [ext.owl]
- [Sarcopterygii](http://purl.obolibrary.org/obo/NCBITaxon_8287) SubClassOf [Euteleostomi](http://purl.obolibrary.org/obo/NCBITaxon_117571) [ext.owl]

## Axioms used 18 times
- [Teleostomi](http://purl.obolibrary.org/obo/NCBITaxon_117570) SubClassOf [Gnathostomata <vertebrate>](http://purl.obolibrary.org/obo/NCBITaxon_7776) [ext.owl]
- [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794) SubClassOf [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317) [ext.owl]
- [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656) SubClassOf [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770) [ext.owl]
- [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711) SubClassOf [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511) [ext.owl]
- [Vertebrata <Metazoa>](http://purl.obolibrary.org/obo/NCBITaxon_7742) SubClassOf [Craniata <chordata>](http://purl.obolibrary.org/obo/NCBITaxon_89593) [ext.owl]
- [Gnathostomata <vertebrate>](http://purl.obolibrary.org/obo/NCBITaxon_7776) SubClassOf [Vertebrata <Metazoa>](http://purl.obolibrary.org/obo/NCBITaxon_7742) [ext.owl]
- [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770) SubClassOf [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794) [ext.owl]
- [Craniata <chordata>](http://purl.obolibrary.org/obo/NCBITaxon_89593) SubClassOf [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711) [ext.owl]
- [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511) [ext.owl]

## Axioms used 16 times
- [Theria <Mammalia>](http://purl.obolibrary.org/obo/NCBITaxon_32525) SubClassOf [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Theria <Mammalia>](http://purl.obolibrary.org/obo/NCBITaxon_32525) [ext.owl]
- [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606) [ext.owl]

## Axioms used 15 times
- [anatomical system](http://purl.obolibrary.org/obo/UBERON_0000467) SubClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) [ext.owl]
- [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [overlaps](http://purl.obolibrary.org/obo/RO_0002131) [ext.owl]
- [overlaps](http://purl.obolibrary.org/obo/RO_0002131) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ext.owl]

## Axioms used 14 times
- [compound eye](http://purl.obolibrary.org/obo/UBERON_0000018) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656) [ext.owl]
- [organ](http://purl.obolibrary.org/obo/UBERON_0000062) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [anatomical system](http://purl.obolibrary.org/obo/UBERON_0000467) [ext.owl]

## Axioms used 13 times
- [eye](http://purl.obolibrary.org/obo/UBERON_0000970) SubClassOf [sense organ](http://purl.obolibrary.org/obo/UBERON_0000020) [ext.owl]

**Comment by balhoff** [comment]
`anatomical structure SubClassOf part of some Homo sapiens` seems a bit presumptuous. 😄 Did that get added by accident?

**Comment by matentzn** [comment]
now solved - its part of the magic sauce. thanks Jim!
