### ISSUE TITLE
UBERON:0014888 iliotibialis muscle: taxon notes + typos in def and synonyms

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1832]
UBERON:0014888 iliotibialis muscle
currently has
A muscle in amphibians that connects originates in the ilium and inserts in the tibia. [ https://www.worldcat.org/search?q=bn%3A0073040584 ]
exact syn: m. iliotibilias
broad synonym: iliotibilias

- [ ] A taxon note should be added to restrict to amphibians, if that's the case
- [ ] The label may be disambiguated accordingly, if desired
- [ ] "connects originates" in the def should be corrected
- [ ] both synonyms should presumably be corrected iliotibilias => iliotibialis

Thanks!
Paola

**Comment by paolaroncaglia** [comment]
@cmungall 
May I assign to you please? Or could you 'volunteer' someone else? :-)

**Comment by paolaroncaglia** [comment]
Hi @wdahdul ,
Could you advice on this ticket, please? Thank you.
Paola

**Comment by paolaroncaglia** [comment]
Following up on https://github.com/obophenotype/uberon/issues/1832#issue-858656801, a quick search suggests that 'iliotibialis _muscle_' is not found in human (the iliotibial tract/band is not the same thing). It may however be found in some birds, but I don't have full access to literature on the issue. As mentioned earlier, I'd be happy for someone else to look into this and do the edits. If not, feel free to close. Thanks.
