### ISSUE TITLE
UBERON:0002323 coelemic cavity lumen and UBERON:0003886 future coelemic cavity lumen

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1834]
**Uberon term**
UBERON:0002323 coelemic cavity lumen
UBERON:0003886 future coelemic cavity lumen

**Bug description**
"coelemic" is a less frequent spelling of "coelomic". For consistency with usage (including elsewhere in Uberon), I'd suggest making "[future] coelemic cavity lumen" an exact synonym, and "[future] coelomic cavity lumen" the primary label. Thanks.

(Update: on further inspection, UBERON:0002323 coelemic cavity lumen has plenty of xrefs and the alternative spelling as an exact synonym already, so I'll leave things as are, and just add the alternative spelling to UBERON:0003886 future coelemic cavity lumen for consistency.)

**Comment by paolaroncaglia** [comment]
Note to self: I forgot to link the PR, it's https://github.com/obophenotype/uberon/pull/2255.
