### ISSUE TITLE
UBERON:0018387 cestode

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1835]
**Uberon term**
UBERON:0018387 cestode

**Reason for deprecation**
"Any of a class (Cestoda) of bilaterally symmetrical flatworms parasitic especially in the intestines of vertebrates. [ http://purl.obolibrary.org/obo/BTO_0005278 ]"
Subclass of larva
This looks incorrect and feels like it should be replaced by NCBITaxon:6199 Cestoda. There's another existing term to represent a cestode larva, though very species-specific: UBERON:0018379 meracestode ("The larval (metacestode) stage of the tapeworm Echinococcus multilocularis. [ http://purl.obolibrary.org/obo/BTO_0000859 ]").  If desired/useful, a broad term for 'cestode larva' could be created in place of 'cestode' to represent any tapeworm larva?

**Suggested replacement or term to consider**
NCBITaxon:6199 Cestoda

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@gouttegd @dosumis 
Perhaps one of you could address this, please? Thanks.

**Comment by paolaroncaglia** [comment]
@cmungall @dosumis please could one of you comment on the need/correctness of having a taxon (Cestoda) as a UBERON class? 
If it's ok to have, feel free to close this ticket.
If it isn't and you wish to obsolete the term, please assign to someone other than me to avoid conflicts of interest :-)
Thanks!

**Comment by dosumis** [comment]
Agree it does not belong in Uberon

**Comment by dosumis** [comment]
@gouttegd - are you happy to obsolete?

**Comment by gouttegd** [comment]
Will do. :)
