### ISSUE TITLE
Typo in synonym of UBERON:0004122 genitourinary system

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1836]
**Uberon term**
UBERON:0004122 genitourinary system

**Bug description**
has related synonym Urogenitalsystem
Should be urogenital system.
Thanks
Paola

**Comment by paolaroncaglia** [comment]
Actually, the typo-containing (related) synonym is imported from BTO, and it's not worth asking them to fix, so I'll close. (The correct synonym is already in place.)
