### ISSUE TITLE
UBERON:2000711 DEL

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1838]
**Uberon term**
UBERON:2000711 DEL

**Suggested revision of label**
Comes from ZFA: "A multilayer of deep cells of fairly uniform thickness that forms during early epiboly (at dome stage; upon conversion of the blastodisc to the blastoderm); during gastrulation the DEL (deep cell layer) gives rise to the epiblast and hypoblast. Kimmel et al, 1995."
has exact synonym: deep cell layer, DEL cells
Please consider swapping label and exact synonym (deep cell layer), and adding "gastrulation" or similar to disambiguate the label further. 

Thanks, 
Paola

**Comment by paolaroncaglia** [comment]
Hi, who could I ask for feedback on a term that came from ZFA/teleost curators, please? Thanks.

**Comment by nicolevasilevsky** [comment]
Maybe @ybradford could help.

**Comment by nicolevasilevsky** [comment]
@sabrinatoro do you have any expertise in this area? Or do you know someone from ZFIN that could potentially help? thanks!

**Comment by ybradford** [comment]
@nicolevasilevsky @paolaroncaglia I can help. I might not be able to take action today but will make sure it gets changed. The suggested change seems reasonable.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky and @paolaroncaglia 
When  "DEL" is mainly used in zebrafish publication, everyone knows (or should know) what DEL refers to. 

I took a look at the terms for the other blastomere layers. The labels are: 
- 'yolk syncytial layer' (synonym: YSL) in ZFA --> corresponds to UBERON: 'yolk syncytial layer'
- 'EVL' (synonym: enveloping layer) in ZFA --> corresponds to UBERON: 'enveloping layer of ectoderm'

Therefore I think it would be ok to update the label of 'DEL' in UBERON to 'deep cell layer', and add 'DEL' as an exact synonym. 


WRT adding "gastrulation" in the label : 
from a zebrafish community perspective, there will never be any confusion about what the "deep cell layer" means. If one needs to talk about the cell layer that is deep in a specific tissue, they would not use "deep cell layer". 
However, I appreciate that UBERON would be used by a broader community than the zebrafish community. And therefore I think adding "gastrulation" would be fine. 

Please let me know if you need me to make these changes in the ontology. I would be happy to.

**Comment by nicolevasilevsky** [comment]
Thanks @ybradford and @sabrinatoro. 
@sabrinatoro please go ahead and make the edits, thanks!

**Comment by paolaroncaglia** [comment]
@ybradford @sabrinatoro thank you both! Yes, ideally we'd want to make the labels as unambiguous as possible. Also, for synonyms that are actually abbreviation/acronyms, you could add an annotation property has_synonym_type = abbreviation. My personal preference would be for DEL not to be an exact synonym, but rather broad or related, because it's potentially not unambiguous in the broader non-zebrafish community (short acronyms rarely are). Thank you!
