### ISSUE TITLE
NTR: vein of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1840]
**Preferred term label:**
vein of appendix

**Synonyms**
vein of appendix vermiformis
vein of vermiform appendix

**Definition (free text, please give PubMed ID)**
Vein that is part of a vermiform appendix.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154
vein http://purl.obolibrary.org/obo/UBERON_0001638

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410044 vein of appendix
