### ISSUE TITLE
NTR: artery of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1841]
**Preferred term label:**
artery of appendix

**Synonyms**
artery of appendix vermiformis
artery of vermiform appendix

**Definition (free text, please give PubMed ID)**
Artery that is part of a vermiform appendix.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154
artery http://purl.obolibrary.org/obo/UBERON_0001637

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410045 artery of appendix
