### ISSUE TITLE
NTR: smooth muscle circular layer of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1842]
**Preferred term label:**
smooth muscle circular layer of appendix

**Synonyms**
smooth muscle circular layer of appendix vermiformis
smooth muscle circular layer of vermiform appendix

**Definition (free text, please give PubMed ID)**
A circular muscle layer of muscular coat that is part of a vermiform appendix smooth muscle.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154
intestine smooth muscle http://purl.obolibrary.org/obo/UBERON_0004221

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410046 appendix smooth muscle circular layer
