### ISSUE TITLE
NTR: serosal nerve fibre of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1844]
**Preferred term label:**
serosal nerve fibre of appendix

**Synonyms**
serosal nerve fibre of appendix vermiformis
serosal nerve fibre of vermiform appendix

**Definition (free text, please give PubMed ID)**
Nerve fibre that is located in the serosa of appendix vermiformis.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
serosa of appendix http://purl.obolibrary.org/obo/UBERON_0012498

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
Note to self: I need to address a conflict in the PR

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410049 serosal nerve fiber of appendix
(Note, "fiber" instead of "fibre", to conform to the American spelling used in Uberon. I've added exact synonyms with the "fibre" spelling.)
