### ISSUE TITLE
NTR: myenteric nerve plexus of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1845]
**Preferred term label:**
myenteric nerve plexus of appendix

**Synonyms**
myenteric nerve plexus of appendix vermiformis
myenteric nerve plexus of vermiform appendix

**Definition (free text, please give PubMed ID)**
Myenteric nerve plexus that is located in the appendix

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
myenteric nerve plexus http://purl.obolibrary.org/obo/UBERON_0002439
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410011 myenteric nerve plexus of appendix
