### ISSUE TITLE
NTR: submucous nerve plexus of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1846]
**Preferred term label:**
submucous nerve plexus of appendix

**Synonyms**
submucous nerve plexus of appendix vermiformis
submucous nerve plexus of vermiform appendix

**Definition (free text, please give PubMed ID)**
Submucous nerve plexus that is located in the vermiform appendix.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
submucous nerve plexus http://purl.obolibrary.org/obo/UBERON_0005304
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410012 submucous nerve plexus of appendix
