### ISSUE TITLE
Typos in 2 obsolete labels

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1847]
**Uberon term**
http://purl.obolibrary.org/obo/UBERON_2005235 | obsoelte UCoD
http://purl.obolibrary.org/obo/UBERON_2005177 | obsoelte VeLD

**Bug description**
You may want to correct "obsoelte" in "obsolete" please. Thanks.

**Comment by paolaroncaglia** [comment]
These typos have been fixed by someone else. Closing now.
