### ISSUE TITLE
teeth terms in uberon

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1848]
I've been working on the teeth terms for FOVT, and they are inconsistent in their axioms and their labels. Below are a couple of examples as well as a suggestion for some patterns. I come from a paleo/modern biology background (i.e., not human or model organisms) so it'd be great to get feedback if I'm using terms that are particular to just my field.

### Issues with teeth:

- do we need to include the term “tooth”
- primary/secondary or deciduous/permanent
- do we need to create parent terms?
- currently defined under most specific (e.g., ‘deciduous premolar tooth 5’ and (‘part of’ some ‘upper jaw region’) for upper primary premolar tooth 5, when it should be: ‘premolar tooth 5’ and (‘part of’ some ‘upper jaw region’) and (‘part of’ some ‘primary dentition’)

### Patterns:
(Note: for all patterns would have to manually put in synonyms such as dM3 [deciduous upper molar 3])
(Note: would have to do repeated pattern for each tooth type as the number of each changes (e.g., molars: 1-4; incisors: 1-6; etc.)

#### General:
Vars: tooth type; number
Vars: lower/upper; tooth type
Vars: deciduous/permanent; tooth type

Subclass tooth type; def: Tooth type phylogenetically in position number.
Axiom: tooth type and (‘part of’ some ‘lower/upper jaw region’)
Axiom: tooth type and ‘deciduous/permanent dentition’
	syn: primary/secondary

#### Specific:
Vars: deciduous/permanent; tooth type; number
Vars: lower/upper; tooth type; number

Axiom: tooth type # and ‘deciduous/permanent dentition'
	syn: primary/secondary
Axiom: tooth type # and (‘part of’ some ‘lower/upper jaw region’)

#### Most Specific:
Vars: lower/upper; deciduous/permanent; tooth type; number
e.g., lower deciduous molar 1

Axiom: tooth type # and ‘deciduous/permanent dentition’ and (‘part of’ some ‘lower/upper jaw region’)
	syn: primary/secondary

**Comment by megbalk** [comment]
@nicolevasilevsky suggested that I tag @markengelstad for feedback

**Comment by markengelstad** [comment]
Thanks for including me. I've been building a knowledge graph that includes all dental concepts including dental anatomy so I've been thinking about this for a while and you have hit one some good issues/ modeling decisions.

let's have a zoom call -- might be too much to type.  I have some standards that I've built into my graph (which is designed to be used by clinicians, not zoologists but hopefully still helpful) 

invite me at markengelstad@gmail.com.  
best days are tues,thurs,fri

**Comment by megbalk** [comment]
Here is the new patterns I have made. Feedback would be great! @markengelstad 

[teeth-pattern.txt](https://github.com/obophenotype/uberon/files/6534101/teeth-pattern.txt)

**Comment by megbalk** [comment]
@cmungall feedback on these patterns would be great. If they're good, I can start making terms and standardizing how we define teeth.

**Comment by megbalk** [comment]
@mellybelly I heard from @nicolevasilevsky that you started the teeth terms, so your input is definitely welcomed!

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,
When you have a chance, could you please update this ticket? Thanks.

**Comment by megbalk** [comment]
Here is the newest teeth pattern. I'd love feedback before testing it.

**Comment by megbalk** [comment]
covered in issue #2479
