### ISSUE TITLE
sagittal crest

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1849]
**Uberon term**
Sagittal crest is currently used to define a skull structure. However, sagittal crest is a more general anatomical term and used for other bones (e.g., sagittal crest of humerus). 

**Suggested solution**
- Fix sagittal crest label to be about the skull
- Create a more general sagittal crest term

**Comment by paolaroncaglia** [comment]
Assigning to @megbalk (tentatively) as she opened this ticket. Thanks Meghan.

**Comment by megbalk** [comment]
created branch: issue-1849

**Comment by megbalk** [comment]
@matentzn @cmungall what is the best practice for renaming a term and creating a new term that has the same name (e.g., renaming "sagittal crest" to "sagittal crest of skull" and creating the term "sagittal crest")?

**Comment by matentzn** [comment]
The cleaner version is to deprecate the old and create two new terms. Sound like a case of splitting.

**Comment by cmungall** [comment]
I think that's safest

**Comment by RDruzinsky** [comment]
I agree

**Comment by megbalk** [comment]
cranial crest does not have a definition and the source is no longer active.

**Comment by cmungall** [comment]
Also agree

**Comment by megbalk** [comment]
@cmungall @rays22 @RDruzinsky see the changes on the branch "redo-issue-1849" (PR #2635 )

**Comment by rays22** [comment]
I think this issue is fixed in https://github.com/obophenotype/uberon/pull/2635.
