### ISSUE TITLE
arteriole of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1851]
**Preferred term label:**
arteriole of anal canal

**Synonyms**
anal canal arteriole

**Definition (free text, please give PubMed ID)**
Arteriole that is located in the anal canal

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159
arteriole http://purl.obolibrary.org/obo/UBERON_0001980

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
The new term is 
UBERON:8410009 anal canal arteriole
The wording is consistent with existing sibling terms in Uberon, but I kept 'arteriole of anal canal' as an exact synonym.
The term will be available in the next Uberon release, which is planned to be completed by June 1st at the latest.
Thanks,
Paola

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'arteriole of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
> hi @paolaroncaglia, can we please change this term to 'arteriole of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

@sfexova done
