### ISSUE TITLE
NTR: venule of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1852]
**Preferred term label:**
venule of anal canal

**Synonyms**
anal canal venule

**Definition (free text, please give PubMed ID)**
Venule that is located in the anal canal

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159
venule http://purl.obolibrary.org/obo/UBERON_0001979

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410008 anal canal venule

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'venule of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
> hi @paolaroncaglia, can we please change this term to 'venule of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

@sfexova done
