### ISSUE TITLE
NTR: submucous nerve plexus of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1854]
**Preferred term label:**
submucous nerve plexus of anal canal

**Synonyms**
anal canal submucous nerve plexus

**Definition (free text, please give PubMed ID)**
Submucous nerve plexus that is located in the anal canal

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
submucous nerve plexus http://purl.obolibrary.org/obo/UBERON_0005304
anal canal http://purl.obolibrary.org/obo/UBERON_0000159

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410006 submucous nerve plexus of anal canal

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'submucus nerve plexus of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
> hi @paolaroncaglia, can we please change this term to 'submucus nerve plexus of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

@sfexova done
