### ISSUE TITLE
transitional glandular epithelium of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1855]
**Preferred term label:**
transitional glandular epithelium of anal canal

**Synonyms**
anal canal transitional glandular epithelium

**Definition (free text, please give PubMed ID)**
Glandular epithelium of the anal transition zone. The anal transition zone is defined loosely as the tissue interposed between the uninterrupted squamous epithelium of the anoderm and the uninterrupted mucosal epithelium of the anal canal. PMID: 8425694

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159
anal canal epithelium http://purl.obolibrary.org/obo/UBERON_0015716
glandular epithelium http://purl.obolibrary.org/obo/UBERON_0006799

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410005 transitional glandular epithelium of anal canal
Will be available at next Ub. release (release date in discussion at today's anatomy editors' meeting).

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'transitional glandular epithelium of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
> hi @paolaroncaglia, can we please change this term to 'transitional glandular epithelium of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

@sfexova and done.
