### ISSUE TITLE
intercondylar fossa

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#1856]
**Uberon term**
intercondylar fossa http://purl.obolibrary.org/obo/UBERON_4200096

trochlear groove of femur Uberon:3000785 is "obsolete" term. (see upload from Protege)
<img width="1047" alt="Screen Shot 2021-05-13 at 3 30 01 PM" src="https://user-images.githubusercontent.com/47257000/118245218-8672ba00-b46e-11eb-8f37-4bf11c25b2f1.png">

**Synonym to be added**
https://en.wikipedia.org/wiki/Intercondylar_fossa_of_femur 
The intercondylar fossa of femur and/or the patellar surface may also be referred to as the patellar groove, patellar sulcus, patellofemoral groove, femoropatellar groove, femoral groove, femoral sulcus, trochlear groove of femur, trochlear sulcus of femur, trochlear surface of femur, or trochlea of femur.

**broad/exact/narrow/related ?**

**Comment by paolaroncaglia** [comment]
Note for self: ideally the synonyms should be available by mid-June. Need to factor release plans in.

**Comment by wdahdul** [comment]
I just added the list above of synonyms to the term in ext. Let me know if anything might still missing. Thanks!

**Comment by paolaroncaglia** [comment]
@wdahdul thanks for adding those synonyms. I'll add you as an assignee.
@emquardokus the synonyms will be available at the next Uberon release, not sure when exactly, but I've asked about a timeline (added to the agenda for tomorrow's CL/Uberon editors meeting).
Best,
Paola

**Comment by emquardokus** [comment]
Thanks to all!
