### ISSUE TITLE
Can't find UBERON:4200096 intercondylar fossa in uberon_edit.obo

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1858]
**Uberon term**
UBERON:4200096 intercondylar fossa

**Bug description**
This term is in OLS: http://purl.obolibrary.org/obo/UBERON_4200096, stemming from https://github.com/obophenotype/uberon/issues/1856
But I can't find it in uberon_edit.obo. I last edited the file on March 26th. I can see my latest edits as well as edits done by Chris after that date, but no trace of UBERON_4200096. I couldn't find any mention of that term being modified since the last release in tickets or commits (and I'd have expected to find the ID in the file anyway). I must be missing something obvious, just not sure what :-D 

Thanks,
Paola

**Comment by balhoff** [comment]
It looks like this term is edited here: https://github.com/obophenotype/uberon-phenoscape-ext/blob/master/phenoscape-ext.owl

The plan is to integrate this back into the main repo (https://github.com/obophenotype/uberon-phenoscape-ext/issues/18).

**Comment by paolaroncaglia** [comment]
> It looks like this term is edited here: https://github.com/obophenotype/uberon-phenoscape-ext/blob/master/phenoscape-ext.owl

Thanks @balhoff for clarifying! 

> The plan is to integrate this back into the main repo ([obophenotype/uberon-phenoscape-ext#18](https://github.com/obophenotype/uberon-phenoscape-ext/issues/18)).

Ok. @emquardokus asked if synonyms could be added to UBERON:4200096 in time to be released/public by mid-June, needed for the CCF-ASCT tables. Should I ask phenoscape editors to address #1856 please? Or will https://github.com/obophenotype/uberon-phenoscape-ext/issues/18 be addressed and committed in time for me to edit UBERON:4200096 in the merged file, and (have someone) release by mid-June? Or, lastly, should we ask Ellen to wait a bit longer.
cc @dosumis for his information.

Thanks all!
Paola

**Comment by balhoff** [comment]
@wdahdul could you add the synonym in #1856?

**Comment by wdahdul** [comment]
I added the synonyms to ext (https://github.com/obophenotype/uberon-phenoscape-ext/commit/cfde6012b8cde1b4e7e14f05475dbaba72cca5d8).

**Comment by paolaroncaglia** [comment]
@wdahdul (and @balhoff )

> I added the synonyms to ext ([obophenotype/uberon-phenoscape-ext@cfde601](https://github.com/obophenotype/uberon-phenoscape-ext/commit/cfde6012b8cde1b4e7e14f05475dbaba72cca5d8)).

Thank you very much!
Paola

**Comment by paolaroncaglia** [comment]
I'm closing this ticket now. I retrospectively assigned it to @wdahdul and @balhoff  for their contribution. Thanks again.
