### ISSUE TITLE
NTR: lymphatic capillary of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1866]
**Preferred term label:**
lymphatic capillary of anal canal

**Synonyms**
anal canal lymphatic capillary

**Definition (free text, please give PubMed ID)**
Lymphatic capillary that is located in the anal canal.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159
lymphatic capillary http://purl.obolibrary.org/obo/UBERON_0006842

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'lymphatic capillary of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410055 lymphatic capillary of anorectum
