### ISSUE TITLE
NTR: myenteric nerve plexus of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1867]
**Preferred term label:**
myenteric nerve plexus of colon

**Synonyms**

**Definition (free text, please give PubMed ID)**
Myenteric nerve plexus that is part of the colon.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
myenteric nerve plexus http://purl.obolibrary.org/obo/UBERON_0002439
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by sfexova** [comment]
I think the current colon definition "Last portion of the large intestine before it becomes the rectum." is not correct - it's not just the last part of large intestine before rectum, it's pretty much all of it, sin't it - we have ascending, transverse, descending and sigmoidal colon

**Comment by paolaroncaglia** [comment]
@sfexova 

> I think the current colon definition "Last portion of the large intestine before it becomes the rectum." is not correct - it's not just the last part of large intestine before rectum, it's pretty much all of it, sin't it - we have ascending, transverse, descending and sigmoidal colon

My understanding is that the above is not the case in all vertebrates, while Uberon 'colon' is meant to cover all vertebrates, and may need some editing to that extent. See the following in the right-hand panel of the [OLS entry](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001155):

editor note: TODO - abstract this such that it legitimately covers all vertebrates

homology notes: Although all vertebrates have a digestive tract and accessory glands, various parts of this system are not necessarily homologous, analogous, or even present in all species. Therefore, broad comparisons can be best made under the listings of headgut, foregut, midgut, pancreas and biliary system, hindgut.

taxon notes: In zebrafish, the posterior intestine has short longitudinally arranged epithelial folds which are similar to the colon of higher vertebrates[ZFIN]; In mammals, the colon consists of four sections: the ascending colon, the transverse colon, the descending colon, and the sigmoid colon[WP]

There are Uberon terms for ascending, transverse, descending and sigmoid colon (see children of 'proximal-distal subdivision of colon'). In the anatomograms, do you wish the requested term 'myenteric nerve plexus of colon' to apply to the whole large intestine (or most of it anyway), or only to a specific portion of it i.e. one or more of the colon "subcategories"?

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Note to self, the colon discussion was moved to #1869 .

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410058 myenteric nerve plexus of colon
