### ISSUE TITLE
NTR: submucous nerve plexus of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1868]
**Preferred term label:**
submucous nerve plexus of colon

**Synonyms**

**Definition (free text, please give PubMed ID)**
Submucous nerve plexus that is part of a colon.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
colon http://purl.obolibrary.org/obo/UBERON_0001155
submucous nerve plexus http://purl.obolibrary.org/obo/UBERON_0005304

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410059 submucous nerve plexus of colon
