### ISSUE TITLE
NTR: anorectum

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1872]
As requested by @sfexova after offline discussion, for use in the Single Cell Expression Atlas anatomograms:

**Preferred term label:**
anorectum

**Synonyms**
anorectal canal [narrow]
anorectal [relational adjective]

**Definition (free text, please give PubMed ID)**
A subdivision of the digestive tract in humans that includes the rectum, the anal canal and the anus. 
https://link.springer.com/chapter/10.1007/978-3-319-26938-2_8 ( DOI https://doi.org/10.1007/978-3-319-26938-2_8 , ISBN 978-3-319-26936-8)
https://pubs.rsna.org/doi/full/10.1148/rg.2015150037 (https://doi.org/10.1148/rg.2015150037)
PMID:29742860

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
equivalent to 'subdivision of digestive tract' and 'has part' some rectum and 'has part' some 'anal canal' and 'has part' some anus
present in taxon Homo sapiens 

**Your nano-attribution (ORCID)**
Silvie's ORCID: https://orcid.org/0000-0003-3440-1876

Optional: editor note: Although a few resources seem to only include the distal part of the rectum in 'anorectum', this grouping term is meant to refer more broadly to the whole of rectum, anal canal and anus.

**Comment by paolaroncaglia** [comment]
@cmungall 
Would you or others have any objection to the creation of a grouping term for 'anorectum' as described in https://github.com/obophenotype/uberon/issues/1872#issue-902530452? Sorry for pestering, I'd like to get the edits in for SCA, in time for the next Uberon release. Thanks!

**Comment by sfexova** [comment]
Hi @paolaroncaglia - thank you! Just one question, sorry if it's a dumb one - I know you mentioned offline that rectum cannot be made part of anorectum because that wouldn’t be true for species that don’t have an anal canal but where exactly does the current definition and relationships place this term in the ontology? - Is this term going to be under 'large intestine' and have children 'rectum', 'anal canal' and 'anus'?

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,

> Hi @paolaroncaglia - thank you! Just one question, sorry if it's a dumb one - I know you mentioned offline that rectum cannot be made part of anorectum because that wouldn’t be true for species that don’t have an anal canal but where exactly does the current definition and relationships place this term in the ontology? - Is this term going to be under 'large intestine' and have children 'rectum', 'anal canal' and 'anus'?

I created the term in Protege so I can show you how it would appear after running the reasoner. I also opened a pull request so that the edit may be reviewed by others and commented/approved as appropriate. The term won't be committed to the live Uberon ontology until then. So, please see the image attached:

![Screen Shot 2021-05-27 at 16 31 36](https://user-images.githubusercontent.com/4982516/119845719-cbd0c600-bf09-11eb-9667-203bc71db6ca.png)

'anorectum' would be a child of 'subdivision of digestive tract'.
It would have, as has_part children, rectum, anal canal and anus.
I didn't make anorectum part_of large intestine because I'm not 100% sure that anus is part_of large intestine. I think that that link doesn't exist in the ontology because not all species that have an anus also have a large intestine. Also, the definition of large intestine is not clear-cut on whether the anus is _part_ of the large intestine proper ("A subdivision of the digestive tract that _connects_ the small intestine to the cloaca or anus."). 
I can enquire about the above if the proposed ontology structure would not work for the anatomograms.

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
So I tested addition of
anorectum 'part of' some 'large intestine' 
Nothing breaks in Uberon pipeline checks, but I'm still really not sure that anus is meant to be included in the definition of large intestine.

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] double-check that DOIs resolve

**Comment by paolaroncaglia** [comment]
Note to self, I'm stuck until @sfexova confirms if we can exclude 'anus' from 'anorectum' or, better, 'anorectal canal', see discussion in https://github.com/obophenotype/uberon/pull/1875#issuecomment-849775182.

**Comment by sfexova** [comment]
Hi @paolaroncaglia, sorry was busy with preparing for a workshop we ran last week. I went through a number of papers and book chapters that I could find but I still am not clear on this. When talking about anorectum they usually refer to it as rectum + anus but clearly meaning anus sensu lato: e.g. 'The last part of the gastrointestinal canal, the rectum and the anus'
I will have to consult Mark on this - a) whether anus proper is part of anorectum and b) whether anus is part of large intestine

**Comment by RDruzinsky** [comment]
Take a look at the British Gray's Anatomy and see what you think.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by paolaroncaglia** [comment]
Hi @sfexova and @RDruzinsky ,
Thank you both for your feedback. I don't have access to the British Gray's Anatomy at the moment, but I suspect it may be in line with what @RDruzinsky summarized in https://github.com/obophenotype/uberon/pull/1875#issuecomment-849754983. @sfexova , if it helps, please keep in mind that when resources/references don't universally agree on nomenclature or partonomy, we have the option of representing one of the two views in the ontology (the one that's most supported, or that has the most recent evidences, or that sounds most reasonable to us or the experts we refer to...). As long as we document, e.g. in a comment, that some literature uses a different nomenclature or partonomy, and include references, it's ok. The ontology is a representation of the field - if there are 2 views in that field, we can reflect that as free text.

**Comment by sfexova** [comment]
Thanks all for your feedback, it really is a tricky one and I unfortunately also do not have access to specialist literature beyond what is available online. I have however heard back from Mark (Arends) regarding this and his view is the following:

> 1. Anorectum includes anus, anal canal, anorectal junction (including transitional zone), and rectum - anatomically speaking - this is what the international anatomical and pathological literature uses and supports, which we should use in the anatomogram.
> 2. Anus is anatomically considered to be the last part or termination of the large intestine.

**Comment by paolaroncaglia** [comment]
@sfexova 
cc @RDruzinsky 
I think if I add a taxon constraint to 'anorectum' (i.e. a computational rule to restrict use of 'anorectum' to the species we're focusing on), and some explanatory text, it might be ok to make anorectum part of large intestine without breaking anything. 
To play it safe, and for the sake of brevity, I'd make anorectum present in taxon Homo sapiens. 
If you or others have any objection please let me know asap, if not I'll create the term tomorrow. Thanks.

**Comment by paolaroncaglia** [comment]
For reference for other editors, here's the full reply from Mark Arends:
"1. Anorectum includes anus, anal canal, anorectal junction (including transitional zone), and rectum - anatomically speaking - this is what the international anatomical and pathological literature uses and supports, which we should use in the anatomogram.
The term "anus proper” is almost never used anatomically or in medical practice - the term “anus" is used.
2. Anus is anatomically considered to be the last part or termination of the large intestine.
3. No, the term anorectal canal is not considered  to be anatomically correct (because the rectum is not a canal). It would have to be “rectum" and "anal canal”. However, the anatomically correct solution is to use the term anorectum to include the anus (as described in my answer 1 above) and to have this as part of the large intestine (the anus is considered to be a part of the large intestine anatomically, pathologically and medically)."

@sfexova 
Could you please find out Mark's ORCID and write it in a comment here, so I can append it to the new term?

**Comment by sfexova** [comment]
https://orcid.org/0000-0002-6826-8770 I believe

**Comment by paolaroncaglia** [comment]
@sfexova 
Here it goes:

id: UBERON:8410050
name: anorectum
def: "A subdivision of the digestive tract in humans that includes the rectum, the anal canal and the anus." [DOI:10.1007/978-3-319-26938-2_8, DOI:10.1148/rg.2015150037, http://orcid.org/0000-0002-6826-8770, http://orcid.org/0000-0003-3440-1876, PMID:29742860]
synonym: "anorectal canal" NARROW []
intersection_of: UBERON:0004921 ! subdivision of digestive tract
intersection_of: has_part UBERON:0000159 ! anal canal
intersection_of: has_part UBERON:0001052 ! rectum
intersection_of: has_part UBERON:0001245 ! anus
relationship: part_of UBERON:0000059 ! large intestine
property_value: editor_note "The anatomy, pathology and medical community considers the anus to be part of the large intestine, and supports the use of 'anorectum' to include rectum, anal canal and anus. Although a few resources seem to only include the distal part of the rectum in 'anorectum', this UBERON grouping term is meant to refer more broadly to the whole of rectum." xsd:string
property_value: has_relational_adjective "anorectal" xsd:string
property_value: present_in_taxon "Homo sapiens" xsd:string
created_by: http://orcid.org/0000-0002-2825-0621
