### ISSUE TITLE
UBERON:0002030 nipple should be part_of UBERON:0001911 mammary gland

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1873]
**Uberon term**
UBERON:0002030 nipple

**Suggested revision and reasons**
UBERON:0002030 nipple isn't linked to mammary gland (other than indirectly via 
develops_from some mammary ridge
and
mammary duct channels_into some nipple).
Please consider adding 
nipple part_of mammary gland
because in species that have nipples, these are always part of a mammary gland. 

Thanks,
Paola

Update: on further analysis, I see that 'nipple' has 2 general class axioms:
nipple and ('part of' some 'Mus musculus') SubClassOf 'part of' some 'mammary gland'
nipple and ('part of' some 'Homo sapiens') SubClassOf 'part of' some breast
I still think that 'nipple' should always be part of 'mammary gland', but the existence of the axioms above suggests that there may have been previous discussion on this, so I'll leave things as they are and close.

**Comment by RDruzinsky** [comment]
I would argue that mammary glands and nipples (or teats) are 'part of' the
breast. Nipples or teats are not parts of the mammary glands.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by paolaroncaglia** [comment]
@RDruzinsky @cmungall 
Thanks for your feedback,

> > I would argue that mammary glands and nipples (or teats) are 'part of' the
> > breast.
> 
> remember uberon is multi-species

Exactly. Only the '_thoracic_ mammary gland' is part_of 'breast'. Nipples in mammals are generally located on the whole trunk, and cows' teats would be part_of 'abdominal mammary gland'...

> > Nipples or teats are not parts of the mammary glands.

But 'areola' and 'mammary fat pad' are - here's the current view:

![Screenshot 2022-03-25 at 10 13 13](https://user-images.githubusercontent.com/4982516/160091249-34b02d7c-0c44-432e-a564-868ea7e4f27b.png)

If areolas and fat tissue are considered part_of mammary glands, rather than adjacent to or similar, then nipples and teats should be too. I suspect that the difference in the existing GCIs  
nipple and ('part of' some 'Mus musculus') SubClassOf 'part of' some 'mammary gland'
nipple and ('part of' some 'Homo sapiens') SubClassOf 'part of' some breast
derives from the observation that mice don't have breasts while humans do. But we should find a solution that works for all mammals, and

> I am reopening until we address this. As @paola-scibite points out we have a taxon GCI saying it's part of the gland in mouse, but that is weirdly specific and it looks like was put there to be consistent with MA (cc @tfhayamizu) - taxon GCIs should be reserved for true taxon-specificity
> 
> we want a consistent story about the relationship of nipple to gland across all mammalian ontologies
> 
> one approach here would be to define a new mereological sum something like mammary unit, consisting of the gland and 'adnexa' - nipples, surrounding tissue. I am not sure if this takes the ontology into strange ontological abstraction territory though

As I said, currently 'mammary gland' does consist of gland + some adnexa. So we either strip the gland of all current adnexa and add a new term for mammary unit, or we leave things as are and make nipple part of mammary gland.
Other gland terms in Uberon have parts that are not strictly glandular ducts, e.g. capsule of liver and liver blood vessel are part of liver.

**Comment by paolaroncaglia** [comment]
This ticket was opened by me while working on SciBite stuff, i.e. I noticed this issue by chance; it isn't strictly required for any of the EBI projects I contribute to. However, [Chris thinks that Uberon should address this](https://github.com/obophenotype/uberon/issues/1873#issuecomment-1077811859). So I'll leave the ticket open, I'll remove my assignment, but I won't assign others - I'll add to the agenda for a future Uberon call. Thanks.

**Comment by shawntanzk** [comment]
assigning myself as I'm trying to not let tickets go unassigned. happy to make the changes once it is discussed and there's a clear actionable item here.

**Comment by cmungall** [comment]
I think the most practical thing to do here is to treat mammary gland as including adnexa. As Paola says we already do this in part. Let's just be consistent.

**Comment by shawntanzk** [comment]
probably my ignorance on non-brain related biology here, but I'm still not 100% sure what the conclusion means in terms of something actionable - does this mean that I should make nipple part_of mammary gland?

**Comment by paola-scibite** [comment]
@shawntanzk 

> probably my ignorance on non-brain related biology here, but I'm still not 100% sure what the conclusion means in terms of something actionable - does this mean that I should make nipple part_of mammary gland?

Based on Chris' comment above, I believe so. Please see my rationale summarised at the bottom of this previous comment of mine: https://github.com/obophenotype/uberon/issues/1873#issuecomment-1078820035
I'd also add a 'see also' AP pointing to this ticket please. Thanks!

**Comment by bvarner-ebi** [comment]
> Nipples or teats are not parts of the mammary glands.

From a clinical perspective, I agree with this statement and do not consider a nipple to be part of the gland. One may also consider supernumerary nipples that develop without (polythelia) or with (polymastia) accessory glands. A nipple does not have to exist as part of a mammary gland.

On the broader discussion...

The [nipple](http://purl.obolibrary.org/obo/UBERON_0002030) is a "projection of skin containing the outlets for 15-20 lactiferous ducts arranged cylindrically around the tip."  
I don't know if this is always true in normal anatomy for all mammals, but the definition does not take into account supernumerary nipples as noted above.
I'm also not convinced that it makes sense to classify the skin containing the ducts to be part of the gland itself. E.g., would 'mouth mucosa' surrounding the parotid duct be classified as part of the parotid gland?

From PMID: [35409243](https://pubmed.ncbi.nlm.nih.gov/35409243):
"Between the 12th and 16th weeks of gestation, the nipple and areola form in the epidermis and **overlie** the developing glands with the differentiation of the mesenchymal cells into fibroblasts, smooth muscle cells, capillary endothelial cells, and adipocytes." 

From [PMID:15369447:](https://erc.bioscientifica.com/view/journals/erc/11/3/0110437.xml)
"In the epidermis **overlying** the developing gland, the nipple begins to form."

"Overlie", "overlying" suggests that these are separate structures.

**Comment by shawntanzk** [comment]
From https://github.com/obophenotype/uberon/issues/2560 @raymond91125

Uberon term
nipple UBERON:0002030
mammary gland UBERON:0001911

Suggested revision and reasons
nipple part_of mammary gland
This relationship is implied in Wikipedia references, and https://biologydictionary.net/mammary-glands/, even in male.
https://github.com/geneontology/go-ontology/issues/22941

**Comment by shawntanzk** [comment]
PS I have not made the change as @bvarner-ebi has brought up some points that I think need to addressed. Might need to wait till next uberon meeting to discuss this properly and make a final call on it?

**Comment by raymond91125** [comment]
Ah, did not see the thread. Thanks. @shawntanzk

**Comment by cmungall** [comment]
This is now blocking other issues. I think we need some decision on this. maybe there can never be complete consensus as lines are drawn differently for different purposes by different communities.

The most important thing is that we are clear and consistent about *some* lines. We can always make new bundles or subdivide things further it people need that (see my comment earlier).

I suggest that when proposing that X is part of Y or not part of Y, this is justified by a clear proposed definition of X and Y that makes it clear:

- what the extent is along different axes (e.g. for nipple, skin boundaries but especially how deep it goes)
- what structures does it completely contain, which does it overlap, and what does it interlace with
- what is the tissue composition (epidermis? epidermis + dermis? epidermis + dermis + subcutaneous tissue? + glands?)

Avoid vague terms like "projection of" unless this is itself defined. Is a projection of something also a part of it? Or continuous with it? 

Line drawing figures showing boundaries can be very helpful here

**Comment by shawntanzk** [comment]
Uberon call: we make nipple part of mammary generally (currently a GCI) 
We add a note that there is a GCI for human that points out GCI in homo sapien

**Comment by RDruzinsky** [comment]
I have not forgotten about all of the other mammals. I am trying to be
precise. I would like to reserve the term 'mammary gland' to mean the
glandular tissue or parenchyma and the ducts, and use a different term for
the whole organ - breast, in humans and perhaps other mammals with a single
thoracic pair, or mamma (pl. mammae) is a term that can be used for any
milk producing organ.

Granted, many folks use 'mammary gland' to mean the whole organ. I don't
agree but maybe I have to live with that.
