### ISSUE TITLE
Check that WikipediaVersioned links resolve

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#1874]
Stemming from https://github.com/obophenotype/cell-ontology/pull/1078
Note for self: double-check that WikipediaVersioned links resolve for the Uberon terms I created (e.g. 'left colic vein'). Check in OLS; Protege may be a different issue.

**Comment by shawntanzk** [comment]
Is this a protege problem then? should we write a ticket for Protege side to fix? If so does protege support the short links from the GO yaml?
I've added this to CL call.

**Comment by shawntanzk** [comment]
@hkir-dev 
There should be a place in protege that has short name to link (eg Wikipedia to http://en.wikipedia.org/wiki/)
We should add WikipediaVersioned as: "https://en.wikipedia.org/w/index.php?title="

@shawntanzk to think if there are any other expansions that should be inserted

**Comment by shawntanzk** [comment]
Fixed with https://github.com/protegeproject/protege/pull/1049 - will be implemented in the next protege release
