### ISSUE TITLE
trochlear sulcus of humerus

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1877]
**Uberon term**
trochlear groove of humerus

**Synonym to be added**
trochlear sulcus of humerus

**broad/exact/narrow/related ?**
exact

**Comment by megbalk** [comment]
@nicolevasilevsky I'll make a new branch and do this

**Comment by megbalk** [comment]
this term is missing from the edit file

**Comment by balhoff** [comment]
@megbalk it could be in the Phenoscape ext: https://github.com/obophenotype/uberon-phenoscape-ext/blob/master/phenoscape-ext.owl

**Comment by balhoff** [comment]
(feel free to submit pull requests there until the repos get merged!)

**Comment by megbalk** [comment]
@balhoff does that not get pulled in with uberon? It's in the URL version (so last release) but not the edit version. Should I suggest a synonym at the phenoscape ext?

**Comment by megbalk** [comment]
ok!

**Comment by nicolevasilevsky** [comment]
I see this in the uberon-edit file, I think this can be closed.
