### ISSUE TITLE
trochlear ridge of humerus

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1878]
**Preferred term label:**
trochlear ridge of humerus

**Synonyms**

**Definition (free text, please give PubMed ID)**
The ridge in the middle of a trochlea of a humerus.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
trochlea of humerus

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
I'll make a new branch and do this

**Comment by paolaroncaglia** [comment]
@megbalk added this as UBERON:7500061 on Jun 2, so I'll close.
@megbalk , please close tickets after you've addressed them, otherwise they'll continue to live in GitHub for a year and a half before being automatically removed ;-)
Happy Thanksgiving!
Paola
