### ISSUE TITLE
tibial tuberosity

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1879]
**Preferred term label:**
tibial tuberosity

**Synonyms**
fossa digitalis

**Definition (free text, please give PubMed ID)**
The tibial tuberosity is on the anterior side of a tibia and is where a patella ligament attaches.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
epiphysis of tibia

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
I will create a branch and do this.

**Comment by paolaroncaglia** [comment]
This is now UBERON:7500062
