### ISSUE TITLE
trochlea of talus and its parts

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1880]
**Preferred term label:**
1. trochlea of talus
2. trochlear groove of talus
3. condyle of talus
4. medial condyle of talus
5. lateral condyle of talus
6. ridge of medial condyle of talus
7. ridge of lateral condyle of talus

**Synonyms**
1. trochlea tali; trochlea for tibia; trochlea of astragalus
2. trochlear groove of astragalus
3. condyle of astragalus
4. medial condyle of astragalus
5. lateral condyle of astragalus
6. ridge of medial condyle of astragalus
7. ridge of lateral condyle of astragalus

**Definition (free text, please give PubMed ID)**
1. The articular surface of a talus that interacts with a tibia. It has a deep depression that forms the trochlear groove and is bounded by the medial and lateral condyles.
2. The furrow between the lateral and medial condyles of the trochlea of talus. 
3. An articular prominence of a talus that engages with the tibia.
4. The medial condyle of talus is an articular prominence of bone on medial side of the trochlea of a talus, which engages with the tibia.
5. The lateral condyle of talus is an articular prominence of bone on the lateral side of the trochlea of a talus, which engages with the tibia.
6. The crest of the medial condyle of a talus.
7. The crest of the lateral condyle of a talus.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
1. talus
2. trochlea of talus
3. trochlea of talus
4. condyle of talus
5. condyle of talus
6. medial condyle of talus
7. lateral condyle of talus

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
I will create a new branch and add these.

**Comment by paolaroncaglia** [comment]
@megbalk 
I'll leave this ticket to you please, to double-check if all terms have been added. If yes, please close. Thanks.

**Comment by megbalk** [comment]
These have been merged.
