### ISSUE TITLE
sulcus tali

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1881]
**Preferred term label:**
sulcus tali

**Synonyms**
sulcus for flexor hallucis longus tendon

**Definition (free text, please give PubMed ID)**
A depression that runs between the two facets of a talus that interact with a calcaneum.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
talus

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
adding this term on the fovt-talus branch

**Comment by paolaroncaglia** [comment]
Added as UBERON:7500070
