### ISSUE TITLE
astragalus head

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1882]
**Uberon term**
astragalus head

**Synonym to be added**
talus head

**broad/exact/narrow/related ?**
exact

**Comment by megbalk** [comment]
I will do this on the fovt-talus branch

**Comment by megbalk** [comment]
this term is missing from the edit file

**Comment by megbalk** [comment]
@balhoff is this the same issue where this resides in the other ontology? How do you figure that out for future?

**Comment by balhoff** [comment]
I think you just need to see if it's in uberon_edit.obo, or else see if it's phenoscape-ext. If you open phenoscape-ext in Protege, the terms defined there will be bold.

**Comment by nicolevasilevsky** [comment]
I see this in the uberon-edit file, I think this can be closed.
