### ISSUE TITLE
rostrum

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1883]
**Preferred term label:**
rostrum

**Synonyms**
related synonyms: snout, muzzle, beak

**Definition (free text, please give PubMed ID)**
Rostrum is a common term used to describe forward protrusions from an animal's face. In vertebrates, this includes the part of the cranium (skull) in front of the zygomatic arches that also holds the teeth, palate, and nasal cavity. In invertebrates it is the forward extension of the carapace and/or the piercing mouthparts.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
organism subdivision
part of some midface
part of some cranium

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
I will create a new branch and do this

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,
May I please suggest to add a taxon constraint to indicate that 'rostrum' is never found in Homo sapiens.
I think it could be safely broadened to 'never in Euarchontoglires' too, but haven't checked fully.
Useful for producing a human-focused version of Uberon.
I'd also suggest adding an exact synonym "animal rostrum".
Thanks!
Paola

**Comment by megbalk** [comment]
Hi @paolaroncaglia, yes! How do I add a taxon constraint? It'd be helpful for other things I'm doing as well.

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,

> How do I add a taxon constraint? It'd be helpful for other things I'm doing as well.

Sure. You can add a "never in taxon" constraint as an annotation property. In Protege, highlight the newly created class 'rostrum', then click on the green "+" next to "Annotations", and from the list select "never in taxon" (there are two, select the one in bold). Then, in the text box ("Literal" tab), fill in 'Homo sapiens'. I'll leave it to you please to check if 'rostrum' can be further restricted to 'never in Euarchontoglires'.
To see examples of how and where 'never in taxon' is used in Uberon, you may go to the "Annotation property hierarchy" tab in Protege, select 'never in taxon' (the one in bold), and then click on the tab "Annotation Property Usage" in the window where one usually looks at a term's details. E.g., 'cervical rib' is restricted to 'Homo sapiens'.   
Summary documentation on taxon constraints is [here](https://obofoundry.github.io/obo-patterns.github.io/key-topics/taxon_constraints/).
Any question or comment please feel free to add to the [agenda for CL/Uberon editors meeting](https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit).

Thanks and happy editing!
Paola

**Comment by megbalk** [comment]
Thank you!

**Comment by megbalk** [comment]
@paolaroncaglia do I use the annotation "never in taxon" or "never_in_taxon"? Or does it not matter?

**Comment by balhoff** [comment]
You want the one with IRI `http://purl.obolibrary.org/obo/RO_0002161`. I see in uberon_edit there is something with IRI `http://www.geneontology.org/formats/oboInOwl#never_in_taxon`—this is just a mistake and should be replaced.

By the way I have the impression that "rostrum" is used with monkeys at least.

**Comment by balhoff** [comment]
@megbalk I got rid of the extra property: #1932 It was being created via a typo combined with an unfortunate feature of the OBO parser.

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,
Assigning to you. Feel free to close if you don't need the term any longer. Thanks,
Paola

**Comment by megbalk** [comment]
It's on fovt-skull but not yet merged. working on it now
