### ISSUE TITLE
antorbital notch

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1886]
**Preferred term label:**
antorbital notch

**Synonyms**

**Definition (free text, please give PubMed ID)**
The antorbital notch is a prominence of bone located anteriolaterally of the antorbital fenestra.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
'bone fossa'
'part of' some skull

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
I will create a branch and add this term. I suspect this term also needs taxon constraints.

**Comment by megbalk** [comment]
@paolaroncaglia does this need a taxon constraint too?

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,

> @paolaroncaglia does this need a taxon constraint too?

Good point; when creating new terms, it's always useful to consider that. You don't provide references or usage examples, and I'm not sure what species have an 'antorbital notch'. However, it may be that the _parent_ terms you suggest already have the appropriate taxon constraints. In this case, the new term would inherit the taxon rule "only in Vertebrata" via 'bone fossa' and its ancestor(s), plus it would inherit the broader 'only in Craniata' via 'skull' (you can see all this in Protege). If 'antorbital notch' occurs in some vertebrates but not others, it'd be useful if you could add more stringent constraints. 
Also, in general, please consider adding definition database cross references  (papers, books, reliable internet resources...).
Thanks!
Paola

**Comment by paolaroncaglia** [comment]
@megbalk 
Just a note to say that details of how to formalize taxon constraints are currently under discussion (there's a whole GitBub project board [here](https://github.com/orgs/obophenotype/projects/2#card-58876023)). In particular, 'only in taxon' is being considered for obsoletion, possibly in favor of 'in taxon', but I wasn't involved in the most recent discussion. So perhaps best to make a note in your tickets of what taxonomic groups the new term a) would never apply to, and/or b) is (only?) found in, and come back to apply those rules when a resolution is reached? I'll make a note in the agenda for the next CL/Uberon editors' meeting.

**Comment by megbalk** [comment]
Thank you!

**Comment by megbalk** [comment]
See "[better doc](https://obofoundry.github.io/obo-patterns.github.io/key-topics/taxon_constraints/)"

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,
Hope all's well. Assigning to you please. As far as I can see, the term hasn't been created yet. Thanks.
Paola
