### ISSUE TITLE
preorbital process

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1888]
**Preferred term label:**
preorbital process

**Synonyms**

**Definition (free text, please give PubMed ID)**
The preorbital process is a projection of bone close to the nasal bones and anterior to the orbital bone.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
'part of' some cranium
'anatomical projection'

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
I will add this to fovt-skull

**Comment by megbalk** [comment]
@paolaroncaglia does this need a taxon constraint too?

**Comment by paolaroncaglia** [comment]
@megbalk 

> @paolaroncaglia does this need a taxon constraint too?

Please see https://github.com/obophenotype/uberon/issues/1886#issuecomment-853793717. This new term would only inherit a taxon constraint for Chordata, so yes possibly it could be restricted further (I see it's in a subset called "vertebrate_core").

**Comment by megbalk** [comment]
Thank you!

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,
Is this term still needed? If it is (I don't see it in Uberon), please consider if/how it should be linked to the existing term UBERON:3000467 'preorbital process of the pars facialis of the maxilla' (sourced from amphibian_anatomy). 
If the term is no longer needed, or if you've added it already under a different label, please close this ticket. 
It's always helpful to link pull requests and note new term IDs :-) Thank you and have a nice day!

**Comment by megbalk** [comment]
@paolaroncaglia I did not see that term last time. I'll look into it.

**Comment by megbalk** [comment]
I have emailed marine mammal anatomist to see if this is the same structure.

**Comment by megbalk** [comment]
Seems to be the same structure. I'm closing the issue.
