### ISSUE TITLE
patellar surface

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1894]
**Preferred term label:**
trochlea of femur

**Synonyms**
patellar surface of femur

**Definition (free text, please give PubMed ID)**
A trochlea on the distal end of a femur that interacts with the patella.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
'part of' some 'distal epiphysis of femur'

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
i will create a branch and create this term

**Comment by paolaroncaglia** [comment]
This was added by @megbalk as UBERON:7500077 trochlea of femur
