### ISSUE TITLE
radial styloid process

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1898]
**Preferred term label:**
radial styloid process

**Synonyms**
has_exact_synonym: radial condyle
has_exact_synonym: radial styloid notch

**Definition (free text, please give PubMed ID)**
A condyle on the distal end and lateral side of a radius.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
'condyle' and ('part of' some 'distal epiphysis of radius')

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
I will create a new branch and create this.

**Comment by paolaroncaglia** [comment]
@megbalk added this as UBERON:7500078
