### ISSUE TITLE
ulnar notch of radius

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1899]
**Preferred term label:**
ulnar notch of radius

**Synonyms**

**Definition (free text, please give PubMed ID)**
A condyle on the distal end and medial side of a radius that interacts with the ulna.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
'mesoderm-derived structure'
'part of' some 'distal epiphysis of radius'

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
I will add this to fovt-radius

**Comment by paolaroncaglia** [comment]
@megbalk added this as UBERON:7500079
