### ISSUE TITLE
articular surface for carpals

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1900]
**Preferred term label:**
articular surface for carpals

**Synonyms**
distal articular surface of radius

**Definition (free text, please give PubMed ID)**
The articular surface on the distal end of a radius that interacts with carpals.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
'articular surface'
'part of' some 'distal epiphysis of radius'

**Your nano-attribution (ORCID)**

**Comment by megbalk** [comment]
I will add this to fovt-radius

**Comment by megbalk** [comment]
Can't find 'articular surface' or 'surface of bone'

**Comment by megbalk** [comment]
@cmungall @nicolevasilevsky why isn't "articular surface" in uberon-edit, but is in the latest release of uberon?

**Comment by nicolevasilevsky** [comment]
I see it @megbalk 
![image](https://user-images.githubusercontent.com/6722114/128092461-2a9b2de6-3cf9-495c-b352-54ca92d7f99f.png)

**Comment by nicolevasilevsky** [comment]
I see surface of bone too

**Comment by megbalk** [comment]
I don't, can you help?
<img width="891" alt="Screen Shot 2021-08-03 at 3 43 22 PM" src="https://user-images.githubusercontent.com/6617332/128101355-8e0cdb4c-c79e-4357-9c2a-58d0e82b70e4.png">

**Comment by matentzn** [comment]
@megbalk wrong file: 
![image](https://user-images.githubusercontent.com/7070631/128178336-c80e2c0b-81be-4c8f-869f-37f229b561a4.png)


should be using `src/ontology/uberon-edit.obo`

**Comment by matentzn** [comment]
In fact, taht file shouldnt even exist anymore.. Maybe you are in an old version of the repo.

**Comment by nicolevasilevsky** [comment]
@megbalk let me know if you need any help with this :)

**Comment by megbalk** [comment]
This was redone on fovt-radius2, PR #2027. I'll close this now.
