### ISSUE TITLE
proximal articular surface of radius

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1901]
**Uberon term**
humeral facet on radius

**Synonym to be added**
proximal articular surface of radius

**broad/exact/narrow/related ?**
exact

**Comment by megbalk** [comment]
I will add this to fovt-radius

**Comment by megbalk** [comment]
I suspect this is in phenotype-ext

**Comment by nicolevasilevsky** [comment]
I see this synonym in Uberon, I think this ticket can be closed.
