### ISSUE TITLE
NTR: levatores costarum

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#1904]
**Preferred term label:**
levatores costarum

**Synonyms**
levatores costarum muscle
levatores costarum muscles
musculi levatores costarum [latin term]

**Definition (free text, please give PubMed ID)**
Adapt from Wikipedia: "The Levatores costarum (/ˌlɛvəˈtɔːriːz kəˈstɛərəm/), twelve in number on either side, are small tendinous and fleshy bundles, which arise from the ends of the transverse processes of the seventh cervical and upper eleven thoracic vertebrae. They pass obliquely downward and laterally, like the fibers of the Intercostales externi, and each is inserted into the outer surface of the rib immediately below the vertebra from which it takes origin, between the tubercle and the angle (Levatores costarum breves). Each of the four lower muscles divides into two fasciculi, one of which is inserted as above described; the other passes down to the second rib below its origin (Levatores costarum longi). They have a role in forceful inspiration."
WikipediaVersioned:Levatores_costarum_muscles&oldid=876138804

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
UBERON:0002426 chest muscle

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-2825-0621

**dbxrefs**
FMA:71312

**Comment by paolaroncaglia** [comment]
@dosumis please confirm: I'll fix the "present in taxon" as per https://github.com/INCATools/ontology-development-kit/blob/b5ac0030c7523dccd57eab567fd85d6a0e807027/docs/TaxonRestriction.md. Correct? :-) Ta.
