### ISSUE TITLE
revise classification of UBERON:0001844 cochlea?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/uberon#1905]
**Uberon term**
UBERON:0001844 cochlea

**Suggested revision and reasons**
Uberon is placing all of the cochlea under the skeleton but is this correct? Would you consider the cochlear hair cells to be part of the skeleton? Similar issue for UBERON:0002371 bone marrow and skeleton (bone marrow is part of bone element).

_From Phenotype editors call 03 June 2021_

**Comment by dosumis** [comment]
The non boney bit is the 'organ of Corti' (AKA 'spiral organ of cochlea').  Is it not sufficient that this is 'located in' the cochlea rather than part of it?

**Comment by dosumis** [comment]
I think it is fine to leave this as-is.  The non-bone component is not part of the cochlea.  See comment above - and here: https://github.com/mgijax/mammalian-phenotype-ontology/issues/3458#issuecomment-922991703

Please re-open if you strongly object.  The only other fix I can of is to make a separate term for the bony component of the cochlea (do we have one already?).  This would allow cochlea to come out from under skeletal system, but we would need to decide where else to put it.

**Comment by dosumis** [comment]
https://github.com/obophenotype/uberon/issues/1513
