### ISSUE TITLE
NTR: muscularis mucosae of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1927]
**Preferred term label:**
muscularis mucosae of colon

**Synonyms**
muscularis mucosa of colon

**Definition (free text, please give PubMed ID)**
Muscularis mucosae that is part of colon.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
muscularis mucosa http://purl.obolibrary.org/obo/UBERON_0006676
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by ANiknejad** [comment]
I am sorry to put the question here, but why creating such term, instead of using composite annotation with UBERON:0006676 muscularis mucosa AND UBERON:0001155 colon ? I thought, it was in Uberon goals to avoid having to much terms. Thank you in advance for clarification.

Anne

**Comment by paolaroncaglia** [comment]
Hi @ANiknejad ,

> I am sorry to put the question here, but why creating such term, instead of using composite annotation with UBERON:0006676 muscularis mucosa AND UBERON:0001155 colon ? I thought, it was in Uberon goals to avoid having to much terms. Thank you in advance for clarification.
> 
> Anne

Sure. Yours is a very valid question, and I confirm that the compositional approach you refer to would be the preferred choice. However, the application that this term (and many others, for both anatomy and cell types) have been requested for, i.e. the anatomograms for the Single Cell Expression Atlas, or SCA, can't currently work with post-composed terms for technical reasons, so we need to pre-compose them explicitly. We discussed the matter extensively at Uberon and CL editors' meetings some time ago, and agreed to address these requests so the anatomograms can be released. If you're interested, the project is described [here](https://www.ebi.ac.uk/about/news/service-news/anatomograms-new-feature-single-cell-expression-atlas), and you may ask @sfexova or @ngeorgeebi for more details.   

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
Uberon already has UBERON:0007178 'muscularis mucosae of colon', with "muscularis mucosa of colon" as exact synonym, see OLS entry [here](http://purl.obolibrary.org/obo/UBERON_0007178). It is part of some colonic mucosa, which is part of colon, so it should work well for the anatomograms. I'll close this ticket, but feel free to re-open it (or comment) if you have any concern. Thanks.
Paola
