### ISSUE TITLE
NTR: smooth muscle circular layer of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1928]
**Preferred term label:**
smooth muscle circular layer of colon

**Synonyms**

**Definition (free text, please give PubMed ID)**
A circular muscle layer of muscular coat that is part of a colon smooth muscle.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
intestine smooth muscle http://purl.obolibrary.org/obo/UBERON_0004221
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410060 colon smooth muscle circular layer
