### ISSUE TITLE
NTR: smooth muscle longitudinal layer of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1929]
**Preferred term label:**
smooth muscle longitudinal layer of colon

**Synonyms**

**Definition (free text, please give PubMed ID)**
A longitudinal muscle layer of muscular coat that is part of a colon smooth muscle.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
colon http://purl.obolibrary.org/obo/UBERON_0001155
intestine smooth muscle http://purl.obolibrary.org/obo/UBERON_0004221

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
I created UBERON:8410061 colon smooth muscle longitudinal layer.
However, it seems that UBERON:0012419 'taenia coli' ([here](http://purl.obolibrary.org/obo/UBERON_0012419)) should be a subclass of the new term above, if not the same thing altogether. 'taenia coli' has clear textual links to colon and to longitudinal muscle layer, but no formal relationship. Are there other known instances of "longitudinal ribbons of smooth muscle" in the colon? 
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@sfexova 
Apologies, I can't remember if you mentioned something about this ticket on our call earlier? The sound wasn't very good so I might have missed it. Thanks.

**Comment by paolaroncaglia** [comment]
I added the requested Uberon term already, so I'll close this ticket.
There may still be room for improvement around possible links between 
UBERON:8410061 colon smooth muscle longitudinal layer.
and 
UBERON:0012419 'taenia coli'
but there was no follow-up, so I'll leave as is.
