### ISSUE TITLE
NTR: capillary of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1930]
**Preferred term label:**
capillary of colon

**Synonyms**
blood vessel capillary of colon

**Definition (free text, please give PubMed ID)**
Capillary that is part of a colon.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
capillary http://purl.obolibrary.org/obo/UBERON_0001982
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410057 capillary of colon
