### ISSUE TITLE
NTR: capillary of anorectum

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1931]
**Preferred term label:**
capillary of anorectum

**Synonyms**
blood vessel capillary of anorectum

**Definition (free text, please give PubMed ID)**
Capillary that is part of anorectum.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
capillary http://purl.obolibrary.org/obo/UBERON_0001982
anorectum UBERON:8410050

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
I added UBERON:8410056 capillary of anorectum. It will be available at the next Uberon release.
Thanks,
Paola
