### ISSUE TITLE
New grouping terms for large/small arteries and veins

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/uberon#1933]
**New Uberon terms/groupings**
These are the suggested UBERON terms:
Large arteries
medium-sized arteries
small arteries
peripheral arteries
lower extremity peripheral artery
middle cerebral artery
(tunica) media of large arteries
(tunica) media of medium-sized arteries
(tunica) media of small arteries
cranial artery (cranial blood vasculature as a parent)
cranial vein

**Suggested revision and reasons**

I am suggesting these terms and revision of groupings of arteries and veins, but I do this full knowing that this is complicated.
Issue is that "classification of ischemic strokes, large-artery atherosclerosis and small- vessel occlusion are major subtypes. However, the meaning of “large artery” and “small vessel” is unclear."  (attaching paper for the quote.). Simply, there are a number of terms in HPO that do not have UBERON terms to reference (see above).    https://github.com/obophenotype/human-phenotype-ontology/issues/4844 
https://github.com/obophenotype/human-phenotype-ontology/issues/6877

[arterysize.pdf](https://github.com/obophenotype/uberon/files/6711052/arterysize.pdf)

Are there any domain experts that could help parse this problem?
Thanks

**Comment by LCCarmody** [comment]
@matentzn @cmungall

**Comment by emquardokus** [comment]
@dosumis Can Griffin Weber's work from HuBMAP Vasculature help at all here?  We have vasculature experts we could leverage.

**Comment by dosumis** [comment]
@emquardokus  - good idea. Is Griffin on GitHub?

**Comment by emquardokus** [comment]
@dosumis Link to this open uberon issue: Vasculature template + compiled OWL #1780
Griffin Weber Github: @GriffinWeber

**Comment by cmungall** [comment]
What is the priority of this request?

**Comment by matentzn** [comment]
From the HPO perspective `medium` - we have ditched our efforts for building phenotypes using these groupings for now.

**Comment by dosumis** [comment]
@GriffinWeber - Is this classification practical based on your experience - or are there two many edge cases where classification would be hard?

**Comment by paolaroncaglia** [comment]
Looks like this shouldn't be closed, so I added it to the agenda for the next editors' meeting. Or @dosumis please comment if you've had any follow-up discussion with @GriffinWeber offline. Thanks.
