### ISSUE TITLE
eyestalk

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1938]
I am currently in the process of annotating some new crustaceans RNA-seq libraries for bgee.org, see for examples these recent papers:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5796769/

https://advances.sciencemag.org/content/7/26/eabe8290

and I am looking for some crustacean or even arthropod or decapod structures that are obviously missing, such as 'eyestalk' , or eye-bearing antenna

It exists a close-related cephalopod term

[Term]
id: CEPH:0000241
name: stalked eye
is_a: UBERON:0000970 ! eye

but so far, and AFAICS, none crustacean equivalent term to describe the eye himself, apart from UBERON:0000018 ! compound eye, or the stalk bearing the eye compound

https://www.thefreedictionary.com/eyestalk

**Comment by matentzn** [comment]
Would you be able to add the terms you need yourself? I don't know how much you have been trained in adding terms to Uberon - but if we set you up to deal with your own term additions, and reduce other peoples involvement to reviewing pull requests, you can drastically increase the speed at which you get new terms :)

**Comment by paolaroncaglia** [comment]
Hi @ANiknejad , is this request still current? Also, please see Nico's comment above. Thank you, and best wishes!

**Comment by ANiknejad** [comment]
Hi Paola, yes, the request is still current, and no, I am not trained to create a new class myself.
I am looking for a class describing the so-called 'crustacean eyestalk' which has an important role in hormonal regulation

https://www.sciencedirect.com/science/article/pii/S0016648018300856?via%3Dihub

**Comment by paolaroncaglia** [comment]
Uberon editors please: any volunteer to add an invertebrate-related term? See @ANiknejad 's request above. Thanks!
