### ISSUE TITLE
NTR: myenteric nerve plexus of small intestine

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1945]
**Preferred term label:**
myenteric nerve plexus of small intestine

**Synonyms**

**Definition (free text, please give PubMed ID)**
Myenteric nerve plexus that is part of the small intestine.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
small intestine http://purl.obolibrary.org/obo/UBERON_0002108
myenteric nerve plexus http://purl.obolibrary.org/obo/UBERON_0002439

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410063
name: myenteric nerve plexus of small intestine
