### ISSUE TITLE
NTR: submucous nerve plexus of small intestine

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#1946]
**Preferred term label:**
submucous nerve plexus of small intestine

**Synonyms**

**Definition (free text, please give PubMed ID)**
Submucous nerve plexus that is located in the small intestine.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
small intestine http://purl.obolibrary.org/obo/UBERON_0002108
submucous nerve plexus http://purl.obolibrary.org/obo/UBERON_0005304

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
@sfexova 
UBERON:8410064
name: submucous nerve plexus of small intestine
