### ISSUE TITLE
Make sure no dangling entities

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1963]
After #1798  is merged, we need to fix some of the dangling issues.

**Comment by matentzn** [comment]
- [ ] CL dangling ones #2024 
- [ ] GO danglines ones #1992 
- [ ] BFO ones coming from RO?

**Comment by paolaroncaglia** [comment]
Hi @matentzn ,
(This ticket is assigned to you so I'm taking the liberty to ask :-) )
SciBite asked about the dangling classes in #2151 . It's one of the tasks you mentioned earlier in this ticket. Wondering if we could provide an update now that some of the bottlenecks have been addressed? I'm not sure if you have bandwidth for this atm, so I'll add to the technical board, in the Todo column - feel free to remove if not appropriate. Thanks!

**Comment by shawntanzk** [comment]
To do:

- [ ] create imports for floating terms and import them in 
- [ ] for certain terms (eg FBbt:01000119 term in uberon) -> request new term to be in uberon
- [ ] Make calls in the logic of the above two for all top level classes that shouldn't be there

**Comment by anitacaron** [comment]
This will be fixed as base migration.

**Comment by shawntanzk** [comment]
Closing this as its not very useful a ticket given we want to move to base migration
