### ISSUE TITLE
Ensure circular references (part-of) check re-instated

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1968]
see #1967 

The quality checking is currently very limited compared to what it was. Need to re-instate.
@cmungall which of the checks was responsible for checking for this?

**Comment by cmungall** [comment]
originally this was a simple graph cycle check in prolog. This check should now be done with relation-graph

Two formal ways to do this:

 - part-of should be declared locally reflexive. Then a cycle will be caught by robot as it there will be an equiv-btwn-NCs entailment
 - declare part-of antisymmetric-- though this may only work on instance level?

unfortunately reflexivity is gnarly, see RO docs

For safety I would do two checks

 - run RG on uberon (perhaps with only relations in obo-basic) and sparql for loops
 - local reflexivity + standard EC checking

Note we want to do this for all ontologies that have a basic artefact. See 6.1.1 in https://owlcollab.github.io/oboformat/doc/obo-syntax.html

**Comment by matentzn** [comment]
Ok, this is all a bit too much for me at the moment, but this way I found your Prolog checks seeking to reinstate these for now:

https://github.com/obophenotype/uberon/pull/1976

**Comment by matentzn** [comment]
I will close now because advanced cycle checking needs to be done through a grant. It works now again!
