### ISSUE TITLE
Review and update composite files

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1969]
We have stopped upgrading composite files until @cmungall had a chance to look them over.

See also:
- https://github.com/obophenotype/uberon/issues/1959

**Comment by matentzn** [comment]
mi-high priority, should probably not be killed.

**Comment by paolaroncaglia** [comment]
@matentzn tech board?

**Comment by matentzn** [comment]
yep

**Comment by matentzn** [comment]
Closed in favour of https://github.com/obophenotype/uberon/issues/1959
