### ISSUE TITLE
QC logs are too verbose

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1977]
Goals like

```
$(OWLSRC): $(SRC) $(COMPONENTSDIR)/disjoint_union_over.ofn $(REPORTDIR)/$(SRC)-gocheck $(REPORTDIR)/$(SRC)-iconv $(SCRIPTSDIR)/expand-dbxref-literals.pl
	echo "STRONG WARNING: issues/contributor.owl needs to be manually updated."
	owltools $(UCAT) $< $(COMPONENTSDIR)/disjoint_union_over.ofn issues/contributor.owl --merge-support-ontologies --expand-macros -o  $@.tmp &&  $(SCRIPTSDIR)/expand-dbxref-literals.pl $@.tmp
	$(ROBOT) query -i $@.tmp --update $(SPARQLDIR)/taxon_constraint_never_in_taxon.ru -o $@
```

produce a huge amount of noise, making the QC Logfile hard to use. This needs to be reduced.

**Comment by paolaroncaglia** [comment]
Hi @matentzn (and @anitacaron ), 
I think I saw a recent thread involving both of you about the same issue? Please feel free to close this if it's a duplicate (or if it's fixed). Thanks.

**Comment by matentzn** [comment]
There is no distinct ticket for this issue.. I don't expect this to be solved as a one off, just step by step as we clean up Uberon.
