### ISSUE TITLE
scapula neck synonym

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#1978]
**Uberon term**
neck of scapula

**Synonym to be added**
collum scapulae

**broad/exact/narrow/related ?**
exact

**Comment by megbalk** [comment]
I will create a new branch and do this.

**Comment by paolaroncaglia** [comment]
@megbalk 
I see that the synonym hasn't been added yet, so I'm commenting to prevent the issue from being closed, in case the synonym is indeed still wanted. Thanks.

**Comment by megbalk** [comment]
made a pull request
