### ISSUE TITLE
incorrect classification of bone surfaces under 'surface structure'

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#1980]
'surface structure': 'Anatomical structure that overlaps the outer epithelial layer and is adjacent to the space surrounding the organism.'

Is used to classify surface structures of bones:

e.g. 

![image](https://user-images.githubusercontent.com/112839/126895596-2e79d1a8-1c36-41d7-bc0a-ff11b1977d6d.png)

These should instead be under 'surface of bone'.  It may also be useful to have more grouping classes for types of surface of bone (e.g. groove).  

There is a more general issue here with whether bone substructures are defined as surfaces, anatomical spaces (see sulcus terms) or 3D parts of bone (see condyle).  Fixing this would be outside of the scope of this ticket, but might make a good mini project for patternization, if we have strong use cases.

**Comment by dosumis** [comment]
HI @megbalk - would you be happy to have a go at changing this ? Changing classifications for bone specific structure(s) to 'surface of bone' ?

**Comment by megbalk** [comment]
@dosumis I can do that. Perhaps we can add the broader issue to discuss at the UBRON meetings?

**Comment by megbalk** [comment]
I am unsure what "nuchal groove" is, but emailed people that study amphibians.

**Comment by megbalk** [comment]
ok, made a pull request. Only found a couple of terms that were bones.
