### ISSUE TITLE
Close all issues that have not seen activity in last 3 years

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1988]
From Uberon call:
- [x] Chris is doing a pass
- [x] tag all issues with `autoclosed-unfixed`
- [x] Add comment to issue: "This issue was close because its old. Please reopen if you still need this to be fixed, as we are now getting resources to deal with these."

**Comment by matentzn** [comment]
- [ ] Check wether tagging is enough to mean "active"

**Comment by gouttegd** [comment]
It seems that _any_ activity on a issue resets the `updated_at` attribute: commenting, assigning to the issue to someone (or un-assigning), tagging with a label. So we can easily “protect” old issues from auto-closing if we find some issues that we know we’d want to keep open.

**Comment by gouttegd** [comment]
Importantly, merely _mentioning_ issue _XXX_ from another issue or pull request (be it by using the `#XXX` syntax or by using the full URL of the issue) does _not_ count as an “activity” on issue _XXX_, even though the mention does appear on the page for that issue.

**Comment by matentzn** [comment]
That is perfect @gouttegd this is both as I would prefer it to be. I will chase @cmungall on slack to do his "pass". Are you in principle ready to roll with the script?

**Comment by gouttegd** [comment]
The script is nowhere near ready, in principle or in reality! :) But go ahead and have Chris do his pass. Just tick the checkbox when it's done so that I know I can run script whenever it's ready.

**Comment by matentzn** [comment]
Hahha sorry :P  Of course! No rush at all on this :)

**Comment by gouttegd** [comment]
@matentzn I am ready to unleash the Auto-Closer™ on the unsuspecting old issues anytime. The script is still rough but is usable.

**Comment by matentzn** [comment]
Haha and you made sure that the script does not close the whole internet down? :D

**Comment by matentzn** [comment]
I would probably feel quite good if we could close 10 tickets to start with - if that works, we do the rest? Its not important whether these tickets come from the middle or the end of the list - just as a test run.

**Comment by matentzn** [comment]
What date cut off did you pick?

**Comment by gouttegd** [comment]
> Haha and you made sure that the script does not close the whole internet down? :D

No need to worry. Initial testing suggests that any undesirable side-effects should be limited to the local star cluster; universe-wide collapse is highly unlikely.

> I would probably feel quite good if we could close 10 tickets to start with - if that works, we do the rest?

Fine with me.

> What date cut off did you pick?

The script defaults to 1 year, but that can be changed for every invocation. I'll use 3 years for the first batch, as decided (where "3 years" is defined as "3⨉365 days").

**Comment by matentzn** [comment]
Sounds great!

**Comment by gouttegd** [comment]
All issues not updated in the last 1095 days have been closed.

Now we can either re-use my script every time we decide to do a cleanup, or have a policy of never letting issues go stale for so long in the first place and enforce that policy using an off-the-shelf GitHub action as suggested in #2014.
