### ISSUE TITLE
Fix use of obsolete classes

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1992]
```
! grep "! obsolete" uberon-edit.obo
relationship: confers_advantage_in ENVO:00000568 ! obsolete aerial habitat
intersection_of: composed_primarily_of CL:0000124 ! obsolete glial cell (sensu Nematoda and Protostomia)
relationship: composed_primarily_of GO:0044464 ! obsolete cell part
relationship: has_component GO:0044464 {minCardinality="2"} ! obsolete cell part
relationship: capable_of_part_of GO:0035636 ! obsolete multi-organism signaling
relationship: confers_advantage_in ENVO:00000572 ! obsolete subterrestrial habitat
```

**Comment by nicolevasilevsky** [comment]
GO_0044464 has two labels, one which is obsolete cell part

**Comment by matentzn** [comment]
Huge chain:

Uberon->PATO->RO->ro_go_cc. Need help from Chris Mungall, solution to the cell part issue is:
1. Fix https://github.com/oborel/obo-relations/issues/471
2. New RO release
3. New PATO release
4. Refresh Uberon import

Tough one maybe @shawntanzk can take this on once @cmungall has commented on 1.

**Comment by shawntanzk** [comment]
happy to do all the releases :)

**Comment by matentzn** [comment]
Some more:
- [ ] http://purl.obolibrary.org/obo/GO_0002378
- [ ] http://purl.obolibrary.org/obo/GO_0005578
- [ ] http://purl.obolibrary.org/obo/GO_0005605
- [ ] http://purl.obolibrary.org/obo/GO_0008003

**Comment by matentzn** [comment]
@shawntanzk I will leave this to you - when you do the above releases, you can run:

```
! grep "! obsolete" ro.obo
```

or 

```
! grep "! obsolete" cl.obo
```

after the releases to check whether their are obsoletion violations.

**Comment by shawntanzk** [comment]
hopefully all good now after the removing the obsolete GO terms from UBERON

**Comment by matentzn** [comment]
Huh, dont we have a check against that now?

**Comment by shawntanzk** [comment]
I think this is fixed? will check up on this later and if all good will close, but pretty sure our qc doesn't allow obsolete anymore

**Comment by shawntanzk** [comment]
seems all good - will close
