### ISSUE TITLE
documentation: xrefs for defs

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/uberon#1997]
Need documentation about how to write and reference definitions. I drafted some text below

Text definitions should follow the recommendations outlined here:

All text definitions in Uberon should have a database_cross_reference (dbxref). They dbxref could be a PubMed ID, a DOI to a book, a Wikipedia link or an ORCID for the person who requested and/or added the term. Examples of the preferred formats are listed below:

- PMID:154915
- https://doi.org/10.1016/B978-0-12-409503-8.00002-0
- ISBN:978-1-62808-994-3
- http://en.wikipedia.org/wiki/B-1_cell
- http://orcid.org/0000-0001-5208-3432

**Comment by nicolevasilevsky** [comment]
From @dosumis  on Slack:

I think this needs better standardisation.  It seems we're gradually normalizing using full URLs in dbxrefs.  I understand why given how broken our curie system is, but I'd rather fix that as moving to URLs makes it hard to use IDs to build out linked data.  One obvious example is DOIs. You can use a doi to pull Biblio data from multiple sources (e.g. EuroPMC).  That's harder if some are provided as URLs.

Standard for Curies always used to be go xrefs yaml file.

**Comment by megbalk** [comment]
What about full MLA citations?

**Comment by nicolevasilevsky** [comment]
I'm not sure that I've ever seen a full MLA citation referenced in an ontology, I think the preference would be to use the DOI or PMID, if applicable.

**Comment by dosumis** [comment]
IDs are always preferable as they can be used in API calls.  It should be possible for downstream applications to reconstruct or retrieve MLA citations from the results of API calls.  I think NCBI allows this directly.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky and @dosumis tagging you as you've contributed to this ticket. Can this be closed - has the documentation been updated already - or are there action items left? Commenting to prevent closure in the latter case. Thanks.

**Comment by nicolevasilevsky** [comment]
I don't think this is done, I think the documentation still needs to be updated.

**Comment by anitacaron** [comment]
@bvarner-ebi, could you write some documentation here, please? 😄

**Comment by bvarner-ebi** [comment]
@anitacaron, can Uberon adapt the same standards as CL (https://github.com/obophenotype/cell-ontology/pull/2058) ?

**Comment by matentzn** [comment]
As a general guideline all ontologies supported by the tech team should adapt mostly the same standards
