### ISSUE TITLE
Subarachnoid space should not be part of brain

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#2006]
**Uberon term**
 
subarachnoid space
http://purl.obolibrary.org/obo/UBERON_0000315

**Bug description**

![image](https://user-images.githubusercontent.com/112839/127549261-8c612589-bd55-4714-8283-d70ceccf6c15.png)

The meninges and the various membranes and spaces that comprise it are the outer part of both the brain and spinal cord.  They therefore should be part_of the CNS, not the brain.

https://en.wikipedia.org/wiki/Meninges#Subarachnoid_space

For optimum partonomy, it might make more sense for the space(s) to be part of the meninges (AKA meningeal cluster) or meninx
![image](https://user-images.githubusercontent.com/112839/127549726-ed1d94a0-8920-41d4-af44-a40100d213bf.png)

**Comment by dosumis** [comment]
@tgbugs - any opinion on the optimal/correct partonomy here?

**Comment by tgbugs** [comment]
I wonder if there isn't a deeper issue here. Should the meninges be part of the nervous system at all? Looking at the language used in the wiki articles and e.g. https://pubmed.ncbi.nlm.nih.gov/30801905/, it seems that they probably are not?

With that in mind, given that the subarachnoid space sits between the meninges which surround more or less the entirety of the CSN and the CNS proper (?), I would say that under the current scheme the subarachnoid space would be a direct part of the CNS with no intervening parts.

If the meninges are not part of the CNS then I would suggest a set of new classes which would be equivalent to CNS + ensheathing parts, and possibly also NS + ensheathing parts. Alternately we could forgoe creating those classes and create some other relationship between meninges + subarachnoid space and the CNS (and NS and its equivalents).

Thoughts?

**Comment by RDruzinsky** [comment]
I agree, and to complicate things even more, the subarachnoid space is an
anatomical space rather than an entity, right?

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by cmungall** [comment]
> Should the meninges be part of the nervous system at all?

#1261 discusses this and also compares how it is done in other ontologies. Whatever decision is made, this will need coordinated. Note all other ontologies treat meninges as part of the nervous system

I think drawing partonomies on the slide of inclusivity is easier for maintenance, and still allows people to draw their own more restricted concepts

**Comment by cmungall** [comment]
> the subarachnoid space is an anatomical space rather than an entity,

yep but spaces can beparts of material entities so all good

**Comment by cmungall** [comment]
I agree with @dosumis's assessment

Furthermore we should have consistent patterns and regularized lattices for meningeal structures. We already implement {brain,forebrain,spinal} x {pia, dura, etc} so we should continue this for subarachnoid space

in fact if we had implemented this structure then our existing placement would be correctly detected as incoherent.

here is fma for comparison:

![image](https://user-images.githubusercontent.com/50745/127574996-8310e098-9a8a-4f9b-8f80-5f6a434ee93a.png)

**Comment by tgbugs** [comment]
> I think drawing partonomies on the slide of inclusivity is easier for maintenance, and still allows people to draw their own more restricted concepts

Agree. It is also easier to discard parts of an inclusive hierarchy than it is to pull in additional specific parts, and removing the meninges from the CNS partonomy would multiply universals if we wanted to talk about "everything inside the skull" (for example).

**Comment by cmungall** [comment]
sorry @rays22 I couldn't resist doing this one ticket. I did a mini-slurp, we still need an SOP for that

**Comment by rays22** [comment]
> sorry @rays22 I couldn't resist doing this one ticket. I did a mini-slurp, we still need an SOP for that

No problem.

**Comment by dosumis** [comment]
@rays22  - please check that this has fixed the inference problem in MP - MP:0009037 abnormal subarachnoid space development should not be under MP:0000913 abnormal brain development.  Ticket can then be closed and tracking spreadsheet updated.
