### ISSUE TITLE
bona fossa: material entity vs 2D surface vs space

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2017]
The term "fossa" as in "bone fossa" is ambiguous as to whether it represents

 1. A material entity: the "walls" or "bed" of the bone or some small but unspecified depth.
 2. Immaterial
     - 2a 2D surface
     - 2b Space/cavity

This may seem fussy, but it is important to be clear about the differences as when we ask questions like:

 - what is the volume of the X fossa
 - what is located in the X fossa
 - what muscles attach to the X fossa

We will get different answers.

 - The volume is always zero for a 2D surface, and is unspecified/not well formed for the "walls"
 - various nerves may be located in the cavity/space, but the only things located in the 2D surface would be other 2D surfaces
 - muscles cannot attach to a space. And if we are to be serious about our upper ontology classification then nothing truly attaches to an immaterial 2D structure (though we could relax the range of the RO relation such that an attachment to a 2D region is understood to be an attachment to the anatomical structure beneath the 2D region)

One approach is to create triad classes for every conceptual fossa - the cavity, the 2D structure, the "walls"

However, I think this is overkill

We have to do something as we can't use fossaes as attachment sites right now:

https://github.com/obophenotype/uberon/issues/1455#issuecomment-891240553

I do think the located in use case is a good example of why it's good to be clear about at least the cavity vs walls distinction.

My proposal would be to rename existing fossaes to "X bone fossa cavity", and then create classes as needed for the cognate muscle attachment sites.

I don't know a good clear term for these. Following the etymological root of "fossa", perhaps the "bone fossa bed"? Sounds odd.

Perhaps "region of bone underlying X fossa"? It is very ugly but I think this may a rare case where this is warranted

**Comment by cmungall** [comment]
An alternative is to have only a single class, for the space, and to have attachment/origin relations deliberately value, e.g. has-origin means that the end of the muscle is attached to X or is located in X.

**Comment by RDruzinsky** [comment]
I like your alternative, single class, solution. It seems to be similar to
the way we use the notion of a fossa in everyday life.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by matentzn** [comment]
Who could we assign this to?
