### ISSUE TITLE
Please reinstate the following axioms - if necessary

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2018]
The following axioms where for one reason or another in the owl-axiom header and head to be removed, see https://github.com/obophenotype/uberon/pull/1993/files

Feel please review and reinstate if necessary. Apply checkbox if either reinstated, or its fine to remove.

- [x] `AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#id> <http://purl.obolibrary.org/obo/RO_0002473> \"RO:0002473\"^^xsd:string)`
- [x] `AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#id> <http://purl.obolibrary.org/obo/RO_0002488> \"RO:0002488\"^^xsd:string)`
- [x] `AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#id> <http://purl.obolibrary.org/obo/RO_0002492> \"RO:0002492\"^^xsd:string)`
- [x] `AnnotationAssertion(<http://purl.obolibrary.org/obo/UBPROP_0000004> <http://purl.obolibrary.org/obo/UBERON_3010717> \"This class was sourced from an external ontology (amphibian_anatomy). Its definitions, naming conventions and relationships may need to be checked for compatibility with uberon\"^^xsd:string)`
- [x] `AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#created_by> <http://purl.obolibrary.org/obo/UBERON_3010717> \"amphibian_anatomy_curators\"^^xsd:string)`
- [x] `AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasOBONamespace> <http://purl.obolibrary.org/obo/UBERON_3010717> \"uberon/phenoscape-anatomy\"^^xsd:string)`
- [ ] `AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_3010717> \"obsolete diverticulum\"^^xsd:string)`
- [x] `AnnotationAssertion(<http://purl.obolibrary.org/obo/UBPROP_0000004> <http://purl.obolibrary.org/obo/UBERON_3010730> \"This class was sourced from an external ontology (amphibian_anatomy). Its definitions, naming conventions and relationships may need to be checked for compatibility with uberon\"^^xsd:string)`
- [x] `AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#created_by> <http://purl.obolibrary.org/obo/UBERON_3010730> \"amphibian_anatomy_curators\"^^xsd:string)`
- [x] `AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasOBONamespace> <http://purl.obolibrary.org/obo/UBERON_3010730> \"uberon/phenoscape-anatomy\"^^xsd:string)`
- [ ] `AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_3010730> \"pterygoideus\"^^xsd:string)`
- [ ] `AnnotationAssertion(<http://purl.obolibrary.org/obo/IAO_0000115> <http://purl.obolibrary.org/obo/UBERON_4300122> \"Posteriorly projecting processes allowing de facto contact between consecutive vertebrae (some soft tissues are also present) via articular facets. [PHENOSCAPE:NI]\"^^xsd:string)
- [x] `AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#created_by> <http://purl.obolibrary.org/obo/UBERON_4300122> \"WD\"^^xsd:string)`
- [ ] `AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_4300122> \"obsolete postzygapophysis\"^^xsd:string)`

**Comment by dosumis** [comment]
I think no need for this if they are all like example here: 

https://github.com/obophenotype/uberon/pull/1993/files#r681726842

Please close if that is that case.  

Thanks.

**Comment by matentzn** [comment]
@anitacaron can you double check the remaining axioms in the list above wether they have not been wrongfully lost from Uberon?

**Comment by anitacaron** [comment]
- [X] AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_3010717> \"obsolete diverticulum\"^^xsd:string)

This axiom is present in the most recent UBERON release.

- [ ] AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_3010730> \"pterygoideus\"^^xsd:string)

I didn't find the term UBERON:3010717 in the most recent release. It's present in the [2021-07-27 release ](https://github.com/obophenotype/uberon/releases/tag/v2021-07-27) and not in the next one [2021-09-29](https://github.com/obophenotype/uberon/releases/tag/v2021-09-29), I believe it got lost there.

- [ ] `AnnotationAssertion(http://purl.obolibrary.org/obo/IAO_0000115 http://purl.obolibrary.org/obo/UBERON_4300122 "Posteriorly projecting processes allowing de facto contact between consecutive vertebrae (some soft tissues are also present) via articular facets. [PHENOSCAPE:NI]"^^xsd:string)

Same case as above for the term UBERON:3010730.

- [ ]  AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_4300122> \"obsolete postzygapophysis\"^^xsd:string)

Same case as above.

**Comment by matentzn** [comment]
@anitacaron we need to reinstate all these terms.. Its a bit of a priority - I would like that done before the next Uberon release cc @shawntanzk 

Do you feel comfortable with re-instating these terms?

**Comment by matentzn** [comment]
Ideally including all the metadata they had previously..

**Comment by anitacaron** [comment]
Could you create an issue to link and document the reason for the addition of these terms, please?

**Comment by matentzn** [comment]
This issue is sufficient I think: it's about reinstating the axioms lost above, in particular the terms.. I accidentally dropped them during a cleanup of the edit file..

**Comment by matentzn** [comment]
- [ ] Can you ensure that UBERON:3010717 is present in uberon-edit.obo, not just uberon.owl?

**Comment by anitacaron** [comment]
Both are in the uberon-edit.obo

**Comment by anitacaron** [comment]
Done by PR #2277
