### ISSUE TITLE
Classes with no labels, etc.

### ISSUE THREAD

**Issue by DanBerrios** [obophenotype/uberon#2029]
**Uberon term**
  71203     
  71204
  71205     <owl:Class rdf:about="http://purl.obolibrary.org/obo/CP_0000027"/>
  71206
  71207
  71208
  71209     
  71210
  71211     <owl:Class rdf:about="http://purl.obolibrary.org/obo/CP_0000028"/>
  71212
  71213
  71214
  71215     
  71216
  71217     <owl:Class rdf:about="http://purl.obolibrary.org/obo/CP_0000035"/>
  71218
  71219
  71220
  71221     
  71222
  71223     <owl:Class rdf:about="http://purl.obolibrary.org/obo/CP_0000037"/>
  71224
  71225
  71226
  71227     
  71228
  71229     <owl:Class rdf:about="http://purl.obolibrary.org/obo/CP_0000039"/>
  71230
  71231
  71232
  71233     
  71234
  71235     <owl:Class rdf:about="http://purl.obolibrary.org/obo/CP_0000040"/>
  71236
  71237
  71238
  71239     
  71240
  71241     <owl:Class rdf:about="http://purl.obolibrary.org/obo/CP_0000043"/>

**Bug description**

These classes' IRIs don't seem to resolve.  Thus, in our uberon module import, they have no labels, parents, etc.  What is the source for these, if these are being imported into uberon?  I tried sleuthing that in Ontobee....but it's not easy. Thanks

**Comment by matentzn** [comment]
I have dealt with these recently, so @megbalk csn you assign this issue To me please?

**Comment by paolaroncaglia** [comment]
Hi @DanBerrios,
This issue is fixed now. The CP classes were being imported into Uberon from the Cell Ontology (CL), and they've now been obsoleted in CL.
Feel free to contact us again if you have any further queries. Thank you.
