### ISSUE TITLE
composite-metazoan.owl version

### ISSUE THREAD

**Issue by sbreiff** [obophenotype/uberon#2032]
Hi,

I noticed that there was a new UBERON version released in late July, but when I look at the composite-metazoan.owl file that’s available now on OBO library, while it doesn’t have its own versionIRI, it lists versionIRIs of the ontologies it pulls in, and for many of the bridges (as well as ext.owl) the version listed is from 2020-09-16 rather than the latest release.
 
My main questions are:
1) How often does the composite-metazoan.owl file get regenerated?
2) Are there any plans to ever assign composite-metazoan.owl its own VersionIRI or include a date on the file in any other way? 

Thanks in advance, and sorry if this is not the right place for this kind of question - when looking up UBERON contact info it sounded like you preferred the github issue tracker, even though this isn't a bug report or a new term request.

Sarah

**Comment by matentzn** [comment]
@sbreiff thank you very much for your comment; this helps greatly with prioritisation on our end.

As you have probably seen, we are in a major overhaul of Uberon with funding coming in etc; one part of this was the modernisation of the release pipelines. The composite files are basically the only ones that we have not fully migrated yet - so we keep releasing the old ones to avoid stuff breaking for downstream users. The composite files are by far the most complex in the entire Uberon ecosystem - so they need a bit more care. I will ensure that @cmungall makes this a priority! Version IRIs etc is not problem, thanks for that comment, I will do that when the composite files are ready.

**Comment by matentzn** [comment]
Also, due to our workload, please keep pushing us in this issue here if we become quiet. Thank you!

**Comment by matentzn** [comment]
@sbreiff I would invite you to contact @cmungall via email for this - he is the only person who can fix this issue. Once he has approved the current pipeline, the new Uberon team will take over and be able to more rapidly respond to your requests.

**Comment by matentzn** [comment]
Until this issue is dealt with, I fixed the composite PURLs to the last release. There is not point to update these every time on each release, and it actually simply gives us false positives on when retrieving versions..

https://github.com/OBOFoundry/purl.obolibrary.org/pull/801

**Comment by paolaroncaglia** [comment]
@matentzn can this be closed? If not, it's already in the (old) tech board, does it need moving or prioritising?
Thanks.

**Comment by matentzn** [comment]
Can't be closed, will be dealt with later this year by @cmungall himself :)

**Comment by gouttegd** [comment]
I believe there is no longer any issue here?

`composite-metazoan` is re-generated upon every release (though until today, the taxon-specific components had been frozen in November 2021 – this will no longer be the case starting from the next release).

It does have a (resolvable) version IRI, and the unversioned IRI (`http://purl.obolibrary.org/obo/uberon/composite-metazoan.owl`) points to the build from the latest release (currently 2023-10-27).
