### ISSUE TITLE
Revise Uberon website: many links are broken

### ISSUE THREAD

**Issue by hsolbrig** [obophenotype/uberon#2034]
The download ontology link on http://uberon.github.io/release/2019/11/22/release.html  -- (http://uberon.github.io/release/2019/11/22/downloads.html) doesn't work

**Comment by matentzn** [comment]
@hsolbrig Sorry the documentation pages are totally broken right now. Use:

http://purl.obolibrary.org/obo/uberon.owl (to get the latest version) or
http://purl.obolibrary.org/obo/uberon/releases/2019-11-22/uberon.owl

To get the exact version you want (which is pretty old).

We are finally pooling resources to making progress on Uberon, documentation is one of the top 5 things we want to take care of.

**Comment by hsolbrig** [comment]
Wow - that is a real-time response.   NP on the download -- I'm working on an [issue in FunOWL](https://github.com/hsolbrig/funowl/issues/25) and thought I'd report it just in case you weren't aware ...

**Comment by matentzn** [comment]
Hahha there is only one way to answer to github issues on community managed projects: right now.

Thanks for reporting! I changed the title to reflect the more general issue.

**Comment by matentzn** [comment]
Any volunteers to meet with me and revamp the Uberon docs? @shawntanzk @gouttegd? We could fix all this in 2 hours during a hackathon, but I don't want to do it alone.. If you are interested ping me.

**Comment by shawntanzk** [comment]
happy to help :) @matentzn

**Comment by gouttegd** [comment]
Happy to help as well, but not sure I can find the time before end of next week…

**Comment by matentzn** [comment]
Monday 27th of September, 3-5pm UK time Uberon documentation hacking?

**Comment by gouttegd** [comment]
Not available that afternoon, sorry. Same day on the morning would be fine, or the following Tuesday afternoon.

**Comment by shawntanzk** [comment]
so sorry, will probably be on leave 24-29 sept

**Comment by matentzn** [comment]
30 Sept 2pm-4pm?

**Comment by gouttegd** [comment]
Good for me.

**Comment by shawntanzk** [comment]
Works for me too :)

**Comment by cmungall** [comment]
Can we draw up a bit of a plan in advance? Can be high level

Assume we will switch to mkdocs?

Will we have some parts autogenerated by metadata? Eg bridge files and
lists of products; pattern docs, usages;

**Comment by matentzn** [comment]
The first meeting will be to recreate the contents of http://uberon.github.io as much as possible, using a normal mkdocs- based ODK setup like http://pato-ontology.github.io/pato/

I am assuming a lot of questions will remain open after that meeting, but none of us actually know what the plan is - part of the purpose of the "docathon" is to make a proposal for a plan. But yes, the essence is to deprecate http://uberon.github.io and move everything to the normal mkdocs setup.

Automatically generating docs for products is not on the list at the moment, but we can look into it a bit. Closing this ticket in favour of #2045
