### ISSUE TITLE
replace obsolete term GO:0044464

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2038]
GO:0044464 (cell part) is obsolete and is currently causing issues in uberon imports 
This can be fixed by changing it to ("part of" some cell) 
GO:0044464 is currently used in "dentate gyrus molecular layer" & "multi cell part structure" 
and also in GO term "neuron" 
not sure who to assign to so I just put @matentzn @dosumis and @gouttegd - happy for this to be reassigned 
ps happy to do it myself if someone could help me with this close PR #2037 where i tried editing uberon-edit.obo with protege and ended up with that

**Comment by paolaroncaglia** [comment]
This looks fixed, so I'll close.
