### ISSUE TITLE
Uberon documentation migration

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2045]
The goal is to migrate the uberon documentation framework to a standard ODK one like:
http://pato-ontology.github.io/pato/

This will involve migrating contents from https://uberon.github.io/ to here, and then obsoleting that repository.

**Comment by cmungall** [comment]
Thanks!

The pato site is still looking quite... generic. And some parts don't make sense. E.g. mentions DROID with no further explanation. Looks like this is the template approach as outlined here: https://docs.google.com/presentation/d/1YyWYSetDML3nhNgMUmcrsw80Xx1Uf1n1dWI-A20PMa8/edit#slide=id.gdfa543b746_0_1

There are some fundamental challenges we haven't solved about which parts of editors docs to centralize (and where) and which to specialize. So is the idea here for some of the uberon docs we would centralize in ODK and periodically update?

 * "News" (last updated 2019): should we just migrate the release notes to github releases? I would be fine with just migrating these across as historic markdown docs and using github releases moving forward as per ODK standards.
 * I think we should be able to map uberon.org directly to the gh pages as we do e.g. for linkml.io
 * http://uberon.github.io/downloads.html
     - we could just migrate as static md, but I think it's good to continue to have this be metadata-driven
  * Wiki docs
     - it will likely be easiest to just keep this as-is, migrate the main website, and keep the links
     - but after we close this issue I would like to prioritize getting the wiki into the site and modernizing https://github.com/obophenotype/uberon/wiki/Manual#design-patterns 
     - 
Some things that can be ditched

 * any reference to our googleplus account
 * mendeley group
 * the attempt to embed various browsers in the site, now failing http://uberon.github.io/browse/olsvis.html
 * search bar that goes to ontobee (we should favor OLS as it shows part-of)
 * http://uberon.github.io/downloads.html#data
 * http://uberon.github.io/about/adopters.html
     - this is way out of date. I would like to just ditch this, focus on the usages metadata in OBO and have something driven from that

**Comment by matentzn** [comment]
Dont worry about the empty PATO docs - its just a skeleton at this point.

I think I have a sense what stuff needs to be centralised. Everything in the PATO documentation _is centralised_ (so an ODK updated would update the docs as well). 

Dont worry about this documentation too much, I think I know how to act in your interests here.. Nothing bad will happen as the new and old docs can coexist for a while for you to check the new ones carefully. This first meeting is just to create the basic technical infrastructure, and get started.

**Comment by matentzn** [comment]
Note to team, lets also check out @cmungall awesome LinkML docs:
https://linkml.io/linkml/

**Comment by matentzn** [comment]
The migration is complete now, to here:
http://obophenotype.github.io/uberon

However feels like they have a stake, please review the new pages ([old ones here](https://uberon.github.io/) for reference).

Before we can close this issue, we still need some advice on how to "push this to uberon.org".

**Comment by matentzn** [comment]
yeah, redirect from uberon.org to the new page would be great.

To ensure users of uberon.github.io finding their way, I would also suggest:

https://github.com/uberon/uberon.github.io/pull/5

**Comment by shawntanzk** [comment]
everything looks nicely setup on http://obophenotype.github.io/uberon/ if there needs to be more docs, we can make add them there - new tickets should be made for that
