### ISSUE TITLE
Uberon and non-OBO-esque axioms

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2046]
Due to blockers on all fronts, I decided to drop the following two axioms from Uberon. 

```
SubClassOf(<http://purl.obolibrary.org/obo/UBERON_0004679> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002473> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/CL_0000000>)))

# Class: <http://purl.obolibrary.org/obo/UBERON_0005162> (<http://purl.obolibrary.org/obo/UBERON_0005162>)

SubClassOf(<http://purl.obolibrary.org/obo/UBERON_0005162> ObjectMinCardinality(2 <http://purl.obolibrary.org/obo/RO_0002180> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/CL_0000000>)))
```

The story can be read here: https://github.com/obophenotype/uberon/pull/2037

Previously, there were two axioms that references the now obsolete GO:cell part, and we wanted to replace them by `part of some CL:cell` which proved to be too deep a nesting for OBO format.

As a protective measure, we do not allow non-OBO axioms in the Uberon edit file. There are three options to proceed:

1. We create a new term `Uberon:cell part` and use that (aka - we create terms instead of use post-composition when the nesting becomes un-OBOtic).
2. We explicitly allow non-OBOesque axioms in Uberon by adding them to a separate, external file
3. We drop these two axioms due to their questionable utility (especially the second one)

cc @dosumis @cmungall @shawntanzk

**Comment by dosumis** [comment]
We should allow for extensions to Uberon that go beyond OBO format.  These should live in an imported ontology:  uberon_ext.owl. This follows precedent for other ontologies whose master files are maintained in OBO format.  Separate issue - we may want to reconsider cardinality constraints given scaling issues.

**Comment by matentzn** [comment]
Currently, this is what ext.owl does:

```
ext.owl: $(TMPDIR)/materialized.owl $(TMP_REFL)
	owltools $(UCAT) $< $(TMP_REFL) --merge-support-ontologies -o $(TMPDIR)/m1.owl && \
	$(ROBOT) --catalog $(CATALOG) merge -i $(TMPDIR)/m1.owl --collapse-import-closure false \
	unmerge -i $(TMP_REFL) \
	annotate -O $(URIBASE)/uberon/$@ -V  $(RELEASE)/$@ -o $@ 2>&1 > $(TMPDIR)/$@.LOG
```

So the only thing that is being added to the normal merged uberon.owl is:

```
Ontology(<http://purl.obolibrary.org/obo/uberon/reflexivity_axioms.owl>
 ReflexiveObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000050>)
 ReflexiveObjectProperty(<http://purl.obolibrary.org/obo/RO_0002202>)
)
```

I don't see anything else! (it used to also merge phenoscape.owl which has since been merged)

**Comment by cmungall** [comment]
We could easily add a new import for expressive axioms

But tbh this is lower priority for these two axioms

```
id: UBERON:0005162
name: multi cell part structure
def: “A structure consisting of multiple cell components but which is not itself a cell and does not have (complete) cells as a part.” [CARO:0001000]
subset: upper_level
synonym: “cell part cluster” RELATED [FMA:83115]
synonym: “multi-cell-component structure” EXACT [CARO:0001000]
synonym: “multi-cell-part structure” EXACT [CARO:0001000]
xref: AAO:0011000
xref: CARO:0001000
xref: FBbt:00007060
xref: FMA:83115
is_a: UBERON:0000477 {source=“FMA”} ! anatomical cluster
relationship: composed_primarily_of GO:0005575 ! cellular_component
***relationship: has_component GO:0044464 {minCardinality=“2"} ! obsolete cell part
property_value: external_ontology_notes “we go with the FMA classification rather than the CARO one. FMA def: ‘Anatomical cluster which has as direct parts cell parts from two or more cells.’” xsd:string {external_ontology=“CARO”, external_ontology=“FMA”}
```

this really doesn't buy us anything from reasoning.. and if we we replaced by (part-of some cell) it's trivially satisfied e..g by having 2 atoms from cells

this one is a bit more interesting:

```
id: UBERON:0004679
name: dentate gyrus molecular layer
def: "The molecular layer of the dentate gyrus that is bounded by the pial surface superficially and the dentate gyrus granule cell layer deep. It is divided into 2 or more sublayers." [BIRNLEX:4127]
synonym: "dentate gyrus molecular layer" EXACT [BIRNLEX:4127]
synonym: "molecular layer of dentate gyrus" EXACT [FMA:83677]
synonym: "molecular layer of the dentate gyrus" RELATED [BAMS:Mol]
synonym: "stratum moleculare gyri dentati" EXACT LATIN [FMA:83677, FMA:TA]
xref: BAMS:mo
xref: BAMS:Mol
xref: BIRNLEX:4127
xref: EMAPA:35279
xref: FMA:83677
xref: http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=2121
xref: MA:0003122
xref: MBA:10703
intersection_of: UBERON:0002304 ! layer of dentate gyrus
intersection_of: bounding_layer_of UBERON:0001885 ! dentate gyrus of hippocampal formation
***relationship: composed_primarily_of GO:0044464 ! obsolete cell part
relationship: has_part GO:0030425 ! dendrite
relationship: has_part UBERON:0006134 ! nerve fiber
relationship: immediately_deep_to UBERON:0002361 ! pia mater
```

It is potentially useful to axiomatize cell layers by their parts, but this hasn't been done consistently, only this one term, and we will probably want a different pattern anyway.

So I think it's OK to close this until we have a real use case and non-rococo axioms we need to express

**Comment by matentzn** [comment]
I agree @cmungall.
