### ISSUE TITLE
Stage ontologies should be released as part of the Uberon release process

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2047]
And follow the same release standards, i.e. owl and json releases.

**Comment by paolaroncaglia** [comment]
@matentzn 
Who should this be assigned to, please? Cheers.

**Comment by matentzn** [comment]
I will do it, but not quickly. I may organise a meeting with @shawntanzk to teach him how to do it, but for now, its best I do it.

**Comment by shawntanzk** [comment]
@matentzn sorry for the late reply - was on holiday. Happy to learn how to do it and follow up with this when I do :)

**Comment by paolaroncaglia** [comment]
@matentzn @shawntanzk I suspect that this issue is already on your radar, I added it to the tech board to keep track if needed. Otherwise, please feel free to close.

**Comment by anitacaron** [comment]
@matentzn, can you list the stage ontologies?

**Comment by matentzn** [comment]
https://github.com/obophenotype/developmental-stage-ontologies/tree/master/src

This repo is also cloned in the uberon pipeline at some point.

**Comment by gouttegd** [comment]
Given the [ongoing work](https://github.com/obophenotype/developmental-stage-ontologies/pull/102) to treat the stage ontologies, collectively, as a _bona fide_ independent ontology, which can be released on its own, I think it’s fair to say that releasing them  “as part of the Uberon release process” is no longer on the cards, so we can close here.
