### ISSUE TITLE
Refining the Uberon Euarchontoglires subset

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#2050]
Stemming from https://github.com/HumanCellAtlas/ontology/issues/84#. I scanned the Uberon Euarchontoglires subset to search for non-primate, non-rodent, non-rabbit terms. Note, this was a quick search and not meant to be exhaustive. Here are a few possible strategies to identify and filter out unwanted classes in a time-effective way. These would improve the subset quality and should help make the subset more manageable (it currently has >20k classes):

- [x] Search for annotation property ‘never in taxon’ ‘Homo sapiens’ (e.g. ‘ampullary gland’, ‘bone of reproductive organ’). Some terms may need double-checking in case they are found in non-human Euarchontoglires.

- [x] I spotted many fish-specific terms. Searching for created_by teleost_anatomy_curators should retrieve them all (e.g. 'fin fold pectoral fin bud’). Their IDs all start with UBERON:2

- [x] Same for amphibians: search by created_by amphibian_anatomy_curators (e.g. 'pars amphibiorum’). Their IDs all start with UBERON:3

- [x] Insect terms may be retrieved by searching for database_cross_reference contains FBbt (e.g.: 'egg chorion’). This will also bring up a dozen terms whose label contains “insect” (e.g. 'insect ring gland’).

- [x] Other random finds:
exoskeleton 
shell
'open circulatory system'
feather
rhinarium?
honey

- [x] Investigate adding taxon constraints en masse (I recall there was a similar comment from Chris some time ago somewhere; found it: https://github.com/obophenotype/uberon/issues/1824#issuecomment-817959064)

Thanks,
Paola

**Comment by dosumis** [comment]
Hi @paolaroncaglia  - are you clear on how to add taxon constraints in these cases, or would you like to discuss?

**Comment by paolaroncaglia** [comment]
@dosumis 

> Hi @paolaroncaglia - are you clear on how to add taxon constraints in these cases, or would you like to discuss?

I might ask @matentzn for help please with adding constraints in bulk, but I'll take a closer look and will then contact him offline if he's available. I'll update the ticket as we go - aiming to have the slim ready to integrate in the HCAO release pipeline for the Oct 19th release.

**Comment by paolaroncaglia** [comment]
@cmungall wrote in https://github.com/obophenotype/uberon/issues/1824#issuecomment-817959064:

"UBERON:6x --> these are all specific to arthropods, and we can add TCs to 6x roots en masse
UBERON:2x --> likely teleost but not universally. I am comfortable adding never-in mammal en masse to existential roots
UBERON:3x --> likely amphibia but not universally. I am comfortable adding never-in mammal en masse to existential roots
UBERON:4x --> mixed, I think this is a small enough subset to look over quickly and add TCs. There will be a handful applicable to human"

So I suggest
- [ ] Add subclass 'only in taxon' some Arthropoda to all UBERON:6x classes
- [ ] Scan UBERON:2x classes quickly. Flag any that may be relevant to Euarchontoglires. Add annotation 'never  in taxon' Mammalia to all others.

TO BE CONTINUED

Note to self, guidelines [here](https://ontology-development-kit.readthedocs.io/en/latest/TaxonRestriction.html).

**Comment by dosumis** [comment]
@paolaroncaglia  - nice work!  It should be straightforward to add these via ROBOT templates. This can be done working directly from you google sheets.

@rays22  - can you have a go at working with Paola to do this?  Happy to help if you run into problems.   We basically just need an ID column and one or two columns for adding taxon constraints.  The results can then be merged into the editor's file with robot merge - chained to robot convert to ensure the results is in obo format.

**Comment by paolaroncaglia** [comment]
Hi @dosumis and @rays22 ,
Before adding TCs en masse, it'd be good to get feedback about those UBERON:2x, UBERON:3x and UBERON:4x classes above, please. I've added to today's meeting agenda.
I don't have ROBOT installed on my old laptop (going to buy a new one soon, but this ticket shouldn't wait), so once the TCs are sorted, I'd leave it to someone else please to add them via ROBOT. Thanks!

**Comment by paolaroncaglia** [comment]
Update: at the Uberon editors meeting earlier this week, it was resolved to mass-add TCs to all UBERON:2x, 3x and 4x terms as above. Then, at a later date, terms that were added TCs may be scanned for FMA xrefs, and brought back into the slim if they have FMA xrefs. Other steps will stay as outlined [above](https://github.com/obophenotype/uberon/issues/2050#issuecomment-925681658).

**Comment by paolaroncaglia** [comment]
Back to the set of Uberon terms with ID starting with 4: Chris wrote:
"UBERON:4x --> mixed, I think this is a small enough subset to look over quickly and add TCs. There will be a handful applicable to human"
As mentioned, there are 369 non-obsolete UBERON:4x classes in the slim, copied [here](https://docs.google.com/spreadsheets/d/133F9PVxOk2lM8tkY_afjy7P_bwbZM1b_u1O2abyTvI8/edit#gid=1223601784). I inspected 10 random terms among the 369, and at least 3 are applicable to human, so I'm not very comfortable with adding TCs en masse to this set. @dosumis what would you prefer: a) we retain all 369 terms in the slim; b) or is there someone who could take a closer look and advice on what terms are safe to restrict to never in mammals? Perhaps Wasila, who authored some terms in this set? Thanks.

**Comment by paolaroncaglia** [comment]
@dosumis @rays22 
The [spreadsheet](https://docs.google.com/spreadsheets/d/133F9PVxOk2lM8tkY_afjy7P_bwbZM1b_u1O2abyTvI8/edit#gid=0) is ready for ROBOT, pending
- [ ] A decision on the UBERON:4x set (last sheet in the spreadsheet)
- [ ] Extraction of class ID from the first column, if that's the format you need
- [ ] Checking that the action item column is in the right format for ROBOT.

As I said I can't really help with ROBOT at the moment, but let me know if I can do anything else for this ticket.
Once the TCs are added, who will re-build the slim?

Thanks and have a good weekend.

**Comment by dosumis** [comment]
Hi @rays22  - looks good.  Do you have a PR I can review?

**Comment by matentzn** [comment]
Please start making a library of reusable templates in src/templates

**Comment by rays22** [comment]
As part of [a roll back](https://github.com/obophenotype/uberon/issues/2127#issuecomment-979791339), I am going to remove the UBERON:3x bulk `never in taxon` *Mammalia* taxon constraints that were part of this ticket. Some of the 2x and 3x classes appear to overlap with *Mammalia*.
