### ISSUE TITLE
Same latin term annotation for 2 different terms

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#2058]
UBERON:0001461 'elbow' and UBERON:0001490 'elbow joint' both have the "latin term" annotation property, "articulatio cubiti". 
"Articulatio" means "joint", so the latin synonym is exact for UBERON:0001490 'elbow joint', and 
- [ ] should be removed from UBERON:0001461 'elbow' please, as 'elbow' encompasses the whole elbow region including skin etc.  

The latin term in 'elbow' is xref'd to the [Wikipedia entry for elbow](https://en.wikipedia.org/wiki/Elbow). If it was ingested automatically, this raises the question, are there other cases where a Wikipedia entry is (understandably) more generalist than Uberon, but causes xrefs like FMA IDs, Mesh IDs, latin term synonyms etc to be attached to a broader class than appropriate?

**Comment by paolaroncaglia** [comment]
At today's Uberon call, Chris confirmed that FMA xrefs are _not_ ingested automatically from Wikipedia.
The potential issue of duplicate "latin term" annotation property is of lower priority.
Chris suggests looking into TA (Terminologia Anatomica) annotations, but that's another project (not clear if the 2 versions of TA use the same ID or not, if they can be inspected programmatically etc.).
In the short term, I might remove the duplicate annotation "articulatio cubiti" (elbow joint) from UBERON:0001461 'elbow', as 'elbow' encompasses the whole elbow region including skin etc., unless @emquardokus has objections please (wrt discussion on "joint" terms). Thanks.
