### ISSUE TITLE
Import file with ":" not allowed in Windows Environments

### ISSUE THREAD

**Issue by JoshuaFortriede** [obophenotype/uberon#2064]
The imports file "urn:unnamed:ontology#ont1snap_import.owl" has the colon ":" character in it. The colon is not a valid filename character in Windows environment. As such, the repo cannot be cloned in a windows environment.

The recommendation would be to rename the file, but I am unsure if scripts/pipelines utilize this exact name.

**Comment by dosumis** [comment]
To fix - this just needs to be deleted: https://github.com/obophenotype/uberon/blob/master/imports/urn:unnamed:ontology%23ont1snap_import.owl

**Comment by dosumis** [comment]
Fixed by https://github.com/obophenotype/uberon/commit/7e6940aaf4dab168698af46e9380b5e0613cee75
