### ISSUE TITLE
Euarch slim should be a -simple file.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#2065]
Doesn't need imports.

**Comment by matentzn** [comment]
I simply cannot handle these extra requests anymore - we need a new strategy moving forward. I can train someone to do it, but we need committed hours - of someone with a nack and interest in going into the technical..

**Comment by paolaroncaglia** [comment]
Also see https://github.com/obophenotype/uberon/issues/2182

**Comment by matentzn** [comment]
Fixed in https://github.com/obophenotype/uberon/pull/2190

**Comment by paolaroncaglia** [comment]
This is done already. I assigned to @matentzn to record his involvement :-)
