### ISSUE TITLE
NTR: right lymphatic duct

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#2069]
From [Wikipedia](https://en.wikipedia.org/wiki/Lymph_duct): "A lymph duct is a great lymphatic vessel that empties lymph into one of the subclavian veins. There are two lymph ducts in the body—the right lymphatic duct and the thoracic duct. The right lymphatic duct drains lymph from the right upper limb, right side of thorax and right halves of head and neck. The thoracic duct drains lymph into the circulatory system at the left brachiocephalic vein between the left subclavian and left internal jugular veins."
Uberon already has 'thoracic duct'. Note that in this case it appears that 'right lymphatic duct' would not need a 'left' counterpart.

**Preferred term label:**
right lymphatic duct

**Synonyms**
See https://en.wikipedia.org/wiki/Right_lymphatic_duct for Latin term

**Definition (free text, please give PubMed ID)**
See https://en.wikipedia.org/wiki/Right_lymphatic_duct for definition and xrefs, including FMA

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lymphatic vessel

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-2825-0621

Taxon note: found in Homo sapiens

**Comment by paolaroncaglia** [comment]
Added as UBERON:8410078 right lymphatic duct
