### ISSUE TITLE
Dip in CL equivalent class axioms detected

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2075]
I can see things like this in the diff:

![image](https://user-images.githubusercontent.com/7070631/135522664-eeebf32b-ae80-4ae9-acdc-9a25a406d195.png)

I chased this down to this goal:

```
$(TMPDIR)/cl-core.obo: $(SRC)
	owltools $(URIBASE)/cl.owl  --make-subset-by-properties -n BFO:0000050 BFO:0000051 RO:0002202 RO:0002215 --remove-external-classes -k CL --remove-dangling --remove-axiom-annotations --remove-imports-declarations -o -f obo --no-check $@
```

The cl.owl that goes in still has the correct axioms (`$(URIBASE)/cl.owl`), `$(TMPDIR)/cl-core.obo` does not. No idea why this never showed up before. It should have! `--remove-external-classes -k CL` is probably the reason, so in my opinion this closing this is acceptable, but I want to mention it to @dosumis and @cmungall as an FYI.

**Comment by paolaroncaglia** [comment]
@matentzn @shawntanzk @dosumis 
Tagging you as author and assignees respectively
Can this be closed? If not, I already added it to the tech board. Thanks.

**Comment by shawntanzk** [comment]
@paolaroncaglia will make sure it gets looked at next meeting

**Comment by shawntanzk** [comment]
Closing this - will also solve itself once we move to base module
