### ISSUE TITLE
Error in definition of pelvic girdle region UBERON:0001271

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#2090]
**Uberon term**
UBERON:0001271

**Bug description**
Definition incorrectly states pectoral girdle in example (this is thoracic region/rib case area) when it should be citing pelvic girdle region.

Current Definition:
The organism subdivision that includes the pelvic girdle skeleton and associated soft tissue. Note that this includes both the skeletal elements and associated tissues (integument, muscle, etc). Examples: There are only two instances in an organism, **right and left pectoral girdle regions.**

This "right and left pectoral girdle regions." should be replaced with "right and left pelvic girdle regions."

<img width="518" alt="Screen Shot 2021-10-11 at 2 23 36 AM" src="https://user-images.githubusercontent.com/47257000/136743241-2f394dcf-b0f0-4aaf-a2a8-2646efb918a1.png">

<img width="314" alt="Screen Shot 2021-10-11 at 2 18 42 AM" src="https://user-images.githubusercontent.com/47257000/136743277-07acc787-c8c9-4e99-a82a-1192ba8e6e6e.png">

**Comment by paolaroncaglia** [comment]
cc @emquardokus 
This typo hasn't been corrected yet. I'll do it next time I edit Uberon.

**Comment by cmungall** [comment]
This should be an easy fix

**Comment by paolaroncaglia** [comment]
@emquardokus FYI, I fixed the typo.
