### ISSUE TITLE
NTR: red bone marrow of iliac crest

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#2091]
**Preferred term label:**
red bone marrow of iliac crest

**Synonyms**

**Definition (free text, please give PubMed ID)**
The iliac crest has a large amount of red bone marrow, and thus it is the site of bone marrow harvests (from both sides) to collect the stem cells used in bone marrow transplantation. https://en.wikipedia.org/wiki/Iliac_crest

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
red bone marrow UBERON:0000361

**Your nano-attribution (ORCID)**
0000-0001-7655-4833

**Comment by paolaroncaglia** [comment]
@emquardokus 
Is this term still needed? If yes, I can add it if you wish.

**Comment by paolaroncaglia** [comment]
@emquardokus the new term is UBERON:8410079 'red bone marrow of iliac crest'.
