### ISSUE TITLE
NTR: red bone marrow of sternum

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#2092]
**Preferred term label:**
red bone marrow of sternum

**Synonyms**

**Definition (free text, please give PubMed ID)**

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
red bone marrow UBERON:0000361

**Your nano-attribution (ORCID)**
0000-0001-7655-4833

**Comment by paolaroncaglia** [comment]
@emquardokus 
Same as #2091 - I'm happy to add this term if it's still needed.

**Comment by emquardokus** [comment]
@paolaroncaglia  yes, please; thank-you

**Comment by paolaroncaglia** [comment]
@emquardokus the new term is UBERON:8410080 'red bone marrow of sternum'.
