### ISSUE TITLE
unify annotations

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2093]
Add documentations on how each of the ontologies handle things like created by and xrefs (I've been noticing that there each one handles it differently and it's sometimes not consistent within ontology)

Related to: https://github.com/pato-ontology/pato/issues/278

**Comment by anitacaron** [comment]
|                           ANNOTATION                           | UBERON |  CL  | PATO |  RO |
|:--------------------------------------------------------------:|:------:|:----:|:----:|:---:|
| http://geneontology.org/formats/oboInOwl#created_by            |        |   3  |      |     |
| http://purl.obolibrary.org/obo/IAO_0000115                     |  11762 | 2141 | 1851 |     |
| http://purl.obolibrary.org/obo/IAO_0000116                     |   910  |   1  |      |     |
| http://purl.obolibrary.org/obo/IAO_0000231                     |   291  |      |  84  |     |
| http://purl.obolibrary.org/obo/IAO_0000232                     |   240  |      |      |  69 |
| http://purl.obolibrary.org/obo/IAO_0000412                     |        |   2  |      |     |
| http://purl.obolibrary.org/obo/IAO_0000589                     |        |      |   1  |  22 |
| http://purl.obolibrary.org/obo/IAO_0100001                     |   512  |  26  |  90  |  2  |
| http://purl.obolibrary.org/obo/RO_0002161                      |   272  |   1  |      |     |
| http://purl.obolibrary.org/obo/RO_0002173                      |    4   |      |      |     |
| http://purl.obolibrary.org/obo/RO_0002174                      |   42   |      |      |     |
| http://purl.obolibrary.org/obo/RO_0002175                      |   312  |   4  |      |     |
| http://purl.obolibrary.org/obo/RO_0002423                      |        |      |      |  1  |
| http://purl.obolibrary.org/obo/RO_0002575                      |        |      |      |  6  |
| http://purl.obolibrary.org/obo/RO_0002579                      |        |      |      |  2  |
| http://purl.obolibrary.org/obo/RO_0002604                      |        |      |  425 |     |
| http://purl.obolibrary.org/obo/RO_0004049                      |        |      |      |  7  |
| http://purl.obolibrary.org/obo/RO_0004050                      |        |      |      |  7  |
| http://purl.obolibrary.org/obo/RO_0040042                      |        |      |      |  2  |
| http://purl.obolibrary.org/obo/UBPROP_0000001                  |  1605  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000002                  |   195  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000003                  |   623  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000004                  |  2470  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000005                  |   23   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000006                  |   88   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000007                  |   315  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000008                  |   815  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000009                  |   159  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000010                  |   114  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000011                  |   157  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000012                  |   646  |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000013                  |   67   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000014                  |   14   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000015                  |   13   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000103                  |    8   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000104                  |   24   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000105                  |    1   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000106                  |   12   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000107                  |   19   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000108                  |   30   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000111                  |    8   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000112                  |   11   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000201                  |   11   |      |      |     |
| http://purl.obolibrary.org/obo/UBPROP_0000202                  |   43   |      |      |     |
| http://purl.obolibrary.org/obo/term_editor                     |   21   |      |      |     |
| http://purl.org/dc/elements/1.1/contributor                    |   299  |   1  |   3  |  7  |
| http://purl.org/dc/elements/1.1/creator                        |    7   |  93  |   4  |  9  |
| http://purl.org/dc/elements/1.1/date                           |   28   |  24  |  25  |     |
| http://purl.org/dc/elements/1.1/description                    |    2   |      |      |  1  |
| http://purl.org/dc/terms/source                                |        |      |      |  2  |
| http://purl.org/spar/cito/citesAsAuthority                     |        |      |      |  41 |
| http://www.geneontology.org/formats/oboInOwl#consider          |   809  |  26  |   3  |     |
| http://www.geneontology.org/formats/oboInOwl#created_by        |  3074  |  873 |  733 |  80 |
| http://www.geneontology.org/formats/oboInOwl#creation_date     |   37   |  759 |  630 |  79 |
| http://www.geneontology.org/formats/oboInOwl#hasAlternativeId  |   341  |  74  |  84  |     |
| http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym   |  1297  |  183 |  12  |     |
| http://www.geneontology.org/formats/oboInOwl#hasDbXref         |  49662 | 1475 |  53  |     |
| http://www.geneontology.org/formats/oboInOwl#hasExactSynonym   |  25684 | 2013 |  623 |     |
| http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym  |   813  |  35  |  22  |     |
| http://www.geneontology.org/formats/oboInOwl#hasOBONamespace   |  15228 | 2177 | 2738 |     |
| http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym |  11777 |  242 |  257 |     |
| http://www.geneontology.org/formats/oboInOwl#id                |  15228 |  101 | 2738 |     |
| http://www.geneontology.org/formats/oboInOwl#inSubset          |  5827  |  143 | 2729 | 224 |
| http://www.w3.org/2000/01/rdf-schema#comment                   |   993  |  486 |  102 |     |
| http://www.w3.org/2000/01/rdf-schema#label                     |  15229 | 2542 | 2738 |     |
| http://www.w3.org/2000/01/rdf-schema#seeAlso                   |   127  |   7  |      |  92 |
| http://www.w3.org/2004/02/skos/core#closeMatch                 |        |      |      |  3  |
| http://www.w3.org/2002/07/owl#deprecated                       |  1338  |  130 |  977 |     |
| http://xmlns.com/foaf/0.1/depicted_by                          |  1885  |   1  |      |     |

**Comment by shawntanzk** [comment]
omg that is such a great table! thanks!
