### ISSUE TITLE
Harmonising oio:created_by and oio:date to Dublin Core (October 2021)

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2106]
Writing this ticket + adding to agenda for call on UBERON - we need consensus and go ahead for this. 

Currently we have multiple annotation properties for creator and creation date which should be reduced and standardised: 

http://purl.org/dc/elements/1.1/creator <- suggest to use this though in obo wont look nice
http://www.geneontology.org/formats/oboInOwl#created_by

http://www.geneontology.org/formats/oboInOwl#creation_date
http://purl.org/dc/elements/1.1/date

**Comment by matentzn** [comment]
Why did david become an individual? He shouldn't.. At least not if he was not forced to be one..

**Comment by balhoff** [comment]
I think that sounds good, although those axioms themselves are a bit invisible inside Protege as far as I can remember.

**Comment by shawntanzk** [comment]
ill leave this on stale as we might forget to close it, but I rmbr there being discussion on this on omo workshop on what standard way we do this.

**Comment by anitacaron** [comment]
This was done in the PR https://github.com/obophenotype/uberon/pull/2206
