### ISSUE TITLE
should apocrine sweat gland be a subclass of apocrine gland ?

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#2111]
**Uberon term**
![image](https://user-images.githubusercontent.com/112839/138073773-6825df6b-9cbe-4942-afdc-845c741b6cfb.png)

**Bug description**

'apocrine sweat gland' is classified as a sweat gland and as a merocrine (AKA eccrine) gland.  It is therefore not classified under the defined class 'skin apocrine gland' (which has no children).

The terminology here  is rather confusing.  The term has the following note:

'curator notes' "A note of confusion is the difference between apocrine secretion and apocrine sweat gland. Apocrine secretion refers to the apical loss of a cell's membrane to create cell blebs, thus creating a secretory product. Apocrine sweat gland refers to a structure, not a secretion process. Apocrine sweat glands actually use a merocrine type secretion, or that mediated by exocytosis of secretory granules. When 'apocrine gland' is used without the word sweat, it is often referring to the gland which uses merocrine secretion, and not the secretion method. The important difference in apocrine sweat gland structure is its larger lumen, compared to the more narrow lumen of the eccrine sweat gland."^^xsd:string

**Comment by paolaroncaglia** [comment]
Notes for self:
- [ ] Add rdfs:comment to 'skin apocrine gland': "Note that 'skin apocrine gland' does not cover 'apocrine sweat gland': in the former, "apocrine" refers to the type of secretion mechanism, while in the latter it refers to a structural feature."
- [ ] https://www.ncbi.nlm.nih.gov/books/NBK482199/ contains examples of true apocrine glands: see if any should be added as subclasses of 'skin apocrine gland' (including non-human examples).

**Comment by paolaroncaglia** [comment]
@dosumis https://github.com/geneontology/go-ontology/issues/22291

**Comment by raymond91125** [comment]
"Apocrine sweat glands actually use a merocrine type secretion, or that mediated by exocytosis of secretory granules." I think this statement is not quite right.
<https://en.wikipedia.org/wiki/Apocrine_sweat_gland>
"Apocrine sweat glands were originally thought to use only apocrine secretion: vesicles pinch off from the secretory cells, then degrade in the secretory lumen, releasing their product.[24] More recent research has also shown that merocrine secretion takes place.[25]"

**Comment by paolaroncaglia** [comment]
@raymond91125 thank you for your input:

> "Apocrine sweat glands actually use a merocrine type secretion, or that mediated by exocytosis of secretory granules." I think this statement is not quite right.
> https://en.wikipedia.org/wiki/Apocrine_sweat_gland
> "Apocrine sweat glands were originally thought to use only apocrine secretion: vesicles pinch off from the secretory cells, then degrade in the secretory lumen, releasing their product.[24] More recent research has also shown that merocrine secretion takes place.[25]"

I've looked for additional evidences in recent literature, but I'm still confused. How would you suggest to rephrase the curator note above? Would this have any consequence on the appropriate placement of the term? I.e. currently 'apocrine sweat gland' is a subclass of 'merocrine gland', but if a consensus isn't clear from the literature and/or both mechanisms have been observed, should the parent be changed to the broader 'exocrine gland' to be conservative?

Thanks,
Paola

**Comment by raymond91125** [comment]
An extensive and good reference review is PMID:18489347 A short history of sweat gland biology.
Apparently cosmetologists are more interested in these things ...

**Comment by paolaroncaglia** [comment]
@dosumis FYI

> Seems like GO should have a process for this secretion mechanism, but I couldn't find a term from a quick search of GO BP. Maybe we should request one? It would be useful for defining glands/cells that use apocrine (decapitation) secretion mechanism.

The GO term was added as GO:0160022 'apocrine secretion' [here](https://github.com/geneontology/go-ontology/commit/a36ded0da2c9c3425cbcce63b88d8132c0260694).
