### ISSUE TITLE
Revise modeling of autonomic nervous system

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#2119]
This is a placeholder ticket stemming from https://github.com/obophenotype/uberon/issues/2104.
Consider coordinating with the Data and Resource Center (DRC) of the NIH-funded SPARC program to revise modeling of autonomic nervous system (their recent paper is [here](https://www.frontiersin.org/articles/10.3389/fphys.2021.693735/full): "...SPARC data are aligned to common spatial standards ... and also annotated with FAIR vocabularies derived from community ontologies like UBERON.").
In particular, see @tgbugs ' [comment](https://github.com/obophenotype/uberon/issues/2104#issuecomment-949170141) "I think that the right thing to do here is to update the modelling so that we wind up with parasypathetic cholinergic neuron projection bundle, because I think that there are very few cases of nerves that are purely cholinergic (though some branches might be). We have been working to develop clearer definitions for nerves, nerve branches, fiber bundles, etc., but they aren't quite ready."
Assigning to @dosumis for discussion and coordination.

**Comment by tgbugs** [comment]
Why is there a stale bot on this repo? There are long standing issues that are years old that have not been fixed, and they should not be closed just to make the numbers look smaller ....

**Comment by dosumis** [comment]
It's there to prompt us into action.  IIRC, discussion on the ticket is enough to keep it open - so your objection already helped.  Shall we make a plan for how to fix modelling and work more closely with SPARC?  We could revise the call we planned before Christmas, which I dropped the ball on.
