### ISSUE TITLE
Refining the Uberon Euarchontoglires subset -- part 2

### ISSUE THREAD

**Issue by rays22** [obophenotype/uberon#2127]
### Remaining tasks

- [x] UBERON:4x series in <https://docs.google.com/spreadsheets/d/133F9PVxOk2lM8tkY_afjy7P_bwbZM1b_u1O2abyTvI8/edit#gid=1223601784>

> UBERON:4x --> mixed, I think this is a small enough subset to look over quickly and add TCs. There will be a handful applicable to human"

_Originally posted by @rays22 in https://github.com/obophenotype/uberon/issues/2050#issuecomment-947820509_

**Comment by dosumis** [comment]
Chris wrote:

> UBERON:2x --> likely teleost but not universally. I am comfortable adding never-in mammal en masse to existential roots
https://github.com/obophenotype/uberon/issues/1824#issuecomment-817959064

spreadsheet is here:
https://docs.google.com/spreadsheets/d/133F9PVxOk2lM8tkY_afjy7P_bwbZM1b_u1O2abyTvI8/edit#gid=1895359959

This => 

preplacodal ectoderm' <http://purl.obolibrary.org/obo/UBERON_2007013> |   | never_in_taxon Mammalia
-- | -- | --

There are other wrong or dubious-looking entries in here: 

primary head sinus' <http://purl.obolibrary.org/obo/UBERON_2005026> |   | never_in_taxon Mammalia
rib of vertebra 1' <http://purl.obolibrary.org/obo/UBERON_2001879> |   | never_in_taxon Mammalia
rib of vertebra 2' <http://purl.obolibrary.org/obo/UBERON_2001878> |   | never_in_taxon Mammalia
rib of vertebra 3' <http://purl.obolibrary.org/obo/UBERON_2001880> |   | never_in_taxon Mammalia
rib of vertebra 4' <http://purl.obolibrary.org/obo/UBERON_2001881> |   | never_in_taxon Mammalia
rib of vertebra 5' <http://purl.obolibrary.org/obo/UBERON_2001751> |   | never_in_taxon Mammalia
rib of vertebra 6' <http://purl.obolibrary.org/obo/UBERON_2001750> |   | never_in_taxon Mammalia
skin flap' <http://purl.obolibrary.org/obo/UBERON_2001951> |   | never_in_taxon Mammalia
somite 1' <http://purl.obolibrary.org/obo/UBERON_2000072> |   | never_in_taxon Mammalia
somite 10' <http://purl.obolibrary.org/obo/UBERON_2000974> |   | never_in_taxon Mammalia
somite 11' <http://purl.obolibrary.org/obo/UBERON_2000725> |   | never_in_taxon Mammalia
...

Conclusion - This needs much more curation!

@rays22 @paolaroncaglia

**Comment by paolaroncaglia** [comment]
Update: the broader issue of taxon restrictions was discussed at the [Uberon editors meeting on 22/11/21](https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit#heading=h.nk1gnd781mf):

"We need more specific action items to deal with taxon stuff
https://github.com/obophenotype/uberon/issues/2137 
Chris suggested fix - Chris to add ticket!
Roll back 2x, 3x, 4x general taxon constraint 
2x, 3x, 4x all get new slim tag - used for anti-slim stripping of terms only with owltools.  Curate to hold back a few.
Suggestion:
We need a taxon fix hackathon where we look at the ontology itself to work through a longer term strategy for fixing."

**Comment by matentzn** [comment]
Alright, this is how I understand this ticket.

- [ ] "Roll back": We go to @rays22 original list of taxon constraints, and remove them using robot unmerge, and instead add a "never_in_euroglires" subset tag on them.
- [ ] "Anti-slim stripping". After the normal unsat-pipeline is run, we use SPARQL to remove the remaining  "never_in_euroglires", the difficulty here is to tie together broken existential edges (i.e. part-of) edges. Maybe we can use some kind of Relationgraph style approach or something @cmungall outline in #2183.

**Comment by rays22** [comment]
> * [ ]  "Roll back": We go to @rays22 original list of taxon constraints, and remove them using robot unmerge, and instead add a "never_in_euroglires" subset tag on them.
> *

### Summary of 673 taxon constraints added as part of #2050
Here is my list of the #2050-related taxon constraints that are in UBERON currently.
* provenance: `{source="https://github.com/obophenotype/uberon/issues/2050"}`

* 660 classes : [never_in_taxon-IDs.txt](https://github.com/obophenotype/uberon/files/7608113/never_in_taxon-IDs.txt) `relationship: never_in_taxon NCBITaxon:n`
    * 23 classes : UBERON:2x (likely Teleost)
    * 637 classes : UBERON:3x (likely Amphibia)
* 13 classes : UBERON:6x (Arthropods) `relationship: in_taxon NCBITaxon:6656 {source="https://github.com/obophenotype/uberon/issues/2050"} ! Arthropoda`

**Comment by paolaroncaglia** [comment]
This is still in progress.
