### ISSUE TITLE
There are multiple terms that have "." as definition

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2129]
There are multiple terms that have "." as definition - this seems super weird, it is triggering duplicate_definition. Will investigate. Examples include:

First 5 violations:
ERROR	duplicate_definition	UBERON:0000089	IAO:0000115	.
ERROR	duplicate_definition	UBERON:0000219	IAO:0000115	.
ERROR	duplicate_definition	UBERON:0000444	IAO:0000115	.
ERROR	duplicate_definition	UBERON:0001430	IAO:0000115	.
ERROR	duplicate_definition	UBERON:0001431	IAO:0000115	.

Note: this does have xrefs attached to it, so it seems it might have been accidentally removed or something?

Btws, found this when running `sh run.sh make reports/uberon-edit.obo-obo-report.tsv`

**Comment by shawntanzk** [comment]
- [ ] @gouttegd to look into this in makefile to see where this should come from
- [ ] @shawntanzk will follow up if we can't figure this out

**Comment by gouttegd** [comment]
The “.” definitions are not injected from anywhere in the pipeline, they come straight from the -edit file.

Contrary to what we have in FBbt, in Uberon it does not seem that there is anything in place in the pipeline to deal with “dot-definitions“.

For reference, what happens in FBbt is that terms with “dot-definitions” are extracted (using [this SPARQL query](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/src/sparql/dot-definitions.sparql)), and processed by [a custom Java program](https://github.com/monarch-ebi-dev/eqwriter) (apparently specifically written for FlyBase) to generate textual definitions from the logical definitions.

Not sure if we want to apply the FlyBase approach in Uberon (of note, some Uberon terms with a “dot-definition” don’t have a logical definition, so that approach would not work anyway for them)… For 131 terms, I am inclined to say the FlyBase approach is overkill and that it would be easier and faster to have the curators manually add a proper definitions to all those terms…

**Comment by shawntanzk** [comment]
@cmungall @dosumis might need help with this

**Comment by cmungall** [comment]
I always thought the dot-definitions in FBbt were placeholders for
literature or some other pointer. Anyway that's what they are in uberon.
Not sure what I can add beyond what I said earlier. If this is priority
then we can just translate to seeAlso or similar

**Comment by matentzn** [comment]
@cmungall the question is, what exactly are they placeholders for? Where is the pipeline that fills them in with actual definitions?

**Comment by gouttegd** [comment]
My understanding is that they are just placeholders waiting to be replaced by an actual definition _by a human editor_. They are not intended to be automatically transformed into something (contrary to what we do in FBbt), they are just here to remind the editors that a real definition will need to be put here sometimes in the future (with the xref giving a clue about where to find the information to create the definition).

**Comment by matentzn** [comment]
Usually they are placeholders for some kind of pattern based replacement strategy. If it is to remind humans, I would vote to ditch them.

**Comment by uberon** [comment]
exactly

**Comment by uberon** [comment]
but keep the relevant information as an annotation of course

**Comment by cmungall** [comment]
grep '^def: "."' uberon-edit.obo


def: "." [GO:dph,
https://sourceforge.net/p/geneontology/ontology-requests/9676/,
Wikipedia:Hypoblast, ZFIN:cvs]
def: "." [Wikipedia:Atlas_(anatomy)#Vertebral_foramen]
def: "." [https://github.com/obophenotype/uberon/issues/6,
https://github.com/obophenotype/uberon/issues/7]
def: "." [Wikipedia:Pronucleus]
def: "." [Wikipedia:Trapezium_(bone)]
def: "." [Wikipedia:Trapezoid_bone]
def: "." [Wikipedia:Capitate_bone]
def: "." [Wikipedia:Hamate_bone]
def: "." [Wikipedia:Iris_muscle]
def: "." [Wikipedia:Facial_skeleton]
def: "." [Wikipedia:Enteric_ganglia]
def: "." [Wikipedia:Gastric_juice]
def: "." [Wikipedia:Common_plantar_digital_arteries]
def: "." [Wikipedia:Node_of_ranvier]
def: "." [Wikipedia:Lumbar_spinal_cord]
def: "." [Wikipedia:Neurofilament]
def: "." [Wikipedia:Intermediate_filament]
def: "." [MP:0009364]
def: "." [MP:0009946]
def: "." [MP:0009988]
def: "." [MP:0009989]
def: "." [MP:0009990]
def: "." [MP:0009993]
def: "." [MP:0009994]
def: "." [MP:0009996]
def: "." [MP:0009997]
def: "." [HP:0000606]
def: "." [HP:0000864]
def: "." [HP:0003350]
def: "." [HP:0003832]
def: "." [HP:0005289]
def: "." [GO:0021751]
def: "." [GO:0003285, Wikipedia:Septum_secondum]
def: "." [GO:0003291]
def: "." [GO:0021729, GO_REF:0000021]
def: "." [Wikipedia:Proper_plantar_digital_arteries]
def: "." [Wikipedia:Brodmann_area_26]
def: "." [https://github.com/obophenotype/uberon/issues/98,
Wikipedia:Articular]
def: "." [Wikipedia:External_sphincter_muscle_of_female_urethra,
Wikipedia:External_sphincter_muscle_of_male_urethra]
def: "." [GO:0003224]
def: "." [GO:0003225]
def: "." [GO:0003226]
def: "." [GO:0003227]
def: "." [GO:0072003]
def: "." [GO:0072165]
def: "." [GO:0072166]
def: "." [Wikipedia:Eparterial_bronchus]
def: "." [GO:0060682]
def: "." [GO:0061214]
def: "." [MP:0009999]
def: "." [
https://sourceforge.net/tracker/?func=detail&aid=3515562&group_id=76834&atid=994726
]
def: "." [http://www.ana.ed.ac.uk/database/humat/notes/extraemb/mesoder.htm]
def: "." [https://github.com/obophenotype/mouse-anatomy-ontology/issues/56]
def: "." [MP:0010002]
def: "." [MP:0010003]
def: "." [BIRNLEX:1732]
def: "." [BIRNLEX:1734]
def: "." [BIRNLEX:1755, https://github.com/obophenotype/uberon/issues/1161]
def: "." [Wikipedia:Dorsal_digital_arteries#]
def: "." [GO:0061249]
def: "." [Wikipedia:Snout]
def: "." [
https://sourceforge.net/tracker/?func=detail&aid=3123600&group_id=76834&atid=1205376,
PMID:14595018]
def: "." [Wikipedia:Brodmann_area_18]
def: "." [Wikipedia:Brodmann_area_39]
def: "." [Wikipedia:Corpus_cavernosum]
def: "." [Wikipedia:Pterion]
def: "." [Wikipedia:Persistent_left_superior_vena_cava]
def: "." [
https://sourceforge.net/tracker/?func=detail&aid=3123598&group_id=76834&atid=1205376
]
def: "." [http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=3220
]
def: "." [http://dev.biologists.org/content/128/22/4573.full]
def: "." [http://retina.anatomy.upenn.edu/~lance/eye/retina_gross.html,
UBERON:CL_meeting_20110725]
def: "." [PMCID:PMC2093943]
def: "." [Wikipedia:Pouch_(marsupial)]
def: "." [Wikipedia:Pancreaticoduodenal_artery]
def: "." [
https://sourceforge.net/tracker/?func=detail&atid=440764&aid=3413098&group_id=36855
]
def: "." [PMID:21558186]
def: "." [PMID:21558186]
def: "." [PMID:21558186]
def: "." [PMID:21558186]
def: "." [Wikipedia:Epicondyle]
def: "." [Wikipedia:Coat_(animal)]
def: "." [Wikipedia:Digestive_system_of_gastropods#Hepatopancreas]
def: "." [GO:0021728]
def: "." [GO:0021729]
def: "." [Wikipedia:Sclera#Histology]
def: "." [http://www.embryology.ch/anglais/turinary/urinhaute03.html]
def: "." [Wikipedia:Adductor_muscles_of_the_hip]
def: "." [http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=3218
]
def: "." [http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=3214
]
def: "." [http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=3221
]
def: "." [http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=3223
]
def: "." [https://github.com/obophenotype/uberon/issues/119]
def: "." [Wikipedia:Anal_gland]
def: "." [Wikipedia:Temporomandibular_joint#Ligaments]
def: "." [http://orcid.org/0000-0002-6601-2165]
def: "." [Wikipedia:Primordial_phallus]
def: "." [Wikipedia:Flight_feather]
def: "." [http://people.eku.edu/ritchisong/feather_evolution.htm]
def: "." [http://people.eku.edu/ritchisong/feather_evolution.htm]
def: "." [Wikipedia:Pisiform_joint]
def: "." [ISBN:0073040584]
def: "." [ISBN:0073040584]
def: "." [ISBN:0073040584]
def: "." [ISBN:0073040584]
def: "." [
https://sourceforge.net/tracker/?func=detail&aid=3580301&group_id=76834&atid=1205376
]
def: "." [Wikipedia:Rattlesnake#Rattle]
def: "." [PMID:20557782, PMID:20566102]
def: "." [PMID:23153189]
def: "." [Wikipedia:Brodmann_area_9]
def: "." [Wikipedia:Brodmann_area_28]
def: "." [EFO:0000240]
def: "." [PMID:23027930]
def: "." [PMID:23027930]
def: "." [Wikipedia:Aquatic_predation#Lunge_feeding]
def: "." [PMID:22622577]
def: "." [PHENOSCAPE:alex]
def: "." [PHENOSCAPE:alex]
def: "." [PHENOSCAPE:Wasila]
def: "."
[Wikipedia:Superior_olivary_complex#Dorsal_periolivary_nucleus_.28DPO.29]
def: "." [Wikipedia:Internal_spermatic_fascia]
def: "." [https://github.com/obophenotype/uberon/issues/1264]
def: "." [FBC:VH]
def: "." [FBC:DOS, FBC:VH]
def: "." [FlyBase:FBrf0007733, FlyBase:FBrf0064792]
def: "." [FlyBase:FBrf0002482, FlyBase:FBrf0007196, FlyBase:FBrf0007735,
FlyBase:FBrf0034076]
def: "." [FBC:VH]
def: "." [FlyBase:FBrf0006943]
def: "." [FBC:DOS, FBC:VH]
def: "." [FBC:VH]
def: "." [FlyBase:FBrf0089570]
def: "." [FBC:DOS, FBC:VH]
def: "." [FBC:VH]
def: "." [FBC:VH]
def: "." [FBC:DOS]
def: "." [FBC:DOS]
def: "." [FBC:DOS]
def: "." [FBC:DOS]
def: "." [
http://purl.obolibrary.org/obo/uberon/docs/Connectivity-Design-Pattern]
def: "." [
http://purl.obolibrary.org/obo/uberon/docs/Connectivity-Design-Pattern]
def: "." [
http://purl.obolibrary.org/obo/uberon/docs/Connectivity-Design-Pattern]


The later ones (6x) are from FBbt itself - there may be newer definitions
in place now.


The phenoscape ones should be replaced by created-by


GO and MP provide some kind of provenance - recall a lot of uberon was
abduced from implicit anatomy ontologies in GO and phenotype ontologies,
and definitions were often taken from these ontologies. In the dot cases
there was nothing in the ontology for a definition. IMO this is useful
metadata in that there is mutual dependency between two ontologies that
relying on "trust" of labels, these should be looked at by humans.


The issues xrefs could be demoted to seeAlso


the wikipedias could be turned to class xrefs but may as well just go
through and add defs quicklly

**Comment by anitacaron** [comment]
I'll check if it was fixed in the new release.

**Comment by shawntanzk** [comment]
There still seems to be some "." defs - eg UBERON_0004133

**Comment by shawntanzk** [comment]
@anitacaron to relook at this

**Comment by anitacaron** [comment]
From the OWL artefacts, this issue is still present only in `uberon-base.owl`,`uberon-full.owl` and `basic.owl` files.

**Comment by shawntanzk** [comment]
the . defs are not in uberon.owl which is good, however, we might need to look into implementing this on -base file if these are going to be used for imports

**Comment by matentzn** [comment]
Can someone figure out where they come from, i.e. from withing uberon-edit.obo? I am assuming these are from some import?

**Comment by shawntanzk** [comment]
just checked uberon-edit.obo - the . defs are there

**Comment by matentzn** [comment]
In an import or the actual file?

**Comment by matentzn** [comment]
ah sorry.. of course.. I am stupid. I meant, the . definitions that are still in uberon-base.owl, are they from uberon-edit or an import?

**Comment by shawntanzk** [comment]
I assume edit file given that I checked UBERON:0004133 and both edit and base file has the . def

**Comment by matentzn** [comment]
ok so it is an @anitacaron issue. Thanks for checking!

**Comment by anitacaron** [comment]
I read Chris' comment carefully and first need to modify `uberon-edit` file before deleting the 'dot definitions'.

- [ ] The phenoscape ones should be replaced by created-by
- [ ] GO and MP provide some kind of provenance
- [ ] The issues xrefs could be demoted to seeAlso
- [ ] the wikipedias could be turned to class xrefs but may as well just go
through and add defs quickly

Also, I checked uberon.Makefile and it seems not taking `uberon-edit.obo`, but `uberon-edit.owl` that is in the temporary folder.

**Comment by matentzn** [comment]
> Also, I checked uberon.Makefile and it seems not taking uberon-edit.obo, but uberon-edit.owl that is in the temporary folder.

tmp/uberon-edit.owl comes from uberon-edit.obo :)

Thanks @anitacaron for the breakdown!

**Comment by anitacaron** [comment]
The `delete-dot-definition` SPARQL query is only used in `tmp/uberon-edit.owl`; that's why they're still in the `uberon-edit.obo` file.

**Comment by matentzn** [comment]
Yeah the question is, how do they end up in uberon-base, or basic.owl? These are all derived from tmp/uberon-edit.owl..

**Comment by anitacaron** [comment]
After look the graph generated from the makefiles, they all came from `uberon-edit.obo` defined on the main Makefile. They're not overridden on `uberon.makefile`.

**Comment by matentzn** [comment]
That is the problem. its also a bit of a general problem with makefiles.. Ideally, we have

- Nothing in the makefile dependent on uberon-edit.obo, except tmp/uberon-edit.owl
- Everything that previously dependent on uberon-edit.obo (`$(SRC)`) now depending on tmp/uberon-edit.owl.

This is going to be hard, but if it works for Uberon, we can generalise this for ODK.

**Comment by matentzn** [comment]
- [ ] Depends on https://github.com/INCATools/ontology-development-kit/issues/544

After this is solved than uberon-base will depend on tmp/uberon-edit and then the dot removal will work.

**Comment by anitacaron** [comment]
We'll have a new ODK release soon that will fix the issue only in the release artefact. The 'dot definitions' will still be present in the edit file.
