### ISSUE TITLE
multiple_equivalent_classes error

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2130]
Checking the report for `sh run.sh make reports/uberon-edit.obo-obo-report.tsv`, the other errors are multiple_equivalent_classes
Here are a few examples of them: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/shawntan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/shawntan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

ERROR | multiple_equivalent_classes | tongue muscle | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid2261
-- | -- | -- | -- | --
ERROR | multiple_equivalent_classes | tongue muscle | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid2265
ERROR | multiple_equivalent_classes | epithelium | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid3006
ERROR | multiple_equivalent_classes | epithelium | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid3010
ERROR | multiple_equivalent_classes | trunk or cervical vertebra | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid39930
ERROR | multiple_equivalent_classes | trunk or cervical vertebra | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid39934
ERROR | multiple_equivalent_classes | cervical vertebra endochondral element | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid79937
ERROR | multiple_equivalent_classes | cervical vertebra endochondral element | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid79941
ERROR | multiple_equivalent_classes | thoracic vertebra endochondral element | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid79948
ERROR | multiple_equivalent_classes | thoracic vertebra endochondral element | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid79952
ERROR | multiple_equivalent_classes | lumbar vertebra endochondral element | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid79959
ERROR | multiple_equivalent_classes | lumbar vertebra endochondral element | owl:equivalentClass | 9ab79cd9-67ba-4234-8df4-ca3f4d8334b1genid79963

</body>

</html>

**Comment by cmungall** [comment]
yes - these are all caused by an additional unonOf eq axiom on top of the defining genus-different eq axiom

**Comment by shawntanzk** [comment]
- [ ] when ROBOT 1.9 is released, reinstate test

**Comment by matentzn** [comment]
@shawntanzk We are ready to try this again I think, no need to wait for  the next ODK.

**Comment by shawntanzk** [comment]
ran `sh run.sh make reports/uberon-edit.obo-obo-report.tsv` and seems the errors are gone: 

```
Violations: 7899
-----------------
ERROR:      0
WARN:       4894
INFO:       3005

First 5 violations:
WARN	duplicate_definition	UBERON:0000089	IAO:0000115	.
WARN	duplicate_definition	UBERON:0000219	IAO:0000115	.
WARN	duplicate_definition	UBERON:0000444	IAO:0000115	.
WARN	duplicate_definition	UBERON:0001430	IAO:0000115	.
WARN	duplicate_definition	UBERON:0001431	IAO:0000115	.
```

I assume that it wont generated the report with no errors?

**Comment by shawntanzk** [comment]
btws related to https://github.com/obophenotype/uberon/issues/2305, heaps of these, a few examples: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/shawntan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/shawntan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



WARN | duplicate_scoped_synonym | UBERON:0034752 | oboInOwl:hasExactSynonym | second auditory area
-- | -- | -- | -- | --
WARN | duplicate_scoped_synonym | UBERON:0034752 | oboInOwl:hasRelatedSynonym | second auditory area
WARN | duplicate_scoped_synonym | UBERON:0034753 | oboInOwl:hasExactSynonym | inferior occipitofrontal fasciculus
WARN | duplicate_scoped_synonym | UBERON:0034753 | oboInOwl:hasRelatedSynonym | inferior occipitofrontal fasciculus
WARN | duplicate_scoped_synonym | UBERON:0034771 | oboInOwl:hasBroadSynonym | commissural nucleus of spinal cord
WARN | duplicate_scoped_synonym | UBERON:0034771 | oboInOwl:hasExactSynonym | commissural nucleus of spinal cord
WARN | duplicate_scoped_synonym | UBERON:0034771 | oboInOwl:hasRelatedSynonym | commissural nucleus of spinal cord
WARN | duplicate_scoped_synonym | UBERON:0034892 | oboInOwl:hasExactSynonym | granular insula
WARN | duplicate_scoped_synonym | UBERON:0034892 | oboInOwl:hasRelatedSynonym | granular insula
WARN | duplicate_scoped_synonym | UBERON:0034893 | oboInOwl:hasExactSynonym | dysgranular insular cortex
WARN | duplicate_scoped_synonym | UBERON:0034893 | oboInOwl:hasRelatedSynonym | dysgranular insular cortex
WARN | duplicate_scoped_synonym | UBERON:0034986 | oboInOwl:hasExactSynonym | plexus sacralis
WARN | duplicate_scoped_synonym | UBERON:0034986 | oboInOwl:hasRelatedSynonym | plexus sacralis
WARN | duplicate_scoped_synonym | UBERON:0034987 | oboInOwl:hasExactSynonym | plexus lumbalis
WARN | duplicate_scoped_synonym | UBERON:0034987 | oboInOwl:hasRelatedSynonym | plexus lumbalis



</body>

</html>
