### ISSUE TITLE
Exempt issue from auto-closing if it is in a project

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2131]
See #2030. 

Can we exempt issues that have been placed into projects? Or at least projects that are still active and have a champion?

**Comment by gouttegd** [comment]
Unfortunately this is not possible for now as the auto-closing action we are using does not have this feature (though [it has been requested](https://github.com/actions/stale/issues/359)).

The best we can do is to decide on a new label (say, `keep-alive`) and to exclude all issues with that label from being marked as stale. But the label would have to be added manually on issues.

**Comment by shawntanzk** [comment]
Thoughts on this: 
I think given how it is super easy to stop items from going stale by adding a comment, and how the system will ping the people involved when it is going stale and give them 6 months to do something about it, there isn't a need for a `keep-alive` label. Worry with the label is that people will add it and forget it and it becomes a forever issue.
