### ISSUE TITLE
ontology IRI for ext is 'materialized'

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#2138]
If you download `http://purl.obolibrary.org/obo/uberon/ext.owl`, the resulting ontology has:

- ontology IRI: `http://purl.obolibrary.org/obo/uberon/materialized.owl`
- version IRI: `http://purl.obolibrary.org/obo/uberon/releases/2021-10-01/ext.owl`

Ontology IRI should be `http://purl.obolibrary.org/obo/uberon/ext.owl`.

**Comment by shawntanzk** [comment]
ext.owl is overwritten in uberon.makefile 
look at uberon.owl creates an ontology and version iri and make sure that ext.owl does in an analogous version

**Comment by shawntanzk** [comment]
Check everything that is listed in release artefact of owl an make sure -O (or --ontology-iri) is set -> ideally with ANNOTATE_ONTOLOGY_VERISION

**Comment by matentzn** [comment]
listen in uberon-odk.yaml

**Comment by matentzn** [comment]
check the following make goals wether they contain `annotate -O` or `annotate --ontology-iri`:

- [ ] ext.owl:
- [ ] basic.owl:
- [ ] merged.owl:
- [ ] core.owl:
- [ ] composite-metazoan.owl:
- [ ] composite-metazoan-basic.owl:
- [ ] composite-vertebrate.owl:
- [ ] composite-vertebrate-basic.owl:
