### ISSUE TITLE
UBERON:3010730 has no label

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2140]
@rays22 to figure out what this is

**Comment by rays22** [comment]
It looks like that `UBERON:3010730 pterygoideus` was an [obsolete class](https://github.com/obophenotype/uberon/issues/1486)
that I re-introduced accidentally in <https://github.com/obophenotype/uberon/pull/2108>.
I will fix it by removing the obsolete class `UBERON:3010730` again.
