### ISSUE TITLE
small intestine capillary

### ISSUE THREAD

**Issue by sfexova** [obophenotype/uberon#2150]
**Preferred term label:**
small intestine capillary

**Synonyms**
capillary of small intestine, blood vessel capillary of small intestine

**Definition (free text, please give PubMed ID)**
Capillary that is part of small intestine.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
capillary http://purl.obolibrary.org/obo/UBERON_0001982
small intestine http://purl.obolibrary.org/obo/UBERON_0002108

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
The related terms I added for SCA follow the naming pattern 'capillary of X' rather than 'X capillary' ('capillary of anorectum', 'capillary of colon'). Shall I do the same for 'capillary of small intestine', and keep the proposed 'small intestine capillary' as an exact synonym?

**Comment by sfexova** [comment]
Hi @paolaroncaglia - yes, I was wondering about that myself, actually. I went with this style in the end because there's 'small intestine venule' and 'small intestine arteriole' etc (rather than venule/arteriole _of_ small intestine like we have for colon and the rest) but I'm happy to change the name if you think that's better. Makes sense to have at least all the capillaries follow the same pattern:)

**Comment by paolaroncaglia** [comment]
Yes, I'd keep the capillary term labels consistent with the ones already in CL. I do appreciate that different naming patterns are used across CL and Uberon, but I think we can live with that. :-) I'll update the ticket when done.

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
The new term is UBERON:8410068 capillary of small intestine.
I'm not sure when the next Uberon release containing this term will be - I'd expect after the holidays now.
