### ISSUE TITLE
Unnamed orphan classes

### ISSUE THREAD

**Issue by janelomax** [obophenotype/uberon#2151]
**Uberon term**

**Bug description**

Latest release 2021-10-01 has a bunch of unnamed orphan classes. From OLS:

<img width="1305" alt="Screenshot 2021-11-05 at 13 45 10" src="https://user-images.githubusercontent.com/6639811/140520302-810993d1-6235-4d3e-8e2c-cf74baf899b7.png">

**Comment by paolaroncaglia** [comment]
Hi @janelomax ,

Thanks for reporting. This is a known issue and some of my Uberon colleagues have been working on it, but there are still a few loose ends (the Uberon pipeline and release processes are not exactly a walk in the park, ehm). #1963  is the relevant ticket, I'll ask if there's any update there. I'll close this ticket as a duplicate, please feel free to subscribe to #1963 if you'd like to receive update notifications (or feel free to ask me directly). 

Cheers,
Paola
