### ISSUE TITLE
[NTR] anterior ectoderm anlage

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2154]
uberon currently has a floating term from FBbt: 
http://www.ontobee.org/ontology/FBbt?iri=http://purl.obolibrary.org/obo/FBbt_01000119

It is currently use in:
'clypeo-labral anlage in statu nascendi' part of FBbt 01000119

If this is right, this term needs to be naturalised into uberon 

@gouttegd hope it's alright if I assign you, happy for you to reassign to someone else from the fly world - i have zero idea on fly stuff so can't help much here >.<

**Comment by gouttegd** [comment]
@shawntanzk No problem with leaving the fly stuff to me. No promise on how fast I will deal with it, however! :D
