### ISSUE TITLE
Remove all axioms that reference GO:excretion

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2165]
GO is obsoleting excretion

https://github.com/geneontology/go-ontology/issues/22368

Related issues:

 * Alliance wants a general "excretory system" that spans all organisms: #1450

**Comment by shawntanzk** [comment]
@anitacaron - could you help bring this up in tech call (I've placed it on the board, just wont be around for the next meetings and all)

**Comment by gouttegd** [comment]
`GO:excretion` is referenced by three terms in Uberon:

* `excreta`, defined as `'organism substance' and (output_of some excretion)`
* `excreted gas`, defined as `'bodily gas' and (output_of some excretion)`
* `renal system`, defined as `organ system and (capable_of some excretion)`

The last one is the most problematic in my opinion as `excretion` in GO has a definition that goes beyond what is normally performed by the renal system (for example, it encompasses defecation). Suggestion here is to update the definition of `renal system` to `organ system and (capable_of some 'renal tubular secretion')`, where `renal tubular secretion` is a subclass of `excretion`.

As for `excreta` and `excreted gas`, not sure we can as easily replace `excretion` in their definitions by a more precise subclass. Both terms are (purposefully, I assume) broadly defined to encompass several types of excretions. Given that GO has decided not to obsolete `excretion` in the end, I would be inclined to keep those references as they are.

**Comment by gouttegd** [comment]
Of note, if we implemented my suggestion above (redefining `renal system` to `organ system and (capable_of some 'renal tubular secretion')`), then we probably also should create a higher-level `excretory system` to encompass all excretory stuff (not limited to kidneys and kidney-like), as requested in #1450.

There are at least one instance where `renal system` is currently used as if it referred to a generic “excretory system”: `excretory gland` is currently `part_of some 'renal system'`, even though the text definition of `excretory gland` does not tie it to the renal system at all (on the contrary, it gives “lacrimal gland” as an example of an excretory gland).
