### ISSUE TITLE
Double specification of CNS-PNS disjointness

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#2174]
Uberon considers that the `central nervous system` and the `peripheral nervous system` are spatially disjoint, that is nothing can be simultaneously part of both the CNS and the PNS.

This “disjointness” is expressed at two different places using two different mechanisms:

* There is a general class axiom `'part of' some 'peripheral nervous system' DisjointWith 'part of' some 'central nervous system'`. This axiom is stored in the file `src/ontology/components/disjoint_union_over.ofn`, which is merged with the main ontology at the very beginning of the pipeline, when generating `src/ontology/tmp/uberon-edit.owl` from the edit file.
* There is also an annotation `mutually_spatially_disjoint_with` carried by the term `peripheral nervous system` in the main edit file: `'peripheral nervous system' mutually_spatially_disjoint_with 'central nervous system'`. When generating the `src/ontology/tmp/uberon-edit.owl` file from the edit file, that annotation is expanded (using `owltools --expand-macros`) into the equivalence axiom `owl:Nothing EquivalentTo ('part of' some 'peripheral nervous system') and ('part of' some 'central nervous system')`.

My understanding is that these two mechanisms have _in fine_ the same result, so what is the rationale for having both?

Can we remove one of them? If so, any reason to prefer the `DisjointWith` general class axiom over the “equivalence-to-nothing” axiom, or the other way round?

**Comment by dosumis** [comment]
Decision - delete AP version.
