### ISSUE TITLE
Set preferred roots Uberon

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2180]
See for example mondo

https://github.com/monarch-initiative/mondo/blob/master/src/ontology/mondo-edit.obo

This is an annotation to the ontology itself.

IAO:0000700

**Comment by shawntanzk** [comment]
Root nodes: 
life cycle
anatomical entity

**Comment by shawntanzk** [comment]
Look into https://github.com/EBISPOT/OLS/issues/502 while at it

**Comment by shawntanzk** [comment]
documentation wise happy to add, but would like to know if it is just adding `property_value: IAO:0000700 UBERON:XXXXXXX` in -edit file and it will solve itself out in release? or what else is needed etc
