### ISSUE TITLE
Some terms have disappeared after simplifying subsets

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2192]
In our latest attempt to create slims, I noticed the following classes disappearing:

Is it ok if these disappear from the euarchontoglires and other subsets?

```
http://purl.bioontology.org/ontology/provisional/1ddd2e2d-2ace-4c87-8ec6-d3b5730b3e7c
.. and 17 more like the above
http://purl.obolibrary.org/obo/BSPOTEMP_58938a8e-359c-49d8-b3f7-5e1fd7e1a109
http://purl.obolibrary.org/obo/EHDAA2_0003079
.. and 10 more like the above
http://purl.obolibrary.org/obo/EMAPA_16647
http://purl.obolibrary.org/obo/UBERON#_Commissure-MA_0002723
http://purl.obolibrary.org/obo/UBERON#_Declive-MA_0001003
http://purl.obolibrary.org/obo/UBERON#_FBbt_00004970
http://purl.obolibrary.org/obo/UBERON#_FBbt_00005386
http://purl.obolibrary.org/obo/UBERON#_Flocculus-MA_0000992
http://purl.obolibrary.org/obo/UBERON#_MIAA_0000021
http://purl.obolibrary.org/obo/UBERON#_WBbt_0005755
http://purl.obolibrary.org/obo/UBERONTEMP_000a0d60-aa06-477d-936c-ba14ac4f0c2d
.. and 10 more like the above
http://purl.obolibrary.org/obo/ZFA_0005228
```

**Comment by dosumis** [comment]
I think only Chris could usefully comment on this.  I have no idea what most of these term are (apart from EMPA and ZFA) or why they woud be in a subset file.  I certainly wouldn't expect them in a -simple release.

**Comment by paolaroncaglia** [comment]
Same here. Thanks @matentzn and @dosumis - 
and @cmungall thanks in advance for when you'll have a chance to comment.

**Comment by matentzn** [comment]
Ok, as it turns out, these are all correctly obsoleted terms. They are included as obsoleted in uberon.owl, but not in the subsets, because they are not included in the simple files due to their idiosyncratic IRI structure. I am ok with this..
