### ISSUE TITLE
Taxon reporting pipeline

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2198]
We want to inform curators about the consequences of adding taxon constraints. 

- [ ] generate a report that looks at the difference between a number of key subsets (human-view, euroglires-basic, mouse-view, potentially more, i.e. configurable). The report should just be class ID and label. In other words: a list should be produced with ID, label pairs indicating which classes are being excluded as a consequence of the current edit. The diff should be between the _version of uberon-edit.obo on master_ and the version of _uberon-edit.obo on the branch_ that performs the taxon constraint.
- [ ] When a user creates a pull request that changes taxon constraints (or for now, edits uberon-edit.obo) generate the reports and concat them into one file. If the file is not empty, paste a comment on the pull request with the report (i.e. the affected classes).

**Comment by shawntanzk** [comment]
@rays22 to make smaller test file for @ubyndr to test on a branch

**Comment by rays22** [comment]
@ubyndr ,
I have created two test files using [robot](https://oboacademy.github.io/obook/tutorial/robot_tutorial_1/) that differ only in taxon constraints. They could be used to generate the list of class IDs and labels that are excluded for the human-specific view.
1. [`test-master.obo`](https://raw.githubusercontent.com/obophenotype/uberon/issue2198t/src/ontology/test-master.obo) : This file is the mock 'master' version.
2. [`test-branch.obo`](https://raw.githubusercontent.com/obophenotype/uberon/issue2198t/src/ontology/test-branch.obo) : This is the edited ontology file that has one additional taxon restriction `property_value: never_in_taxon "Euarchontoglires" xsd:string` for term UBERON:0000022 (label: feather).

You can use them to test full versus human-views.
