### ISSUE TITLE
is 'zona limitans intrathalamica' really non-material?

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#2214]
[zona limitans intrathalamica](http://purl.obolibrary.org/obo/UBERON_0009848) is defined as:

```
'anatomical line'
 and ('adjacent to' some 'ventral thalamus')
 and ('adjacent to' some 'dorsal thalamus')
```

However GO is using this term in a way that requires it to be a material structure: [zona limitans intrathalamica formation](http://purl.obolibrary.org/obo/GO_0022006), and is causing a property range violation.

It doesn't sound immaterial [in Wikipedia](https://en.wikipedia.org/wiki/Zona_limitans_intrathalamica). Maybe this should be an [anatomical junction](http://purl.obolibrary.org/obo/UBERON_0007651) or [anatomical border](http://purl.obolibrary.org/obo/UBERON_0036304)?

Related to https://github.com/geneontology/go-ontology/issues/22537 and https://github.com/geneontology/go-ontology/issues/16524

**Comment by cmungall** [comment]
_A narrow stripe of cells that lies between the prospective dorsal and ventral thalami. This boundary contains signals that pattern the prethalamic and thalamic territories of the future mid-diencephalon_

definitely not immaterial!

Go with junction. Border has only one subclass which is suspect. But the immediate priority is making this material
