### ISSUE TITLE
material structures needed to replace anatomical space fillers in GO logical definitions

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#2218]
I'm trying to resolve all [reasoning violations in GO](https://github.com/geneontology/go-ontology/issues/16524) resulting from property range axioms. The remaining issues have to do with anatomical spaces used as targets of [results in development of](http://purl.obolibrary.org/obo/RO_0002296). Here are the GO terms and Uberon terms used:

- [ ] [subarachnoid space development](http://purl.obolibrary.org/obo/GO_1903374) | [subarachnoid space](http://purl.obolibrary.org/obo/UBERON_0000315)
- [ ] [tube lumen cavitation](http://purl.obolibrary.org/obo/GO_0060605) | [tube lumen](http://purl.obolibrary.org/obo/UBERON_0005082)
- [ ] [neural rod cavitation](http://purl.obolibrary.org/obo/GO_0014024) | [neural tube lumen](http://purl.obolibrary.org/obo/UBERON_0003842)
- [ ] [pronephric sinus development](http://purl.obolibrary.org/obo/GO_0039012) | [pronephric sinus](http://purl.obolibrary.org/obo/UBERON_0006174)

I would appreciate any suggestions for what to do about these.

Related: #2214, #2215

**Comment by shawntanzk** [comment]
@balhoff - has this ticket been addressed with the GO ticket? or is it something we need to look into for a proper fix?

**Comment by balhoff** [comment]
We do still need to address this. I took a look, and we're only avoiding unsatisfiable classes at the moment due to a lack of connections from Uberon into CARO and BFO (at least what we have imported into GO).

**Comment by bvarner-ebi** [comment]
Initial thoughts from @addiehl: need to address property range problems. How are spaces handled as material, anatomical entities? May be a relations ontology issue, not something that can be solved just in Uberon.

**Comment by cmungall** [comment]
We should revise

- whether these are truly immaterial or material
- if immaterial, make material counterparts/shadows for each, and use these in GO
- place these under the new "gross anatomical part" term

**Comment by pgaudet** [comment]
Just noting that the issues have been resolved in GO; is this still needed?

**Comment by cmungall** [comment]
I don't think the issues were fully resolved, but the main issue is with the pronephric sinus, see #2274
