### ISSUE TITLE
needs to harmonize 'parvicellular' and 'parvocellular' terms

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#2224]
Hello,

both terms ('parvicellular' and 'parvocellular)' are used in Uberon class names, and I guess, there is none biological reason to make a difference, 'parvocellular' sounds to be the correct one, see https://en.wikipedia.org/wiki/Parvocellular_cell

UBERON:2002219 parvocellular preoptic nucleus

UBERON:0002938 parvocellular part of red nucleus

---> https://en.wikipedia.org/wiki/Parvocellular_red_nucleus)

UBERON:0002654 parvicellular part of medial dorsal nucleus

UBERON:0002937 parvicellular part of ventral anterior nucleus

**Comment by paolaroncaglia** [comment]
Hi @ANiknejad ,

Thanks for bringing this up. Both "parvocellular" and "parvicellular" come from the Latin "parvus" (small) and are equally valid variants, but the former is found nearly 5 times more often than the latter in PubMed. I would suggest to

- [ ] Look at all Uberon classes whose label contain "parvo" or "parvi" (there are 11 and 8 now, respectively)
- [ ] Have all primary labels conform to "parvo"
- [ ] Keep or add the "parvi" variant as an exact synonym 
- [ ] As parvocellular cells are types of neurons, @shawntanzk @dosumis or others please feel free to comment if you object to any of the above based on literature/community usage. Thanks.
