### ISSUE TITLE
Please revise UBERON:0001850 lacrimal drainage system

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/uberon#2225]
UBERON:0001850 lacrimal drainage system
has an editor note "TODO - resolve lacrimal canaliculus vs larcimal duct"
please see https://github.com/obophenotype/cell-ontology/issues/1392 for implications/consequences in CL too. Thanks!

**Comment by anitacaron** [comment]
@bvarner-ebi, could you have a look into this, please? 😄

**Comment by bvarner-ebi** [comment]
Below are some notes and proposed edits.
CC @cmungall who is a dbxref for the text definitions of some of the terms noted below.

### Synonyms
- "lacrimal duct" is a related synonym of 'lacrimal drainage system'. 
**Agree, no change.**
Of note, the definition of synonym dbxref [FMA:61063 ‘Lacrimal duct’](http://purl.obolibrary.org/obo/FMA_61063) seems to exclude excretory lacrimal ducts, which aligns with the definitions of ‘lacrimal canaliculus’ and ‘nasolacrimal duct’.

- [ ] Add "lacrimal duct" as a **related synonym** of '[lacrimal canaliculus](http://purl.obolibrary.org/obo/UBERON_0001770)';
dbxrefs:
[ISBN:1587341026](https://duckduckgo.com/?q=ISBN%3A1587341026&t=osx&ia=web);
https://www.bartleby.com/lit-hub/anatomy-of-the-human-body/fig-896/

-  [ ]  Add "lacrimal duct" as a **related synonym** of '[nasolacrimal duct](http://purl.obolibrary.org/obo/UBERON_0002392)'; 
dbxref:
PMID:[30285382](https://pubmed.ncbi.nlm.nih.gov/30285382)

### Definitions
- CL:1000433 '[epithelial cell of lacrimal canaliculus](http://purl.obolibrary.org/obo/CL_1000433)'
 Equivalent to  `epithelial cell and part of some lacrimal canaliculus`
**Agree, no change.**

- CL:1000435 '[epithelial cell of lacrimal duct](http://purl.obolibrary.org/obo/CL_1000435)'
 Equivalent to  `non-branched duct epithelial cell and part of some lacrimal drainage system`
 **Proposed changes:**
 
 - [ ] Relabel 'epithelial cell of lacrimal duct' to 'epithelial cell of lacrimal drainage system'
 - [ ] Add "epithelial cell of lacrimal duct” (the current label) as a related synonym.
 - [ ] Change logical defintion to:
 Equivalent to  `‘duct epithelial cell’ and part of some 'lacrimal drainage system'`

### Miscellaneous
- [ ] Remove editor note from 'lacrimal drainage system' and 'lacrimal canaliculus'
 
- Consider obsoleting the following and move current classes under 'duct epithelial cell':

‘[branched duct epithelial cell](http://purl.obolibrary.org/obo/CL_0000069)’
‘[non-branched duct epithelial cell](http://purl.obolibrary.org/obo/CL_0000072)’

- Consider adding new Uberon term 'excretory lacrimal duct'

**Comment by dosumis** [comment]
@paola-scibite  - could you comment on @bvarner-ebi 's comment?

**Comment by dosumis** [comment]
CC @cmungall

**Comment by cmungall** [comment]
I agree with @bvarner-ebi's proposed changes

**Comment by paola-scibite** [comment]
Thank you @bvarner-ebi , @dosumis and @cmungall . The proposed changes sound good to me too. Best wishes!

**Comment by bvarner-ebi** [comment]
Edits addressed in this issue:

- [x] Add "lacrimal duct" as a **related synonym** of '[lacrimal canaliculus](http://purl.obolibrary.org/obo/UBERON_0001770)';
dbxrefs:
[ISBN:1587341026](https://duckduckgo.com/?q=ISBN%3A1587341026&t=osx&ia=web);
https://www.bartleby.com/lit-hub/anatomy-of-the-human-body/fig-896/

-  [x]  Add "lacrimal duct" as a **related synonym** of '[nasolacrimal duct](http://purl.obolibrary.org/obo/UBERON_0002392)'; 
dbxref:
PMID:[30285382](https://pubmed.ncbi.nlm.nih.gov/30285382)

- [x] Remove editor note from 'lacrimal drainage system' and 'lacrimal canaliculus'
 

- **CL edits to be addressed in cell-ontology.**
- **Deeper review to be addressed in separate Uberon issue.**
