### ISSUE TITLE
mediodorsal thalamus parts, missing term 'MDM (medial part) of Mediodorsal thalamic nucleus' ?

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#2229]
Hi Uberon Team,

Happy New Year to All of You!

Here a recent paper with mediodorsal thalamus (MD) subdivisions (medial, central, and lateral):
https://pubmed.ncbi.nlm.nih.gov/34184265/

So far in Uberon we have:

MDC (central part) -> UBERON:0035113 central part of mediodorsal nucleus of the thalamus
MDL (lateral part) -> UBERON:0035114 lateral part of mediodorsal nucleus of the thalamus
but none MDM medial part of mediodorsal nucleus of the thalamus

However it exists 

UBERON:0002647 magnocellular part of medial dorsal nucleus
with synonym: "MDM" BROAD ABBREVIATION [BIRNLEX:1262, NIFSTD:NeuroNames_abbrevSource]

https://scicrunch.org/scicrunch/interlex/view/ilx_0106473

I am wondering if UBERON:0002647 can indeed be considered as the class describing MDM (medial part) of Mediodorsal thalamic nucleus ? or if there is a misunderstanding about the 'm', for 'medial' or 'magnocellular'?

If UBERON:0002647 does not describe the medial part of the mediodorsal nucleus of the thalamus, we then need a new class as below:

**Preferred term label: medial part of mediodorsal nucleus of the thalamus**

**synonym: "mediodorsal nucleus of the thalamus, medial part"**

**Definition to be retrieved from PMID: 34184265

**relationship: part_of UBERON:0002739 ! medial dorsal nucleus of thalamus**

https://orcid.org/0000-0003-3308-6245

Thank you in advance for your feedback,
Cheers,

Anne

**Comment by shawntanzk** [comment]
@nicolevasilevsky given this is brain related, happy to look into it, you can remove yourself from assignee if you want :) thanks

**Comment by nicolevasilevsky** [comment]
great, thanks @shawntanzk!

**Comment by shawntanzk** [comment]
Looks like you are right - I've just checked cross-reference for the Allen Mouse Brain Atlas and it points to "mediodorsal nucleus of the thalamus, medial part". I see that the cross-reference to Human Brain Atlas is to "mediodorsal nucleus of the thalamus, left, magnocellular division" - wonder if its a whole human vs mouse thing? In which case  @patrick-lloyd-ray might be able to weight in. Should we add medial part of mediodorsal nucleus of the thalamus as a Exact or Broad synonym?

**Comment by patrick-lloyd-ray** [comment]
For mouse: 'magnocellular part of medial dorsal nucleus' and 'medial part of mediodorsal nucleus of the thalamus' (MDm) are the same according to MBA. Quick check outside of Allen MBA with Paxinos and Watson confirms this. So, I think it's safe to make them exact synonyms for rodents in UBERON.
<img width="481" alt="Screen Shot 2022-08-02 at 2 41 30 PM" src="https://user-images.githubusercontent.com/67486986/182677564-a448a5bf-98cf-40ca-8ad3-b893f9342b1a.png">
It's slightly different in humans according to the Allen atlases: in HBA, the mediodorsal nucleus of thalamus has 'magnocellular (medial) division of MD' (MDm). HBA also parcellates MDm further into 'central part of medial subdivision of MD' (MDmc) in HBA. 
<img width="607" alt="Screen Shot 2022-08-03 at 11 02 59 AM" src="https://user-images.githubusercontent.com/67486986/182677756-bcdded93-e820-472d-b34e-b25862153b2e.png">
<img width="458" alt="Screen Shot 2022-08-03 at 11 03 06 AM" src="https://user-images.githubusercontent.com/67486986/182677771-24338904-576b-4d2c-894f-06259fc15590.png">
However, lots of people use the abbreviation 'MDmc' (in human neuroanatomy) to refer to 'magnocellular division of MD'. This is the case here (https://doi.org/10.3389/fnsys.2013.00037) and here (https://doi.org/10.1016/j.neubiorev.2015.03.001) and here (https://doi.org/10.3390/brainsci10090624). In those papers, they confirm that the closest equivalent human structure to magnocellular part of medial dorsal nucleus/MDm in rodents is the magnocellular division of MD (MDm in HBA, MDmc in others). 

So, I think it's safe to add medial part of mediodorsal nucleus of the thalamus as exact. Also, I don't think it would be confusing to list MDm/MDM/MDmc as acronyms of (UBERON:0002647). As far as I know, there is no corresponding UBERON term for the HBA 'central part of medial subdivision of MD' and it looks like it's just a difference in granularity, not disagreement.

**Comment by shawntanzk** [comment]
Will add it as exact synonym and put the source as MBA :) Thanks @patrick-lloyd-ray 

Also weird thing on this term - it seems it has its exact label as related synonym too lol: 

![Screenshot 2022-08-04 at 09 41 54](https://user-images.githubusercontent.com/76212760/182803821-1768c09d-8d35-4956-8c70-1cbcf8424360.png)

**Comment by patrick-lloyd-ray** [comment]
> it has its exact label as related synonym too lol

I guess being self-identical makes it related, haha.
