### ISSUE TITLE
'glomerular visceral epithelium' should be part of (or merged with) glomerular visceral layer

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#2230]
'glomerular visceral epithelium' currently has no definition.

The only reason I can see to keep both terms would be if we need to include basement membrane as part of the layer but not part of the epithelium, however, the basement membrane is currently separate and appears to be a composite structure coming from visceral epithelium and underlying endothelium, so probably not:

https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0005777

**Comment by paolaroncaglia** [comment]
> 'glomerular visceral epithelium' currently has no definition.
> 
> The only reason I can see to keep both terms would be if we need to include basement membrane as part of the layer but not part of the epithelium, however, the basement membrane is currently separate and appears to be a composite structure coming from visceral epithelium and underlying endothelium, so probably not:
> 
> https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0005777

I've looked at several images and I'm still not sure. I agree that the basement membrane is currently not included in the glomerular visceral epithelium (UBERON:0005751 'visceral layer of glomerular capsule' is defined as "...Lies just above the thickened glomerular basement membrane..."). @RDruzinsky please, your feedback on this would be greatly appreciated, thank you in advance!

**Comment by paolaroncaglia** [comment]
Discussed at Uberon call today. @emquardokus will email 2 experts (thank you).

**Comment by paolaroncaglia** [comment]
Also, @bvarner-ebi who's been looking at the related CL tickets might comment at a later time. Thank you.

**Comment by bvarner-ebi** [comment]
I will take a closer look at PMID:22410250 and add feedback...

**Comment by bvarner-ebi** [comment]
**Preface**
GBM = glomerular basement membrane
Assumption: UBERON:0005751 ‘visceral layer of glomerular capsule’ = glomerular visceral layer --_please advise if this assumption is not correct_ 

Some visualisations illustrating the distinct structures:

PMID:22410250, the glomerular filtration barrier is composed of: endothelium, GBM and podocyte.￼
![image](https://user-images.githubusercontent.com/95643797/151018022-790b8db6-999e-4c2b-b932-286ba36371e5.jpeg)

Diagram from DOI:10.1016/j.krcp.2012.04.323:
![image](https://user-images.githubusercontent.com/95643797/151017992-96838ebb-902c-4f20-977e-f937082b67a6.jpeg)

**Findings**
The current text definition of UBERON:0005751 ‘visceral layer of glomerular capsule’, states this layer ‘lies above the thickened GBM and is made of podocytes’. 
However, it has SubClass Of axiom: (‘has part’ some ‘basement membrane of epithelium’). I don’t see a source that supports that axiom, and it contradicts the text definition. Of note, UBERON:0006852 ‘glomerular visceral epithelium’ also has the same axiom, also potentially unjustified.

I have not found any reference that groups the GBM with the visceral epithelium. 
I have only found the visceral epithelium to be associated with podocytes (e.g., from https://www.sciencedirect.com/science/article/pii/B9780323357753000114#s0025:
Visceral epithelium (of Bowman's capsule)—The layer of podocytes that closely surround the capillaries of the glomerular tuft, making up part of the glomerular filtration barrier)

UBERON:0006852 ‘glomerular visceral epithelium’ has related synonym ‘podocyte layer’.

**Proposed Solution - to confirm with @emquardokus’ contacts**
[ ] Remove (‘has part’ some ‘basement membrane of epithelium’) from UBERON:0005751 ‘visceral layer of glomerular capsule and UBERON:0005751 ‘visceral layer of glomerular capsule’ 

[ ] Merge UBERON:0005751 ‘visceral layer of glomerular capsule’ with UBERON:0006852 ‘glomerular visceral epithelium’, setting ‘glomerular visceral epithelium’ as an exact synonym (or vice versa)

[ ] Obsolete the subsumed term

[ ] Consider adding term for 'glomerular filtration barrier'

**Comment by paolaroncaglia** [comment]
@bvarner-ebi thank you!
@emquardokus could you please email the experts and run Bradley's proposal by them? I saw that one of them replied to your other query. Thank you.

**Comment by bvarner-ebi** [comment]
Hi, @emquardokus, checking in to see if your SME contacts provided feedback on the proposal detailed above. Thank you.

**Comment by dosumis** [comment]
Discussed on call.  We agreed that expert input not needed.  Bradley's solution is good.  We can hold off on adding 'glomerular filtration barrier' unless/until it is needed.

**Comment by emquardokus** [comment]
Glomerular filtration barrier definition: "These three structures—the fenestrated endothelium, glomerular basement membrane, and glomerular epithelium—are the glomerular filtration barrier." "Each glomerular capillary loop forms a glomerular filtration barrier (GFB) comprising the glycocalyx and fenestrated glomerular endothelial cells (GECs), which block negatively charged molecules and plasma proteins; the glomerular basement membrane (GBM), which provides a physical scaffold that supports the GECs and podocytes, but contributes little directly to GFB function; and podocytes, which form primary, secondary and tertiary (foot) processes." See Daehn, I.S., Duffield, J.S. The glomerular filtration barrier: a structural target for novel kidney therapies. Nat Rev Drug Discov 20, 770–788 (2021). https://doi.org/10.1038/s41573-021-00242-0

**Comment by bvarner-ebi** [comment]
Thanks, all, for the feedback! I will work on this as soon as I have an Uberon idrange (I will request this).

Solution:

[ ] Merge UBERON:0005751 ‘visceral layer of glomerular capsule’ with UBERON:0006852 ‘glomerular visceral epithelium’, obsoleting the former and keeping the latter

[ ] Add ‘visceral layer of glomerular capsule’ as an exact synonym.

[ ] Remove (‘has part’ some ‘basement membrane of epithelium’) from UBERON:0006852 ‘glomerular visceral epithelium’

[ ] Obsolete UBERON:0005751 ‘visceral layer of glomerular capsule’

[ ] Do not add new term 'glomerular filtration barrier' until a use case exists.

**Comment by paolaroncaglia** [comment]
@bvarner-ebi thanks for addressing this. FYI, I think strictly speaking you don't need a Uberon ID range for the edits you propose (as they don't include creation of new terms). :-)

**Comment by bvarner-ebi** [comment]
Thank you, @paolaroncaglia. That makes sense! I still put in a request, but as noted, an idrange is not needed for these edits :)
