### ISSUE TITLE
surface structure is an asserted parent of cornea - coming from imports

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/uberon#2240]
surface structure is an asserted parent of cornea but this has been removed as an asserted parent in https://github.com/monarch-initiative/mondo/issues/542. This assertion is coming from the NBO and PATO import.

This is causing an issue in Mondo: https://github.com/monarch-initiative/mondo/issues/542

Thanks!

**Comment by matentzn** [comment]
Not sure I understand - how is this an uberon issue if it comes from the PATO import? Is PATO simply out of sync with uberon? If this issue is still not fixed Uberon, you could simply fix it yourself!

**Comment by nicolevasilevsky** [comment]
Not sure - there are two asserted superclasses, one from NBO and one from PATO.
Can I refresh the PATO and NBO imports?

Otherwise, how do I fix it myself?

Thanks! :)

![image](https://user-images.githubusercontent.com/6722114/150410460-a9754f96-aa10-4e81-89f0-1b96ddb06f5e.png)

**Comment by matentzn** [comment]
Try doing a PATO release, and review wether the offending change gets removed. If it does, you can do the same for NBO - this needs to get a release anyways.. I am there to advice but I will try not do the actual work anymore - not because I am lazy (you know I love this stuff) but because I need to make myself redundant!

**Comment by nicolevasilevsky** [comment]
sure, I'll try to run a PATO release now :)

**Comment by nicolevasilevsky** [comment]
actually, looking into it further - PATO has been release since this issue has come up and it looks like it is not fixed:
https://github.com/pato-ontology/pato

**Comment by matentzn** [comment]
Did you check if PATO.owl has the offending axiom? If not, maybe you have to refresh the PATO import in Mondo?

**Comment by nicolevasilevsky** [comment]
![image](https://user-images.githubusercontent.com/6722114/150419853-46798d79-7b68-4368-8dfa-7383dd57167c.png)

I think this is an issue in PATO

Should I remove this assertion in PATO, then do a release?

**Comment by balhoff** [comment]
@nicolevasilevsky you are looking at a very old PATO. I don't see that in the current release. I do see this in NBO, which probably needs it's Uberon import refreshed.

**Comment by nicolevasilevsky** [comment]
Ah, okay, I'll try to do that. Thanks @balhoff!

**Comment by nicolevasilevsky** [comment]
<img width="1792" alt="Screen Shot 2022-01-20 at 1 06 02 PM" src="https://user-images.githubusercontent.com/6722114/150422259-017c582c-d84f-47aa-b57a-b45017fb174d.png">

I updated the Uberon import but I still see surface structure asserted in NBO

**Comment by balhoff** [comment]
It's coming back into Uberon via its own pato and nbo imports. I guess that's exactly what you started off saying here. Sorry! We need base files. 🥴

**Comment by nicolevasilevsky** [comment]
Is there anything I can do to help? I assume the need for base files is on the radar?

**Comment by balhoff** [comment]
It's a self-perpetuating axiom that lives entirely within a recursive import circle. I think a good place to start would be to change the Uberon build to at least filter external axioms from the PATO and NBO downloads, using something like this: https://github.com/INCATools/ubergraph/blob/a27eda415f2379ffdcdc563feaa466c0e3a16830/Makefile#L19-L25

**Comment by nicolevasilevsky** [comment]
@balhoff or @matentzn could either of you help me with this? thank you!

**Comment by nicolevasilevsky** [comment]
we discussed this on the Uberon call on 01/24/22.

This may be a makefile issue for Uberon.

once the NBO base file is added per https://github.com/obo-behavior/behavior-ontology/issues/117, we then need to change the makefile configuration in Uberon such as the NBO and PATO base files are used to make the imports in Uberon.

**Comment by matentzn** [comment]
This issue will be solved by moving Uberon to base. Priority.

**Comment by shawntanzk** [comment]
@nicolevasilevsky - I'm going to close this ticket (given we moved nbo and pato to base file). We will make a UBERON release this week. If there is still any issue, please reopen. Thanks!
