### ISSUE TITLE
Question: how should unspecified anatomical terms be provided in Cellosaurus

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2242]
Relaying a Q from Amos, before imposing my own view just putting this up for consensus, how should cellosaurus indicate in a cell line record where the anatomy is unspecified:

 * 😆   Add a new term "unspecified anatomical entity"
 * 🚀 Use the root term "anatomical entity" or "material anatomical entity"
 * 👀  recommend a separate vocabulary of unknown values and recommend an additional field in cellosaurus

**Comment by addiehl** [comment]
Use the term 'material anatomical entity' and some type of annotation (comment or editor's note or specialized annotation property) that indicates the anatomical sources is unknown.
