### ISSUE TITLE
Many taxon restrictions are in xsd:string instead of a relation

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2259]
eg
property_value: present_in_taxon "Homo sapiens" xsd:string 

A couple of things we should do: 
1) @shawntanzk will replaces all these with the appropriate 
`relationship: present_in_taxon NCBITaxon_9606! Homo sapiens`
2) we should have a SPARQL check written up to disallow 
property_value: present_in_taxon
property_value: only_in_taxon
property_value: never_in_taxon
property_value: ambiguous_for_taxon
property_value: dubious_for_taxon
property_value: in_taxon
(happy to give a go at this - would like to starting learning how to do this stuff anyway, but might take a bit longer and would REALLY need checks when I try it) 

@dosumis - could you let me know if there are any other taxon stuff that should be added to point 2?

**Comment by anitacaron** [comment]
Closing because #2241 and #2260 were merged.
