### ISSUE TITLE
Uberon BASE is not a true BASE

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2263]
The Uberon base file contains external axioms. Something is wrong with the makefile, my suspicion it it has the to with some import merging step somewhere.

Please fix this before the next release.

**Comment by anitacaron** [comment]
The Makefile seems good. It's getting directly from `uberon-edit.obo` and the FBbt mapping. No other override in `uberon.Makefile`.

<img width="1150" alt="Screenshot 2022-02-04 at 16 28 25" src="https://user-images.githubusercontent.com/2208124/152565913-3b6777b4-e217-436a-87d8-e035a2fc3015.png">

Do you know which external axiom was found?

**Comment by matentzn** [comment]
If you open uberon-base.owl, you will find that there are GO axioms in there! If you can figure out why they get in there.. That would be awesome!

**Comment by matentzn** [comment]
Sorry I meant RO, not GO!

**Comment by anitacaron** [comment]
If it's this kind of axioms, it seems they've always been there since the first release available here.

```
<owl:Axiom>
   <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/RO_0002175"/>
   <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000115"/>
   <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">S present_in_taxon T if some instance of T has some S. This does not means that all instances of T have an S - it may only be certain life stages or sexes that have S</owl:annotatedTarget>
    <oboInOwl:hasDbXref rdf:resource="https://orcid.org/0000-0002-6601-2165"/>
</owl:Axiom>
```

**Comment by matentzn** [comment]
Yes, they must have - it is still wrong though. A base file should not include any external axioms at all! Thank you for checking that! Dont get to stuck on this.. In contrast to all the things you have done this week already (THANK YOU) this is _not_ a high priority.

**Comment by anitacaron** [comment]
A `robot remove --terms RO` won't work to fix it?

**Comment by matentzn** [comment]
It would, but it should not even be necessary - the fact that there are RO axioms points to a more fundamental problem.

**Comment by anitacaron** [comment]
Is there anything that I can do?

**Comment by matentzn** [comment]
Yeah, thanks.. We still dont know _why_ there are non-Uberon axioms in the uberon-base.owl! There should be 0 axioms that belong in other ontologies!

**Comment by matentzn** [comment]
Can we remove everything non-base and see how this impacts the class hierarchy?
