### ISSUE TITLE
No dbxref on UBERON:7500073 and UBERON:7500074

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2267]
Was running some stuff and came upon and error that showed no dbxref on UBERON:7500073 and UBERON:7500074
I've currently fixed by putting the term_editor orcid as dbxref
Assigning to @ramonawalls as the ID falls in your ID range.
Assigning to @megbalk as the ORCID belongs to you.
If you are ok with the change I've made feel free to close this ticket.

**Comment by megbalk** [comment]
It was strange, the database xref showed in protégé, but not in the text file. It should be fixed. I made a PR.
