### ISSUE TITLE
New policy proposal to deal with PRs: absence of objection is tacit approval

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#2268]
_Note: The following proposal would apply to CL as well as Uberon._

We still regularly have pull requests that are several weeks or even several months old and that are waiting to be merged because nobody jumped in to review them.

The “shepherding“ system put in place last summer is not enough, at least in part, I believe, because the “domains of responsibility” of available reviewers (as decided in the Uberon call of July 26, 2021) are quite vague and therefore many PRs end up being assigned to the same two or three reviewers (typically Chris or David).

I would thus like to suggest a new approach, based on Grace Hopper’s advice that it is “easier to ask for forgiveness than to get permission”, in which the author of a PR would be tacitly allowed to merge it after a certain period of time (I tentatively propose one month, though this is debatable) if _nobody_ raised any concern on that PR since its submission.

This would _not_ be automatic, but left at the discretion of the PR author. If they are really not sure whether what they did is the best solution to the issue they were trying to tackle, they may still choose not to merge until they got an _explicit_ green light from a reviewer.

Worst-case scenario, this approach may lead to a PR with a questionable change being merged to master. But then, once the change is in master, if it is really problematic then it will (finally) be noticed and a corrective action can be taken.

I believe such an approach is more suitable to projects like Uberon or CL, where there’s no single official “project lead” to whom we can defer every single decision.

**Comment by matentzn** [comment]
Great!
