### ISSUE TITLE
Merge 'descending thin limb' UBERON_0005096 and 'descending limb of loop of Henle' UBERON_0001289?

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#2276]
@RDruzinsky please (of course, feedback from others is welcome too!)
For the ASCT+B work, we're looking at these two terms:

descending thin limb http://purl.obolibrary.org/obo/UBERON_0005096
descending limb of loop of Henle http://purl.obolibrary.org/obo/UBERON_0001289

There is currently no is_a, part_of or overlaps relationship between these 2 classes.  
Wikipedia suggests that a nomenclature issue may be causing redundancy:
"Like the ascending limb, the descending limb has thick and thin portions. However, this distinction is not as important physiologically as in the ascending limb, so often the two are treated as one structure. The thick descending limb is less important than the thin descending limb, so often the terms "descending limb" and "thin descending limb" are used interchangeably.
Some sources simply refer to a "thin limb". In this context, the thin ascending limb of loop of Henle would be included."
(https://en.wikipedia.org/w/index.php?title=Descending_limb_of_loop_of_Henle&oldid=993917236#Nomenclature)

- [ ] Does the community use the 2 terms interchangeably (if so we should merge them)?
- [ ] Or should the 2 terms continue to exist, and if so,  could you please help us clarify the difference between them, and if/what relationship should exist between them?

For reference, the original ticket with details is [here](https://github.com/obophenotype/asct-b_validation/issues/23).

Thank you in advance!
Paola

**Comment by paolaroncaglia** [comment]
@emquardokus , hi, could you please consult your collaborators on this issue? Thanks in advance.

**Comment by paolaroncaglia** [comment]
@emquardokus , adding you as an assignee. When you have a chance, please let us know if you think you could get feedback from external experts on this issue. If you think that's unlikely, no problem, please mention that so we'll know we need to make a resolution on this ourselves. Thanks.

**Comment by paolaroncaglia** [comment]
@RDruzinsky , 

Could I please ask for your feedback on whether these 2 terms
descending thin limb http://purl.obolibrary.org/obo/UBERON_0005096
descending limb of loop of Henle http://purl.obolibrary.org/obo/UBERON_0001289
are the same thing or not? Details here: https://github.com/obophenotype/uberon/issues/2276#issue-1122893647

Thank you very much in advance!

Note to self/Uberon editor: if we do merge the terms, follow [these obook SOPs](https://github.com/OBOAcademy/obook/pull/145) and give feedback.

**Comment by RDruzinsky** [comment]
Hi,
I do not think that they are exact synonyms. There are thick and thin parts
of the descending limb and thick and thin parts of the ascending limb, and
I believe that there are functional differences between the various parts.
I am not at all sure about differences across species, although I know that
the thin parts vary in length.

I can do some research if that would be helpful.


Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by paolaroncaglia** [comment]
(cc @dosumis and @emquardokus )
@RDruzinsky thank you for your feedback on the descending thin/thick limb terms.
Summing up, in support of _not_ merging 
descending thin limb http://purl.obolibrary.org/obo/UBERON_0005096
descending limb of loop of Henle http://purl.obolibrary.org/obo/UBERON_0001289
we have not only @RDruzinsky 's feedback, but also some differences at the cellular and physiological level between the thick and thin limb, supported by

- the definition of 'descending limb of loop of Henle' ("...it consists of an initial short thick segment lined by low simple cuboidal epithelium and a long thin segment lined by simple squamous epithelium...")
- the bottom figure in the [supporting Wikipedia reference](https://en.wikipedia.org/wiki/Descending_limb_of_loop_of_Henle)
- the presence of distinct cell types in the thin vs thick limb as listed in the [Kidney Tissue Atlas Explorer](https://atlas.kpmp.org/explorer/) 

On this basis, I will make 'descending thin limb' a part_of 'descending limb of loop of Henle'. It already has an exact synonym "descending thin limb of loop of Henle", so I won't modify the label.

**Comment by paolaroncaglia** [comment]
@dosumis @emquardokus FYI this is fixed now.
