### ISSUE TITLE
Bridge the gap between left subclavian artery and arch of aorta

### ISSUE THREAD

**Issue by Baytars** [obophenotype/uberon#2281]
**Uberon term**
left subclavian artery (UBERON_0001584)

**Suggested revision and reasons**
Taxon notes of the term "left subclavian artery" (UBERON_0001584) say "in humans, branches off the arch of aorta", though, this is not reflected in the subclass relationships of left subclavian artery, where I saw no "[channels_from](https://www.ebi.ac.uk/ols/ontologies/uberon/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fuberon%2Fcore%23channels_from) some [arch of aorta](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001508)". I am making an app which can walk through systemic circulation and I found this gap between left subclavian artery and arch of aorta disturbing. Looks like you are dealing with anatomical discrepancies among species, doesn't it? Must I deal with the gap manually or can you help me with that? Looking forward to your reply.

**Comment by shawntanzk** [comment]
Hi @Baytars sorry this took so long to get to, I'm now shepherding tickets in uberon.
I don't have a good answer for now, but channels_from is a custom uberon relation and we are trying to move all relations to using RO terms. 
I see that there is already a connected_to axiom, however I do understand that that is not specific.
I think that the options here are:
1) request a term in RO that fromalizes channels_from (I will open a ticket to ask if this is ideal)
2) add the channels_from axiom for now and replace it with RO term if/when it gets through
3) deal with the gap manually

**Comment by shawntanzk** [comment]
We will go with option 2 for now for a quick fix, but there are a lot more discussions with vasculature relations and moving relations to RO
