### ISSUE TITLE
Remove character coding restrictions on Uberon

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#2292]
@gouttegd noted:

> Even though the edit file is encoded in UTF-8, we forbid all characters outside of the Latin-9 character set (see uberon.Makefile, line 638)

We should be able to drop this restriction.  I think it dates back to OBO-Edit days and support for legacy DBs.  The world should all be UTF-8 compliant now, and if they're not, it's their problem.

Any objections?  @cmungall ?

**Comment by balhoff** [comment]
Speaking of OBO-Edit: https://github.com/geneontology/obo-edit/commit/907523ac6dda6a4bbd40774aaa0ffad31a6d6c79
😉

**Comment by dosumis** [comment]
2009 !!!! 😲

**Comment by shawntanzk** [comment]
```
$(REPORTDIR)/%-iconv: %
	iconv -f UTF-8 -t ISO-8859-15 $< > $@
```

convert to UTF-8 instead of latin 15 here @gouttegd to check if this is alright

**Comment by gouttegd** [comment]
I confirm that attempting a “mock” conversion from UTF-8 to UTF-8 will still catch real encoding errors (e.g. use of invalid UTF-8 sequences), without forbidding the use of valid Unicode characters outside of the Latin-9 character set.

I’ll submit a PR to that effect, then we can see whether the presence of non-Latin-9 characters is breaking anything downstream.

**Comment by gouttegd** [comment]
If anyone wants to test, there’s a branch (#2328) with some non-ASCII characters randomly introduced into a few terms (in labels, definitions, and synonyms).

The main release artefacts are built without errors, and so are the bridge files (which were my biggest concerns, as I was not sure the ~~dubious hacks~~ ingenious scripts we use to generate them would cope with non-ASCII stuff).

If you know of any downstream consumer of Uberon whose application could be broken by the use of UTF-8, you may direct them to PR #2328 and get them to test whatever they do with that branch.
