### ISSUE TITLE
Add sparql update query to "attach xsd:string datatype" to oboInOwl properties

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2300]
Can you write a SPARQL update query that matches all oboInOwl properties w/o datatype string and then inserts the datatype?

**Comment by shawntanzk** [comment]
synonym, xref, source -> make xsd:string (conservative method) 
When we find out more then add to above 
make sure it is indeed string (eg not an IRI)

**Comment by shawntanzk** [comment]
Start with https://api.triplydb.com/s/--ywm2QLQ

**Comment by anitacaron** [comment]
@matentzn, this issue might not be relevant anymore with the new OWLAPI serialisation, right?

**Comment by matentzn** [comment]
Thats right can be closed
