### ISSUE TITLE
Auto-deploy docs 

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#2308]
needs to be done manually right now - mkdocs command in Makefile.

**Comment by shawntanzk** [comment]
Fixed by: https://github.com/INCATools/ontology-development-kit/pull/550
Figured should do this through ODK if not it will get wiped and this shouldn't be specific to uberon anyway.
I saw that @gouttegd has already run a deploy docs this round so docs should be updated

**Comment by shawntanzk** [comment]
Will be fixed in next ODK release - for now we can just manually do this
