### ISSUE TITLE
Revert orcid-contributor-violation https check

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2318]
Undo this commit: https://github.com/obophenotype/uberon/commit/af0d05e64ae30c3ddce21c4709916937bdc7fbf8 when https://github.com/protegeproject/protege/issues/1045 is addressed

**Comment by anitacaron** [comment]
No, because we still don't have a new Protegé release.

**Comment by shawntanzk** [comment]
oh right >.< fixed there but waiting for release, got it! thanks :)

**Comment by anitacaron** [comment]
You can unassign yourself in this if you want. I have already created the PR, just waiting for the release.

**Comment by anitacaron** [comment]
Protege will have a new release on Feb 14th.
