### ISSUE TITLE
depreciate FOVT lines

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#2333]
**Uberon term**
line from caundal-sacral region of the vertebral column to the last vertebra
line from helix of outer ear to intertragus incisure
line from the distal-most end of the longest nail to the posterior-most part of the foot
line from the distal-most end of the longest phalax of the foot to the posterior-most part of the foot
line from tip of nose to the caudal-sacral region of the vertebral column
line from tip of nose to the posterior-most part of the last caudal vertebra
line from trochlea of humerus to proximal head of humerus
line from trochlea of humerus to ventral tubercle of humerus
line of medial condyle of femur to greater trochanter
line of medial condyle of femur to head of femur

**Reason for deprecation**
@dosumis and I came up with a different pattern such that lines are no longer needed. This is not a common thing people would want to have or search on.

**Suggested replacement or term to consider**
I have noted that lengths of these lines will be in OBA or FOVT.

tail length (http://purl.obolibrary.org/obo/OBA_VT0002758)
ear length to notch (FOVT:0000005)
pes length with nail (FOVT:0000003)
pes length without nail (FOVT:0000004)
body length without tail (FOVT:0000002)
body length with tail (FOVT:0000001)
humerus length from trochlea to caput (FOVT:0000008)
humerus length from trochlea to ventral tubercle (FOVT:0000009)
femur length from greater trochanter to medial condyle (FOVT:0000006)
femur length from caput to medial condyle (FOVT:0000007)

**Comment by paolaroncaglia** [comment]
Hi @megbalk ,
I assigned this ticket to you as I understand that you plan to do the obsoletions, but if not, please assign to others as appropriate.
Unassigned tickets tend to get lost ;-) 
Thanks,
Paola

**Comment by megbalk** [comment]
depreciating more terms:
tip of tail (already exists)
tip of digit (not needed)
posterior of pes
