### ISSUE TITLE
[NTR] anterior ectoderm anlage

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2340]
Currently there is a dangling term [FBbt_01000119](https://www.ebi.ac.uk/ols/ontologies/dpo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_01000119)
This should be added as a class in uberon and replaced. 
@gouttegd would you mind handling this or passing this to someone who can - I would do it but i have no idea about fly stuff >.< 
related to https://github.com/obophenotype/uberon/issues/1963

**Comment by gouttegd** [comment]
Duplicate of #2154 ;) Closing this one for clarity.

**Comment by shawntanzk** [comment]
lol thanks, sorry about that, should have checked beforehand >.<
