### ISSUE TITLE
Missing spatial disjointness: forebrain is allowed to be part of brainstem

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2342]
[Nothing](http://www.w3.org/2002/07/owl#Nothing) EquivalentTo ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [forebrain](http://purl.obolibrary.org/obo/UBERON_0001890)) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [brainstem](http://purl.obolibrary.org/obo/UBERON_0002298)) is missing

I wonder if it is something I should add as is, or if we should work up how high up the hierarchy we can go to add disjointness there - I'm not 100% sure how to do this properly/systematically

**Comment by dosumis** [comment]
I think fine to add this directly.  Don't think it makes sense to go higher up in this case.  Doing this more systemically for brain needs discussion with @cmungall.  Also a good topic for discussion with Allen and any experts they bring in to review.
