### ISSUE TITLE
UBERON:0001367 'external anal sphincter' isn't a subclass of 'anal sphincter'

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/uberon#2344]
Quick placeholder ticket to look into what needs fixing here - what axioms may need revising/adding

**Uberon term**
UBERON:0001367 'external anal sphincter'

**Suggested revision and reasons**
Should be a subclass of 'anal sphincter'

Note for self - noticed while addressing an [HCA ticket](https://github.com/HumanCellAtlas/ontology/issues/103)

**Comment by paolaroncaglia** [comment]
Currently, UBERON:0001367 'external anal sphincter' is not a(n inferred) subclass of 'anal sphincter', like 'internal anal sphincter' is, because it isn't a subclass of 'sphincter muscle'. I'll assert the missing superclass.

**Comment by cmungall** [comment]
can you instead assert the part-of that will give us the inference

should mirror internal

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/50745/160679977-cb0c0b8d-9b9c-4f7e-bc43-0fa0147843e6.png">


or even better investigate what is missing:

```yaml
id: UBERON:0001367
name: external anal sphincter
is_a: UBERON:0004832 {source="MA"} ! anal region skeletal muscle
relationship: part_of UBERON:0006867 {source="FMA"} ! anal part of perineum
relationship: surrounds UBERON:0001245 ! anus
```yaml

shouldn't this be sufficient?

**Comment by paolaroncaglia** [comment]
@cmungall 

> doh, I see what is missing
> 'external anal sphincter' should be asserted as a subclass of _sphincter muscle_

Yep, that's what I said I'd do ;-)

> however I see literature saying the EAS is not a _true_ sphincter, which is presumably why we don't say this

Ah ok, could you please provide dbxrefs while you have them handy? So I can add an rdfs:comment to EAS to that extent, and I won't add the asserted sphincter muscle parent. Thanks.

**Comment by uberon** [comment]
tbh it may be simpler and less 'surprising' to be more, errm, relaxed with
the definition our sphincter term, we can just add a note to EAS that it's
sometimes considered to be not 'true'

it's a bit odd at the moment as IAS is a single-child of AS and those are
always bad.. design practice

**Comment by RDruzinsky** [comment]
This is an interesting question. Except for location, I am not sure that
there should be a class 'anal sphincter' with subclasses 'external anal
sphincter' and 'internal anal sphincter' because they develop from
completely separate anlage.

Thoughts?


Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by cmungall** [comment]
Well there may be other reasons to group beyond lineage

but point taken we want to avoid deceptive or useless grouping classes where the commonality is primarily lexical

FWIW some other ontologies group the same way

<img width="985" alt="image" src="https://user-images.githubusercontent.com/50745/195187684-a0bd2489-9145-4790-85f0-b35725426a17.png">

Historically uberon has generally been liberal in including groupings, but also liberal in applying annotations to them that flag them as groupings. We don't need to retain that policy though
