### ISSUE TITLE
Where are the axioms that connect CL with Uberon?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2345]
Opening uberon.owl or cl.owl reveals no connection of the CL upper level with Uberon.

cc @dosumis @shawntanzk

**Comment by matentzn** [comment]
(at the very least I expect cell to be a subclass of anatomical entity?)

**Comment by shawntanzk** [comment]
def of anatomical entity:
'Biological entity that is either an individual member of a biological species or constitutes the structural organization of an individual member of a biological species.'
cell should be considered "an individual member of a biological species" right?
in which case what Nico said make sense

**Comment by dosumis** [comment]
If you just mean 'cell -> anatomical entity' - I think the link is through CARO.   CARO was always meant to knit all these together.  IN the absence of sufficient CARO imports to do this, I think it makes sense to have a direct link to uberon 'anatomical entity' in CL - maybe in a component file?  

Presumably needed for uPheno pattern ranges to bridge across anatomical entity -> cell ?

**Comment by cmungall** [comment]
See also

- #2348

**Comment by matentzn** [comment]
Deprioritised during Tech call 20 June 2022.
