### ISSUE TITLE
replace metazoan-specific relationships on generic caro-equivalent structures with taxon GCIs

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2348]
There are a broader set of issues I will link to later about whether or not it is a good idea to have

uberon:anatomical_structure = caro:anatomical_structure and part-of some metazoa

for now people are using the uberon classes as if they were more general. Issues arise from this e.g. with starts-and-ends to zygote for anatomical structure where anatomical structure is pan-cellular organisms.

Let's replace this with taxon GCIs while we figure out what the longer term solution is

Note that @fbastian relies on the stages, even for generic terms I believe. But the stages will 'come back' in the composite-metazoan release

**Comment by cmungall** [comment]
`obo-grep.pl -r 'xref: CARO' uberon-edit.obo | obo-grep.pl --neg -r obsolete - | obo-grep.pl -r relationship - | obo-filter-tags.pl -t id -t name -t relationship -`

I am annotating output with actions proposed:

[Term]
id: UBERON:0000026 ! appendage
name: appendage
relationship: only_in_taxon NCBITaxon:6072 ! Eumetazoa
^^ok

[Term]
id: UBERON:0000061 ! anatomical structure
name: anatomical structure
relationship: existence_ends_during_or_before UBERON:0000071 ! death stage
relationship: existence_starts_during_or_after UBERON:0000106 ! zygote stage
^^taxon-GCI (term is pan-life)

[Term]
id: UBERON:0000062 ! organ
name: organ
relationship: capable_of GO:0008150 ! biological_process
relationship: existence_starts_during_or_after UBERON:0000111 ! organogenesis stage
relationship: has_boundary UBERON:0006984 ! anatomical surface
relationship: never_in_taxon NCBITaxon:110815 {source="Wikipedia"} ! Xenoturbella
relationship: part_of UBERON:0000467 ! anatomical system
^^taxon-GCI (term is plant+metazoa)

[Term]
id: UBERON:0000122 ! neuron projection bundle
name: neuron projection bundle
relationship: has_part GO:0043005 ! neuron projection
relationship: part_of UBERON:0001016 ! nervous system
^^ok

[Term]
id: UBERON:0000179 ! haemolymphatic fluid
name: haemolymphatic fluid
relationship: only_in_taxon NCBITaxon:6072 ! Eumetazoa
^^ok

[Term]
id: UBERON:0000463 ! organism substance
name: organism substance
relationship: has_quality PATO:0002198 ! quality of a substance
relationship: part_of UBERON:0000468 {notes="this relationship may be too strong and may be weakened in future"} ! multicellular organism
^^probably OK as we don't use this e.g for cellular substances or biofilms

[Term]
id: UBERON:0000464 ! anatomical space
name: anatomical space
relationship: surrounded_by UBERON:0000061 ! anatomical structure
^^ok

[Term]
id: UBERON:0000467 ! anatomical system
name: anatomical system
relationship: existence_starts_during_or_after UBERON:0000111 ! organogenesis stage
^^taxon-GCI (term is plant+metazoa)
relationship: has_part UBERON:0000062 ! organ
relationship: part_of UBERON:0000468 ! multicellular organism
^^ these two are ok if the above terms themselves can apply to plants
relationship: seeAlso EHDAA2:0001330


[Term]
id: UBERON:0000471 ! compound organ component
name: compound organ component
relationship: part_of UBERON:0003103 ! compound organ
^^ ok

[Term]
id: UBERON:0000475 ! organism subdivision
name: organism subdivision
relationship: has_part UBERON:0000075 {gci_relation="part_of", gci_filler="NCBITaxon:7742"} ! subdivision of skeletal system
relationship: has_part UBERON:0034929 {gci_relation="part_of", gci_filler="NCBITaxon:7742"} ! external soft tissue zone
relationship: overlaps UBERON:0001009 ! circulatory system
relationship: overlaps UBERON:0001015 ! musculature
relationship: overlaps UBERON:0001016 ! nervous system
relationship: overlaps UBERON:0001434 ! skeletal system
relationship: overlaps UBERON:0002416 ! integumental system
relationship: part_of UBERON:0000468 ! multicellular organism
^^ replace all overlaps with taxon GCIs. unlikely they do much work anyway

[Term]
id: UBERON:0000478 ! extraembryonic structure
name: extraembryonic structure
relationship: existence_starts_and_ends_during UBERON:0000068 ! embryo stage
^^taxon-GCI (term is plant+metazoa).. I DON'T think uberon embryo stage should encompass plants

[Term]
id: UBERON:0000479 ! tissue
name: tissue
relationship: has_part GO:0031012 ! extracellular matrix
relationship: part_of UBERON:0000468 ! multicellular organism

[Term]
id: UBERON:0000480 ! anatomical group
name: anatomical group
relationship: part_of UBERON:0000468 ! multicellular organism

[Term]
id: UBERON:0000481 ! multi-tissue structure
name: multi-tissue structure
relationship: has_part UBERON:0000479 ! tissue
relationship: part_of NCBITaxon:6072 ! Eumetazoa
^^taxon-GCI (term is plant+metazoa)

[Term]
id: UBERON:0000482 ! basal lamina of epithelium
name: basal lamina of epithelium
relationship: composed_primarily_of GO:0005604 ! basement membrane
relationship: part_of UBERON:0005769 {source="FMA"} ! basement membrane of epithelium
^^ok

[Term]
id: UBERON:0000483 ! epithelium
name: epithelium
relationship: has_part GO:0005911 ! cell-cell junction
relationship: has_part UBERON:0005769 ! basement membrane of epithelium
relationship: only_in_taxon NCBITaxon:6072 ! Eumetazoa
^^ ok, epithelium is correctly eumetazoa (but see separate issues about dicty analog)

[Term]
id: UBERON:0002416 ! integumental system
name: integumental system
relationship: bounding_layer_of UBERON:0000468 ! multicellular organism
relationship: existence_ends_during UBERON:0000066 ! fully formed stage
relationship: has_part UBERON:0007376 ! outer epithelium
relationship: surrounded_by UBERON:0013514 ! space surrounding organism
^^ ok

[Term]
id: UBERON:0003100 ! female organism
name: female organism
relationship: mutually_spatially_disjoint_with UBERON:0003101 ! male organism
^^ sounds funny but ok

[Term]
id: UBERON:0003103 ! compound organ
name: compound organ
relationship: only_in_taxon NCBITaxon:6072 ! Eumetazoa
^^taxon-GCI (term is plant+metazoa)... but probably not priority as not widely used term

[Term]
id: UBERON:0005162 ! multi cell part structure
name: multi cell part structure
relationship: composed_primarily_of GO:0005575 ! cellular_component

[Term]
id: UBERON:0010000 ! multicellular anatomical structure
name: multicellular anatomical structure
relationship: has_part CL:0000000 ! cell
^^ok (cell is already generic in CL)

[Term]
id: UBERON:0014732 ! compound cell cluster organ
name: compound cell cluster organ
relationship: composed_primarily_of UBERON:0010001 ! cell cluster organ
relationship: has_component UBERON:0010001 {min_cardinality="2"} ! cell cluster organ
^^ ok

[Term]
id: UBERON:0034921 ! multi organ part structure
name: multi organ part structure
relationship: composed_primarily_of UBERON:0000064 ! organ part
^^ ok

[Term]
id: UBERON:0034922 ! cell cluster
name: cell cluster
relationship: surrounded_by UBERON:0000015 ! non-material anatomical boundary
^^ok

[Term]
id: UBERON:0034923 ! disconnected anatomical group
name: disconnected anatomical group
relationship: composed_primarily_of UBERON:0000061 ! anatomical structure
relationship: has_component UBERON:0000061 {minCardinality="2"} ! anatomical structure
relationship: has_quality PATO:0010001 ! disconnected
^^ok

**Comment by balhoff** [comment]
@cmungall what taxon for `'anatomical structure' existence_starts_during_or_after 'zygote stage'`?

**Comment by shawntanzk** [comment]
assigning you @cmungall, same as https://github.com/obophenotype/uberon/issues/2345
