### ISSUE TITLE
Clarify CARO-Uberon connections

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2349]
We have two possible approaches:

1. CARO generalizes
2. CARO and Uberon are equivalent

clearly 1 was intended originally, but if we are serious about this, we need to make sure

- uberon generic terms are unique (prefixed with "metazoan")
- make sure bridge files are easy to compose with main uberon release

I am not sure of the value of 1 anymore. I think it would be much simpler if uberon were analogous to CL, where generic structures are not artificially restricted. PO, FAO, and even GO CC would subclass the relevant Uberon structures (a small handful).

See

- #2348

**Comment by shawntanzk** [comment]
added to agenda, hope it's alright if I assign this ticket to you for now @cmungall (trying to make sure all relatively recent tickets have someone assigned) - happy to make changes once there's an action plan. Thanks

**Comment by balhoff** [comment]
For (2) It might be useful to explicitly mark the small set of Uberon pan-life terms. Then add 'present in taxon' statements to them forcing their applicability in various taxa.

**Comment by balhoff** [comment]
Here's a draft set for a generic/pan-life subset:

- [anatomical entity](http://purl.obolibrary.org/obo/UBERON_0001062)
  - [anatomical cluster](http://purl.obolibrary.org/obo/UBERON_0000477)
  - [immaterial anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000466)
    - [anatomical point](http://purl.obolibrary.org/obo/UBERON_0006983)
    - [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464)
    - [non-material anatomical boundary](http://purl.obolibrary.org/obo/UBERON_0000015)
      - [anatomical line](http://purl.obolibrary.org/obo/UBERON_0006800)
  - [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465)
    - [anatomical collection](http://purl.obolibrary.org/obo/UBERON_0034925)
      - [anatomical row](http://purl.obolibrary.org/obo/UBERON_0034926)
    - [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)
      - [acellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000476)
        - [acellular membrane](http://purl.obolibrary.org/obo/UBERON_0005764)
      - [anatomical border](http://purl.obolibrary.org/obo/UBERON_0036304)
      - [anatomical group](http://purl.obolibrary.org/obo/UBERON_0000480)
      - [anatomical junction](http://purl.obolibrary.org/obo/UBERON_0007651)
      - [anatomical system](http://purl.obolibrary.org/obo/UBERON_0000467)
    - [anatomical surface region](http://purl.obolibrary.org/obo/UBERON_0036215)
    - [developing anatomical structure](http://purl.obolibrary.org/obo/UBERON_0005423)
    - [disconnected anatomical group](http://purl.obolibrary.org/obo/UBERON_0034923)
      - [aligned anatomical group](http://purl.obolibrary.org/obo/UBERON_0034924)
    - [organism substance](http://purl.obolibrary.org/obo/UBERON_0000463)
- [processual entity](http://purl.obolibrary.org/obo/UBERON_0000000)
  - [life cycle](http://purl.obolibrary.org/obo/UBERON_0000104)
  - [life cycle stage](http://purl.obolibrary.org/obo/UBERON_0000105)
    - [death stage](http://purl.obolibrary.org/obo/UBERON_0000071)
  - [life cycle temporal boundary](http://purl.obolibrary.org/obo/UBERON_0035943)
    - [life-death temporal boundary](http://purl.obolibrary.org/obo/UBERON_0035944)
      - [start of life cycle](http://purl.obolibrary.org/obo/UBERON_0035945)

**Comment by ddooley** [comment]
I presume this will help resolve that right now CARO terms "anatomical entity" and "anatomical structure" and "material anatomical entity" are in UBERON and have duplicate UBERON terms?  I have an automated ontofox import script that brings in both terms, and its a hassle to manually drop the CARO ones to reduce confusion.

**Comment by balhoff** [comment]
@ddooley I am going to propose that we obsolete the CARO ontology entirely, and maintain the pan-life layer at the top of Uberon. Mainly just to reduce confusion and facilitate maintenance. Any thoughts on that idea?

**Comment by ddooley** [comment]
Sounds great to me!

**Comment by balhoff** [comment]
Added [anatomical conduit space](http://purl.obolibrary.org/obo/UBERON_0013686) to the subset.

**Comment by anitacaron** [comment]
Completed by PR #2614.
