### ISSUE TITLE
Guidance Requested - UBERON addition for ferret brain areas

### ISSUE THREAD

**Issue by stevevanhooser** [obophenotype/uberon#2352]
My name is Danielle Scafidi and I am a graduate student in Steve Van Hooser’s lab at Brandeis University. I am reaching out on behalf of the lab to ask for advice on an ontology project we are currently working on. 

One aspect of the lab’s work is involved in developing analysis and database software for neuroscience, specifically working toward the streamlining of data exchange. The use of ontologies in such work is crucial to achieve a comprehensive search of existing research and the integration of new data. To this end, I have been working on building an ontology of cortical and thalamic ferret visual areas that will hopefully map onto the existing Uberon ontology. Building off of previous work done by Claus Hilgetag and colleagues and Susanne Radtke-Schuller, I have compiled a list of ferret brain areas, their synonyms and relationships to terms in the Uberon ontology. 

However, we do not have experience coding ontologies and do not know the preferred language or means of specifying these entries in UBERON. We were hoping to get some guidance in these areas as we move forward with the project. I have included some examples of entries that exist in our spreadsheet that represent the type of relationships we would like to express. 

As one example: Ferrets have a "primary visual cortex" that is homologous to the entry “primary visual cortex” (UBERON_0002436) and has the same synonyms. 

Another example: There exists an area “PMLS” that is a “part of” visual cortex generically (UBERON_0000411) but is only in some taxa (currently only defined in the cat and the ferret, but perhaps in all carnivores). This area is also broadly a "part of" visual cortex (UBERON_0000411). It has some synonyms and a full spelling.

We have two types of questions…

1) First, what are the relationships that are expected in UBERON?

For areas already in UBERON, like “primary visual cortex”, do we need to add a line to the ontology that says “in taxon” and give the ferret species name?

For areas that are not (like PMLS), do we have the relationships set up correctly? (Part of UBERTON_000411 and “in taxon” {ferret}). 

How would you recommend expressing a synonym when a brain area is also commonly known as a number, when this number doesn’t correspond to other species? For example, would we say the synonym is “Ferret 20a” for a particular area instead of just “20a”? 

2) We imagine it is relatively simple to express these relationships in the ontology, but we haven’t written ontology code before. Do we need to add it to a .ttl file or .owl file or some other type of file?

**Comment by stevevanhooser** [comment]
Chris responded with:

Hi Danielle!

How would you feel about moving some of this discussion to the github issue tracker? Let u know if you need help getting a github account

You ask good questions with nuanced answers, but broadly speaking:

1. for primary visual cortex, I don't think we need to do anything. We could add an annotation that says this is present in the ferret and give you as attribution, but we have broader assertions that should tell us this is homologous across mammals (I think)
2. for PMLS, I think we would want a new term with a new ID. This would be part of the standard uberon primary visual cortex.

If you like we can provide training material for editing the ontology in Protege, but I think to get started I would have a different route: we would agree on a google sheet format, and we would take care of importing this into the ontology.

Perhaps there would be two google sheets

For existing uberon terms (e.g. primary visual cortex):

1. Uberon ID 
2. preferred label 
3. proposed ferret-specific synonyms
4. PMIDs or DOIs that provide evidence this structure is present in ferrets
5. any notes that you want to make about the structure as it is present in ferrets

only make rows where there is new info

For proposed new terms (e.g. PMLS)

1. ID (but leave blank, we will fill in)
2. preferred label
3. definition
4. synonyms
5. part-of parent
6. superclass, if this isn't a plain brain region (e.g. neural nucleus, gyrus)
7. taxonomic scope, ie NCBITaxon IDs for which there is evidence this structure is present (ferret assumed)
8. potential homolog structures in uberon
9. notes

the homolog thing is a giant can of worms, but just use judgment. For something like primary visual cortex it makes sense to lump with the generic uberon structure. If it doesn't make sense for you to lump, make a new row in the 2nd sheet

**Comment by shawntanzk** [comment]
Hi @stevevanhooser 

Happy to take a look into this, thought I'll admit that because it is not directly part of our funding, the priority on this might be a bit lower. What you could help us with though is having simple actionable items in individual tickets.
Eg if you need a new term in uberon, you can create a ticket with [NTR] (new term request). When you create the issue, there should be a new term template that will let you know what we info we need. Don't worry too much if you don't know the answers to any field, happy to help. Please also tag me so that I get notified (if you can assign me to it, that's even better). 

I'll go through what you have written above a bit later to try to understand and try to work through the questions too. Thanks!

**Comment by shawntanzk** [comment]
I assume Chris is @cmungall and hence he is involved in this too? - pinging you in case

**Comment by shawntanzk** [comment]
PS converting this to an epic as I assume it will have multiple individual actions to look into

**Comment by stevevanhooser** [comment]
We could break it down into multiple issues. Now we are raising issues that have arisen as we have begun to prepare our ferret areas for addition. (And yes, Chris answered our initial message, thanks for asking.)
Best
Steve
