### ISSUE TITLE
serrated projection of ctenactinium is both an intromittent organ and a head bone

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2357]
https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0013677&viewMode=PreferredRoots&siblings=false

although this is an unusual organ https://www.fishbase.se/glossary/Glossary.php?q=priapium -- but I suspect something is not quite right here

**Comment by shawntanzk** [comment]
added to agenda, assigning myself, will follow up once I have actionable items
