### ISSUE TITLE
NTR: skin tissues

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2358]
**Comment**: The following terms are requested to indicate the origin of the tissues to establish cell lines annotated in Cellosaurus. Many thanks 
_____________________________________________________________________________________________________________
**Preferred term label:** skin of breast

**Synonyms** breast skin

**Definition** A zone of skin that is part of the breast

**Parent term**
breast UBERON:0000310
skin of chest UBERON:0001868

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of buttock

**Synonyms** buttock skin

**Definition** A zone of skin that is part of the buttock

**Parent term**
buttock UBERON:0013691
skin of trunk UBERON:0001085

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of calf

**Synonyms** calf skin

**Definition** A zone of skin that is part of the calf

**Parent term** -
NOTE: Calf is the back of the lower leg. Calf is missing in UBERON

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** calf

**Synonyms** -

**Definition** The back of the lower leg

**Parent term**
hindlimb zeugopod UBERON:0003823

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of flank

**Synonyms** flank skin

**Definition** A zone of skin that is part of the flank

**Parent term**
lateral lumbar region of abdomen UBERON:0000180 
skin of abdomen UBERON:0001416

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of sacral region

**Synonyms** sacral region skin

**Definition** A zone of skin that is part of the sacral region

**Parent term**
sacral region UBERON:0005473 
skin of pelvis UBERON:0001415

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of clavicle zone

**Synonyms** -

**Definition** A zone of skin that is above the left clavicle zone

**Parent term**
NOTE: This term is requested to indicate the origin of the tissue to establish cell lines. Samples were taken from the skin region above the left clavicle UBERON:0008256 (PubMed=11992403)

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of posterior iliac crest zone

**Synonyms** -

**Definition** A zone of skin that is above the posterior iliac crest zone

**Parent term** 
NOTE: Samples were taken from the skin region above this bone (CLPUB00447). I did not find posterior iliac crest, but I am not sure if are different entities.  iliac crest UBERON:0014437.

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of temple

**Synonyms** temple skin

**Definition** A zone of skin that is part of the temple

**Parent term**
skin of head UBERON:0001084
NOTE: Temple is missing in UBERON (requested below)

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** temple

**Synonyms** -

**Definition** The temple is a latch where four skull bones fuse: the frontal, parietal, temporal, and sphenoid. It is located on the side of the head behind the eye between the forehead and the ear. [Wikipedia: https://en.wikipedia.org/wiki/Temple_(anatomy)]

**Parent term**
head UBERON:0000033

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of genital area

**Synonyms** genital area skin

**Definition** A zone of skin that is part of the genital area

**Parent term**
NOTE: not equivalent to UBERON_0014481 which is specific to lower primates. This term is requested to indicate the tissue origin of CVCL_IL08. The sex of cell is ambiguous. Not sure if and how UBERON deal with this terms

![image](https://user-images.githubusercontent.com/4089751/159234304-b08a8fb9-d0d6-4fec-b035-3e039b9f8b10.png)

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of gonad

**Synonyms** gonad skin

**Definition** A zone of skin that is part of the gonad

**Parent term** 
NOTE: This term is requested to indicate the tissue origin of CVCL_IL12. The sex of cell is ambiguous. Not sure  if and how UBERON deal with this terms

![image](https://user-images.githubusercontent.com/4089751/159234272-96143100-b6b2-43ce-9fe1-8489f38189a0.png)

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

_____________________________________________________________________________________________________________
**Preferred term label:** skin of labioscrotal fold

**Synonyms** labioscrotal fold skin

**Definition**
**Parent term**
NOTE: This term is requested to indicate the tissue origin of CVCL_JX70 from an individual 46 XY (GM02935). In this case "labioscrotal folds" does not refer to the embryonic structure (UBERON:0011754 genital swelling). Not sure if and how UBERON deal with this terms

![image](https://user-images.githubusercontent.com/4089751/159234149-17de7da8-d848-42b3-b753-8c705ee9a705.png)

**Your nano-attribution (ORCID)** 0000-0002-0819-0473

**Comment by shawntanzk** [comment]
@paulacalipho - just to make sure, these will be added to the template too yeah?

**Comment by paulacalipho** [comment]
@shawntanzk They have been already added

**Comment by bvarner-ebi** [comment]
@emquardokus, in an offline discussion, you mentioned you may have some advice for these skin-related terms. If so, can you add comments for @paulacalipho's and my considerations?
