### ISSUE TITLE
Taxon constraint violation after import updates

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2367]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/7070631/160240263-1e3d06b3-ef5b-4cc9-aff8-4450ce6db40a.png">

Blocks release #2364

**Comment by shawntanzk** [comment]
dont think I can be super helpful here, I have like ZERO idea bout fish let alone their eyes.
My guess is that jugular vein part_of some neck is over-restrictive. 
Did a quick search and it seems fish do indeed have jugular veins and im guessing fishes don't have necks

**Comment by shawntanzk** [comment]
I would think removing the part_of neck would be the right thing to do, but I don't know how that would affect modelling, I'm guessing there's a reason that axiom is there? I guess inherent difficulty with multi-species anatomy ontology

**Comment by shawntanzk** [comment]
> I would think removing the part_of neck would be the right thing to do

shall I do this in the branch @matentzn

**Comment by matentzn** [comment]
Can you branch off from my branch and then make a pr to the branch? Same with the other ticket. You may have to undo changes I made previously

**Comment by matentzn** [comment]
Hmm.. Still a problem:

## [ZFA_0005829](http://purl.obolibrary.org/obo/ZFA_0005829) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [ZFA_0005829](http://purl.obolibrary.org/obo/ZFA_0005829) EquivalentTo [uterine horn](http://purl.obolibrary.org/obo/UBERON_0002247) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Danio](http://purl.obolibrary.org/obo/NCBITaxon_7954))
    - [Danio](http://purl.obolibrary.org/obo/NCBITaxon_7954) SubClassOf [Danioninae](http://purl.obolibrary.org/obo/NCBITaxon_2743711)
      - [Danioninae](http://purl.obolibrary.org/obo/NCBITaxon_2743711) SubClassOf [Danionidae](http://purl.obolibrary.org/obo/NCBITaxon_2743709)
        - [Danionidae](http://purl.obolibrary.org/obo/NCBITaxon_2743709) SubClassOf [Cyprinoidei](http://purl.obolibrary.org/obo/NCBITaxon_30727)
          - [Cyprinoidei](http://purl.obolibrary.org/obo/NCBITaxon_30727) SubClassOf [Cypriniformes](http://purl.obolibrary.org/obo/NCBITaxon_7952)
            - [Cypriniformes](http://purl.obolibrary.org/obo/NCBITaxon_7952) SubClassOf [Cypriniphysae](http://purl.obolibrary.org/obo/NCBITaxon_186627)
              - [Cypriniphysae](http://purl.obolibrary.org/obo/NCBITaxon_186627) SubClassOf [Otophysi](http://purl.obolibrary.org/obo/NCBITaxon_186626)
                - [Otophysi](http://purl.obolibrary.org/obo/NCBITaxon_186626) SubClassOf [Ostariophysi](http://purl.obolibrary.org/obo/NCBITaxon_32519)
                  - [Ostariophysi](http://purl.obolibrary.org/obo/NCBITaxon_32519) SubClassOf [Otomorpha](http://purl.obolibrary.org/obo/NCBITaxon_186634)
                    - [Otomorpha](http://purl.obolibrary.org/obo/NCBITaxon_186634) SubClassOf [Clupeocephala](http://purl.obolibrary.org/obo/NCBITaxon_186625)
                      - [Clupeocephala](http://purl.obolibrary.org/obo/NCBITaxon_186625) SubClassOf [Osteoglossocephalai](http://purl.obolibrary.org/obo/NCBITaxon_1489341)
                        - [Osteoglossocephalai](http://purl.obolibrary.org/obo/NCBITaxon_1489341) SubClassOf [Teleostei](http://purl.obolibrary.org/obo/NCBITaxon_32443)
                          - [Teleostei](http://purl.obolibrary.org/obo/NCBITaxon_32443) SubClassOf [Neopterygii](http://purl.obolibrary.org/obo/NCBITaxon_41665)
                            - [Neopterygii](http://purl.obolibrary.org/obo/NCBITaxon_41665) SubClassOf [Actinopteri](http://purl.obolibrary.org/obo/NCBITaxon_186623)
                              - [Actinopteri](http://purl.obolibrary.org/obo/NCBITaxon_186623) SubClassOf [Actinopterygii](http://purl.obolibrary.org/obo/NCBITaxon_7898)
          - [Cyprinoidei](http://purl.obolibrary.org/obo/NCBITaxon_30727) SubClassOf [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Cyprinoidei](http://purl.obolibrary.org/obo/NCBITaxon_30727)
    - [uterine horn](http://purl.obolibrary.org/obo/UBERON_0002247) SubClassOf [connected to](http://purl.obolibrary.org/obo/RO_0002170) some [fallopian tube](http://purl.obolibrary.org/obo/UBERON_0003889)
      - [fallopian tube](http://purl.obolibrary.org/obo/UBERON_0003889) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674)
        - [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674) SubClassOf [Amniota](http://purl.obolibrary.org/obo/NCBITaxon_32524)
          - [Amniota](http://purl.obolibrary.org/obo/NCBITaxon_32524) SubClassOf [Tetrapoda](http://purl.obolibrary.org/obo/NCBITaxon_32523)
            - [Tetrapoda](http://purl.obolibrary.org/obo/NCBITaxon_32523) SubClassOf [Dipnotetrapodomorpha](http://purl.obolibrary.org/obo/NCBITaxon_1338369)
              - [Dipnotetrapodomorpha](http://purl.obolibrary.org/obo/NCBITaxon_1338369) SubClassOf [Sarcopterygii](http://purl.obolibrary.org/obo/NCBITaxon_8287)
        - [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
    - [part_of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [overlaps](http://purl.obolibrary.org/obo/RO_0002131)
  - [overlaps](http://purl.obolibrary.org/obo/RO_0002131) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Actinopterygii](http://purl.obolibrary.org/obo/NCBITaxon_7898) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Sarcopterygii](http://purl.obolibrary.org/obo/NCBITaxon_8287)
  - [connected to](http://purl.obolibrary.org/obo/RO_0002170) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

# Axiom Impact 
## Axioms used 1 times
- [ZFA_0005829](http://purl.obolibrary.org/obo/ZFA_0005829) EquivalentTo [uterine horn](http://purl.obolibrary.org/obo/UBERON_0002247) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Danio](http://purl.obolibrary.org/obo/NCBITaxon_7954)) [core.owl]
- [Dipnotetrapodomorpha](http://purl.obolibrary.org/obo/NCBITaxon_1338369) SubClassOf [Sarcopterygii](http://purl.obolibrary.org/obo/NCBITaxon_8287) [core.owl]
- [Osteoglossocephalai](http://purl.obolibrary.org/obo/NCBITaxon_1489341) SubClassOf [Teleostei](http://purl.obolibrary.org/obo/NCBITaxon_32443) [core.owl]
- [Actinopteri](http://purl.obolibrary.org/obo/NCBITaxon_186623) SubClassOf [Actinopterygii](http://purl.obolibrary.org/obo/NCBITaxon_7898) [core.owl]
- [Clupeocephala](http://purl.obolibrary.org/obo/NCBITaxon_186625) SubClassOf [Osteoglossocephalai](http://purl.obolibrary.org/obo/NCBITaxon_1489341) [core.owl]
- [Otophysi](http://purl.obolibrary.org/obo/NCBITaxon_186626) SubClassOf [Ostariophysi](http://purl.obolibrary.org/obo/NCBITaxon_32519) [core.owl]
- [Cypriniphysae](http://purl.obolibrary.org/obo/NCBITaxon_186627) SubClassOf [Otophysi](http://purl.obolibrary.org/obo/NCBITaxon_186626) [core.owl]
- [Otomorpha](http://purl.obolibrary.org/obo/NCBITaxon_186634) SubClassOf [Clupeocephala](http://purl.obolibrary.org/obo/NCBITaxon_186625) [core.owl]
- [Danionidae](http://purl.obolibrary.org/obo/NCBITaxon_2743709) SubClassOf [Cyprinoidei](http://purl.obolibrary.org/obo/NCBITaxon_30727) [core.owl]
- [Danioninae](http://purl.obolibrary.org/obo/NCBITaxon_2743711) SubClassOf [Danionidae](http://purl.obolibrary.org/obo/NCBITaxon_2743709) [core.owl]
- [Cyprinoidei](http://purl.obolibrary.org/obo/NCBITaxon_30727) SubClassOf [Cypriniformes](http://purl.obolibrary.org/obo/NCBITaxon_7952) [core.owl]
- [Cyprinoidei](http://purl.obolibrary.org/obo/NCBITaxon_30727) SubClassOf [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Cyprinoidei](http://purl.obolibrary.org/obo/NCBITaxon_30727) [core.owl]
- [Teleostei](http://purl.obolibrary.org/obo/NCBITaxon_32443) SubClassOf [Neopterygii](http://purl.obolibrary.org/obo/NCBITaxon_41665) [core.owl]
- [Ostariophysi](http://purl.obolibrary.org/obo/NCBITaxon_32519) SubClassOf [Otomorpha](http://purl.obolibrary.org/obo/NCBITaxon_186634) [core.owl]
- [Tetrapoda](http://purl.obolibrary.org/obo/NCBITaxon_32523) SubClassOf [Dipnotetrapodomorpha](http://purl.obolibrary.org/obo/NCBITaxon_1338369) [core.owl]
- [Amniota](http://purl.obolibrary.org/obo/NCBITaxon_32524) SubClassOf [Tetrapoda](http://purl.obolibrary.org/obo/NCBITaxon_32523) [core.owl]
- [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674) SubClassOf [Amniota](http://purl.obolibrary.org/obo/NCBITaxon_32524) [core.owl]
- [Neopterygii](http://purl.obolibrary.org/obo/NCBITaxon_41665) SubClassOf [Actinopteri](http://purl.obolibrary.org/obo/NCBITaxon_186623) [core.owl]
- [Cypriniformes](http://purl.obolibrary.org/obo/NCBITaxon_7952) SubClassOf [Cypriniphysae](http://purl.obolibrary.org/obo/NCBITaxon_186627) [core.owl]
- [Danio](http://purl.obolibrary.org/obo/NCBITaxon_7954) SubClassOf [Danioninae](http://purl.obolibrary.org/obo/NCBITaxon_2743711) [core.owl]
- [uterine horn](http://purl.obolibrary.org/obo/UBERON_0002247) SubClassOf [connected to](http://purl.obolibrary.org/obo/RO_0002170) some [fallopian tube](http://purl.obolibrary.org/obo/UBERON_0003889) [core.owl]
- [fallopian tube](http://purl.obolibrary.org/obo/UBERON_0003889) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674) [core.owl]
- [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Actinopterygii](http://purl.obolibrary.org/obo/NCBITaxon_7898) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Sarcopterygii](http://purl.obolibrary.org/obo/NCBITaxon_8287) [core.owl]
- [part_of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [overlaps](http://purl.obolibrary.org/obo/RO_0002131) [core.owl]
- [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [core.owl]
- [overlaps](http://purl.obolibrary.org/obo/RO_0002131) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [core.owl]
- [connected to](http://purl.obolibrary.org/obo/RO_0002170) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [core.owl]



# Ontologies used: 
- core.owl (http://purl.obolibrary.org/obo/uberon/core.owl)

**Comment by matentzn** [comment]
I have removed the mapping again, but invite you to reinstate it after the release. We can make another release fairly quickly

https://github.com/obophenotype/uberon/commit/3ecc9031cddbc4e34cf3841a2e5b972b24df83bf

**Comment by shawntanzk** [comment]
> [uterine horn](http://purl.obolibrary.org/obo/UBERON_0002247) SubClassOf [connected to](http://purl.obolibrary.org/obo/RO_0002170) some [fallopian tube](http://purl.obolibrary.org/obo/UBERON_0003889)
> [fallopian tube](http://purl.obolibrary.org/obo/UBERON_0003889) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674)

I'm guessing that uterine horn is a thing in fishes but fallopian tubes arent - this feels like an important connected to axiom, and it brings up the question on how mammalia centric is uberon 

will look into this more either way, but im guessing its the above issue

**Comment by paolaroncaglia** [comment]
> > [uterine horn](http://purl.obolibrary.org/obo/UBERON_0002247) SubClassOf [connected to](http://purl.obolibrary.org/obo/RO_0002170) some [fallopian tube](http://purl.obolibrary.org/obo/UBERON_0003889)
> > [fallopian tube](http://purl.obolibrary.org/obo/UBERON_0003889) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674)
> 
> I'm guessing that uterine horn is a thing in fishes but fallopian tubes arent - this feels like an important connected to axiom, and it brings up the question on how mammalia centric is uberon
> 
> will look into this more either way, but im guessing its the above issue

Briefly: Fallopian tube is strictly mammalian, the broader term is oviduct. Fish uterine horn should be connected to oviduct (if that's biologically the case).

**Comment by shawntanzk** [comment]
Thanks @paolaroncaglia, that was super useful - I guess then the question is if we should change uterine horn to connected to some oviduct instead - that way its accurate to fish too (will check if this is true)

don't want to hold up the release, so maybe keep the mapping removed and ill try to figure it outside of the release

**Comment by shawntanzk** [comment]
Trying to fix this - changing connected to axiom still leaves part of some uterus as an issue
![Screenshot 2022-04-12 at 13 49 48](https://user-images.githubusercontent.com/76212760/162966078-76359985-e0f2-4879-92a8-a2a7cc6bc19d.png)
From a search Zebrafish defs have a uterine horn, but I guess they don't have uterus which I guess makes sense since they have ex uteri embryos 
Is removing the part of axiom sensible in this case? it has a source "MA" on it?

**Comment by shawntanzk** [comment]
> From a search Zebrafish defs have a uterine horn

Take this back, the paper was talking about mice lol - actually that's a good question, if zebrafish do not have uterus, do they have a uterine horn?

**Comment by shawntanzk** [comment]
Ok should have done this at the start, just checked, ZFA_0005829 is schlemm's canal which is "Vessel that drains aqueous humor from the eye" - this is almost certainly not equiv to uterine tube
It should be mapped to http://purl.obolibrary.org/obo/UBERON_0004029 instead

**Comment by cmungall** [comment]
It may be odd for human use cases for the jugular not to be part of the neck

Taxonomy gci would be a little better

I think the best solution would be to generalize neck in a way that keeps
the fish people happy. Fish may lack a neck proper but they have an
analogous region of the craniocervucal region with the same skeletal
elements

**Comment by shawntanzk** [comment]
Happy to add a taxonomy GCI, not sure how to generalize neck to fish. 
I'm guessing taxonomy gci should be on mammalia? so like: 
```
'jugular vein' and ('in taxon' some Mammalia) SubClassOf 'part of' some neck
```

**Comment by shawntanzk** [comment]
FBdv unsats is caused by:
[occurrent](http://purl.obolibrary.org/obo/BFO_0000003) DisjointWith [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [continuant](http://purl.obolibrary.org/obo/BFO_0000002)

All are similar patterns which is: 
[FBdv_00005336](http://purl.obolibrary.org/obo/FBdv_00005336) EquivalentTo [larval stage](http://purl.obolibrary.org/obo/UBERON_0000069) and [instar larval stage](http://purl.obolibrary.org/obo/UBERON_0004730) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Drosophila melanogaster](http://purl.obolibrary.org/obo/NCBITaxon_7227))

Larval stage (or whatever the stage is on the axiom) is and occurent, while Drosophila is a continuant

Not sure how to fix this

**Comment by shawntanzk** [comment]
@matentzn i think this is with all developmental axioms in bridge actually:

  - [HsapDv_0000006](http://purl.obolibrary.org/obo/HsapDv_0000006) EquivalentTo [blastula stage](http://purl.obolibrary.org/obo/UBERON_0000108) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606))
  - [ZFS_0000044](http://purl.obolibrary.org/obo/ZFS_0000044) EquivalentTo [post-juvenile adult stage](http://purl.obolibrary.org/obo/UBERON_0000113) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Danio](http://purl.obolibrary.org/obo/NCBITaxon_7954))
   - [XAO_1000001](http://purl.obolibrary.org/obo/XAO_1000001) EquivalentTo [zygote stage](http://purl.obolibrary.org/obo/UBERON_0000106) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Xenopus <genus>](http://purl.obolibrary.org/obo/NCBITaxon_8353))
     - [FMA_24120](http://purl.obolibrary.org/obo/FMA_24120) EquivalentTo [life cycle stage](http://purl.obolibrary.org/obo/UBERON_0000105) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606))
    - [MmusDv_0000017](http://purl.obolibrary.org/obo/MmusDv_0000017) EquivalentTo [neurula stage](http://purl.obolibrary.org/obo/UBERON_0000110) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Mus musculus](http://purl.obolibrary.org/obo/NCBITaxon_10090))
    - [WBls_0000093](http://purl.obolibrary.org/obo/WBls_0000093) EquivalentTo [post-embryonic stage](http://purl.obolibrary.org/obo/UBERON_0000092) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Caenorhabditis](http://purl.obolibrary.org/obo/NCBITaxon_6237))
    
 I don't really see anything wrong with the axioms per se, think its more of a limitation on the modelling? 
 My guess is this overarching problem is the the cause of all the remaining unsats - I've skimmed through them and they all seem to be that way

**Comment by dosumis** [comment]
> [FBdv_00005336](http://purl.obolibrary.org/obo/FBdv_00005336) EquivalentTo [larval stage](http://purl.obolibrary.org/obo/UBERON_0000069) and [instar larval stage](http://purl.obolibrary.org/obo/UBERON_0004730) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Drosophila melanogaster](http://purl.obolibrary.org/obo/NCBITaxon_7227))

Looks like that part_of should be changed to in_taxon.  Is this coming from a bridging file?

**Comment by dosumis** [comment]
NCBI taxon terms are are subclasses of 'organism', which I think makes sense (I am an instance of and organism and an instance the class Homo sapiens).  But that means you cannot use part_of to link an occurrent (in the above case a stage) to a continuant (an organism).

**Comment by shawntanzk** [comment]
Shall we change all bridge file `intersection_of: part_of NCBITaxon:` to `intersection_of: in_taxon NCBITaxon:` (or whatever in_taxon OP is in obo, and of course changing the owl file too?) or just those with unsats? 
Also not sure how the bridges are generated - if we make a change they wont get overridden right?

**Comment by matentzn** [comment]
Need to sharen in obo slack uberon channel and tag @cmungall

**Comment by dosumis** [comment]
> that's not wrong and probably the easiest to do in the short term but
longer term I am favoring generalizing neck - can you make a separate

Isn't this a separate issue?

**Comment by shawntanzk** [comment]
@dosumis it is - problem shifted from that part_of -> in_taxon (initial problem was neck stuff). Anyway I've created another ticket for the neck stuff.

**Comment by cmungall** [comment]
Here's my summary

- make a taxon GCI for now to be able to move forward and close this issue and make a release
- flip it back to a full relationship if we decide to generalize on neck as per #2417. 
- for the decision as to whether to change the pattern in bridge axioms - this is pretty huge and we have to be able to work through the implications. This deserves its own issue (AFAICR we were also discussing this for the stages too)?

**Comment by shawntanzk** [comment]
the part_of axioms in bridge are now a blocker for making a release without a hack that @matentzn implemented right?

**Comment by matentzn** [comment]
There is no hack - I cant run a release at the moment!

**Comment by shawntanzk** [comment]
Fixed

**Comment by uberon** [comment]
I think for now the most conservative thing is to selectively change these
from part-of for stage terms only. I believe these get made from the stages
repo, not this one (sorry for the descent into build pipeline hell... and
sorry these were never caught before!)
