### ISSUE TITLE
Include proper taxon constrait checking in general CI

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2374]
For debugging purposes, I am running:

```
sh run.sh make reports/taxon-constraint-check.txt MIR=false IMP=false PAT=false BRI=true -B
robot explain -i tmp/uberon-edit-plus-tax-equivs.owl --reasoner ELK -M unsatisfiability --unsatisfiable random:10 --explanation unsat.md
```

Then pasting unsat.md in GitHub

_Originally posted by @matentzn in https://github.com/obophenotype/uberon/issues/2367#issuecomment-1084855364_

**Comment by matentzn** [comment]
Reinstate `xref: ZFA:0005829` to test this.

**Comment by anitacaron** [comment]
Is this related to https://github.com/obophenotype/uberon/issues/2613?

**Comment by matentzn** [comment]
Maybe, and perhaps fixed by https://github.com/obophenotype/uberon/pull/2388 but it does not seem to work atm, i.e. I cannot get it to fail
