### ISSUE TITLE
Make a decision on Develops from property chain - accept or remove

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2381]
Develops from property chain removal (https://github.com/obophenotype/uberon/pull/1808) caused a lot of useful axioms to not be there. 
While the removal was to solve some weird axioms @balhoff found, some of the axioms that it removed in uberon are still useful.
This leads to a bit of a conundrum on if we should remove it or not and needs discussion. 
However, we cannot let this be a blocker anymore, so our plan is to insert the property chain as a component that is left out in base file. 
This will allow the inferences to still be there, but leave it out from ontologies that use the base file (which hopefully more and more are)

This is a temp fix just to get the release out, but we still need to make a final decision on it: 
should we  generally accept it or generally reject it? 

Tagging @cmungall & @dosumis too
Related to https://github.com/obophenotype/uberon/pull/2376

**Comment by shawntanzk** [comment]
`develops_from o part_of -> develops_from` - this is ok (though it should be restricted to anatomical entity on the left side too) 
`part_of o develops_from -> develops_from` - is ok if left side is restricted to anatomical entity
Difficulty in expressing in owl? 

For now: 

- Get rid of 2nd one, but add back the first one
- Make a ticket on 2nd one to decide how to handle

**Comment by balhoff** [comment]
It is easy to restrict to anatomical entity using rolification. Not sure if that works in Elk, but it does work in Whelk. I still think both chains are incorrect. In any case the chains should be added to RO and not Uberon.

**Comment by shawntanzk** [comment]
@balhoff - could you give some concerns with the above patterns so we can understand better please? 
atm we will leave this alone, and only implement once we have a clear strategy on how to do it.

**Comment by matentzn** [comment]
As of today, they are both still in there.

**Comment by cmungall** [comment]
We agreed a year ago to get rid of the 2nd, no controversy

Let's make a separate RO issue for adding the rolification constraint on the 1st. This is low priority as I will wager there are zero tbox existentials in OBO connecting organism to anything bigger. But the point is this should be a RO issue

**Comment by anitacaron** [comment]
Issue to remove `part_of o develops_from -> develops_from` in Uberon:
- #2723 
Issue to add `develops_from o part_of -> develops_from` in RO:
- https://github.com/oborel/obo-relations/issues/784
