### ISSUE TITLE
SPARQL taxon expansion does nothing

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2382]
Right now the goal to generate the intermediate uberon (processed version) looks like this:

```
$(OWLSRC): tmp/uberon-merged.owl $(COMPONENTSDIR)/disjoint_union_over.ofn $(REPORTDIR)/$(SRC)-gocheck $(REPORTDIR)/$(SRC)-iconv $(SCRIPTSDIR)/expand-dbxref-literals.pl
	echo "STRONG WARNING: issues/contributor.owl needs to be manually updated."
	$(OWLTOOLS) --no-logging $< $(COMPONENTSDIR)/disjoint_union_over.ofn issues/contributor.owl --merge-support-ontologies --expand-macros -o  $@ &&  $(SCRIPTSDIR)/expand-dbxref-literals.pl $@ > $@.tmp
	# The previous step seems to be necessary because somehow the expand-dbxref-literals script expects the owtools output.. No idea why
	$(ROBOT) merge -i $@.tmp \
		query \
			--update $(SPARQLDIR)/taxon_constraint_never_in_taxon.ru \
			--update $(SPARQLDIR)/remove_axioms.ru \
			--update $(SPARQLDIR)/delete-definition-dot.ru \
		merge -i imports/ro_import.owl -o $@
```

```
--expand-macros
```

Not only adds the correct Disjointness axioms, it also _removes_ the annotations that are being expanded. So, before

```
--update $(SPARQLDIR)/taxon_constraint_never_in_taxon.ru 
```

kicks in, the never_in_taxon has already been dropped: so it does nothing.

This ticket should be part of the great `makefile revision`. Maye we add a tag for that process @shawntanzk?

**Comment by balhoff** [comment]
Let's get this moving along: https://github.com/ontodev/robot/pull/964

I think I need to update the annotation property IRI with the one you added to OMO.

**Comment by matentzn** [comment]
Yeah agree.. If you change the IRI I will review the PR again, and get James to take a look as well.

**Comment by balhoff** [comment]
@shawntanzk https://github.com/oborel/obo-relations/pull/616

To make that work, we need to merge that PR, make an RO release, refresh Uberon RO import, add `expand` into Uberon ROBOT chains somewhere. I think we will want to run all expansions for QC, but suppress 'present in taxon' for release output (there is an argument for that).

**Comment by anitacaron** [comment]
- [ ] merge that PR
- [ ] make a RO release
- [ ] refresh Uberon RO import
- [ ] update to ODK v1.3.1
- [ ] add expand into Uberon ROBOT chains somewhere

**Comment by matentzn** [comment]
http://robot.obolibrary.org/expand
