### ISSUE TITLE
ABA-Uberon bridge file updates

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2384]
We have some expert-curated stuff for ABA-uberon bridge files that need to be updated 
[CCF_to_UBERON.xlsx](https://github.com/obophenotype/uberon/files/8428351/CCF_to_UBERON.xlsx)

- Ignore verify for now
- Remove mapping for nok  - @shawntanzk to find out what the alternative is (can we replace with something more generic for now) 
- Change accordingly for gen

**Comment by patrick-lloyd-ray** [comment]
@shawntanzk, let me know if anything is unclear with the mappings or if you need anything at all.

**Comment by patrick-lloyd-ray** [comment]
> or the nok -> is there an alternative we can map to? something perhaps more generic or something?

If I could find a mapping that worked, I put it in column F. If F is empty, there should be 'add term' in G (meaning we would like to add a new term).

> we assumed verify meant that it still needed to be verified

If column F is blank, then they are in need of verification. If there is a term in column F, that has been verified.

**Comment by shawntanzk** [comment]
Looks like many are fixed already - found some that aren't so will still go through the whole list and make the fixes. 
New terms don't seem to have been added, will slowly get through them - might take awhile as I will need to do research on each of them and all

Some terms are confusing - if its sensible to change the status, I will: 
eg <http://purl.obolibrary.org/obo/DMBA_16339> (intercalate nucleus) - is nok and has add term but its mapped to exactly  the same thing it uberon as http://purl.obolibrary.org/obo/HBA_9572 ( intercalate nucleus)

**Comment by shawntanzk** [comment]
To verify @patrick-lloyd-ray 
MBA_820 (inferior colliculus, dorsal nucleus) is mapped to the same as MBA_811 (inferior colliculus, central nucleus) - UBERON_0002563 (central nucleus of inferior colliculus)
Bridge file currently maps MBA_820 to UBERON_0002577 (pericentral nucleus of inferior colliculus) which seems more correct - I hence didnt want to change it.

**Comment by shawntanzk** [comment]
There are some marked "cerebellum" which dont seem to be in the bridge file. 
The MBA stuff seem to require specific layers to be added to UBERON anyway.
My suggestion is that I add them to uberon and add them to bridge file after.

**Comment by shawntanzk** [comment]
MBA_985 (primary motor area) is mapped to primary motor cortex in uberon which is right from what I see in the brain atlas - it is marked ok but also has "add term" to it - will ignore it for now, but in case it means something, please do let me know

**Comment by shawntanzk** [comment]
DMBA Long list of terms to add (kept this separate as its really long and clustered together (some are 'HAS PARALLEL', not sure what this means, but best to check for mappings before adding anything anyway): 

- [ ] blood vessels of spinal cord
- [ ] ventricular zone of SpA
- [ ] mantle zone of SpA
- [ ] ventricular zone of SpB
- [ ] mantle zone of SpB
- [ ] ventricular zone of SpF
- [ ] mantle zone of SpF
- [ ] periventricular stratum of SpF
- [ ] intermediate stratum of SpF
- [ ] superficial stratum of SpF
- [ ] ventricles, spinal cord
- [ ] ventricles, SpC roof plate
- [ ] ventricles, SpC alar plate
- [ ] ventricles, SpC basal plate (anterior   horn)
- [ ] ventricles, SpC floor plate
- [ ] SpC roof plate
- [ ] SpC alar plate
- [ ] medial (cornucommissural) part of the   spinal alar plate
- [ ] ventricular zone of the SpAM
- [ ] mantle zone of the SpAM
- [ ] periventricular stratum of the SpAM
- [ ] alar medial part of Rexed's layer 10
- [ ] intermediate stratum of the SpAM
- [ ] cornucommissural part of Rexed's layer 4
- [ ] internal basilar (cervical) nucleus
- [ ] dorsal (thoracic) nucleus of Clarke
- [ ] lumbar dorsal commissural nucleus
- [ ] sacral dorsal commissural nucleus
- [ ] superficial stratum of the SpAM
- [ ] lateral (dorsal horn) part of the spinal   alar plate
- [ ] ventricular zone of the SpAL
- [ ] alar lateral part of Rexed's layer 10
- [ ] mantle zone of the SpAL
- [ ] periventricular stratum of the SpAL
- [ ] intermediate stratum of the SpAL
- [ ] Rexed's layer 3
- [ ] Rexed's layer 4 (main or lateral part)
- [ ] superficial stratum of the SpAL
- [ ] Rexed's layer 1 (marginal layer)
- [ ] Rexed's layer 2 (gelatinous substance)
- [ ] ventral (liminal) part of the spinal alar   plate
- [ ] ventricular zone of the SpAV
- [ ] mantle zone of the SpAV
- [ ] periventricular stratum of the SpAV
- [ ] alar ventral part of Rexed's layer 10
- [ ] intermediate stratum of the SpAV
- [ ] Rexed's layer 5 (neck of dorsal horn)
- [ ] medial (deep) part of 5Sp
- [ ] lateral (superficial) part of 5Sp
- [ ] Rexed's layer 6 (basis of dorsal horn)
- [ ] medial (deep) part of 6Sp
- [ ] lateral (superficial) part of 6Sp
- [ ] superficial stratum of the SpAV
- [ ] SpC basal plate   (anterior horn)
- [ ] lateral part of SpB
- [ ] ventricular zone of SpBL
- [ ] mantle zone of SpBL
- [ ] periventricular stratum of SpBL
- [ ] basal lateral part of Rexed's layer 10
- [ ] intermediate stratum of SpBL
- [ ] Rexed's layer 7 (intermediate zone)
- [ ] lumbar precerebellar nucleus
- [ ] sacral precerebellar nucleus
- [ ] central cervical nucleus
- [ ] ventral horn lateral interneurons
- [ ] intermediomedial   nucleus
- [ ] intermediolateral nucleus (lateral horn)
- [ ] laterodorsal commissural nucleus
- [ ] sacral parasympathetic preganglionic   neurons
- [ ] superficial stratum of SpBL
- [ ] intermediate part of SpB
- [ ] ventricular zone of SpBI
- [ ] mantle zone of SpBI
- [ ] periventricular stratum of SpBI
- [ ] basal intermediate part of Rexed's layer   10
- [ ] intermediate stratum of SpBI
- [ ] Rexed's layer 9
- [ ] motoneuron columns
- [ ] medial motoneuron columns
- [ ] lateral motoneuron columns
- [ ] central motoneuron columns
- [ ] Onuf's nucleus
- [ ] medial (anal) part of Onuf's nucleus
- [ ] lateral (urethral) part of Onuf's nucleus
- [ ] superficial stratum of SpBI
- [ ] medial part of SpB
- [ ] ventricular zone of SpBM
- [ ] mantle zone of SpBM
- [ ] periventricular stratum of SpBM
- [ ] basal medial part of Rexed's layer 10
- [ ] intermediate stratum of SpBM
- [ ] Rexed's layer 8
- [ ] ventral horn medial interneurons
- [ ] superficial stratum of SpBM
- [ ] SpC floor plate

**Comment by shawntanzk** [comment]
spot checked on row 4670-5051 -> they don't seem to be in bridge file at all

**Comment by shawntanzk** [comment]
These mappings seem a bit odd - its MBA but mapped to Broadann area which can't be right yeah?

superclass_iri | subclass_name | subclass_iri | Analysis | Recommended   Mapping | Type of mapping   issue
-- | -- | -- | -- | -- | --
<http://purl.obolibrary.org/obo/UBERON_0010314> | prelimbic area, layer 6b | <http://purl.obolibrary.org/obo/MBA_132> | Verify | Brodmann (1909)   area 32 (http://purl.obolibrary.org/obo/UBERON_0013560) | OR ADD LAYER
<http://purl.obolibrary.org/obo/UBERON_0010314> | prelimbic area, layer 1 | <http://purl.obolibrary.org/obo/MBA_171> | Verify | Brodmann (1909)   area 32 (http://purl.obolibrary.org/obo/UBERON_0013560) | OR ADD LAYER
<http://purl.obolibrary.org/obo/UBERON_0010314> | anterior cingulate area, layer 6a | <http://purl.obolibrary.org/obo/MBA_179> | Verify | Brodmann (1909) area   24 (http://purl.obolibrary.org/obo/UBERON_0006101) | OR ADD LAYER

**Comment by patrick-lloyd-ray** [comment]
> Some terms are confusing - if its sensible to change the status, I will:
eg http://purl.obolibrary.org/obo/DMBA_16339 (intercalate nucleus) - is nok and has add term but its mapped to exactly the same thing it uberon as http://purl.obolibrary.org/obo/HBA_9572 ( intercalate nucleus)

Yeah, that might be a problem that has since been fixed, the mapping file I received is a few years old, so it's possible some of these have gotten patched up since.

**Comment by patrick-lloyd-ray** [comment]
> These mappings seem a bit odd - its MBA but mapped to Broadann area which can't be right yeah?

Yeah, that's a mistake -- they are supposed to be: prelimbic area, layer [X].

**Comment by patrick-lloyd-ray** [comment]
> Doesn't have "Add Term" in excel sheet but mapping seems wrong and needs term adding:

Yeah, there are going to be some of these too -- it's a lot of lines/structures to check, so I've surely made some mistakes trying to get these done sort-of quickly. I appreciate the verifications.

**Comment by patrick-lloyd-ray** [comment]
> Layer stuff (note, dont think they need be added, but can instead be like 'has soma location' some 'primary somatosensory area' and 'has soma location' some 'cortical layer 1' etc.):

For these (and ones like them), the atlases are pretty fine-grained but this sounds like a fine solution for annotating cell location.

**Comment by patrick-lloyd-ray** [comment]
> MBA_985 (primary motor area) is mapped to primary motor cortex in uberon which is right from what I see in the brain atlas - it is marked ok but also has "add term" to it - will ignore it for now, but in case it means something, please do let me know

Yes, that is a typo.

**Comment by patrick-lloyd-ray** [comment]
> DMBA Long list of terms to add (kept this separate as its really long and clustered together (some are 'HAS PARALLEL', not sure what this means, but best to check for mappings before adding anything anyway):

HAS PARALLEL means (as I was using it) that the structure is parallel to some other structure that already exists in UBERON. e.g., central glial substance is parallel to or surrounds the central canal.

**Comment by shawntanzk** [comment]
I've changed the mapping for MBA_436 (columns of the fornix) to UBERON_0004680 (body of fornix - has exact synonym "columns of fornix") - it was previously mapped to body of fornix (UBERON_0004680) with "add term"

**Comment by patrick-lloyd-ray** [comment]
I think @lydiang would like to be in the loop here.

**Comment by shawntanzk** [comment]
For layers:
general class with part relations to both

eg primary somatosensory area, barrel field, layer 1
Regional part of cerebral layer and part of "Primary somatosensory area, barrel field" and part of "layer 1"

**Comment by shawntanzk** [comment]
@patrick-lloyd-ray - looking to start adding stuff to bridge file and want to provide provenance to the source of mapping. I'm guessing it isn't just you who looked at it and there isn't a easy way to separate who did what - Could we put source as allen institute using https://ror.org/03cpe7c52

**Comment by shawntanzk** [comment]
@tgbugs - this is the ticket. See this comment for meeting https://github.com/obophenotype/uberon/issues/2384#issuecomment-1098796442

**Comment by patrick-lloyd-ray** [comment]
> Perhaps we could use part of the UBERON call on 25/04/22 to discuss this?

I can make the call on the 25th. If we need a separate call, then that would be fine as well. 

> Could we put source as allen institute using https://ror.org/03cpe7c52

Absolutely.

**Comment by cmungall** [comment]
I'll be there!

**Comment by shawntanzk** [comment]
Bridge files generated from using xrefs through https://github.com/obophenotype/uberon/blob/master/src/scripts/make-bridge-ontologies-from-xrefs.pl

**Comment by shawntanzk** [comment]
Differentiate provenance from those that came originally from the bridge file to those that come from the ABA experts.
Original bridge - credit to Chris Mungall; Approved by experts using Allen Brain Institute ROR - using another annotation. @shawntanzk to pick whatever AP for now, and we can change this when we discuss further.

**Comment by patrick-lloyd-ray** [comment]
> Should I map MBA_911 as equivalent to UBERON_0002618 instead of UBERON_0001644?

Yes, MBA_911 should be mapped to UBERON_0002618 because the synonyms for UBERON_0002618 more closely align with MBA_911 than UBERON_0001644 (i.e., MBA_911 is closer to 'trochlear nerve tract' or 'trochlear nerve fibers' than the entire nerve -- just a difference in atlas/ontology terminology, I believe, not any fundamental disagreement in structure).

MBA_911 is marked 'IVn' in this diagram, if that helps:
![image](https://user-images.githubusercontent.com/67486986/165590940-e7998092-e931-4db7-97fb-1d6b39fe38d5.png)

For DMBA_17746, it's the converse: UBERON_0002731 is "Either of the two roots that come of the vestibulocochlear nerve." but the atlas has it slightly differently, so it's better mapped to UBERON_0001648. (in this diagram DMBA_17746 is marked as '8n'): 
![image](https://user-images.githubusercontent.com/67486986/165593509-6de5e8c3-d10b-4235-aa0c-eb20874f8e19.png)

Also, DMBA is developmental, so the mappings are often not straightforward. If you look at the MBA, it's more closely aligned with UBERON for that structure, I believe. 

> vomeronasal nerve (MBA_949) is mapped to vomeronasal nerve (UBERON_0009121) - but it writes `Add Term`

Hmm, the only thing I can think of is that vomeronasal nerve is not present in adult humans but present in adult macrosmatic mammals (mouse), so I think that's why our anatomists found issue there. But, I see there is a note on UBERON_0009121 to that effect, so I'll leave it up to you.

**Comment by shawntanzk** [comment]
thanks! thats super helpful :) will map accordingly

**Comment by cmungall** [comment]
I think if we resolve this issue

- #286.  

then some of this becomes easier

**Comment by shawntanzk** [comment]
MBA_634 (nucleus of the posterior commissure) was given ok for both diencephalic nucleus UBERON_0006569 and nucleus of the posterior commissure UBERON_0002711. I've picked nucleus of the posterior commissure UBERON_0002711.

MBA_1019 corticospinal tract, crossed is mapped to both corticospinal tract UBERON_0002707 and lateral corticospinal tract UBERON_0002589 - I have chosen lateral corticospinal tract UBERON_0002589 as that was a original verified mapping rather than one chosen from a `gen` status

DMBA_17773 lateral olfactory tract is mapped to both olfactory tract UBERON_0002265 and lateral olfactory stria UBERON_0001888. I have chosen lateral olfactory stria UBERON_0001888 as hat was a original verified mapping rather than one chosen from a `gen` status.

MBA_665 lateral olfactory tract, body is mapped to both olfactory tract UBERON_0002265 and lateral olfactory stria UBERON_0001888.  I have chosen lateral olfactory stria UBERON_0001888 as hat was a original verified mapping rather than one chosen from a `gen` status.

MBA_105 superior olivary complex, medial part is mapped to both UBERON_0002782 medial superior olivary nucleus and UBERON_0002128 superior olivary complex. I have chosen UBERON_0002782 medial superior olivary nucleus as that was a original verified mapping rather than one chosen from a `gen` status.

MBA_212 main olfactory bulb, glomerular layer is mapped to both UBERON_0005377 olfactory bulb glomerular layer and UBERON_0023934 olfactory bulb main glomerular layer. I have chosen UBERON_0005377 olfactory bulb glomerular layer as it is mapped twice that way (as opposed to once the other way)

MBA_554 bed nuclei of the stria terminalis, anterior division, oval nucleus is mapped to both UBERON_0011176 oval nucleus of stria terminalis and UBERON_0001880 bed nucleus of stria terminalis . I have chosen UBERON_0011176 oval nucleus of stria terminalis as that was a original verified mapping rather than one chosen from a `gen` status.

MBA_149 paraventricular nucleus of the thalamus is mapped to both UBERON_0002708 posterior periventricular nucleus  and UBERON_0001920 paraventricular nucleus of thalamus. I've chosen UBERON_0001920 paraventricular nucleus of thalamus as it is more similar. 

DMBA_15999 posterolateral cortical amygdaloid area is mapped to both UBERON_0034999 posterolateral cortical amygdaloid nucleus and UBERON_0035001 posteromedial cortical amygdaloid nucleus. I have chosen UBERON_0034999 posterolateral cortical amygdaloid nucleus as that was a original verified mapping rather than one chosen from a `gen` status

continue from [MBA_981](http://purl.obolibrary.org/obo/MBA_981)

**Comment by patrick-lloyd-ray** [comment]
> MBA_634 (nucleus of the posterior commissure) was given ok for both diencephalic nucleus UBERON_0006569 and nucleus of the posterior commissure UBERON_0002711. I've picked nucleus of the posterior commissure UBERON_0002711.

Sounds good!

> MBA_1019 corticospinal tract, crossed is mapped to both corticospinal tract UBERON_0002707 and lateral corticospinal tract UBERON_0002589 - I have chosen lateral corticospinal tract UBERON_0002589 as that was a original verified mapping rather than one chosen from a gen status

Yes, that works. 

> DMBA_17773 lateral olfactory tract is mapped to both olfactory tract UBERON_0002265 and lateral olfactory stria UBERON_0001888. I have chosen lateral olfactory stria UBERON_0001888 as hat was a original verified mapping rather than one chosen from a gen status.

> MBA_665 lateral olfactory tract, body is mapped to both olfactory tract UBERON_0002265 and lateral olfactory stria UBERON_0001888. I have chosen lateral olfactory stria UBERON_0001888 as hat was a original verified mapping rather than one chosen from a gen status.

Yep, that's fine. 

> MBA_105 superior olivary complex, medial part is mapped to both UBERON_0002782 medial superior olivary nucleus and UBERON_0002128 superior olivary complex. I have chosen UBERON_0002782 medial superior olivary nucleus as that was a original verified mapping rather than one chosen from a gen status.

Yes, UBERON_0002782 is right for that one. 

> MBA_212 main olfactory bulb, glomerular layer is mapped to both UBERON_0005377 olfactory bulb glomerular layer and UBERON_0023934 olfactory bulb main glomerular layer. I have chosen UBERON_0005377 olfactory bulb glomerular layer as it is mapped twice that way (as opposed to once the other way)

Yes, that makes sense to me. 

> MBA_554 bed nuclei of the stria terminalis, anterior division, oval nucleus is mapped to both UBERON_0011176 oval nucleus of stria terminalis and UBERON_0001880 bed nucleus of stria terminalis . I have chosen UBERON_0011176 oval nucleus of stria terminalis as that was a original verified mapping rather than one chosen from a gen status.

Yes, it should be UBERON_0011176.

> MBA_149 paraventricular nucleus of the thalamus is mapped to both UBERON_0002708 posterior periventricular nucleus and UBERON_0001920 paraventricular nucleus of thalamus. I've chosen UBERON_0001920 paraventricular nucleus of thalamus as it is more similar.

Yes, should be UBERON_0001920.

> DMBA_15999 posterolateral cortical amygdaloid area is mapped to both UBERON_0034999 posterolateral cortical amygdaloid nucleus and UBERON_0035001 posteromedial cortical amygdaloid nucleus. I have chosen UBERON_0034999 posterolateral cortical amygdaloid nucleus as that was an original verified mapping rather than one chosen from a gen status

Yes, that makes sense to me. 

> MBA_578 bed nuclei of the stria terminalis, posterior division, principal nucleus is mapped to both UBERON_0001880 bed nucleus of stria terminalis and UBERON_0011178 principal nucleus of stria terminalis. I have chosen UBERON_0011178 principal nucleus of stria terminalis as that was an original verified mapping rather than one chosen from a gen status.

Yes, that works. 

> MBA_594 bed nuclei of the stria terminalis, posterior division, transverse nucleus is mapped to both UBERON_0011179 transverse nucleus of stria terminalis and UBERON_0001880 bed nucleus of stria terminalis. I have chosen UBERON_0011179 transverse nucleus of stria terminalis as that was an original verified mapping rather than one chosen from a gen status.

Yes, that works too. 

> MBA_1028 corticospinal tract, uncrossed is mapped to both UBERON_0002760 ventral corticospinal tract and UBERON_0002707 corticospinal tract. I have chosen UBERON_0002760 ventral corticospinal tract as that was an original verified mapping rather than one chosen from a gen status.

Okay, that works. 

> DMBA_16926 cerebellar white matter is mapped to both UBERON_0002317 white matter of cerebellum and UBERON_0024045 white matter of the cerebellar cortex. I have chosen UBERON_0002317 white matter of cerebellum as it is mapped that way 3/4 times

Yes, UBERON_0002317 works best. 

> DMBA_17749 accessory nerve root is mapped to both UBERON_0014615 accessory nerve root and UBERON_0002019 accessory XI nerve. I have chosen UBERON_0014615 accessory nerve root as it is more similar.

Yes, UBERON_0014615 makes sense for this mapping. #298 might affect this but I'll defer to your design decisions. 

> MBA_30 periventricular hypothalamic nucleus, anterior part is mapped to both UBERON_0002622 preoptic periventricular nucleus and UBERON_0014667 periventricular nucleus of the hypothalamus. I have selected (subclass part of) UBERON_0014667 periventricular nucleus of the hypothalamus as it is more similar.

Yes, that makes sense to me. 

> MBA_436 columns of the fornix is mapped to both UBERON_0004680 column of fornix and UBERON_0004680 body of fornix. I have selected UBERON_0004680 column of fornix as it is more similar.

Okay, that's fine. 

> MBA_908 anterior commissure, temporal limb is mapped to both anterior commissure anterior part UBERON_0003039 and UBERON_0003043 posterior part of anterior commissure. I've remapped it to subclass part of UBERON:0000935 anterior commissure for safety

Okay, that's a good idea. Thanks, @shawntanzk!

**Comment by shawntanzk** [comment]
@patrick-lloyd-ray is sublaterodorsal nucleus (SLD) the same as sublaterodorsal tegmental nucleus? (from literature that's all I seem to be able to find and the acronym is the same)

**Comment by shawntanzk** [comment]
Note to self: 
rhinocele is problematic as uberon obsoleted rhinencephalon (UBERON_0008981) with the reason:
"Obsoleted because The term rhinencephalon has been used to describe different structures at different points in time.[ISBN 0-8493-8631-4]. May refer to: a specific structure in aves; a part of the brain involved with olfaction;"
I'd imagine that the rhinocele will have the same issue. 
Consider mapping it as subclass of part of telencephalic ventricle (UBERON:0002285) instead

**Comment by shawntanzk** [comment]
@patrick-lloyd-ray - could you help me with the questions found in: https://docs.google.com/document/d/1DYiaGNa8KLZZRU7pxd9XL6YJwvXsap-JTs3g3tM4Meo/edit
Feel free to answer directly on the google docs, thanks :)

**Comment by patrick-lloyd-ray** [comment]
Will do -- might take me a bit to get to them, but just ping me if anything needs immediate attention and I'll prioritize it.

**Comment by patrick-lloyd-ray** [comment]
I'm fairly certain this can be closed.
