### ISSUE TITLE
NTR: stroma of the human mammary gland

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2393]
**Comment:**The following terms are needed to indicate the origin of the tissues used establish cell lines annotated in Cellosaurus. Many thanks

**Preferred term label:** interlobular stroma of mammary gland
**Synonyms** interlobular stroma of breast (broad)
**Definition** The stroma of the human mammary gland lobule contains two distinctive types of connective tissue. The intralobular stroma containing loosely connected fibroblasts surrounded by the more compact interlobular stroma which separates the lobules and intralobular stroma from any substantial direct contact with the adipose tissue. [PMID: 18710550]
**Parent term** mammary gland UBERON:0001911
**NOTE** Not sure if this term is human specific PMID: 15369447
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

**Preferred term label:** intralobular stroma of mammary gland
**Definition** The stroma of the human mammary gland lobule contains two distinctive types of connective tissue. The intralobular stroma containing loosely connected fibroblasts surrounded by the more compact interlobular stroma which separates the lobules and intralobular stroma from any substantial direct contact with the adipose tissue. [PMID: 18710550]
**Parent term** mammary gland UBERON:0001911
**NOTE** Not sure if this term is human specific PMID: 15369447
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

**Comment by bvarner-ebi** [comment]
Hi @paulacalipho, for your pending new term request tickets, can I assign these to you?

**Comment by paulacalipho** [comment]
Hello @bvarner-ebi , yes please you can assign all of them to me. I will start working on them soon. Thanks
