### ISSUE TITLE
NTR: cartilage of long bone

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2399]
**Comment:** The following term is needed to indicate the origin of the tissues used establish cell lines annotated in Cellosaurus. Many thanks

**Preferred term label:** cartilage of long bone
**Synonyms** long bone cartilage
**NOTE** Not sure if this term (FMA_32676) is synonym of "epiphyseal plate" that "is a hyaline cartilage, where new bone growth takes place, lengthening the bone prior to adulthood. Bone lengthening ceases when this cartilage is lost, leaving a remnant referred to as an epiphyseal line" (UBERON:0002516)
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

**Comment by nicolevasilevsky** [comment]
From @paulacalipho 

FMA has "cartilage of long bone" and it is used in https://www.cellosaurus.org/CVCL_C462 -> https://www.atcc.org/products/crl-2846 and that it is used in literature also PMID: 33169221, PMID: 12220122.

**Comment by nicolevasilevsky** [comment]
this was addressed here: https://github.com/obophenotype/uberon/pull/2748

**Comment by anitacaron** [comment]
@nicolevasilevsky, the PR was closed and not merged.

**Comment by anitacaron** [comment]
Is this issue still being planned to be addressed?

**Comment by anitacaron** [comment]
Just found the duplicated issue https://github.com/obophenotype/uberon/issues/2399
