### ISSUE TITLE
Surface structure definition

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#24]
From the recent doc "VAO-UBERON-text-diffs"

VAO:0000001 : surface structure
VAO: Organism subdivision which is the collection of anatomical structures on the body surface.
UBR: Organism subdivision that is the collection of anatomical structures on the body surface[ZFA].

CJM-NOTES:Use VAO

Note: Wasila will replace "which"  with "that" in VAO definition

**Comment by cmungall** [comment]
currently:

[UBERON:0003102](http://purl.obolibrary.org/obo/UBERON_0003102) ! surface structure
def: "Anatomical structure that overlaps the outer epithelial layer and is adjacent to the space surrounding the organism." [http://orcid.org/0000-0002-6601-2165, http://purl.obolibrary.org/obo/uberon/tracker/24]
