### ISSUE TITLE
NTR: semitendinosus tendon

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2405]
**Comment:** The following term is needed to indicate the origin of the tissues used establish cell lines annotated in Cellosaurus. Many thanks

**Preferred term label:** semitendinosus tendon
**Synonyms** tendon of semitendinosus
**Definition** The semitendinosus tendon inserts at the upper part of the medial surface of the tibia, behind the attachment of sartorius and infero-anterior to the attachment of gracilis. [https://www.physio-pedia.com/Semitendinosus]. The distal tendon of the semitendinosus is often used as a graft in orthopedic reconstructive surgery. [PMID: 31257566]
**Parent term**
tendon UBERON:0000043
semitendinosus UBERON:0001375
lower leg connective tissue UBERON:0004270
**NOTE** Pes anserinus ("goose foot") refers to the conjoined tendons of three muscles of the thigh. The three tendons, from front to back, that conjoin to form the pes anserinus come from the sartorius muscle, the gracilis muscle, and the semitendinosus muscle. https://en.wikipedia.org/wiki/Pes_anserinus_(leg)
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

**Comment by jlzamanian** [comment]
This term is also needed to describe the tissues used in single cell analysis experiments for the human cell atlas.

@paulacalipho

**Comment by paulacalipho** [comment]
@jlzamanian I will do a pull request on this term so you can go with issues#2649
