### ISSUE TITLE
NTR: subiliac lymph node

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2406]
**Comment:** The following term is needed to indicate the origin of the tissues used establish cell lines annotated in Cellosaurus. Many thanks

**Preferred term label:** subiliac lymph node
**Synonyms**
sub-ilal lymph node
subiliac lymphocenter [https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=2350&context=iowastate_veterinarian]
precrural lymph node [https://www.mpi.govt.nz/dmsdocument/26111/direct]
prefemoral lymph node [https://www.mpi.govt.nz/dmsdocument/26111/direct]
**Definition** Lymph node of the abdominal wall  situated subcutaneously (embedded in fat) on the lateral and on the ventral side of the abdominal wall. [https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=2350&context=iowastate_veterinarian]
**Parent term** abdominal lymph node UBERON:0002507
**NOTE** This term is used in swine [https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=2350&context=iowastate_veterinarian] and other animals [https://www.imaios.com/en/vet-Anatomy/Vet-Anatomical-Part/Subiliac-lymph-nodes]. The subiliac lymphocenter includes in, swine, the subiliac lymph nodes only. In Sisson, S. and Grossman. J. D. (Anatomy of the Domestic Animals. 4th edition. Press of W. B.Saunders Co.. Philadel",hla. 1953.) they are called the prefemoral lymph nodes. The term "prefemoral" is considered by the authors as somewhat unfortunate since the lymph nodes drain largely the subcutaneous dorso-lateral lumbar area of the trunk. In fact, the subiliac lymph nodes appear to be rather closely associated with the common iliac lymphocenter. [https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=2350&context=iowastate_veterinarian]
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

**Comment by ANiknejad** [comment]
Dear Paula,

'subiliac' definition itself sounds a bit broad, and as you listed here above, appears in the literature sometimes such as a synonym of 'prefemoral' (see https://en.wikivet.net/Lymphatics_of_the_Hindlimb_-_Anatomy_%26_Physiology), which then is also named 'precrural' (see https://www.gla.ac.uk/t4/~vet/files/teaching/clinicalexam/examination/left.html). But in the last version of the 'Systematized Nomenclature of Medicine, International Version' ontology, both terms are linked to different classes, 'subiliac lymph node' to 'lymp node of pelvis, NOS' and 'prefemoral lymph node' to 'lymph node of lower extremity, NOS'

https://bioportal.bioontology.org/ontologies/SNMI/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNMI%2FT-C4616&jump_to_nav=true

However 'subiliac lymph node' appears in the 'Foundational Model of Anatomy' ontology
https://bioportal.bioontology.org/ontologies/FMA/?p=classes&conceptid=http%3A%2F%2Fpurl.org%2Fsig%2Font%2Ffma%2Ffma323407&jump_to_nav=true

FMA:323407 does not appear as a xref in UBERON but its parent class, FMA:66193  Parietal lymph node of pelvis, does

[Term]
id: UBERON:0015877
name: parietal pelvic lymph node
namespace: uberon
synonym: "paracervical lymph node" RELATED [FMA:66193]
xref: FMA:66193
is_a: UBERON:0015876 {source="FMA"} ! pelvic lymph node

The child classes of UBERON:0015877 (parietal pelvic lymph node) are

- UBERON:0015878 common iliac lymph node
- 
- UBERON:0015880 external iliac lymph node
- 
- UBERON:0015881 internal iliac lymph node
- 
- UBERON:0015883 gluteal lymph node
- 
- UBERON:0015884 presymphysial lymph node

(I will continue the review soon...)

**Comment by paulacalipho** [comment]
Thanks @ANiknejad for this feedback. I will study all of this and come back as soon as possible.

**Comment by paulacalipho** [comment]
@ANiknejad 
Summary of exchanges in NTR and PR:

**1.** Remove "prefemoral lymph node" as synonym of subiliac lymph node : in the last version of the 'Systematized Nomenclature of Medicine, International Version' ontology, both terms are linked to different classes, 'subiliac lymph node' to 'lymp node of pelvis, NOS' and 'prefemoral lymph node' to 'lymph node of lower extremity, NOS

**2.** In https://flexikon.doccheck.com/de/Lymphzentrum_(Veterin%C3%A4rmedizin) lymphatic centers are defined according to the anatomical location and refer to functionally connected lymph nodes in domestic mammals. 

«lymphonodi subiliaci» is one of the lymph nodes of the lymphocentrum «lymphocentrum inguinale superficiale», lymphocentrum that is classified as a «hind limb» lymphocentrum.

In FMA, «superficial inguinal lymph node» FMA:5036 («superficial inguinal lymph node» UBERON:0009007) is_a subclass of «lymph node of lower limb».

**3.** «subiliac lymph node» exists in FMA (FMA:323407) and is_a subclass of «parietal lymph node of pelvis» FMA:66193 («parietal pelvic lymph node» UBERON:0015877).

According to point 2 and 3 «subiliac lymph node» may be class of both lymph node of lower limb and pelvic lymph node. 
In https://www.imaios.com/en/vet-anatomy/mouse/mouse-whole-body?slice=482&structureId=7700&isolate=true «subiliac lymph node» is a subclass of «inguinofemoral lymph node center». The definition of « inguinal part of abdomen » UBERON:0008337 indicates that the groin is in the junctural region.

**Proposition_to_review_with_expert**: 
1- add synonym «lymphocentrum inguinale superficiale» to «superficial inguinal lymph node» UBERON:0009007
2- create «subiliac lymph node» as a subclass of «superficial inguinal lymph node» UBERON:0009007 and «parietal pelvic lymph node» UBERON:0015877.

**Comment by ANiknejad** [comment]
as a note
http://linkedlifedata.com/resource/umls/id/C0229814

**Comment by paulacalipho** [comment]
@ANiknejad I rechecked what we found for subiliac lymph node. Would you agree with the following description of the term? Do you think we need to recheck with some expert on the field?

**term**: subiliac lymph node
**definition**: A lymph node located below the ilium.
**database_cross_reference**: NCIT:C0229814

**broad synonym**: subiliac lymphocenter
**database_cross_reference**: https://dr.lib.iastate.edu/handle/20.500.12876/46336

**database_cross_reference**: FMA:323407

**SubClass Of**: 'parietal pelvic lymph node' UBERON:0015877

**curator note**: This term is frequently used in swine (PMID: 35566137, PMID: 27866702) and mice (PMID:16624319, PMID:23328410). According to PMID:32882076 ‘inguinal lymph node’ (PMID:25919005, PMID:17804011) and ‘superficial inguinal lymph node’ (PMID:11581317) have been used incorrectly as synonym of ‘subiliac lymph node’. In addition, ‘prefemoral lymph node’ and ‘subiliac lymph node’ have been used as synonyms (PMID:22561151, PMID:23228067, PMID:24752354, PMID:8727908). However, in the last version of the 'Systematized Nomenclature of Medicine, International Version' ontology, both terms are linked to different classes, ‘subiliac lymph node’ to ‘lymp node of pelvis, NOS’ and ‘prefemoral lymph node’ to ‘lymph node of lower extremity, NOS’.
