### ISSUE TITLE
NTR: sublumbar lymph node

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2407]
**Comment:** The following term is needed to indicate the origin of the tissues used establish cell lines annotated in Cellosaurus. Many thanks

**Preferred term label:** sublumbar lymph node
**Definition** A lymph node located under the spine. [Definition Source: NCI; NCIT_C77655]. The sublumbar lymph nodes include the medial iliac, internal iliac (previously termed hypogastric), and sacral. [PMID: 32655159]
**Parent term** lymph node UBERON:0000029
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

**Comment by bvarner-ebi** [comment]
Hi @paulacalipho, thank you for all of your recent NTR tickets. Since this is a large volume of new requests, could you advise what your timeline is to have these terms added? Are there any that are more time-sensitive than others?
Would you also have any interest in learning how to add terms to the ontology yourself?

**Comment by paulacalipho** [comment]
Dear @bvarner-ebi, thanks for your message. We would like to release the mapping to UBERON beginning 2023. There are no special priorities among the terms, and there will be probably more request terms. I will be happy to learn how to add terms to ontology myself, thanks for proposing

**Comment by matentzn** [comment]
@paulacalipho if you are interested in real training, I think your best bet is to joining the Monarch OBO training; you can send me an email (@bvarner-ebi has it) to add you to the list of invites.

However, training is a lengthy process. In my experience with HPO, the best thing would be to provide @paulacalipho with ROBOT templates to populate and add the terms, and have uberon core developers deal with/review the logical axiomatisations where necessary. The best way to make progress on that is:

1. @paulacalipho creates a google sheet with all the terms she need, one row per term.
2. @shawntanzk and @bvarner-ebi will add columns to the sheet and explain to @paulacalipho what needs to be added
3. @shawntanzk slurps the sheet into uberon-edit.obo using robot template + merge.

My two cents. But, you are, in any case, welcome to join any training!

**Comment by shawntanzk** [comment]
Happy to provide or help with a "new term" robot template on google sheets. Will get to it after the long weekend :)

**Comment by bvarner-ebi** [comment]
Hi @paulacalipho, with regard to the definition for this term, can you clarify what is meant by "**under** the spine"? 
Could you select an appropriate anatomical term to replace 'under', such as 'inferior', 'posterior', etc?

**Comment by paulacalipho** [comment]
Hi @bvarner-ebi, I understand that "under" means ventral. Another proposal for definition:
The sublumbar lymph nodes include the medial iliac, internal iliac (previously termed hypogastric), and sacral. This lymph center is located within the caudal abdomen and pelvis, on the ventral side of the lumbar region [PMID: 32655159]
We will use this mapping for cell lines derived from dogs. I do not know how this term applies to other species.
About the mapping to NCIT, we decided in Cellosaurus to map cell types and tissues to Cell Ontology and UBERON. 

Concerning the training: how should I proceed with the google sheet?

**Comment by shawntanzk** [comment]
Hi @paulacalipho I've created a google sheet here:
https://docs.google.com/spreadsheets/d/1mAu30Lzy4ZAxBE0AhlAM0FFxd51SePaNMF2LqtajWew/edit#gid=0
I think (big emphasis on think) it has everything needed for the term additions. 
Happy to go through with you on how to handle it etc. if you need any guidance.
After addition of terms, I guess @bvarner-ebi will co-ordinate the review of them and I will be happy to use our tools to add them to the ontology and make a PR where it can be reviewed again (though given the large amount of terms, I'd prefer the review to primarily be done on the template) 
Hope that helps

**Comment by shawntanzk** [comment]
Training wise, you are very welcome to join us.
You can see https://oboacademy.github.io/obook/courses/monarch-obo-training/ for more details.
We run ongoing training every other Tuesday at 4pm UKT, today being one of the weeks we have a session. If you are interested @matentzn can invite you on the calendar :)

**Comment by bvarner-ebi** [comment]
> Hi @bvarner-ebi, I understand that "under" means ventral. Another proposal for definition: The sublumbar lymph nodes include the medial iliac, internal iliac (previously termed hypogastric), and sacral. This lymph center is located within the caudal abdomen and pelvis, on the ventral side of the lumbar region [PMID: 32655159] We will use this mapping for cell lines derived from dogs. I do not know how this term applies to other species. About the mapping to NCIT, we decided in Cellosaurus to map cell types and tissues to Cell Ontology and UBERON.
> 
> Concerning the training: how should I proceed with the google sheet?

Thank you, @paulacalipho.

Let me know if you need assistance with sheet that Shawn created.

For the term definition, what do you think of the following:  A lymph node with a lymph center located within the caudal abdomen and pelvis, on the ventral side of the lumbar region. Includes the medial iliac, internal iliac (previously termed hypogastric) and sacral lymph nodes.  [PMID: 32655159]

**Comment by paulacalipho** [comment]
Many thanks, definition is OK.

I will go asap through the google sheet and let you know

**Comment by bvarner-ebi** [comment]
@paulacalipho, thank you again to beginning to populate the the [template](https://docs.google.com/spreadsheets/d/1mAu30Lzy4ZAxBE0AhlAM0FFxd51SePaNMF2LqtajWew/edit#gid=0). 
Would you like to review the tab 'bv-suggestions'? I highlighted some cells orange and would like to get your input on them. Also, if you would like to propose equivalence axioms (column D) for your terms, that could help expedite adding these terms and also make sure we capture your intention in creating them. I populated a couple to show the general approach.

**Comment by paulacalipho** [comment]
@***@***.***>, thanks for reviewing the terms. How do you prefer I work on this table? Creating a new (3rd) one? Making comments on your table?

**Comment by bvarner-ebi** [comment]
@paulacalipho, may I suggest you could make edits directly on the 'bv-suggestions' tab (we could rename it to something like 'working-version' or something like that). You could simply overwrite my questions with your response/edits. Happy to also arrange a zoom meeting if we get to a point where that will be more efficient.

**Comment by paulacalipho** [comment]
@bvarner-ebi I answered to your suggestions in the document with "Paula: ....". I also added some comments in the equivalence axioms (column D) highlighted in cyan for some terms for which I have difficulties to suggest parent terms. Apart from that, I am not sure to really understand how to fill the equivalence axioms (column D)

**Comment by bvarner-ebi** [comment]
Thank you, @paulacalipho.
No worries on the equivalence axioms. If I see opportunities where they can be applied, I will enter them.

**Comment by bvarner-ebi** [comment]
@paulacalipho, the following term has been added to Uberon:

UBERON:8470001 'sub lumbar lymph node'
