### ISSUE TITLE
Make Neck more generalizable

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2417]
Currently Fish cannot have a neck because of taxon constraints 

@cmungall commented (https://github.com/obophenotype/uberon/issues/2367#issuecomment-1096815312): 
"I think the best solution would be to generalize neck in a way that keeps
the fish people happy. Fish may lack a neck proper but they have an
analogous region of the craniocervucal region with the same skeletal
elements"

For now, we are making a taxon GCI (https://github.com/obophenotype/uberon/pull/2415) but a better solution is to make neck more generalizable like the above

I'm assigning myself for now so that it doesn't got unassigned, but I would like someone who is more knowledgeable about fish stuff to take over this ticket (not sure who, but if anyone knows, please do assign them/let me know)

**Comment by wdahdul** [comment]
Thanks for copying me (and apologies for the delay!). The terms ‘neck’ or ‘craniocervical’ or ‘cervical’ aren’t used in the fish comparative literature for the region behind the skull, and as far as I know, there is no generalized term for that region in fish anatomy. For example, the vertebrae directly behind the head in fishes are called ‘precaudal vertebrae’ meaning that they are anterior to the caudal vertebrae. 

@megbalk and I reviewed the related ticket and if the best option is a taxonomic constraint, we suggest using this: 'jugular vein' and ('in taxon' some Sarcopterygii) SubClassOf 'part of' some neck. In the related ticket, this was expressed at the level of Mammalia, but it can be broadened to Sarcopterygii (lobe finned fishes)– see the curator note on ‘neck’:

"true necks are considered to be present when the pectoral girdle is separate from the skull - Tiktaalik is the earliest known fish to have a true neck."

**Comment by cmungall** [comment]
unfortunately tooling support for taxon GCIs are not great. This means people coming to OLS etc with mammals in mind looking under neck would not see jugular vein.

**Comment by shawntanzk** [comment]
@cmungall - could you suggest and actionable item for this please? thanks :)

**Comment by cmungall** [comment]
generalize the existing taxon GCI from mammals to Sarcopterygii

**Comment by anitacaron** [comment]
@aleixpuigb, can you try to work on this issue because we have a straightforward fix for it, please?

> cmungall: generalize the existing taxon GCI from mammals to Sarcopterygii

change the taxon GCI here to Sarcopterygii in jugular vein (UBERON:0004711)

```
relationship: part_of UBERON:0000974 {gci_filler="NCBITaxon:40674", gci_relation="in_taxon"} ! neck
```

**Comment by aleixpuigb** [comment]
Looking at `neck` and the original ticket #2367, `neck SubclassOf 'only in taxon' some Sarcopterygii` doesn't seem correct, shouldn't we remove that axiom? Then we can add `'jugular vein' and ('in taxon' some Sarcopterygii) SubClassOf 'part of' some neck` (not replacing the mammalian GCI). Therefore I suggest the following actions for this ticket:
- [ ] Remove axiom `neck SubclassOf 'only in taxon' some Sarcopterygii`.
- [ ] Add GCI `'jugular vein' and ('in taxon' some Sarcopterygii) SubClassOf 'part of' some neck`.

@cmungall, do you agree with these edits?

**Comment by cmungall** [comment]
agreed
