### ISSUE TITLE
Proper use of 'derives from' in referencing UBERON anatomical parts for FoodOn

### ISSUE THREAD

**Issue by ddooley** [obophenotype/uberon#2420]
In FoodOn we need to reference plant and animal parts and products derived from them without necessarily implying they are connected to the anatomy of whole organisms.  Currently our pattern is:

    organism part: equivalentTo [anatomical part] and 'derives from' some [NCBITaxon organism term]

e.g.

    'cow heart (whole)': equivalentTo heart and ‘derives from’ some ‘Bos taurus’

Some email debate has highlighted that UBERON has all its entities logically connected, so if I reference an instance of UBERON heart, that also logically implies an instance of head, foot, arm etc. are connected?!  (This is in contrast to the plant ontology PO which according to the same dialogue was developed with some ability to reference instances of anatomical parts, like seed, fruit, without implying connection to an instant of the remaining plant).

So this leaves me wondering how to revise the animal part equivalency axiom correctly.

We actually need to know how to do / recommend two aims: 

**A) reference an organism part as being separated from its organism.** as food products are when they are harvested or extracted.  So for an animal part, do we have to say something like:

    'butchered heart': subClassOf 'butchered organ' and 'derives from' some heart and 'derives from' only heart

Should we ask for something like a "severed from" relation which is more precise relation linked to a severing (~butchery) process? [edit: or perhaps "separated from" though it is currently a PATO quality].

    'butchered heart': subClassOf 'butchered organ' and 'severed from' some heart and 'severed from' only heart

**B) reference the organism part ambiguously, leaving it that it might or might not be attached to the whole organism, and might not be whole.**  This shows up because we want to be as informative as possible, but no more, about biosamples that have vague descriptions.  A biosample may mention "heart" for its material but this doesn't mean necessarily the whole heart, or that the heart was removed from an animal.  A way to reference heart tissue and allow it to be in-situ or not is kind of the Schrödinger's cat / Claude Shannon minimum information case we need to handle. So for this use should we define:

    "heart (whole or parts)": heart or 'derives from' some heart and 'derives from' only heart

In this way 'heart (whole or parts) allows both butchered heart and heart in situ (dead or alive).  Because of 'derives from', other kinds of processing are also possible - the heart material could have been cooked, mushed etc. 

Thanks for advice!

**Comment by ddooley** [comment]
Note as well that even though "milk" is a "bodily fluid", by virtue of "organism substance" it is "part of" some "multicellular organism".  So FoodOn, in referencing milk, needs to define "harvested milk" to reference milk that has been separated from the animal?

**Comment by shawntanzk** [comment]
similar to https://github.com/obophenotype/uberon/issues/2427 - will assign you, already in agenda

**Comment by ddooley** [comment]
I don't actually know when UBERON curation meetings take place - is that in the thursday UPHENO call? It would be great to attend as you discuss...

**Comment by shawntanzk** [comment]
@ddooley uberon call details can be found here: https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit 

but actually looking at this, given its a relation question, I've moved it to the RO call tmr (also cause uberon call is not for awhile :p). I guess you'll be at that call anyway?

**Comment by ddooley** [comment]
Yes, will do, thx.
