### ISSUE TITLE
Proper use of 'in taxon' vs derives from

### ISSUE THREAD

**Issue by ddooley** [obophenotype/uberon#2427]
Related to #2420, in FoodOn say we want to talk about a cow heart.  So far we've been saying:

`'cow heart': equivalentTo heart and ('derives from' some 'Bos taurus' and 'derives from' only 'Bos taurus')`

According to RO, the '**in taxon**' definition is shorthand allowing for one of "part of (reflexive), developmentally preceded by, derives from, secreted by, expressed.", though 'secreted by' and 'expressed' don't seem to be RO relations, so maybe 'produced by' would be a better relation in there?

If we said:

`'cow heart': equivalentTo heart and 'in taxon' some 'Bos taurus'`

Are we being more vague than if we were to stick with 'derives from'? Is that an inappropriate use of 'in taxon'? People turning to using OBO Foundry I think are finding 'in taxon' conceptually more accessible than 'derives from'.

Could we use 'only in taxon' to be more precise?  Earlier we were warned off using this as it was going to be deprecated?  The NCBITaxon disjointness required to make this relation obsolete sounds computationally intense.

We want to then be able to say:

`'butchered cow heart':  equivalentTo 'butchered heart' and 'in taxon' some 'Bos taurus'`

And similarly, for reference to cow heart in situ, or parts derived from that:

`'cow heart (whole or parts)': equivalent to 'cow heart' or ('derives from' some 'cow heart' and 'derives from' only 'cow heart'`

All good?

Thanks for advice/confirmation...

**Comment by shawntanzk** [comment]
Will place this in uberon call agenda, but if you need this more urgently, slack might be faster. Am assigning myself to this for now (trying to make sure newer tickets all get assigned)

**Comment by dosumis** [comment]
Not strictly and Uberon issue  - more an issue for how Uberon is used.  @cmungall will comment further.  Might be better for patterns to be associated with COB.

**Comment by ddooley** [comment]
We have implemented 'in taxon' in FoodOn, but the outstanding question is about how to reference an "animal heart" with respect to UBERON heart.  It seems like ideally we could have a relationship like "severed from", so "animal heart" subClassOf: "'severed from' some heart". In this way conveying that the animal heart is the entire heart part but no longer connected to the rest of the animal.

**Comment by ddooley** [comment]
Closing this in favour of: https://github.com/oborel/obo-relations/issues/621
