### ISSUE TITLE
Developmental bridge files causing unsats

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2428]
Unsats caused by:
[occurrent](http://purl.obolibrary.org/obo/BFO_0000003) DisjointWith [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [continuant](http://purl.obolibrary.org/obo/BFO_0000002)

Follows the following pattern: 
[FBdv_00005336](http://purl.obolibrary.org/obo/FBdv_00005336) EquivalentTo [larval stage](http://purl.obolibrary.org/obo/UBERON_0000069) and [instar larval stage](http://purl.obolibrary.org/obo/UBERON_0004730) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Drosophila melanogaster](http://purl.obolibrary.org/obo/NCBITaxon_7227))
[HsapDv_0000006](http://purl.obolibrary.org/obo/HsapDv_0000006) EquivalentTo [blastula stage](http://purl.obolibrary.org/obo/UBERON_0000108) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606))
[ZFS_0000044](http://purl.obolibrary.org/obo/ZFS_0000044) EquivalentTo [post-juvenile adult stage](http://purl.obolibrary.org/obo/UBERON_0000113) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Danio](http://purl.obolibrary.org/obo/NCBITaxon_7954))
[XAO_1000001](http://purl.obolibrary.org/obo/XAO_1000001) EquivalentTo [zygote stage](http://purl.obolibrary.org/obo/UBERON_0000106) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Xenopus ](http://purl.obolibrary.org/obo/NCBITaxon_8353))
[FMA_24120](http://purl.obolibrary.org/obo/FMA_24120) EquivalentTo [life cycle stage](http://purl.obolibrary.org/obo/UBERON_0000105) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606))
[MmusDv_0000017](http://purl.obolibrary.org/obo/MmusDv_0000017) EquivalentTo [neurula stage](http://purl.obolibrary.org/obo/UBERON_0000110) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Mus musculus](http://purl.obolibrary.org/obo/NCBITaxon_10090))
[WBls_0000093](http://purl.obolibrary.org/obo/WBls_0000093) EquivalentTo [post-embryonic stage](http://purl.obolibrary.org/obo/UBERON_0000092) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Caenorhabditis](http://purl.obolibrary.org/obo/NCBITaxon_6237))

Potential fix: 
1) part_of should be changed to in_taxon

Potential strategies: 
1)  change all bridge file intersection_of: part_of NCBITaxon: to intersection_of: in_taxon NCBITaxon:
2) change only developmental bridges
3) change only unsats

Related to https://github.com/obophenotype/uberon/issues/2367

**Comment by matentzn** [comment]
Share with Chris on slack, this blocks everything right now. I vote for 1, and Anita can do it.

**Comment by cmungall** [comment]
I don't understand 3, I think the choice is between 1 and 2

In OWL it's hard to have rules like "if X in-taxon T, and X is a continuant, then X part-of T". So implementing (1) could lose inferences. These will likely affect composite-metazoan.. but then we don't have composite metazoan anyway..

I think the best solution is to add two axioms

1. equivalentTo T and in-taxon T
2. subClassOf R some T, where R is determined by the category: part-of for continuants and occurs-in for processes

If this involves developing new code then go ahead and implement 1 for now and we will create an issue to return to make the more complete axioms

**Comment by shawntanzk** [comment]
> I think the best solution is to add two axioms

Just to confirm does this mean something like:

[HsapDv_0000006](http://purl.obolibrary.org/obo/HsapDv_0000006) EquivalentTo [blastula stage](http://purl.obolibrary.org/obo/UBERON_0000108) and in_taxon some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606)
[HsapDv_0000006](http://purl.obolibrary.org/obo/HsapDv_0000006) subClassOf occurs-in some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606)

or 

MBA_710 EquivalentTo [abducens nerve](http://purl.obolibrary.org/obo/UBERON_0001646) and in_taxon some [Mus musculus](http://purl.obolibrary.org/obo/NCBITaxon_10090)
MBA_710 subClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Mus musculus](http://purl.obolibrary.org/obo/NCBITaxon_10090)

Where [blastula stage](http://purl.obolibrary.org/obo/UBERON_0000108) is a process and [abducens nerve](http://purl.obolibrary.org/obo/UBERON_0001646) is a continuant

**Comment by shawntanzk** [comment]
Note to self: this has implications on https://github.com/obophenotype/uberon/issues/2384

**Comment by shawntanzk** [comment]
Fixed - though unsure if QC checks are reactivated if they were turned off - if so, open new ticket on it
