### ISSUE TITLE
lateral tuberal nucleus is specific to humans and primates

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2439]
NEEDS MORE RESEARCH

lateral tuberal nucleus (UBERON:0000435) should be specific to humans and higher primates 
From PMID:1362279:

> It can be recognized in man and higher primates, probably not in other mammals.

This is repeated in multiple books https://www.sciencedirect.com/topics/immunology-and-microbiology/tuberal-nucleus

The homologous region in mammals is tuberal nucleus (https://www.science.org/doi/10.1126/science.aar4983#core-R2). 

Currently lateral tuberal nucleus has an xref to mba:614 which is tuberal nucleus in the allen mouse brain atlas.

This is technically wrong, however, it seems that lateral tuberal nucleus (or NTL) is used interchangeably.  https://www.science.org/doi/full/10.1126/science.aau1419

Also found a 1970 paper that has NTL in fish https://link.springer.com/article/10.1007/BF00343982 and this term also exists in the zebrafish anatomy ontology https://zfin.org/action/ontology/term-detail/ZFA:0000227

Also according to http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=1890, it seems lateral tuberal nucleus is part of the tuberal nucleus in mouse/rats. Could tuberal nucleus be homologous to human tuberal region of HTH instead? 

@patrick-lloyd-ray - I assume the `nok` and `add term` for tuberal nucleus is because experts thought lateral tuberal nucleus doesn't exist in mouse? 

@dosumis I'm now not sure how to handle this - I still think adding a new term tuberal nucleus is useful, but I don't know how to get the terms to co-exist without confusion

**Comment by shawntanzk** [comment]
Solution: 

- [ ] We can add a sensu term specific for rodentia to map mba to 
- [ ] Add taxon restriction to primates to current lateral tuberal nucleus
- [ ] Check if ZFA has a bridge (cause taxon restriction will break that) - if so maybe need to remap or add a term for fish too

**Comment by dosumis** [comment]
Please also add comments and references describing evidence for and against homology between these different structures and detailing any terminological confusion.

**Comment by shawntanzk** [comment]
**New terms:**

Label: tuberal nucleus (sensu Rodentia)
Exact Synonym: lateral tuberal nucleus (sensu Rodentia) [PMID:29976812]
Broad Synonym: lateral tuberal nucleus (sensu Rodentia) [http://braininfo.rprc.washington.edu/centraldirectory.aspx?ID=1890]
Definition: A hypothalamic region in rodents that is homologous to the lateral tuberal nucleus in humans and higher primates and is involved in energy homeostasis. [PMID:29976812, PMID:29976824]
rdfs:comment:  This term is used specifically for rodents as lateral tuberal nucleus (UBERON:0000435) refers to a structure that is specific to humans and higher primates. [PMID:1362279]
Editors note: Lateral tuberal nucleus is listed as both an exact synonym and related synonym as the term has been used in both ways. See `https://github.com/obophenotype/uberon/issues/2439` for more details.
dbxref: MBA:614, DMBA:16271
in_taxon: NCBITaxon:9989

Label: lateral hypothalamic nucleus (sensu Teleostei) 
Exact Synonym: nucleus lateralis tuberis (NLT) system (sensu Teleostei) [DOI:10.1016/0016-6480(71)90165-1]
Exact Synonym: lateral tuberal nucleus (sensu Teleostei) [ZFA:0000227]
Definition: Diencephalic nucleus which is the lateral part of the ventral hypothalamic zone and anatomically homologous to the hypothalamic arcuate (infundibular)-median eminence (ME) system of tetrpods. [ZFA:0000227, DOI:10.1016/0016-6480(71)90165-1]
rdfs:comment: This term is used specifically for fish (or Teleostei in general) as lateral tuberal nucleus (UBERON:0000435) refers to a structure that is specific to humans and higher primates. [PMID:1362279]
dbxref: ZFA:0000227

**Comment by patrick-lloyd-ray** [comment]
> the nok and add term for tuberal nucleus is because experts thought lateral tuberal nucleus doesn't exist in mouse?

Yes, that's right. The solution you have here looks like a good one to me!

**Comment by shawntanzk** [comment]
Whoops, take it back about ZFA:0000227 - mistakenly went to the wrong term and saw the xref, it isn't there of NLT
