### ISSUE TITLE
Uberon is obsoleting external terms.. Should it?

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#2440]
In Uberon `http://purl.obolibrary.org/obo/uberon/releases/2022-04-18/ext.owl` it appears that EMAPA [future neurohypophysis](http://purl.obolibrary.org/obo/EMAPA_16647) is merged (obsoleted) into Uberon [future neurohypophysis](http://purl.obolibrary.org/obo/UBERON_0034876).

Uberon should not be obsoleting other ontologies' terms. This is causing automatic migrations of GO annotations from EMAPA to Uberon. It looks like it came up in https://github.com/obophenotype/uberon/issues/2192, but not sure how the obsoletion happened.

**Comment by matentzn** [comment]
I fixed this in #2442 

But I will repurpose this ticket now to the general question:

There are 33 such cases in Uberon (search regex: `alt_id: [^U].*`):

```
alt_id: http://purl.bioontology.org/ontology/provisional/1ddd2e2d-2ace-4c87-8ec6-d3b5730b3e7c
alt_id: http://purl.bioontology.org/ontology/provisional/8378426c-67ca-4bab-a9cf-531093b9b95e
alt_id: EHDAA2:0003079
alt_id: EHDAA2:0003081
alt_id: EHDAA2:0003095
alt_id: EHDAA2:0003099
alt_id: EHDAA2:0003100
alt_id: EHDAA2:0003112
alt_id: EHDAA2:0003117
alt_id: EHDAA2:0003118
alt_id: EHDAA2:0003119
alt_id: EHDAA2:0003146
alt_id: EHDAA2:0003151
alt_id: EHDAA2:0003152
alt_id: EHDAA2:0003233
alt_id: EHDAA2:0003251
alt_id: ZFA:0005228
alt_id: BSPOTEMP:58938a8e-359c-49d8-b3f7-5e1fd7e1a109
alt_id: http://purl.bioontology.org/ontology/provisional/58938a8e-359c-49d8-b3f7-5e1fd7e1a109
alt_id: http://purl.bioontology.org/ontology/provisional/3b77fb04-1e62-43af-a84b-5d5eb7388525
alt_id: http://purl.bioontology.org/ontology/provisional/bdc28b9d-8fe6-4175-ae67-002f61493279
alt_id: http://purl.bioontology.org/ontology/provisional/2cb7c05f-bfbf-4393-8c2a-70218b824b41
alt_id: http://purl.bioontology.org/ontology/provisional/3bde5870-7193-4f1c-a9c3-930cef534038
alt_id: http://purl.bioontology.org/ontology/provisional/2018775c-cd54-4503-88bc-9b62d35a1fdb
alt_id: http://purl.bioontology.org/ontology/provisional/b0379d68-e54b-4dac-851c-0336cfb85a8f
alt_id: http://purl.bioontology.org/ontology/provisional/b247b724-0e9c-44bd-bbd2-b84e6cb5b072
alt_id: http://purl.bioontology.org/ontology/provisional/f17c9aff-4a92-418e-989f-b8e9dd62caf6
alt_id: http://purl.bioontology.org/ontology/provisional/8b514716-1381-474b-93d5-1ac01c28f54c
alt_id: http://purl.bioontology.org/ontology/provisional/c4f989c4-2805-49a3-8241-b5e37405e9ca
alt_id: http://purl.bioontology.org/ontology/provisional/c97fd8d8-cf3e-4326-938d-bea58477423d
alt_id: http://purl.bioontology.org/ontology/provisional/3f8eb04d-3229-487c-9c0e-b65e1a1f035e
alt_id: http://purl.bioontology.org/ontology/provisional/53cf86f8-2122-4125-bc72-117201b4f4c4
alt_id: http://purl.bioontology.org/ontology/provisional/faea86d9-5281-441b-be89-0f0be1d49129
```

I would like to remove all of these. @cmungall any objections? Maybe I am missing some strategic thing here.

**Comment by cthoyt** [comment]
I'm going to add an OBO-wide check for this scenario in https://github.com/cthoyt/oquat

**Comment by matentzn** [comment]
I think this may be very tricky to do in general.. OBO format is very idiosyncratic here. @cthoyt  how would you formulate the test independently of the specific syntactic conventions of the OBO format? The majority of ontologies are using OWL and are only transformed to OBO after the fact, so wouldn't create `alt_ids`.
