### ISSUE TITLE
Create a coherent collected-metazoa ontology that includes all bridging axioms

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2452]
I realize there may be smaller issues for this but I think we should tackle this as a whole

We want all metazoan ssAOs plus bridge axioms plus Uberon to have no unsatisfiable classes

This may need some compromise on the uberon side. We may need to relax some disjointness axioms (these can be retained as something that is used internally to check uberon, but are dropped from the main release). Having the ability to traverse up from terms to their uberon counterparts is a higher priority for users than ontological perfection.

The main challenge here will be space-vs-material distinctions. IMO this is irrelevant to biologists and I think it's OK if collected-metazoa drops CARO/BFO/COB so that we can conflate these. An alternative is to have a rule that no mod ssAO maps to spaces and we make a material counterpart for all.

Note: this task is impossible with the current official release of FMA as it is already incoherent but we should be able to use the bioportal release which has no disjointness axioms

**Comment by anitacaron** [comment]
Maybe the PR https://github.com/obophenotype/uberon/pull/3102 is doing this?

**Comment by gouttegd** [comment]
#3102 is the first step, to enforce taxon constraints over Uberon combined with all the ssAO bridges.

Then there is #3061, to overhaul how the bridges are generated, and after that there will be the overhaul of how collected- and composite-metazoan are generated.

The overhaul of the generating pipelines will not, in itself, fix any existing or future inconsistency in collected-metazoan, but it should help in fixing them, by making the whole thing easier to debug (notably, easier to rebuild after a change has been made).
