### ISSUE TITLE
Diff report should merge master into the branch before running diff

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2489]
Right now, if the branch is behind master, the diff runs wild:

https://github.com/obophenotype/uberon/pull/2481

I think we need to merge master into the branch just before running diff.

**Comment by megbalk** [comment]
done

**Comment by matentzn** [comment]
This was not for you @megbalk its a very general issue ;)

**Comment by ubyndr** [comment]
- [ ] Check if the current branch is behind the master branch and warn the users to update their branches before any other actions.

**Comment by matentzn** [comment]
To calrify `warn the user`: fail the action with a comment.

**Comment by anitacaron** [comment]
This will be solved differently. Only run the diff when it's asked. If the branch is behind the master then the action will fail.

Reference #2068
