### ISSUE TITLE
Update 'genital system': populate with subclasses, add text definition and synonym

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/uberon#2493]
**Uberon term**
UBERON:3011048 'genital system'

**Synonym to be added**
- [x] broad: genitalia
- [x] broad: reproductive system

**Notes**
- [x] Populate with appropriate subclasses.
- [x] Add text definition. Definition from [XAO term](http://purl.obolibrary.org/obo/XAO_0000142) can be appropriated.
- [x] After PR is merged, update [OrganList](https://docs.google.com/spreadsheets/d/1QzuB07M61TqCElRzydWVs4ap5RIIlmg7xIpSLxC6PFU/edit?skip_itp2_check=true#gid=0) to map major.Organ 'genitals' to Uberon 'genital system'
- [x] Ask @ubyndr to rerun mapping coverage analysis (related [Organ and Ontology Discussion](https://capdevelopment.atlassian.net/wiki/spaces/CAP/pages/162889729/2022-05-24+Organ+ontology+discussion)).

Motivation: update term with subclasses to improve coverage with the Cell Annotation Platform (CAP) organ terms, which are being leveraged to build the autosuggest search term feature for the platform.

**Comment by cmungall** [comment]
You perhaps weren't to know this but I think the correct course of action here was to merge genital system. See #2514

**Comment by bvarner-ebi** [comment]
@cmungall, do you mean merge 'genital system' with 'reproductive system'?

FYI @dosumis

**Comment by balhoff** [comment]
Is 'genital system' just amphibian-specific terminology for reproductive system? https://www.ontobee.org/ontology/XAO?iri=http://purl.obolibrary.org/obo/XAO_0000142

**Comment by dosumis** [comment]
I think the key question is whether [reproductive system](https://github.com/obophenotype/uberon/issues/2493) is broader than genitalia (we have terms for internal and external genitalia, but not the grouping term - genital system is the closest we have to that).

![image](https://user-images.githubusercontent.com/112839/172811481-6c1b09ab-9ee2-42d6-8143-48d3e7e8f515.png)

We have terms under reproductive system that I don't think anyone would consider genitalia, e.g. 

cotylephore
[http://purl.obolibrary.org/obo/UBERON_2002114 ](http://purl.obolibrary.org/obo/UBERON_2002114) 
Multi-tissue structure that is a transient outgrowth of tissue on skin brooding fish that acts as an attachment site for embryos. [ TAO : wd ]

[ovipositor](http://purl.obolibrary.org/obo/UBERON_2002117)

Would reproductive system also include specialised structures involved in mating e.g. sex combs on the front legs of some insects?  What about glands secreting sex phereomones?

Suggested fix:  Genital system -> genitalia becomes grouping term for internal & external genitalia + gonad? (which doesn't currently appear to be under genitalia)

**Comment by dosumis** [comment]
I'd drop the broad synonyms recently added and make genital system and extact synonym of genitalia.  The 'reproductive system' broad synonym should go, as we shouldn't duplicate a superclass name as a synonym.

**Comment by bvarner-ebi** [comment]
Proposal:

[ ] change label of UBERON:3011048 ‘genital system’ to ‘genitalia’ 
[ ] change the definition of UBERON:3011048 from:

“Anatomical system that has as its parts the organs concerned with reproduction, especially the external genital organs.”
to 
“An organ from the group of internal or external organs that are part of the reproductive system”

[ ] make the following subclasses of UBERON:3011048:
‘internal genitalia’
‘external genitalia’
‘intermittent organ’
‘gonad’
[ ] remove the the ‘reproductive system’ broad synonym from UBERON:3011048
[ ] change ‘genitalia’ from a broad to exact synonym

**Comment by bvarner-ebi** [comment]
@balhoff, @dosumis, while we figure out the bigger solution, should I for now remove 

`'part of' some 'genital system' `

from 'gonad' to deal with the ubergraph update issue?

**Comment by balhoff** [comment]
> @balhoff, @dosumis, while we figure out the bigger solution, should I for now remove
> 
> `'part of' some 'genital system' `
> 
> from 'gonad' to deal with the ubergraph update issue?

I think so, and after you merge such a commit, I can run the Ubergraph coherency check (https://github.com/INCATools/ubergraph/actions/workflows/test-merged.yaml) to catch anything else before an actual Uberon release.

**Comment by dosumis** [comment]
> @balhoff, @dosumis, while we figure out the bigger solution, should I for now remove

> 'part of' some 'genital system'

> from 'gonad' to deal with the ubergraph update issue?

That should work as a temp fix.

**Comment by bvarner-ebi** [comment]
> change the logical defs in this branch to use capable_of_part_of some 'reproduction'? 

What do you mean by "this branch," please?

**Comment by dosumis** [comment]
At least 'reproductive organ' and anything under it (post reasoning) right now that has capable_of reproduction

**Comment by cmungall** [comment]
We have this issue from a while ago (auto-closed):

- #547
