### ISSUE TITLE
Does UBERON_0000066 'fully formed stage' cover bugs and insects?

### ISSUE THREAD

**Issue by zhengj2007** [obophenotype/uberon#2498]
[VEuPathDB database](https://veupathdb.org/) need a term to annotate the adult stage of mosquito. We are thinking to use  
http://purl.obolibrary.org/obo/UBERON_0000066 'fully formed stage' (adult stage).

The term definition is 'The stage of development at which the animal is fully formed, including immaturity and maturity. Includes both sexually immature stage, and adult stage.' 

We'd like to know whether the animal used in the definition include bugs and insects. Thanks!

**Comment by shawntanzk** [comment]
I think it does - VFB seems to use it (https://www.virtualflybrain.org/blog/2022/01/01/fully-formed-stage-uberon_0000066/) (sorry for the weird link, ols seems to be down). So if it applies to flies, i don't see why not mosquitoes :) 
If that answers the question, please do help close this ticket. Thanks!

**Comment by shawntanzk** [comment]
I'll be closing this ticket, but please feel free to reopne if there is any other concerns. Thanks
