### ISSUE TITLE
new term request: optic lobe

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/uberon#2504]
Optic lobe - Either of two prominences of the midbrain concerned with vision (BTO:0000965)

**Comment by shawntanzk** [comment]
I'm guessing you are looking for occiptal lobe: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002021 unless you are looking for an area of the brain that is related to vision (which is more complex, and there is ongoing debate on function vs spatial differentiation - which would more be visual cortex etc. but given you mentioned lobe, I assume the occiptal lobe is what you want.
