### ISSUE TITLE
brain striatum

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/uberon#2507]
**Preferred term label:**: brain striatum

**Synonyms**: neostriatum, striate nucleus

**Definition (free text, please give PubMed ID)**: PMID: [24858182](https://pubmed.ncbi.nlm.nih.gov/24858182)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Comment by shawntanzk** [comment]
Hi @kalpanaps - the term striatum is already in uberon (https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002435). I will hence be closing this ticket.
