### ISSUE TITLE
nerve cord

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/uberon#2508]
**Preferred term label:**:nerve cord

**Synonyms**

**Definition (free text, please give PubMed ID)**
The pair of closely united ventral longitudinal nerves with their segmental ganglia that is characteristic of many elongate invertebrates (as earthworms). 2. The dorsal tubular cord of nervous tissue above the notochord of a chordate that comprises or develops into the central nervous system - BTO:0001656

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Comment by shawntanzk** [comment]
Hi @kalpanaps, nerve cord is already in uberon (see synonym) https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0005053. I will hence be closing this ticket.
PS - OLS is a really powerful tool that you can use to look up terms before requesting, that will help us heaps and I guess will cut down your workload on writing up these tickets too :) Thanks
