### ISSUE TITLE
villus

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/uberon#2509]
**Preferred term label:**villus

**Synonyms**

**Definition (free text, please give PubMed ID)**: Any of the small, slender, vascular projections that increase the surface area of a membrane. Important villous membranes include the placenta and the mucous-membrane coating of the small intestine. Each villus has a central core composed of one artery and one vein, a strand of muscle, a centrally located lymphatic capillary, and connective tissue that adds support to the structures. Covering the core of a villus is the surface mucous-membrane layer. This is mainly composed of two cell types: tall, narrow, columnar cells and goblet cells. - BTO:0003121

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**

**Your nano-attribution (ORCID)**: 0000-0003-2534-198X

**Comment by shawntanzk** [comment]
Villus is an exact synonym here: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001213 - if there is any issues with this, please open a ticket detailing the change you would like see made instead of a new term request :) thanks!
