### ISSUE TITLE
hippocampus

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/uberon#2510]
**Preferred term label:**: hippocampus

**Synonyms**: major hippocampus

**Definition (free text, please give PubMed ID)**:  curved elongated ridge that extends over the floor of the descending horn of each lateral ventricle of the brain and consists of gray matter covered on the ventricular surface with white matter; The hippocampus is a part of the temporal lobe, which has a well established role in learning, memory and emotion - BTO:0000601

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Comment by shawntanzk** [comment]
I'm guessing you are looking for hippocampal formation (https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002421&lang=en&viewMode=PreferredRoots&siblings=false) if not please see the child nodes if you are looking for something more specific. If you need a concept that isn't represented in uberon, please state the exact issue with the current representation and we will look into it. Thanks!
