### ISSUE TITLE
crypt

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/uberon#2511]
**Preferred term label:**: crypt

**Synonyms**

**Definition (free text, please give PubMed ID)**:A crypt is a deep pit that protrudes down into the connective tissue surrounding the small intestine. The epithelium at the base of the crypt is the site of stem cell proliferation and the differentiated cells move upwards and are shed 3-5 days later at the tips of the villi (BTO:0000305)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Comment by shawntanzk** [comment]
I'm guessing this is what you are looking for: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001983
