### ISSUE TITLE
fix typo in 'right cardiac atrium' [UBERON:0002078]

### ISSUE THREAD

**Issue by jahilton** [obophenotype/uberon#2512]
**Uberon term**
UBERON:0002078

**Suggested revision of textual definition**
A cardiac atrium that is in the ~~left~~ **right** side of the heart. It receives deoxygenated blood. In mammals, this comes from the superior and inferior vena cava and the coronary sinus, and pumps it into the right ventricle through the tricuspid valve.

**Comment by nlharris** [comment]
At first glance, I thought, "This seems like the sort of thing that the issue submitter could just submit a PR for," but I wasn't actually able to find that definition anywhere official-seeming. https://github.com/search?q=%22receives+deoxygenated+blood%22+uberon&type=code
Best match I found was in https://github.com/cmungall/testwiki/blob/master/uberon/UBERON/78/UBERON_0002078.md -- that can't be the canonical place for that, right?
