### ISSUE TITLE
iliac vein smooth muscle tissue

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2528]
**Preferred term label:** iliac vein smooth muscle tissue
**Synonyms** muscle of iliac vein
**Definition** A portion of smooth muscle tissue that is part of an iliac vein
**Parent term** 
iliac vein UBERON:0005610
venous system smooth muscle UBERON:0004696
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

**Comment by shawntanzk** [comment]
@bvarner-ebi - ive assigned you to this ticket, hope you don't mind, lmk if it is out of scope for you. Thanks

**Comment by bvarner-ebi** [comment]
This term is originally from #2392 and will be used to train @paulacalipho on adding new terms to Uberon.
