### ISSUE TITLE
Some imports have missing ontology IRI

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#2531]
Some files are imported into uberon-edit.obo, but don't have an ontology IRI that matches the import name (they have no ontology IRI). The result is that their contents are not properly imported into the ontology closure in Protégé:

- `http://purl.obolibrary.org/obo/uberon/components/hra_subset.owl`
- `http://purl.obolibrary.org/obo/uberon/components/vasculature_class.owl`

**Comment by shawntanzk** [comment]
@anitacaron - I assume this is related to https://github.com/obophenotype/uberon/pull/2527 
I'll assign this to you

**Comment by anitacaron** [comment]
Yes, I'm fixing the OWL files.

**Comment by anitacaron** [comment]
Since #2527 was merged, I'll close this issue.
