### ISSUE TITLE
ncbitaxon_import.owl target misses taxa

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#2532]
Running `make imports/ncbitaxon_import.owl` results in losing taxa that are only referenced in `never_in_taxon` annotations (if I'm interpreting the situation correctly). I assume this is because these assertions aren't expanded prior to running `robot extract`. This may be easier to deal with after we can use `robot expand`, but if there is an easy solution in the meantime that would be great.

**Comment by anitacaron** [comment]
Related to https://github.com/obophenotype/uberon/issues/2382

**Comment by anitacaron** [comment]
I ran `make imports/ncbitaxon_import.owl` (both with and without `-B`) now in a new branch from master, and it doesn't result in deleting any taxa, only updating some synonyms.
Honestly, I tried the same at the time @balhoff opened the issue and had the same as him. Is it a new mystery to solve, or is it good something solved by itself?

**Comment by shawntanzk** [comment]
seems solved? will close this for now, if there is still an issue, please reopen ticket
