### ISSUE TITLE
taxon disjoints missing from locally built uberon.owl

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#2533]
Please correct me if I'm missing it, but as far as I can tell, the Uberon build doesn't use `taxslim-disjoint-over-in-taxon.owl` anywhere, or generate the axioms it contains, like:

```
('in taxon' some Opisthokonta) DisjointWith ('in taxon' some Viridiplantae)
```

Without these axioms, taxon constraints don't do anything in OWL EL. I would expect to find these GCIs in the final Uberon product. I'm running into this while trying to test some edits for #2349.

**Comment by balhoff** [comment]
I do see a disjoint axiom like that in #2367; can some explain where they're used?

**Comment by balhoff** [comment]
Now I see that these axioms are present in the released `ext.owl`, but not the version I built locally by running `make ext.owl`. What am I doing wrong?

**Comment by matentzn** [comment]
This is so weird. In ext.owl they must be coming in from through CL or something.. 

Can you summarise the functional problem with these axioms missing? I think that the for the subset generation, which is the place using the taxon constraints are used in Uberon, some other owltools based step is invoked after the fact, but the disjointness axioms are not shipped out.. From your understanding, should the taxon disjointness axioms be present in the release? So that it works with, for example, your OBO taxon plugin?

**Comment by balhoff** [comment]
I think the taxon constraints should be working for any DL coherency check, not just to generate subsets. If you don't have axioms like `('in taxon' some X) DisjointWith ('in taxon' some Y)`, then there is no way to infer an unsatisfiable class based on taxon constraints (using OWL EL). Personally I think the taxon disjointness axioms should be in the release. They're definitely needed for the Protege taxon constraints plugin to work.

**Comment by matentzn** [comment]
@cmungall Do you see any reason _not_ to release the unfolded taxon constraints in Uberon?

**Comment by cmungall** [comment]
> Do you see any reason not to release the unfolded taxon constraints in Uberon?

To be pedantic, axioms like

`('in taxon' some X) DisjointWith ('in taxon' some Y)`

are not themselves taxon constraints. This is part of the axiomatization of NCBITaxon.

The documentation for this is very buried:
https://github.com/obophenotype/ncbitaxon/blob/master/subsets/README.md

I have no problem in incorporating these in a merged release file accompanying the taxon constraints themselves. But be aware from the point of view of assembly non-redundant subsets of ontologies using base files, these would not be included. They *should* come from some kind of ncbitaxon-base, were such a thing to exist

**Comment by shawntanzk** [comment]
Action item: 

- [ ] Figure out where `('in taxon' some X) DisjointWith ('in taxon' some Y)` live (look through uberon.makefile)
- [ ] Specify new component for these axioms (make sure to only import needed axioms - ie related to taxa we use) 
- [ ] Make PR and see what breaks

**Comment by anitacaron** [comment]
- [X] Figure out where ('in taxon' some X) DisjointWith ('in taxon' some Y) live (look through uberon.makefile)

This is not in the pipeline right now. We need to merge the `taxslim-disjoint-over-in-taxon.owl` as Jim said.

A related issue that will fix this #2707

**Comment by anitacaron** [comment]
After refactoring the Makefile, the `ext.owl` artefact was removed because it was the same as `uberon.owl`. For now, it's only adding in the QC.

**Comment by gouttegd** [comment]
Taxon disjointness axioms are now included in `uberon.owl`, for all taxa that are imported by Uberon. Closing here.
