### ISSUE TITLE
Add the top 3-5 PRs / issues that need DOS attention or CJM attention

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2539]
(Chris, David please do not read this issue, not of your business 😛 )

@shawntanzk @rays22 @anitacaron I would like to try the following

We have CJM (Chris Mungall) and DOS (David) high priority boards. There should never be more than 5 priority issues on it.

- [CJM](https://github.com/orgs/obophenotype/projects/12/views/1)
- [DOS](https://github.com/orgs/obophenotype/projects/13/views/1)

Of all the open PRs in Uberon, CL, PATO and RO, can you find the top three ones that we should have these two review and pass? We will then create a new process in which we will nag them during ever Tech call to get these done. Just 3 - no more. 

This issue can be closed as soon as both boards have at least 3 issues (or more importantly, pull requests) on them. Thanks!

**Comment by anitacaron** [comment]
Done

**Comment by matentzn** [comment]
Thanks @anitacaron. @shawntanzk @rays22 also both add your top3 issues as well, we will prioritise during tech call.

**Comment by shawntanzk** [comment]
top 3 personal or repo tickets lol

**Comment by matentzn** [comment]
Mix. Top 2 personal Top 1 repo. The goal is to keep PRs open no longer than 3 weeks..

**Comment by matentzn** [comment]
(and get feedback on key issues relevant to our projects)

**Comment by shawntanzk** [comment]
In Tech call we will reviewer both CJM and DOS board and pick top 3 topics. @matentzn will convey to them for now, but eventually they should just pick this up
