### ISSUE TITLE
Clean up owltools expand (if its not being used)

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2552]
We should clean up uberon.makefile if owltools expand is not needed
should check before cleaning up though - not 100% sure if its still being used

**Comment by anitacaron** [comment]
Just to let you know and to be linked here in this issue, `expand-macros` is removing the annotation that is being expanded as noted [here](https://github.com/obophenotype/uberon/issues/2382). It's the only place that `expand-macros` is relevant in the `uberon.Makefile`.

**Comment by shawntanzk** [comment]
owltools expand is already replaced with robot expand 
however, owltools still needs to remain for composite products (see https://github.com/obophenotype/uberon/issues/2588#issuecomment-1280861427)
