### ISSUE TITLE
nipple should be a part of mammary gland

### ISSUE THREAD

**Issue by raymond91125** [obophenotype/uberon#2560]
**Uberon term**
nipple UBERON:0002030
mammary gland UBERON:0001911

**Suggested revision and reasons**
nipple part_of mammary gland
This relationship is implied in Wikipedia references, and https://biologydictionary.net/mammary-glands/, even in male.
https://github.com/geneontology/go-ontology/issues/22941

**Comment by shawntanzk** [comment]
Thanks for bringing this up, we are already discussing this over at this ticket: https://github.com/obophenotype/uberon/issues/1873
I have copied your comment over and will close this ticket
