### ISSUE TITLE
Tighten taxon constraints for skeletal muscle organ and somatic muscle

### ISSUE THREAD

**Issue by raymond91125** [obophenotype/uberon#2563]
**Uberon term**
UBERON:0014892 skeletal muscle organ
UBERON:0014895 somatic muscle

**Suggested revision and reasons**
UBERON:0014892 skeletal muscle organ 'only in taxon' some Eumetazoa
Definition: "A muscle organ that consists of skeletal muscle tissue ensheathed in epimysium, that develops from myotome and that is innervated by some somatic motor neuron. Skeletal muscles are typically attached (via a tendon) to a bone but there are exceptions (e.g. intrinsic tongue muscles)."
Appears to refer to vertebrate skeletal muscle. Maybe add 'only in taxon' some Craniata to avoid confusion.

UBERON:0014895 somatic muscle 'only in taxon' some Eumetazoa
Definition: "A muscle structure of invertebrates whose origin and insertion sites are in basal side of the epidermis or structures derived from it. The simplest somatic muscles consist of a single cell and associated extracellular structures."
Maybe add 'never in taxon' some Craniata.

Further discussions here https://github.com/geneontology/go-ontology/issues/19666

**Comment by bvarner-ebi** [comment]
RE: **UBERON:0014892 'skeletal muscle organ'**

>Appears to refer to vertebrate skeletal muscle. Maybe add 'only in taxon' some Craniata to avoid confusion.

@raymond91125, would adding `'only in taxon' some 'Vertebrata <vertebrates>'` and updating the label to ''skeletal muscle organ (vertebrate)' be appropriate? 

-----

RE: **UBERON:0014895 'somatic muscle'**

> Maybe add 'never in taxon' some Craniata.

This class currently has the annotation `'never in taxon' some 'Vertebrata <vertebrates>'`. Is that already sufficient?

The text definition also has "A muscle structure of invertebrates ...". Is it appropriate to relabel this class as 'somatic muscle (invertebrate)'? 
My understanding is "somatic muscle" is any muscle derived from a somite and is not limited to invertebrates. 
Dbxref for the text def is GOC:DOS (@dosumis?).

**Comment by dosumis** [comment]
@gouttegd - Could you comment on this?  It seems like use in flies vs vertebrates does not reflect common semantics.  Maybe we need two sensu terms?

**Comment by gouttegd** [comment]
In flies “somatic muscle” and “skeletal muscle” are used interchangeably and refers to muscles that are attached at both ends to the cuticle (opposed to “visceral muscle”, which are either attached to the cuticle by only one end – the other end being attached to the viscera – or not attached to the cuticle at all). In Fbbt we call them “somatic”, with “skeletal” being an exact synonym.

I _think_ that in vertebrates _also_ “skeletal” and “somatic” are routinely used interchangeably. Therefore, if we want to distinguish between insect skeletal/somatic muscles and vertebrate skeletal/somatic muscle (which is apparently what we are currently doing with “skeletal muscle organ” which seems to refer to vertebrate only and “somatic muscle“ which seems to refer to insect only — but I am not sure this distinction is needed), the distinction should _not_ be done by calling the vertebrate term “skeletal” and the insect term “somatic”. Instead I would agree that the taxon specificity should be made apparent in the labels, e.g. by renaming the insect-specific term “insect somatic muscle” or “somatic muscle (sensu Insecta)”.

**Comment by gouttegd** [comment]
Related: last time I checked the entire “muscle” stuff in Uberon was in needs of some clarifications (https://github.com/obophenotype/uberon/issues/2688). That is still on my radar, but frankly quite low in my priority list right now…

**Comment by bvarner-ebi** [comment]
@gouttegd, thank you for the clarifications and suggestions.

Regarding labels, in CL there was discussion on noting taxon restraints in the labels using the format:

'{cell type}, {taxon}'

For example, '[dendritic cell, human](http://purl.obolibrary.org/obo/CL_0001056)' and '[ILC1, human](http://purl.obolibrary.org/obo/CL_0001077)'.

This was discussed in CL call 19/10/2022 and noted in [this comment](https://github.com/obophenotype/cell-ontology/pull/1696#issuecomment-1256353142). Apart from human-specific classes, which would use the format above, consensus has not been established and/or implemented. 

With the above in mind, here are the proposed edits:

**UBERON:0014892 'skeletal muscle organ'**
- [ ] add` 'only in taxon' some 'Vertebrata <vertebrates>' `
- [ ] update the label to ''skeletal muscle organ, vertebrate'

**UBERON:0014895 'somatic muscle'**
Assuming, as the text definition currently states, this class is applicable to all invertebrates:
- [ ] add` 'present in taxon' some Insecta` 
   - `'never in taxon' some 'Vertebrata <vertebrates>'` is already present - no change
- [ ] update the label to 'somatic muscle, invertebrate'

**Comment by bvarner-ebi** [comment]
@gouttegd, @raymond91125, can you comment if the proposed edits above are appropriate? If further discussion is needed, kindly add to the monthly Uberon call agenda.

**Comment by gouttegd** [comment]
Looks good to me.

**Comment by raymond91125** [comment]
fine to me also. thanks.
