### ISSUE TITLE
[NTR] cerebellum vermis lobule IV-V

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2566]
Follow patterns in http://purl.obolibrary.org/obo/UBERON_0004070 child nodes
Needed for ABA-uberon mapping
@patrick-lloyd-ray - I assume this term is an intermediary? Given atlas has defined boundaries, im not 10% sure how to define this in the ontology as uberon already has cerebellum vermis lobule IV and V - Is mapping those to uberon terms alright then? should it be a subclass instead of equivalent then? 

Thanks

**Comment by patrick-lloyd-ray** [comment]
How about http://purl.obolibrary.org/obo/UBERON_0007763?

**Comment by shawntanzk** [comment]
can make it a subclass of http://purl.obolibrary.org/obo/UBERON_0007763, but would be nice to have an equivalent class esp since there is precedence for it (http://purl.obolibrary.org/obo/UBERON_0004079 & http://purl.obolibrary.org/obo/UBERON_0004077) - Ive already

**Comment by patrick-lloyd-ray** [comment]
Yes, sorry, I meant subclass of UBERON:0007763. I think mapping to those terms is fine.

**Comment by shawntanzk** [comment]
will close this ticket then
