### ISSUE TITLE
Revise pancreas organ definition--> uses GO, which needs update

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#2572]
**Uberon term**
pancreas UBERON:0001264 http://purl.obolibrary.org/obo/UBERON_0001264 

**Suggested revision of textual definition**
Our HuBMAP pancreas expert emailed this morning and asked if the definition could be revised to correct a mistake in the definition that comes from GO.

GO definition: "An endoderm derived structure that produces precursors of digestive enzymes and blood glucose regulating ***enzymes***[GO]. [ http://amigo.geneontology.org/amigo/term/GO:0031016 ] "

The last part "blood glucose regulating ***enzymes***[GO]." should read blood glucose regulating hormones.

Substitute hormones for the term enzymes in the second part of the definition.

On Jul 18, 2022, at 8:37 AM, Campbell-Thompson, Martha <[thompmc@pathology.ufl.edu](mailto:thompmc@pathology.ufl.edu)> wrote:
Hi Ellen- on several webpages, this is listed for Pancreas:

![image001](https://user-images.githubusercontent.com/47257000/179552951-91105a30-f5bb-4b87-92a9-eea210507378.png)
 
Please get the second enzymes changed to hormones. Should be blood glucose regulating hormones.
 
Sincerely,
Martha

**Comment by bvarner-ebi** [comment]
@emquardokus, I'll make the change in Uberon and create a ticket for the definition to be updated in GO as well.

**Comment by bvarner-ebi** [comment]
https://github.com/geneontology/go-ontology/issues/23777 has been submitted to update the text definition for the related GO term.
