### ISSUE TITLE
Where are the composite subsets?

### ISSUE THREAD

**Issue by fbastian** [obophenotype/uberon#2578]
Hi,

I try to find the composite-metazoan version of Uberon, but I don't see it. I need notably to access the composite life-stages.

* On [this page](http://obophenotype.github.io/uberon/combined_multispecies/) there is mention of a collected-eukaryote, but the link does not work
* And anyway I'm interested in the composite version, not the collected
* In the [subset folder](https://github.com/obophenotype/uberon/tree/master/subsets), the [life-stages-composite.obo](https://github.com/obophenotype/uberon/blob/master/subsets/life-stages-composite.obo) hasn't been updated in two years, while there was a recent integration of the updates from https://github.com/obophenotype/developmental-stage-ontologies/.

**Comment by shawntanzk** [comment]
@matentzn - could you help, I'm guessing something to do with release now

**Comment by shawntanzk** [comment]
@fbastian have you looked into the version in our latest release of uberon? (https://github.com/obophenotype/uberon/releases/tag/v2022-06-30) - I've just checked and composite-metazoan is attached there :)

**Comment by matentzn** [comment]
Also note https://github.com/obophenotype/uberon/issues/2032

**Comment by matentzn** [comment]
FYI, here is the collected version, (its a static file btw: https://github.com/obophenotype/uberon/blob/master/src/ontology/bridge/collected-eukaryote.owl).

I will close this issue now, as I don't see how to further act on it, but @fbastian please persist and reopen if you are still having issues.
