### ISSUE TITLE
diastema

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#2602]
**Uberon term**
diastema

**Suggested revision of textual definition**
Currently it says "a space or gap between two consecutive teeth". I'd like to remove the term "consecutive" as in 1) it is assumes a sequence, like between incisor 1 and incisor 2, but if incisor 2 is missing, then it would be between incisor 1 and a canine; 2) some animals with diastemas, like horses which have diastemas between their incisors and premolars, have vestigial canines that may appear in the diastema, but the diastema is still considered between the incisor and premolar.

**Comment by megbalk** [comment]
@nicolevasilevsky would you like me to do this ticket?

**Comment by nicolevasilevsky** [comment]
sure, thank you!
