### ISSUE TITLE
palate bone, palatine bone, and hard palate

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#2603]
These are confusing and adding more information in the definition would help.

Hard palate: change "and palatine" to "and the palatine bone".
Palatine bone: add that it helps for the hard palate.

palate bone: it is unclear to me how this is different from palatine bone.

**Comment by nicolevasilevsky** [comment]
I'll fix these defs @megbalk

**Comment by nicolevasilevsky** [comment]
> palate bone: it is unclear to me how this is different from palatine bone.

@megbalk did you google this? If needed, I can ask a colleague with expertise in craniofacial medicine.

**Comment by megbalk** [comment]
@nicolevasilevsky I did, and that is why it is unclear to me.

**Comment by nicolevasilevsky** [comment]
@megbalk I'll ask my colleague!

**Comment by nicolevasilevsky** [comment]
@RDruzinsky thnaks for your reply!

Note, I deleted your contact info from the comment, because this is a public site

**Comment by megbalk** [comment]
Agreed. I am unsure what "palate bone" is trying to accomplish that palatine bone and hard palate don't already, and it adds more confusion.
