### ISSUE TITLE
New term requests to support Daphnia magna anatomical annotations

### ISSUE THREAD

**Issue by proccaserra** [obophenotype/uberon#2607]
**This is a batch request for term addition, hence the table**

Daphnia magnaAnatomical ID | System/structure (Display Name) | Parent Structure | definition | definition source | parent term | synonym | editor | orcid | Suggested Parent Class in UBERON | UBERON identifier | UBERON class label | SKOS relation to UBERON class | Comment
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2200 | Food Groove | Digestive | elongated median channel between bases of thoracic limbs, where the food is transferred to the mouthpart | DOI: https://doi.org/10.1098/rstb.1991.0001 | digestive system | food channel | Mee Siing Ngu | 0000-0002-7638-4659 | ? | ? | ? | ? | TERM REQUEST
2510 | Labral Gland Cell | Labrum | cell at the base and in the median part of labrum | PMID: 29929348 | labrum |   | Mee Siing Ngu | 0000-0002-7638-4659 | ? | ? | ? | ? | TERM REQUEST
4110 | Protopodite | Antenna | basal part of each antenna; relatively long, bearing two- to four-segmented dorsal and ventral branches (rami) | PMID: 24540161 | antenna | protopod | Mee Siing Ngu | 0000-0002-7638-4659 | ? |   |   |   | TERM REQUEST
4120 | Ramus | Antenna | dorsal or ventral branches of antennae | PMID: 24540161 | protopodite |   | Mee Siing Ngu | 0000-0002-7638-4659 | ? |   |   |   | TERM REQUEST
4130 | Seta | Ramus | one of numerous bristle-like projections extending from appendage or body | PMID: 24540161 | ramus |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0013703 | integumentary projection | broader | TERM REQUEST
4210 | Copulatory Hook (Male) | Thoracic Limb 1 | chitinized hooks of male Daphnia that are used for clasping the females during copulation | ISBN:9057821516 9789057821516 or https://doi.org/10.1093/plankt/fbl041 | thoracic limb 1 | clasping hook | Mee Siing Ngu | 0000-0002-7638-4659 | ? |   |   |   | TERM REQUEST
4220 | Seta | Thoracic Limb 1 | bristle-like projection extending from thoracic limb 1 | ISBN:9057821516 9789057821516 or https://doi.org/10.1093/plankt/fbl041 | thoracic limb 1 |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0013703 | integumentary projection | broader | TERM REQUEST
4410 | Filter Plate 3 | Thoracic Limb 3 | food filtering apparatus on the gnathobases of thoracic limbs 3 | https://doi.org/10.1098/rstb.1991.0001 | thoracic limb 3 | filter | Mee Siing Ngu | 0000-0002-7638-4659 | ? |   |   |   | TERM REQUEST
4510 | Filter Plate 4 | Thoracic Limb 4 | food filtering apparatus on the gnathobases of thoracic limbs 4 | https://doi.org/10.1098/rstb.1991.0001 | thoracic limb 4 | filter | Mee Siing Ngu | 0000-0002-7638-4659 | ? |   |   |   | TERM REQUEST
5020 | Antennule Muscle (Male) | Muscular | muscle in the antennule | https://doi.org/10.1002/iroh.19310260104 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001630 | muscle organ | broader | TERM REQUEST
5030 | Anterior Carapace Adductor Muscle | Muscular | muscle attached to the carapace that pulls it to the body | https://doi.org/10.1098/rstb.1991.0001 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001630 | muscle organ | broader | TERM REQUEST
5040 | Anterior Rotator Muscle of Mandible | Muscular | anterior rotator muscle of the mandible | https://doi.org/10.1002/iroh.19310260104 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001630 | muscle organ | broader | TERM REQUEST
5050 | Circular Muscle | Muscular | muscle encasing the cecum and gut | https://doi.org/10.1016/C2011-0-05143-8 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_2005279 | enteric circular muscle | narrower | TERM REQUEST
5060 | Dorsal Longitudinal Muscle | Muscular | dorsal muscle that extends along each side of the body | https://doi.org/10.1098/rstb.1991.0001 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001630 | muscle organ | broader | TERM REQUEST
5070 | Esophageal Dilator Muscle | Muscular | dilator muscle of the esophagus | https://doi.org/10.1098/rstb.1991.0001 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0003832 | easophagus muscle | broader | TERM REQUEST
5080 | Horizontal Muscle | Muscular | horizontal muscle along each side of the body | https://doi.org/10.1098/rstb.1991.0001 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001630 | muscle organ | broader | TERM REQUEST
5090 | Oblique-Lateral Muscle | Muscular | muscle branching from the ventral longitudinal muscle | https://doi.org/10.1002/iroh.19310260104 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001630 | muscle organ | broader | TERM REQUEST
5100 | Postabdominal Muscle | Muscular | adductor muscle on the abdomen/postabdomen | https://doi.org/10.1002/iroh.19310260104 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001630 | muscle organ | broader | TERM REQUEST
5110 | Posterior Carapace Adductor Muscle | Muscular | muscle attached to the carapace that pulls it to the body | https://doi.org/10.1098/rstb.1991.0001 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001630 | muscle organ | broader | TERM REQUEST
5120 | Posterior Rotator Muscle of Mandible | Muscular | posterior rotator muscle of the mandible | https://doi.org/10.1002/iroh.19310260104 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001630 | muscle organ | broader | TERM REQUEST
5130 | Rectal Dilator Muscle | Muscular | dilator muscle around the rectum | https://doi.org/10.1098/rstb.1991.0001 | musculoskeletal |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0018112 | rectum smooth muscle tissue | narrower | TERM REQUEST
7000 | Postabdomen |   | recurved posteriormost region of trunk | https://www.ncbi.nlm.nih.gov/books/NBK2036 | abdomen |   | Mee Siing Ngu | 0000-0002-7638-4659 | ? | ? | ? | ? | TERM REQUEST
7100 | Abdominal Process | Postabdomen | dorsal processes projecting from border of trunk and postabdomen; one is considered to serve in closing off brood chamber posteriorly | https://www.ncbi.nlm.nih.gov/books/NBK2036 | postabdomen |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0013703 | integumentary projection | broader | TERM REQUEST
7300 | Postabdominal Claw | Postabdomen | one of two relatively short, claw-shaped projections at end of postabomen | https://www.ncbi.nlm.nih.gov/books/NBK2036 | postabdomen |   | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0013703 | integumentary projection | broader | TERM REQUEST
8420 | Gonopore (Male) | Testis | ejaculatory opening on the postabdomen of the male daphnia | ISBN:9057821516 9789057821516 or https://doi.org/10.1093/plankt/fbl041 | sperm duct | ejaculatory opening | Mee Siing Ngu | 0000-0002-7638-4659 | UBERON | http://purl.obolibrary.org/obo/UBERON_0001349 | externally connecting tube lumen | broader | TERM REQUEST

**Comment by shawntanzk** [comment]
@bvarner-ebi - can I leave this with you? I would recommend using templates for such a huge add.
@proccaserra - I think there are some issues with your MD formatting that is causing misalignment - please do check. It would also be good if you could work with @bvarner-ebi (if he takes this ticket) to create more ontology-conforming definitions for the terms requested. 
@bvarner-ebi - I will assign this to you for now, but do let me know if you need help etc. Thanks!

**Comment by proccaserra** [comment]
@shawntanzk thank you for picking this up so quickly. 
@bvarner-ebi , I have updated the issue to clear the error in the markdown table.
I can also provide a tsv file matching the template that would suit the process if you point me to it.

much appreciated!

**Comment by bvarner-ebi** [comment]
@proccaserra, thank you for the potential Uberon contributions.

To suggest new terms, we ask you provide information as requested in the new term request template: https://github.com/obophenotype/uberon/issues/new?assignees=&labels=new+term+request&template=a_adding_term.md
This will help an editor better understand your request. You can use the attached template as a guide.

[uberon_template.xlsx](https://github.com/obophenotype/uberon/files/9373830/uberon_template.xlsx)

As noted above, the definitions should be reviewed and written to align with Uberon standards. My recommendation is to review similar terms in Uberon and pattern your definitions off of those.

Please note there is currently a backlog of new term requests, so it may be a few months before this ticket would be started once the requested information is provided.

**Comment by MeeSiing** [comment]
@proccaserra @bvarner-ebi thank you for your help and information. I will use the template as a guide.

**Comment by shawntanzk** [comment]
@proccaserra btws this might help with definitions: https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/ 

I would advice you write it in genus-differentia method stated in the above :)

**Comment by proccaserra** [comment]
@shawntanzk indeed, this is best practice. I was brokering the submission on behalf of @MeeSiing.
@MeeSiing happy to assist if you further questions.

@bvarner-ebi , @shawntanzk regarding the timeline for processing the terms and to avoid any delay, were there any 'red-flags' from this list of terms? 
By `red-flag`, I mean any constraint on Uberon which would lead to rejecting a term. For instance, a term such as 'post abdomen' defined as 'recurved posteriormost region of trunk' (which once rephrased would be: a part of the trunk located in the most posterior region and which is recurved' ?).
thx

**Comment by bvarner-ebi** [comment]
@MeeSiing, @proccaserra, I noticed you have included a field called "Daphnia magnaAnatomical ID". Are these coming from an atlas or do you by chance already have a Daphnia magna-focused ontology?

Context of this question: Uberon covers metazoa, but has a vertebrate bias. Most, if not all, of these terms would require taxon restrictions. For example, food grooves and filter plates are not present in all metazoa, and would need to be annotated as such in Uberon.

**Comment by MeeSiing** [comment]
@proccaserra Thank you for the question about 'red-flags'. Please also point out to me if you have seen some and I will work on them. truly appreciate your help.
@bvarner-ebi these terms are daphnia specific and are from the daphnia histology atlas that I am developing http://daphnia.io. The ontology list can be found here (http://daphnia.io/assets/downloads/DaHRA/S2_File_Anatomy_ontology.xlsx). I compiled them from different resources and selected this list based on their relevance to current studies.

**Comment by shawntanzk** [comment]
Thanks @MeeSiing - just so we understand, what's your use case of adding the terms to uberon? I ask as I wonder if it makes more sense to convert the xls file into a species-specific ontology and link it to uberon using a bridge or [SSSOM](https://github.com/mapping-commons/sssom) - we can probably provide some support for you with that too. 

Would also like some input on this from @cmungall

**Comment by proccaserra** [comment]
The context is the following:
The project we are involved in currently working  with 6 species [Homo sapiens (cells), Xenopus laevis, Danio rerio, Drosophila melanogaster, C. elegans, Daphnia magna] exploring the effect of chemical agents (250 of them) with omics and imaging based phenotyping.
Since nothing (to my knowledge) exists for Daphnia and there is a need to go cross-species, the idea of pushing term to Uberon appealed as it could/would save having to maintain another resource.
Having said that, it seems an anatomy ontology for Daphnia magna would be straightforward to produce (technically speaking). Yet, if we can spare a mapping. 
Thank you all.

**Comment by cmungall** [comment]
Hi @proccaserra 

Short story: a separate ontology is probably the best bet in the short term

I'm open to incorporating directly in uberon but if we do this, we need to do it right, and this will require expertise in both comparative arthropod anatomy and familiarity with uberon patterns (there used to be an active arthropod anatomy ontology community, but I am not sure how active they are). I can help a bit here but it will be a bit of work

These are the kinds of things we'd need to address:

- what's the relationship of the proposed "labrum" term to the existing uberon [insect labrum](http://purl.obolibrary.org/obo/UBERON_0005905). Should the existing uberon term be generalized?
- similarly how best to generalize the current "insect thorax" to all arthropods
- how to deal with serial homology

If you start with your own ontology then you can go ahead and make terms like "thoracic limb 4" without getting bogged down in homology questions.

If you do make your own ontology you can reuse some uberon classes that should be safe for pan-arthropod usage:

- antenna
- testis
- muscle

I would try and reuse patterns as much as possible but we don't have great docs for this

**Comment by proccaserra** [comment]
Hi @cmungall 

Thank you for the insights. 
I was indeed concerned about these homologous structures.
We can work with @MeeSiing to generate the species specific ontology and then work with @shawntanzk and @matentzn to develop an SSSOM file against UBERON.

We might even help with the doc in the process. 
thx

**Comment by proccaserra** [comment]
Hi @bvarner-ebi , thank for checking. 
it sounds about right. If we need terms from uberon, we'll open an issue.
