### ISSUE TITLE
incoherency caused changes to genitourinary system

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2610]
This commit is probably causing some incoherency issues in Ubergraph:
https://github.com/obophenotype/uberon/commit/40e47c686350786a411775cd2c1340652b6566e1#diff-7dde9e81f71ce11962436529956798fa723e49d1bc8d188cc399d8009c2f72b4
see:
https://github.com/INCATools/ubergraph/issues/82
@bvarner-ebi - I see that this was originally your PR, could you help look into this please? 
@nicolevasilevsky & @cmungall - putting you in assignee list as you were involved with the PR too
Thanks

**Comment by shawntanzk** [comment]
btws the addition of: 
`[reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [genitourinary system](http://purl.obolibrary.org/obo/UBERON_0004122)`
seems to be the one causing the incoherence - I don't see anything inherently wrong with but perhaps relaxing: 
`[genitourinary system](http://purl.obolibrary.org/obo/UBERON_0004122) EquivalentTo [anatomical system](http://purl.obolibrary.org/obo/UBERON_0000467) and ([has part](http://purl.obolibrary.org/obo/BFO_0000051) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990)) and ([has part](http://purl.obolibrary.org/obo/BFO_0000051) some [renal system](http://purl.obolibrary.org/obo/UBERON_0001008))`
Might be the best modelling solution?

**Comment by bvarner-ebi** [comment]
> not all reproductive systems are part of the genitourinary system 

@shawntanzk, can you point me to an example of this?

**Comment by shawntanzk** [comment]
I think worms reproductive systems that arent part of urinary system 
Reproductive: 
![Screenshot 2022-08-16 at 13 29 27](https://user-images.githubusercontent.com/76212760/184879845-f34dff13-1615-4755-9eb7-64e9bbe8ff19.png)
Urinary: 
![Screenshot 2022-08-16 at 13 32 23](https://user-images.githubusercontent.com/76212760/184880376-08d259ca-9e70-4cb8-af8f-2ba9a54a402b.png)

**Comment by shawntanzk** [comment]
> Would it be related to asexual reproductive systems?

yeah I think so

**Comment by bvarner-ebi** [comment]
> I think worms reproductive systems that arent part of urinary system

I'm not sure about this, but I don't think worms produce urine / have urinary systems. That looks like a diagram of an excretory system.

**Comment by shawntanzk** [comment]
> I don't think worms produce urine / have urinary systems

Fair enough, I guess then like you suggest, there would be asexual reproductive systems that would not be part of some genitourinary system. Thanks :)

**Comment by balhoff** [comment]
> > I think worms reproductive systems that arent part of urinary system
> 
> I'm not sure about this, but I don't think worms produce urine / have urinary systems. That looks like a diagram of an excretory system. I guess since they don't have genitourinary systems, that would justify removing '[reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [genitourinary system](http://purl.obolibrary.org/obo/UBERON_0004122)'

I think that's right. The 'has part' that @shawntanzk suggested may be correct. Or else a taxon-scoped 'part of' could also be added. I'm not sure that the specific violation that Ubergraph reported is 100% valid, since GO probably shouldn't use Uberon reproductive system to cover fungi (see https://github.com/obophenotype/uberon/issues/2349). But in any case I don't think the relation to urinary system applies to all animals.

**Comment by shawntanzk** [comment]
Wanted to run a release, but I'll let ubergraph run a coherency check again first (no rush, so I'll just let the normal actions run) and do a release tmr :) thanks all!

**Comment by bvarner-ebi** [comment]
>> I don't think worms produce urine / have urinary systems

>Fair enough, I guess then like you suggest, there would be asexual reproductive systems that would not be part of some genitourinary system. Thanks :)

Now I'm reading about nephridial systems and not sure. 
Regardless, your proposed edit makes sense since not all reproductive systems need to be part of a GU system. Thanks for finding this.

**Comment by shawntanzk** [comment]
> Now I'm reading about nephridial systems and not sure.

Down the rabbit hole lol, I once spent a good chunk of time reading about width, length, and height >.<

**Comment by balhoff** [comment]
@shawntanzk I started a new Ubergraph check. I think you should have permissions to run those as well (https://github.com/INCATools/ubergraph/actions/workflows/test-merged.yaml).
