### ISSUE TITLE
sensory perception of pain: general class axiom

### ISSUE THREAD

**Issue by wdduncan** [obophenotype/uberon#2636]
**Uberon term**
[sensory perception of pain (go:GO_0019233)](http://purl.obolibrary.org/obo/GO_0019233) has the general class axioms:
```
'anatomical entity' and ('capable of part of' some 'sensory perception of pain') SubClassOf 'part of' some 'somatosensory system'
```
The GCA is not included in the `2022-07-01` version of `go.owl`. So, I am assuming (?) that it was added by UBERON.

Is this GCA asserting that `sensory perception of pain` is a subclass of `'anatomical entity' and ('capable of part of' some 'sensory perception of pain')`? If so, this seems incorrect ...

cc @cmungall @matentzn @dosumis 

**Suggested revision of logical definition**

**Comment by shawntanzk** [comment]
> Is this GCA asserting that sensory perception of pain is a subclass of 'anatomical entity' and ('capable of part of' some 'sensory perception of pain')? If so, this seems incorrect ...

I think this asserts that any anatomical entity that is 'capable of part of' some 'sensory perception of pain' is 'part of' some 'somatosensory system' which seems correct

**Comment by wdduncan** [comment]
@shawntanzk Yes. I think the logic of the GCA itself seems fine, but does this also assert that `sensory perception of pain` is a subclass of the GCA? If so, that seems wrong. `sensory perception of pain` is a process not an `anatomical entity`.

**Comment by shawntanzk** [comment]
@wdduncan I don't think it does - from my understanding GCA's wont make the class a subclass of it but rather applies generally to the ontology (as sort of standalone). I've asked about it being attached to a class before, but I can't fully rmbr the answer - i think it was something to do with administrative or something. But if you look at the source code (as in opening the obo or owl file with a text editor - you will see that it isn't a subclass_of). Hope that answers your question - if you do not have any more concerns, could you help me close this issue please? thanks heaps :)

**Comment by wdduncan** [comment]
Thanks for getting back to me @shawntanzk !
I also tagged @cmungall @matentzn and @dosumis in the issue b/c their OWL-foo is much better than mine :)   
Perhaps we can pester them for clarification?  
In the mean time, I'll try to find some time experiment with GCAs. I can reason over UBERON using HermiT on my laptop.

**Comment by cmungall** [comment]
Why don't you try the experiment and see if your assumption is correct Bill? 

Hint: you don't need hermit, GCIs are within EL++ (we use GCIs extensively in uberon and rely solely on Elk) In fact you don't need to use all of uberon you could just make a small unit test ontology to try your assumption.

**Comment by wdduncan** [comment]
Thanks @cmungall   
I will test on a smaller toy example :)

What does it mean when a GCI is displayed in the side panel of Protege? I’ve only used a GCI for anonymous class expressions.

**Comment by uberon** [comment]
See also
https://github.com/obophenotype/uberon/wiki/Evolutionary-variability-GCIs

And the section on GCIs from the paper

https://genomebiology.biomedcentral.com/articles/10.1186/gb-2012-13-1-r5

See also
http://ontogenesis.knowledgeblog.org/1288

**Comment by wdduncan** [comment]
Ok. I did some playing around in Protege. It turns out that if a GCI mentions a class, then that GCI appears in the `General class axioms` view in the right hand panel. It doesn't add any other inferencing to the class selected in the left hand panel.

Thanks for entertaining my question :)
