### ISSUE TITLE
skin of calf

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2638]
**Uberon term** lower leg skin UBERON:0004264

**Synonym to be added** skin of calf; calf skin

**broad/exact/narrow/related ?** narrow

**Comment**: 
Calf is the back of the lower leg. Calf appears in UBERON as narrow synonym of hindlimb zeugopod UBERON:0003823. I do not know what is best:
1- create term calf and remove it from narrow synonym of hindlimb zeugopod UBERON:0003823, and then create calf skin
2- add calf skin to lower leg skin UBERON:0004264.
I think 1 is more correct, but let you decide, thanks

**Comment by cmungall** [comment]
Let's just go ahead and and front and back compartments for HZ and out calf in its proper place. Various parts will need pushed down

See also #2358
