### ISSUE TITLE
QC fails at dc-contributor annotation on obsolete terms

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2655]
Currently QC seems to be unhappy about dc-contributor annotation on obsolete terms
It seems to think that dc-contributor is a logical axiom - possibly cause of `relationship:` in obo format? 
See https://github.com/obophenotype/uberon/pull/2647

- [ ] Fix the failing check in the makefile to allow contributor relationships (I am assuming that contributor has metadata: True in the OBO file.

**Comment by shawntanzk** [comment]
I think this is in check-obo-for-standard-release.pl in scripts folder:
I think cause dc-contributor is a relationship, so there is a flag for has relationship 
Not sure how to turn it off - don't know perl, could you help @anitacaron 

Thanks

```
unless ($disabled{'no-logical-axioms-on-obsolete-check'}) {
    foreach my $id (keys %obsh) {
        if ($xp{$id}) {
            flag('logic-axiom-references-obsolete', "$id has logical def @{$xp{$id}}");
        }
        if ($edge{$id}) {
            foreach (keys %{$edge{$id}}) {
                flag('logic-axiom-references-obsolete', "$id has relationship to $_");
            }
        }
        if ($disjoint_h{$id}) {
            flag('logic-axiom-references-obsolete', "$id $nameh{$id} in disjointness axiom $disjoint_h{$id}");
        }
    }
}
```

**Comment by anitacaron** [comment]
After digging the Perl script, I didn't find a way not to check the dc-contributor in obsolete terms. First, the script takes all relationships from all terms and later puts into a separate list the obsolete terms.

The solution that minimises the changes in the script is to exclude the check for dc-contributor from all terms.

**Comment by anitacaron** [comment]
Or I can change it back to `property_value` instead of `relationship`. I don't remember why we had to switch to `relationship`. I can even roll back the contributors that had to be deleted in the obsolete terms. I did some tests, and it seems to work fine.

Then, this won't be an issue anymore.

**Comment by matentzn** [comment]
No, we need to do the right thing.. There must have been a reason to switch to relationship, and I think it had to do with the nature of the value (<IRI>). The two are totally different..
