### ISSUE TITLE
Edinger-Westphal nucleus should be in the oculomotor nuclear complex 

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2658]
From Maryann Martone (@memartone)

I’ve been working a lot with UBERON for the SPARC project, and came across this note for the Edinger-Westphal nucleus http://purl.obolibrary.org/obo/UBERON_0002141:  
NIFSTD places this in oculomotor nuclear complex but this conflicts with disjointness axioms from MBA, as well as location described in Wikipedia, and is not supported in any other ontology
But NIFSTD is correct on this: 

Please see:  

1)  https://onlinelibrary.wiley.com/doi/10.1002/cne.22580:  
The Edinger-Westphal nucleus: A historical, structural, and functional perspective on a dichotomous terminology
"The eponymous term nucleus of Edinger-Westphal (EW) has come to be used to describe two juxtaposed and somewhat intermingled cell groups of the midbrain that differ dramatically in their connectivity and neurochemistry. On one hand, the classically defined EW is the part of the oculomotor complex that is the source of the parasympathetic preganglionic motoneuron input to the ciliary ganglion (CG), through which it controls pupil constriction and lens accommodation.”

2)   https://www.ncbi.nlm.nih.gov/books/NBK554555/: 
Neuroanatomy, Edinger–Westphal Nucleus (Accessory Oculomotor Nucleus)

The Edinger-Westphal (EW) nucleus, which is part of the oculomotor nuclear complex (ONC), was first described in the literature in the 17th century.[[1]](https://www.ncbi.nlm.nih.gov/books/NBK554555/#)

**Comment by cmungall** [comment]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/50745/191307914-736718ee-143e-4bbf-98e9-2df88b303e66.png">

**Comment by shawntanzk** [comment]
Oh! right! I was looking at owl:Nothing disjointness which of course it wouldn't ping with something like that - Perhaps we need to think of some automated check on that, but that's for another discussion. Thanks @cmungall 
EW (highlighted) = edinger-Westphal nucleus, III = oculomotor nucleus 
![Screenshot 2022-09-20 at 17 05 50](https://user-images.githubusercontent.com/76212760/191308894-b8b42cf4-4595-4649-8f2b-3de8913ded0b.png)
Looking at https://onlinelibrary.wiley.com/doi/10.1002/cne.22580:
![Screenshot 2022-09-20 at 17 10 06](https://user-images.githubusercontent.com/76212760/191309739-b921696c-0c58-4f9b-bca8-cf1f2fb1fca0.png)
I need to read the above paper more, so I think that the paper cited agrees with MBA modelling. Perhaps what we need to do is separate oculomotor complex and somatic oculomotor nuclei (III), and mapping MBA:35 to somatic oculomotor nuclei (III)

**Comment by shawntanzk** [comment]
To do for now: 

- [ ]  remove the comment and replace it with a link to this issue
