### ISSUE TITLE
uberon.owl is missing from master

### ISSUE THREAD

**Issue by asmvernon** [obophenotype/uberon#2670]
**Bug description**
`uberon.owl` is missing from master. Is this expected?

**Comment by shawntanzk** [comment]
I think it has to do with the new way we do our releases (@matentzn and/or @gouttegd could you help with this please?) 
But basically, you should be able to get it from the release (https://github.com/obophenotype/uberon/releases/tag/v2022-09-30) or alternatively our purl redirect at https://purl.obolibrary.org/obo/uberon.owl 
Hope that helps

**Comment by matentzn** [comment]
@shawntanzk you are right, we no longer check most Uberon release files into version control. @asmvernon, hi, you should always use the PURL that @shawntanzk mentioned above to access Uberon!

**Comment by shawntanzk** [comment]
I'll close this ticket for now, but please do reopen if you have any other concerns. Thanks :)

**Comment by asmvernon** [comment]
Thanks all! Will use the versioned endpoint then 👍 
Thanks for such a quick response!

**Comment by shawntanzk** [comment]
btws @asmvernon you should be using purls even for specific version yeah :) 
so for latest: 
https://purl.obolibrary.org/obo/uberon.owl
for specific version:
http://purl.obolibrary.org/obo/uberon/releases/2022-09-30/uberon.owl
