### ISSUE TITLE
mba root terms mapping to uberon

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2672]
Currently some root terms are not mapped well to uberon making some not great general mappings.
Can we map the following safely: 

MBA:1009 (fiber tracts) - UBERON:0000122 (neuron projection bundle)
MBA:1024 (grooves) - UBERON:0013118 (sulcus of brain)*

*editors note of UBERON:0013118: sulci are considered absent from lissencephalic mammals such as mice, but they may possess fissures. For example, the Allen mouse brain Atlas includes hippocampal, rhinal and choroid fissure. For this reason we do not place a taxon constraint on this class

**Comment by dosumis** [comment]
Seems reasonable.

**Comment by patrick-lloyd-ray** [comment]
Both seem reasonable to me.

**Comment by shawntanzk** [comment]
brilliant will map those two accordingly, thanks all :)
