### ISSUE TITLE
incorrect relation on 'taste bud'

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#2675]
Some Ubergraph build tests are revealing unsatisfiable classes. One example:

## [glossopharyngeal nerve development](http://purl.obolibrary.org/obo/GO_0021563) EquivalentTo [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [glossopharyngeal nerve development](http://purl.obolibrary.org/obo/GO_0021563) EquivalentTo [anatomical structure development](http://purl.obolibrary.org/obo/GO_0048856) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [glossopharyngeal nerve](http://purl.obolibrary.org/obo/UBERON_0001649))
    - [glossopharyngeal nerve](http://purl.obolibrary.org/obo/UBERON_0001649) SubClassOf [innervates](http://purl.obolibrary.org/obo/RO_0002134) some [taste bud](http://purl.obolibrary.org/obo/UBERON_0001727)
      - [taste bud](http://purl.obolibrary.org/obo/UBERON_0001727) SubClassOf [has_part](http://purl.obolibrary.org/obo/BFO_0000051) some [taste receptor activity](http://purl.obolibrary.org/obo/GO_0008527)
        - [taste receptor activity](http://purl.obolibrary.org/obo/GO_0008527) SubClassOf [transmembrane signaling receptor activity](http://purl.obolibrary.org/obo/GO_0004888)
          - [transmembrane signaling receptor activity](http://purl.obolibrary.org/obo/GO_0004888) SubClassOf [signaling receptor activity](http://purl.obolibrary.org/obo/GO_0038023)
            - [signaling receptor activity](http://purl.obolibrary.org/obo/GO_0038023) SubClassOf [molecular transducer activity](http://purl.obolibrary.org/obo/GO_0060089)
              - [molecular transducer activity](http://purl.obolibrary.org/obo/GO_0060089) SubClassOf [molecular_function](http://purl.obolibrary.org/obo/GO_0003674)
                - [gene product or complex activity](http://purl.obolibrary.org/obo/COB_0000038) EquivalentTo [molecular_function](http://purl.obolibrary.org/obo/GO_0003674)
                  - [gene product or complex activity](http://purl.obolibrary.org/obo/COB_0000038) SubClassOf [enabled by](http://purl.obolibrary.org/obo/COB_0000074) some 
([gene product](http://purl.obolibrary.org/obo/COB_0000073) or [protein-containing macromolecular complex](http://purl.obolibrary.org/obo/COB_0000075))
                    - [enabled by](http://purl.obolibrary.org/obo/COB_0000074) EquivalentTo [enabled by](http://purl.obolibrary.org/obo/RO_0002333)
                      - [enabled by](http://purl.obolibrary.org/obo/RO_0002333) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
                        - [has participant](http://purl.obolibrary.org/obo/RO_0000057) Domain [occurrent](http://purl.obolibrary.org/obo/BFO_0000003)
      - [taste bud](http://purl.obolibrary.org/obo/UBERON_0001727) SubClassOf [capable_of](http://purl.obolibrary.org/obo/RO_0002215) some [detection of chemical stimulus involved in sensory perception of taste](http://purl.obolibrary.org/obo/GO_0050912)
        - [capable_of](http://purl.obolibrary.org/obo/RO_0002215) Domain [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004)
          - [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004) SubClassOf [continuant](http://purl.obolibrary.org/obo/BFO_0000002)
  - [has_part](http://purl.obolibrary.org/obo/BFO_0000051) o [has participant](http://purl.obolibrary.org/obo/RO_0000057) SubPropertyOf: [has participant](http://purl.obolibrary.org/obo/RO_0000057)
  - [continuant](http://purl.obolibrary.org/obo/BFO_0000002) DisjointWith [occurrent](http://purl.obolibrary.org/obo/BFO_0000003)

I think the core problem is:
- [taste bud](http://purl.obolibrary.org/obo/UBERON_0001727) SubClassOf [has_part](http://purl.obolibrary.org/obo/BFO_0000051) some [taste receptor activity](http://purl.obolibrary.org/obo/GO_0008527)

An anatomical structure shouldn't have a process as a part. There is also a relation `'has part' some 'taste receptor cell'`; maybe the link to the activity was an accident? Or else, I'm not sure what relation to change the `has part` to.

**Comment by shawntanzk** [comment]
Thanks @balhoff :) 
I would think 'capable of' or 'capabe of part of' 
leave it with me, my term and all :)

**Comment by balhoff** [comment]
Sounds good! I'm not sure whether anything in the GO molecular_function branch should be connected to structures via 'capable of', since those all represent gene product activities. The existing 'capable of' relation to [detection of chemical stimulus involved in sensory perception of taste](http://purl.obolibrary.org/obo/GO_0050912) might be good enough?

**Comment by shawntanzk** [comment]
> I'm not sure whether anything in the GO molecular_function branch should be connected to structures via 'capable of',

Ah thanks :) you did my homework for me :) was going to look into the term and figure out what it is etc. 
I think given its a transmembrane signaling receptor activity, it should exist with the receptor or cell, defs not the structure anyway. Will remove the axiom, don't think it will affect anything :)

**Comment by shawntanzk** [comment]
Will create a ticket in CL to see how to link taste receptor cell to the GO term (or at least see if we should)

**Comment by shawntanzk** [comment]
I guess given this, there isn't a need to link anymore than [detection of chemical stimulus involved in sensory perception of taste](http://purl.obolibrary.org/obo/GO_0050912)
![Screenshot 2022-10-12 at 19 03 01](https://user-images.githubusercontent.com/76212760/195415502-b83d31ac-6ae5-4dfd-9f10-bc4cc500f1a5.png)
