### ISSUE TITLE
missing human teeth when comparing FMA to UBERON

### ISSUE THREAD

**Issue by wdduncan** [obophenotype/uberon#2692]
In order to use UBERON in the [OHD](https://github.com/oral-health-and-disease-ontologies/ohd-ontology), I need at least a complete set of human teeth (i.e., dentition).

I did a comparison between the FMA and UBERON, and found that UBERON was missing `52` (e.g., `FMA:55696` "Right upper third secondary molar tooth"). The full results can be seen [here](https://github.com/oral-health-and-disease-ontologies/ohd-ontology/blob/master/src/ontology/compare-fma-uberon-teeth/fma-uberon-misses.tsv).

The instructions for how I created the file are found on the [README](https://github.com/oral-health-and-disease-ontologies/ohd-ontology/blob/master/src/ontology/compare-fma-uberon-teeth/README.md).

**Comment by cmungall** [comment]
I can't find the link to the issue/DP now but there are a lot of issues pertaining to people wanting left and right classes materialized. Previously our recommendation has been to postcoordinate laterality for structures that exhibit lateral symmetry. We can always revisit this.

**Comment by wdduncan** [comment]
> Previously our recommendation has been to postcoordinate laterality for structures that exhibit lateral symmetry.  

Sorry. I was not aware of this recommendation.  

I can post-coordinate in the OHD, although then I'm faced with the choice of using the FMA classes for laterality or to just create new OHD classes.

**Comment by cmungall** [comment]
not sure what you mean.. if you can postcoordinate then you just need the base classes

if you don't have the optional of postcoordinating then either we precoordinate in uberon or you use FMA

**Comment by wdduncan** [comment]
> not sure what you mean.. if you can postcoordinate then you just need the base classes

Yes. I can create specific tooth classes in the OHD. E.g:
```
ohd:'upper right wisdom tooth' rdfs:subClassOf uberon:'upper third secondary molar tooth'
```

I can also import `FMA:55696` (Right upper third secondary molar tooth) and define it as subclass of the UBERON class. E.g.:
```
fma:'Right upper third secondary molar tooth' rdfs:subClassOf uberon:'upper third secondary molar tooth'
```

If I take the FMA route, there may be a few drawbacks:
- The FMA is no longer maintained (as far as I can tell)
- I have to decide if I keep the FMA axioms (e.g., `'constitutional part' some 'Cavity of right upper third molar tooth'`)
- I might be changing the semantics of the FMA class (see screenshot)

<img width="454" alt="image" src="https://user-images.githubusercontent.com/3186638/198118981-9ac5c146-5f59-4941-8b22-c858d5f25387.png">

**Comment by wdduncan** [comment]
> A tooth has parts. E.g. cingulum. We already precoordinate classes like cingulum of [upper,lower]{molar, incisor}[NUMBER] etc. If we precoordinate left and right for all tooth subclasses, do we also precoordinate the lateral parts?

I understand how this can cause maintenance issues :(    
For what it is worth, the FMA  does include a number of lateral specific tooth parts. E.g.:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/3186638/198128863-f414f0ed-c1bf-4fc8-8302-ffe52c4c1971.png">

The OHD is clinically biased. So, the lateral distinctions between teeth are needed (e.g., need to represent which wisdom tooth was extracted). In the clinical records I've worked with, I haven't seen tooth parts defined by laterality. For example, if the distal surface of the left lower canine was restored, there is no special code for the lower left canine distal surface.

If I assert the FMA classes to be subclasses of the UBERON classes am I committing the cardinal sin of axiom injection?  
Given that the FMA is not active, I am leaning towards simple creating the tooth classes in the OHD. This is more work for me in the short term, but may work out better in the long run.

**Comment by cmungall** [comment]
would you be up for adding the terms to uberon via dosdps?

**Comment by wdduncan** [comment]
Yes. I could do that. I'd have to brush up on dosdps :)

**Comment by shawntanzk** [comment]
Hi @wdduncan - I'm assigning this ticket to you, hope that is ok :)

**Comment by wdduncan** [comment]
@shawntanzk fine with me :)

**Comment by wdduncan** [comment]
@shawntanzk What is the best way to add this using the dosdp-patterns? 
In the [dosdp-patterns](https://github.com/obophenotype/uberon/tree/master/src/patterns/dosdp-patterns) directory I see some tooth patterns: [lower_tooth_pattern](https://github.com/obophenotype/uberon/blob/master/src/patterns/dosdp-patterns/lower_tooth_pattern.yaml), [upper_tooth_pattern](https://github.com/obophenotype/uberon/blob/master/src/patterns/dosdp-patterns/upper_tooth_pattern.yaml).

Should I add to these or create a new pattern (e.g., human_tooth_pattern.yaml)?

**Comment by shawntanzk** [comment]
Ah I did remember @megbalk doing some work with this - she would be the best person to talk to regarding this (I don't know the patterns and biology as well as I assume she would). Happy to help but she is probably a better first point :)

**Comment by uberon** [comment]
We don't add species-specific terms, if I understand correctly what you
need is laterialized teeth. We could have a pair of general
laterilization patterns, eg left_X and right_X

**Comment by megbalk** [comment]
We can add right and left to the patterns and just ignore right or left if not used?

**Comment by cmungall** [comment]
the existing system doesn't work well with unspecified fields. Others can correct me if I'm wrong but I think the best way to do this is two new patterns, two new TSVs

Later on we can explore using linkml-owl which allows a single yaml object for a laterializable structure to be in one record with all 3 ids

**Comment by wdduncan** [comment]
@cmungall do mean two new patterns for the right/left teeth? E.g., right_tooth_pattern.yaml.

Also, I'm not following some of the naming conventions. E.g.:
- `upper molar 1`
  - `upper first molar primary molar tooth`
  - `upper first secondary molar tooth`

Do we want the parent to be named `upper first molar tooth`?  Also, do we need the "tooth" modifier? Are there other molars that aren't teeth? All my google searches for "molar anatomy" returned teeth.

Also, I noticed that `upper first secondary molar tooth` is defined using the axiom:
```
'molar tooth 1'
 and ('part of' some 'upper jaw region')
 and ('part of' some 'secondary dentition')
```

`dentition` is defined as:
```
'anatomical collection'
 and ('has member' some 'calcareous tooth')
```

So, shouldn't we be using the `member of` relation for defining teeth (e.g., `'member of' some 'secondary dentition'`)?

**Comment by cmungall** [comment]
> dentition is defined as:

> 'anatomical collection'
>  and ('has member' some 'calcareous tooth')
> So, shouldn't we be using the member of relation for defining teeth (e.g., 'member of' some 'secondary dentition')?

good point.

**Comment by wdduncan** [comment]
> Note that we strive for consistency. The base class should be called "molar tooth" as "molar" is not going to be unique across OBO (chemistry).

Agreed :)

Wondering about the definition for `molar tooth 1`:  
```
The molar tooth of the upper or lower jaw that is phylogenetically number 1.
```
Do you know of a reference about this? I do now if `phylogenetically number 1` aligns with what dentist call the "first molar". E.g., In the figure below, I do not know if the teeth labeled "First Molar" are called that b/c they are the first molar encountered when counting teeth from front to back, or if this order aligns with phylogenetic order of how these teeth came to be. (P.S. The innermost numbers are the ADA  labels teeth; the outermost numbers are the FDI labels for teeth; the little diagrams between the numbers come from the Palmer system.)

<img width="714" alt="image" src="https://user-images.githubusercontent.com/3186638/199327102-7eaac1bc-fe19-43bf-8d23-a0f76c5aa3b9.png">

**Comment by cmungall** [comment]
@skansa @megbalk any thoughts on this? should we continue to group by homology?

**Comment by wdduncan** [comment]
Looking at this [figure](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3632217/figure/F2/) in this [article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3632217/), I am tempted to say that a "first molar" is type of `molar tooth 1`. But, I will defer to those who know more about tooth evolution (or evolution in general).

**Comment by wdduncan** [comment]
Can someone give me permissions to create new branches and do a PR w/o having to fork UBERON?

**Comment by cmungall** [comment]
you should have an invite

**Comment by wdduncan** [comment]
Thanks @cmungall !

**Comment by wdduncan** [comment]
since I'm adding specifically human teeth, do you want me to use the `only in taxon` OP? E.g.:
```
upper secondary right third molar only in taxon Homo sapiens
```
Or is there another/better way to tag the tooth type as being human specific?

**Comment by cmungall** [comment]
uberon is a multi-species ontology, there are very few species specific terms in it. you should make these as general as possible

**Comment by wdduncan** [comment]
@cmungall the `present in taxon` annotation seems pretty general to me:
```
S present_in_taxon T if some instance of T has some S. This does not means that all instances of T have an S - it may only be certain life stages or sexes that have S
```
As far as I can tell, it doesn't commit to a tooth type being only in humans. 

There are uses of `present in taxon` for humans. E..g.:
```
adipose tissue present in taxon Homo sapiens
```

**Comment by cmungall** [comment]
@wdduncan so sorry I didn't read your original comment closely enough, I read it as you wanting to put only-in-taxon

yes, please add present-in-taxons! thanks 🙏 🙏 🙏
