### ISSUE TITLE
nociception is not the same as sensory perception of pain

### ISSUE THREAD

**Issue by wdduncan** [obophenotype/uberon#2697]
**Uberon term**
GO:0019233 'sensory perception of pain' (Perhaps this needs to be a GO issue?)

**Bug description**
'sensory perception of pain' `has_exact_synonym` nociception  
According this [reference](https://www.physio-pedia.com/Nociception):
> The terms nociception and [pain](https://www.physio-pedia.com/Pain_Behaviours) should not be used synonymously, because each can occur without the other.[[1]](https://www.physio-pedia.com/Nociception#cite_note-1.-1). [Pain](https://www.physio-pedia.com/Pain_Mechanisms) arising from activation of the nociceptors is called nociceptive pain.

**Comment by cmungall** [comment]
did you mean to use this repo? This is a go term!

**Comment by wdduncan** [comment]
@cmungall That is why I asked "Perhaps this needs to be a GO issue?" :)
