### ISSUE TITLE
Request to add a definition to gland of anal sac & snout

### ISSUE THREAD

**Issue by Anoosha-Sehar** [obophenotype/uberon#2698]
Dear Uberon curators,

My name is Anoosha. I would like to make a request to add definitions to these Uberon terms, as a part of the AMR_GRDI project, I'm currently working on. I couldn't find the relevant template. Please let me know if in case I should add these in a different template or need to make any changes to any of it. Thank you.

**Uberon term**
[gland of anal sac](http://purl.obolibrary.org/obo/UBERON_0006333)
**Suggested revision of textual definition**
A small paired scent gland found in many mammals on either side of the anus between the external and internal sphincter muscles.
**Definition Source**
https://en.wikipedia.org/wiki/Anal_gland 

**Uberon term**
[snout](http://purl.obolibrary.org/obo/UBERON_0006333)
**Suggested revision of textual definition**
A part protruding from an animal's mid-face that consists of the nose, mouth, and jaw.
**Definition Source**
[https://en.wikipedia.org/wiki/Snout](https://en.wikipedia.org/wiki/Snout 
)

**Comment by anitacaron** [comment]
Hi @Anoosha-Sehar, thank you for your suggestion. We need to replace the definitions with '.'. @shawntanzk, if you agree with the request, replacing it isn't a problem.

**Comment by shawntanzk** [comment]
Happy to replace these manually, just wondering if we had a wider strategy to deal with all the . definitions - its been a long time since we have looked into this >.<

**Comment by anitacaron** [comment]
The solution would be to remove the definition property. The terms would still need to have a complete definition.
