### ISSUE TITLE
Taxon disjointness unsat not showing up in pipeline

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2707]
See https://github.com/obophenotype/uberon/pull/2702

From @balhoff 

> It means taxon constraints are not set up correctly. Four things are needed:

>taxon constraints in ontology
robot expansions (only for never_in_taxon)
import of taxonomy hierarchy
import of taxonomy in_taxon sibling disjointness

Assigning myself for now, but to discuss in tech support group call

**Comment by anitacaron** [comment]
@balhoff, I'm working on this now. One of the steps is "import of taxonomy in_taxon sibling disjointness", but in the [OBO Academy docs about taxonomy](https://oboacademy.github.io/obook/explanation/taxon-constraints-explainer/#employing-taxon-restrictions-in-your-qc-pipeline) it says:

> import http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim-disjoint-over-in-taxon.owl (or implement a way to generate the needed disjointness axioms)
Note: that file only covers a subset of the taxonomy, and is missing (in_taxon some X) DisjointWith (in_taxon some (not X)). You may need to implement a way to generate the needed disjointness axioms until this is corrected.

How can I implement that?

**Comment by balhoff** [comment]
@anitacaron you can use this SPARQL update: https://github.com/geneontology/go-ontology/blob/master/src/sparql/add-taxon-disjoints.ru

Or we can implement this issue at the source: https://github.com/obophenotype/ncbitaxon/issues/72
