### ISSUE TITLE
primary/secondary teeth are member of dentition (not part of)

### ISSUE THREAD

**Issue by wdduncan** [obophenotype/uberon#2711]
**Uberon term**
`secondary tooth` UBERON:0007775
`deciduous tooth` UBERON:0007115

deciduous (primary) and secondary teeth are defined using the class expressions:
```
'calcareous tooth' and ('part of' some 'primary dentition')
'calcareous tooth' and ('part of' some 'secondary dentition')
```

However, `dentition` (UBERON:0003672) is a type of `anatomical collection` (UBERON:0034925), and is defined using the class expression:
```
'anatomical collection' and ('has member' some 'calcareous tooth')
```
So, shouldn't primary and secondary teeth be **members of** their respective dentitions?

**Suggested revision of logical definition**
```
'calcareous tooth' and ('member of' some 'primary dentition') # primary tooth
'calcareous tooth' and ('member of' some 'secondary dentition') # secondary tooth
```

I mentioned this in #2692   
I can fix in a separate PR.

cc @shawntanzk @megbalk

**Comment by wdduncan** [comment]
The change to `member of` can be made in the lower_tooth_pattern.yaml and upper_tooth_pattern.yaml.

**Comment by megbalk** [comment]
fixed
