### ISSUE TITLE
[NTR] Moderator band a.ka. Septomarginal trabecula (heart)

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#2714]
**Preferred term label:**
Moderator band

**Synonyms**
Septomarginal trabecula

**Definition (free text, please give PubMed ID)**
https://en.wikipedia.org/wiki/Moderator_band_(heart)
The moderator band is located in the right ventricle.[[2]](https://en.wikipedia.org/wiki/Moderator_band_(heart)#cite_note-:0-2)[[3]](https://en.wikipedia.org/wiki/Moderator_band_(heart)#cite_note-:1-3) The moderator band connects the base of the anterior papillary muscles to the ventricular septum.[[2]](https://en.wikipedia.org/wiki/Moderator_band_(heart)#cite_note-:0-2)

Haroun, Heshmat. “Comparative Anatomy of the Cardiac Septomarginal Trabecula (Moderator Band).” Anatomy Physiology & Biochemistry International Journal 2 (May 6, 2017). https://doi.org/10.19080/APBIJ.2017.02.555595.
" In man, it connects the interventricular septum with the anterior wall of the right ventricle at the base of the anterior papillary muscle. It is also present in non-human mammals where it stretches between the bases of the muscles papilaris subarteriosus and magnus. Its morphology and structure varies in different species. It carries the continuation of the right bundle branch of the conducting system of the heart."

Lee JY, Hur MS. Morphological classification of the moderator band and its relationship with the anterior papillary muscle. Anat Cell Biol. 2019 Mar;52(1):38-42. doi: 10.5115/acb.2019.52.1.38. Epub 2019 Mar 29. PMID: 30984450; PMCID: PMC6449581.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
heart right ventricle UBERON:0002080 http://purl.obolibrary.org/obo/UBERON_0002080

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-7655-4833

**Comment by bvarner-ebi** [comment]
@emquardokus,
thank you for the new term.

I propose the following modelling. Kindly comment if you propose revisions.

preferred term label:
septomarginal trabecula

synonym:
moderator band (Exact)
https://doi.org/10.1016/j.morpho.2010.03.004)

text defintion:
A muscular trabecula in the right ventricle of the heart that links the lower part of the interventricular septum to the wall and to the base of the anterior papillary muscle of the right ventricle. The morphology and structure of the septomarginal trabecula varies in different species.
https://doi.org/10.1016/j.morpho.2010.03.004
https://doi.org/10.19080/APBIJ.2017.02.555595
PMID:30984450

subclasses:
is a UBERON:0000440 trabecula
located in UBERON:0002080 'heart right ventricle'

comment:
In humans, the septomarginal trabecula connects the interventricular septum with the anterior wall of the right ventricle at the base of the anterior papillary muscle. It is also present in non-human mammals where it stretches between the bases of the muscles papilaris subarteriosus and magnus. In some instances it carries the continuation of the right bundle branch of the conducting system of the heart. It is constituted of ordinary cardiac myocytes around and in between Purkinje myocytes.
https://doi.org/10.19080/APBIJ.2017.02.555595
https://doi.org/10.1016/j.morpho.2010.03.004

ORCID:
https://orcid.org/0000-0001-7655-4833

**Comment by bvarner-ebi** [comment]
@emquardokus, thank you again for the new term request.
The following has been added to Uberon and should be available in the next release:

UBERON:8470002 'moderator band'
