### ISSUE TITLE
incisor teeth

### ISSUE THREAD

**Issue by meghalithic** [obophenotype/uberon#2719]
**Uberon term**
central incisor tooth and lateral incisor tooth

**Suggested revision of logical definition**
both have EQ that include a set of dentition, rather than a specific tooth
In non-human mammals, the central incisor is the same as the first incisor, and the lateral incisor is the same as the second incisor. Since mammals can have up to five incisors, lateral incisor is a meaningless term.

central incisor EQ:
'incisor tooth'
 and ('in central side of' some 'incisor region of dentition')

lateral incisor EQ:
'incisor tooth'
 and ('in lateral side of' some 'incisor region of dentition')

incisor region of dentition def:
The subdivision of the dentition that consists entire of incisor teeth.

As these are specific teeth, not a set of teeth, I propose modeling the central and lateral incisor after other teeth, like the molars and premolars.

As an example:
molar tooth 1:
def: The molar tooth of the upper or lower jaw that is phylogenetically number 1.
Subclass: molar tooth

**Comment by megbalk** [comment]
@anitacaron is this issue done?

**Comment by megbalk** [comment]
Can we get help with it?
