### ISSUE TITLE
UBERON:0000933 'pharyngeal muscle' LD revision

### ISSUE THREAD

**Issue by raymond91125** [obophenotype/uberon#2724]
**UBERON:0000933 pharyngeal muscle**

**Suggested revision of logical definition**
'muscle organ' and ('part of' some 'musculature of pharynx')

See https://github.com/geneontology/go-ontology/issues/18285
Current LD for pharyngeal muscle is "'muscle organ' and ('part of' some 'musculature of pharynx')", which has redundant specification of "muscle/musculature". And 'musculature of pharynx' causes a possibly unnecessarily strict taxon restriction to Chordata. By changing 'musculature of pharynx' to 'pharynx' would relax the taxon constraint.

**Comment by cmungall** [comment]
I don't think we should have a pan-metazoan pharynx grouping, it's meaningless
