### ISSUE TITLE
Switch CHEBI import to slim

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2738]
After #2204 is merged, we should switch the unnecessarily enormous CHEBI import to the OBO slim, like we do for all other ontologies.

**Comment by anitacaron** [comment]
Isn't it better to include this change in PR #2204?

**Comment by matentzn** [comment]
Yes, but I didnt want to annoy you even more :D I was going to request the change, and then got scared you would kill me, so I made an issue instead. Feel empowered to do it in #2204

**Comment by anitacaron** [comment]
No worries! 😄
