### ISSUE TITLE
FMA_32676: cartilage of long bone

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2739]
**Uberon term** UBERON:0002516 (epiphyseal plate)

**Synonym to be added** cartilage of long bone

**broad/exact/narrow/related ?**

**Comment**
Check if FMA_32676 (cartilage of long bone) is synonym of UBERON:0002516 (epiphyseal plate).
The term « cartilage of long bone » is required to indicate the tissue origin of cell line https://www.cellosaurus.org/CVCL_C462
I made a NTR cartilage of long bone #2399 but I want to check first if it is not a synonym of UBERON:0002516 (epiphyseal plate).

**Comment by nicolevasilevsky** [comment]
According to wikipedia, this seems like an appropriate synonym:
https://en.wikipedia.org/wiki/Epiphyseal_plate

**Comment by nicolevasilevsky** [comment]
@paulacalipho maybe you should ask someone else to confirm, as I'm not 100% sure about this.

**Comment by nicolevasilevsky** [comment]
@pnrobinson - do you know if cartilage of long bone is an exact synonym of epiphyseal plate?

**Comment by pnrobinson** [comment]
Not if "cartilage of long bone" includes articular cartilage -- how is this defined actually? I do not think the term label is good, it seems rather ambiguous
