### ISSUE TITLE
Strategy for updating Relations Guide

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/uberon#2747]
1- Review relations of 'part of' - what are most used? 
Focus on top five and draft guidelines on their usage and make release.

See PR: https://github.com/obophenotype/uberon/pull/2720

2- Review relations of 'develops from' - what are most used?
Focus on top five and draft guidelines on their usage and make release.

**Comment by shawntanzk** [comment]
My proposal is to use what we have in this PR (https://github.com/obophenotype/uberon/pull/2720)
and from there add more relations.
Some I have used and think will be useful:

- [ ] extends fibers into
- [ ] innervates/innervated by
- [ ] capable of 
- [ ] capable of part of

**Comment by bvarner-ebi** [comment]
Closing this issue as the initially proposed work has been merged in #2720.
A new issue can be opened once there is refreshed strategy.
