### ISSUE TITLE
[Text def] 'lens of camera-type eye' 

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/uberon#2773]
UBERON term
UBERON:0000965 ['lens of camera-type eye'](http://purl.obolibrary.org/obo/UBERON_0000965)

Suggested revision of textual definition
The current text definition for ['lens of camera-type eye'](http://purl.obolibrary.org/obo/UBERON_0000965) equally describes the [cornea](http://purl.obolibrary.org/obo/UBERON_0000964). Consider revising/adding differentia to the text definition of ['lens of camera-type eye'](http://purl.obolibrary.org/obo/UBERON_0000965).

**Comment by shawntanzk** [comment]
Looks like a good first task given its just changing a text def :) @bvarner-ebi - shall I leave this for you to use as training? Will assign it to you for now, but feel free to change it accordingly.
