### ISSUE TITLE
Uberon for Human

### ISSUE THREAD

**Issue by Jordi-Valls** [obophenotype/uberon#2777]
Hi all,

I just want to ask, where I can find the Uberon for humans. I find in the documentation that one file called human-view.obo could be in subsets folder, however, I can not find it. Otherwise, if someone could tell me how can I select the human samples directly form uberon.obo, I will appreciate it a lot.

Thanks for your time,

Jordi

**Comment by anitacaron** [comment]
Hi @Jordi-Valls,

You can have access to the last version using the purl http://purl.obolibrary.org/obo/uberon/subsets/human-view.obo

And for the specific version, you can use the purl http://purl.obolibrary.org/obo/uberon/releases/2023-01-09/human-view.obo

**Comment by Jordi-Valls** [comment]
Sorry Anita,

I click the links but I'm unable to download the files... Also I looking for this file in this github but I cannot find it, I serach it in subsets folder or in the welcome page, but they are not included in it as previous versions...

Could you tell me where are this file?  I try to follow the link that you attach but, I'm not able to arrive it...  

Thanks

Jordi

**Comment by balhoff** [comment]
@Jordi-Valls I believe you're running into a problem with Chrome (or some other browser; Safari will download the files when clicking the links). Chrome doesn't let you click `http` links on `https` pages. I think if you copy the URL and paste it into the location bar of a new tab, it will download (tested in Chrome).

**Comment by Jordi-Valls** [comment]
@balhoff Really thanks! This is what exactly happens. I can download it.

Thanks @anitacaron and @balhoff  for your help!

Jordi

**Comment by shawntanzk** [comment]
Looks like this is solved, will close this ticket, please do reopen if you have any other issues :)
