### ISSUE TITLE
BUG: some strange CL classes in last release of composite-metazoan.obo (v2023-01-09)

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#2782]
Hello UBERON team,

in the last UBERON release (v2023-01-09) available in composite-metazoan.obo (v2023-01-09), there is obviously an issue for these CL classes here below, name is missing for example, and the xref disappeared

[Term]
id: CL:0000395
relationship: part_of FBbt:00017007 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! crystal cell primordium (Drosophila)
relationship: RO:0002292 http://flybase.org/reports/FBgn0002576 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! lz
[Term]
id: CL:0000396
is_a: FBbt:00001684 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! embryonic/larval hemocyte (Drosophila)
is_a: UBERON:0004120 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! mesoderm-derived structure
relationship: develops_from FBbt:00005248 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! prolamellocyte (Drosophila)
relationship: RO:0002292 http://flybase.org/reports/FBgn0032422 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! atilla

In previous release v2022-08-19, these classes were reported correctly:

[Term]
id: CL:0000395
name: procrystal cell
xref: FBbt:00001689
is_a: CL:0000387 ! hemocyte (sensu Arthropoda)
relationship: part_of FBbt:00017007 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! crystal cell primordium (Drosophila)
relationship: RO:0002292 http://flybase.org/reports/FBgn0002576 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! lz
[Term]
id: CL:0000396
name: lamellocyte
xref: FBbt:00001687
is_a: CL:0000394 ! plasmatocyte
relationship: develops_from FBbt:00005248 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! prolamellocyte (Drosophila)
relationship: RO:0002292 http://flybase.org/reports/FBgn0032422 {gci_relation="part_of", gci_filler="NCBITaxon:7227"} ! atilla

Thank you for your help.

Anne

**Comment by dosumis** [comment]
Can we make sure that this is on the tech group's radar?

**Comment by gouttegd** [comment]
It was already. It’s merely another one of the issues affecting `composite-metazoan`. I plan to overhaul the way this product is generated to fix all those issues at once – and hopefully not introducing new issues at the same time…

**Comment by gouttegd** [comment]
For the record, this issue is _not_ stale. The overhaul of the composite-metazoan pipeline (that will hopefully fix this issue) is still planned – but I want to cleanup the Makefile before I do anything else (#2973).

**Comment by gouttegd** [comment]
Should be fixed now with the new composite pipeline. Fixed `composite-metazoan` will be available at the next Uberon release.
