### ISSUE TITLE
Fetal cortex

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/uberon#2790]
**Preferred term label:** Metal cortex

**Synonyms**

**Definition (free text, please give PubMed ID)** 16619380

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**UBERON:0001851

**Your nano-attribution (ORCID)**

**Comment by ANiknejad** [comment]
Hello 

I close this issue and I explain you why. First, you are obviously looking after the 'cerebral cortex' and not the broad concept of 'cortex', so it is important to define correctly your needs.
UBERON anatomical structures do have information about the developmental stages the structure appears, you can see these informations in the .obo file, here available for download https://github.com/obophenotype/uberon/releases/download/v2023-01-09/composite-metazoan-basic.obo
For examples:

UBERON:0000956
name: cerebral cortex
relationship: existence_starts_during_or_after HsapDv:0000023 {gci_relation="part_of", gci_filler="NCBITaxon:9606"} ! Carnegie stage 16 (human)

If you are looking at the 'cerebral cortex' before Carnegie stage 16, 'telencephalon' will be the right one:

UBERON:0001893
name: telencephalon
relationship: existence_starts_during_or_after HsapDv:0000019 {gci_relation="part_of", gci_filler="NCBITaxon:9606"} ! CS12

Carnegie stages are the stages describing the human developmental stages, and are reported in the hsapdv.obo ontology, please look at https://www.ebi.ac.uk/ols/ontologies/hsapdv

Before submitting a NTR (New Term Request), I encourage you to look further into the concept of ontology, and also please be careful when writing (see your 'Metal cortex')
