### ISSUE TITLE
integration of XAO in last composite-metazoan, ex UBERON:0004069

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#2796]
hello Team,

maybe related to the current issue on composite-metazoan.obo, sorry in advance, but I am wondering why UBERON:0004069 does not have xref:XAO:0004530, while the cross-information between XAO and UBERON was already in XAO release 03/04/2021:

[Term]
id: XAO:0004530
name: accessory olfactory bulb
def: "The forebrain region that coordinates sensory signaling arising from the vomeronasal organ; it is located on the dorsal-posterior portion of the main olfactory bulb, and the axons that leave the accessory olfactory bulb project to targets in the amygdala and hypothalamus." [UBERON:0004069]
synonym: "anterior olfactory bulb" RELATED []
**xref: UBERON:0004069**
is_a: XAO:0003037 ! multi-tissue structure
relationship: end_stage XAO:0000437 ! death
relationship: part_of XAO:0004180 ! olfactory bulb
relationship: start_stage XAO:1000042 ! NF stage 26

Thank you in advance

Anne

**Comment by ANiknejad** [comment]
Actually I checked just now
https://github.com/obophenotype/uberon/blob/master/src/ontology/bridge/uberon-bridge-to-xao.obo
and XAO:0004530 is not present, why, if the cross-mapping between XAO and UBERON was already available in 2021?

**Comment by uberon** [comment]
I’m not sure xrefs are pulled from xao or any external ontology. The source
of truth has historically been the uberon source

**Comment by ANiknejad** [comment]
at Bgee, we do integrate xref when we create new developmental stage ontologies, and the xrefs are then imported into Uberon as far as I understand, so I supposed the same was done for anatomical structures. How are then anatomical structures integrated into Uberon? Who reviews the uberon-bridge-to... files?

**Comment by uberon** [comment]
I think the stage ontologies have their own pipeline..

**Comment by ANiknejad** [comment]
but here, I want say that this XAO class XAO:0004530, which is from XAO release 03/04/2021 DOES NOT be present in the last composite-metazoan, neither as a xref (as I expected) nor as a species-specific class

**Comment by gouttegd** [comment]
Should be fixed now. If you still find that some XAO classes are missing from `composite-metazoan` after the next release, please re-open.
