### ISSUE TITLE
Confusion about where to download composite metazoan

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#2800]
I am with @fbastian and the Bgee team, we are having some confusion about where to download composite metazoan from

Googling "uberon downloads" takes us to the stale website:

https://uberon.github.io/downloads.html

This has a link to this PURL
http://purl.obolibrary.org/obo/uberon/composite-metazoan.obo

The obo file doesn't include the versionIRI, but it looks like this is an old product; e.g. it has:

```
remark: Includes Ontology(OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-zfa.owl>) VersionIRI(<http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-zfa/2020-09-16/uberon/bridge/uberon-bridge-to-zfa.owl>))) [Axioms: 10458 Logical Axioms: 2070]
remark: Includes Ontology(OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/zfa.owl>) VersionIRI(<http://purl.obolibrary.org/obo/zfa/releases/2014-09-12/zfa.owl>))) [Axioms: 22468 Logical Axioms: 11339]
```

It looks like the PURL is hardwired to an old version:

https://github.com/obophenotype/uberon/releases/download/v2021-10-01/composite-metazoan.obo

And in fact, on the releases page:

https://github.com/obophenotype/uberon/releases

We can get https://github.com/obophenotype/uberon/releases/download/v2023-01-09/composite-metazoan.obo

which seems to be up to date, e.g

```
remark: Includes Ontology(OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/uberon/bridge/cl-bridge-to-zfa.owl>) VersionIRI(<http://purl.obolibrary.org/obo/uberon/bridge/cl-bridge-to-zfa/2022-12-13/uberon/bridge/cl-bridge-to-zfa.owl>))) [Axioms: 138 Logical Axioms: 5]
remark: Includes Ontology(OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-zfa.owl>) VersionIRI(<http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-zfa/2022-12-13/uberon/bridge/uberon-bridge-to-zfa.owl>))) [Axioms: 10454 Logical Axioms: 2067]
remark: Includes Ontology(OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/zfa.owl>) VersionIRI(<http://purl.obolibrary.org/obo/zfa/releases/2022-12-09/zfa.owl>))) [Axioms: 37225 Logical Axioms: 12250]
property_value: seeAlso https://sourceforge.net/p/obo/zebrafish-anatomy-zfa-term-requests/87 xsd:anyURI
```

A secondary issue is that the new site http://obophenotype.github.io/uberon/combined_multispecies/ has a table but no actual links

I think a few things would help:

- have the PURL redirect to https://github.com/obophenotype/uberon/releases/latest/download/composite-metazoan.obo
- include the versionIRI in the release products (which becomes data-version in the .obo used by bgee)
- remove stale pages from the old docs
- touch up the current docs a bit. And maybe it's OK to ditch the original system I had to pull everything from metadata and instead just point people to the assets page?

**Comment by anitacaron** [comment]
Currently, you can have access to the latest composite-metazoan release at http://purl.obolibrary.org/obo/uberon/subsets/composite-metazoan.obo

For especif version at http://purl.obolibrary.org/obo/uberon/releases/2023-01-09/composite-metazoan.obo

Just so you know, you need to copy the link and paste it into the address bar to download it.

**Comment by cmungall** [comment]
ah, I see, to summarize:

- http://purl.obolibrary.org/obo/uberon/composite-metazoan.obo is a bad URL that resolves to something that is no longer updated
- http://purl.obolibrary.org/obo/uberon/subsets/composite-metazoan.obo is the correct URL

I suggest yanking the bad URL as well as getting rid of the stale web page that points to it

> Just so you know, you need to copy the link and paste it into the address bar to download it.

I just use curl :-)

**Comment by anitacaron** [comment]
I suggested the change on the redirect `http://purl.obolibrary.org/obo/uberon/composite-metazoan.obo` to `http://purl.obolibrary.org/obo/uberon/releases/2021-10-01/composite-metazoan.obo`

**Comment by anitacaron** [comment]
In the PR https://github.com/OBOFoundry/purl.obolibrary.org/pull/944 we fixed the URL `http://purl.obolibrary.org/obo/uberon/composite-metazoan.obo` to redirect to the latest `composite-metazoan.obo` version
