### ISSUE TITLE
lacrimal

### ISSUE THREAD

**Issue by meghalithic** [obophenotype/uberon#2804]
**Uberon term**
[lacrimal](http://purl.obolibrary.org/obo/UBERON_3010146): UBERON:3010146 and [lacrimal bone](http://purl.obolibrary.org/obo/UBERON_0001680) UBERON:0001680 

**Bug description**

Both terms exist in Uberon but do not seem that different. Should one be used over the other?

**Comment by megbalk** [comment]
@wdahdul and I are unsure which term we should use.

**Comment by seger** [comment]
@megbalk I don't have any particular insights to offer. The work done on the old amphibian ontology (where the former term came from) was long ago. I'd probably vote to keep the latter term (UBERON:0001680) if I had to choose.

**Comment by megbalk** [comment]
@anitacaron is it useful to have a tag "preferred term" you think?

**Comment by anitacaron** [comment]
It would be better to obsolete the term UBERON:3010146 and add the replaced_by annotation to UBERON:0001680. @aleixpuigb, can you comment here, please?

**Comment by aleixpuigb** [comment]
I agree [lacrimal](http://purl.obolibrary.org/obo/UBERON_3010146): UBERON:3010146 should be merged into [lacrimal bone](http://purl.obolibrary.org/obo/UBERON_0001680) UBERON:0001680.
