### ISSUE TITLE
squamous part of temporal bone

### ISSUE THREAD

**Issue by megbalk** [obophenotype/uberon#2807]
**Uberon term**
[squamosal part of temporal bone](http://purl.obolibrary.org/obo/UBERON_0001695) UBERON:0001695

**Synonym to be added**
squama temporalis should be an exact synonym rather than related

**broad/exact/narrow/related ?**
exact

**Comment by megbalk** [comment]
or rather, squama temporalis is listed as both an exact and related synonym. As it is an exact synonym, the related synonym should be removed.

**Comment by nicolevasilevsky** [comment]
@megbalk I approved and merged the PR, can this be closed?
