### ISSUE TITLE
Question: why does 'anatomical structure' existence end during or before death stage?

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/uberon#2809]
Whilst reviewing some anatomical structures in Uberon, I noticed a subClass Of (Anonymous Ancestor) that is originating from ['anatomical structure'](http://purl.obolibrary.org/obo/UBERON_0000061).

The subClass Of axiom is:
[existence ends during or before](https://www.ebi.ac.uk/ols/ontologies/hcao/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002497) some [death stage](https://www.ebi.ac.uk/ols/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000071)

The text definition of ['existence ends during or before'](https://www.ebi.ac.uk/ols/ontologies/hcao/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002497) is:
"x existence ends during or before y if and only if the time point at which x ends is before or equivalent to the time point at which y ends."

Given that all anatomical structures do not cease to exist before or during the "end of the life of an organism", this intuitively does not seem correct. Indeed, one would expect classes under 'anatomical structure' are used to annotate post-mortem samples.

Is this subClass Of axiom appropriately attributed to 'anatomical structure'? If so, can a rationale be provided?

**Comment by balhoff** [comment]
I think this question is similar to the issue of a severed finger. The ontology says that every finger is part of a hand. Clearly this isn't true for a severed finger, so a severed finger can't be an instance of UBERON finger, i.e. UBERON fingers only describe "canonical" normally attached fingers. To use UBERON to describe a severed finger, you would need to use some relation like 'derived from' some UBERON finger. But if I was describing post-mortem samples I'd probably just ignore that and use the UBERON terms.

**Comment by bvarner-ebi** [comment]
Thanks for the feedback, @balhoff.

Still unsure why [existence ends during or before](https://www.ebi.ac.uk/ols/ontologies/hcao/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002497) some [death stage](https://www.ebi.ac.uk/ols/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000071) was made a super class of 'anatomical entity'. What purpose does it serve?

**Comment by balhoff** [comment]
> Thanks for the feedback, @balhoff.
> 
> Still unsure why [existence ends during or before](https://www.ebi.ac.uk/ols/ontologies/hcao/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002497) some [death stage](https://www.ebi.ac.uk/ols/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000071) was made a super class of 'anatomical entity'. What purpose does it serve?

Yes, still a good question, hopefully @cmungall can comment.

**Comment by ddooley** [comment]
Will dropping that then enable reference to UBERON in modelling both living organisms, and modelling of dead organisms, which may be on ice, or in some form of decay?  Living organisms can have decaying parts too.

**Comment by cmungall** [comment]
> Still unsure why [existence ends during or before](https://www.ebi.ac.uk/ols/ontologies/hcao/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002497) some [death stage](https://www.ebi.ac.uk/ols/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000071) was made a super class of 'anatomical entity'. What purpose does it serve?

partly completeness, partly QC

**Comment by ddooley** [comment]
@cmungall not quite following - it seems like a conceptual distinction not to enable use of UBERON terms in case of dead organisms?  Model only living organisms to avoid anatomical transformations that might occur after death?

**Comment by cmungall** [comment]
That is indeed the intent - many of the axioms in uberon would likely be untrue for dead organisms. I dislike the phrase "canonical anatomy" but all anatomy ontologies in OBO have built in assumptions of being a canonical, non-variant, living organisms, whether they make it explicit like uberon or not. The same holds for things like processes in GO.

We should add more to the docs on best practice for non-canonical anatomy, including pathological structures, variants, surgically removed parts, parts on a butchers' table, etc. But the basic idea is to link via some existential like transformation-of, variant-of, etc

**Comment by bvarner-ebi** [comment]
Thank you for confirming the assertion is intentional.

**Comment by ddooley** [comment]
There is a contradiction then with [carcass](http://purl.obolibrary.org/obo/UBERON_0008979), which is currently under anatomical structure? We need to move that up to "material anatomical entity"?

def: A body of a multi-cellular organism that is no longer living.
