### ISSUE TITLE
[NTR] Visceral muscle tissue

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/uberon#2813]
**Preferred term label:**
visceral muscle tissue

**Synonyms**

**Definition (free text, please give PubMed ID)**
A muscle tissue that is associated with internal organs (viscera), except the heart.
BTO:0002780
PMID:12132390

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
UBERON:0002385 muscle tissue

**Your nano-attribution (ORCID)**
http://orcid.org/0000-0001-6677-8489

**Comment**
It is quite common to refer to visceral muscles as smooth muscles, by analogy with vertebrates; however most visceral muscles in arthropods are actually striated
BTO:0002780
PMID:24594685
PMID:19463947

**Context**
[Visceral muscle cell lacks logical definition](https://github.com/obophenotype/cell-ontology/issues/1793)

**Comment by aleixpuigb** [comment]
Please, could you give me your opinion on this term @bvarner-ebi.

`Visceral muscle tissue` has been used as a broad synonym of `smooth muscle tissue`. However, not all `smooth muscle tissue` is associated with viscera (e.g. blood vessel smooth muscle in limbs). Therefore I don't think it should be used as a synonym.

Another question is if there should be child terms. Taking the CL ontology as a reference, `visceral muscle cell `has three child terms:
<img width="354" alt="Screenshot 2023-02-15 at 11 05 04" src="https://user-images.githubusercontent.com/94959119/219010549-2e54b049-b7c5-4b47-beb6-93fbc3e65dd1.png">

In my opinion, `smooth muscle cell` should not be a child term because not all `smooth muscle cells` are `visceral muscle cells`. In UBERON, `visceral striated muscle tissue` does not exist, and `transversely visceral striated muscle cell` should be a child term of `visceral striated muscle cell`. So I propose the following:
- [ ] Create `visceral muscle tissue` and remove it as a narrow synonym of `smooth muscle tissue`
- [ ] Create two child terms: `visceral striated muscle tissue` and `visceral smooth muscle tissue`
- [ ] Repair CL ontology by creating `visceral smooth muscle cell`, and smooth muscle cell would be a subclassOf muscle cell.

**Comment by bvarner-ebi** [comment]
> In my opinion, smooth muscle cell should not be a child term because not all smooth muscle cells are visceral muscle cells

This seems to be aligned with the BTO term ['visceral muscle'](http://purl.obolibrary.org/obo/BTO_0002780), which has 'smooth muscle' as a parent class as opposed to a child class.

> In UBERON, visceral striated muscle tissue does not exist

'visceral striated muscle' may be the same as skeletal muscle apart from location, so it would be prudent to support any new terms and modelling with references.

> Create two child terms: visceral striated muscle tissue and visceral smooth muscle tissue

Sure, if you find references that support adding these terms.

**Comment by aleixpuigb** [comment]
New terms:

Name: visceral smooth muscle tissue
Definition: Smooth muscle tissue associated to internal organs (viscera). xdbref: PMID:33729000, PMID:12132390
Subclass of: smooth muscle tissue, visceral muscle tissue

Name: visceral striated muscle tissue
Definition: Striated muscle tissue associated to internal organs (viscera), except the heart. xdbref: [Histology: an identification manual](https://pressbooks.pub/rbtallitsch/chapter/chapter-6-muscle-tissue/)
Subclass of: striated muscle tissue, visceral muscle tissue
