### ISSUE TITLE
Review classification under "anatomical cluster"

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#2819]
It has already been noted elsewhere (https://github.com/obophenotype/cell-ontology/issues/1782) that several terms currently classified under _anatomical cluster_ do not belong there. Time to review and fix those.

One of those terms at least is a cause of unsats as a result of that bogus classification: _hard palate_ (UBERON:0003216).

**Comment by cmungall** [comment]
I think these kinds of very abstract grouping classes should be modeled as properties or characteristics of some kind. See:

https://github.com/BFO-ontology/BFO/issues/221

but happy to align with fbbt as an intermediate step

**Comment by gouttegd** [comment]
In Uberon _disconnected anatomical group_ is a subclass of `'has quality' some disconnected` (PATO:0010001), and _anatomical structure_ is a subclass of `'has quality' some 'maximally connected'` (PATO:0010000).

So you would suggest to find (or create if they don’t already exist in PATO or elsewhere) more qualities to more finely distinguish the different types of entities? E.g., something like `'has quality' some 'closely grouped'` or similar for _anatomical cluster_, if we follow FBbt’s meaning of the term?

**Comment by cmungall** [comment]
The PATO term seems a bit vague here. I think if we feel that clustered in the FBbt concept is a useful concept for AOs then it's worth making a PATO subclass?

It looks like many of the existing 'clusters' are essentially mereological sums / "set" terms. I think it's worth having a DP for these but I don't think that is the intent of the CARO class

**Comment by gouttegd** [comment]
Just to be clear, _closely grouped_ does **not** exist in PATO, I just made it up for the example because it doesn’t look like there already is a quality in PATO that we could use to qualify “clusters”.

I’d be happy with a _clustered_ quality instead, with an agreed upon definition.

**Comment by gouttegd** [comment]
Here’s the rest of the problems with the _anatomical cluster_ hierarchy.

Barring any objection, I’ll submit a PR to fix the issues highlighted in the first two sections below (cross-references and subclasses that belong elsewhere). The other issues will require more time and more input.

## Obsolete cross-references

Uberon’s _anatomical cluster_ has a cross-reference to CARO’s [anatomical cluster](http://purl.obolibrary.org/obo/CARO_0000041), which is obsolete and replaced with [multi organ part structure](http://purl.obolibrary.org/obo/CARO_0020001), which has a different meaning than the one intended in Uberon for “anatomical cluster” (and which is already linked to Uberon’s own [multi organ part structure](http://purl.obolibrary.org/obo/UBERON_0034921).

Unless we happen to have a policy of keeping cross-references to obsolete foreign terms (e.g. for backwards compatibility?), the CARO cross-reference should be removed. And along with it, I would also suggest to remove all cross-references to what I would call “CARO term copies” – terms in other ontologies that mimic the obsolete CARO term, sometimes to the point that they use the same CURIE number (e.g. [BILA:0000041](http://purl.obolibrary.org/obo/BILA_0000041), [HAO:0000041](http://purl.obolibrary.org/obo/HAO_0000041), [FZA:0001478](http://purl.obolibrary.org/obo/ZFA_0001478)...).

Cross-reference to [FMA:49443](http://purl.obolibrary.org/obo/FMA_49443) should be removed as well, since the FMA term has a very different definition (which is closer to _multi organ part structure_ than to _anatomical cluster_).


## Subclasses that belong elsewhere

A handful of classes can confidently be re-classified somewhere else than under _anatomical cluster_:

* [accessory articulation](http://purl.obolibrary.org/obo/UBERON_3000809) -> move under [multi organ part structure](http://purl.obolibrary.org/obo/UBERON_0034921);
* [glottis](http://purl.obolibrary.org/obo/UBERON_0002486) -> move under [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061);
* [hard palate](http://purl.obolibrary.org/obo/UBERON_0003216) -> move under [multi organ part structure](http://purl.obolibrary.org/obo/UBERON_0034921);
* [soft palate](http://purl.obolibrary.org/obo/UBERON_0001733) -> move under [multi organ part structure](http://purl.obolibrary.org/obo/UBERON_0034921);
* [head capsule](http://purl.obolibrary.org/obo/UBERON_0003153) -> move under [insect region of integument]() (mimic the FBbt classification; the term should also be rename to make it clearer it is intended for insects);
* [insect analia](http://purl.obolibrary.org/obo/UBERON_6004823) -> move under [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) (mimic the FBbt classification);
* [juxtaglomerular apparatus](http://purl.obolibrary.org/obo/UBERON_0002303) -> move under [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061), as per the definition;
* [muscle spindle](http://purl.obolibrary.org/obo/UBERON_0003718) -> move under [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061);
* [lower urinary tract](http://purl.obolibrary.org/obo/UBERON_0001556) -> move under [organ system subdivision](http://purl.obolibrary.org/obo/UBERON_0011216);
* [upper urinary tract](http://purl.obolibrary.org/obo/UBERON_0011143) -> move under [organ system subdivision](http://purl.obolibrary.org/obo/UBERON_0011216);
* [ocular adnexa](http://purl.obolibrary.org/obo/UBERON_0035639) -> move under [multi organ part structure](http://purl.obolibrary.org/obo/UBERON_0034921);
* [osseus cochlea](http://purl.obolibrary.org/obo/UBERON_0007223) -> move under [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061);
* [palatoglossal arch](http://purl.obolibrary.org/obo/UBERON_0011640) -> move under [multi organ part structure](http://purl.obolibrary.org/obo/UBERON_0034921);
* [pharyngeal arch system](http://purl.obolibrary.org/obo/UBERON_0008814) -> move under [multi organ part structure](http://purl.obolibrary.org/obo/UBERON_0034921).


## Under-defined, possibly taxon-specific classes

A handful of classes seem to come straight from taxon-specific ontologies, have little or no definition (making it difficult to assess whether they belong under _anatomical cluster_ of not), and may have (if they are really taxon-specific) a name that is too generic:

* [intervening zone](http://purl.obolibrary.org/obo/UBERON_2001341);
* [medial column](http://purl.obolibrary.org/obo/UBERON_2000542);
* [midline column](http://purl.obolibrary.org/obo/UBERON_2000241);
* [opercular series](http://purl.obolibrary.org/obo/UBERON_2001875) — the name “series” does suggest it is a cluster of some sort (like other similarly named classes such as [infraorbital series](http://purl.obolibrary.org/obo/UBERON_2001709) or [epibranchial series](http://purl.obolibrary.org/obo/UBERON_2002102)), but without any definition it's hard to be sure;
* [pars inferior ear](http://purl.obolibrary.org/obo/UBERON_2005410);
* [pars superior ear](http://purl.obolibrary.org/obo/UBERON_2005409);
* [postzonal element](http://purl.obolibrary.org/obo/UBERON_3000938);
* [prezonal element](http://purl.obolibrary.org/obo/UBERON_3000938);
* [zonal area](http://purl.obolibrary.org/obo/UBERON_3000757);
* [ventricular musculature](http://purl.obolibrary.org/obo/UBERON_3010243);
* [visceromotor column](http://purl.obolibrary.org/obo/UBERON_2000611);


## Other various problematic classes

* [entire embryonic mesenchym](http://purl.obolibrary.org/obo/UBERON_0009142) — definitely not a “cluster” under any reasonable definition, but unsure where it should go;
* [exoskeleton](http://purl.obolibrary.org/obo/UBERON_0006611) — likewise;
* [hypophysial region](http://purl.obolibrary.org/obo/UBERON_4200248);
* [proliferative region](http://purl.obolibrary.org/obo/UBERON_2000098), coming from TAO, where it has as “exact synynoms” terms such as _cell cycle_, _proliferation_, _cell division_ (to which my reaction is “err, what the hell…?”); ZFA defines it as “cluster of rapidly dividing cells”, which sounds like something that could be made more generic and used elsewhere;
* [region of neural crest](http://purl.obolibrary.org/obo/UBERON_0010170) — the cross-referenced terms in ZFA, EMAPA, and TAO all represent the actual _neural crest_ and not a region of it, and the definition also sounds like the term is referring to the entire neural crest, so it’s unclear what the term is really about;
* [renal pelvis / ureter](http://purl.obolibrary.org/obo/UBERON_0036295) — a term intended to group the [renal pelvis](http://purl.obolibrary.org/obo/UBERON_0001224) and the [ureter](http://purl.obolibrary.org/obo/UBERON_0000056) — is such a grouping term really necessary? if so, it probably belongs under [organ system subdivision](http://purl.obolibrary.org/obo/UBERON_0011216);
* [shell](http://purl.obolibrary.org/obo/UBERON_0006612) — again, not a “cluster”, but unsure where it should belong;
* [subungual region](http://purl.obolibrary.org/obo/UBERON_0004105) — not a “cluster” and possibly redundant with [nail bed](http://purl.obolibrary.org/obo/UBERON_0005273);
* [vasculature](http://purl.obolibrary.org/obo/UBERON_0002049) — not a “cluster” and possibly redundant with [vascular system](http://purl.obolibrary.org/obo/UBERON_0007798);
* [dorsal fin pterygiophore](http://purl.obolibrary.org/obo/UBERON_2001419) — the definition makes it a “cluster” all right, but it seems that the name actually refer to the individual elements that make up the cluster (which seems confirmed by all the _dorsal fin pterygiophore X_ subclasses);
* [anal fin pterygiophore](http://purl.obolibrary.org/obo/UBERON_2001420) — likewise.
