### ISSUE TITLE
Add directly_supplies_drains 

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#2831]
Use case:  

Currently supplies is used for indirect relationships.  The definitions fits this:

> Relation between an arterial structure and another structure, where the arterial structure acts as a conduit channeling fluid, substance or energy.

HubMap VCCF is curating direct supplies/drains relationships between the capillary networks and the tissues they supply/drain

Parking this ticket here for discussion. Consider moving to RO if agreement reached.

@anitacaron @emquardokus @GriffinWeber

**Comment by aleixpuigb** [comment]
> Parking this ticket here for discussion. Consider moving to RO if agreement reached.

If I'm not wrong, I think there was an agreement to add this object property. Should I move it to RO?
