### ISSUE TITLE
Eye relationships

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/uberon#2852]
**Uberon term**
The following structures  in Uberon are missing relationships:

s | slabel | user_slabel | o | olabel | user_olabel 
-- | -- | -- | -- | -- | --
UBERON:0003902 | retinal neural layer | retinal neural layer | UBERON:0000941 | cranial nerve II  | cranial nerve II 
UBERON:0035966 | scleral lamina cribrosa | scleral lamina cribrosa | UBERON:0000941 | cranial nerve II | cranial nerve II

See [#66](https://github.com/obophenotype/asct-b_validation/issues/66)

**Suggested revision and reasons**
1. retinal neural layer is `'connected' to some 'cranial nerve II'` (aka optic nerve)
The optic nerve is formed as axons of the retinal ganglion cells (in the retinal neural layer) exit the retina through the optic disc.

2. scleral lamina cribrosa `'overlaps with' some 'cranial nerve II'`

<img width="400" alt="image" src="https://user-images.githubusercontent.com/94959119/227892976-12c1e1fd-0ba4-4acd-91e0-39ed550656d8.png">

> The lamina cribrosa (LC) is a mesh-like structure at the optic nerve head that surrounds and supports the retinal ganglion cell axons as they form the optic nerve. doi:https://doi.org/10.1167/iovs.14-15540

@bvarner-ebi, do you agree with these two relationships?

**Comment by aleixpuigb** [comment]
Thank you for your comment @bvarner-ebi!
>consider if 'retinal neural layer' and 'cranial nerve II' are discrete structures.
Yes

>if the above is true, be able to identify some other structure that connects them

Axons of the retinal ganglion cells connect both structures (become the optic nerve, to be more precise).

>If you can identify z, then the statement seems reasonable, but I'm unsure if z exists in this relationship. Related to the previous relationship, it may be helpful to define where 'cranial nerve II' begins with respect to the rest of the eye.

Can it be eye the z? Literature is a bit vague where the optic disc starts, but some [sources](https://www.ncbi.nlm.nih.gov/books/NBK507907/) suggest that in the optic disc.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/94959119/227942820-8be89798-5d88-4813-810d-facfbd758038.png">

**Comment by bvarner-ebi** [comment]
> Axons of the retinal ganglion cells connect both structures (become the optic nerve, to be more precise).

Uberon asserts:
- the ['nerve fiber layer of retina'](http://purl.obolibrary.org/obo/UBERON_0001793) is part of the 'retinal neural layer'
- the 'nerve fiber layer of retina' is composed primarily of axons (presumably the axons to which you are referring above)
- the 'nerve fiber layer of retina' overlaps with 'cranial nerve II'

With respect to the definition of 'connected to', I am not sure if the _c_ (in your example, a collection of axons) can also be part of or overlap _a_ and/or _b_. It may be worth discussing at the next RO meeting (tomorrow).

> Can it be eye the z?

I do not think it is accurate to say 'scleral lamina cribrosa' has part 'eye' or that 'eye' is part of 'cranial nerve II'.

**Comment by aleixpuigb** [comment]
The edits of this issue are not needed.
