### ISSUE TITLE
Wikipedia link is incorrect in "midgut loop" 

### ISSUE THREAD

**Issue by lubianat** [obophenotype/uberon#2857]
**Uberon term**

https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0011698 
**Bug description**

Wikipedia xref points to the page about Wikipedia:

[database cross reference](https://www.ebi.ac.uk/ols/search?q=database_cross_reference&exact=true&type=property&ontology=uberon)
[EMAPA:17036](http://www.informatics.jax.org/vocab/gxd/anatomy/EMAPA:17036)
NCIT:C34211
UMLS:C1513298 (ncithesaurus:Midgut_Loop)
[null:http://en.wikipedia.org/wiki/Wikipedia](http://en.wikipedia.org/wiki/Wikipedia)
VHOG:0000673
[null:http://linkedlifedata.com/resource/umls/id/C1513298](http://linkedlifedata.com/resource/umls/id/C1513298)

**Comment by aleixpuigb** [comment]
Thank you, @lubianat! 
It seems likely that the intended wikipedia link was the following: https://en.wikipedia.org/wiki/Midgut.
