### ISSUE TITLE
'neurectoderm' should not refer to 'primary neuron'

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#2869]
CL is planning to obsolete [primary neuron](http://purl.obolibrary.org/obo/CL_0000530), given the absence of a consensual meaning for such a term across species (obophenotype/cell-ontology#1931).

Uberon is using that term in its definition of [neurectoderm](http://purl.obolibrary.org/obo/UBERON_0002346), which should be amended accordingly.

**Comment by cmungall** [comment]
I don't think uberon uses this in its textual or logical definition. Only here

```yaml
relationship: has_part CL:0000530 {source="ZFA"} ! primary neuron
```

this axiom doesn't buy us much so ok for it to go

**Comment by gouttegd** [comment]
Yes, that was the axiom I was referring to. Sorry, I was a bit laxist in my usage of “definition”.
