### ISSUE TITLE
How to post-coordinate Uberon Ids?

### ISSUE THREAD

**Issue by ssyeds3** [obophenotype/uberon#2871]
What is the delimiter that is used to post-coordinate Uberon Ids? For example, we would like to concatenate the following two Uberon Ids:

Head - UBERON:0000033
Neck - UBERON:0000974

Thank you,
-Sofia

**Comment by balhoff** [comment]
@ssyeds3 I think this depends on what software you're using and how it references Uberon IDs. If you're using OWL, there are various kinds of expressions you could write using two class IDs, such as the union of these two concepts, etc. What semantics are you trying to represent?

**Comment by ssyeds3** [comment]
Thank you so much for your quick reply Jim. We’re standardizing data elements for aggregating several different data collections, therefore the aspect of what software or tool was used is not going to be applicable here so instead we would like to put our focus on the output. 

We’re trying to find an appropriate way to represent an existing specimen anatomic site valid value from one of the collections that is currently stated as “head and neck”. We have heard that Uberon codes can be concatenated to form a post-coordinated representation and that it would be an acceptable use of the Uberon ontology.

**Comment by balhoff** [comment]
By "software" I really meant the file format or data representation model you are using. There isn't any particular syntax provided by Uberon by combining terms; it would depend on your data model what a list of terms combined with some syntax is meant to represent. Uberon itself is developed in OWL, and if you're using OWL there are well defined ways to combine terms, e.g., using Manchester syntax such as `'part of' some ('head' or 'neck')`. In some other data model you could use any syntax you prefer to map to some particular OWL semantics. Sorry that is kind of an open-ended answer!

By the way for "head and neck" I would use the term [craniocervical region](http://purl.obolibrary.org/obo/UBERON_0007811).

**Comment by cmungall** [comment]
@ssyeds3 - what software are you using to find the terms you need in uberon? It looks like it isn't searching on synonyms

**Comment by ssyeds3** [comment]
> By "software" I really meant the file format or data representation model you are using. There isn't any particular syntax provided by Uberon by combining terms; it would depend on your data model what a list of terms combined with some syntax is meant to represent. Uberon itself is developed in OWL, and if you're using OWL there are well defined ways to combine terms, e.g., using Manchester syntax such as `'part of' some ('head' or 'neck')`. In some other data model you could use any syntax you prefer to map to some particular OWL semantics. Sorry that is kind of an open-ended answer!
> 
> By the way for "head and neck" I would use the term [craniocervical region](http://purl.obolibrary.org/obo/UBERON_0007811).

Thank you for the thorough explanation. This was very helpful!

**Comment by ssyeds3** [comment]
> @ssyeds3 - what software are you using to find the terms you need in uberon? It looks like it isn't searching on synonyms

We are using https://www.ebi.ac.uk/ols/ontologies for our mappings. What software/tool do you recommend that searches on synonyms?

**Comment by balhoff** [comment]
@ssyeds3 I opened an issue at OLS, since it doesn't seem to be searching all types of synonyms: https://github.com/EBISPOT/ols4/issues/358

I usually open Uberon in Protégé, but that is not exactly an end-user tool. The Ontobee search seems to work for this: https://ontobee.org/search?ontology=UBERON&keywords=head+and+neck&submit=Search+terms and it also seems to work in [Bioportal](https://bioportal.bioontology.org/ontologies/UBERON).

**Comment by ssyeds3** [comment]
> @ssyeds3 I opened an issue at OLS, since it doesn't seem to be searching all types of synonyms: [EBISPOT/ols4#358](https://github.com/EBISPOT/ols4/issues/358)
> 
> I usually open Uberon in Protégé, but that is not exactly an end-user tool. The Ontobee search seems to work for this: https://ontobee.org/search?ontology=UBERON&keywords=head+and+neck&submit=Search+terms and it also seems to work in [Bioportal](https://bioportal.bioontology.org/ontologies/UBERON).

Thank you very much. This is very helpful. We will go back and re-evaluate our remaining terms.

**Comment by anitacaron** [comment]
I am closing this issue because I believe all questions have been answered. Please reopen if needed.
