### ISSUE TITLE
temporal line

### ISSUE THREAD

**Issue by helenamachado** [obophenotype/uberon#2880]
**Preferred term label:**
temporal line

**Synonyms**

**Definition (free text, please give PubMed ID)**
line (or either of two nearly parallel lines) dorsally concave laterally directed that runs upward and backward from the zygomatic arch. It bounds the anterodorsal part of the temporal fossa and its the attachment site to the temporalis muscle.

ref.: https://www.merriam-webster.com/medical/temporal%20line
https://www.imaios.com/en/e-anatomy/anatomical-structure/temporal-line-1536895640
https://en.wikipedia.org/wiki/Parietal_bone

EQ: anatomical line and part of some frontal bone and part of some parietal bone

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-8415-4848

**Comment by megbalk** [comment]
@helenamachado see if my changes make sense.

Also, did you want to make edits to cranial temporal crest as well?

**Comment by helenamachado** [comment]
looks great!

and yes, I think the new definition is more appropriate in distinguishing the temporal crest from the temporal line https://github.com/futres/fovt/issues/118#issuecomment-1515403754

**Comment by megbalk** [comment]
Great, do you want to take a pass at it on this issue and push the commits?
