### ISSUE TITLE
Term for liver right lateral lobe requested

### ISSUE THREAD

**Issue by jrsjrs** [obophenotype/uberon#2885]
**Preferred term label:**
liver right lateral lobe

**Synonyms**
liver right posterior lobe

**Definition (free text, please give PubMed ID)**
The lateral or posterior sector of the right lobe of the liver.  The right lobe is divided into medial and lateral sectors by an oblique line that passes anteroposteriorly from the midpoint of the right lobe to the vena caval groove. (from https://www.kenhub.com/en/library/anatomy/functional-division-of-the-liver)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
right lobe of liver (UBERON:0001114)

**Your nano-attribution (ORCID)**
ORCID:0000-0002-6443-9376

**Comment by aleixpuigb** [comment]
Thank you for your term @jrsjrs. Kindly consider the following couple of questions and suggestions that I have regarding this term.

- Doing a cursory review, I've noticed that the majority of published work uses the posterior annotation, while lateral is more used for the left lobe. Is that correct, or `liver right lateral lobe` is more used and that was my perception?

- The second sentence of the definition describes the right lobe of liver. I propose the following definition: "The lateral (posterior) sector of the right lobe of the liver." Would that be sufficient?

- I would also like to include [this reference]( https://doi.org/10.1002/ca.22350) for the textual definition and this reference for the synonym: PMID: [30992874](https://pubmed.ncbi.nlm.nih.gov/30992874).

- The medial (anterior) sector is not in Uberon, would you mind that it is also created in this ticket?

**Comment by jrsjrs** [comment]
*   Doing a cursory review, I've noticed that the majority of published work uses the posterior annotation, while lateral is more used for the left lobe. Is that correct, or liver right lateral lobe is more used and that was my perception?
     *   I am working on a curation project for the Somatic Cell Genome Editing Consortium and have requested this term to be used for a data submission that came to us as part of that project.  I can't comment on whether the more generally used term is "posterior…" or "lateral…"  I can only say that the data submitted to us used the terms left lateral lobe and right lateral lobe.   If you decide the term should be "liver right posterior lobe", that should be fine for our purposes as long as "liver right lateral lobe" is included as a synonym (preferably an exact synonym).
  *   The second sentence of the definition describes the right lobe of liver. I propose the following definition: "The lateral (posterior) sector of the right lobe of the liver." Would that be sufficient?
     *   Yes, that is fine.
  *   I would also like to include this reference<https://urldefense.com/v3/__https:/doi.org/10.1002/ca.22350__;!!H8mHWRdzp34!4M5Y9-az8ac-1IM_f2SeRIawVxPgpESuZiH5a6qUzwHH9UqgVF8SYTNFDojG67rwE_vN0nF93m-R1qu07bPfKLD4$> for the textual definition and this reference for the synonym: PMID: 30992874<https://urldefense.com/v3/__https:/pubmed.ncbi.nlm.nih.gov/30992874__;!!H8mHWRdzp34!4M5Y9-az8ac-1IM_f2SeRIawVxPgpESuZiH5a6qUzwHH9UqgVF8SYTNFDojG67rwE_vN0nF93m-R1qu07V-PFkmd$>.
     *   This looks good.
  *   The medial (anterior) sector is not in Uberon, would you mind that it is also created in this ticket?
     *   Agreed—that makes sense.
Thank you!

Jennifer

Jennifer R. Smith
Project Manager
Rat Genome Database
Medical College of Wisconsin
8701 Watertown Plank Rd.
Milwaukee, WI 53226
Ph:  414-955-8871
***@***.******@***.***>
https://rgd.mcw.edu

**Comment by jrsjrs** [comment]
Thank you, Aleix!

Jennifer


Jennifer R. Smith
Project Manager
Rat Genome Database
Medical College of Wisconsin
8701 Watertown Plank Rd.
Milwaukee, WI 53226
Ph:  414-955-8871
***@***.******@***.***>
https://rgd.mcw.edu

**Comment by aleixpuigb** [comment]
The terms `posterior sector of right lobe of liver` and `anterior sector of right lobe of liver` have been created. Please find the review process in the [pull request](https://github.com/obophenotype/uberon/pull/2894). 

`liver right lateral lobe` is a related synonym of `posterior sector of right lobe of liver`, while `lateral sector of right lobe of liver` is an exact synonym.
