### ISSUE TITLE
Disconnect "neuron projection bundle" from CARO "anatomical entity"

### ISSUE THREAD

**Issue by ddooley** [obophenotype/uberon#2907]
**Uberon term**
UBERON_0000122

**Suggested revision and reasons**
Disconnect it from http://purl.obolibrary.org/obo/CARO_0000000 anatomical entity

Through its existing "[multi cell part structure](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0005162?lang=en)" parent, it is already situated under UBERON anatomical structure.

As an aside, on the road to phasing out CARO, it seems there are a number of other UBERON items under CARO anatomical entity that don't need to be connected to that too?

**Comment by anitacaron** [comment]
All CARO terms were removed in Uberon, so the CARO parent in [neuron projection bundle](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000122)

<img width="471" alt="Screenshot 2023-11-27 at 10 02 45" src="https://github.com/obophenotype/uberon/assets/2208124/03561d0e-f405-4ba4-b8f2-e081af821c51">
