### ISSUE TITLE
Revise subclass relationship: vasa recta 

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#2914]
**Uberon term**
vasa recta	UBERON:0004726

**Suggested revision and reasons**
Currently uberon has vasa recta as part of renal vein; however, this is a place in the kidney blood vasculature where venous and arterial blood supplies come together.  The definition in uberon also condradicts being placed as a subclass of renal vein.

Discussed this with kidney expert Sanjay Jain (WUSTL) in detail and investigated kidney vasculature as a whole; a reorganization of kidney vasculature is needed.

Vasa Recta has ascending vasa recta and descending vasa recta
Sanjay Jain stated that in uberon vasa recta should be made part of kidney vasculature, it should not be part of renal vein because of the dual venous and arterial portions of the vasa recta. 
Ascending vasa recta (AVR): branching from kidney arcuate vein
Descending vasa recta (DVR): branching from efferent arteriole

From: Apelt, Katerina, Roel Bijkerk, Franck Lebrin, and Ton J. Rabelink. 2021. "Imaging the Renal Microcirculation in Cell Therapy" Cells 10, no. 5: 1087. https://doi.org/10.3390/cells10051087 
Figure 2. The renal microvascular network exhibits remarkable heterogeneity on morphological and functional level. The (a) glomerular capillaries have a fenestrated endothelium and are wrapped by podocytes. The highly muscularized (b) cortical afferent arteriole is surrounded by pericytes, in contrast to (c) cortical efferent arteriole which contains less smooth muscle cells and flows into the (d) peritubular capillaries that are highly surrounded by pericytes. The glomeruli situated close to the arcuate artery and vein are bigger in size, which is reflected by a larger vessel diameter of (e) juxtamedullary afferent arteriole and (f) juxtamedullary efferent arteriole. The vascular network of the medulla is supplied by efferent arterioles, which arise from the juxtamedullary glomeruli forming a dense capillary plexus and interbundle plexus in the inner stripe of the outer medulla. The (g) vascular bundle is wrapped by many pericytes and enter deeper into the inner medulla to form the vasa recta capillaries between the (h) descending vasa recta (DVR) and the fenestrated (i) ascending vasa recta (AVR).
<img width="1294" alt="Screenshot 2023-06-07 at 4 49 04 AM" src="https://github.com/obophenotype/uberon/assets/47257000/4a738510-9e07-4647-abbe-6176a79b1b21">

the word "limb" should be removed from both entries---limb refers to Loop of Henle structure not to the vasa recta which runs parallel to the Loop of Henle--terminology between them seems to have become confused in uberon.

**Propose name change of the following: 

inner medulla vasa recta ascending limb to inner medulla ascending vasa recta 
inner medulla vasa recta descending limb  to inner medulla descending vasa recta 
outer medulla vasa recta ascending limb to outer medulla ascending vasa recta 
outer medulla vasa recta descending limb to outer medulla descending vasa recta 

**Plus names of cell types associated with both: **
inner medulla vasa recta ascending limb cell to inner medulla ascending vasa recta cell
inner medulla vasa recta descending limb cell to inner medulla descending vasa recta cell
outer medulla vasa recta ascending limb cell to outer medulla ascending vasa recta cell
outer medulla vasa recta descending limb cell to outer medulla descending vasa recta cell

**Current uberon screenshots**
<img width="557" alt="Screenshot 2023-06-07 at 4 19 53 AM" src="https://github.com/obophenotype/uberon/assets/47257000/ce685c94-0d2a-4abb-8b8e-57fe2de214db">

<img width="487" alt="Screenshot 2023-06-07 at 4 27 14 AM" src="https://github.com/obophenotype/uberon/assets/47257000/11f1afce-e7bd-483c-b352-4b6cbec75caa">

**Current uberon screenshot:**
<img width="500" alt="Screenshot 2023-06-05 at 4 48 08 PM" src="https://github.com/obophenotype/uberon/assets/47257000/f405622f-a151-41e2-99cf-356bf7bd2234">

**The definition in uberon:** In the blood supply of the kidney, the vasa recta renis (or straight arteries of kidney, or straight arterioles of kidney) form a series of straight capillaries in the medulla. They lie parallel to the loop of Henle. These vessels branch off the efferent arterioles of juxtamedullary nephrons (those nephrons closest to the medulla), enter the medulla, and surround the loop of Henle.
**Consider revising definition**:  Wikipedia definition is more accurate: https://en.wikipedia.org/wiki/Vasa_recta_(kidney)
The vasa recta of the kidney, (vasa recta renis) are the straight arterioles, and the straight venules of the [kidney](https://en.wikipedia.org/wiki/Kidney), – a series of [blood vessels](https://en.wikipedia.org/wiki/Blood_vessel) in the [blood supply of the kidney](https://en.wikipedia.org/wiki/Renal_circulation) that enter the [medulla](https://en.wikipedia.org/wiki/Renal_medulla) as the straight arterioles, and leave the medulla to ascend to the cortex as the straight venules.

**Comment by aleixpuigb** [comment]
Hi @emquardokus. Thank you for this ticket. I agree that this class needs some work and I might add a couple of items. I will break down in a tasklist to make it more trackable:

- [ ] Change SubclassOf 'renal vein' to SubclassOf 'part of' some ['kidney vasculature'](http://purl.obolibrary.org/obo/UBERON_0006544) 
- [ ] Remove limb from class names. Should we maintain the actual class names as synonyms?
- [ ] Revision of the textual definition.

I would also add the following:
- [ ] Revision of synonyms. Some of the synonyms don't seem appropriate (e.g. arteria recta) or need to change synonym type (e.g. 'straight arterioles of kidney' from EXACT to NARROW):
![image](https://github.com/obophenotype/uberon/assets/94959119/693426a7-4f7b-4447-ad2b-754b0cdd53db)
- [ ] According to the figure legend provided, vasa recta might only be found in the inner medulla.
> The (g) vascular bundle is wrapped by many pericytes and enter deeper into the inner medulla to form the vasa recta capillaries between the (h) descending vasa recta (DVR) and the fenestrated (i) ascending vasa recta (AVR).

- [ ] There is also an[ intestinal vasa recta](https://en.wikipedia.org/wiki/Vasa_recta_(intestines)), it might be beneficial to change the label into `renal vasa recta`.

Do you think these sums up all the edits?
