### ISSUE TITLE
Broca's area

### ISSUE THREAD

**Issue by svempati21** [obophenotype/uberon#2917]
**Uberon term**
Brodmann (1909) area 44

**Suggested revision of textual definition**
Brodmann area 44 and Brodmann area 45 combined make up the area within the brain known as Broca's area.

**Comment by RDruzinsky** [comment]
I suggest the following:

Broca's area is a region of the inferior frontal gyrus (in the dominant
cerebral hemisphere, usually on the left side) that is composed of parts of
Brodmanns' areas 44 and 45.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky
