### ISSUE TITLE
NTR: placental villous stroma

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#2920]
**Preferred term label:**
placental villous stroma

**Synonyms**

**Definition (free text, please give PubMed ID)**
PMID: 31512233
Palaiologou E, Etter O, Goggin P, Chatelet DS, Johnston DA, Lofthouse EM, Doherty R, Pearson-Farr J, Sengers BG, Torrens C, Cleal JK, Page AM, Lewis RM. Human placental villi contain stromal macrovesicles associated with networks of stellate cells. J Anat. 2020 Jan;236(1):132-141. doi: 10.1111/joa.13082. Epub 2019 Sep 11. PMID: 31512233; PMCID: PMC6904625.

**Definition from paper:** The placental villous stroma is a connective tissue layer that supports the fetal capillaries and villous trophoblast.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
unclear if an appropriate parent exists currently

**Your nano-attribution (ORCID)**
0000-0001-7655-4833

**Comment by aleixpuigb** [comment]
Hi @emquardokus, thank you for this term.

I would suggest the following edits:

Definition
> A stroma that is part of a chorionic villus. A placental villous stroma supports the fetal capillaries and villus trophoblast.

Parent terms:
- stroma (UBERON:0003891) and
- 'part of' some ['chorionic villus'](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0007106) (UBERON:0007106) (synonym of placental villus).

**Comment by emquardokus** [comment]
@aleixpuigb Thank you for your suggestions; I have spent some time verifying this information in the literature. Please proceed.
