### ISSUE TITLE
'preorbital bone region' has no explicit parent

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2934]
Currently 'preorbital bone region' only has 'part of' some 'orbit of skull'
This gets placed under CARO anatomical entity when materialised 
This has issues in some of our scripts as we take Uberon anatomical entity as a root node 
Related to https://github.com/obophenotype/uberon/issues/2296
IMO minimal solution is to explicitly make this a subclass of uberons anatomical entity

**Comment by balhoff** [comment]
Domains and ranges in RO have been updated to Uberon instead of CARO: https://github.com/oborel/obo-relations/pull/722 

I think in the next release.

**Comment by shawntanzk** [comment]
given parent is now explicit ) albeit a bit general, will close this ticket. New ticket should be opened if there is any other work needed
