### ISSUE TITLE
Error every time I create an issue

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/uberon#2955]
Every time I create or edit an issue in Uberon, I receive a notification with the following message: "Create new pull request: All jobs have failed"
As I am not creating a PR yet, I don't understand why it is giving me this error.

An example can be found in: https://github.com/obophenotype/uberon/actions/runs/5475477058
![image](https://github.com/obophenotype/uberon/assets/94959119/5516cfbc-cf24-4f7f-af35-156c6474c178)

**Comment by balhoff** [comment]
@hrshdhgd can fix this—it's the automatic change request bot.

**Comment by hrshdhgd** [comment]
Done!

**Comment by aleixpuigb** [comment]
Thank you @hrshdhgd and @balhoff!
