### ISSUE TITLE
base-file orphans a few terms 

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2987]
Not sure why this is happening, but I assume it is unintended. 
It seems that terms that are under UBERON:0001062 ('anatomical entity') that are in the UBERON namespace gets the subClassOf UBERON:0001062 removed in base file orphaning them as top level terms. 
There are currently 3 terms that fall into that:
UBERON:8600016
UBERON:8600015
UBERON:0008874

**Comment by shawntanzk** [comment]
@matentzn @anitacaron or @gouttegd would you mind helping me take a look at this please? Thanks :)

**Comment by gouttegd** [comment]
From what I can see, it’s not a problem with the generation of the base file. Those terms are already orphaned at the source, in the `-edit` file.

**Comment by shawntanzk** [comment]
@gouttegd ah dang you are right - I guess some process in materialization or something gave them parents in the full file but not the base file for some odd reason. Sorry for not checking the edit file, dont tend to use that these days >.< Will make a PR to fix it in the edit file, thanks heaps :) 
PS I thought the base file came out as a product of the full file, and given the full file has subClassOf anatomical entity, how did this get dumped in base?

**Comment by gouttegd** [comment]
> I thought the base file came out as a product of the full file

No, the `-base` file comes straight from the `-edit` file (well, almost: it comes from the “preprocessed” `-edit` file):

```
# base: All the axioms as they are editted by the editors, excluding reasoning
$(ONT)-base.owl: $(EDIT_PREPROCESSED) $(OTHER_SRC)
        $(ROBOT_RELEASE_IMPORT_MODE_BASE) \
        $(SHARED_ROBOT_COMMANDS) \
        annotate --link-annotation http://purl.org/dc/elements/1.1/type http://purl.obolibrary.org/obo/IAO_8000001 \
                --ontology-iri $(ONTBASE)/$@ $(ANNOTATE_ONTOLOGY_VERSION) \
                --output $@.tmp.owl && mv $@.tmp.owl $@
```

So any relationship coming from the materialisation leading to `-full` will _not_ show up in `-base`.
