### ISSUE TITLE
NTR: bronchoalveolar lavage fluid

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#2995]
**Preferred term label:** bronchoalveolar lavage fluid

**Definition (free text, please give PubMed ID)** Cells and fluid from bronchioles and lung alveoli obtained after washing out of the lungs with saline or mucolytic agents.
BTO_0000155, MESH/D018893, NCI Thesaurus/ C51913

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
respiratory system fluid/secretion, UBERON_0006538

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-0819-0473

**Comment by bvarner-ebi** [comment]
@paulacalipho, this term may be outside the scope of Uberon as it is "obtained after washing out of the lungs". Could you use BTO:0000155 for your purposes? If not, are you able to use EFO terms, as it may be more suitable to add the term there?

FYI @zoependlington

**Comment by paulacalipho** [comment]
@bvarner-ebi Thanks for the feedback, I understand. We only use UBERON or CL to describe the origin of the cell lines. A solution would be to map to the general term respiratory system fluid/secretion, UBERON_0006538. You can close/remove this NTR if you wish.

**Comment by cmungall** [comment]
I suggest coordinating with the OBI group
