### ISSUE TITLE
chebi_import.owl missing from v2023-07-25 release?

### ISSUE THREAD

**Issue by tgbugs** [obophenotype/uberon#2997]
This might be an issue with the purl resolver (can't quite spot the issue in https://github.com/OBOFoundry/purl.obolibrary.org), but it reads like it is expecting chebi_import.owl to be included as part of the latest release?

```
DEBUG Missing exception ID: org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/uberon/chebi_import.owl> Cause: https://github.com/obophenotype/uberon/releases/download/v2023-07-25/chebi_import.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/uberon/chebi_import.owl> Cause: https://github.com/obophenotype/uberon/releases/download/v2023-07-25/chebi_import.owl
```

**Comment by gouttegd** [comment]
Which file of the v2023-07-25 release are you trying to read?

The `chebi_import.owl` module no longer exists per se, as for all the former individual import modules. They are all merged into a single `merged_import.owl` module. No product of Uberon should still have an import declaration for one of the former individual modules.
