### ISSUE TITLE
http://xmlns.com/foaf/0.1/depicted_by does not resolve, is it correct?

### ISSUE THREAD

**Issue by lubianat** [obophenotype/uberon#3008]
Hello! I was working in this CL PR: 

 - https://github.com/obophenotype/cell-ontology/pull/2092
 
 And realized that the  FOAF URI used by Uberon and CL for images does not have any content and does not resolve: http://xmlns.com/foaf/0.1/depicted_by 
  
 There seems to exist a foaf:depiction --> http://xmlns.com/foaf/0.1/#term_depiction, but no foaf:depicted_by 
 
Is that correct?

**Comment by anitacaron** [comment]
Just found out about an issue from 2017 about the same thing - https://github.com/obophenotype/uberon/issues/1364. I'll close this to keep the other one.
