### ISSUE TITLE
Revise MAKEOBO custom rule

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#3014]
The ODK standard method to create a `.obo` artifact from a `.owl` one is this:

```sh
robot convert -i myfile.owl --check false -f obo -o myfile.obo.tmp && grep -v ^owl-axioms: myfile.obo.tmp > myfile.obo && rm tmp.obo
```

In Uberon, we use this custom rule instead:

```Makefile
MAKEOBO=  $(OWLTOOLS) $< --add-obo-shorthand-to-properties  -o -f obo --no-check $@.tmp1 && grep -v ^property_value: $@.tmp1 | perl -npe 's@relationship: dc-@property_value: dc-@' | grep -v ^owl-axioms: > $@.tmp && mv $@.tmp  $@
```

So in addition to removing the `owl-axioms:` tag, this rule:
* adds shorthands to object properties that don’t already have one (an “OBO shorthand” is basically what allows to use, e.g, `part_of` instead of `BFO:0000050` in a class expression);
* removes all `property_value` tags;
* replaces DC annotations incorrectly represented as relationships by proper annotations (e.g. `relationship: dc-creator ...` -> `property_value: dc-creator ...`.

I question whether this custom rule is useful and if so, whether it should be ported to the ODK instead. I am particularly unconvinced by the usefulness of the additions of OBO shorthands.

**Comment by matentzn** [comment]
I think we should standardise this towards the normal way ODK is done.

After the huge #3028, we could get rid of the custom OBO generation code IMO.

**Comment by matentzn** [comment]
Note that most ontologies in the wild, including HPO, RO, CL and others, this has not been happening, and no one complained.

**Comment by gouttegd** [comment]
Based on @matentzn ’s comments above and the fact that nobody bothered to weigh in to say that they need any of the things done by this custom rule, let’s go ahead and remove it.
