### ISSUE TITLE
Move the source of truth for HubMaps HRA subset to Uberon itself

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#3037]
We have this goal in uberon.Makefile:

```
HRA_SUBSET_URL="https://raw.githubusercontent.com/hubmapconsortium/ccf-validation-tools/master/owl/UB_ASCTB_subset.owl"
$(TMPDIR)/hra_subset.owl:
	wget $(HRA_SUBSET_URL) -O $@
```

This creates a significant dependency of Uberon to a file totally outside of our control.. Look at this example statement. Isnt it a bit risky that some outside consortium is allowed to add taxon constraints which could potentially break the Uberon build? Also, who can tell if this subset goes stale, or moves location (since its not even linked to a PURL.

```
    <!-- http://purl.obolibrary.org/obo/UBERON_0000209 -->

    <Class rdf:about="http://purl.obolibrary.org/obo/UBERON_0000209">
        <obo:RO_0002175 rdf:resource="http://purl.obolibrary.org/obo/NCBITaxon_9606"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/uberon/core#human_reference_atlas"/>
    </Class>
```

I vote for the source of truth of this subset to be moved to Uberon, and hubmap developers updating it here.

**Comment by matentzn** [comment]
Similar to https://github.com/obophenotype/uberon/pull/3028/commits/a719af2c18452c618e8973d4e60a2626dd3c4076

**Comment by anitacaron** [comment]
The subset is generated during a validation pipeline in the HuBMAP repository. It would be harder to keep the subset updated, but I can do it.

**Comment by matentzn** [comment]
Maybe before you do it, decide on a strategy with your hubmap colleagues on this.. And the rest of the Uberon team! Maybe I am overreacting here, and having an externally maintained dependency is ok.

**Comment by anitacaron** [comment]
The EBI team manages this subset, so it's Aleix and me only.

**Comment by anitacaron** [comment]
It's simple but needs to grab the terms from 30+ spreadsheet tables, etc. Everything is done in a GH Action every week now.

**Comment by matentzn** [comment]
Ok leave it as is then..  I don't want the uberon pipeline to be more complex than necessary now that it has been simplified so nicely! Lets close this issue and thanks for the explanations!

**Comment by anitacaron** [comment]
I want to add this in the odk config file, but it's not working correctly now. I need to check this later.

**Comment by anitacaron** [comment]
This is the plan. https://github.com/obophenotype/uberon/pull/2975
