### ISSUE TITLE
Revise definition of kidney as per kidney expert community request

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#3046]
**Uberon term**
kidney
UBERON:0002113
http://purl.obolibrary.org/obo/UBERON_0002113

**Suggested revision of textual definition**
Requested by Sanjay Jain MD, PhD (HuBMAP, KPMP) in response to being contacted by several researchers and colleagues about the current definition of kidney that appears on the HuBMAP website organ pages : https://portal.hubmapconsortium.org/organ/kidney that is directly coming from uberon “A paired organ of the urinary tract which has the production of urine as its primary function”.

Proposed revised definition approved by Sanjay Jain MD, PhD "A paired organ of the urinary tract that produces urine and maintains bodily fluid homeostasis, blood pressure, pH levels, red blood cell production and bone health."

**Add reference source from the National Kidney Foundation:** : 
https://www.kidney.org/kidneydisease/top-5-jobs-kidneys-do

**Comment by sbello** [comment]
Are all those functions applicable to all species with kidneys? Given that cartilaginous fishes have kidneys I'm concerned at least about the inclusion of 'bone health'. If the production of the active form is not species specific then maybe this could be rephrased?

**Comment by RDruzinsky** [comment]
Exactly what I was wondering.  I doubt that all of these functions are true
for all vertebrates.

**Comment by aleixpuigb** [comment]
> Proposed revision based on comments and literature: A paired organ of the urinary tract that produces urine and maintains bodily fluid homeostasis, blood pressure, pH levels, red blood cell production and skeleton mineralization.

@emquardokus could you run this definition with Sanjay Jain MD, PhD?
@RDruzinsky @sbello Are there any further concerns with the revised definitions?

**Comment by RDruzinsky** [comment]
Looks good to me. Thanks!

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor Emeritus
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
***@***.***

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by emquardokus** [comment]
@aleixpuigb 
Received approval from original requester Sanjay Jain: 

Begin forwarded message:

From: "Jain, Sanjay" <sanjayjain@wustl.edu>
Subject: RE: Fwd: Kidney definition update proposed Re: HuBMAP website
Date: February 7, 2024 at 11:36:44 AM EST
To: "Quardokus, Ellen M" <ellenmq@iu.edu>
Cc: "Borner, Katy" <katy@iu.edu>

the definition below is fine
Thanks
Sanjay
 
Sanjay Jain MD, PhD
Professor: Medicine (Nephrology), Pediatrics, Pathology and Immunology
Director, Kidney Translational Research Center (KTRC)
PI/MPI: HuBMAP (TMC, HIVE OT2), KPMP (TIS), ATLAS-D2K, PCEN-WU
Washington University School of Medicine, Box 8126
McDonnell Medical Sc Rm 880
660 S. Euclid Ave, St. Louis, MO 63110
Office:314-454-8728; Lab:314-454-8464; Fax:314-454-7735.
