### ISSUE TITLE
Inventory of current bridges between Uberon/CL and foreign resources

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#3047]
I will soon overhaul the way the bridges between Uberon/CL and foreign resources (mostly foreign ontologies but not only) are handled. Before I do that, here is an inventory of those bridges as they currently exist. Some of them may not be relevant anymore, so I’d like people to weigh in on whether they can be removed or not.

“Last updated” refers to the last time the bridge file had any changes committed to the repository (regardless of whether those changes were significant or not; for example, merely changing the version IRI without any edit to the bridging axioms still counts as an “update” and indicates the bridge file is actively maintained); when the last update is “ODK migration (2021)”, it means the history of the bridge cannot be traced back any further than PR #1798 because of the huge repository-wide changes in that PR – the real last update may be much older.

The “source of truth” indicates where the mappings that underlie the bridging axioms come from. A “?“ means that the source of truth is unknown: we have the bridge file, but we have no indication of how that file was generated in the first place.

The “bridge types” are:

* `equivalent`: the mapped foreign term is said to be equivalent to the Uberon/CL term (`FOREIGN:YYYY EquivalentTo: UBERON:XXXX`);
* `has-subclass`: the mapped foreign term is said to be a subclass of the Uberon/CL term (`FOREIGN:YYYY SubClassOf: UBERON:XXXX`);
* `is-a`: the Uberon/CL term is said to be a subclass of the mapped foreign term (`UBERON:XXXX SubClassOf: FOREIGN:YYYY`);
* `reverse genus differentia (NCBITaxon:ZZZZ)`: the mapped foreign term is said to be equivalent to the intersection of the Uberon/CL term and an existential restriction with the indicated taxon (`FOREIGN:YYYY EquivalentTo: UBERON:XXXX and (BFO:0000050 some NCBITaxon:ZZZZ)` in most cases, except when the Uberon term represents a life stage, in which case the property is BFO:0000066 instead of BFO:0000050);
* `complex`: custom-made bridge that does not obey simple rules like the previous ones.

# Uberon bridges

| Foreign end | OBO Foundry status | Last updated | Source of truth | Bridge type | Remarks |
| ----------- | ------------------ | ------------ | --------------- | ----------- | ------- |
| [Amphibian gross anatomy ontology](http://obofoundry.org/ontology/aao) (AAO) | deprecated | last release | AAO xrefs in Uberon | reverse genus differentia (NCBITaxon:8292) | OK |
| ? ABA       | unknown to the OBO Foundry | ODK migration (2021) | ? | reverse genus differentia (NCBITaxon:10090) | just of handful of bridging axioms |
| [Anatomical entity ontology](http://obofoundry.org/ontology/aeo) (AEO) | inactive | last release | AEO xrefs in Uberon | equivalent | OK |
| [Basic formal ontology](http://obofoundry.org/ontology/bfo) (BFO) | | ODK migration (2021) | ? | is-a | just a handful of bridging axioms, some of them redundant with what is already stated in Uberon |
| [Bilateria anatomy ontology](http://obofoundry.org/ontology/bila) (BILA) | deprecated | last release | BILA xrefs in Uberon | equivalent | OK |
| ? BSD | unknown to the OBO Foundry | ODK migration (2021) | ? | ? seemingly intended as a reverse genus differentia bridge for NCBITaxon:7712 | empty |
| [Biological spatial ontology](http://obofoundry.org/ontology/bspo) (BSPO) | | last release | BSPO xrefs in Uberon | equivalent | empty |
| [Common anatomy reference ontology](http://obofoundry.org/ontology/caro) (CARO) | | last release | CARO xrefs in Uberon | equivalent | OK |
| [Developing human brain atlas](https://www.brainspan.org/) (DHBA) | N/A | last release | DHBA xrefs in Uberon | reverse genus differentia (NCBITaxon:9606) | OK |
| [Developing mouse brain atlas](https://developingmouse.brain-map.org) (DMBA) | N/A | august 2022 | [ABA Uberon](https://github.com/obophenotype/ABA_Uberon) | complex | set up by Shawn |
| [Experimental factor ontology](https://www.ebi.ac.uk/efo/) (EFO) | N/A | last release | EFO xrefs in Uberon | equivalent | OK |
| [Human developmental anatomy, abstract version](http://obofoundry.org/ontology/ehdaa) (EHDAA) | deprecated | last release | EHDAA xrefs in Uberon | has-subclass | OK |
| [human developmental anatomy, abstract](http://obofoundry.org/ontology/ehdaa2.html) (EHDAA2) | | last release | EHDAA2 xrefs in Uberon | reverse genus differentia (NCBITaxon:9606) | OK |
| [Mouse gross anatomy and development, timed](http://obofoundry.org/ontology/emap) (EMAP) | deprecated | ODK migration (2021) | ? | complex | OK |
| [Mouse developmental anatomy ontology](http://obofoundry.org/ontology/emapa) (EMAPA) | | last release | EMAPA xrefs in Uberon | reverse genus differentia (NCBITaxon:10090) | OK |
| [eVOC (expressed sequence annotation for humans)](http://obofoundry.org/ontology/ev) (EV) | deprecated | last release | EV xrefs in Uberon | has-subclass | OK |
| [Drosophila anatomy ontology](http://obofoundry.org/ontology/fbbt) (FBbt) | | last release | FBbt’s SSSOM set | reverse genus differentia (NCBITaxon:7227) | OK |
| [Drosophila development ontology](http://obofoundry.org/ontology/fbdv) (FBdv) | | last release | FBdv xrefs in Uberon | reverse genus differentia (NCBITaxon:7227) | OK |
| [Foundational model of anatomy ontology](http://obofoundry.org/ontology/fma) (FMA) | inactive | last release | FMA xrefs in Uberon | reverse genus differentia (NCBITaxon:9606) | OK |
| [Gene ontology](http://obofoundry.org/ontology/go) (GO) | | last release | GO xrefs in Uberon | equivalent | only two bridging axioms |
| [Hymenoptera anatomy ontology](http://obofoundry.org/ontology/hao) (HAO) | | last release | HAO xrefs in Uberon | reverse genus differentia (NCBITaxon:7399) | OK |
| [Human brain atlas](https://human.brain-map.org/) (HBA) | N/A | last release | HBA xrefs in Uberon | reverse genus differentia (NCBITaxon:9606) | OK |
| [Human developmental stages](http://obofoundry.org/ontology/hsapdv) (HsapDv) | | last release | HsapDv xrefs in Uberon | reverse genus differentia (NCBITaxon:9606) | OK |
| [Mouse adult gross anatomy](http://obofoundry.org/ontology/ma) (MA) | | last release | MA xrefs in Uberon | reverse genus differentia (NCBITaxon:10090) | OK |
| [Mouse brain atlas](https://mouse.brain-map.org) (MBA) | N/A | january 2023 | [ABA Uberon](https://github.com/obophenotype/ABA_Uberon) | complex | set up by Shawn |
| [Medaka fish anatomy and development](http://obofoundry.org/ontology/mfo) (MFO) | deprecated | last release | MFO xrefs in Uberon | reverse genus differentia (NCBITaxon:8089) | empty |
| [Mouse developmental stages](http://obofoundry.org/ontology/mmusdv) (MmusDv) | | last release | MmusDv xrefs in Uberon | reverse genus differentia (NCBITaxon:10090) | OK |
| [NCI thesaurus OBO edition](http://obofoundry.org/ontology/ncit) (NCIT) | | last release | NCIT xrefs in Uberon | has-subclass | OK |
| [NIF standard ontology](https://github.com/SciCrunch/NIF-Ontology) (NIFSTD) | N/A | ODK migration (2021) | ? | equivalent | only 6 bridging axioms, at least 4 pointing to obsolete terms |
| ? OG | unknown to the OBO Foundry | last release | OG xrefs in Uberon | equivalent | empty |
| ? OGES | unknown to the OBO Foundry | last release | OGES xrefs in Uberon | has-subclass | OK |
| [Medaka developmental stages](http://obofoundry.org/ontology/olatdv) (OlatDv) | inactive | last release | OlatDv xrefs in Uberon | reverse genus differentia (NCBITaxon:8089) | only one bridging axiom |
| Primate brain atlas (PBA) | N/A | last release | PBA xrefs in Uberon | reverse genus differentia (NCBITaxon:9443) | OK |
| SNOMED CT (SCTID) | N/A | least release | SCTID xrefs in Uberon | has-subclass | OK |
| [Spider ontology](http://obofoundry.org/ontology/spd) (SPD) | | last release | SPD xrefs in Uberon | reverse genus differentia (NCBITaxon:6893) | OK |
| [Tick anatomy ontology](http://obofoundry.org/ontology/tads) (TADS) | inactive | last release | TADS xrefs in Uberon | reverse genus differentia (NCBITaxon:6939) | OK |
| [Teleost anatomy ontology](http://obofoundry.org/ontology/tao) (TAO) | deprecated | last release | TAO xrefs in Uberon | reverse genus differentia (NCBITaxon:32443) | OK |
| [Mosquito gross anatomy ontology](http://obofoundry.org/ontology/tgma) (TGMA) | inactive | last release | TGMA xrefs in Uberon | reverse genus differentia (NCBITaxon:44484) | OK |
| ? VAO | unknown to the OBO Foundry | ODK migration (2021) | ? | equivalent | OK |
| [Vertebrate homologous ontology group ontology](http://obofoundry.org/ontology/vhog) (VHOG) | deprecated | ODK migration (2021) | ? | ? | empty |
| [Vertebrate skeletal anatomy ontology](http://obofoundry.org/ontology/vsao) (VSAO) | deprecated | last release | VSAO xrefs in Uberon | equivalent | OK |
| [C. elegans gross anatomy ontology](http://obofoundry.org/ontology/wbbt) (WBbt) | | last release | WBbt xrefs in Uberon | reverse genus differentia (NCBITaxon:6237) | OK |
| [C. elegans development ontology](http://obofoundry.org/ontology/wbls) (WBls) | | last release | WBls xrefs in Uberon | reverse genus differentia (NCBITaxon:6237) | OK |
| [Xenopus anatomy ontology](http://obofoundry.org/ontology/xao) (XAO) | | last release | XAO xrefs in Uberon | reverse genus differentia (NCBITaxon:8353) | OK |
| [Zebrafish anatomy ontology](http://obofoundry.org/ontology/zfa) (ZFA) | | last release | ZFA xrefs in Uberon | reverse genus differentia (NCBITaxon:7954) | OK |
| [Zebrafish development stages ontology](http://obofoundry.org/ontology/zfs) (ZFS) | | last release | ZFS xrefs in Uberon | reverse genus differentia (NCBITaxon:7954) | OK |

# CL bridges

| Foreign end | OBO Foundry status | Last updated | Source of truth | Bridge type | Remarks |
| ----------- | ------------------ | ------------ | --------------- | ----------- | ------- |
| [Amphibian gross anatomy ontology](http://obofoundry.org/ontology/aao) (AAO) | deprecated | last release | AAO xrefs in CL | reverse genus differentia (NCBITaxon:8292) | one bridging axiom only |
| [Anatomical entity ontology](http://obofoundry.org/ontology/aeo) (AEO) | inactive | last release | AEO xrefs in CL | equivalent | one bridging axiom only |
| [Bilateria anatomy ontology](http://obofoundry.org/ontology/bila) (BILA) | deprecated | last release | BILA xrefs in CL | equivalent | empty |
| [Biological spatial ontology](http://obofoundry.org/ontology/bspo) (BSPO) | | last release | BSPO xrefs in CL | equivalent | empty |
| [Common anatomy reference ontology](http://obofoundry.org/ontology/caro) (CARO) | | last release | CARO xrefs in CL | equivalent | two bridging axioms only |
| [Developing human brain atlas](https://www.brainspan.org/) (DHBA) | N/A | last release | DHBA xrefs in CL | reverse genus differentia (NCBITaxon:9606) | empty |
| [Developing mouse brain atlas](https://developingmouse.brain-map.org) (DMBA) | N/A | may 2022 | [ABA Uberon](https://github.com/obophenotype/ABA_Uberon) | complex | empty |
| [Experimental factor ontology](https://www.ebi.ac.uk/efo/) (EFO) | N/A | last release | EFO xrefs in CL | equivalent | OK |
| [Human developmental anatomy, abstract version](http://obofoundry.org/ontology/ehdaa) (EHDAA) | deprecated | last release | EHDAA xrefs in CL | has-subclass | empty |
| [human developmental anatomy, abstract](http://obofoundry.org/ontology/ehdaa2.html) (EHDAA2) | | last release | EHDAA2 xrefs in CL | reverse genus differentia (NCBITaxon:9606) | OK |
| [Mouse developmental anatomy ontology](http://obofoundry.org/ontology/emapa) (EMAPA) | | last release | EMAPA xrefs in CL | reverse genus differentia (NCBITaxon:10090) | OK |
| [eVOC (expressed sequence annotation for humans)](http://obofoundry.org/ontology/ev) (EV) | deprecated | last release | EV xrefs in CL | has-subclass | one bridging axiom only |
| [Drosophila anatomy ontology](http://obofoundry.org/ontology/fbbt) (FBbt) | | last release | FBbt’s SSSOM set | reverse genus differentia (NCBITaxon:7227) | OK |
| [Drosophila development ontology](http://obofoundry.org/ontology/fbdv) (FBdv) | | last release | FBdv xrefs in CL | reverse genus differentia (NCBITaxon:7227) | empty |
| [Foundational model of anatomy ontology](http://obofoundry.org/ontology/fma) (FMA) | inactive | last release | FMA xrefs in CL | reverse genus differentia (NCBITaxon:9606) | OK |
| [Gene ontology](http://obofoundry.org/ontology/go) (GO) | | last release | GO xrefs in CL | equivalent | one bridging axiom only |
| [Hymenoptera anatomy ontology](http://obofoundry.org/ontology/hao) (HAO) | | last release | HAO xrefs in CL | reverse genus differentia (NCBITaxon:7399) | empty |
| [Human brain atlas](https://human.brain-map.org/) (HBA) | N/A | last release | HBA xrefs in CL | reverse genus differentia (NCBITaxon:9606) | OK |
| [Human developmental stages](http://obofoundry.org/ontology/hsapdv) (HsapDv) | | last release | HsapDv xrefs in CL | reverse genus differentia (NCBITaxon:9606) | empty |
| Kidney and urinary pathway ontology (KUPO) | unknown to the OBO Foundry | ODK migration (2021) | ? | reverse genus differentia (NCBITaxon:9606) | OK |
| [Mouse adult gross anatomy](http://obofoundry.org/ontology/ma) (MA) | | last release | MA xrefs in CL | reverse genus differentia (NCBITaxon:10090) | OK |
| [Mouse brain atlas](https://mouse.brain-map.org) (MBA) | N/A | may 2022 | [ABA Uberon](https://github.com/obophenotype/ABA_Uberon) | complex | empty |
| [Medaka fish anatomy and development](http://obofoundry.org/ontology/mfo) (MFO) | deprecated | last release | MFO xrefs in CL | reverse genus differentia (NCBITaxon:8089) | empty |
| [Mouse developmental stages](http://obofoundry.org/ontology/mmusdv) (MmusDv) | | last release | MmusDv xrefs in CL | reverse genus differentia (NCBITaxon:10090) | empty |
| [NCI thesaurus OBO edition](http://obofoundry.org/ontology/ncit) (NCIT) | | last release | NCIT xrefs in CL | has-subclass | OK |
| [NIF gross anatomy](https://github.com/SciCrunch/NIF-Ontology) (NIF\_grossanatomy) | N/A | ODK migration (2021) | ? | ? | empty |
| ? OG | unknown to the OBO Foundry | last release | OG xrefs in CL | equivalent | empty |
| ? OGES | unknown to the OBO Foundry | last release | OGES xrefs in CL | has-subclass | empty |
| [Medaka developmental stages](http://obofoundry.org/ontology/olatdv) (OlatDv) | inactive | last release | OlatDv xrefs in CL | reverse genus differentia (NCBITaxon:8089) | empty |
| Primate brain atlas (PBA) | N/A | last release | PBA xrefs in CL | reverse genus differentia (NCBITaxon:9443) | empty |
| SNOMED CT (SCTID) | N/A | least release | SCTID xrefs in CL | has-subclass | one bridging axiom only |
| [Spider ontology](http://obofoundry.org/ontology/spd) (SPD) | | last release | SPD xrefs in CL | reverse genus differentia (NCBITaxon:6893) | empty |
| [Tick anatomy ontology](http://obofoundry.org/ontology/tads) (TADS) | inactive | last release | TADS xrefs in CL | reverse genus differentia (NCBITaxon:6939) | empty |
| [Teleost anatomy ontology](http://obofoundry.org/ontology/tao) (TAO) | deprecated | last release | TAO xrefs in CL | reverse genus differentia (NCBITaxon:32443) | empty |
| [Mosquito gross anatomy ontology](http://obofoundry.org/ontology/tgma) (TGMA) | inactive | last release | TGMA xrefs in CL | reverse genus differentia (NCBITaxon:44484) | empty |
| [Vertebrate skeletal anatomy ontology](http://obofoundry.org/ontology/vsao) (VSAO) | deprecated | last release | VSAO xrefs in CL | equivalent | three bridging axioms only |
| [C. elegans gross anatomy ontology](http://obofoundry.org/ontology/wbbt) (WBbt) | | last release | WBbt xrefs in CL | reverse genus differentia (NCBITaxon:6237) | OK |
| [C. elegans development ontology](http://obofoundry.org/ontology/wbls) (WBls) | | last release | WBls xrefs in CL | reverse genus differentia (NCBITaxon:6237) | empty |
| [Xenopus anatomy ontology](http://obofoundry.org/ontology/xao) (XAO) | | last release | XAO xrefs in CL | reverse genus differentia (NCBITaxon:8353) | OK |
| [Zebrafish anatomy ontology](http://obofoundry.org/ontology/zfa) (ZFA) | | last release | **CL xrefs in ZFA** | reverse genus differentia (NCBITaxon:7954) | currently broken |
| [Zebrafish development stages ontology](http://obofoundry.org/ontology/zfs) (ZFS) | | last release | ZFS xrefs in CL | reverse genus differentia (NCBITaxon:7954) | empty |

Of note, it is completely expected that the CL bridges with foreign ontologies such as FBdv, HsapDv, MFO, MmusDv, WBls, or ZFS are empty: those ontologies only contain terms representing life stages, and CL has no such terms (all terms representing life stages are in Uberon).

**Comment by gouttegd** [comment]
What I am considering to do (unless there is objection):

* Remove the CL bridges to the life stage ontologies. This shouldn’t be controversial. Unless we start putting some life stage terms in CL (why whould we ever do that?), those bridges will _always_ remain empty, so they serve no purpose at all.

* Remove the bridges to ontologies that are _deprecated_ (e.g., AAO, BILA, EHDAA, EMAP, EV, etc.). We may keep the existing cross-references on the Uberon/CL terms (though I’be keen to remove them as well), but they would no longer be used to generate bridge files.

* I’d be inclined to do the same for ontologies that are _inactive_ (e.g. AEO, MFA, OlatDv, etc.), but maybe this is going a bit too far.

* For prefixes that are  “unknown to the OBO Foundry” (e.g. ABA, BSD, OG, OGES, etc.): unsure. All those prefixes are also unknown to Bioregistry. If someone knows which resources these prefixes refer to, please share your knowledge and indicate whether you think having bridges with these resources is still relevant.

* For the ontologies where the source of truth is currently unknown (meaning we have the bridges, but no idea where they come from), I’d suggest moving the source of truth to cross-references in Uberon/CL, to align them with most of the other bridges. That would concern at least BFO, and possibly ABA, NIFSTD, VAO, KUPO (if we decide to keep the bridges with those).

**Comment by gouttegd** [comment]
Another piece of information:

The following bridges are used to build the `composite-metazoan` product:
* FBbt
* WBbt
* FBdv
* WBls
* ZFA
* XAO
* DHBA
* DMBA
* MBA
* HBA
* PBA
* EHDAA2
* EMAPA
* MA
* FMA

In addition:
* EMAP is used to build `composite-mouse-with-stages`;
* VHOG is used to build `composite-vhog`.

Those last two products are typically _not_ built in recent releases.

**Comment by matentzn** [comment]
I looked through the empty ones, and I agree they can be all excluded.

**Comment by gouttegd** [comment]
FYI, here is what I plan to do with the current bridges when overhauling the pipeline that generates them:

1) The following bridges will be removed (they will no longer be produced and will be removed from the repository; the cross-references in the -edit file will be left untouched, so no information will be lost – if we later decide to reactive those bridges, we can do so in a matter of seconds) as the ontologies they bridge to are formally deprecated:

* AAO
* BILA
* EHDAA
* EMAP
* EV
* MFO
* TAO
* VHOG
* VSAO

In addition, the bridge to OlatDv will be removed as well; that ontology is only _inactive_ and not _deprecated_, but since MFO is deprecated, I am not sure there is a point in keeping OlatDv if we drop MFO (OlatDv is the ontology of life stage terms for the same taxon as MFO; basically, OlatDv is to MFO what FBdv is to FBbt).

2) The following bridges will also be removed since they are, by construction, empty (they are supposed to bridge CL to ontologies of life stage terms; as mentioned above, CL has no such terms):

* CL bridge to FBdv
* CL bridge to HsapDv
* CL bridge to MmusDv
* CL bridge to WBls
* CL bridge to ZFS

3) The following bridges will be removed for the indicated reason(s):

* ABA: redundant with the custom MBA/DMBA bridges
* BSD: currently empty and source of truth unknown (so we can’t fill it)
* NIF_grossanatomy: Likewise
* NIFSTD: source of truth unknown, contains only 6 terms including 2 whose IRI cannot be resolved and 4 that points to foreign terms that have since been obsoleted and replaced by the very Uberon term they are mapped with
* VAO: VAO is seemingly the same thing as VSAO (cross-references are the same, and both [Bioregistry](https://bioregistry.io/registry/vsao) and [Bio2KG](https://registry.bio2kg.org/resource/vao) list `vao` as an alternative prefix for `vsao`)

4) The following bridges will be maintained and have their source of truth moved to the -edit file:

* BFO
* KUPO

If you think one (or more!) of the bridges slated for removal should be kept, please say so.

**Comment by gouttegd** [comment]
Final list of bridges about to be deprecated

# Uberon bridges

| Bridge name | Foreign end | Reason for deprecation |
| ----------- | ----------- | ---------------------- |
| `uberon-bridge-to-aao` | [Amphibian gross anatomy ontology](http://obofoundry.org/ontology/aao) | AAO is deprecated |
| `uberon-bridge-to-aba` | Allen Brain Atlas | Redundant with the MBA/DMBA bridges |
| `uberon-bridge-to-bila` | [Bilateria anatomy ontology](http://obofoundry.org/ontology/bila) | BILA is deprecated |
| `uberon-bridge-to-bspo` | [Biological spatial ontology](http://obofoundry.org/ontology/bspo) | Bridge is empty |
| `uberon-bridge-to-efo` | [Experimental factor ontology](https://www.ebi.ac.uk/efo/) | Bridge “makes no practical sense” (©️  @matentzn) |
| `uberon-bridge-to-ehdaa` | [Human developmental anatomy, abstract version](http://obofoundry.org/ontology/ehdaa) | EHDAA is deprecated |
| `uberon-bridge-to-ev` | [eVOC (expressed sequence annotation for humans)](http://obofoundry.org/ontology/ev) | EV is deprecated |
| `uberon-bridge-to-mfo` | [Medaka fish anatomy and development](http://obofoundry.org/ontology/mfo) | MFO is deprecated |
| `uberon-bridge-to-nifstd` | [NIF standard ontology](https://github.com/SciCrunch/NIF-Ontology) | Unknown source of truth, only contains pointless bridging axioms |
| `uberon-bridge-to-og` | ? | Bridge is empty |
| `uberon-bridge-to-olatdv` | [Medaka developmental stages](http://obofoundry.org/ontology/olatdv) | OlatDV is inactive and tied to MFO which is deprecated |
| `uberon-bridge-to-tao` | [Teleost anatomy ontology](http://obofoundry.org/ontology/tao) | TAO is deprecated |
| `uberon-bridge-to-vhog` | [Vertebrate homologous ontology group](http://obofoundry.org/ontology/vhog) | VHOG is deprecated |
| `uberon-bridge-to-vsao` | [Vertebrate skeletal anatomy ontology](http://obofoundry.org/ontology/vsao) | VSAO is deprecated |
| `uberon-ext-bridge-to-zfa` | [Xebrafish anatomy ontology](http://obofoundry.org/ontology/zfa)| Uberon “ext” no longer exists (note that this is _not_ the `uberon-bridge-to-zfa`!) |

# CL bridges

| Bridge name | Foreign end | Reason for deprecation |
| ----------- | ----------- | ---------------------- |
| `cl-bridge-to-aao` | [Amphibian gross anatomy ontology](http://obofoundry.org/ontology/aao) | AAO is deprecated |
| `cl-bridge-to-bila` | [Bilateria anatomy ontology](http://obofoundry.org/ontology/bila) | BILA is deprecated |
| `cl-bridge-to-bspo` | [Biological spatial ontology](http://obofoundry.org/ontology/bspo) | Bridge is empty |
| ` cl-bridge-to-dhba` | [Developing human brain atlas](https://www.brainspan.org/) | Bridge is empty |
| `cl-bridge-to-dmba` | [Developing mouse brain atlas](https://developingmouse.brain-map.org/) | Bridge is empty |
| `cl-bridge-to-efo` | [Experimental factor ontology](https://www.ebi.ac.uk/efo/) | Bridge “makes no practical sense” (©️  @matentzn) |
| `cl-bridge-to-ehdaa` | [Human developmental anatomy, abstract version](http://obofoundry.org/ontology/ehdaa) | EHDAA is deprecated |
| `cl-bridge-to-ev` | [eVOC (expressed sequence annotation for humans)](http://obofoundry.org/ontology/ev) | EV is deprecated |
| `cl-bridge-to-fbdv` | [Drosophila development ontology](http://obofoundry.org/ontology/fbdv) | Bridge is empty |
| `cl-bridge-to-hao` | [Hymenoptera anatomy ontology](http://obofoundry.org/ontology/hao) | Bridge is empty |
| `cl-bridge-to-hba` | [Human brain atlas](https://human.brain-map.org/) | Bridge is empty |
| `cl-bridge-to-hsapdv` | [Human developmental stages](http://obofoundry.org/ontology/hsapdv) | Bridge is empty |
| `cl-bridge-to-mba` | [Mouse brain atlas](https://mouse.brain-map.org/) | Bridge is empty |
| `cl-bridge-to-mfo` | [Medaka fish anatomy and development](http://obofoundry.org/ontology/mfo) | MFO is deprecated |
| `cl-bridge-to-mmusdv` | [Mouse developmental stages](http://obofoundry.org/ontology/mmusdv) | Bridge is empty |
| `cl-bridge-to-nif_grossanatomy` | ? | Bridge is empty |
| `cl-bridge-to-og` | ? | Bridge is empty |
| `cl-bridge-to-oges` | ? | Bridge is empty |
| `cl-bridge-to-olatdv` | [Medaka developmental stages](http://obofoundry.org/ontology/olatdv) | OlatDV is inactive and tied to MFO which is deprecated; also, the bridge is empty |
| `cl-bridge-to-pba` | Primate brain atlas | Bridge is empty |
| `cl-bridge-to-spd` | [Spider ontology](http://obofoundry.org/ontology/spd) | Bridge is empty |
| `cl-bridge-to-tads` | [Tick anatomy ontology](http://obofoundry.org/ontology/tads) | Bridge is empty |
| `cl-bridge-to-tao` | [Teleost anatomy ontology](http://obofoundry.org/ontology/tao) | TAO is deprecated |
| `cl-bridge-to-tgma` | [Mosquito gross anatomy ontology](http://obofoundry.org/ontology/tgma) | Bridge is empty |
| `cl-bridge-to-vsao` | [Vertebrate skeletal anatomy ontology](http://obofoundry.org/ontology/vsao) | VSAO is deprecated |
| `cl-bridge-to-wbls` | [C. elegans development ontology](http://obofoundry.org/ontology/wbls) | Bridge is empty |
| `cl-bridge-to-zfs` | [Zebrafish development stages](http://obofoundry.org/ontology/zfs) | Bridge is empty |

**Comment by gouttegd** [comment]
The overhaul of the bridge pipeline is over, so we can close here.
