### ISSUE TITLE
"insect pharynx" has bogus ID

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#3051]
The recently added term '[insect pharynx](http://purl.obolibrary.org/obo/UBERON_60005380)' has an ID with 8-digits (UBERON:60005380) instead of the Uberon standard of 7 digits.

The term needs to be obsoleted for technical reason and replaced with a new term with the correct ID of UBERON:6005380.

Need a QC check to flag similar bogus IDs in the future.

**Comment by anitacaron** [comment]
Could you create another issue to address the QC part, please?

**Comment by anitacaron** [comment]
Never mind, I didn't check the PR before.
