### ISSUE TITLE
Add OMO import to UBERON

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/uberon#3058]
Context: https://github.com/obophenotype/cell-ontology/issues/2045

Depends on importing OMO (@anitacaron).

Once OMO is imported, edit all plural term annotation properties to [OMO:0003004](http://purl.obolibrary.org/obo/OMO_0003004) 'plural form'.

**Comment by bvarner-ebi** [comment]
#3080 details the ontology edits required.

@anitacaron, can we re-appropriate this issue to track adding the OMO import to Uberon? If so, I will assign this ticket to you and, once completed, follow up in #3080.

**Comment by anitacaron** [comment]
Ok, can you change the title, too, please?
