### ISSUE TITLE
pro-, meso-, metapterygium definition

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#306]
Hi Chris,

These terms are currently (part_of UBERON:0010710 ! pectoral fin skeleton) and also definitions are related to pectoral fin, but in the literature, we find a more extended definition:

"In archetypal paired appendages, skeletal supports consisted of several large endoskeletal bones (pro-, meso-, and metapterygium of Gegenbaur, 1878) lying at the base, which articulate proximally with pectoral or pelvic girdles and distally with numerous smaller bones supporting dermal fin rays."

http://www.sciencedirect.com/science/article/pii/S0012160608010166

So either part of pectoral fin or part of pelvic fin?

Whatever these bones are all present (tribasal type) or not (dibasal type for instance), they should refer both to pectoral and pelvic fins, I guess.

Thank you.

Anne

Bgee team

**Comment by cmungall** [comment]
This is still not done, but we are closing old issues. Current defs:

```
[Term]
id: UBERON:2100623
name: basipterygium element
def: "Endochondral element that is paired and supports the pelvic fin. The basipterygium has a posteromedial process called the ischiac process (Wietzman 1962)." [TAO:wd]
synonym: "basipterygia" RELATED PLURAL [TAO:0000623]
synonym: "basipterygium" RELATED []
synonym: "basiptrygium ischiatique" RELATED [PSPUB:0000145]
synonym: "os pelvien" RELATED [PSPUB:0000164]
synonym: "pelvic bone" RELATED [TAO:0000623]
synonym: "pelvic plate" RELATED []
synonym: "pubic plate" RELATED []
is_a: UBERON:0010363 ! endochondral element
relationship: overlaps UBERON:2001939 ! inter-basipterygium joint
relationship: part_of UBERON:0007832 ! pelvic girdle skeleton

[Term]
id: UBERON:4300081
name: mesopterygium element
is_a: UBERON:2101587 ! pectoral fin proximal radial element
created_by: WD

[Term]
id: UBERON:4300082
name: metapterygium element
is_a: UBERON:2101587 ! pectoral fin proximal radial element
created_by: WD

[Term]
id: UBERON:4300083
name: propterygium element
is_a: UBERON:2101587 ! pectoral fin proximal radial element
created_by: WD

```
