### ISSUE TITLE
Removed names from contributor annotation property

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/uberon#3070]
Every time I do an edit in an Uberon branch, it has the following effect for some contributor annotation properties:

<img width="1387" alt="image" src="https://github.com/obophenotype/uberon/assets/94959119/77ca76a6-b919-4475-a66c-404bf5146cbe">

Is this an Uberon issue, protégé or from another ontology? Is it ok to commit them? I have been removing these changes so far.

**Comment by anitacaron** [comment]
I [imported ORCIDIO](#3071) into Uberon, and it should not happen again.
