### ISSUE TITLE
UBERON:0005439 does not have textual definition

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#3073]
UBERON:0005439 does not have textual definition, suggested definition: 

An embryonic structure that is the internal layer of the embryonic gut, formed by the recruitment of epiblast cells through the primitive streak. [PMID:27534536]

on this note, @anitacaron  do you know if there is checks for textual definitions, if so how did this slip through, if not should we consider (might be a painful fix lol)

**Comment by anitacaron** [comment]
@shawntanzk The "missing definition" check is now a part of the [ROBOT report](https://github.com/obophenotype/uberon/blob/master/src/ontology/reports/uberon-edit.obo-obo-report.tsv) with an error level of WARN.
