### ISSUE TITLE
Unsats caused by an issue involving tail (UBERON:0002415)

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/uberon#3081]
Among the remaining unsats, a handful are caused by an issue involving [tail](http://purl.obolibrary.org/obo/UBERON_0002415) and the fact that said tail is constrained not to exist in _Homo sapiens_. Here is an example of such an issue:

- [http://purl.obolibrary.org/obo/UBERON_0011528 in taxon http://purl.obolibrary.org/obo/NCBITaxon_9606](http://purl.obolibrary.org/obo/RO_0002175#285d4803f7b54839300fb8f489288fbb-89a49698565f149a052a9b292cd497d0) SubClassOf [pubococcygeus muscle](http://purl.obolibrary.org/obo/UBERON_0011528)
  - [pubococcygeus muscle](http://purl.obolibrary.org/obo/UBERON_0011528) SubClassOf [has muscle insertion](http://purl.obolibrary.org/obo/RO_0002373) some [coccyx](http://purl.obolibrary.org/obo/UBERON_0001350)
    - [has muscle insertion](http://purl.obolibrary.org/obo/RO_0002373) SubPropertyOf: [attached to](http://purl.obolibrary.org/obo/RO_0002371)
      - [attached to](http://purl.obolibrary.org/obo/RO_0002371) SubPropertyOf: [connected to](http://purl.obolibrary.org/obo/RO_0002170)
    - [coccyx](http://purl.obolibrary.org/obo/UBERON_0001350) SubClassOf [develops from](http://purl.obolibrary.org/obo/RO_0002202) some [embryonic post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007144)
      - [embryonic post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007144) SubClassOf [transformation of](http://purl.obolibrary.org/obo/RO_0002494) some [post-anal tail bud](http://purl.obolibrary.org/obo/UBERON_0002533)
        - [post-anal tail bud](http://purl.obolibrary.org/obo/UBERON_0002533) SubClassOf [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) some [post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007812)
          - [post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007812) EquivalentTo [tail](http://purl.obolibrary.org/obo/UBERON_0002415) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [caudal region](http://purl.obolibrary.org/obo/UBERON_0006071))
            - [tail](http://purl.obolibrary.org/obo/UBERON_0002415) SubClassOf [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some (not ([Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606)))
        - [transformation of](http://purl.obolibrary.org/obo/RO_0002494) SubPropertyOf: [develops from](http://purl.obolibrary.org/obo/RO_0002202)
      - [develops from](http://purl.obolibrary.org/obo/RO_0002202) SubPropertyOf: [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254)
- [http://purl.obolibrary.org/obo/UBERON_0011528 in taxon http://purl.obolibrary.org/obo/NCBITaxon_9606](http://purl.obolibrary.org/obo/RO_0002175#285d4803f7b54839300fb8f489288fbb-89a49698565f149a052a9b292cd497d0) SubClassOf [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606)
- [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some (not ([Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606)))
- [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
- [connected to](http://purl.obolibrary.org/obo/RO_0002170) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

I believe the faulty axiom, in this issue and the similar ones, is the following:

- [post-anal tail bud](http://purl.obolibrary.org/obo/UBERON_0002533) SubClassOf [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) some [post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007812)

If we look at [post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007812), it is said to [transformation of](http://purl.obolibrary.org/obo/RO_0002494) some [embryonic post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007144) – _not_ the transformation of some [post-anal tail bud](http://purl.obolibrary.org/obo/UBERON_0002533)! So it seems there is a discrepancy between the developmental relations: by following the [transformation of](http://purl.obolibrary.org/obo/RO_0002494), we have:

- post-anal tail bud -> embryonic post-anal tail -> post-anal tail

but following the [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387), we have directly instead:

- post-anal tail bud -> post-anal tail

_Originally posted by @gouttegd in https://github.com/obophenotype/uberon/issues/2928#issuecomment-1726376929_

**Comment by aleixpuigb** [comment]
Removing [post-anal tail bud](http://purl.obolibrary.org/obo/UBERON_0002533) SubClassOf [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) some [post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007812) should fix the problem, and the relation is maintained:

>If we look at [post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007812), it is said to [transformation of](http://purl.obolibrary.org/obo/RO_0002494) some [embryonic post-anal tail](http://purl.obolibrary.org/obo/UBERON_0007144) – not the transformation of some [post-anal tail bud](http://purl.obolibrary.org/obo/UBERON_0002533)! So it seems there is a discrepancy between the developmental relations: by following the [transformation of](http://purl.obolibrary.org/obo/RO_0002494), we have:
>
>post-anal tail bud -> embryonic post-anal tail -> post-anal tail
