### ISSUE TITLE
CI failure, maybe due to overlapping synonyms

### ISSUE THREAD

**Issue by cthoyt** [obophenotype/uberon#3084]
In my recent PRs #3082 and #3083, there appear to be some QA check failures occurring. From how they look, it's because different terms are sharing exact synonyms:

```csv
entity,property,value
http://purl.obolibrary.org/obo/UBERON_0002633,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,nV
http://purl.obolibrary.org/obo/UBERON_2000438,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,phy
http://purl.obolibrary.org/obo/UBERON_2005093,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,NV
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,PHY
```

This wasn't an issue in the last merge, so I'm guessing it has to do with updates to odk/robot. Can someone take a look at these and solve them?

**Comment by cmungall** [comment]
looks like the check went from case sensitive to case insensitive. This is
probably a good thing but your PR should not have been caught in the
crossfire. If someone is able to make the fix (here or another PR), I would
demote the TAO derived abbrevs

**Comment by anitacaron** [comment]
That's unexpected. The ODK version in the QC is v1.4.1.

**Comment by anitacaron** [comment]
Updating the ODK to v1.4.3 with new OWLAPI and ROBOT versions in the QC will fix the issue.

**Comment by cthoyt** [comment]
It appears that this was not fixed by the ODK update. #3082 is still failing
