### ISSUE TITLE
Consider adding terms for "caudal region of psoas major muscle" and "cranial region of psoas major muscle"

### ISSUE THREAD

**Issue by jrsjrs** [obophenotype/uberon#3114]
**Preferred term label:**  
caudal region of psoas major muscle
cranial region of psoas major muscle

**Synonyms**
caudal segment of psoas major muscle
cranial segment of psoas major muscle

**Definition (free text, please give PubMed ID)**
PMID:19930517

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
psoas major muscle (UBERON:0001298)

**Your nano-attribution (ORCID)**

The reference also talks about differences in muscle fibers between the left and right psoas major muscle.  I don't know if there is enough evidence to warrant adding terms for left/right psoas major muscle and then caudal and cranial regions of both of those.  The use case we are trying to fulfill involves measurements taken in all four regions--left cranial, left caudal, right cranial and right caudal--but we do have another mechanism to specify left/right (and cranial/caudal) if necessary, i.e., if you do not find sufficient evidence to warrant adding the terms.

**Comment by aleixpuigb** [comment]
Hi @jrsjrs, tank you for your request.
The reference you have provided only compares the cranial and caudal regions of the origin of the psoas major (L1 origin is cranial and L4 origin is caudal). However, it doesn't study the caudal region of the muscle (insertion in the lesser trochanter of the femur).
The terms that you are requesting seems to focus on the whole muscle, and not only the origin. Is that correct?

As you mentioned, there seems to be a difference in the fibre composition between the origin of the left and the right psoas major. I need to do a bit more research to see if there are more evidences to support the addition of these terms. Do you have any additional article that shows differences between both muscles?

**Comment by aleixpuigb** [comment]
Hi @jrsjrs, since the terms you requested don't align with the ones described in the article, do you want to close this ticket?

**Comment by jrsjrs** [comment]
Hi, @aleixpuigb, thanks for looking into it.  I didn't find any other articles that talked about it so I'll go ahead and close the ticket.
