### ISSUE TITLE
NTR: intestinal lamina propria terms

### ISSUE THREAD

**Issue by EMRutherford** [obophenotype/uberon#3130]
**Preferred term label:**
jejunum lamina propria

**Synonyms**
lamina propria of jejunum, jejunal lamina propria

**Definitions (free text, please give PubMed ID)**
A lamina propria that is part of a jejunum (PMID: 9394954)
(https://www.kenhub.com/en/library/anatomy/the-jejunum)

**Parent terms (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lamina propria of small intestine (UBERON:0001238)
intestinal villus of jejunum (UBERON:0008343)
jejunal mucosa (UBERON:0000399)

**Your nano-attribution (ORCID)**
0000-0001-8134-3037

**Preferred term label:**
ileum lamina propria

**Synonyms**
lamina propria of ileum, Ileal lamina propria

**Definitions (free text, please give PubMed ID)**
A lamina propria that is part of an ileum (PMID: 29316348)
(https://www.kenhub.com/en/library/anatomy/the-ileum)

**Parent terms (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
lamina propria of small intestine (UBERON:0001238)
intestinal villus of ileum (UBERON:0008344)
ileal mucosa (UBERON:0000331)

**Your nano-attribution (ORCID)**
0000-0001-8134-3037

**Comment:**  One of these terms is needed to describe tissues used for experiments for the Human Cell Atlas.  I am requesting both for consistency within Uberon.  I set these up as sister terms to duodenum lamina propria (UBERON:0015834), and because that term exists, I think it is appropriate to add these as well.

**Comment by aleixpuigb** [comment]
@EMRutherford Thank you for submitting these terms, I will add them to Uberon.

**Comment by aleixpuigb** [comment]
@EMRutherford The terms have been created and will be available in the next release. Thank you for your help!
