### ISSUE TITLE
Remove CARO from composite pipeline

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/uberon#3139]
Given that there has been an effort to get rid of caro in favour of a thin anatomy top layer in uberon, https://github.com/obophenotype/uberon/pull/2614, can you judge if removing this will cause issues?

_Originally posted by @matentzn in https://github.com/obophenotype/uberon/pull/3129#discussion_r1412129802_

**Comment by gouttegd** [comment]
Who are you asking this? “Causing issues” for who?

`composite-metazoan` itself will be just fine without the CARO bridges. Removing them won’t break anything internally.

The question is, “are there users of `composite-metazoan` somewhere who need the composite ontology to include those bridges?” That’s not a technical question. If the answer is “yes”, we can keep those bridges in place; if the answer is “no”, it’s two lines to remove in `uberon.Makefile`.

**Comment by gouttegd** [comment]
In fact the only way to know whether someone needs those bridges might be to... remove them and wait for that someone to show up on the issue tracker complaining about the missing bridges. 😀

**Comment by matentzn** [comment]
I agree and maybe just announce, again, on slack. Eventually we could contemplate a mailing list for Uberon as well.

**Comment by anitacaron** [comment]
> To be clear: when I say “removing the bridges”, I mean “stop merging them in composite-metazoan”. The bridges themselves would still be available in the bridges directory for whoever might want them.

I agree with this action.
