### ISSUE TITLE
add synonyms 'lateral border of tongue' and 'lateral surface of the tongue' to 'margin of tongue' UBERON:0011877

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/uberon#3144]
**Uberon term**
'margin of tongue' UBERON:0011877

**Synonym to be added**
'lateral border of tongue'
'lateral surface of the tongue'
NCIT:C160983

**exact ?**

**Comment by nicolevasilevsky** [comment]
@paulacalipho do you want to create a PR and assign me to review?
