### ISSUE TITLE
neuromeres

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#318]
Consider adding subclasses for pro and meso

See:
https://sourceforge.net/p/obo/zebrafish-anatomy-zfa-term-requests/110/

And:
doi:10.1016/j.tins.2013.06.004

Note also that some of the brain development relationships should be reviewed. We should have consistent terminology for the presumptive structures that make of the fore, mid and hindbrain plus SC, agreement as to whether they are part_of or df neural tube, etc

**Comment by shawntanzk** [comment]
these terms look like they are already in uberon:
prosomere (UBERON:0014775) & midbrain neuromere (synonym: mesomere)(UBERON:0014776)
