### ISSUE TITLE
Bridge file to bspo 404

### ISSUE THREAD

**Issue by jamesamcl** [obophenotype/uberon#3193]
This URL which used to work (used by the upheno2 build) now results in 404:

    https://raw.githubusercontent.com/obophenotype/uberon/master/src/ontology/bridge/uberon-bridge-to-bspo.owl

Is there no longer a bridge to bspo?

**Comment by anitacaron** [comment]
It was deprecated because the file was empty. REF. https://github.com/obophenotype/uberon/issues/3047#issuecomment-1808346275

**Comment by anitacaron** [comment]
You can check the [previous version](https://github.com/obophenotype/uberon/blob/177c7afa9da084ee001f17a6aadf5d0a1684f0b6/src/ontology/bridge/uberon-bridge-to-bspo.owl) only with annotations and object properties.

**Comment by matentzn** [comment]
@jamesamcl We discussed this at the tech call today - the bridge was erroneuously introduced by me into the uPheno pipeline, but it was never needed. There is no point in this bridge, as there are no mappings across Uberon and BSPO _classes_.
