### ISSUE TITLE
periderm: Revise textual definition and synonyms plus add taxon differences

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#3200]
**Uberon term**
periderm UBERON:0003055 http://purl.obolibrary.org/obo/UBERON_0003055

**Reasons for revisions to textural definition**
1) Some taxon specificity exists on the structure of periderm between mouse and human.

2) In addition, no mention is made that periderm is associated with fetal rather than adult organism. 

3) Stratum corneum which is only associated with adult rather than fetal organism is currently subclass of periderm.
<img width="503" alt="Screenshot 2024-02-05 at 12 20 33 PM" src="https://github.com/obophenotype/uberon/assets/47257000/5014d13c-acce-42ba-a3d4-f418c7a09e6d">

4) Skin of epidermis should have stratum corneum as a layer of it, but it currently does not because it is listed as a subclass of periderm.
<img width="392" alt="Screenshot 2024-02-05 at 12 17 54 PM" src="https://github.com/obophenotype/uberon/assets/47257000/f3ed2370-b843-4759-811c-0c350073a3b8">

======
**synonyms for periderm do not seem correct in light of developmental context**
**current synonyms of periderm**
Synonym
epidermis epithelial layer
epidermis outer layer
epitrichium
EVL
periderm
skin periderm

**suggested qualifying terms**
fetal epidermis epithelial layer
fetal epidermis outer layer

======

**Suggested revision of textual definition**

**Current definition:** A temporary epithelium that derives from the outer layer of the ectdoerm and is shed once the inner layer differentiates to form a true epidermis.

**Revised definition: **
The periderm is the outer layer of embryonic skin, which is essential for the development of the epidermis and the establishment of its barrier function. In humans, the periderm is a monolayer and is shed prenatally.” Panteleyev AA. Dual nature of mouse periderm structure, function and fate. Exp Dermatol. 2022; 31: 1102-1108. doi: [10.1111/exd.14608](https://doi.org/10.1111/exd.14608)

**References**
Panteleyev AA. Dual nature of mouse periderm structure, function and fate. Exp Dermatol. 2022; 31: 1102-1108. doi: [10.1111/exd.14608](https://doi.org/10.1111/exd.14608)

Attribution (OrcID): https://orcid.org/0000-0001-7655-4833

**Comment by aleixpuigb** [comment]
Thank you for submitting this ticket. Based on your research and suggestions, I propose the following edits:

### periderm
**New definition:**
The outermost layer (or layers, depending on the species) of embryonic skin essential for the development of the epidermis and establishment of the barrier functions. The periderm derive from the outer layer of the ectoderm.[PMID:35582825](https://doi.org/10.1111/exd.14608), PMID:[25133425](https://pubmed.ncbi.nlm.nih.gov/25133425)

**Synonyms**
Remove: epidermis epithelial layer,, epidermis outer layer, periderm, skin periderm
Add reference to epitrichium PMID:[28722897](https://pubmed.ncbi.nlm.nih.gov/28722897 "PubMed record of this page")
Add abbreviation to EVL

**Taxon notes**
1. In humans, the periderm is a monolayer and is shed prenatally. [PMID:35582825](https://doi.org/10.1111/exd.14608)
2. In mice, the periderm is bilayered. It consists of the outer layer, which possesses numerous microvilli, and the inner layer that develops specific periderm granules. Both layers can be well recognized as early as at E14.5 and they are shed at different time points: the outer layer is shed in utero, in conjunction with barrier acquisition (E16-18), while the inner layer is retained postnatally. [PMID:35582825](https://doi.org/10.1111/exd.14608)




### stratum corneum of epidermis
**Subclass**
Remove `periderm`
Add `part of some skin epidermis`

**Comment by emquardokus** [comment]
@aleixpuigb

1) Agree with stratum corneum of epidermis relationship updates to periderm.
2) Should there be a different relationship added to periderm?
3) EVL --> already a synonym of periderm but would be good to add in Zebrafish enveloping layer (EVL)--Add "eveloping layer" as synonym because this is what EVL means?  https://zfin.org/action/ontology/term-detail/ZFA:0001185
<img width="607" alt="Screenshot 2024-02-07 at 3 10 53 PM" src="https://github.com/obophenotype/uberon/assets/47257000/b953dc57-cbbb-4522-bf4a-b5f9aa5d18a7">

Otherwise, seems good; thanks

**Comment by aleixpuigb** [comment]
> 2\. Should there be a different relationship added to periderm?

I can add is_a  [outer epithelium](http://purl.obolibrary.org/obo/UBERON_0007376), although I'm not very happy with the textual definition.

> 3\. EVL --> already a synonym of periderm but would be good to add in Zebrafish enveloping layer (EVL)--Add "eveloping layer" as synonym because this is what EVL means? https://zfin.org/action/ontology/term-detail/ZFA:0001185

Thank you, I will also add it as a related synonym.

**Comment by emquardokus** [comment]
Yes, add is_a outer epithelium makes sense.
What part of the definition gives you pause yet?  My main issue initially was the equating it with adult when it was embryonic. 
This was your proposed change: 
**New definition:**
The outermost layer (or layers, depending on the species) of embryonic skin essential for the development of the epidermis and establishment of the barrier functions. The periderm derive from the outer layer of the ectoderm.[PMID:35582825](https://doi.org/10.1111/exd.14608), PMID:[25133425](https://pubmed.ncbi.nlm.nih.gov/25133425)
Thank you for the EVL related synonym.

**Comment by aleixpuigb** [comment]
> What part of the definition gives you pause yet?

Sorry, I meant the definition of [outer epithelium](http://purl.obolibrary.org/obo/UBERON_0007376), since it is an exact synonym of epidermis and it is used interchangeably in the definition. Probably it should be changed to be broader?

**Comment by aleixpuigb** [comment]
Exactly, therefore outer epithelium synonyms and definitions should be edited.
