### ISSUE TITLE
NTRs: Urinary bladder regional terms

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#3214]
**Preferred term label:**
Lateral wall of urinary bladder FMA:15905 (left FMA:15907, right FMA:15906)
Anterior wall of urinary bladder FMA:15903
Posterior wall of urinary bladder FMA:15904
Apex of urinary bladder FMA:15914
Dome of urinary bladder FMA:265241

**Synonyms**
Apex of urinary bladder FMA:15914 ---> Vertex of urinary bladder

**Definition (free text, please give PubMed ID)**
Apex of urinary bladder: The most anterior region of the urinary bladder, attached to the median umbilical ligament (originally the urachus). 

Dome of urinary bladder: Anterosuperior ​region of urinary bladder, with boundaries of the apex and urinary bladder fundus

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
wall of urinary bladder UBERON:0001256 http://purl.obolibrary.org/obo/UBERON_0001256 -->Lateral wall of urinary bladder
wall of urinary bladder UBERON:0001256 http://purl.obolibrary.org/obo/UBERON_0001256 --> Anterior wall of urinary bladder
wall of urinary bladder UBERON:0001256 http://purl.obolibrary.org/obo/UBERON_0001256 --> Posterior wall of urinary bladder

Apex of urinary bladder-->urinary bladder UBERON:0001255 http://purl.obolibrary.org/obo/UBERON_0001255
Dome of urinary bladder-->urinary bladder UBERON:0001255 http://purl.obolibrary.org/obo/UBERON_0001255

<img width="478" alt="Screenshot 2024-02-14 at 2 43 15 PM" src="https://github.com/obophenotype/uberon/assets/47257000/26f89a01-9f0c-46a6-adc8-e06ef5e8c105">

**Your nano-attribution (ORCID)**
Ellen M. Quardokus https://orcid.org/0000-0001-7655-4833  
Sanjay Jain https://orcid.org/0000-0003-2804-127X  
Janet Keast https://orcid.org/0000-0002-4341-3265

**Comment by aleixpuigb** [comment]
For the lateral wall of urinary bladder, are left and right terms also requested as Subclasses?

**Comment by emquardokus** [comment]
Yes please left and right.  I know generally this is frowned upon, but in cases where an organ has laterality and some differences, it seems warranted.  Kidney and lung makes sense for laterality. Thanks

**Comment by aleixpuigb** [comment]
Hi Ellen, please find here all the details I will add. I have minimally adapted the definitions based on the literature:

**Preferred term label:**
lateral wall of urinary bladder
FMA:15905

**Synonyms**


**Definition (free text, please give PubMed ID)**
A wall of the urinary bladder that is situated on the sides or flanks.
[PMID:30548115]([https://doi.org/10.1111/bju.14647](https://doi.org/10.1111/bju.14647))

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
[wall of urinary bladder]([http://purl.obolibrary.org/obo/UBERON_0001256](http://purl.obolibrary.org/obo/UBERON_0001256))

**Your nano-attribution (ORCID)**
Ellen M. Quardokus 0000-0001-7655-4833  
Sanjay Jain 0000-0003-2804-127X  
Janet Keast 0000-0002-4341-32


----

**Preferred term label:**
left lateral wall of urinary bladder

**Synonyms**
left wall of bladder
PMID:32233638

**Definition (free text, please give PubMed ID)**
A lateral wall of the urinary bladder that is located on the left side.
[PMID:30548115]([https://doi.org/10.1111/bju.14647](https://doi.org/10.1111/bju.14647))

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
[wall of urinary bladder]([http://purl.obolibrary.org/obo/UBERON_0001256](http://purl.obolibrary.org/obo/UBERON_0001256))

**Your nano-attribution (ORCID)**
Ellen M. Quardokus 0000-0001-7655-4833  
Sanjay Jain 0000-0003-2804-127X  
Janet Keast 0000-0002-4341-32


----

**Preferred term label:**
right lateral wall of urinary bladder

**Synonyms**
right wall of bladder
PMID:32233638

**Definition (free text, please give PubMed ID)**
A lateral wall of the urinary bladder that is located on the right side.
[PMID:30548115]([https://doi.org/10.1111/bju.14647](https://doi.org/10.1111/bju.14647))

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
[wall of urinary bladder]([http://purl.obolibrary.org/obo/UBERON_0001256](http://purl.obolibrary.org/obo/UBERON_0001256))

**Your nano-attribution (ORCID)**
Ellen M. Quardokus 0000-0001-7655-4833  
Sanjay Jain 0000-0003-2804-127X  
Janet Keast 0000-0002-4341-32


----

**Preferred term label:**
anterior wall of urinary bladder
FMA:15903

**Synonyms**
anterior wall of bladder [PMID:30548115]([https://doi.org/10.1111/bju.14647](https://doi.org/10.1111/bju.14647))
RELATED bladder roof https://doi.org/10.1007/978-3-642-71368-2_6

**Definition (free text, please give PubMed ID)**
The most anterior wall of the urinary bladder.
[PMID:30548115]([https://doi.org/10.1111/bju.14647](https://doi.org/10.1111/bju.14647))
https://doi.org/10.1007/978-3-642-71368-2_6

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
[wall of urinary bladder]([http://purl.obolibrary.org/obo/UBERON_0001256](http://purl.obolibrary.org/obo/UBERON_0001256))

**Your nano-attribution (ORCID)**
Ellen M. Quardokus 0000-0001-7655-4833  
Sanjay Jain 0000-0003-2804-127X  
Janet Keast 0000-0002-4341-32


----

**Preferred term label:**
posterior wall of urinary bladder
FMA:15904

**Synonyms**
posterior wall of bladder [PMID:30548115]([https://doi.org/10.1111/bju.14647](https://doi.org/10.1111/bju.14647))
RELATED fundus https://doi.org/10.1007/978-3-642-71368-2_6

**Definition (free text, please give PubMed ID)**
The most posterior wall of the urinary bladder.
[PMID:30548115]([https://doi.org/10.1111/bju.14647](https://doi.org/10.1111/bju.14647))

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
[wall of urinary bladder]([http://purl.obolibrary.org/obo/UBERON_0001256](http://purl.obolibrary.org/obo/UBERON_0001256))

**Your nano-attribution (ORCID)**
Ellen M. Quardokus 0000-0001-7655-4833  
Sanjay Jain 0000-0003-2804-127X  
Janet Keast 0000-0002-4341-32


----

**Preferred term label:**
apex of urinary bladder
FMA:15914

**Synonyms**
apex of bladder FMA:15914
vertex of urinary bladder 


**Definition (free text, please give PubMed ID)**
The anterior angle of the superior surface of the urinary bladder. The apex of urinary bladder is connected to the umbilicus by the urachus in embryos, and by the median umbilical ligament, a remnant of urachus, in adults.
PMID:[31372192](https://pubmed.ncbi.nlm.nih.gov/31372192)
[doi:10.1016/j.mpsur.2016.04.001](https://doi.org/10.1016/j.mpsur.2016.04.001 "Persistent link using digital object identifier")
[doi:10.1016/j.mpsur.2013.04.013](https://doi.org/10.1016/j.mpsur.2013.04.013 "Persistent link using digital object identifier")

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
'part of' some 'urinary bladder'
'connected to' some umbilicus

**Your nano-attribution (ORCID)**
Ellen M. Quardokus 0000-0001-7655-4833  
Sanjay Jain 0000-0003-2804-127X  
Janet Keast 0000-0002-4341-32

* Add to `remnant of urachus` connects to  'apex of urinary bladder'

----

**Preferred term label:**
dome of urinary bladder
FMA:265241

**Synonyms**


**Definition (free text, please give PubMed ID)**
The anterosuperior surface of the urinary bladder, with boundaries at the apex and fundus of the urinary bladder.
[doi:10.1016/j.mpsur.2016.04.001](https://doi.org/10.1016/j.mpsur.2016.04.001 "Persistent link using digital object identifier")


**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
'part of' some 'urinary bladder'

**Your nano-attribution (ORCID)**
Ellen M. Quardokus 0000-0001-7655-4833  
Sanjay Jain 0000-0003-2804-127X  
Janet Keast 0000-0002-4341-32
