### ISSUE TITLE
The ontobot workflow needs a dedicated user account

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#3223]
(Note: this issue also applies to other obophenotype repositories where the ontobot workflow is enabled, such as CL.)

We have in this repository a GitHub Action workflow that can be used to automatically create pull requests for simple changes described in a ticket with the KGCL syntax.

Currently, pull requests created with that workflow do not trigger the CI test suite automatically. This is because the workflow runs with the default authentication token `GITHUB_TOKEN`, which explicitly does not allow a workflow to trigger the execution of other workflows.

We need to create a non-default authentication token specifically for the purpose of running the ontobot workflow. While any person with admin rights on the repo can do that, it would be better if this was done from a distinct account that is not actually used by any editor. Pull requests created by the ontobot workflow will appear to have been created by whichever account created the authentication token – that account will therefore be unable to approve or request changes on the automatically created pull requests.

CC @anitacaron : This is related to [your question](https://github.com/obophenotype/uberon/pull/3216#pullrequestreview-1882188197) about why the CI test suite was not triggered on #3216.

**Comment by balhoff** [comment]
@gouttegd I have done this for GO using this account: @ontobot. 

Example: https://github.com/geneontology/go-ontology/pull/27037

Do you want to use this account somehow? How do we manage that? Or else will you just create another bot account?

**Comment by gouttegd** [comment]
@balhoff I had forgotten the existence of that account. Reusing it for Uberon/CL would be nice, rather than creating a new one. Would that be possible? Who controls that account?

**Comment by balhoff** [comment]
It's my account. Just let me know the best way to create a token and give it to you.

**Comment by gouttegd** [comment]
I suppose you have admin access to the Uberon and CL repos? Then if I understand correctly I don’t even need to see the token, you should be able to add it directly as a “repository secret” here: https://github.com/obophenotype/uberon/settings/secrets/actions

Then on our side we would need to grant “collaborator access“ to the `ontobot` account.

@hrshdhgd Is there anything else that we should do that I am not aware of?

**Comment by hrshdhgd** [comment]
Once the token is saved as `GH_TOKEN` with adequate permissions, everything should work as expected flawlessly.

**Comment by balhoff** [comment]
@gouttegd sure, I can add the token there. One problem I have had (in go-ontology) is trying to get the permissions set correctly. Basically in the end I have had to grant basically everything to make it work (I'm sure there is some more minimal set though). But I guess that's more of a "risk" for the ontobot user than for the Uberon repo.

**Comment by hrshdhgd** [comment]
![Screenshot_2024-02-19-15-09-37-08_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/obophenotype/uberon/assets/5247075/082fb676-d4e5-4cfe-b0d2-9861e56ccd16)

These are all you need

**Comment by balhoff** [comment]
I've added it as `ONTOBOT_TOKEN`; please let me know if it works!

**Comment by hrshdhgd** [comment]
The workflow will need updating with that variable name and that should work.

**Comment by gouttegd** [comment]
Thank you both! I’ll update the workflow and test it sometimes tomorrow.

**Comment by gouttegd** [comment]
It didn’t work at first because I had stupidly forgotten to grant write access to the `ontobot` account ( 🤦 ), but it is now working as expected.
