### ISSUE TITLE
Terms in Uberon that are immaterial entities and part of material entities

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/uberon#3232]
In Uberon there are 609 terms that are immaterial entities and part of material entities.
![image](https://github.com/obophenotype/uberon/assets/94959119/e98b89ad-d4e1-49ac-9e8f-afa19dc741cd)

Example: apex of heart
![image](https://github.com/obophenotype/uberon/assets/94959119/a0a123c9-adec-46a0-89b8-282626eafc48)

There is a disjoint between `material entity` and `immaterial entity` and only a material entity should be part of a material entity.

There might be two possible solutions, although probably not the same for all terms:
1) Change 'part of' for 'located in'
2) Change the parent term that is_a `immaterial entity`

Also, is it possible to include this on the checks @anitacaron?

**Comment by balhoff** [comment]
@aleixpuigb it is okay for an immaterial entity to be part of a material entity. The logical error would be the other way around: a material entity should not be part of an immaterial entity. That's where 'located in' should be used.
