### ISSUE TITLE
Asserted axiom in uberon-edit file disappears in release file

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/uberon#3243]
**Uberon term**
[stratum corneum of epidermis](http://purl.obolibrary.org/obo/UBERON_0002027)

**Bug description**
The uberon-edit file includes the axiom `'part of' some 'skin epidermis'`:
![image](https://github.com/obophenotype/uberon/assets/94959119/0514cc39-8b73-4a84-8a72-ef4a28298c00)

However, this is not reflected in the release file or OLS:
<img width="470" alt="image" src="https://github.com/obophenotype/uberon/assets/94959119/d66efce3-749b-4f19-838f-d58998197d8b">

![image](https://github.com/obophenotype/uberon/assets/94959119/569b3d73-a6c1-4559-a613-3c872d70b2fb)

I have DL queried ('part of' some 'skin epidermis') to check for redundancy stripping, but the term is not returned. Moreover, the relationship is not validated using the [relation-validator](https://github.com/INCATools/relation-validator)(which validates ontology relationships using [Ubergraph](https://zenodo.org/record/7249759#.ZDRuZOzML1c) as source of truth).

![image](https://github.com/obophenotype/uberon/assets/94959119/b41e8144-6149-42c9-a559-245ecb53357b)

Am I missing something or is this a bug?
@anitacaron @dosumis @gouttegd @cmungall @balhoff

**Comment by gouttegd** [comment]
Isn’t that simply because that axiom was added on the 29th of February (in  commit 731359f44ed65a57bc57915281ca46a533584afe) but the latest release happened [9 days before that](https://github.com/obophenotype/uberon/releases/tag/v2024-02-20)?

**Comment by aleixpuigb** [comment]
Thank you Damien, I should have remembered that.
