### ISSUE TITLE
should 'upper fourth secondary molar tooth' be a subclass of 'molar tooth 4'?

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#3246]
[upper fourth secondary molar tooth](http://purl.obolibrary.org/obo/UBERON_7500057) seems to be missing a logical definition when compared to [upper third secondary molar tooth](http://purl.obolibrary.org/obo/UBERON_0018577) and [upper second secondary molar tooth](http://purl.obolibrary.org/obo/UBERON_0018576). Is this on purpose?

**Comment by aleixpuigb** [comment]
It looks like it is missing. @megbalk, would you agree to include a logical definition?
['molar tooth 4'](http://purl.obolibrary.org/obo/UBERON_7500055) and 'part of' some ['upper jaw region'](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001709?lang=en) and 'part of' some ['secondary dentition'](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0007774?lang=en)

**Comment by megbalk** [comment]
It does seem to be missing. It may be because I wanted to use "maxilla" rather than "upper jaw region".

**Comment by aleixpuigb** [comment]
I have been doing some research, and from what I could find, the maxilla holds the teeth, but teeth are not part of it. We might be able to find a different object property for maxilla and maintain the same pattern as the other molar teeth.
https://www.cancer.gov/publications/dictionaries/cancer-terms/def/maxilla
https://www.elsevier.com/resources/anatomy/skeletal-system/axial-skeleton/maxilla/24695
[PMID:21250078](https://pubmed.ncbi.nlm.nih.gov/21250078)
[PMID:30860762](https://pubmed.ncbi.nlm.nih.gov/30860762)

**Comment by megbalk** [comment]
We should still with the pattern that all the other teeth have. Feel free to add the eq statements.
