### ISSUE TITLE
Add documentation page on how to onboard a new Uberon member

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#3250]
We need a dedicated page in the Uberon documentation page on how a new person can be onboarded to Uberon team.

I suggest the following:

1. Join Uberon / CL slack workspace
2. Join uberon channel on OBO slack
3. Get added to the meeting invites on the Monarch Calendar
4. Add their name to https://obophenotype.github.io/uberon/team/
5. Add their github handle to https://github.com/orgs/obophenotype/teams/uberon-cl-curators
6. Work through https://oboacademy.github.io/obook/pathways/ontology-curator-go-style/, in particular https://oboacademy.github.io/obook/lesson/contributing-to-obo-ontologies/, if they have not contributed before
7. Work through  https://github.com/obophenotype/uberon/blob/master/docs/uberon-editor-sop.md (@aleixpuigb suggestion, thank you!)

Any other things?

**Comment by matentzn** [comment]
@dosumis @cmungall 

Do we need a "formal" process, involving "votes", to do 4 and 5 above?

**Comment by aleixpuigb** [comment]
I would include as well the uberon editor SOP: https://github.com/obophenotype/uberon/blob/master/docs/uberon-editor-sop.md

**Comment by matentzn** [comment]
Thank you @aleixpuigb updated the original comment (OC)

**Comment by gouttegd** [comment]
Also assign them an ID range?

**Comment by gouttegd** [comment]
I was on a documentation update spree, so while I was at it I had a go at adding such a page (#3256).

**Comment by matentzn** [comment]
Aweeeesome!
