### ISSUE TITLE
[NTR] New Term Request: sensory corpuscle

### ISSUE THREAD

**Issue by lubianat** [obophenotype/uberon#3290]
**Preferred term label:**
      
*sensory corpuscle*

**Synonyms**
COEC, COECs, cutaneous end-organ complex

**Definition (free text, please give PubMed ID)**
A mechanosensory complex in the terminal end of some nerves that forms a corpuscle. It comprises one or more neuronal terminations and associated non-neuronal cells. 
[PMID:35356056](https://pubmed.ncbi.nlm.nih.gov/35356056)

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
mechanoreceptor structure
UBERON ID: [UBERON:0012449](http://purl.obolibrary.org/obo/UBERON_0012449)

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-2473-2313

**Link back to Wikidata item**
https://www.wikidata.org/wiki/Q126363978
            
 Relates to: 
     - https://github.com/obophenotype/cell-ontology/issues/2386

**Comment by lubianat** [comment]
@aleixpuigb  @anitacaron I am not sure who is shepherding the issues in UBERON; I don't really have an ID range in Uberon, so I think I cannot open a PR

**Comment by aleixpuigb** [comment]
Hi @lubianat I can add this term for you. Would you like an ID range?

**Comment by lubianat** [comment]
Hi, @aleixpuigb thanks!! Having an ID range would be great; I'd be happy to make a PR. 
If it is any easier to just add the term, well, that works too. 

Cheers!

**Comment by aleixpuigb** [comment]
I have created a PR to give you an ID range. Let me know if you would like me to create the term, or review it once you create the PR.

**Comment by lubianat** [comment]
Of note, there is an important mismatch here between UBERON and FMA. 

FMA has two distinct classes, one for the neuronal part other for the multicellular structure. 

For example, they split: 

* Nerve ending within Pacinian corpuscle (http://purl.obolibrary.org/obo/FMA_83996) 

From 

* Pacinian corpuscle (http://purl.obolibrary.org/obo/FMA_83604)

In UBERON they are all merged under "nerve ending", which is a _multi cell part structure_. 

This looks like it requires some additional modeling on the UBERON side of things. 
It looks like a mid-size restructuring, affecting a few dozen terms. 

In the end it can be reduced to the question whether a _nerve ending_ is just the neuronal part or if it includes the associated glia/epineurial/perineurial cells. 

The definition of _nerve ending_ on UBERON is pulled from MeSH: 

Specialized terminations of peripheral neurons. Nerve endings include NEUROEFFECTOR JUNCTION(s) by which neurons activate target organs and sensory receptors (see RECEPTORS, SENSORY) which transduce information from the various sensory modalities and send it centrally in the nervous system. Presynaptic nerve endings are PRESYNAPTIC TERMINALS.

The definition of _nerve_ in UBERON seems to refer just to the axons: 

An enclosed, cable-like bundle of axons in the peripheral nervous system originating in a nerve root in the central nervous system (or a condensed nervous structure) connecting with peripheral structures.

Not sure how to proceed.  Tagging @cmungall who might have experience with these sort of issues


(also maybe this should be moved to a new ticket? what do you thing @aleixpuigb ?)

**Comment by aleixpuigb** [comment]
sensoI think the main problem is that sensory receptor is_a nerve ending. There can be sensory receptors that are free nerve endings, but in many cases (e.g. the Pacinian corpucle) it also involves other cells. The current EquivalentTo is:
`'nerve ending' and ('capable of' some 'detection of stimulus')`
We could explore changing it, perhaps:
`'cell cluster' and ('has part' some 'nerve ending') and ('capable of' some 'detection of stimulus')`
I am not convinced that we need a nerve ending for each sensory cluster.

**Comment by lubianat** [comment]
From the PR 

> The definition of `multi cell part structure` is:
> 
> > A structure consisting of multiple cell components but which is not itself a cell and does not have (complete) cells as a part.
> 
> In sensory corpuscles there are some complete cells. I'm not aware if there is a term that comprises parts of cells and complete cells, but I will have a look.

So apparently, the capsule of the Pacinian corpuscle is indeed being excluded altogether from the Pacinian corpuscle .
