### ISSUE TITLE
Lip should be part of face

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/uberon#3311]
**Uberon term**
[lip](http://purl.obolibrary.org/obo/UBERON_0001833)

**Suggested revision and reasons**
Lip is part of mouth, but not part of face.

**Comment by rays22** [comment]
Consider dropping the '[face](http://purl.obolibrary.org/obo/UBERON_0001456) 'has part' some [mouth](http://purl.obolibrary.org/obo/UBERON_0000165)' assertion (asserted for UBERON:0001456).
See discussion the [discussion here.](https://github.com/obophenotype/upheno/issues/957#issuecomment-2229000473)

**Comment by uberon** [comment]
Why?

**Comment by rays22** [comment]
> Why?


The `Suggested revision and reasons` should actually read:

> Lip is part of mouth, and it should be also part of face.
> The reason is to prevent inferring (transitively) that 'lingual tonsil' is part of 'face'. 

See https://github.com/obophenotype/upheno/issues/957#issuecomment-2230534954

### The changes implemented in the [associated PR](https://github.com/obophenotype/uberon/pull/3312/files) are as follows
1. UBERON:0001833 lip
    * 'lip' *remains* part of 'mouth'
    * in the [associated PR](https://github.com/obophenotype/uberon/pull/3312/files) 'lip' becomes also part of 'face'

```
[Term]
id: UBERON:0001833
name: lip
...
relationship: part_of UBERON:0000165 {source="BTO", source="FMA-implicit", source="VHOG", source="ZFA"} ! mouth
+relationship: part_of UBERON:0001456 ! face
...
```

2. 'face' no longer 'has part' 'mouth' in the [associated PR](https://github.com/obophenotype/uberon/pull/3312/files)

```
id: UBERON:0001456
name: face
...
- relationship: has_part UBERON:0000165 ! mouth
...
```
