### ISSUE TITLE
Revise subclasses of 'subdivision of oviduct'

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/uberon#3317]
Exploring CL, we have found that there are cell types from endometrium and vagina that wrongly classified as part_of fallopian tube. This is caused as oviduct in Uberon comprises from the ovaries until the exterior of the body:

> A tube or collection of tubes in an animal from the ovaries to the outside of the body.

Therefore, uterus and vagina are 'subdivision of oviduct. However, the logical definition of 'fallopian tube' is:

` 'subdivision of oviduct' and ('part of' some oviduct) and ('develops from' some 'Mullerian duct')`

The uterus and the upper part of the vagina develop from the 'Mullerian duct' (although in Uberon only 'upper part of vagina' contains the axiom), resulting in being classified as part of the 'fallopian tube'.

Therefore, the logical definition of 'fallopian tube' should be removed.

Moreover, 'oviduct epithelium' is part_of the 'fallopian tube'. This should be the opposite in agreement with the current definitions of oviduct and fallopian tube.

cc @cmungall what do you think of these proposed changes?  For reference, I think you added this editor note to oviduct:

> sometimes oviduct is used interchangeably with follaopian tube. Here they are different - the oviduct connects the gonad to the outside in a variety of animals. The mammal-class fallopian tube is derived from the mullerian duct and connects the gonads/infubdibulum to the uterus

**Comment by dosumis** [comment]
Oviduct epithelium has

<img width="402" alt="image" src="https://github.com/user-attachments/assets/f3152f44-cb90-4468-b3bc-7db10406b527">

Removing the incorrect assertion that this epithelium is part_of some fallopian tube removes all the incorrect inference of shared tissues and cell types between uterus and fallopian tube

<img width="531" alt="image" src="https://github.com/user-attachments/assets/decc9125-3aca-43f7-9036-c55fb90eb369">

**Comment by dosumis** [comment]
I'd also suggest renaming left and right uterine tube to left and right fallopian tube and making the current names synonyms

<img width="283" alt="image" src="https://github.com/user-attachments/assets/10a35657-ffa8-4df4-9ecb-6fa63701e6fd">

**Comment by aleixpuigb** [comment]
> I'd also suggest renaming left and right uterine tube to left and right fallopian tube and making the current names synonyms

And for consistency also 'fimbria of uterine tube'.
