### ISSUE TITLE
Broken link at uberon/docs/bridges.md

### ISSUE THREAD

**Issue by larisa1995** [obophenotype/uberon#3344]
**Current state**

At https://github.com/obophenotype/uberon/blob/master/docs/bridges.md you have a link to https://mapping-commons.github.io/sssom/home/ which throws "404 - Not found".

**Suggested solution**

You might replace it with https://mapping-commons.github.io/sssom/.

**Comment by aleixpuigb** [comment]
Thank you for letting us know!

**Comment by aleixpuigb** [comment]
Thank you very much, the issue has been solved
