### ISSUE TITLE
ZFA/Uberon issues: inferior raphe nucleus

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/uberon#3356]
In ZFA, '[inferior raphe nucleus](http://purl.obolibrary.org/obo/ZFA_0000366)' is a '[hindbrain nucleus](http://purl.obolibrary.org/obo/UBERON_0009662)' and therefore [part_of](http://purl.obolibrary.org/obo/BFO_0000050) the [hindbrain](http://purl.obolibrary.org/obo/ZFA_0000029).

The ZFA term is mapped to Uberon’s '[dorsal raphe nucleus](http://purl.obolibrary.org/obo/UBERON_0002043)', which is ultimately [part_of](http://purl.obolibrary.org/obo/BFO_0000050) the [midbrain](http://purl.obolibrary.org/obo/UBERON_0001891) (through several independent relationships).

This is a direct contradiction, and a violation of the disjointness between [hindbrain](http://purl.obolibrary.org/obo/UBERON_0002028) and [midbrain](http://purl.obolibrary.org/obo/UBERON_0001891) in Uberon.

I believe this may be a mapping error. According to [Beecher, Beamer & Bartlett 2019](https://www.sciencedirect.com/science/article/pii/B9780128000502000061), the “raphe nuclei” are

* the _superior raphe nuclei_
  * the _dorsal raphe nucleus_
  * the _median raphe nucleus_
  * the _supralemniscal nucleus_
* the _inferior raphe nuclei_
  * the _nucleus raphe obscurus_
  * the _nucleus raphe pallidus_
  * the _nucleus raphe magnus_

So it seems dubious that ZFA’s '[inferior raphe nucleus](http://purl.obolibrary.org/obo/ZFA_0000366)' should be mapped to '[dorsal raphe nucleus](http://purl.obolibrary.org/obo/UBERON_0002043)' which is (according to the classification above) a **superior** raphe nucleus.

In Uberon, '[nucleus raphe obscurus](http://purl.obolibrary.org/obo/UBERON_0002684)', '[nucleus raphe pallidus](http://purl.obolibrary.org/obo/UBERON_0002157)', and '[nucleus raphe magnus](http://purl.obolibrary.org/obo/UBERON_0002156)' are the three parts making up the '[medullay raphe nuclear complex](http://purl.obolibrary.org/obo/UBERON_0002692)'. So assuming that what ZFA calls the _inferior raphe nucleus_ is the set of three nuclei that Beecher, Beamer & Bartlett call the _inferior raphe nuclei_, the ZFA term should be mapped to '[medullay raphe nuclear complex](http://purl.obolibrary.org/obo/UBERON_0002692)' instead.

Of note, if the above is true, that is, if _inferior raphe nucleus_ is not the same thing as _dorsal raphe nucleus_, then there is an also a similar error in GO: '[inferior raphe nucleus development](http://purl.obolibrary.org/obo/GO_0021724)' is said to '[results in development of](http://purl.obolibrary.org/obo/RO_0002296) the '[dorsal raphe nucleus](http://purl.obolibrary.org/obo/UBERON_0002043)'.

**Comment by gouttegd** [comment]
@AvolaAmg If you could have a look at this issue and tell me whether I am completely wrong, that’d be much appreciated. :)

**Comment by cmungall** [comment]
Some background here:

- https://github.com/geneontology/go-ontology/issues/8509

Although this doesn't really explain what I think is overzealous lumping. I think either a split or simply dropping the xrefs is warranted here
