### ISSUE TITLE
bronchus should be part of lung as well as part of tracheobronchial tree

### ISSUE THREAD

**Issue by dosumis** [obophenotype/uberon#3410]
**Uberon term**

rdfs:label "bronchus"
id "UBERON:0002185"
definition "The upper conducting airways of the lung; these airways arise from the terminus of the trachea."

**Suggested revision of logical definition**

add 
SubClassOf part_of some lung

**Comment by uberon** [comment]
Yes the definition shoukd be updated )IMO it doesn’t say it’s part of the
lung it’s just vague )

Asserting overlaps is often an anti-pattern (and most users don’t use
anyway). It’s usually better to have more comprehensive has parts
(carefully as this is where a lot of taxon variance comes in) and infer the
overlaps
