### ISSUE TITLE
Revise textual definition & add synonyms: mesosalpinx to include fallopian tube

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/uberon#3411]
**Uberon term**
mesosalpinx UBERON:0012331 http://purl.obolibrary.org/obo/UBERON_0012331

**Definition (free text, please give PubMed ID)**
https://en.wikipedia.org/wiki/Mesosalpinx

https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/mesosalpinx

Craig ME, Sudanagunta S, Billow M. Anatomy, Abdomen and Pelvis: Broad Ligaments. 2023 Jul 24. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2024 Jan–. PMID: 29763118.

**Suggested revision of textual definition**
Current Uberon definition: The mesosalpinx is part of the lining of the abdominal cavity in higher vertebrates, specifically the portion of the broad ligament that stretches from the uterine tube to the level of the ovary.

Modified definition to support additional NTRs for fallopian tube layers: Bolded words are added to definition.
The mesosalpinx is part of the **peritoneal** lining of the abdominal cavity in higher vertebrates, specifically the portion of the broad ligament that stretches from the **fallopian tube** (uterine tube) to the ovary. **It is made up of epithelial cells of mesothelium and a mesh of serous membrane lining.**

**synonyms**
serous layer of the fallopian tube

**notes**
serosa of fallopian tube UBERON:0012499 http://purl.obolibrary.org/obo/UBERON_0012499 exists already in Uberon; I feel like these are referring to the same structure?

**figure**
Figure source: Craig ME, Sudanagunta S, Billow M. Anatomy, Abdomen and Pelvis: Broad Ligaments. 2023 Jul 24. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2024 Jan–. PMID: 29763118.

![uterusLigaments](https://github.com/user-attachments/assets/0bfd5459-8c39-4453-8716-28fcc2f88a19)

**Your nano-attribution (ORCID)**
0000-0001-7655-4833

**Comment by aleixpuigb** [comment]
> serosa of fallopian tube UBERON:0012499 http://purl.obolibrary.org/obo/UBERON_0012499 exists already in Uberon; I feel like these are referring to the same structure?

Indeed it looks like the same structure in humans. However, mesosalpinx should be a general term for all mammals. I will add a Subclass relationship.

**Comment by cmungall** [comment]
I agree that different terminology is not sufficient reason for a different class. But the challenge is that different relationships may hold for taxonomically restricted structures. But we could be using taxon-GCIs more frequently here.
