### ISSUE TITLE
bug for stage merging in last composite-metazoan

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#521]
Hi Chris,

even if xref are present for stages in Uberon, no merge applied.
example for both xref and original class:

Line 140100: id: HsapDv:0000001
Line 154855: xref: HsapDv:0000001

Thank you

Anne

**Comment by cmungall** [comment]
Apologies but I just realized the heart associated veins issue is back in the 2015-01-01 release. I will check this out...
