### ISSUE TITLE
Non-simple property used in a cardinality restriction

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#541]
multi cell component structure SubClassOf (overlaps min 2 cell)

is invalid because 'overlaps' has transitive subproperties.

HermiT reports:
Non-simple property 'http://purl.obolibrary.org/obo/RO_0002131' or its inverse appears in the cardinality restriction 'ObjectMinCardinality(2 http://purl.obolibrary.org/obo/RO_0002131 http://purl.obolibrary.org/obo/GO_0005623)'

Using http://purl.obolibrary.org/obo/uberon/releases/2014-07-15/ext.owl

**Comment by cmungall** [comment]
OK, am closing this for now.

We should do a `robot validate-profile -p DL -i ONT` over ALL ontologies. Will make an ODK ticket.
