### ISSUE TITLE
tooth abbreviations

### ISSUE THREAD

**Issue by wdahdul** [obophenotype/uberon#559]
Please add the following abbreviations for various individual teeth:
Lp1, lower premolar 1
Lp2, lower premolar 2
p1, premolar 1
UdP5, upper  deciduous premolar 5
LdP5, lower deciduous premolar 5
UM1, upper molar 1
UI2, upper lateral secondary incisor tooth
Lm3, lower molar 3

**Comment by megbalk** [comment]
I've added abbreviations for what we use in non-human anatomy: we use the letter (e.g., p in premolar) to denote if it is upper or lower (P for upper, p for lower) not "U" or "L"
