### ISSUE TITLE
ZFS:0000049 segmentation

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#563]
Hi Chris,

ZFS:0000049 segmentation could have 
relationship: part_of UBERON:0000068 ! embryo stage

,
I guess, looking at ZFS development here 
http://zfin.org/zf_info/zfbook/stages/

There is no 'embryo stage' currently in ZFS (something I will soon start to discuss with them through 
https://code.google.com/p/developmental-stage-ontologies/issues/list)

BTW: who manages the 'bridge-to-uberon' file for ZFS?
Sorry if misposted!

Anne

**Comment by fbastian** [comment]
We now directly manage such relations at integration into Bgee.
