### ISSUE TITLE
new terms request: for Porifera and Cnidaria

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#578]
Hi Chris,

http://www.ncbi.nlm.nih.gov/pubmed/24844197

"Thus, while sponges contain only a limited number of direct orthologues of genes involved in body plan patterning in the eumetazoans, all of them are expressed in patterns supporting Haeckel’s view that body plans of sponges and cnidarians are homologous: choanoderm corresponds to the gastrodermis and osculum to the mouth of the polyp. Clearly, the described expression patterns of the developmental regulatory genes, while highly suggestive, do not prove homology of the body plans. Rather, they provide the necessary first step and a framework for studies aimed at determining the regulatory networks governing development of sponges. Once established, these networks can be further compared with developmental regulatory networks in other animals and provide insights into the molecular mechanisms underlying diversification of animal body plans."

so maybe worth to have the following new terms?

*(sponge) choanoderm
*(sponge) osculum
*(cnidaria) gastrodermis

see also 
ISBN:978-0030259821 "Ruppert EE, Fox RS, Barnes RD, Invertebrate zoology: a functional evolutionary approach (2003)
pages 78-79 for Porifera
page 100 'gastrodermis' in eumetazoa

Comments?
Cheers,

Anne

**Comment by ANiknejad** [comment]
Hi Chris,

I would appreciate to have 'gastrodermis' as a synonym of 
UBERON:0003929
name: gut epithelium

As you proposed, UBERON:0003929 can be renamed 'digestive tract epithelium'

Cheers,

Anne

**Comment by cmungall** [comment]
are we good to close this now?

**Comment by ANiknejad** [comment]
yes, thank you Chris!
