### ISSUE TITLE
New term request: 'proximal musculature of limb'

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/uberon#579]
New term request:
'proximal musculature of limb'

Needed for logical definition in HP for term: Proximal limb muscle stiffness
Proposed logical definition:
has_part some (inflexible and ('inheres in' some 'proximal musculature of limb'))

**Comment by nicolevasilevsky** [comment]
see doc, tab HP Anon terms:
https://docs.google.com/spreadsheets/d/1z2e3J_R1e7WgvdZi1la39HBbBwzBK2pZDQTsxdScW4M/edit#gid=1796408997

**Comment by cmungall** [comment]
See my comments on your other PR. This HPO class has no text def. Make one first. Only then do we know what the filler should be

Also remember the golden rule **not every HPO class needs to have a logical definition**

This ticket stems from 2014 when we were still over-stating logical definitions.

**Comment by nicolevasilevsky** [comment]
Closing, we decided we no longer need this term.
