### ISSUE TITLE
New term request: proximal tibia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/uberon#580]
New term request: proximal tibia

Needed for logical definition of HP term: Proximal tibial hypopolasia
Proposed new logical definition:
has_part some (hypoplastic and ('inheres in' some 'proximal tibia'))

**Comment by nicolevasilevsky** [comment]
see doc, HP Anon terms tab:
https://docs.google.com/spreadsheets/d/1z2e3J_R1e7WgvdZi1la39HBbBwzBK2pZDQTsxdScW4M/edit#gid=1796408997

**Comment by cmungall** [comment]
This doesn't make any sense. There is no proximal tibia. The HP class refers to the proximal part of the tibia

**Comment by cmungall** [comment]
The first thing to do before making an uberon term for an HPO logical definition is to check what the HPO text definition is. If there is no text definition, stop what you are doing and resolve this. In this case there is no HPO text definition so we don't even know what it is that should fill the slot in the logical definition

**Comment by cmungall** [comment]
note in uberon we have precise terms eg proximal epiphysis of tibia. but I expect the HPO phenotype also affects metaphysis and diaphysis. but we need to check. Can you open an issue @nicolevasilevsky

**Comment by megbalk** [comment]
@cmungall you beat me to what I was going to say.

**Comment by nicolevasilevsky** [comment]
based on comments on #2000, we don't want to axiomatize the HPO terms. Closing this ticket.
