### ISSUE TITLE
Request class "Scapular muscles"

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#597]
Scapular muscles
   ('muscle organ'
    and (has_part some 'infraspinatus muscle')
    and (has_part some 'teres major muscle')
    and (has_part some 'supraspinatus muscle')
    and (has_part some 'levator scapulae muscle')
    and (has_part some 'teres minor muscle’))

**Comment by cmungall** [comment]
Discussion has moved to #614

**Comment by RDruzinsky** [comment]
Sorry I missed this. I do like this construction for scapular muscle and I
think we should follow this in similar situations.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky
