### ISSUE TITLE
Request "upper central primary incisor tooth"

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#602]
I couldn't find this class. Probably should be defined as:
'incisor tooth' and (part_of some 'upper jaw region') and (part_of some 'primary dentition') and (in_central_side_of some 'incisor region of dentition')

**Comment by RDruzinsky** [comment]
I would be interested in doing this, but it will take time. Also, the
homologies are different in different mammalian taxonomic groups, so it's
complicated.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky
