### ISSUE TITLE
missing 'part_of' relation between UBERON:2001586 pectoral fin radial bone and UBERON:4440009 pectoral fin radial skeleton

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#638]
Currently only
UBERON:2101586 pectoral fin radial element
has the relation
part_of UBERON:4440009 ! pectoral fin radial skeleton

UBERON:2001586 pectoral fin radial bone
has no part_of relation

**Comment by cmungall** [comment]
http://purl.obolibrary.org/obo/UBERON_2001586

The general pattern is:

 bone is_a element part_of skeleton

       po UBERON:0004710 ! pectoral appendage
        is_a UBERON:0000151 ! pectoral fin
         po UBERON:0010710 ! pectoral fin skeleton
          po UBERON:4440009 ! pectoral fin radial skeleton
           po UBERON:2101586 ! pectoral fin radial element
            is_a UBERON:2001586 ! pectoral fin radial bone ***

**Comment by cmungall** [comment]
See also: https://github.com/obophenotype/uberon/wiki/Modeling-endochondral-elements-Design-Pattern
