### ISSUE TITLE
new terms request: juvenile stage

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#645]
https://github.com/obophenotype/uberon/issues/576

Def:  The stage of being no more dependent from nest and /or from caregivers for subsistence while having not reach sexual maturity.  

relationship: part_of UBERON: 0000112 {gci_filler="NCBITaxon: 40674", gci_relation="part_of"} ! sexually immature stage
relationship: preceded_by UBERON: 0007221 {gci_filler="NCBITaxon: amphibia, sauropsida, etc…", gci_relation="part_of"} ! neonate stage
relationship: immediately_preceded_by UBERON:xxx {gci_filler="NCBITaxon: 40674", gci_relation="part_of"} ! infant stage

**Comment by ANiknejad** [comment]
this would involve to remove 
synonym: "juvenile stage" EXACT [XAO:1000010]
from UBERON:0000112 sexually immature stage

so we would have in details:

- sexually immature stage
-- nursing (mammals)
--- neonate (mammals: part_of nursing stage, others: part_of sexually immature stage)
--- infant stage (mammals: part_of nursing stage)
-- juvenile stage (preceded by infant stage and neonate in mammals, preceded by neonate stage in others)

What do you think, Chris? Sounds ok?
Many thanks for the help
Anne

**Comment by cmungall** [comment]
When does juvenile stage start? (scoping for metazoa)
