### ISSUE TITLE
Incorrect GCI relations generating cycles

### ISSUE THREAD

**Issue by fbastian** [obophenotype/uberon#651]
The following GCI relations seem incorrect, and generate cycles: 

```
[Term]
id: UBERON:0000074
name: renal glomerulus
is_a: UBERON:0005325 {gci_filler="NCBITaxon:7954", gci_relation="part_of"} ! mesonephric glomerulus

[Term]
id: UBERON:0000045
name: ganglion
is_a: UBERON:0003338 {gci_filler="NCBITaxon:8353", gci_relation="part_of"} ! ganglion of peripheral nervous system
is_a: UBERON:0003338 {gci_filler="NCBITaxon:7954", gci_relation="part_of"} ! ganglion of peripheral nervous system

[Term]
id: UBERON:0000955
name: brain
is_a: UBERON:0008823 {gci_filler="NCBITaxon:10090", gci_relation="part_of"} ! neural tube derived brain
is_a: UBERON:0008823 {gci_filler="NCBITaxon:7954", gci_relation="part_of"} ! neural tube derived brain
is_a: UBERON:0008823 {gci_filler="NCBITaxon:8353", gci_relation="part_of"} ! neural tube derived brain

[Term]
id: UBERON:0001232
name: collecting duct of renal tubule
is_a: UBERON:0005319 {gci_filler="NCBITaxon:7954", gci_relation="part_of"} ! mesonephric collecting duct

[Term]
id: UBERON:0001285
name: nephron
is_a: UBERON:0005322 {gci_filler="NCBITaxon:7954", gci_relation="part_of"} ! mesonephric nephron

[Term]
id: UBERON:0002329
name: somite
is_a: UBERON:0005598 {gci_filler="NCBITaxon:7954", gci_relation="part_of"} ! trunk somite

[Term]
id: UBERON:0004198
name: comma-shaped body
is_a: UBERON:0005328 {gci_filler="NCBITaxon:7954", gci_relation="part_of"} ! mesonephric comma-shaped body

[Term]
id: UBERON:0004199
name: S-shaped body
is_a: UBERON:0005332 {gci_filler="NCBITaxon:7954", gci_relation="part_of"} ! mesonephric S-shaped body

[Term]
id: UBERON:0004212
name: glomerular capillary
is_a: UBERON:0006183 {gci_filler="NCBITaxon:7954", gci_relation="part_of"} ! mesonephric glomerular capillary
```

**Comment by fbastian** [comment]
Note that these relations are not always present in the species-specific ontology, e.g. UBERON:0000074 is_a UBERON:0005325 is not present in zfa.

**Comment by cmungall** [comment]
These are actually all intended, and used in cases where the levels of the hierarchy make distinctions across taxa but are meaningless within: all somites in fish are trunk somites. 

I'm not sure of the validity of the renal ones - it looks like the intent was to say all nephrons in fish are mesonephric nephrons - but could they not also be pronephric?

Technically a cycle with subclass is not a problem, say `a` and `b` are taxon-specific subclasses of the uberon classes above, if `a ⊆ b` and `b ⊆ a` then `b=a`, which is the intent here. But I can see how this would be problematic for your workflow. If this is the sum total of problematic GCIs then we can just get rid of them at least for the main release

**Comment by fbastian** [comment]
Hmm, interesting. Is this documented somewhere?

Don't remove them, I think I can quite easily filter them. I'm trying to find a better use than simply removing them.

**Comment by fbastian** [comment]
I note here the new cycles I identified related to this issue, to make sure they are correct, and for reference for future updates of Bgee (it was very helpful for me to retrieve this issue): 

```
Cycle: 
UBERON:0002437 "cerebral hemisphere white matter" - 
UBERON:0011299 "white matter of telencephalon" - 
UBERON:0019261 "white matter of forebrain" - 
UBERON:0003544 "brain white matter" - 
UBERON:0003544 "brain white matter" - 
UBERON:0002316 "white matter" - 
UBERON:0002437 "cerebral hemisphere white matter"

[Term]
id: UBERON:0002316
name: white matter
is_a: UBERON:0002437 {gci_relation="part_of", gci_filler="NCBITaxon:9443"} ! cerebral hemisphere white matter


Cycle : 
UBERON:0002371 "bone marrow" - 
UBERON:0012429 "hemopoietic tissue" - 
UBERON:0002371 "bone marrow"

[Term]
id: UBERON:0012429
name: hemopoietic tissue
relationship: part_of UBERON:0002371 {gci_relation="part_of", gci_filler="NCBITaxon:9606", source="FMA"} ! bone marrow


Cycle: 
UBERON:2005073 "atrioventricular ring" - 
UBERON:2005072 "endocardial ring" - 
UBERON:2005073 "atrioventricular ring"

[Term]
id: UBERON:2005072
name: endocardial ring
relationship: part_of UBERON:2005073 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! atrioventricular ring
```

**Comment by cmungall** [comment]
On 30 Nov 2016, at 9:36, fbastian wrote:

> I note here the new cycles I identified related to this issue, to make 
> sure they are correct, and for reference for future updates of Bgee 
> (it was very helpful for me to retrieve this issue):
>
> ```
> Cycle:
> UBERON:0002437 "cerebral hemisphere white matter" -
> UBERON:0011299 "white matter of telencephalon" -
> UBERON:0019261 "white matter of forebrain" -
> UBERON:0003544 "brain white matter" -
> UBERON:0003544 "brain white matter" -
> UBERON:0002316 "white matter" -
> UBERON:0002437 "cerebral hemisphere white matter"
>
> [Term]
> id: UBERON:0002316
> name: white matter
> is_a: UBERON:0002437 {gci_relation="part_of", 
> gci_filler="NCBITaxon:9443"} ! cerebral hemisphere white matter

This is obviously wrong. It says all white matter in primates is found 
in the cerebral hemisphere.

The source is the Allen primate brain atlas:

  / PBA:3999 ! brain
   po PBA:128011350 ! telencephalon
    po PBA:128011354 ! cerebral cortex
     po PBA:294021746 ! neocortex
      po PBA:294022044 ! white matter ***
       po PBA:10007 ! white matter of rostral cingulate cortex
       po PBA:10016 ! white matter of medial orbitofrontal cortex
       po PBA:10025 ! white matter of caudal orbitofrontal cortex
       po PBA:10038 ! white matter of V1
       po PBA:10051 ! white matter of V2

It seems that the label for PBA:294022044 is deceptively broad, and it 
actually means neocortex white matter.

I will fix this, but the larger issue is whether to continue with this 
strategy for using external AOs for phylogenetic GCIs. We can revisit 
the strategy of doing a one-off dump and then curating.


> Cycle :
> UBERON:0002371 "bone marrow" -
> UBERON:0012429 "hemopoietic tissue" -
> UBERON:0002371 "bone marrow"
>
> [Term]
> id: UBERON:0012429
> name: hemopoietic tissue
> relationship: part_of UBERON:0002371 {gci_relation="part_of", 
> gci_filler="NCBITaxon:9606", source="FMA"} ! bone marrow

Here we are saying that in humans all hemopoietic tissue is found in the 
bone marrow. I think this is correct.

The problem is that bone marrow is itself classified at HT. I think HT 
has too broad an OWL def:

```
intersection_of: UBERON:0000479 ! tissue
intersection_of: contains_process GO:0030097 ! hemopoiesis
```

>
> Cycle:
> UBERON:2005073 "atrioventricular ring" -
> UBERON:2005072 "endocardial ring" -
> UBERON:2005073 "atrioventricular ring"
>
> [Term]
> id: UBERON:2005072
> name: endocardial ring
> relationship: part_of UBERON:2005073 {gci_relation="part_of", 
> gci_filler="NCBITaxon:7954"} ! atrioventricular ring
> ```

will look at this one later

**Comment by fbastian** [comment]
New ones:

```
[Term]
id: UBERON:0001083
name: myocardium of ventricle
is_a: UBERON:0018649 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! cardiac muscle tissue of ventricle

[Term]
id: UBERON:0002302
name: myocardium of atrium
is_a: UBERON:0004490 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! cardiac muscle tissue of atrium

[Term]
id: UBERON:0002343
name: abdomen musculature
is_a: UBERON:0002378 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! muscle of abdomen

[Term]
id: UBERON:0011362
name: cranial blood vasculature
is_a: UBERON:0003496 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! head blood vessel

[Term]
id: CL:0000103
name: bipolar neuron
is_a: CL:0000748 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! retinal bipolar neuron

[Term]
id: CL:0000287
name: eye photoreceptor cell
is_a: CL:0010009 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! camera-type eye photoreceptor cell

[Term]
id: CL:0000653
name: glomerular visceral epithelial cell
is_a: CL:0002523 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! mesonephric glomerular visceral epithelial cell
```

**Comment by cmungall** [comment]
1+2: I think these are OK?

3+4: there is a general issue here that uberon follows fma in making precise divisions between elements + stuff (e.g. vessels/muscles vs vasculature/musculature). other ontologies are a bit looser. This results in oddities like this. I'm afraid I don't have an immediate fix. It's not clear we want to keep the shadows in uberon long term; we may prefer to just keep the elements and add a special synonym for the mass form.

last 3: these are all formally correct, but it would be more straightforward if we simply merged these in the composite file

**Comment by fbastian** [comment]
No problem, I report them all here for our pipeline, we can't accept cycles in Bgee for now. Other ones:

```
[Term]
id: UBERON:0000474
name: female reproductive system
is_a: UBERON:0000992 {gci_relation="part_of", gci_filler="NCBITaxon:6237"} ! ovary

[Term]
id: UBERON:0000079
name: male reproductive system
is_a: UBERON:0000473 {gci_relation="part_of", gci_filler="NCBITaxon:6237"} ! testis

[Term]
id: UBERON:0006337
name: distal early tubule
is_a: UBERON:0007308 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! pronephric distal early tubule

[Term]
id: UBERON:0001705
name: nail
is_a: UBERON:0009567 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! nail of pedal digit

[Term]
id: UBERON:0002481
name: bone tissue
is_a: UBERON:4000115 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! mineralized bone tissue

[Term]
id: UBERON:0002099
name: cardiac septum
is_a: UBERON:0004142 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! outflow tract septum
```

**Comment by fbastian** [comment]
Also, we have
```
[Term]
id: UBERON:0001135
name: smooth muscle tissue
is_a: WBbt:0005780 {gci_relation="part_of", gci_filler="NCBITaxon:6237"} ! non-striated muscle (C elegans)
```
While I think WBbt:0005780 should be is_a UBERON:0001135. The current relation seems incorrect:
```
[Term]
id: WBbt:0005780
name: non-striated muscle (C elegans)
is_a: CL:0000187 ! muscle cell
```

**Comment by uberon** [comment]
On Sat, Mar 27, 2021 at 7:26 AM fbastian ***@***.***> wrote:

> No problem, I report them all here for our pipeline, we can't accept
> cycles in Bgee for now. Other ones:
>
> [Term]
> id: UBERON:0000474
> name: female reproductive system
> is_a: UBERON:0000992 {gci_relation="part_of", gci_filler="NCBITaxon:6237"} ! ovary
>
> [Term]
> id: UBERON:0000079
> name: male reproductive system
> is_a: UBERON:0000473 {gci_relation="part_of", gci_filler="NCBITaxon:6237"} ! testis
>
>
WBbt mappings will fix

>
>
> [Term]
> id: UBERON:0006337
> name: distal early tubule
> is_a: UBERON:0007308 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! pronephric distal early tubule
>
>
formally correct, these are equivalent in frogs (which don't progress
beyond pronephros, AFAICR)


>
> [Term]
> id: UBERON:0001705
> name: nail
> is_a: UBERON:0009567 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! nail of pedal digit
>
>
will fix


>
> [Term]
> id: UBERON:0002481
> name: bone tissue
> is_a: UBERON:4000115 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! mineralized bone tissue
>
>
I think we need to merge the ext edit file in first then fix this, Nico is
on it

it's not clear why this subclass was added for ext in the first place

>
>
> [Term]
> id: UBERON:0002099
> name: cardiac septum
> is_a: UBERON:0004142 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! outflow tract septum
>
>
fixed in PR

**Comment by shawntanzk** [comment]
> [Term]
 id: UBERON:0002481
 name: bone tissue
 is_a: UBERON:4000115 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! mineralized bone tissue

>I think we need to merge the ext edit file in first then fix this, Nico is
on it

it's not clear why this subclass was added for ext in the first place

Tech call:
Phenoscape external were merged into uberon-edit a long time ago, don't see anymore external axioms to merge into file, what other file needs to be added to edit file?

**Comment by cmungall** [comment]
Can someone summarize where w are with this? Can we close this?

**Comment by shawntanzk** [comment]
Hi @cmungall - I think the tech team was a bit confused as to what needs to be done here? 
The GCI doesn't seem to be in uberon-edit file so if nothing else needs to be done we can close it? Thanks
