### ISSUE TITLE
Repair term "bile duct epithelium" text definition,xrefs and NTR for "epithelium of biliary tree"

### ISSUE THREAD

**Issue by cindyJax** [obophenotype/uberon#653]
Current text definition for 'bile duct epithelium" [http://purl.obolibrary.org/obo/UBERON_0004820] refers to both the bile duct epithelia and the gall bladder epithelium.  Primary reference is to BTO:0001513 [= biliary epithelium].  However, "epithelium of gall bladder" has its own class [http://purl.obolibrary.org/obo/UBERON_0002029].  Bile duct epithelium should not include gall baldder epithelium in the text and the correct BTO cross reference should be to BTO:0000417[ = bile duct epithelium]

A superclass for "biliary epithelium" or "epithelium of biliary tree" may be considered- this would then include both the bile duct epithelium (intrahepatic and extrahepatic) and gall bladder epithelium, using the current definition for "bile duct epithelium". Be reminded of taxa constraints; many mammalian species do not have a gallbladder (rat, horse, deer etc...)

Reference:
Functional anatomy of normal bile ducts.
Strazzabosco M, Fabris L.
Anat Rec (Hoboken). 2008 Jun;291(6):653-60. doi: 10.1002/ar.20664. Review.
PMID:18484611
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3743051/

Bile formation and secretion.
Boyer JL.
Compr Physiol. 2013 Jul;3(3):1035-78. doi: 10.1002/cphy.c120027. Review.
PMID:23897680
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4091928/

**Comment by cmungall** [comment]
FMA draws a distinction between the biliary tree (network of biliary ducts) and more generally the biliary system (which it also calls the biliary tract).

The 'biliary tree epithelium' would then be trvially the same as 'bile duct epithelium' (the tree contains the bile ducts - the cystic duct, intrahepatic and extrahepatic bile ducts). This means the commit I just made is on the wrong track. The wider grouping would be 'biliary system epithelium' (including the gallbladder)
