### ISSUE TITLE
granulosa cell(CL:0000501) A supporting cell for the developing female gamete in the ovary of mammals.

### ISSUE THREAD

**Issue by michaelerice** [obophenotype/uberon#656]
Suggest "of mammals" be removed from the definition.

**Comment by cmungall** [comment]
Hi Michael, would you mind submitting this to:
https://code.google.com/p/cell-ontology/issues/list

I could easily do this for you if you like, but I'm a bit obsessive about having the proper attribution trail of who helped in what way, thanks!

Sorry for the tracker proliferation. Animal cells go in the cell ontology, animal gross anatomical structures in uberon (even though we are tightly allied and the cell ontology shows up as a module of uberon)

**Comment by cmungall** [comment]
https://code.google.com/p/cell-ontology/issues/detail?id=173

**Comment by michaelerice** [comment]
Chris,

Sorry somehow I missed your email asking me to submit to the cell-ontology issues, and it looks like you have fixed it already. Is that correct? Thanks

Mike
________________________________
Michael E. Rice AgBase biocurator
School of Animal and Comparative Biomedical Science
Thomas W. Keating Bioresearch Building
1657 E. Helen St.
Tucson, AZ 85721
The College of Agriculture and Life Sciences
The University of Arizona
520 955-2745
mrice@email.arizona.edu<http://mrice@email.arizona.edu>
________________________________
