### ISSUE TITLE
to review the definition of UBERON:0000100 blastopore

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#660]
Hi Chris,

some interesting papers talk about the no more accurate use of gastrulation site to define protostomes and deuterostomes
http://www.ncbi.nlm.nih.gov/pubmed/?term=23305667
"in protostomes the site of gastrulation (i.e., position of endoderm formation) rarely ever becomes the mouth, although differential growth often displaces vegetal tissue towards the oral opening. These data indicate that endodermal tissue originates from the vegetal pole in both protostomes and deuterostomes and that the mouth bears no conserved relationship to the site of gastrulation.It is tempting to speculate that this may be due to the wide range of modes of gastrulation observed in the protostomes and the conserved persistence of the blastopore in deuterostomes as a constraint of epithelial invagination."
original paper http://www.ncbi.nlm.nih.gov/pubmed/23103190

New definition could be:

"the orifice of invagination of the endomesodermal cells during the embryonic stages of an organism"

based on the current Uberon definition and a sentence found in:
http://www.sciencedirect.com/science/article/pii/S0960982212011396
(The division of bilaterally symmetric animals (Bilateria) into the Protostomia and the Deuterostomia [6] was traditionally based on the fate of the blastopore [7], which is the orifice of invagination of the endomesodermal cells [8].)

Thank you.

Anne

**Comment by cmungall** [comment]
This paper looks fascinating, will try and read later.

I like the suggestion, will implement. What do you think of the existing relationship to archenteron?

**Comment by ANiknejad** [comment]
I guess, blastopore part_of archenteron is still fine, it is the opening of the archenteron to the exterior.
In the same way, UBERON:0000166 oral opening
def: "The orifice that connects the mouth to the exterior of the body."
has the relationship
part_of UBERON:0000165 ! mouth 

Thank you Chris
