### ISSUE TITLE
UBERON:0008258 oral surface: tentative definition and relation to UBERON:0000165 mouth?

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#661]
id: UBERON:0008258
name: oral surface
namespace: uberon
synonym: "actinal side" EXACT []
synonym: "actinal surface" EXACT []
is_a: UBERON:0000475 ! organism subdivision
relationship: only_in_taxon NCBITaxon:6072 ! Eumetazoa
relationship: present_in_taxon NCBITaxon:6073 ! Cnidaria

Definition could be:

"Pertaining to the side or surface around the mouth in an animal that has radial symmetry such as a starfish.[http://en.wiktionary.org/wiki/actinal].
In Cnidaria, concave under surface of the bell (umbrella) that is called subumbrella and where the mouth is located [adapted from ISBN:978-1449648916 "Springer J, Holley D, An Introduction to Zoology: Investigating the Animal World (2012) p.142"]

So, 'subumbrella' as synonym, and also should be useful to have a relation to UBERON:0000165 mouth (has_part?)

**Comment by cmungall** [comment]
Are you sure the def is correct? it's just not around the mouth - even the tips of each of the 5 appendages of a starfish have an oral surface and an aboral surface, no?

We have been putting surfaces in BSPO
http://purl.obolibrary.org/obo/BSPO_0000378

We should add 'oral surface' there.

Note that in BSPO and Uberon, surfaces are immaterial. This means genes can't be expressed there. And the only parts it would have would be immaterial. So the oral surface of a starfish would have as a part (debatably) 2D lumen of oral opening. You might be thinking at this point this isn't what you really want...

Maybe you want something like this:

 * [UBERON:0010000](http://purl.obolibrary.org/obo/UBERON_0010000) ! multicellular anatomical structure
    * [UBERON:0000475](http://purl.obolibrary.org/obo/UBERON_0000475) ! organism subdivision
        * [UBERON:0001137](http://purl.obolibrary.org/obo/UBERON_0001137) ! dorsum  

So 'oral side subdivision' would be the upward of the two divisions of the starfish when you slice it lengthwise. Somehat analogous to a [ventrum](http://purl.obolibrary.org/obo/UBERON_0013235] of a morphologically bilaterian animal.

From here there could be layered divisions, such as 'oral side integument'. This might be a better place for the label 'subumbrella'.  Should this end at the oral boundary, or continue into the mouth... as far as the pharynx?

Is this for homology or expression curation?

**Comment by cmungall** [comment]
We do have 'sides' in BSPO that are structures

 * [BSPO:0000054](http://purl.obolibrary.org/obo/BSPO_0000054) ! anatomical side  
      * [BSPO:0000000](http://purl.obolibrary.org/obo/BSPO_0000000) ! left side  
      * [BSPO:0000001](http://purl.obolibrary.org/obo/BSPO_0000001) ! upper side  
      * [BSPO:0000002](http://purl.obolibrary.org/obo/BSPO_0000002) ! lower side  
      * [BSPO:0000003](http://purl.obolibrary.org/obo/BSPO_0000003) ! deep side  
      * [BSPO:0000004](http://purl.obolibrary.org/obo/BSPO_0000004) ! superficial side  
      * [BSPO:0000007](http://purl.obolibrary.org/obo/BSPO_0000007) ! right side  
      * [BSPO:0000022](http://purl.obolibrary.org/obo/BSPO_0000022) ! superior side  
      * [BSPO:0000025](http://purl.obolibrary.org/obo/BSPO_0000025) ! inferior side  
      * [BSPO:0000055](http://purl.obolibrary.org/obo/BSPO_0000055) ! anterior side  
      * [BSPO:0000056](http://purl.obolibrary.org/obo/BSPO_0000056) ! posterior side  
      * [BSPO:0000057](http://purl.obolibrary.org/obo/BSPO_0000057) ! apical side  
      * [BSPO:0000058](http://purl.obolibrary.org/obo/BSPO_0000058) ! basal side  
      * [BSPO:0000059](http://purl.obolibrary.org/obo/BSPO_0000059) ! central side  
      * [BSPO:0000060](http://purl.obolibrary.org/obo/BSPO_0000060) ! contralateral side  
      * [BSPO:0000061](http://purl.obolibrary.org/obo/BSPO_0000061) ! proximal side  
      * [BSPO:0000062](http://purl.obolibrary.org/obo/BSPO_0000062) ! distal side  
      * [BSPO:0000063](http://purl.obolibrary.org/obo/BSPO_0000063) ! dorsal side  
      * [BSPO:0000065](http://purl.obolibrary.org/obo/BSPO_0000065) ! ipsilateral side  
      * [BSPO:0000066](http://purl.obolibrary.org/obo/BSPO_0000066) ! lateral side  
      * [BSPO:0000067](http://purl.obolibrary.org/obo/BSPO_0000067) ! medial side  
      * [BSPO:0000068](http://purl.obolibrary.org/obo/BSPO_0000068) ! ventral side  
      * [BSPO:0000129](http://purl.obolibrary.org/obo/BSPO_0000129) ! peripheral side  
      * [BSPO:0000130](http://purl.obolibrary.org/obo/BSPO_0000130) ! axial side  

I think the organism subdivisions are still appropriate for uberon though, especially layers of these, e.g. integument

**Comment by fbastian** [comment]
It's for homology curation. 'oral surface' evolved before a proper 'mouth', but currently, terms that could correspond are all 'part_of some mouth', which make them unsuitable.

**Comment by ANiknejad** [comment]
for homology purpose the use of 'mouth' for all animal that eats should be fine, I guess.
I was just confused by this sentence:
"...the homology of the oral opening of cnidarians and the mouth of bilaterians...."
and reviewing all the 'oral' classes in Uberon, 'oral surface' was the one having relationship:
present_in_taxon NCBITaxon:6073 ! Cnidaria
and I was wondering if 'oral opening' has to be considered as the mouth of cnidarians, but in fact, Cnidaria have a 'mouth' too

**Comment by ANiknejad** [comment]
>Note that in BSPO and Uberon, surfaces are immaterial.

yes, so I will do homology curation on 'mouth' only, also when talking about 'oral opening' because in fact 'oral opening' is just the opening that connects the mouth to the exterior (part_of mouth)

**Comment by cmungall** [comment]
Oh right, 'oral surface' is in there already, I thought this was for a new term. Let me review and get back to you... I think the existing term should be labeled clearly as a subdivision
