### ISSUE TITLE
Term request: Spinal canal at lumbar vertebra

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#669]
UBERON has classes:
- central canal of spinal cord
- vertebral canal

What I need is the part of the spinal canal at the level of the lumbar vertebra. Is that possible?

Sebastian

**Comment by drseb** [comment]
Sorry, is the class with label "lumbar spinal cord central canal" the answer here? It didn't show up on ontobee...

**Comment by cmungall** [comment]
https://github.com/ontoden/ontobee/issues/35#issuecomment-74310876

**Comment by RDruzinsky** [comment]
Is it necessary to create a class for this sort of thing? Could it not be
composed from other terms?

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by cmungall** [comment]
There's never a satisfactory answer to this. Some applications can't handle post-comp. It's actually not trivial to do for anything like this involving maximal extent. I bet you'd get about four different answers for how to compose this, some unsatisfiable. The uberon class is hopefully a single unambiguous reusable atomic unit that is ready packaged. In fact the equivalence axiom in uberon is a bit of a hack..
