### ISSUE TITLE
Term request: XXX upper central secondary incisor tooth

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#671]
I am kindly asking you to add the following UBERON terms in order to get rid of FMA references:

Right upper central secondary incisor tooth (FMA:55681)
Left upper central secondary incisor tooth (FMA:55682)

Thanks 
Sebastian

**Comment by cmungall** [comment]
I have an aversion to naming lateral skeletal elements.

I assume this is for
HP:0001566 ! Widely-spaced maxillary central incisors
which currently is defined as 'increased distance' and inheres in some 'left upper secondary incisor' and towards some 'right upper secondary incisor'.

This is weird and wrong, and will lead to both missing inferences and incorrect inferences.

I suggest adding a class 'inter-tooth gap' and subclasses. Then we can use a simple length quality measurement. This is similar to what is done for inter-pupil inter-nippple etc distances. Sound OK?

I also suggest weakening the marked syn below to BROAD
```
[Term]
id: HP:0001566
name: Widely-spaced maxillary central incisors
namespace: human_phenotype
alt_id: HP:0000669
alt_id: HP:0001570
alt_id: HP:0006300
alt_id: HP:0006324
def: "Increased distance between the `maxillary central permanent incisor tooth` (FMA:55722)." [HPO:ibailleulforestier]
***synonym: "Central incisor gap" EXACT []
synonym: "Diastasis of the central incisors" EXACT []
synonym: "Separated superior central incisors" EXACT []
synonym: "Wide gap between upper central incisors" EXACT []
synonym: "Wide upper central incisors" EXACT []
synonym: "Widely spaced upper incisors" EXACT []
xref: UMLS:C1835762
is_a: HP:0000699  ! Diastema
is_a: HP:0006304  ! Widely-spaced incisors
```

**Comment by drseb** [comment]
Please create a class "inter-tooth gap" and the herein required subclass.  

Can you let me know where the class for inter-nipple distance is located. I can't seem to find it!

I have changed the exact to broad synonym.

Thank you very much,
Sebastian

**Comment by cmungall** [comment]
* [UBERON:0013771](http://purl.obolibrary.org/obo/UBERON_0013771) ! intermammary line

I think the label should probably be more explicit this is between nipples
