### ISSUE TITLE
Term request: XXX optic axis

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#672]
I am kindly asking you to add the following UBERON terms in order to get rid of FMA references:

Right optic axis (FMA:58164)
Left optic axis (FMA:58165)

Thanks 
Sebastian

**Comment by drseb** [comment]
Please close, unless you want to think about creating an "alignment of X and Y" class. (Similar to the gaps and distances discussed here:https://github.com/obophenotype/uberon/issues/671 )
We need these class to express a misalignment between the left and right eye, e.g. in Strabismus.

Seb

**Comment by cmungall** [comment]
I think this can be done using [UBERON:0010222](http://purl.obolibrary.org/obo/UBERON_0010222) ! anatomical line between pupils

+ a quality such as misaligned

**Comment by drseb** [comment]
Ok thanks. Please have a look at https://code.google.com/p/phenotype-ontologies/issues/detail?id=123
