### ISSUE TITLE
Term request: Medial angle of XXX eye

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#673]
I am kindly asking you to add the following UBERON terms in order to get rid of FMA references:

Medial angle of right eye (FMA:59323)
Medial angle of left eye (FMA:59324)

Thanks 
Sebastian

**Comment by cmungall** [comment]
I take it this is for telecanthus, currently defined as distance & inheres-in some medial-angle-of-L-eye and towards some medial-angle-of-R-eye

A better way to express what this axiom is attempting to express is to use `distance` with:

[UBERON:0013678](http://purl.obolibrary.org/obo/UBERON_0013678) ! anatomical line between inner canthi

**Comment by drseb** [comment]
add def 

'has part' some 
('increased length' 
  and ('inheres in' some 'anatomical line between inner canthi') 
  and ('has modifier' some abnormal))


thanks
