### ISSUE TITLE
Term request: Longitudinal arch of foot

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#678]
We would like to remove the FMA reference to FMA:75030. If not present in UBERON could you create this class with label "Longitudinal arch of foot"

Thanks,
Sebastian

**Comment by cmungall** [comment]
you may want to fix the text/semi-formal def in HPO:

    def: "A foot where the `plantar arch` (FMA:43942) is in contact with the ground or floor when the individual is standing; or, in a patient lying supine, a foot where the arch is in contact with the surface of a flat board pressed against the sole of the foot by the examiner with a pressure similar to that expected from weight bearing; or, the height of the arch is reduced." [HPO:probinson, pmid:19125433]

the referenced FMA class is a branch of the plantar artery...

**Comment by drseb** [comment]
Thanks. I repaired the semi-formal-def.

Still the question remains: is it possible to create a class in UBERON for the longitudinal arch of foot or can you help with post composition?
