### ISSUE TITLE
Term request: Superficial vein

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#680]
We would like to remove references to FMA and use UBERON. Could you add (if not already present) a class for "Superficial vein". In FMA this has the ID FMA:76719.

Thanks,
Sebastian

**Comment by cmungall** [comment]
Any idea for a good differentia? So far we've been using PATO which is unsatisfactory. Grey's says "The superficial veins are placed immediately beneath the integument between the two layers of superficial fascia", i.e. located_in UBERON:0011818 ! superficial fascia

Can you add a def to
```
[Term]
id: HP:0001015
name: Prominent superficial veins
namespace: human_phenotype
xref: UMLS:C1837785
is_a: HP:0002624  ! Venous abnormality
is_a: HP:0007394  ! Prominent superficial blood vessels
```

**Comment by drseb** [comment]
Requested textual definition at https://sourceforge.net/p/obo/human-phenotype-requests/447/

Until now I moved the logical def to the comment annotation in hpo.

**Comment by drseb** [comment]
The textual definition is now: "A condition in which superficial veins (i.e., veins just under the skin) are more conspicuous or noticable than normal." An example can be found in Figure 4 of http://www.ncbi.nlm.nih.gov/pubmed/24456199.

So should I just use:
 - 'blood vessel' and ('part of' some 'skin of body')
  - vein and ('part of' some 'skin of body')
  - artery and ('part of' some 'skin of body')
for this and the related HPO terms? Or do you think "under the skin" is not 'part of skin'? But then keep in mind that this and related HPO classes are all subclasses of 'Vascular skin abnormalities'.

Note that there is a multitude of subclasses for vasculature, e.g. kidney vasculature, vasculature of liver, etc.
Maybe UBERON can have a thought about adding:
 - vasculature of skin
     - vein of skin
     - artery of skin

**Comment by cmungall** [comment]
added UBERON:0035550
