### ISSUE TITLE
Term request: Musculature of anterior abdominal wall

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#681]
If not already present in UBERON (I haven't found) please add a class labelled "Musculature of anterior abdominal wall". In FMA this has ID FMA:78435.

Best,
Sebastian

**Comment by cmungall** [comment]
I presume this is for 

```
     HP:0002933 ! Ventral hernia [DEF: "Ventral hernia refers to a condition in which abdominal contents protrude through a weakened portion of the abnominal wall."]
```

See comments for #683 

Why does the logical def for this one refer to musculature but the others don't?
