### ISSUE TITLE
Term request: Skin of palm proper

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#682]
Could you please add a class for "Skin of palm proper". In FMA this has ID FMA:79170. We want to remove references to FMA.

Best,
Sebastian

**Comment by cmungall** [comment]
Use [UBERON:0013777](http://purl.obolibrary.org/obo/UBERON_0013777) ! skin of palm of manus

Will add more syns to next release

I don't think you care about the 'proper'

**Comment by drseb** [comment]
Thanks. I updated the def.
