### ISSUE TITLE
Term request: Body of thoracic vertebra

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#684]
In order to remove all reference to FMA in HPO and use UBERON instead, we need a class labelled "Body of thoracic vertebra". In FMA this has ID FMA:9141. Is this in UBERON already (I couldn't find it). If not, could you add this please?

Best,
Sebastian

**Comment by cmungall** [comment]
For this one I concur with @RDruzinsky in #669 - let's just post-compose

Note that for endochrondral elements, uberon typically names a triad, so here we have

 * [UBERON:0016491](http://purl.obolibrary.org/obo/UBERON_0016491) ! vertebral centrum element
       * [UBERON:0001075](http://purl.obolibrary.org/obo/UBERON_0001075) ! bony vertebral centrum
       * [UBERON:0009291](http://purl.obolibrary.org/obo/UBERON_0009291) ! cartilaginous vertebral centrum

the naming is clumsy, but friendlier names may be ambiguous regarding whether we are talking about bone or uncommitted. Docs: https://github.com/obophenotype/uberon/wiki/Modeling-endochondral-elements-Design-Pattern

I assume this is the term
HP:0012792 ! Absent ossification of thoracic vertebral bodies

so this is an absence of

  go:ossification and occurs_in some ('vertebral centrum element' and part-of some 'thoracic region of vertebral column')

I think it makes sense to use the uncommitted state as it makes no sense to talk of absent ossification of a bone.

Alternately, it could be described using PATO:0001449 ! cartilaginous... either way we'll want to make sure the HPO hierarchy uses classes consistently

**Comment by drseb** [comment]
Ok. I used the suggested definition. 
It seems very unclear to me when UBERON decides to create a class for a user and when the user is forced to think of a post composition. Is there a clear guideline? 
IMHO not all users will know how to post compose properly and I am not sure how this helps with interoperability if users unintentionally decide for a different or even wrong post composition.

Thanks
Sebastian

**Comment by cmungall** [comment]
I think better tooling is required here

For now, just looking at existing subclasses of the genus is a good place to start
