### ISSUE TITLE
FBbt:00000123 amnioproctodeal invagination (Drosophila) and UBERON:0000931 proctodeum

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#685]
could these terms be merged?
comments?
@dosumis

**Comment by dosumis** [comment]
Hi @ANiknejad, please could you post to [FBbt on sourceforge](http://purl.obolibrary.org/obo/fbbt/tracker).  CC'ing in @mmc46 as she edits this now.  
Cheers,
David

**Comment by ANiknejad** [comment]
Hi David,

yes, sure, here the post now:
https://sourceforge.net/p/fbbtdv/tickets/52/

Cheers,

Anne

**Comment by mmc46** [comment]
Can we have FBbt:00000123 amnioproctodeal invagination as a xref into UBERON proctodeum, instead of FBbt:00000440 proctodeum?
