### ISSUE TITLE
Term request: Superclasses for "diastema between central incisors"

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#687]
Can you add general classes for "diastema between incisors", "diastema between teeth", "diastema between primary teeth", without the restriction on the central incisors.

I would need this for the definition of HPO classes such as "Widely-spaced incisors", "Abnormal spaced incisors", "Widely spaced teeth" etc.

Thanks,
Sebastian

This is related to: https://github.com/obophenotype/uberon/commit/3a05ee21e60e707392adc55c3692d7089367509e

**Comment by cmungall** [comment]
Ah, I thought I got all the ones required for HPO but missed the primary teeth one.

hierarchy seems a bit weird no?
```
         is_a HP:0000692 ! Misalignment of teeth [DEF: "Abnormal alignment, positioning, or spacing of the teeth, i.e., `misaligned` (PATO:0001654) `teeth` (FMA:12516)."]
          is_a HP:0000687 ! Widely spaced teeth ***  [DEF: "Increased spaces (diastemata) between most of the teeth in the same dental arch."]
           is_a HP:0006313 ! Widely spaced primary teeth [DEF: "Increased space between the primary teeth. Note this phenotype should be distinguished from increased space due purely to microdontia."]
          is_a HP:0000699 ! Diastema ***  [DEF: "Increased space between two adjacent teeth in the same dental arch."]
           is_a HP:0001566 ! Widely-spaced maxillary central incisors [DEF: "Increased distance between the `maxillary central permanent incisor tooth` (FMA:55722)."]
```

also feel free to re-open tickets

**Comment by RDruzinsky** [comment]
Calling a diastema a "misalignment" is a very human-centric approach.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

**Comment by drseb** [comment]
@cmungall  Yes, I start to work on this part now.

@RDruzinsky Might be true, but I guess you are referring to the HP-IDs posted before and these refer to the Human Phenotype Ontology. Do you agree that a diastema is a "misalignment of teeth" in humans?

**Comment by RDruzinsky** [comment]
@SKöhler I suppose that most dentists would call a diastema a misalignment
in humans.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky

On Tue, Apr 14, 2015 at 10:22 AM, Sebastian Köhler <notifications@github.com

**Comment by cmungall** [comment]
The uberon class has primary label 'diastema' and is intended to be neutral. We could call it 'interdental space' if less likely to conflict with HPO and it's value judgements.

btw, I use 'diastema' as singular and 'diastemata' as plural, but I have seen 'diastem' used before which sounded odd. Know the correct usage @RDruzinsky ?

**Comment by cmungall** [comment]
@drseb I think I see why HPO has the two branches now. 'Widely spaced teeth' is essentially a mereological sum of abnormal diastemata in a single quadrant, whereas 'Diastema' is a single abnormal diastema between exactly two teeth?

**Comment by RDruzinsky** [comment]
Diastema is the proper term and we should use it. It is a neutral term.

You are correct with regard to the singular and plural terms.

Robert E. Druzinsky, Ph.D.
Clinical Associate Professor
Dept. of Oral Biology
College of Dentistry
University of Illinois at Chicago
801 S. Paulina
Chicago, IL 60612
druzinsk@uic.edu

Office: 312-996-0406
Lab: 312-996-0629
Website: www.peerj.com/RobertDruzinsky
