### ISSUE TITLE
extra basihyal term

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#688]
Should this term be obsoleted?

http://purl.obolibrary.org/obo/UBERON_3000957

It doesn't seem to be related to the other basihyal element terms.

**Comment by wdahdul** [comment]
These may need to remain separate terms, based on whether they are paired or unpaired. 

The "extra" basihyal UBERON:3000957 came from AAO:
Def from AAO: Paired, anterior element that articulates medially with basibranchial I and posterolaterally with the paired hypohyals.

The triad basihyal terms came from ZFA/TAO and described an unpaired element (basihyal element UBERON:0011614, basihyal bone UBERON:0011618, basihyal cartilage UBERON:0011615)

**Comment by wdahdul** [comment]
This came up again, and I agree that we should obsolete. The definition and classification as 
 endochondral bone is problematic. According to Dave Blackburn, the basihyal is unpaired and cartilaginous in amphibians.

**Comment by wdahdul** [comment]
yes, i can address this

**Comment by wdahdul** [comment]
Obsoleted this term in ext.
