### ISSUE TITLE
new term request: collar nerve cord

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#692]
Please see this paper:
http://www.ncbi.nlm.nih.gov/pubmed/25903626

"Miyamoto and Wada found that the endoderm of the enteropneust stomochord and the roof of the buccal cavity are sources of Hedgehog signals that evidently induce and pattern the collar nerve cord. This parallels Hedgehog signalling from the notochord to the nascent neural tube during vertebrate development. Their data could be interpreted to mean that dorsoventral inversion did not take place during the enteropneust-to-vertebrate transition, that the stomochord is homologous to a notochord, and that the collar cord corresponds to at least part of the vertebrate CNS."

Tentative definition (from this paper):
A nerve tract found in marine worms that is located in the collar body region (three body regions in marine worms: proboscis, collar (extending into tentacle-fringed arms) and trunk)

Many thanks

Anne

**Comment by dosumis** [comment]
On 30 Apr 2015, at 08:17, ANiknejad <notifications@github.com> wrote:

> extending into tentacle-fringed arms

I'm jealous of any anatomy ontologist who gets to put that phrase in a definition.

**Comment by cmungall** [comment]
If someone wants to bud off a separate ambulacrarian module I'd be more than happy... I've been trying to persuade @balhoff to do the echiderms.

I was looking at some of the other papers in that Nature special issue. I think [nerve cord](http://purl.obolibrary.org/obo/UBERON_0005053) and children need some work.
