### ISSUE TITLE
unsatisfiable classes caused by zfa bridge

### ISSUE THREAD

**Issue by balhoff** [obophenotype/uberon#694]
Import together:
http://purl.obolibrary.org/obo/uberon/releases/2015-04-23/ext.owl
http://purl.obolibrary.org/obo/zfa/releases/2014-09-12/zfa.owl
http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-zfa/2015-04-23/uberon/bridge/uberon-bridge-to-zfa.owl

114 classes will be inferred by ELK to be equivalent to owl:Nothing.

**Comment by balhoff** [comment]
Does the Uberon project consider this to be a "bug", or just unavoidable sometimes?

**Comment by cmungall** [comment]
It depends. 

This is the current set of ssAOs that have to pass with each release - in theory. Sometimes to force a pass a disjointness axiom is moved to the pending-disjoints file, usually with a note to a tracker. If the disjointness is axiom is crucial then we retain the axiom and 'exile' the ssAO, as we did for XAO pending this ticket:

https://code.google.com/p/xenopus-anatomy-ontology/issues/detail?id=8

(looks like they fixed it, so we may be able to move xao back to the whitelist)

Now, I'm not totally sure why the above versions of zfa plus uberon are incoherent. It could be issues that are fixed. Or it could be something evading the checks. I will investigate.

Either way, it would probably be useful to make something involving stable IRIs more formal.

**Comment by cmungall** [comment]
Note to self: need to fix this before next release: https://code.google.com/p/cell-ontology/issues/detail?id=180

**Comment by cmungall** [comment]
For reference, here are the rules for constraint axioms that should go into the docs:

 * ones that are inviolable live in main ontology
 * ones that are parked for dealing with later go in pending-disjoints-core.obo
 * ones that are respected in uberon but violated in a ssAO go into pending-disjoints.obo
    * these do not 'see the light of day', but are ALWAYS used for validation WITHIN uberon as part of release process
    * these are also used as validation during the release process against "gold standard" ontologies. The set of gold standards can vary over time. Whether an ontology is gold or not, it should NOT cause incoherency when incorporated into a bridge ontology

Note that we will be slightly more lax when including disjointness axioms in uberon; some will be moved into pending to avoid incoherencies in public sets. However, we still
keep their value as part of the internal release process

**Comment by raymond91125** [comment]
@cmungall, has my commit in wbbt resolved the problem? https://github.com/raymond91125/Wao/commit/27eeee04b7bf494ee91140ded6982d28aee0474b

**Comment by cmungall** [comment]
I'm assuming it will (won't know for sure until I get a chance to try a new build). Will let you know if it doesn't
