### ISSUE TITLE
Identifying the subset of human relevant terms

### ISSUE THREAD

**Issue by dhimmel** [obophenotype/uberon#703]
For my project, I would like to identify the set of Uberon, and potentially Cell Ontology, terms that apply to humans. In other words, which structures exist in humans.

I posted the question on Thinklab -- an open science platform that pays people for feedback -- and @cmungall gave a [detailed and expert answer](https://think-lab.github.io/d/41/#276). I will continue the discussion on Thinklab, but wanted to post here in case others had the same question.

**Comment by fbastian** [comment]
Chris showed you how to generate a human subset of Uberon. From this, I also generate a csv files with a true/false status for all terms in Uberon, I find it more convenient to spot errors, see https://www.dropbox.com/s/r97fykcg68tvmux/ext_human_constraints.csv?dl=0

Chris mentioned two approaches, but IMO the best approach would be to stick to the first solution, and fix the incorrect taxon constraints in Uberon directly. If you are interested, we could share the effort, as this is something we want to do.

**Comment by dhimmel** [comment]
Thanks for generating the file -- it's a tsv rather than csv, which is [better](https://github.com/pydata/pandas/issues/10327#issue-87154775) and should be named as such.

I will look into how the *negative evidence method* compares with our (likely suboptimal) [implementation](http://thinklab.com/discussion/tissue-node/41#237) of the *positive evidence method*.

I will help in what ways I can, which will be pretty limited because I don't know much about anatomy and am inexperienced with OWL (although here I am looking to learn).

**Comment by dhimmel** [comment]
@fbastian, [take a look at my comparison](http://thinklab.com/discussion/tissue-node/41#279) of the *positive evidence* versus *no negative evidence* methods. For now, we plan to use your tsv file to determine whether a term is human appropriate. However, we identified 8 terms where the *no negative evidence* approach failed. These may be a good place to start regarding taxon constraints.

**Comment by fbastian** [comment]
Hey, this is really great! I wanted to use the "only_in_taxon" and "present_in_taxon" to infer "positive evidence", but never had the time. It's also nice to use the xrefs. 

I think @cmungall will easily find how to fix the taxon constraints for the 8 terms you identified.

**Comment by plasticfist** [comment]
bump.
I'm interested in reading how others are doing this, now.  Some of the best links in this thread are now dead (e.g. thinklab links are all dead)

Note: UBERON lists a file called human-view.obo but it is zero length (as are human-view.owl, and some other views)

**Comment by dhimmel** [comment]
> Some of the best links in this thread are now dead (e.g. thinklab links are all dead)

I updated those links to the current URLs. Thanks for the notification.

**Comment by anitacaron** [comment]
Hi @plasticfist, sorry for you not having found the human-view file before. 

You can find it here now http://purl.obolibrary.org/obo/uberon/subsets/human-view.obo (you need to copy and paste it in the address bar to be able to download it).

**Comment by dhimmel** [comment]
Ah nice. I see `subsets/human-view.obo` referenced on the [download page](https://uberon.github.io/downloads.html):

> ## Taxon Subsets
> These are constructed using Uberon [taxon constraints](https://github.com/obophenotype/uberon/wiki/Taxon-constraints)
>
> Developmental stages are included, and species-specific stages start and end ranges are encoded as [Taxon GCIs](https://github.com/obophenotype/uberon/wiki/Evolutionary-variability-GCIs)

@anitacaron out of curiosity, is the command / code to generate these subsets in the GitHub? I imagine the export happens automatically as part of the release process?
