### ISSUE TITLE
Taxon constraints in the different uberon versions

### ISSUE THREAD

**Issue by fbastian** [obophenotype/uberon#705]
Taxon constraints are not present in all files. For instance, there is no "only_in_taxon" relations in ext.obo, but they are present in ext.owl. 

Also, I noticed some variations in the inferences between ext.owl and composite-metazoan.owl: for instance, UBERON:0000023 "wing" is inferred to be unsatisfiable for human using ext.owl, but not when using composite-metazoan.owl. Would this be caused by some relations not removed by the SpeciesSubsetterUtil before inference?

**Comment by fbastian** [comment]
One of the problems is that, in composite-metazoan.owl, there is absolutely no EC axioms to owl:Nothing. They are present in ext.owl.

**Comment by fbastian** [comment]
EC axioms to owl:Nothing still absent from composite-metazoan.owl, and present in ext.owl.

**Comment by anitacaron** [comment]
We have a new [composite-metazoan.owl](http://purl.obolibrary.org/obo/uberon/composite-metazoan.owl) version and we don't release ext.owl anymore because it was the same as uberon.owl.
