### ISSUE TITLE
Image for pelvis UBERON:0002355

### ISSUE THREAD

**Issue by drseb** [obophenotype/uberon#720]
URL cannot be found https://upload.wikimedia.org/wikipedia/commons/f/fe/Gray242.png

Maybe it was meant to be: http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Gray242.png/200px-Gray242.png

Anyway, this only shows the bone of pelvis and I am not sure this what is meant for this class.

Seb

**Comment by cmungall** [comment]
Other bad images:

 * http://upload.wikimedia.org/wikipedia/commons/0/02/Cell_differentiation_gastrula.PNG
 * http://upload.wikimedia.org/wikipedia/commons/1/16/Gray968.png
 * http://upload.wikimedia.org/wikipedia/commons/1/17/Gray1078.png
 * http://upload.wikimedia.org/wikipedia/commons/2/20/Internal_iliac_branches.PNG
 * http://upload.wikimedia.org/wikipedia/commons/2/23/NMJ.jpg
 * http://upload.wikimedia.org/wikipedia/commons/2/25/Gray517.png
 * http://upload.wikimedia.org/wikipedia/commons/2/27/Gray1128.png
 * http://upload.wikimedia.org/wikipedia/commons/2/2d/Gray572.png
 * http://upload.wikimedia.org/wikipedia/commons/3/34/Femoral_triangle.gif
 * http://upload.wikimedia.org/wikipedia/commons/3/36/Biceps_%28PSF%29.jpg
 * http://upload.wikimedia.org/wikipedia/commons/3/36/Illu_capillary_microcirculation.jpg
 * http://upload.wikimedia.org/wikipedia/commons/3/38/Vastus_medialis.png
 * http://upload.wikimedia.org/wikipedia/commons/3/3f/Illu_pancrease.svg
 * http://upload.wikimedia.org/wikipedia/commons/4/45/Gray787.png
 * http://upload.wikimedia.org/wikipedia/commons/4/48/Illu_liver_gallbladder.jpg
 * http://upload.wikimedia.org/wikipedia/commons/4/4e/Ens.png
 * http://upload.wikimedia.org/wikipedia/commons/5/50/Mature_Graffian_follicle.jpg
 * http://upload.wikimedia.org/wikipedia/commons/5/52/Penis.svg
 * http://upload.wikimedia.org/wikipedia/commons/5/57/Illu_lower_extremity_muscles.jpg
 * http://upload.wikimedia.org/wikipedia/commons/6/65/Vestibular_system%27s_semicircular_canal-_a_cross-section.jpg
 * http://upload.wikimedia.org/wikipedia/commons/6/6a/Female_reproductive_system_lateral_nolabel.png
 * http://upload.wikimedia.org/wikipedia/commons/7/75/ECR-longus.png
 * http://upload.wikimedia.org/wikipedia/commons/7/77/Neocortex.jpg
 * http://upload.wikimedia.org/wikipedia/commons/8/82/Stomach_colon_rectum_diagram.svg
 * http://upload.wikimedia.org/wikipedia/commons/8/8c/Clitoris_inner_anatomy.gif
 * http://upload.wikimedia.org/wikipedia/commons/9/9a/Arcusanterioratlantis.png
 * http://upload.wikimedia.org/wikipedia/commons/9/9a/Knee_diagram.svg
 * http://upload.wikimedia.org/wikipedia/commons/9/9c/Gray1240.png
 * http://upload.wikimedia.org/wikipedia/commons/a/a5/Delphinschaedel.svg
 * http://upload.wikimedia.org/wikipedia/commons/b/b3/1543%2CVisalius%27OpticChiasma.jpg
 * http://upload.wikimedia.org/wikipedia/commons/b/b4/Venenwinkel.png
 * http://upload.wikimedia.org/wikipedia/commons/b/bd/Clitoris_outer_anatomy.gif
 * http://upload.wikimedia.org/wikipedia/commons/b/bd/Gray585.png
 * http://upload.wikimedia.org/wikipedia/commons/c/c3/Blastocyst.gif
 * http://upload.wikimedia.org/wikipedia/commons/c/c3/Tkanka_nablonkowa.png
 * http://upload.wikimedia.org/wikipedia/commons/c/c4/Parsbasilaris%28young%29.PNG
 * http://upload.wikimedia.org/wikipedia/commons/c/c7/Cochlea-crosssection.png
 * http://upload.wikimedia.org/wikipedia/commons/c/c7/Gray583.png
 * http://upload.wikimedia.org/wikipedia/commons/c/cb/Female_anatomy.png
 * http://upload.wikimedia.org/wikipedia/commons/d/d2/Gray906.png
 * http://upload.wikimedia.org/wikipedia/commons/d/da/Female_unshaved_genitalia.jpg
 * http://upload.wikimedia.org/wikipedia/commons/d/de/PhysiologieGlom%C3%A9rulaire.png
 * http://upload.wikimedia.org/wikipedia/commons/d/df/Gray36.png
 * http://upload.wikimedia.org/wikipedia/commons/e/e6/Aponeurosis.png
 * http://upload.wikimedia.org/wikipedia/commons/e/ea/Brachial_plexus_2.svg
 * http://upload.wikimedia.org/wikipedia/commons/e/ee/432px-Gray-back.PNG
 * http://upload.wikimedia.org/wikipedia/commons/f/f9/Gray512.svg
 * http://upload.wikimedia.org/wikipedia/commons/f/fe/Gray242.png
 * http://upload.wikimedia.org/wikipedia/en/thumb/3/3e/HairedHumanScrotum.png/200px-HairedHumanScrotum.png
 * http://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Foreskin2.jpg/200px-Foreskin2.jpg
