### ISSUE TITLE
Taxon constraints on UBERON_0000023 "wing"

### ISSUE THREAD

**Issue by fbastian** [obophenotype/uberon#721]
Currently, we only have: 

    id: UBERON_0000023
    name: wing
    relationship: only_in_taxon NCBITaxon:33213
    relationship: never_in_taxon NCBITaxon:9606

For Bgee, I would suggest the following, as it's not possible to use several only_in_taxon: 

    relationship: never_in_taxon NCBITaxon:9443 ! Primates
    relationship: never_in_taxon NCBITaxon:314147 ! Glyres
    relationship: never_in_taxon NCBITaxon:91561 ! Cetartiodactyla 
    relationship: never_in_taxon NCBITaxon:9263 ! Metatheria  
    relationship: never_in_taxon NCBITaxon:9254 ! Prototheria  
    relationship: never_in_taxon NCBITaxon:8457 ! Sauropsida  
    relationship: never_in_taxon NCBITaxon:8292 ! Amphibia (if you don't consider flying frogs as having wings)  
    relationship: never_in_taxon NCBITaxon:6231 ! Nematoda  
    relationship: never_in_taxon NCBITaxon:118072 ! Coelacanthimorpha  
    relationship: never_in_taxon NCBITaxon:7878 ! Dipnoi  
    relationship: never_in_taxon NCBITaxon:186634 ! Otomorpha (because sister taxon 'Euteleosteomorpha' contains 'flying fish'; do we consider that flying fish have wings?)

**Comment by cmungall** [comment]
Yeh, it's kind of arbitrary with all these gliding creatures. We use PATO to define wing, see: http://purl.obolibrary.org/obo/UBERON_0000023

appendage and (has quality some [aliform](http://purl.obolibrary.org/obo/PATO_0002236) )

which is defined as... "Shape quality inhering in a bearer by virtue of the bearer's being shaped like a wing"

circular!

There is an argument for obsoleting wing. I'm not sure it does anyone any good. It might still be useful to have a kb somewhere that says that this PATO quality inheres in this entity in taxa A, B, ... but that is phenoscape's job, and we traditionally have these axioms outside the ontology.

I think we would still want to precoordinate fin vs limb of course... the differentiae here is classically autopod presence?

Some others defined by pato morphology

```
[Term]
id: UBERON:0008291 ! down feather
intersection_of: UBERON:0000022 ! feather
intersection_of: has_quality PATO:0005010 ! plumose

[Term]
id: UBERON:0000023 ! wing
intersection_of: UBERON:0000026 ! appendage
intersection_of: has_quality PATO:0002236 ! aliform

[Term]
id: UBERON:0000024 ! forelimb wing
intersection_of: UBERON:0002102 ! forelimb
intersection_of: has_quality PATO:0002236 ! aliform

[Term]
id: UBERON:0000025 ! tube
intersection_of: UBERON:0004111 ! anatomical conduit
intersection_of: has_quality PATO:0002299 ! tubular

[Term]
id: UBERON:0003914 ! epithelial tube
intersection_of: UBERON:0000483 ! epithelium
intersection_of: has_quality PATO:0002299 ! tubular

[Term]
id: UBERON:0006314 ! bodily fluid ! bodily fluid
intersection_of: UBERON:0000463 ! organism substance
intersection_of: has_quality PATO:0001548 ! quality of a liquid

[Term]
id: UBERON:0034873 ! bodily gas ! bodily gas
intersection_of: UBERON:0000463 ! organism substance
intersection_of: has_quality PATO:0001547 ! quality of a gas

[Term]
id: UBERON:0000957 ! lamina
intersection_of: UBERON:0000479 ! tissue
intersection_of: has_quality PATO:0002124 ! laminar

[Term]
id: UBERON:0005160 ! vestigial structure
intersection_of: UBERON:0000061 ! anatomical structure
intersection_of: has_quality PATO:0000588 ! vestigial

[Term]
id: UBERON:0018135 ! fibrocollagenous connective tissue
intersection_of: UBERON:0011824 ! fibrous connective tissue
intersection_of: has_quality PATO:0002462 ! collagenous

[Term]
id: UBERON:4000013 ! mineralized skeletal tissue
intersection_of: UBERON:0004755 ! skeletal tissue
intersection_of: has_quality PATO:0002444 ! mineralized

[Term]
id: UBERON:0010064 ! open anatomical space
intersection_of: UBERON:0000464 ! anatomical space
intersection_of: has_quality PATO:0000610 ! open

[Term]
id: UBERON:0012467 ! enclosed anatomical space
intersection_of: UBERON:0000464 ! anatomical space
intersection_of: has_quality PATO:0000608 ! closed

[Term]
id: UBERON:0003915 ! endothelial tube ! endothelial tube
intersection_of: UBERON:0001986 ! endothelium
intersection_of: has_quality PATO:0002299 ! tubular

[Term]
id: UBERON:0006846 ! surface groove ! surface groove
intersection_of: UBERON:0003102 ! surface structure
intersection_of: has_quality PATO:0002255 ! grooved

[Term]
id: UBERON:0007499 ! epithelial sac ! epithelial sac
intersection_of: UBERON:0000483 ! epithelium
intersection_of: has_quality PATO:0001987 ! saccular

[Term]
id: UBERON:0009856 ! sac ! sac
intersection_of: UBERON:0000061 ! anatomical structure
intersection_of: has_quality PATO:0001987 ! saccular

[Term]
id: UBERON:0010879 ! tusk
intersection_of: UBERON:0001091 ! calcareous tooth
intersection_of: has_quality PATO:0001154 ! elongated
intersection_of: has_quality PATO:0001598 ! protruding

[Term]
id: UBERON:0015848 ! incisor tusk
intersection_of: UBERON:0001098 ! incisor tooth
intersection_of: has_quality PATO:0001154 ! elongated
intersection_of: has_quality PATO:0001598 ! protruding

[Term]
id: UBERON:0015849 ! canine tusk
intersection_of: UBERON:0003674 ! cuspid
intersection_of: has_quality PATO:0001154 ! elongated
intersection_of: has_quality PATO:0001598 ! protruding
```
