### ISSUE TITLE
skeletal muscles and musculoskeletal system

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#77]
- Musculoskeletal system should only include skeletal muscles
- Consider mereological sum class for 'set of all skeletal muscles'

See MA:
- is_a MA:0002405 ! postnatal mouse
  - po MA:0000003 ! organ system
    - is_a MA:0002418 ! musculoskeletal system
    - po MA:0002888 ! muscular system
    - po MA:0000165 ! set of skeletal muscles **\* 
    - is_a MA:0000514 ! trunk muscle
    - is_a MA:0000571 ! head or neck muscle
    - is_a MA:0000692 ! limb muscle
    - is_a MA:0000699 ! tail muscle

**Comment by cmungall** [comment]
See also https://github.com/monarch-initiative/mondo/issues/548

**Comment by paolaroncaglia** [comment]
The Mondo ticket linked above is still open (and blocked), so this Uberon ticket should probably be kept open.
