### ISSUE TITLE
Shreckstoff [ext]

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#87]
http://en.wikipedia.org/wiki/Schreckstoff

currently a subclass of chemical substance

This really belongs in CHEBI - make a chebi request and obsolete

**Comment by cmungall** [comment]
This is causing problems as we have now obsoleted 'cell part' which was our previous home for these kinds of things that didn't really belong.

**Comment by balhoff** [comment]
This is [in CHEBI now](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:133299). Should we just obsolete and put a replaced_by?
